Document: lmce-xml-data-handler-plugin
Title: Debian lmce-xml-data-handler-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-xml-data-handler-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-xml-data-handler-plugin/lmce-xml-data-handler-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-xml-data-handler-plugin/lmce-xml-data-handler-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-xml-data-handler-plugin/lmce-xml-data-handler-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-xml-data-handler-plugin/html/index.html
Files: /usr/share/doc/lmce-xml-data-handler-plugin/html/*.html
