SOURCES = charperiod.c

ifeq ($(ARCH),mipsel)
	CC = mipsel-linux-gcc
	CXX = mipsel-linux-g++
else
	CC = gcc
	CXX = g++
endif
CFLAGS = -O2

all: $(SOURCES:.c=)
	cp $+ ../bin

clean:
	rm -f $(SOURCES:.c=)
