Document: pluto-vdr-plugin
Title: Debian pluto-vdr-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-vdr-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-vdr-plugin/pluto-vdr-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-vdr-plugin/pluto-vdr-plugin.ps.gz

Format: text
Files: /usr/share/doc/pluto-vdr-plugin/pluto-vdr-plugin.text.gz

Format: HTML
Index: /usr/share/doc/pluto-vdr-plugin/html/index.html
Files: /usr/share/doc/pluto-vdr-plugin/html/*.html
