Document: updatemedia
Title: Debian updatemedia Manual
Author: <insert document author here>
Abstract: This manual describes what updatemedia is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/updatemedia/updatemedia.sgml.gz

Format: postscript
Files: /usr/share/doc/updatemedia/updatemedia.ps.gz

Format: text
Files: /usr/share/doc/updatemedia/updatemedia.text.gz

Format: HTML
Index: /usr/share/doc/updatemedia/html/index.html
Files: /usr/share/doc/updatemedia/html/*.html
