Document: lmce-dlna
Title: Debian lmce-dlna Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-dlna is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-dlna/lmce-dlna.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-dlna/lmce-dlna.ps.gz

Format: text
Files: /usr/share/doc/lmce-dlna/lmce-dlna.text.gz

Format: HTML
Index: /usr/share/doc/lmce-dlna/html/index.html
Files: /usr/share/doc/lmce-dlna/html/*.html
