Document: libbdcommon
Title: Debian libbdcommon Manual
Author: <insert document author here>
Abstract: This manual describes what libbdcommon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libbdcommon/libbdcommon.sgml.gz

Format: postscript
Files: /usr/share/doc/libbdcommon/libbdcommon.ps.gz

Format: text
Files: /usr/share/doc/libbdcommon/libbdcommon.text.gz

Format: HTML
Index: /usr/share/doc/libbdcommon/html/index.html
Files: /usr/share/doc/libbdcommon/html/*.html
