Document: libpluto-main
Title: Debian libpluto-main Manual
Author: <insert document author here>
Abstract: This manual describes what libpluto-main is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpluto-main/libpluto-main.sgml.gz

Format: postscript
Files: /usr/share/doc/libpluto-main/libpluto-main.ps.gz

Format: text
Files: /usr/share/doc/libpluto-main/libpluto-main.text.gz

Format: HTML
Index: /usr/share/doc/libpluto-main/html/index.html
Files: /usr/share/doc/libpluto-main/html/*.html
