Document: pluto-media
Title: Debian pluto-media Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-media is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-media/pluto-media.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-media/pluto-media.ps.gz

Format: text
Files: /usr/share/doc/pluto-media/pluto-media.text.gz

Format: HTML
Index: /usr/share/doc/pluto-media/html/index.html
Files: /usr/share/doc/pluto-media/html/*.html
