Document: pluto-pluto-media-db
Title: Debian pluto-pluto-media-db Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-pluto-media-db is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-pluto-media-db/pluto-pluto-media-db.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-pluto-media-db/pluto-pluto-media-db.ps.gz

Format: text
Files: /usr/share/doc/pluto-pluto-media-db/pluto-pluto-media-db.text.gz

Format: HTML
Index: /usr/share/doc/pluto-pluto-media-db/html/index.html
Files: /usr/share/doc/pluto-pluto-media-db/html/*.html
