#!/bin/bash
if [[ -n "$HEADER_FB_RPI2" ]]; then
	return 0
fi
HEADER_FB_RPI2=included

find_linux_root_device() {
	RDEV=$(mountpoint -d /)

	for file in $(find /dev -type b 2>/dev/null) ; 	do
		MAJOR=$(stat --printf="%t" "$file")
		MAJOR_DEC=$((16#$MAJOR))
		MINOR=$(stat --printf="%T" "$file")
		MINOR_DEC=$((16#$MINOR))

		if [ "$MAJOR_DEC:$MINOR_DEC" = "$RDEV" ]; then
			ROOTDEVICE="$file"
			break;
		fi
	done
	echo "$ROOTDEVICE"
}

firstboot_lmce_rpi2_preinst() {
	# Resize the SD Card to full size prior to doing anything else
	ret=2;
	if [ ! -f /etc/part_resized ] ; then
		StatsMessage "Resizing the SD Card partition"

		ROOT_PART=$(find_linux_root_device)
		PART_NUM=${ROOT_PART#/dev/mmcblk0p}
		PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d:)

		fdisk /dev/mmcblk0 <<EOF
p
d
$PART_NUM
n
p
$PART_NUM
$PART_START

w
EOF
		StatsMessage "Resizing partition done"
		echo "done" > /etc/part_resized

		# tell kernel about new partition table
		partprobe
		ret=$?

		if [ ret != 0 ] ; then
			reboot
		fi
	fi

	if [ -f /etc/part_resized ] ; then
		StatsMessage "Resizing the SD Card filesystem"
		ROOT_PART=$(find_linux_root_device)
		resize2fs $ROOT_PART
		ret=$?
		if [ ret != 0 ] ; then
			StatsMessage "Resizing filesystem failed!"
		else
			StatsMessage "Resizing filesystem completed"
			echo "done" > /etc/sd_resized
		fi
	fi
}


firstboot_lmce_rpi2_kernel() {
	apt-get -f -y install linux-headers-rpi2 linux-image-rpi2
	VerifyExitCode "Install linux image & headers for rpi2 failed" 

	return 0
}

firstboot_lmce_rpi2_postinst() {
	StatsMessage "Setting up rpi2 specific boot settings"

	. /usr/pluto/bin/Config_Ops.sh

	ConfSet "AVWizardOverride" "0"
	ConfSet "AVWizardDone" "1"
}
