#ifndef __Define_RemoteMapping_pschist_H__
#define __Define_RemoteMapping_pschist_H__


#define REMOTEMAPPING_PSCHIST_TABLE "RemoteMapping_pschist"
#define REMOTEMAPPING_PSCHIST_PK_REMOTEMAPPING_FIELD "PK_RemoteMapping"
#define REMOTEMAPPING_PSCHIST_PK_REMOTEMAPPING_TABLE_FIELD "RemoteMapping_pschist.PK_RemoteMapping"
#define REMOTEMAPPING_PSCHIST_DESCRIPTION_FIELD "Description"
#define REMOTEMAPPING_PSCHIST_DESCRIPTION_TABLE_FIELD "RemoteMapping_pschist.Description"
#define REMOTEMAPPING_PSCHIST_SCREENTYPE_FIELD "ScreenType"
#define REMOTEMAPPING_PSCHIST_SCREENTYPE_TABLE_FIELD "RemoteMapping_pschist.ScreenType"
#define REMOTEMAPPING_PSCHIST_REMOTELAYOUT_FIELD "RemoteLayout"
#define REMOTEMAPPING_PSCHIST_REMOTELAYOUT_TABLE_FIELD "RemoteMapping_pschist.RemoteLayout"
#define REMOTEMAPPING_PSCHIST_MAPPING_FIELD "Mapping"
#define REMOTEMAPPING_PSCHIST_MAPPING_TABLE_FIELD "RemoteMapping_pschist.Mapping"
#define REMOTEMAPPING_PSCHIST_PSC_ID_FIELD "psc_id"
#define REMOTEMAPPING_PSCHIST_PSC_ID_TABLE_FIELD "RemoteMapping_pschist.psc_id"
#define REMOTEMAPPING_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define REMOTEMAPPING_PSCHIST_PSC_BATCH_TABLE_FIELD "RemoteMapping_pschist.psc_batch"
#define REMOTEMAPPING_PSCHIST_PSC_USER_FIELD "psc_user"
#define REMOTEMAPPING_PSCHIST_PSC_USER_TABLE_FIELD "RemoteMapping_pschist.psc_user"
#define REMOTEMAPPING_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define REMOTEMAPPING_PSCHIST_PSC_FROZEN_TABLE_FIELD "RemoteMapping_pschist.psc_frozen"
#define REMOTEMAPPING_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define REMOTEMAPPING_PSCHIST_PSC_MOD_TABLE_FIELD "RemoteMapping_pschist.psc_mod"
#define REMOTEMAPPING_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define REMOTEMAPPING_PSCHIST_PSC_RESTRICT_TABLE_FIELD "RemoteMapping_pschist.psc_restrict"
#define REMOTEMAPPING_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define REMOTEMAPPING_PSCHIST_PSC_TOC_TABLE_FIELD "RemoteMapping_pschist.psc_toc"


#endif

