#ifndef __Define_Directory_pschmask_H__
#define __Define_Directory_pschmask_H__


#define DIRECTORY_PSCHMASK_TABLE "Directory_pschmask"
#define DIRECTORY_PSCHMASK_PK_DIRECTORY_FIELD "PK_Directory"
#define DIRECTORY_PSCHMASK_PK_DIRECTORY_TABLE_FIELD "Directory_pschmask.PK_Directory"
#define DIRECTORY_PSCHMASK_DESCRIPTION_FIELD "Description"
#define DIRECTORY_PSCHMASK_DESCRIPTION_TABLE_FIELD "Directory_pschmask.Description"
#define DIRECTORY_PSCHMASK_DEFINE_FIELD "Define"
#define DIRECTORY_PSCHMASK_DEFINE_TABLE_FIELD "Directory_pschmask.Define"
#define DIRECTORY_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DIRECTORY_PSCHMASK_PSC_ID_TABLE_FIELD "Directory_pschmask.psc_id"
#define DIRECTORY_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DIRECTORY_PSCHMASK_PSC_BATCH_TABLE_FIELD "Directory_pschmask.psc_batch"
#define DIRECTORY_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DIRECTORY_PSCHMASK_PSC_USER_TABLE_FIELD "Directory_pschmask.psc_user"
#define DIRECTORY_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DIRECTORY_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Directory_pschmask.psc_frozen"
#define DIRECTORY_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DIRECTORY_PSCHMASK_PSC_MOD_TABLE_FIELD "Directory_pschmask.psc_mod"
#define DIRECTORY_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DIRECTORY_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Directory_pschmask.psc_restrict"


#endif

