#ifndef __Define_OperatingSystem_pschmask_H__
#define __Define_OperatingSystem_pschmask_H__


#define OPERATINGSYSTEM_PSCHMASK_TABLE "OperatingSystem_pschmask"
#define OPERATINGSYSTEM_PSCHMASK_PK_OPERATINGSYSTEM_FIELD "PK_OperatingSystem"
#define OPERATINGSYSTEM_PSCHMASK_PK_OPERATINGSYSTEM_TABLE_FIELD "OperatingSystem_pschmask.PK_OperatingSystem"
#define OPERATINGSYSTEM_PSCHMASK_DESCRIPTION_FIELD "Description"
#define OPERATINGSYSTEM_PSCHMASK_DESCRIPTION_TABLE_FIELD "OperatingSystem_pschmask.Description"
#define OPERATINGSYSTEM_PSCHMASK_DEFINE_FIELD "Define"
#define OPERATINGSYSTEM_PSCHMASK_DEFINE_TABLE_FIELD "OperatingSystem_pschmask.Define"
#define OPERATINGSYSTEM_PSCHMASK_PSC_ID_FIELD "psc_id"
#define OPERATINGSYSTEM_PSCHMASK_PSC_ID_TABLE_FIELD "OperatingSystem_pschmask.psc_id"
#define OPERATINGSYSTEM_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define OPERATINGSYSTEM_PSCHMASK_PSC_BATCH_TABLE_FIELD "OperatingSystem_pschmask.psc_batch"
#define OPERATINGSYSTEM_PSCHMASK_PSC_USER_FIELD "psc_user"
#define OPERATINGSYSTEM_PSCHMASK_PSC_USER_TABLE_FIELD "OperatingSystem_pschmask.psc_user"
#define OPERATINGSYSTEM_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define OPERATINGSYSTEM_PSCHMASK_PSC_FROZEN_TABLE_FIELD "OperatingSystem_pschmask.psc_frozen"
#define OPERATINGSYSTEM_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define OPERATINGSYSTEM_PSCHMASK_PSC_MOD_TABLE_FIELD "OperatingSystem_pschmask.psc_mod"
#define OPERATINGSYSTEM_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define OPERATINGSYSTEM_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "OperatingSystem_pschmask.psc_restrict"


#endif

