#ifndef __Define_MediaType_Broadcast_pschmask_H__
#define __Define_MediaType_Broadcast_pschmask_H__


#define MEDIATYPE_BROADCAST_PSCHMASK_TABLE "MediaType_Broadcast_pschmask"
#define MEDIATYPE_BROADCAST_PSCHMASK_FK_MEDIATYPE_FIELD "FK_MediaType"
#define MEDIATYPE_BROADCAST_PSCHMASK_FK_MEDIATYPE_TABLE_FIELD "MediaType_Broadcast_pschmask.FK_MediaType"
#define MEDIATYPE_BROADCAST_PSCHMASK_FK_BROADCAST_FIELD "FK_Broadcast"
#define MEDIATYPE_BROADCAST_PSCHMASK_FK_BROADCAST_TABLE_FIELD "MediaType_Broadcast_pschmask.FK_Broadcast"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_ID_FIELD "psc_id"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_ID_TABLE_FIELD "MediaType_Broadcast_pschmask.psc_id"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_BATCH_TABLE_FIELD "MediaType_Broadcast_pschmask.psc_batch"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_USER_FIELD "psc_user"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_USER_TABLE_FIELD "MediaType_Broadcast_pschmask.psc_user"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_FROZEN_TABLE_FIELD "MediaType_Broadcast_pschmask.psc_frozen"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_MOD_TABLE_FIELD "MediaType_Broadcast_pschmask.psc_mod"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define MEDIATYPE_BROADCAST_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "MediaType_Broadcast_pschmask.psc_restrict"


#endif

