#ifndef __Define_Firewall_pschmask_H__
#define __Define_Firewall_pschmask_H__


#define FIREWALL_PSCHMASK_TABLE "Firewall_pschmask"
#define FIREWALL_PSCHMASK_PK_FIREWALL_FIELD "PK_Firewall"
#define FIREWALL_PSCHMASK_PK_FIREWALL_TABLE_FIELD "Firewall_pschmask.PK_Firewall"
#define FIREWALL_PSCHMASK_PROTOCOL_FIELD "Protocol"
#define FIREWALL_PSCHMASK_PROTOCOL_TABLE_FIELD "Firewall_pschmask.Protocol"
#define FIREWALL_PSCHMASK_SOURCEPORT_FIELD "SourcePort"
#define FIREWALL_PSCHMASK_SOURCEPORT_TABLE_FIELD "Firewall_pschmask.SourcePort"
#define FIREWALL_PSCHMASK_SOURCEPORTEND_FIELD "SourcePortEnd"
#define FIREWALL_PSCHMASK_SOURCEPORTEND_TABLE_FIELD "Firewall_pschmask.SourcePortEnd"
#define FIREWALL_PSCHMASK_DESTINATIONPORT_FIELD "DestinationPort"
#define FIREWALL_PSCHMASK_DESTINATIONPORT_TABLE_FIELD "Firewall_pschmask.DestinationPort"
#define FIREWALL_PSCHMASK_SOURCEIP_FIELD "SourceIP"
#define FIREWALL_PSCHMASK_SOURCEIP_TABLE_FIELD "Firewall_pschmask.SourceIP"
#define FIREWALL_PSCHMASK_DESTINATIONIP_FIELD "DestinationIP"
#define FIREWALL_PSCHMASK_DESTINATIONIP_TABLE_FIELD "Firewall_pschmask.DestinationIP"
#define FIREWALL_PSCHMASK_RULETYPE_FIELD "RuleType"
#define FIREWALL_PSCHMASK_RULETYPE_TABLE_FIELD "Firewall_pschmask.RuleType"
#define FIREWALL_PSCHMASK_PSC_ID_FIELD "psc_id"
#define FIREWALL_PSCHMASK_PSC_ID_TABLE_FIELD "Firewall_pschmask.psc_id"
#define FIREWALL_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define FIREWALL_PSCHMASK_PSC_BATCH_TABLE_FIELD "Firewall_pschmask.psc_batch"
#define FIREWALL_PSCHMASK_PSC_USER_FIELD "psc_user"
#define FIREWALL_PSCHMASK_PSC_USER_TABLE_FIELD "Firewall_pschmask.psc_user"
#define FIREWALL_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define FIREWALL_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Firewall_pschmask.psc_frozen"
#define FIREWALL_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define FIREWALL_PSCHMASK_PSC_MOD_TABLE_FIELD "Firewall_pschmask.psc_mod"
#define FIREWALL_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define FIREWALL_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Firewall_pschmask.psc_restrict"


#endif

