#ifndef __Define_Skin_pschist_H__
#define __Define_Skin_pschist_H__


#define SKIN_PSCHIST_TABLE "Skin_pschist"
#define SKIN_PSCHIST_PK_SKIN_FIELD "PK_Skin"
#define SKIN_PSCHIST_PK_SKIN_TABLE_FIELD "Skin_pschist.PK_Skin"
#define SKIN_PSCHIST_DESCRIPTION_FIELD "Description"
#define SKIN_PSCHIST_DESCRIPTION_TABLE_FIELD "Skin_pschist.Description"
#define SKIN_PSCHIST_DEFINE_FIELD "Define"
#define SKIN_PSCHIST_DEFINE_TABLE_FIELD "Skin_pschist.Define"
#define SKIN_PSCHIST_FK_UI_FIELD "FK_UI"
#define SKIN_PSCHIST_FK_UI_TABLE_FIELD "Skin_pschist.FK_UI"
#define SKIN_PSCHIST_MERGESTANDARDVARIATION_FIELD "MergeStandardVariation"
#define SKIN_PSCHIST_MERGESTANDARDVARIATION_TABLE_FIELD "Skin_pschist.MergeStandardVariation"
#define SKIN_PSCHIST_DATASUBDIRECTORY_FIELD "DataSubdirectory"
#define SKIN_PSCHIST_DATASUBDIRECTORY_TABLE_FIELD "Skin_pschist.DataSubdirectory"
#define SKIN_PSCHIST_FK_STYLE_FIELD "FK_Style"
#define SKIN_PSCHIST_FK_STYLE_TABLE_FIELD "Skin_pschist.FK_Style"
#define SKIN_PSCHIST_FK_SKIN_TEXTPLACEMENT_FIELD "FK_Skin_TextPlacement"
#define SKIN_PSCHIST_FK_SKIN_TEXTPLACEMENT_TABLE_FIELD "Skin_pschist.FK_Skin_TextPlacement"
#define SKIN_PSCHIST_DRAWTEXTBEFORECHILDREN_FIELD "DrawTextBeforeChildren"
#define SKIN_PSCHIST_DRAWTEXTBEFORECHILDREN_TABLE_FIELD "Skin_pschist.DrawTextBeforeChildren"
#define SKIN_PSCHIST_FK_STABILITYSTATUS_FIELD "FK_StabilityStatus"
#define SKIN_PSCHIST_FK_STABILITYSTATUS_TABLE_FIELD "Skin_pschist.FK_StabilityStatus"
#define SKIN_PSCHIST_FK_SCREEN_MAINMENU_FIELD "FK_Screen_MainMenu"
#define SKIN_PSCHIST_FK_SCREEN_MAINMENU_TABLE_FIELD "Skin_pschist.FK_Screen_MainMenu"
#define SKIN_PSCHIST_FK_SCREEN_SLEEPING_FIELD "FK_Screen_Sleeping"
#define SKIN_PSCHIST_FK_SCREEN_SLEEPING_TABLE_FIELD "Skin_pschist.FK_Screen_Sleeping"
#define SKIN_PSCHIST_FK_SCREEN_SCREENSAVER_FIELD "FK_Screen_ScreenSaver"
#define SKIN_PSCHIST_FK_SCREEN_SCREENSAVER_TABLE_FIELD "Skin_pschist.FK_Screen_ScreenSaver"
#define SKIN_PSCHIST_FK_PACKAGE_FIELD "FK_Package"
#define SKIN_PSCHIST_FK_PACKAGE_TABLE_FIELD "Skin_pschist.FK_Package"
#define SKIN_PSCHIST_PSC_ID_FIELD "psc_id"
#define SKIN_PSCHIST_PSC_ID_TABLE_FIELD "Skin_pschist.psc_id"
#define SKIN_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define SKIN_PSCHIST_PSC_BATCH_TABLE_FIELD "Skin_pschist.psc_batch"
#define SKIN_PSCHIST_PSC_USER_FIELD "psc_user"
#define SKIN_PSCHIST_PSC_USER_TABLE_FIELD "Skin_pschist.psc_user"
#define SKIN_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define SKIN_PSCHIST_PSC_FROZEN_TABLE_FIELD "Skin_pschist.psc_frozen"
#define SKIN_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define SKIN_PSCHIST_PSC_MOD_TABLE_FIELD "Skin_pschist.psc_mod"
#define SKIN_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define SKIN_PSCHIST_PSC_TOC_TABLE_FIELD "Skin_pschist.psc_toc"
#define SKIN_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define SKIN_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Skin_pschist.psc_restrict"


#endif

