#ifndef __Define_Household_Installation_pschmask_H__
#define __Define_Household_Installation_pschmask_H__


#define HOUSEHOLD_INSTALLATION_PSCHMASK_TABLE "Household_Installation_pschmask"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_FK_HOUSEHOLD_FIELD "FK_Household"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_FK_HOUSEHOLD_TABLE_FIELD "Household_Installation_pschmask.FK_Household"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_FK_INSTALLATION_FIELD "FK_Installation"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_FK_INSTALLATION_TABLE_FIELD "Household_Installation_pschmask.FK_Installation"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_ID_FIELD "psc_id"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_ID_TABLE_FIELD "Household_Installation_pschmask.psc_id"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_BATCH_TABLE_FIELD "Household_Installation_pschmask.psc_batch"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_USER_FIELD "psc_user"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_USER_TABLE_FIELD "Household_Installation_pschmask.psc_user"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Household_Installation_pschmask.psc_frozen"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_MOD_TABLE_FIELD "Household_Installation_pschmask.psc_mod"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define HOUSEHOLD_INSTALLATION_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Household_Installation_pschmask.psc_restrict"


#endif

