#ifndef __Define_HouseMode_pschmask_H__
#define __Define_HouseMode_pschmask_H__


#define HOUSEMODE_PSCHMASK_TABLE "HouseMode_pschmask"
#define HOUSEMODE_PSCHMASK_PK_HOUSEMODE_FIELD "PK_HouseMode"
#define HOUSEMODE_PSCHMASK_PK_HOUSEMODE_TABLE_FIELD "HouseMode_pschmask.PK_HouseMode"
#define HOUSEMODE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define HOUSEMODE_PSCHMASK_DESCRIPTION_TABLE_FIELD "HouseMode_pschmask.Description"
#define HOUSEMODE_PSCHMASK_DEFINE_FIELD "Define"
#define HOUSEMODE_PSCHMASK_DEFINE_TABLE_FIELD "HouseMode_pschmask.Define"
#define HOUSEMODE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define HOUSEMODE_PSCHMASK_PSC_ID_TABLE_FIELD "HouseMode_pschmask.psc_id"
#define HOUSEMODE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define HOUSEMODE_PSCHMASK_PSC_BATCH_TABLE_FIELD "HouseMode_pschmask.psc_batch"
#define HOUSEMODE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define HOUSEMODE_PSCHMASK_PSC_USER_TABLE_FIELD "HouseMode_pschmask.psc_user"
#define HOUSEMODE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define HOUSEMODE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "HouseMode_pschmask.psc_frozen"
#define HOUSEMODE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define HOUSEMODE_PSCHMASK_PSC_MOD_TABLE_FIELD "HouseMode_pschmask.psc_mod"
#define HOUSEMODE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define HOUSEMODE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "HouseMode_pschmask.psc_restrict"


#endif

