#ifndef __Define_Orbiter_Variable_pschist_H__
#define __Define_Orbiter_Variable_pschist_H__


#define ORBITER_VARIABLE_PSCHIST_TABLE "Orbiter_Variable_pschist"
#define ORBITER_VARIABLE_PSCHIST_FK_ORBITER_FIELD "FK_Orbiter"
#define ORBITER_VARIABLE_PSCHIST_FK_ORBITER_TABLE_FIELD "Orbiter_Variable_pschist.FK_Orbiter"
#define ORBITER_VARIABLE_PSCHIST_FK_VARIABLE_FIELD "FK_Variable"
#define ORBITER_VARIABLE_PSCHIST_FK_VARIABLE_TABLE_FIELD "Orbiter_Variable_pschist.FK_Variable"
#define ORBITER_VARIABLE_PSCHIST_VALUE_FIELD "Value"
#define ORBITER_VARIABLE_PSCHIST_VALUE_TABLE_FIELD "Orbiter_Variable_pschist.Value"
#define ORBITER_VARIABLE_PSCHIST_PSC_ID_FIELD "psc_id"
#define ORBITER_VARIABLE_PSCHIST_PSC_ID_TABLE_FIELD "Orbiter_Variable_pschist.psc_id"
#define ORBITER_VARIABLE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define ORBITER_VARIABLE_PSCHIST_PSC_BATCH_TABLE_FIELD "Orbiter_Variable_pschist.psc_batch"
#define ORBITER_VARIABLE_PSCHIST_PSC_USER_FIELD "psc_user"
#define ORBITER_VARIABLE_PSCHIST_PSC_USER_TABLE_FIELD "Orbiter_Variable_pschist.psc_user"
#define ORBITER_VARIABLE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define ORBITER_VARIABLE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Orbiter_Variable_pschist.psc_frozen"
#define ORBITER_VARIABLE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define ORBITER_VARIABLE_PSCHIST_PSC_MOD_TABLE_FIELD "Orbiter_Variable_pschist.psc_mod"
#define ORBITER_VARIABLE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define ORBITER_VARIABLE_PSCHIST_PSC_TOC_TABLE_FIELD "Orbiter_Variable_pschist.psc_toc"
#define ORBITER_VARIABLE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define ORBITER_VARIABLE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Orbiter_Variable_pschist.psc_restrict"


#endif

