#ifndef __Define_Licensing_pschmask_H__
#define __Define_Licensing_pschmask_H__


#define LICENSING_PSCHMASK_TABLE "Licensing_pschmask"
#define LICENSING_PSCHMASK_PK_LICENSING_FIELD "PK_Licensing"
#define LICENSING_PSCHMASK_PK_LICENSING_TABLE_FIELD "Licensing_pschmask.PK_Licensing"
#define LICENSING_PSCHMASK_DESCRIPTION_FIELD "Description"
#define LICENSING_PSCHMASK_DESCRIPTION_TABLE_FIELD "Licensing_pschmask.Description"
#define LICENSING_PSCHMASK_REQUIRESPAYMENT_FIELD "RequiresPayment"
#define LICENSING_PSCHMASK_REQUIRESPAYMENT_TABLE_FIELD "Licensing_pschmask.RequiresPayment"
#define LICENSING_PSCHMASK_RECOMMENDSPAYMENT_FIELD "RecommendsPayment"
#define LICENSING_PSCHMASK_RECOMMENDSPAYMENT_TABLE_FIELD "Licensing_pschmask.RecommendsPayment"
#define LICENSING_PSCHMASK_FREETRIAL_FIELD "FreeTrial"
#define LICENSING_PSCHMASK_FREETRIAL_TABLE_FIELD "Licensing_pschmask.FreeTrial"
#define LICENSING_PSCHMASK_PSC_ID_FIELD "psc_id"
#define LICENSING_PSCHMASK_PSC_ID_TABLE_FIELD "Licensing_pschmask.psc_id"
#define LICENSING_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define LICENSING_PSCHMASK_PSC_BATCH_TABLE_FIELD "Licensing_pschmask.psc_batch"
#define LICENSING_PSCHMASK_PSC_USER_FIELD "psc_user"
#define LICENSING_PSCHMASK_PSC_USER_TABLE_FIELD "Licensing_pschmask.psc_user"
#define LICENSING_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define LICENSING_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Licensing_pschmask.psc_frozen"
#define LICENSING_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define LICENSING_PSCHMASK_PSC_MOD_TABLE_FIELD "Licensing_pschmask.psc_mod"
#define LICENSING_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define LICENSING_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Licensing_pschmask.psc_restrict"


#endif

