#ifndef __Define_Broadcast_pschmask_H__
#define __Define_Broadcast_pschmask_H__


#define BROADCAST_PSCHMASK_TABLE "Broadcast_pschmask"
#define BROADCAST_PSCHMASK_PK_BROADCAST_FIELD "PK_Broadcast"
#define BROADCAST_PSCHMASK_PK_BROADCAST_TABLE_FIELD "Broadcast_pschmask.PK_Broadcast"
#define BROADCAST_PSCHMASK_DESCRIPTION_FIELD "Description"
#define BROADCAST_PSCHMASK_DESCRIPTION_TABLE_FIELD "Broadcast_pschmask.Description"
#define BROADCAST_PSCHMASK_EXTENSIONS_FIELD "Extensions"
#define BROADCAST_PSCHMASK_EXTENSIONS_TABLE_FIELD "Broadcast_pschmask.Extensions"
#define BROADCAST_PSCHMASK_PSC_ID_FIELD "psc_id"
#define BROADCAST_PSCHMASK_PSC_ID_TABLE_FIELD "Broadcast_pschmask.psc_id"
#define BROADCAST_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define BROADCAST_PSCHMASK_PSC_BATCH_TABLE_FIELD "Broadcast_pschmask.psc_batch"
#define BROADCAST_PSCHMASK_PSC_USER_FIELD "psc_user"
#define BROADCAST_PSCHMASK_PSC_USER_TABLE_FIELD "Broadcast_pschmask.psc_user"
#define BROADCAST_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define BROADCAST_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Broadcast_pschmask.psc_frozen"
#define BROADCAST_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define BROADCAST_PSCHMASK_PSC_MOD_TABLE_FIELD "Broadcast_pschmask.psc_mod"
#define BROADCAST_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define BROADCAST_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Broadcast_pschmask.psc_restrict"


#endif

