#ifndef __Define_psc_dce_batdet_H__
#define __Define_psc_dce_batdet_H__


#define PSC_DCE_BATDET_TABLE "psc_dce_batdet"
#define PSC_DCE_BATDET_PK_PSC_DCE_BATDET_FIELD "PK_psc_dce_batdet"
#define PSC_DCE_BATDET_PK_PSC_DCE_BATDET_TABLE_FIELD "psc_dce_batdet.PK_psc_dce_batdet"
#define PSC_DCE_BATDET_FK_PSC_DCE_BATHDR_FIELD "FK_psc_dce_bathdr"
#define PSC_DCE_BATDET_FK_PSC_DCE_BATHDR_TABLE_FIELD "psc_dce_batdet.FK_psc_dce_bathdr"
#define PSC_DCE_BATDET_TABLENAME_FIELD "Tablename"
#define PSC_DCE_BATDET_TABLENAME_TABLE_FIELD "psc_dce_batdet.Tablename"
#define PSC_DCE_BATDET_NEW_FIELD "New"
#define PSC_DCE_BATDET_NEW_TABLE_FIELD "psc_dce_batdet.New"
#define PSC_DCE_BATDET_DELETED_FIELD "Deleted"
#define PSC_DCE_BATDET_DELETED_TABLE_FIELD "psc_dce_batdet.Deleted"
#define PSC_DCE_BATDET_MODIFIED_FIELD "Modified"
#define PSC_DCE_BATDET_MODIFIED_TABLE_FIELD "psc_dce_batdet.Modified"
#define PSC_DCE_BATDET_FK_PSC_DCE_BATHDR_ORIG_FIELD "FK_psc_dce_bathdr_orig"
#define PSC_DCE_BATDET_FK_PSC_DCE_BATHDR_ORIG_TABLE_FIELD "psc_dce_batdet.FK_psc_dce_bathdr_orig"
#define PSC_DCE_BATDET_FK_PSC_DCE_BATHDR_AUTH_FIELD "FK_psc_dce_bathdr_auth"
#define PSC_DCE_BATDET_FK_PSC_DCE_BATHDR_AUTH_TABLE_FIELD "psc_dce_batdet.FK_psc_dce_bathdr_auth"
#define PSC_DCE_BATDET_FK_PSC_DCE_BATHDR_UNAUTH_FIELD "FK_psc_dce_bathdr_unauth"
#define PSC_DCE_BATDET_FK_PSC_DCE_BATHDR_UNAUTH_TABLE_FIELD "psc_dce_batdet.FK_psc_dce_bathdr_unauth"


#endif

