#ifndef __Define_PnpProtocol_pschist_H__
#define __Define_PnpProtocol_pschist_H__


#define PNPPROTOCOL_PSCHIST_TABLE "PnpProtocol_pschist"
#define PNPPROTOCOL_PSCHIST_PK_PNPPROTOCOL_FIELD "PK_PnpProtocol"
#define PNPPROTOCOL_PSCHIST_PK_PNPPROTOCOL_TABLE_FIELD "PnpProtocol_pschist.PK_PnpProtocol"
#define PNPPROTOCOL_PSCHIST_DESCRIPTION_FIELD "Description"
#define PNPPROTOCOL_PSCHIST_DESCRIPTION_TABLE_FIELD "PnpProtocol_pschist.Description"
#define PNPPROTOCOL_PSCHIST_DEFINE_FIELD "Define"
#define PNPPROTOCOL_PSCHIST_DEFINE_TABLE_FIELD "PnpProtocol_pschist.Define"
#define PNPPROTOCOL_PSCHIST_PSC_ID_FIELD "psc_id"
#define PNPPROTOCOL_PSCHIST_PSC_ID_TABLE_FIELD "PnpProtocol_pschist.psc_id"
#define PNPPROTOCOL_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PNPPROTOCOL_PSCHIST_PSC_BATCH_TABLE_FIELD "PnpProtocol_pschist.psc_batch"
#define PNPPROTOCOL_PSCHIST_PSC_USER_FIELD "psc_user"
#define PNPPROTOCOL_PSCHIST_PSC_USER_TABLE_FIELD "PnpProtocol_pschist.psc_user"
#define PNPPROTOCOL_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PNPPROTOCOL_PSCHIST_PSC_FROZEN_TABLE_FIELD "PnpProtocol_pschist.psc_frozen"
#define PNPPROTOCOL_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PNPPROTOCOL_PSCHIST_PSC_MOD_TABLE_FIELD "PnpProtocol_pschist.psc_mod"
#define PNPPROTOCOL_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PNPPROTOCOL_PSCHIST_PSC_RESTRICT_TABLE_FIELD "PnpProtocol_pschist.psc_restrict"
#define PNPPROTOCOL_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PNPPROTOCOL_PSCHIST_PSC_TOC_TABLE_FIELD "PnpProtocol_pschist.psc_toc"


#endif

