#ifndef __Define_DeviceData_H__
#define __Define_DeviceData_H__

#define DEVICEDATA_Device_CONST 1
#define DEVICEDATA_Path_CONST 2
#define DEVICEDATA_PK_Users_CONST 3
#define DEVICEDATA_Current_Screen_CONST 4
#define DEVICEDATA_MediaDescriptor_CONST 5
#define DEVICEDATA_Drive_CONST 6
#define DEVICEDATA_PK_Distro_CONST 7
#define DEVICEDATA_Development_CONST 8
#define DEVICEDATA_Diskless_Boot_CONST 9
#define DEVICEDATA_Floorplan_Info_CONST 10
#define DEVICEDATA_PK_FloorplanObjectType_CONST 11
#define DEVICEDATA_PortChannel_Number_CONST 12
#define DEVICEDATA_InputOrOutput_CONST 18
#define DEVICEDATA_Default_State_CONST 19
#define DEVICEDATA_No_Effects_CONST 20
#define DEVICEDATA_PK_Skin_CONST 24
#define DEVICEDATA_PK_Size_CONST 25
#define DEVICEDATA_PK_Language_CONST 26
#define DEVICEDATA_FK_EntertainArea_CONST 27
#define DEVICEDATA_DHCP_CONST 28
#define DEVICEDATA_PhoneType_CONST 29
#define DEVICEDATA_PhoneNumber_CONST 31
#define DEVICEDATA_Network_Interfaces_CONST 32
#define DEVICEDATA_Alert_CONST 33
#define DEVICEDATA_Mobile_Orbiter_Notification_CONST 34
#define DEVICEDATA_Other_Phone_Notifications_CONST 35
#define DEVICEDATA_Neighbors_to_Call_CONST 36
#define DEVICEDATA_COM_Port_on_PC_CONST 37
#define DEVICEDATA_PK_HouseMode_CONST 38
#define DEVICEDATA_Delay_CONST 39
#define DEVICEDATA_Name_CONST 40
#define DEVICEDATA_Update_Name_CONST 41
#define DEVICEDATA_File_Name_and_Path_CONST 42
#define DEVICEDATA_Communication_file_CONST 43
#define DEVICEDATA_MythTV_PVR_Input_CONST 44
#define DEVICEDATA_EK_AlertType_CONST 45
#define DEVICEDATA_Kick_Start_CD_CONST 46
#define DEVICEDATA_Type_CONST 47
#define DEVICEDATA_Number_of_ports_CONST 48
#define DEVICEDATA_Video_Standard_CONST 49
#define DEVICEDATA_Motion_Option_CONST 51
#define DEVICEDATA_Sensitivity_CONST 52
#define DEVICEDATA_Noise_CONST 53
#define DEVICEDATA_Purge_Period_CONST 54
#define DEVICEDATA_Remote_Type_CONST 55
#define DEVICEDATA_Timeout_CONST 56
#define DEVICEDATA_CacheFolder_CONST 57
#define DEVICEDATA_CacheSize_CONST 58
#define DEVICEDATA_Configuration_CONST 59
#define DEVICEDATA_Mapping_CONST 60
#define DEVICEDATA_ThreshHold_CONST 61
#define DEVICEDATA_Serial_Port_CONST 62
#define DEVICEDATA_Use_OCG_Format_CONST 64
#define DEVICEDATA_Video_Input_Type_CONST 65
#define DEVICEDATA_Connector_CONST 68
#define DEVICEDATA_TCP_Port_CONST 69
#define DEVICEDATA_Idle_Delay_CONST 70
#define DEVICEDATA_Output_Speaker_arrangement_CONST 71
#define DEVICEDATA_VideoFrameInterval_CONST 72
#define DEVICEDATA_Alsa_Output_Device_CONST 74
#define DEVICEDATA_ImageQuality_CONST 75
#define DEVICEDATA_COM_Port_ParityBitStop_CONST 76
#define DEVICEDATA_PK_Device_CONST 77
#define DEVICEDATA_COM_Port_BaudRate_CONST 78
#define DEVICEDATA_Area_CONST 80
#define DEVICEDATA_Channel_CONST 81
#define DEVICEDATA_Leave_Monitor_on_for_OSD_CONST 84

#define DEVICEDATA_TABLE "DeviceData"
#define DEVICEDATA_PK_DEVICEDATA_FIELD "PK_DeviceData"
#define DEVICEDATA_PK_DEVICEDATA_TABLE_FIELD "DeviceData.PK_DeviceData"
#define DEVICEDATA_DESCRIPTION_FIELD "Description"
#define DEVICEDATA_DESCRIPTION_TABLE_FIELD "DeviceData.Description"
#define DEVICEDATA_DEFINE_FIELD "Define"
#define DEVICEDATA_DEFINE_TABLE_FIELD "DeviceData.Define"
#define DEVICEDATA_FK_PARAMETERTYPE_FIELD "FK_ParameterType"
#define DEVICEDATA_FK_PARAMETERTYPE_TABLE_FIELD "DeviceData.FK_ParameterType"
#define DEVICEDATA_PSC_ID_FIELD "psc_id"
#define DEVICEDATA_PSC_ID_TABLE_FIELD "DeviceData.psc_id"
#define DEVICEDATA_PSC_BATCH_FIELD "psc_batch"
#define DEVICEDATA_PSC_BATCH_TABLE_FIELD "DeviceData.psc_batch"
#define DEVICEDATA_PSC_USER_FIELD "psc_user"
#define DEVICEDATA_PSC_USER_TABLE_FIELD "DeviceData.psc_user"
#define DEVICEDATA_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICEDATA_PSC_FROZEN_TABLE_FIELD "DeviceData.psc_frozen"
#define DEVICEDATA_PSC_MOD_FIELD "psc_mod"
#define DEVICEDATA_PSC_MOD_TABLE_FIELD "DeviceData.psc_mod"


#endif

