#ifndef __Define_DeviceData_pschist_H__
#define __Define_DeviceData_pschist_H__


#define DEVICEDATA_PSCHIST_TABLE "DeviceData_pschist"
#define DEVICEDATA_PSCHIST_PK_DEVICEDATA_FIELD "PK_DeviceData"
#define DEVICEDATA_PSCHIST_PK_DEVICEDATA_TABLE_FIELD "DeviceData_pschist.PK_DeviceData"
#define DEVICEDATA_PSCHIST_DESCRIPTION_FIELD "Description"
#define DEVICEDATA_PSCHIST_DESCRIPTION_TABLE_FIELD "DeviceData_pschist.Description"
#define DEVICEDATA_PSCHIST_DEFINE_FIELD "Define"
#define DEVICEDATA_PSCHIST_DEFINE_TABLE_FIELD "DeviceData_pschist.Define"
#define DEVICEDATA_PSCHIST_FK_PARAMETERTYPE_FIELD "FK_ParameterType"
#define DEVICEDATA_PSCHIST_FK_PARAMETERTYPE_TABLE_FIELD "DeviceData_pschist.FK_ParameterType"
#define DEVICEDATA_PSCHIST_PSC_ID_FIELD "psc_id"
#define DEVICEDATA_PSCHIST_PSC_ID_TABLE_FIELD "DeviceData_pschist.psc_id"
#define DEVICEDATA_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DEVICEDATA_PSCHIST_PSC_BATCH_TABLE_FIELD "DeviceData_pschist.psc_batch"
#define DEVICEDATA_PSCHIST_PSC_USER_FIELD "psc_user"
#define DEVICEDATA_PSCHIST_PSC_USER_TABLE_FIELD "DeviceData_pschist.psc_user"
#define DEVICEDATA_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICEDATA_PSCHIST_PSC_FROZEN_TABLE_FIELD "DeviceData_pschist.psc_frozen"
#define DEVICEDATA_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DEVICEDATA_PSCHIST_PSC_MOD_TABLE_FIELD "DeviceData_pschist.psc_mod"
#define DEVICEDATA_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DEVICEDATA_PSCHIST_PSC_TOC_TABLE_FIELD "DeviceData_pschist.psc_toc"
#define DEVICEDATA_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICEDATA_PSCHIST_PSC_RESTRICT_TABLE_FIELD "DeviceData_pschist.psc_restrict"


#endif

