#ifndef __Define_DeviceGroup_pschmask_H__
#define __Define_DeviceGroup_pschmask_H__


#define DEVICEGROUP_PSCHMASK_TABLE "DeviceGroup_pschmask"
#define DEVICEGROUP_PSCHMASK_PK_DEVICEGROUP_FIELD "PK_DeviceGroup"
#define DEVICEGROUP_PSCHMASK_PK_DEVICEGROUP_TABLE_FIELD "DeviceGroup_pschmask.PK_DeviceGroup"
#define DEVICEGROUP_PSCHMASK_FK_DEVICEGROUP_PARENT_FIELD "FK_DeviceGroup_Parent"
#define DEVICEGROUP_PSCHMASK_FK_DEVICEGROUP_PARENT_TABLE_FIELD "DeviceGroup_pschmask.FK_DeviceGroup_Parent"
#define DEVICEGROUP_PSCHMASK_FK_INSTALLATION_FIELD "FK_Installation"
#define DEVICEGROUP_PSCHMASK_FK_INSTALLATION_TABLE_FIELD "DeviceGroup_pschmask.FK_Installation"
#define DEVICEGROUP_PSCHMASK_DESCRIPTION_FIELD "Description"
#define DEVICEGROUP_PSCHMASK_DESCRIPTION_TABLE_FIELD "DeviceGroup_pschmask.Description"
#define DEVICEGROUP_PSCHMASK_TYPE_FIELD "Type"
#define DEVICEGROUP_PSCHMASK_TYPE_TABLE_FIELD "DeviceGroup_pschmask.Type"
#define DEVICEGROUP_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DEVICEGROUP_PSCHMASK_PSC_ID_TABLE_FIELD "DeviceGroup_pschmask.psc_id"
#define DEVICEGROUP_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DEVICEGROUP_PSCHMASK_PSC_BATCH_TABLE_FIELD "DeviceGroup_pschmask.psc_batch"
#define DEVICEGROUP_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DEVICEGROUP_PSCHMASK_PSC_USER_TABLE_FIELD "DeviceGroup_pschmask.psc_user"
#define DEVICEGROUP_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICEGROUP_PSCHMASK_PSC_FROZEN_TABLE_FIELD "DeviceGroup_pschmask.psc_frozen"
#define DEVICEGROUP_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DEVICEGROUP_PSCHMASK_PSC_MOD_TABLE_FIELD "DeviceGroup_pschmask.psc_mod"
#define DEVICEGROUP_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICEGROUP_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "DeviceGroup_pschmask.psc_restrict"


#endif

