#ifndef __Define_DeviceData_pschmask_H__
#define __Define_DeviceData_pschmask_H__


#define DEVICEDATA_PSCHMASK_TABLE "DeviceData_pschmask"
#define DEVICEDATA_PSCHMASK_PK_DEVICEDATA_FIELD "PK_DeviceData"
#define DEVICEDATA_PSCHMASK_PK_DEVICEDATA_TABLE_FIELD "DeviceData_pschmask.PK_DeviceData"
#define DEVICEDATA_PSCHMASK_DESCRIPTION_FIELD "Description"
#define DEVICEDATA_PSCHMASK_DESCRIPTION_TABLE_FIELD "DeviceData_pschmask.Description"
#define DEVICEDATA_PSCHMASK_DEFINE_FIELD "Define"
#define DEVICEDATA_PSCHMASK_DEFINE_TABLE_FIELD "DeviceData_pschmask.Define"
#define DEVICEDATA_PSCHMASK_FK_PARAMETERTYPE_FIELD "FK_ParameterType"
#define DEVICEDATA_PSCHMASK_FK_PARAMETERTYPE_TABLE_FIELD "DeviceData_pschmask.FK_ParameterType"
#define DEVICEDATA_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DEVICEDATA_PSCHMASK_PSC_ID_TABLE_FIELD "DeviceData_pschmask.psc_id"
#define DEVICEDATA_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DEVICEDATA_PSCHMASK_PSC_BATCH_TABLE_FIELD "DeviceData_pschmask.psc_batch"
#define DEVICEDATA_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DEVICEDATA_PSCHMASK_PSC_USER_TABLE_FIELD "DeviceData_pschmask.psc_user"
#define DEVICEDATA_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICEDATA_PSCHMASK_PSC_FROZEN_TABLE_FIELD "DeviceData_pschmask.psc_frozen"
#define DEVICEDATA_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DEVICEDATA_PSCHMASK_PSC_MOD_TABLE_FIELD "DeviceData_pschmask.psc_mod"
#define DEVICEDATA_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICEDATA_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "DeviceData_pschmask.psc_restrict"


#endif

