#ifndef __Define_VertAlignment_pschmask_H__
#define __Define_VertAlignment_pschmask_H__


#define VERTALIGNMENT_PSCHMASK_TABLE "VertAlignment_pschmask"
#define VERTALIGNMENT_PSCHMASK_PK_VERTALIGNMENT_FIELD "PK_VertAlignment"
#define VERTALIGNMENT_PSCHMASK_PK_VERTALIGNMENT_TABLE_FIELD "VertAlignment_pschmask.PK_VertAlignment"
#define VERTALIGNMENT_PSCHMASK_DESCRIPTION_FIELD "Description"
#define VERTALIGNMENT_PSCHMASK_DESCRIPTION_TABLE_FIELD "VertAlignment_pschmask.Description"
#define VERTALIGNMENT_PSCHMASK_DEFINE_FIELD "Define"
#define VERTALIGNMENT_PSCHMASK_DEFINE_TABLE_FIELD "VertAlignment_pschmask.Define"
#define VERTALIGNMENT_PSCHMASK_PSC_ID_FIELD "psc_id"
#define VERTALIGNMENT_PSCHMASK_PSC_ID_TABLE_FIELD "VertAlignment_pschmask.psc_id"
#define VERTALIGNMENT_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define VERTALIGNMENT_PSCHMASK_PSC_BATCH_TABLE_FIELD "VertAlignment_pschmask.psc_batch"
#define VERTALIGNMENT_PSCHMASK_PSC_USER_FIELD "psc_user"
#define VERTALIGNMENT_PSCHMASK_PSC_USER_TABLE_FIELD "VertAlignment_pschmask.psc_user"
#define VERTALIGNMENT_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define VERTALIGNMENT_PSCHMASK_PSC_FROZEN_TABLE_FIELD "VertAlignment_pschmask.psc_frozen"
#define VERTALIGNMENT_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define VERTALIGNMENT_PSCHMASK_PSC_MOD_TABLE_FIELD "VertAlignment_pschmask.psc_mod"
#define VERTALIGNMENT_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define VERTALIGNMENT_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "VertAlignment_pschmask.psc_restrict"


#endif

