#ifndef __Define_Installation_H__
#define __Define_Installation_H__


#define INSTALLATION_TABLE "Installation"
#define INSTALLATION_PK_INSTALLATION_FIELD "PK_Installation"
#define INSTALLATION_PK_INSTALLATION_TABLE_FIELD "Installation.PK_Installation"
#define INSTALLATION_DESCRIPTION_FIELD "Description"
#define INSTALLATION_DESCRIPTION_TABLE_FIELD "Installation.Description"
#define INSTALLATION_NAME_FIELD "Name"
#define INSTALLATION_NAME_TABLE_FIELD "Installation.Name"
#define INSTALLATION_ADDRESS_FIELD "Address"
#define INSTALLATION_ADDRESS_TABLE_FIELD "Installation.Address"
#define INSTALLATION_CITY_FIELD "City"
#define INSTALLATION_CITY_TABLE_FIELD "Installation.City"
#define INSTALLATION_STATE_FIELD "State"
#define INSTALLATION_STATE_TABLE_FIELD "Installation.State"
#define INSTALLATION_ZIP_FIELD "Zip"
#define INSTALLATION_ZIP_TABLE_FIELD "Installation.Zip"
#define INSTALLATION_FK_COUNTRY_FIELD "FK_Country"
#define INSTALLATION_FK_COUNTRY_TABLE_FIELD "Installation.FK_Country"
#define INSTALLATION_ACTIVATIONCODE_FIELD "ActivationCode"
#define INSTALLATION_ACTIVATIONCODE_TABLE_FIELD "Installation.ActivationCode"
#define INSTALLATION_LASTSTATUS_FIELD "LastStatus"
#define INSTALLATION_LASTSTATUS_TABLE_FIELD "Installation.LastStatus"
#define INSTALLATION_LASTALIVE_FIELD "LastAlive"
#define INSTALLATION_LASTALIVE_TABLE_FIELD "Installation.LastAlive"
#define INSTALLATION_ISACTIVE_FIELD "isActive"
#define INSTALLATION_ISACTIVE_TABLE_FIELD "Installation.isActive"
#define INSTALLATION_FK_VERSION_FIELD "FK_Version"
#define INSTALLATION_FK_VERSION_TABLE_FIELD "Installation.FK_Version"
#define INSTALLATION_ISMONITORED_FIELD "isMonitored"
#define INSTALLATION_ISMONITORED_TABLE_FIELD "Installation.isMonitored"
#define INSTALLATION_FK_REPOSITORYTYPE_SOURCE_FIELD "FK_RepositoryType_Source"
#define INSTALLATION_FK_REPOSITORYTYPE_SOURCE_TABLE_FIELD "Installation.FK_RepositoryType_Source"
#define INSTALLATION_FK_REPOSITORYTYPE_BINARIES_FIELD "FK_RepositoryType_Binaries"
#define INSTALLATION_FK_REPOSITORYTYPE_BINARIES_TABLE_FIELD "Installation.FK_RepositoryType_Binaries"
#define INSTALLATION_PSC_ID_FIELD "psc_id"
#define INSTALLATION_PSC_ID_TABLE_FIELD "Installation.psc_id"
#define INSTALLATION_PSC_BATCH_FIELD "psc_batch"
#define INSTALLATION_PSC_BATCH_TABLE_FIELD "Installation.psc_batch"
#define INSTALLATION_PSC_USER_FIELD "psc_user"
#define INSTALLATION_PSC_USER_TABLE_FIELD "Installation.psc_user"
#define INSTALLATION_PSC_FROZEN_FIELD "psc_frozen"
#define INSTALLATION_PSC_FROZEN_TABLE_FIELD "Installation.psc_frozen"
#define INSTALLATION_PSC_MOD_FIELD "psc_mod"
#define INSTALLATION_PSC_MOD_TABLE_FIELD "Installation.psc_mod"
#define INSTALLATION_PSC_RESTRICT_FIELD "psc_restrict"
#define INSTALLATION_PSC_RESTRICT_TABLE_FIELD "Installation.psc_restrict"


#endif

