#ifndef __Define_Screen_pschmask_H__
#define __Define_Screen_pschmask_H__


#define SCREEN_PSCHMASK_TABLE "Screen_pschmask"
#define SCREEN_PSCHMASK_PK_SCREEN_FIELD "PK_Screen"
#define SCREEN_PSCHMASK_PK_SCREEN_TABLE_FIELD "Screen_pschmask.PK_Screen"
#define SCREEN_PSCHMASK_DESCRIPTION_FIELD "Description"
#define SCREEN_PSCHMASK_DESCRIPTION_TABLE_FIELD "Screen_pschmask.Description"
#define SCREEN_PSCHMASK_DEFINE_FIELD "Define"
#define SCREEN_PSCHMASK_DEFINE_TABLE_FIELD "Screen_pschmask.Define"
#define SCREEN_PSCHMASK_COMMENTS_FIELD "Comments"
#define SCREEN_PSCHMASK_COMMENTS_TABLE_FIELD "Screen_pschmask.Comments"
#define SCREEN_PSCHMASK_SPECIALHANDINGRECOMMENDED_FIELD "SpecialHandingRecommended"
#define SCREEN_PSCHMASK_SPECIALHANDINGRECOMMENDED_TABLE_FIELD "Screen_pschmask.SpecialHandingRecommended"
#define SCREEN_PSCHMASK_ALWAYSINCLUDE_FIELD "AlwaysInclude"
#define SCREEN_PSCHMASK_ALWAYSINCLUDE_TABLE_FIELD "Screen_pschmask.AlwaysInclude"
#define SCREEN_PSCHMASK_PRESERVECALLBACKS_FIELD "PreserveCallBacks"
#define SCREEN_PSCHMASK_PRESERVECALLBACKS_TABLE_FIELD "Screen_pschmask.PreserveCallBacks"
#define SCREEN_PSCHMASK_GOBACKTOSCREEN_FIELD "GoBackToScreen"
#define SCREEN_PSCHMASK_GOBACKTOSCREEN_TABLE_FIELD "Screen_pschmask.GoBackToScreen"
#define SCREEN_PSCHMASK_ALLOWINTERRUPTIONS_FIELD "AllowInterruptions"
#define SCREEN_PSCHMASK_ALLOWINTERRUPTIONS_TABLE_FIELD "Screen_pschmask.AllowInterruptions"
#define SCREEN_PSCHMASK_PSC_ID_FIELD "psc_id"
#define SCREEN_PSCHMASK_PSC_ID_TABLE_FIELD "Screen_pschmask.psc_id"
#define SCREEN_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define SCREEN_PSCHMASK_PSC_BATCH_TABLE_FIELD "Screen_pschmask.psc_batch"
#define SCREEN_PSCHMASK_PSC_USER_FIELD "psc_user"
#define SCREEN_PSCHMASK_PSC_USER_TABLE_FIELD "Screen_pschmask.psc_user"
#define SCREEN_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define SCREEN_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Screen_pschmask.psc_frozen"
#define SCREEN_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define SCREEN_PSCHMASK_PSC_MOD_TABLE_FIELD "Screen_pschmask.psc_mod"
#define SCREEN_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define SCREEN_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Screen_pschmask.psc_restrict"


#endif

