#ifndef __Define_Device_MRU_pschist_H__
#define __Define_Device_MRU_pschist_H__


#define DEVICE_MRU_PSCHIST_TABLE "Device_MRU_pschist"
#define DEVICE_MRU_PSCHIST_PK_DEVICE_MRU_FIELD "PK_Device_MRU"
#define DEVICE_MRU_PSCHIST_PK_DEVICE_MRU_TABLE_FIELD "Device_MRU_pschist.PK_Device_MRU"
#define DEVICE_MRU_PSCHIST_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_MRU_PSCHIST_FK_DEVICE_TABLE_FIELD "Device_MRU_pschist.FK_Device"
#define DEVICE_MRU_PSCHIST_FILENAME_FIELD "Filename"
#define DEVICE_MRU_PSCHIST_FILENAME_TABLE_FIELD "Device_MRU_pschist.Filename"
#define DEVICE_MRU_PSCHIST_LASTUSED_FIELD "LastUsed"
#define DEVICE_MRU_PSCHIST_LASTUSED_TABLE_FIELD "Device_MRU_pschist.LastUsed"
#define DEVICE_MRU_PSCHIST_PSC_ID_FIELD "psc_id"
#define DEVICE_MRU_PSCHIST_PSC_ID_TABLE_FIELD "Device_MRU_pschist.psc_id"
#define DEVICE_MRU_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_MRU_PSCHIST_PSC_BATCH_TABLE_FIELD "Device_MRU_pschist.psc_batch"
#define DEVICE_MRU_PSCHIST_PSC_USER_FIELD "psc_user"
#define DEVICE_MRU_PSCHIST_PSC_USER_TABLE_FIELD "Device_MRU_pschist.psc_user"
#define DEVICE_MRU_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_MRU_PSCHIST_PSC_FROZEN_TABLE_FIELD "Device_MRU_pschist.psc_frozen"
#define DEVICE_MRU_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DEVICE_MRU_PSCHIST_PSC_MOD_TABLE_FIELD "Device_MRU_pschist.psc_mod"
#define DEVICE_MRU_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_MRU_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Device_MRU_pschist.psc_restrict"
#define DEVICE_MRU_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DEVICE_MRU_PSCHIST_PSC_TOC_TABLE_FIELD "Device_MRU_pschist.psc_toc"


#endif

