#ifndef __Define_Package_Version_pschmask_H__
#define __Define_Package_Version_pschmask_H__


#define PACKAGE_VERSION_PSCHMASK_TABLE "Package_Version_pschmask"
#define PACKAGE_VERSION_PSCHMASK_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_VERSION_PSCHMASK_FK_PACKAGE_TABLE_FIELD "Package_Version_pschmask.FK_Package"
#define PACKAGE_VERSION_PSCHMASK_FK_VERSION_FIELD "FK_Version"
#define PACKAGE_VERSION_PSCHMASK_FK_VERSION_TABLE_FIELD "Package_Version_pschmask.FK_Version"
#define PACKAGE_VERSION_PSCHMASK_COMMENTS_FIELD "Comments"
#define PACKAGE_VERSION_PSCHMASK_COMMENTS_TABLE_FIELD "Package_Version_pschmask.Comments"
#define PACKAGE_VERSION_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PACKAGE_VERSION_PSCHMASK_PSC_ID_TABLE_FIELD "Package_Version_pschmask.psc_id"
#define PACKAGE_VERSION_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_VERSION_PSCHMASK_PSC_BATCH_TABLE_FIELD "Package_Version_pschmask.psc_batch"
#define PACKAGE_VERSION_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PACKAGE_VERSION_PSCHMASK_PSC_USER_TABLE_FIELD "Package_Version_pschmask.psc_user"
#define PACKAGE_VERSION_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_VERSION_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Package_Version_pschmask.psc_frozen"
#define PACKAGE_VERSION_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_VERSION_PSCHMASK_PSC_MOD_TABLE_FIELD "Package_Version_pschmask.psc_mod"
#define PACKAGE_VERSION_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_VERSION_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Package_Version_pschmask.psc_restrict"


#endif

