/*
     Copyright (C) 2004 Pluto, Inc., a Florida Corporation

     www.plutohome.com

     Phone: +1 (877) 758-8648
 

     This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License.
     This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
     of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     See the GNU General Public License for more details.

*/
#ifndef __Define_DeviceTemplate_DeviceTemplate_ControlledVia_Pipe_H__
#define __Define_DeviceTemplate_DeviceTemplate_ControlledVia_Pipe_H__


#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_TABLE "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_FK_DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_FIELD "FK_DeviceTemplate_DeviceTemplate_ControlledVia"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_FK_DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.FK_DeviceTemplate_DeviceTemplate_ControlledVia"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_FK_PIPE_FIELD "FK_Pipe"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_FK_PIPE_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.FK_Pipe"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_FK_COMMAND_INPUT_FIELD "FK_Command_Input"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_FK_COMMAND_INPUT_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.FK_Command_Input"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_FK_COMMAND_OUTPUT_FIELD "FK_Command_Output"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_FK_COMMAND_OUTPUT_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.FK_Command_Output"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_TOCHILD_FIELD "ToChild"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_TOCHILD_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.ToChild"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_ID_FIELD "psc_id"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_ID_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.psc_id"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_BATCH_FIELD "psc_batch"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_BATCH_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.psc_batch"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_USER_FIELD "psc_user"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_USER_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.psc_user"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_FROZEN_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.psc_frozen"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_MOD_FIELD "psc_mod"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_MOD_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.psc_mod"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICETEMPLATE_DEVICETEMPLATE_CONTROLLEDVIA_PIPE_PSC_RESTRICT_TABLE_FIELD "DeviceTemplate_DeviceTemplate_ControlledVia_Pipe.psc_restrict"


#endif

