#ifndef __Define_Household_Installation_pschist_H__
#define __Define_Household_Installation_pschist_H__


#define HOUSEHOLD_INSTALLATION_PSCHIST_TABLE "Household_Installation_pschist"
#define HOUSEHOLD_INSTALLATION_PSCHIST_FK_HOUSEHOLD_FIELD "FK_Household"
#define HOUSEHOLD_INSTALLATION_PSCHIST_FK_HOUSEHOLD_TABLE_FIELD "Household_Installation_pschist.FK_Household"
#define HOUSEHOLD_INSTALLATION_PSCHIST_FK_INSTALLATION_FIELD "FK_Installation"
#define HOUSEHOLD_INSTALLATION_PSCHIST_FK_INSTALLATION_TABLE_FIELD "Household_Installation_pschist.FK_Installation"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_ID_FIELD "psc_id"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_ID_TABLE_FIELD "Household_Installation_pschist.psc_id"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_BATCH_TABLE_FIELD "Household_Installation_pschist.psc_batch"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_USER_FIELD "psc_user"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_USER_TABLE_FIELD "Household_Installation_pschist.psc_user"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_FROZEN_TABLE_FIELD "Household_Installation_pschist.psc_frozen"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_MOD_TABLE_FIELD "Household_Installation_pschist.psc_mod"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_TOC_TABLE_FIELD "Household_Installation_pschist.psc_toc"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define HOUSEHOLD_INSTALLATION_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Household_Installation_pschist.psc_restrict"


#endif

