#ifndef __Define_Device_Device_Pipe_pschist_H__
#define __Define_Device_Device_Pipe_pschist_H__


#define DEVICE_DEVICE_PIPE_PSCHIST_TABLE "Device_Device_Pipe_pschist"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_DEVICE_FROM_FIELD "FK_Device_From"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_DEVICE_FROM_TABLE_FIELD "Device_Device_Pipe_pschist.FK_Device_From"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_DEVICE_TO_FIELD "FK_Device_To"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_DEVICE_TO_TABLE_FIELD "Device_Device_Pipe_pschist.FK_Device_To"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_PIPE_FIELD "FK_Pipe"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_PIPE_TABLE_FIELD "Device_Device_Pipe_pschist.FK_Pipe"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_COMMAND_INPUT_FIELD "FK_Command_Input"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_COMMAND_INPUT_TABLE_FIELD "Device_Device_Pipe_pschist.FK_Command_Input"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_COMMAND_OUTPUT_FIELD "FK_Command_Output"
#define DEVICE_DEVICE_PIPE_PSCHIST_FK_COMMAND_OUTPUT_TABLE_FIELD "Device_Device_Pipe_pschist.FK_Command_Output"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_ID_FIELD "psc_id"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_ID_TABLE_FIELD "Device_Device_Pipe_pschist.psc_id"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_BATCH_TABLE_FIELD "Device_Device_Pipe_pschist.psc_batch"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_USER_FIELD "psc_user"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_USER_TABLE_FIELD "Device_Device_Pipe_pschist.psc_user"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Device_Device_Pipe_pschist.psc_frozen"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_MOD_TABLE_FIELD "Device_Device_Pipe_pschist.psc_mod"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_TOC_TABLE_FIELD "Device_Device_Pipe_pschist.psc_toc"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_DEVICE_PIPE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Device_Device_Pipe_pschist.psc_restrict"


#endif

