#ifndef __Define_EventParameter_H__
#define __Define_EventParameter_H__

#define EVENTPARAMETER_X_Position_CONST 1
#define EVENTPARAMETER_Y_Position_CONST 2
#define EVENTPARAMETER_FK_MediaType_CONST 3
#define EVENTPARAMETER_MRL_CONST 4
#define EVENTPARAMETER_Mac_Address_CONST 5
#define EVENTPARAMETER_Signal_Strength_CONST 6
#define EVENTPARAMETER_ID_CONST 7
#define EVENTPARAMETER_Version_CONST 8
#define EVENTPARAMETER_Stream_ID_CONST 9
#define EVENTPARAMETER_OnOff_CONST 10
#define EVENTPARAMETER_ConnectionFailed_CONST 11
#define EVENTPARAMETER_Error_Message_CONST 12
#define EVENTPARAMETER_Text_CONST 13
#define EVENTPARAMETER_PK_Orbiter_CONST 14
#define EVENTPARAMETER_MediaDescription_CONST 15
#define EVENTPARAMETER_SectionDescription_CONST 16
#define EVENTPARAMETER_SynposisDescription_CONST 17
#define EVENTPARAMETER_PhoneNumber_CONST 18
#define EVENTPARAMETER_CommandID_CONST 19
#define EVENTPARAMETER_Result_CONST 20
#define EVENTPARAMETER_Message_CONST 21
#define EVENTPARAMETER_PhoneExtension_CONST 22
#define EVENTPARAMETER_PhoneCallID_CONST 23
#define EVENTPARAMETER_PhoneCallerID_CONST 24
#define EVENTPARAMETER_Tripped_CONST 25
#define EVENTPARAMETER_PK_Device_CONST 26
#define EVENTPARAMETER_PK_Room_CONST 27
#define EVENTPARAMETER_IP_Address_CONST 28
#define EVENTPARAMETER_MythTV_ChannelID_CONST 29

#define EVENTPARAMETER_TABLE "EventParameter"
#define EVENTPARAMETER_PK_EVENTPARAMETER_FIELD "PK_EventParameter"
#define EVENTPARAMETER_PK_EVENTPARAMETER_TABLE_FIELD "EventParameter.PK_EventParameter"
#define EVENTPARAMETER_DESCRIPTION_FIELD "Description"
#define EVENTPARAMETER_DESCRIPTION_TABLE_FIELD "EventParameter.Description"
#define EVENTPARAMETER_DEFINE_FIELD "Define"
#define EVENTPARAMETER_DEFINE_TABLE_FIELD "EventParameter.Define"
#define EVENTPARAMETER_COMMENTS_FIELD "Comments"
#define EVENTPARAMETER_COMMENTS_TABLE_FIELD "EventParameter.Comments"
#define EVENTPARAMETER_FK_PARAMETERTYPE_FIELD "FK_ParameterType"
#define EVENTPARAMETER_FK_PARAMETERTYPE_TABLE_FIELD "EventParameter.FK_ParameterType"
#define EVENTPARAMETER_PSC_ID_FIELD "psc_id"
#define EVENTPARAMETER_PSC_ID_TABLE_FIELD "EventParameter.psc_id"
#define EVENTPARAMETER_PSC_BATCH_FIELD "psc_batch"
#define EVENTPARAMETER_PSC_BATCH_TABLE_FIELD "EventParameter.psc_batch"
#define EVENTPARAMETER_PSC_USER_FIELD "psc_user"
#define EVENTPARAMETER_PSC_USER_TABLE_FIELD "EventParameter.psc_user"
#define EVENTPARAMETER_PSC_FROZEN_FIELD "psc_frozen"
#define EVENTPARAMETER_PSC_FROZEN_TABLE_FIELD "EventParameter.psc_frozen"
#define EVENTPARAMETER_PSC_MOD_FIELD "psc_mod"
#define EVENTPARAMETER_PSC_MOD_TABLE_FIELD "EventParameter.psc_mod"


#endif

