#ifndef __Define_FloorplanType_pschist_H__
#define __Define_FloorplanType_pschist_H__


#define FLOORPLANTYPE_PSCHIST_TABLE "FloorplanType_pschist"
#define FLOORPLANTYPE_PSCHIST_PK_FLOORPLANTYPE_FIELD "PK_FloorplanType"
#define FLOORPLANTYPE_PSCHIST_PK_FLOORPLANTYPE_TABLE_FIELD "FloorplanType_pschist.PK_FloorplanType"
#define FLOORPLANTYPE_PSCHIST_DESCRIPTION_FIELD "Description"
#define FLOORPLANTYPE_PSCHIST_DESCRIPTION_TABLE_FIELD "FloorplanType_pschist.Description"
#define FLOORPLANTYPE_PSCHIST_DEFINE_FIELD "Define"
#define FLOORPLANTYPE_PSCHIST_DEFINE_TABLE_FIELD "FloorplanType_pschist.Define"
#define FLOORPLANTYPE_PSCHIST_PSC_ID_FIELD "psc_id"
#define FLOORPLANTYPE_PSCHIST_PSC_ID_TABLE_FIELD "FloorplanType_pschist.psc_id"
#define FLOORPLANTYPE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define FLOORPLANTYPE_PSCHIST_PSC_BATCH_TABLE_FIELD "FloorplanType_pschist.psc_batch"
#define FLOORPLANTYPE_PSCHIST_PSC_USER_FIELD "psc_user"
#define FLOORPLANTYPE_PSCHIST_PSC_USER_TABLE_FIELD "FloorplanType_pschist.psc_user"
#define FLOORPLANTYPE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define FLOORPLANTYPE_PSCHIST_PSC_FROZEN_TABLE_FIELD "FloorplanType_pschist.psc_frozen"
#define FLOORPLANTYPE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define FLOORPLANTYPE_PSCHIST_PSC_MOD_TABLE_FIELD "FloorplanType_pschist.psc_mod"
#define FLOORPLANTYPE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define FLOORPLANTYPE_PSCHIST_PSC_TOC_TABLE_FIELD "FloorplanType_pschist.psc_toc"
#define FLOORPLANTYPE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define FLOORPLANTYPE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "FloorplanType_pschist.psc_restrict"


#endif

