#ifndef __Define_SetupStep_pschmask_H__
#define __Define_SetupStep_pschmask_H__


#define SETUPSTEP_PSCHMASK_TABLE "SetupStep_pschmask"
#define SETUPSTEP_PSCHMASK_PK_SETUPSTEP_FIELD "PK_SetupStep"
#define SETUPSTEP_PSCHMASK_PK_SETUPSTEP_TABLE_FIELD "SetupStep_pschmask.PK_SetupStep"
#define SETUPSTEP_PSCHMASK_FK_INSTALLATION_FIELD "FK_Installation"
#define SETUPSTEP_PSCHMASK_FK_INSTALLATION_TABLE_FIELD "SetupStep_pschmask.FK_Installation"
#define SETUPSTEP_PSCHMASK_FK_PAGESETUP_FIELD "FK_PageSetup"
#define SETUPSTEP_PSCHMASK_FK_PAGESETUP_TABLE_FIELD "SetupStep_pschmask.FK_PageSetup"
#define SETUPSTEP_PSCHMASK_PSC_ID_FIELD "psc_id"
#define SETUPSTEP_PSCHMASK_PSC_ID_TABLE_FIELD "SetupStep_pschmask.psc_id"
#define SETUPSTEP_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define SETUPSTEP_PSCHMASK_PSC_BATCH_TABLE_FIELD "SetupStep_pschmask.psc_batch"
#define SETUPSTEP_PSCHMASK_PSC_USER_FIELD "psc_user"
#define SETUPSTEP_PSCHMASK_PSC_USER_TABLE_FIELD "SetupStep_pschmask.psc_user"
#define SETUPSTEP_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define SETUPSTEP_PSCHMASK_PSC_FROZEN_TABLE_FIELD "SetupStep_pschmask.psc_frozen"
#define SETUPSTEP_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define SETUPSTEP_PSCHMASK_PSC_MOD_TABLE_FIELD "SetupStep_pschmask.psc_mod"
#define SETUPSTEP_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define SETUPSTEP_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "SetupStep_pschmask.psc_restrict"


#endif

