#ifndef __Define_Package_Package_pschmask_H__
#define __Define_Package_Package_pschmask_H__


#define PACKAGE_PACKAGE_PSCHMASK_TABLE "Package_Package_pschmask"
#define PACKAGE_PACKAGE_PSCHMASK_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_PACKAGE_PSCHMASK_FK_PACKAGE_TABLE_FIELD "Package_Package_pschmask.FK_Package"
#define PACKAGE_PACKAGE_PSCHMASK_FK_PACKAGE_DEPENDSON_FIELD "FK_Package_DependsOn"
#define PACKAGE_PACKAGE_PSCHMASK_FK_PACKAGE_DEPENDSON_TABLE_FIELD "Package_Package_pschmask.FK_Package_DependsOn"
#define PACKAGE_PACKAGE_PSCHMASK_ONLYTOBUILD_FIELD "OnlyToBuild"
#define PACKAGE_PACKAGE_PSCHMASK_ONLYTOBUILD_TABLE_FIELD "Package_Package_pschmask.OnlyToBuild"
#define PACKAGE_PACKAGE_PSCHMASK_PREDEPENDENCY_FIELD "PreDependency"
#define PACKAGE_PACKAGE_PSCHMASK_PREDEPENDENCY_TABLE_FIELD "Package_Package_pschmask.PreDependency"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_ID_TABLE_FIELD "Package_Package_pschmask.psc_id"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_BATCH_TABLE_FIELD "Package_Package_pschmask.psc_batch"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_USER_TABLE_FIELD "Package_Package_pschmask.psc_user"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Package_Package_pschmask.psc_frozen"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_MOD_TABLE_FIELD "Package_Package_pschmask.psc_mod"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_PACKAGE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Package_Package_pschmask.psc_restrict"


#endif

