#ifndef __Define_ConfigType_pschmask_H__
#define __Define_ConfigType_pschmask_H__


#define CONFIGTYPE_PSCHMASK_TABLE "ConfigType_pschmask"
#define CONFIGTYPE_PSCHMASK_PK_CONFIGTYPE_FIELD "PK_ConfigType"
#define CONFIGTYPE_PSCHMASK_PK_CONFIGTYPE_TABLE_FIELD "ConfigType_pschmask.PK_ConfigType"
#define CONFIGTYPE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define CONFIGTYPE_PSCHMASK_DESCRIPTION_TABLE_FIELD "ConfigType_pschmask.Description"
#define CONFIGTYPE_PSCHMASK_DEFINE_FIELD "Define"
#define CONFIGTYPE_PSCHMASK_DEFINE_TABLE_FIELD "ConfigType_pschmask.Define"
#define CONFIGTYPE_PSCHMASK_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define CONFIGTYPE_PSCHMASK_FK_DEVICETEMPLATE_TABLE_FIELD "ConfigType_pschmask.FK_DeviceTemplate"
#define CONFIGTYPE_PSCHMASK_FK_DEVICECATEGORY_FIELD "FK_DeviceCategory"
#define CONFIGTYPE_PSCHMASK_FK_DEVICECATEGORY_TABLE_FIELD "ConfigType_pschmask.FK_DeviceCategory"
#define CONFIGTYPE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define CONFIGTYPE_PSCHMASK_PSC_ID_TABLE_FIELD "ConfigType_pschmask.psc_id"
#define CONFIGTYPE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define CONFIGTYPE_PSCHMASK_PSC_BATCH_TABLE_FIELD "ConfigType_pschmask.psc_batch"
#define CONFIGTYPE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define CONFIGTYPE_PSCHMASK_PSC_USER_TABLE_FIELD "ConfigType_pschmask.psc_user"
#define CONFIGTYPE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define CONFIGTYPE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "ConfigType_pschmask.psc_frozen"
#define CONFIGTYPE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define CONFIGTYPE_PSCHMASK_PSC_MOD_TABLE_FIELD "ConfigType_pschmask.psc_mod"
#define CONFIGTYPE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define CONFIGTYPE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "ConfigType_pschmask.psc_restrict"


#endif

