#ifndef __Define_Users_pschmask_H__
#define __Define_Users_pschmask_H__


#define USERS_PSCHMASK_TABLE "Users_pschmask"
#define USERS_PSCHMASK_PK_USERS_FIELD "PK_Users"
#define USERS_PSCHMASK_PK_USERS_TABLE_FIELD "Users_pschmask.PK_Users"
#define USERS_PSCHMASK_USERNAME_FIELD "UserName"
#define USERS_PSCHMASK_USERNAME_TABLE_FIELD "Users_pschmask.UserName"
#define USERS_PSCHMASK_PASSWORD_FIELD "Password"
#define USERS_PSCHMASK_PASSWORD_TABLE_FIELD "Users_pschmask.Password"
#define USERS_PSCHMASK_PINCODE_FIELD "PINCode"
#define USERS_PSCHMASK_PINCODE_TABLE_FIELD "Users_pschmask.PINCode"
#define USERS_PSCHMASK_HASMAILBOX_FIELD "HasMailbox"
#define USERS_PSCHMASK_HASMAILBOX_TABLE_FIELD "Users_pschmask.HasMailbox"
#define USERS_PSCHMASK_ACCESSGENERALMAILBOX_FIELD "AccessGeneralMailbox"
#define USERS_PSCHMASK_ACCESSGENERALMAILBOX_TABLE_FIELD "Users_pschmask.AccessGeneralMailbox"
#define USERS_PSCHMASK_EXTENSION_FIELD "Extension"
#define USERS_PSCHMASK_EXTENSION_TABLE_FIELD "Users_pschmask.Extension"
#define USERS_PSCHMASK_FIRSTNAME_FIELD "FirstName"
#define USERS_PSCHMASK_FIRSTNAME_TABLE_FIELD "Users_pschmask.FirstName"
#define USERS_PSCHMASK_LASTNAME_FIELD "LastName"
#define USERS_PSCHMASK_LASTNAME_TABLE_FIELD "Users_pschmask.LastName"
#define USERS_PSCHMASK_NICKNAME_FIELD "Nickname"
#define USERS_PSCHMASK_NICKNAME_TABLE_FIELD "Users_pschmask.Nickname"
#define USERS_PSCHMASK_EXTENSIONRINGTIMEOUT_FIELD "ExtensionRingTimeout"
#define USERS_PSCHMASK_EXTENSIONRINGTIMEOUT_TABLE_FIELD "Users_pschmask.ExtensionRingTimeout"
#define USERS_PSCHMASK_FORWARDEMAIL_FIELD "ForwardEmail"
#define USERS_PSCHMASK_FORWARDEMAIL_TABLE_FIELD "Users_pschmask.ForwardEmail"
#define USERS_PSCHMASK_FK_LANGUAGE_FIELD "FK_Language"
#define USERS_PSCHMASK_FK_LANGUAGE_TABLE_FIELD "Users_pschmask.FK_Language"
#define USERS_PSCHMASK_FK_INSTALLATION_MAIN_FIELD "FK_Installation_Main"
#define USERS_PSCHMASK_FK_INSTALLATION_MAIN_TABLE_FIELD "Users_pschmask.FK_Installation_Main"
#define USERS_PSCHMASK_HIDEFROMORBITER_FIELD "HideFromOrbiter"
#define USERS_PSCHMASK_HIDEFROMORBITER_TABLE_FIELD "Users_pschmask.HideFromOrbiter"
#define USERS_PSCHMASK_STAFF_FIELD "Staff"
#define USERS_PSCHMASK_STAFF_TABLE_FIELD "Users_pschmask.Staff"
#define USERS_PSCHMASK_PASSWORD_UNIX_FIELD "Password_Unix"
#define USERS_PSCHMASK_PASSWORD_UNIX_TABLE_FIELD "Users_pschmask.Password_Unix"
#define USERS_PSCHMASK_PASSWORD_SAMBA_FIELD "Password_Samba"
#define USERS_PSCHMASK_PASSWORD_SAMBA_TABLE_FIELD "Users_pschmask.Password_Samba"
#define USERS_PSCHMASK_FK_USERMODE_FIELD "FK_UserMode"
#define USERS_PSCHMASK_FK_USERMODE_TABLE_FIELD "Users_pschmask.FK_UserMode"
#define USERS_PSCHMASK_EK_DEALER_FIELD "EK_Dealer"
#define USERS_PSCHMASK_EK_DEALER_TABLE_FIELD "Users_pschmask.EK_Dealer"
#define USERS_PSCHMASK_EK_MANUFACTURER_FIELD "EK_Manufacturer"
#define USERS_PSCHMASK_EK_MANUFACTURER_TABLE_FIELD "Users_pschmask.EK_Manufacturer"
#define USERS_PSCHMASK_REQUIREPINTOSELECT_FIELD "RequirePinToSelect"
#define USERS_PSCHMASK_REQUIREPINTOSELECT_TABLE_FIELD "Users_pschmask.RequirePinToSelect"
#define USERS_PSCHMASK_PSC_ID_FIELD "psc_id"
#define USERS_PSCHMASK_PSC_ID_TABLE_FIELD "Users_pschmask.psc_id"
#define USERS_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define USERS_PSCHMASK_PSC_BATCH_TABLE_FIELD "Users_pschmask.psc_batch"
#define USERS_PSCHMASK_PSC_USER_FIELD "psc_user"
#define USERS_PSCHMASK_PSC_USER_TABLE_FIELD "Users_pschmask.psc_user"
#define USERS_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define USERS_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Users_pschmask.psc_frozen"
#define USERS_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define USERS_PSCHMASK_PSC_MOD_TABLE_FIELD "Users_pschmask.psc_mod"
#define USERS_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define USERS_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Users_pschmask.psc_restrict"


#endif

