#ifndef __Define_PackageType_pschmask_H__
#define __Define_PackageType_pschmask_H__


#define PACKAGETYPE_PSCHMASK_TABLE "PackageType_pschmask"
#define PACKAGETYPE_PSCHMASK_PK_PACKAGETYPE_FIELD "PK_PackageType"
#define PACKAGETYPE_PSCHMASK_PK_PACKAGETYPE_TABLE_FIELD "PackageType_pschmask.PK_PackageType"
#define PACKAGETYPE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define PACKAGETYPE_PSCHMASK_DESCRIPTION_TABLE_FIELD "PackageType_pschmask.Description"
#define PACKAGETYPE_PSCHMASK_DEFINE_FIELD "Define"
#define PACKAGETYPE_PSCHMASK_DEFINE_TABLE_FIELD "PackageType_pschmask.Define"
#define PACKAGETYPE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PACKAGETYPE_PSCHMASK_PSC_ID_TABLE_FIELD "PackageType_pschmask.psc_id"
#define PACKAGETYPE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PACKAGETYPE_PSCHMASK_PSC_BATCH_TABLE_FIELD "PackageType_pschmask.psc_batch"
#define PACKAGETYPE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PACKAGETYPE_PSCHMASK_PSC_USER_TABLE_FIELD "PackageType_pschmask.psc_user"
#define PACKAGETYPE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGETYPE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "PackageType_pschmask.psc_frozen"
#define PACKAGETYPE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PACKAGETYPE_PSCHMASK_PSC_MOD_TABLE_FIELD "PackageType_pschmask.psc_mod"
#define PACKAGETYPE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGETYPE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "PackageType_pschmask.psc_restrict"


#endif

