#ifndef __Define_EffectType_pschist_H__
#define __Define_EffectType_pschist_H__


#define EFFECTTYPE_PSCHIST_TABLE "EffectType_pschist"
#define EFFECTTYPE_PSCHIST_PK_EFFECTTYPE_FIELD "PK_EffectType"
#define EFFECTTYPE_PSCHIST_PK_EFFECTTYPE_TABLE_FIELD "EffectType_pschist.PK_EffectType"
#define EFFECTTYPE_PSCHIST_DESCRIPTION_FIELD "Description"
#define EFFECTTYPE_PSCHIST_DESCRIPTION_TABLE_FIELD "EffectType_pschist.Description"
#define EFFECTTYPE_PSCHIST_DEFINE_FIELD "Define"
#define EFFECTTYPE_PSCHIST_DEFINE_TABLE_FIELD "EffectType_pschist.Define"
#define EFFECTTYPE_PSCHIST_PSC_ID_FIELD "psc_id"
#define EFFECTTYPE_PSCHIST_PSC_ID_TABLE_FIELD "EffectType_pschist.psc_id"
#define EFFECTTYPE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define EFFECTTYPE_PSCHIST_PSC_BATCH_TABLE_FIELD "EffectType_pschist.psc_batch"
#define EFFECTTYPE_PSCHIST_PSC_USER_FIELD "psc_user"
#define EFFECTTYPE_PSCHIST_PSC_USER_TABLE_FIELD "EffectType_pschist.psc_user"
#define EFFECTTYPE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define EFFECTTYPE_PSCHIST_PSC_FROZEN_TABLE_FIELD "EffectType_pschist.psc_frozen"
#define EFFECTTYPE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define EFFECTTYPE_PSCHIST_PSC_MOD_TABLE_FIELD "EffectType_pschist.psc_mod"
#define EFFECTTYPE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define EFFECTTYPE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "EffectType_pschist.psc_restrict"
#define EFFECTTYPE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define EFFECTTYPE_PSCHIST_PSC_TOC_TABLE_FIELD "EffectType_pschist.psc_toc"


#endif

