#ifndef __Define_RemoteControl_H__
#define __Define_RemoteControl_H__


#define REMOTECONTROL_TABLE "RemoteControl"
#define REMOTECONTROL_PK_REMOTECONTROL_FIELD "PK_RemoteControl"
#define REMOTECONTROL_PK_REMOTECONTROL_TABLE_FIELD "RemoteControl.PK_RemoteControl"
#define REMOTECONTROL_FK_ORBITER_FIELD "FK_Orbiter"
#define REMOTECONTROL_FK_ORBITER_TABLE_FIELD "RemoteControl.FK_Orbiter"
#define REMOTECONTROL_FK_DEVICETEMPLATE_MEDIATYPE_DESIGNOBJ_FIELD "FK_DeviceTemplate_MediaType_DesignObj"
#define REMOTECONTROL_FK_DEVICETEMPLATE_MEDIATYPE_DESIGNOBJ_TABLE_FIELD "RemoteControl.FK_DeviceTemplate_MediaType_DesignObj"
#define REMOTECONTROL_FK_MEDIATYPE_DESIGNOBJ_FIELD "FK_MediaType_DesignObj"
#define REMOTECONTROL_FK_MEDIATYPE_DESIGNOBJ_TABLE_FIELD "RemoteControl.FK_MediaType_DesignObj"
#define REMOTECONTROL_PSC_ID_FIELD "psc_id"
#define REMOTECONTROL_PSC_ID_TABLE_FIELD "RemoteControl.psc_id"
#define REMOTECONTROL_PSC_BATCH_FIELD "psc_batch"
#define REMOTECONTROL_PSC_BATCH_TABLE_FIELD "RemoteControl.psc_batch"
#define REMOTECONTROL_PSC_USER_FIELD "psc_user"
#define REMOTECONTROL_PSC_USER_TABLE_FIELD "RemoteControl.psc_user"
#define REMOTECONTROL_PSC_FROZEN_FIELD "psc_frozen"
#define REMOTECONTROL_PSC_FROZEN_TABLE_FIELD "RemoteControl.psc_frozen"
#define REMOTECONTROL_PSC_MOD_FIELD "psc_mod"
#define REMOTECONTROL_PSC_MOD_TABLE_FIELD "RemoteControl.psc_mod"
#define REMOTECONTROL_PSC_RESTRICT_FIELD "psc_restrict"
#define REMOTECONTROL_PSC_RESTRICT_TABLE_FIELD "RemoteControl.psc_restrict"


#endif

