#ifndef __Define_SetupStep_pschist_H__
#define __Define_SetupStep_pschist_H__


#define SETUPSTEP_PSCHIST_TABLE "SetupStep_pschist"
#define SETUPSTEP_PSCHIST_PK_SETUPSTEP_FIELD "PK_SetupStep"
#define SETUPSTEP_PSCHIST_PK_SETUPSTEP_TABLE_FIELD "SetupStep_pschist.PK_SetupStep"
#define SETUPSTEP_PSCHIST_FK_INSTALLATION_FIELD "FK_Installation"
#define SETUPSTEP_PSCHIST_FK_INSTALLATION_TABLE_FIELD "SetupStep_pschist.FK_Installation"
#define SETUPSTEP_PSCHIST_FK_PAGESETUP_FIELD "FK_PageSetup"
#define SETUPSTEP_PSCHIST_FK_PAGESETUP_TABLE_FIELD "SetupStep_pschist.FK_PageSetup"
#define SETUPSTEP_PSCHIST_PSC_ID_FIELD "psc_id"
#define SETUPSTEP_PSCHIST_PSC_ID_TABLE_FIELD "SetupStep_pschist.psc_id"
#define SETUPSTEP_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define SETUPSTEP_PSCHIST_PSC_BATCH_TABLE_FIELD "SetupStep_pschist.psc_batch"
#define SETUPSTEP_PSCHIST_PSC_USER_FIELD "psc_user"
#define SETUPSTEP_PSCHIST_PSC_USER_TABLE_FIELD "SetupStep_pschist.psc_user"
#define SETUPSTEP_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define SETUPSTEP_PSCHIST_PSC_FROZEN_TABLE_FIELD "SetupStep_pschist.psc_frozen"
#define SETUPSTEP_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define SETUPSTEP_PSCHIST_PSC_MOD_TABLE_FIELD "SetupStep_pschist.psc_mod"
#define SETUPSTEP_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define SETUPSTEP_PSCHIST_PSC_TOC_TABLE_FIELD "SetupStep_pschist.psc_toc"
#define SETUPSTEP_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define SETUPSTEP_PSCHIST_PSC_RESTRICT_TABLE_FIELD "SetupStep_pschist.psc_restrict"


#endif

