#ifndef __Define_Text_H__
#define __Define_Text_H__

#define TEXT_ARRAY_DESCRIPTION_CONST 316
#define TEXT_MORE_CONST 317
#define TEXT_DROP_CALL_CONST 318
#define TEXT_ANSWER_HERE_CONST 320
#define TEXT_SEND_VM_CONST 321
#define TEXT_MOVE_CALL_CONST 322
#define TEXT_TRANSFER_CONST 323
#define TEXT_CALLER_NAME_CONST 324
#define TEXT_CALLER_NUMBER_CONST 325
#define TEXT_NO_VIDEO_CONST 326
#define TEXT_INCOMING_CALL_CONST 327
#define TEXT_CALL_MNGR_CONST 328
#define TEXT_USER_STATS_CONST 329
#define TEXT_CALL_PB_CONST 343
#define TEXT_CALL_DNUM_CONST 344
#define TEXT_CALL_SPEED_CONST 345
#define TEXT_CALL_PLUTO_CONST 346
#define TEXT_USR_ENTRY_CONST 347
#define TEXT_CALL_CONST 348
#define TEXT_A_CONST 351
#define TEXT_B_CONST 352
#define TEXT_C_CONST 353
#define TEXT_D_CONST 354
#define TEXT_E_CONST 355
#define TEXT_F_CONST 356
#define TEXT_G_CONST 357
#define TEXT_H_CONST 358
#define TEXT_I_CONST 359
#define TEXT_J_CONST 360
#define TEXT_K_CONST 361
#define TEXT_L_CONST 362
#define TEXT_M_CONST 363
#define TEXT_N_CONST 364
#define TEXT_O_CONST 365
#define TEXT_P_CONST 366
#define TEXT_Q_CONST 367
#define TEXT_R_CONST 368
#define TEXT_S_CONST 369
#define TEXT_T_CONST 370
#define TEXT_U_CONST 371
#define TEXT_V_CONST 372
#define TEXT_W_CONST 373
#define TEXT_X_CONST 374
#define TEXT_Y_CONST 375
#define TEXT_Z_CONST 376
#define TEXT_1_CONST 377
#define TEXT_2_CONST 378
#define TEXT_3_CONST 379
#define TEXT_4_CONST 380
#define TEXT_5_CONST 381
#define TEXT_6_CONST 382
#define TEXT_7_CONST 383
#define TEXT_8_CONST 384
#define TEXT_9_CONST 385
#define TEXT_0_CONST 386
#define TEXT_SPACE_CONST 388
#define TEXT_RECENT_CALLS_CONST 389
#define TEXT_SPEED_DIAL_CONST 390
#define TEXT_SECURITY_ALERTS_CONST 394
#define TEXT_TRIPPED_SENSOR_CONST 395
#define TEXT_SEC_ALERTS_CONST 396
#define TEXT_TRIPPED_SENSORS_CONST 397
#define TEXT_CONNECTION_LOST_CONST 398
#define TEXT_ALERT_CONST 399
#define TEXT_Location_Description_CONST 400
#define TEXT_TOUCHSCREEN_UNLOCK_CONST 401
#define TEXT_ASK_TO_LEAVE_CONST 402
#define TEXT_CAMERA1_CONST 403
#define TEXT_CAMERA2_CONST 404
#define TEXT_CAMERA3_CONST 405
#define TEXT_CAMERA4_CONST 406
#define TEXT_GO_CONST 407
#define TEXT_EPG_SHOW_PREVIEW_CONST 408
#define TEXT_SEARCH_TITLE_CONST 409
#define TEXT_SEARCH_CREDITS_CONST 410
#define TEXT_SEARCH_GENRE_CONST 411
#define TEXT_SEARCH_YEAR_CONST 412
#define TEXT_SEARCH_RATING_CONST 413
#define TEXT_SEACH_ALL_CONST 414
#define TEXT_SEARCH_BY_DESC_CONST 415
#define TEXT_SHOW_STARS_DESC_CONST 416
#define TEXT_SEARCH_SHOW_DESC_CONST 417
#define TEXT_SEARCH_TV_RATING_CONST 418
#define TEXT_PVR_FUTURE_RECORD_CONST 419
#define TEXT_PVR_RECORD_FUTURE_NEW_CONST 420
#define TEXT_PVR_FUTURE_REC_EPISODE_CONST 421
#define TEXT_AUTOMATICALLY_TUNE_CONST 422
#define TEXT_PVR_RECORD_BUSY_CONST 423
#define TEXT_PVR_DONT_RECORD_CONST 424
#define TEXT_PVR_SKIP_RECORDING_CONST 426
#define TEXT_PVR_NOT_MY_SHOW_CONST 427
#define TEXT_PVR_FORCE_RECORD_CONST 428
#define TEXT_PVR_RECORD_SELECTMC_CONST 429
#define TEXT_PVR_ALREADY_RECORDING_CONST 430
#define TEXT_CANCEL_RECORDING_CONST 431
#define TEXT_PVR_CANNOT_CHANGE_CHANNEL_CONST 432
#define TEXT_PVR_CANNOT_USE_CONST 433
#define TEXT_BROWSE_MEDIA_ALL_CONST 437
#define TEXT_VIEW_OTHER_CONSOLE_CONST 438
#define TEXT_VIEW_CURRENT_BROADCAST_CONST 439
#define TEXT_REFRESH_CONST 442
#define TEXT_PLAY_CONST 443
#define TEXT_ADD_ALL_CONST 444
#define TEXT_NEXT_CONST 446
#define TEXT_FILE_LIST_DESC_CONST 447
#define TEXT_SAVE_FILE_DESC_CONST 448
#define TEXT_SAVE_CONST 449
#define TEXT_DISC_DRIVE_BUSY_CONST 452
#define TEXT_CANCEL_CONST 453
#define TEXT_DRIVE_ACTION_CONST 454
#define TEXT_PROGRESS_CONST 455
#define TEXT_BROADCAST_CONST 456
#define TEXT_CLEAR_CONST 457
#define TEXT_SEARCH_MOVIE_RATING_CONST 463
#define TEXT_SEARCH_TV_MPAA_RATING_CONST 464
#define TEXT_SEARCH_1950_CONST 465
#define TEXT_SEARCH_1960_CONST 466
#define TEXT_SEARCH_1970_CONST 467
#define TEXT_SEARCH_1980_CONST 468
#define TEXT_SEARCH_1990_CONST 469
#define TEXT_SEARCH_CONST 471
#define TEXT_GUIDE_CONST 472
#define TEXT_RECORDED_TV_CONST 473
#define TEXT_REMOTE_CONST 474
#define TEXT_FAVORITES_CONST 475
#define TEXT_CALL_INTERCOM_CONST 476
#define TEXT_EPG_SHOW_NAME_CONST 477
#define TEXT_EPG_CHANNEL_NAME_CONST 478
#define TEXT_BURN_CD_AUDIO_CONST 482
#define TEXT_BURN_CD_DATA_CONST 483
#define TEXT_BURN_DVD_VIDEO_CONST 484
#define TEXT_BURN_DVD_DATA_CONST 485
#define TEXT_BURN_LAST_IMAGE_CONST 486
#define TEXT_CREATE_MEDIA_INST_CONST 487
#define TEXT_INSERT_MEDIA_CONST 488
#define TEXT_CONTINUE_CONST 489
#define TEXT_VERIFY_MEDIA_CONST 490
#define TEXT_RIP_CD_TRACKS_CONST 499
#define TEXT_ALL_TRACKS_CONST 500
#define TEXT_SCREEN_TALLER_CONST 501
#define TEXT_SCREEN_SHORTER_CONST 502
#define TEXT_SCREEN_WIDER_CONST 503
#define TEXT_SCREEN_Narrow_CONST 504
#define TEXT_SCREEN_UP_CONST 505
#define TEXT_SCREEN_DOWN_CONST 506
#define TEXT_SCREEN_LEFT_CONST 507
#define TEXT_SCREEN_RIGHT_CONST 508
#define TEXT_PVR_OPTIONS_CONST 510
#define TEXT_PVR_REC_SHOW_CONST 511
#define TEXT_PVR_REC_NOW_CONST 512
#define TEXT_PVR_REC_EVERYTHING_CONST 513
#define TEXT_PVR_REC_DURATION_CONST 514
#define TEXT_PVR_REC_30M_CONST 515
#define TEXT_PVR_REC_60M_CONST 516
#define TEXT_PVR_REC_INDEFINATE_CONST 517
#define TEXT_PVR_REC_ENDOFSHOW_CONST 518
#define TEXT_DV_START_CONST 519
#define TEXT_DV_STOP_CAPTURE_CONST 520
#define TEXT_ADD_CONTACT_CONST 521
#define TEXT_ADD_FAVORITES_CHANNEL_CONST 522
#define TEXT_CONTROLLER_STATUS_CONST 523
#define TEXT_ADD_FAVORITES_SHOWS_CONST 525
#define TEXT_REMOVE_FAVORITES_CHANNEL_CONST 526
#define TEXT_REMOVE_FAVORITES_SHOWS_CONST 527
#define TEXT_KEEP_RECORDING_CONST 529
#define TEXT_Choose_Filename_CONST 530
#define TEXT_EPG_FILE_NAME_CONST 531
#define TEXT_ADD_SPEED_DIAL_CONST 532
#define TEXT_ADDING_SPEED_DIAL_CONST 533
#define TEXT_QUESTION_MARK_CONST 534
#define TEXT_AMPERSAND_CONST 535
#define TEXT_HYPHEN_CONST 536
#define TEXT_AT_SYMBOL_CONST 537
#define TEXT_PERIOD_CONST 538
#define TEXT_RETRANSMIT_IR_CONST 541
#define TEXT_CALL_FROM_WHAT_DEVICE_CONST 542
#define TEXT_CALL_TO_WHICH_INTERCOM_CONST 543
#define TEXT_SAVE_PUBLIC_CONST 545
#define TEXT_SAVE_PRIVATE_CONST 546
#define TEXT_CONFIRM_DELETE_CONST 547
#define TEXT_DELETE_CONST 548
#define TEXT_ENTER_URL_CONST 550
#define TEXT_GOTO_URL_CONST 551
#define TEXT_PLUTO_BROWSER_CONST 552
#define TEXT_MAP_CONST 553
#define TEXT_NO_MEDIA_IN_DRIVE_CONST 555
#define TEXT_ENTER_MODE_CONST 556
#define TEXT_CHANGED_MODE_CONST 557
#define TEXT_HOUSE_MODE_CONST 558
#define TEXT_TOUCH_CONTINUE_CONST 559
#define TEXT_WAIT_FOR_SENSORS_CONST 560
#define TEXT_BYPASS_SENSORS_CONST 561
#define TEXT_ARM_WHEN_READY_CONST 562
#define TEXT_Copy_Disc_CONST 566
#define TEXT_ADVANCED_REMOTE_CONST 567
#define TEXT_REJECT_CALL_CONST 568
#define TEXT_HOME_VIDEOS_CONST 569
#define TEXT_STORED_MUSIC_CONST 570
#define TEXT_OTHER_MEDIA_CONST 571
#define TEXT_JUMP_TO_CONST 572
#define TEXT_INFO_CONST 573
#define TEXT_KEEP_PVR_NAME_CONST 581
#define TEXT_ADD_THIS_NUMBER_CONST 582
#define TEXT_SORT_CONST 583
#define TEXT_FIND_ALL_CONST 584
#define TEXT_EPG_SHOW_INFO_CONST 585
#define TEXT_DEVICE_PROBLEM_CONST 586
#define TEXT_PROBLEM_DEVICE_CONST 587
#define TEXT_YES_CONST 588
#define TEXT_NO_CONST 589
#define TEXT_DEVICE_PROBLEM_TITLE_CONST 590
#define TEXT_ADD_WWW_CONST 591
#define TEXT_CREATE_DOC_CONST 592
#define TEXT_CREATE_SPREADSHEET_CONST 593
#define TEXT_OPEN_WWW_PDA_CONST 594
#define TEXT_OPEN_WWW_TV_CONST 595
#define TEXT_OPEN_FILE_CONST 596
#define TEXT_ALL_Files_CONST 597
#define TEXT_RECENT_DOCUMENTS_CONST 598
#define TEXT_REMOVE_WWW_CONST 599
#define TEXT_Specific_FOLDER_CONST 600
#define TEXT_PRINT_CONST 601
#define TEXT_EMAIL_CONST 602
#define TEXT_EXIT_CONTROLLER_CONST 603
#define TEXT_RESET_PLUTO_UNIVERSE_CONST 604
#define TEXT_RESET_CONSOLE_CONST 605
#define TEXT_CALLING_CONST 606
#define TEXT_PICK_A_USER_CONST 607
#define TEXT_BROADCAST_LINPHONE_CONST 608
#define TEXT_END_LINPHONE_BROADCAST_CONST 609
#define TEXT_Restart_Router_CONST 610
#define TEXT_CONTROL_AV_CONST 611
#define TEXT_CONTROL_MISC_CONST 612
#define TEXT_CONTROL_ALL_DEV_CONST 613
#define TEXT_MOVE_CALL_HERE_CONST 614
#define TEXT_PLACE_FROM_HERE_CONST 615
#define TEXT_PIN_Code_CONST 617
#define TEXT_ADD_REMOVE_CONST 618
#define TEXT_JUKEBOX_CONST 619
#define TEXT_BROWSE_TITLE_CONST 620
#define TEXT_BROWSE_GENRE_CONST 621
#define TEXT_BROWSE_FOLDERS_CONST 622
#define TEXT_BROWSE_PERFORMER_CONST 626
#define TEXT_BROWSE_BY_CONST 627
#define TEXT_HOME_VIDS_CONST 628
#define TEXT_MOVIES_CONST 629
#define TEXT_MUSIC_CONST 630
#define TEXT_PLAYLIST_CONST 631
#define TEXT_View_CONST 632
#define TEXT_Close_CONST 633
#define TEXT_CURRENTLY_USING_CONST 637
#define TEXT_ENT_GUIDE_CONST 638
#define TEXT_MEDIA_CENTRAL_CONST 639
#define TEXT_REMOTE_A_CONST 640
#define TEXT_REMOTE_B_CONST 641
#define TEXT_REMOTE1_TAB_CONST 642
#define TEXT_REMOTE2_TAB_CONST 643
#define TEXT_GUIDE_TAB_CONST 644
#define TEXT_HOUSE_GLANCE_CONST 645
#define TEXT_RECORD_AND_TURN_OFF_CONST 646
#define TEXT_CONFERENCE_CONST 647
#define TEXT_STEP_ONE_CONST 648
#define TEXT_STEP_TWO_CONST 649
#define TEXT_OR_CONST 650
#define TEXT_CALL_IN_PROGRESS_CONST 651
#define TEXT_XFER_MD_CONST 652
#define TEXT_XFER_PHONE_CONST 653
#define TEXT_XFER_ORBITER_CONST 654
#define TEXT_NET_MEDIA_CONST 655
#define TEXT_CHANGE_MEDIA_GROUP_CONST 659
#define TEXT_SAVE_PLAYLIST_CONST 664
#define TEXT_RUNTIME_ARRAY_DESCRIPTION_CONST 668
#define TEXT_RUNTIME_ARRAY_ID_CONST 669
#define TEXT_STATUS_CONST 670
#define TEXT_STATUS_VARIABLE_CONST 671
#define TEXT_LEARN_IR_CODE_CONST 672
#define TEXT_RESET_AV_CONST 673
#define TEXT_RESET_AV_2_CONST 674
#define TEXT_Khz33_CONST 675
#define TEXT_Khz45_CONST 676
#define TEXT_Khz60_CONST 677
#define TEXT_TELECOM_OVERVIEW_CONST 678
#define TEXT_ON_100_CONST 679
#define TEXT_PERCENT_90_CONST 680
#define TEXT_PERCENT_70_CONST 681
#define TEXT_PERCENT_50_CONST 682
#define TEXT_PERCENT_30_CONST 683
#define TEXT_PERCENT_10_CONST 684
#define TEXT_OFF_CONST 685
#define TEXT_AUTO_CONST 686
#define TEXT_HEAT_CONST 687
#define TEXT_COOL_CONST 688
#define TEXT_FAN_CONST 689
#define TEXT_PLUS_CONST 690
#define TEXT_MINUS_CONST 691
#define TEXT_VOL_CONST 692
#define TEXT_CH_CONST 693
#define TEXT_Name_Playlist_CONST 696
#define TEXT_CANNOT_ADD_TO_PLAYLIST_CONST 698
#define TEXT_CHOOSE_SOMETHING_ELSE_CONST 699
#define TEXT_FAN_AUTO_CONST 700
#define TEXT_RESTART_AS_WINDOWS_CONST 701
#define TEXT_HOUSE_DISARMED_CONST 710
#define TEXT_HOUSE_ARMED_CONST 711
#define TEXT_AT_HOME_SEC_CONST 712
#define TEXT_SLEEPING_CONST 713
#define TEXT_EXTENDED_AWAY_CONST 714
#define TEXT_ENTERTAINING_CONST 715
#define TEXT_Start_As_Pluto_CONST 717
#define TEXT_DRIVE_BEING_USED_CONST 718
#define TEXT_DVD_REMOTE_CONST 719
#define TEXT_STILL_BUILDING_EPG_CONST 720
#define TEXT_GOT_NEW_EPG_DATA_CONST 721
#define TEXT_AVENTER_CONST 722
#define TEXT_EPG_SHOW_1_CONST 723
#define TEXT_EPG_SHOW_2_CONST 724
#define TEXT_FINISHED_EPG_CONST 725
#define TEXT_Preview_Auto_CONST 726
#define TEXT_LOCK_PREVIEW_CONST 727
#define TEXT_Show_Nothing_CONST 728
#define TEXT_PLAY_ALL_CONST 729
#define TEXT_OUTSIDE_NUMBER_CONST 730
#define TEXT_REBOOT_MD_CONST 731
#define TEXT_Delete_Rule_CONST 734
#define TEXT_Delete_Rule_And_Shows_CONST 735
#define TEXT_Hangup_All_TVs_CONST 736
#define TEXT_ADVANCED_MEDIA_OPTIONS_CONST 738
#define TEXT_NOW_PLAYING_LONG_CONST 740
#define TEXT_FILE_LIST_CONST 741
#define TEXT_ONE_EXCLAMATION_CONST 742
#define TEXT_TWO_AT_CONST 743
#define TEXT_THREE_NUMBER_CONST 744
#define TEXT_FOUR_DOLLAR_CONST 745
#define TEXT_Five_Percent_CONST 746
#define TEXT_Six_Caret_CONST 747
#define TEXT_Seven_Ampersand_CONST 748
#define TEXT_Eight_Asterisk_CONST 749
#define TEXT_Nine_Left_Parent_CONST 750
#define TEXT_Zero_Right_Parenth_CONST 751
#define TEXT_dash_underscore_CONST 752
#define TEXT_Equals_Plus_CONST 753
#define TEXT_Colon_SemiColon_CONST 754
#define TEXT_Quotations_CONST 755
#define TEXT_Comma_CONST 756
#define TEXT_Shift_CONST 758
#define TEXT_Back_CONST 759
#define TEXT_CAPS_LOCK_CONST 760
#define TEXT_Instant_Replay_CONST 761
#define TEXT_Previous_Channel_CONST 762
#define TEXT_Return_To_Live_CONST 763
#define TEXT_Menu_CONST 765
#define TEXT_Search_Media_CONST 766
#define TEXT_Files_CONST 767
#define TEXT_Collections_CONST 768
#define TEXT_Attributes_CONST 770
#define TEXT_GOTO_REMOTE_CONST 772
#define TEXT_NON_PLUTO_TV_CONST 773
#define TEXT_PLUTO_TV_CONST 774
#define TEXT_Exit_CONST 775
#define TEXT_AVInfo_CONST 776
#define TEXT_SATMusic_CONST 777
#define TEXT_QUEUE_CONST 779
#define TEXT_CHANNEL_CONST 780
#define TEXT_MUTE_CONST 781
#define TEXT_AVGuide_CONST 784
#define TEXT_dot_dot_dot_CONST 785
#define TEXT_On_CONST 786
#define TEXT_MIN_5_CONST 787
#define TEXT_MIN_10_CONST 788
#define TEXT_MIN_20_CONST 789
#define TEXT_MIN_30_CONST 790
#define TEXT_MIN_45_CONST 791
#define TEXT_HOUR_1_CONST 792
#define TEXT_STOP_COMPUTING_CONST 793
#define TEXT_DVD_OPTIONS_CONST 794
#define TEXT_Lights_CONST 795
#define TEXT_Media_CONST 796
#define TEXT_Climate_CONST 797
#define TEXT_Telecom_CONST 798
#define TEXT_Security_CONST 799
#define TEXT_Other_CONST 800
#define TEXT_location_CONST 801
#define TEXT_Hold_C_Help_15_follow_CONST 802
#define TEXT_playing_CONST 803
#define TEXT_music_media_CONST 816
#define TEXT_Yes_Install_the_software_CONST 1065
#define TEXT_No_This_device_is_not_a_mobile_phone_CONST 1066
#define TEXT_new_phone_detected_CONST 1067
#define TEXT_Next_myth_CONST 1068
#define TEXT_myth_setup_CONST 1069
#define TEXT_Setup_Myth_TV_CONST 1070
#define TEXT_First_Time_CONST 1071
#define TEXT_No_Media_CONST 1072
#define TEXT_go_to_main_menu_CONST 1073
#define TEXT_Load_playlist_CONST 1074
#define TEXT_Enter_CONST 1075
#define TEXT_Launch_MythTV_configuration_CONST 1076
#define TEXT_Dial_number_CONST 1077
#define TEXT_Dial_user_CONST 1078
#define TEXT_Voicemail_CONST 1079
#define TEXT_transfer_call_or_conference_CONST 1080
#define TEXT_Choose_user_CONST 1081
#define TEXT_Vol_up_CONST 1082
#define TEXT_Vol_down_CONST 1083
#define TEXT_At_home_CONST 1084
#define TEXT_Away_CONST 1085
#define TEXT_Disturb_CONST 1086
#define TEXT_Sleeping_phone_status_CONST 1087
#define TEXT_Press_enter_to_go_to_security_alerts_CONST 1088
#define TEXT_To_enter_PIN_press_Enter_CONST 1089
#define TEXT_Choose_a_user_CONST 1090
#define TEXT_House_Mode_Time_CONST 1091
#define TEXT_Alerts_since_last_change_CONST 1092
#define TEXT_Alerts_Placeholder_CONST 1093
#define TEXT_Manage_Playlist_CONST 1094
#define TEXT_Version_CONST 1095
#define TEXT_Try_other_codes_CONST 1096
#define TEXT_Device_Info_CONST 1097
#define TEXT_Computing_CONST 1098
#define TEXT_Sleeping_menu_CONST 1099
#define TEXT_Time_CONST 1100
#define TEXT_Date_CONST 1101
#define TEXT_Temp_outside_CONST 1102
#define TEXT_Temp_inside_CONST 1103
#define TEXT_Wake_Up_CONST 1104
#define TEXT_Email_Contacts_CONST 1105
#define TEXT_KDE_desktop_CONST 1106
#define TEXT_Installed_Programs_CONST 1107
#define TEXT_Recent_files_CONST 1108
#define TEXT_Go_to_Pluto_Admin_web_site_CONST 1109
#define TEXT_Display_Off_CONST 1110
#define TEXT_instructions_CONST 1111
#define TEXT_Alarms_CONST 1112
#define TEXT_Regen_Orbiter_CONST 1113
#define TEXT_Delete_entry_CONST 1114
#define TEXT_Delete_Playlist_CONST 1115
#define TEXT_Addgc_CONST 1116
#define TEXT_New_PnP_CONST 1117
#define TEXT_Regen_all_Orbiters_CONST 1118
#define TEXT_Orbiter_in_control_CONST 1119
#define TEXT_Orbiter_I_am_CONST 1120
#define TEXT_ON_display_CONST 1121
#define TEXT_OFF_display_CONST 1122
#define TEXT_Display_CONST 1123
#define TEXT_Power_ON_CONST 1124
#define TEXT_Current_media_CONST 1125
#define TEXT_Halt_CONST 1126
#define TEXT_My_Media_CONST 1127
#define TEXT_Yes_its_a_phone_CONST 1128
#define TEXT_choose_room_CONST 1129
#define TEXT_Orbiters_Regenerated_CONST 1130
#define TEXT_Checking_drive_CONST 1131
#define TEXT_Cannot_play_DVD_CONST 1132
#define TEXT_Exit_Pluto_CONST 1133
#define TEXT_advanced_CONST 1134
#define TEXT_asterisc_CONST 1135
#define TEXT_pound_CONST 1136
#define TEXT_Quad_view_CONST 1137
#define TEXT_Choose_camerav_CONST 1138
#define TEXT_Single_camera_view_CONST 1139
#define TEXT_orbiter_regenerated_CONST 1140
#define TEXT_Angles_CONST 1141
#define TEXT_Audio_Options_CONST 1142
#define TEXT_Subtitles_CONST 1143
#define TEXT_Selected_Devices_CONST 1144
#define TEXT_press_pencil_to_go_to_floorplan_CONST 1145
#define TEXT_type_channel_number_CONST 1146
#define TEXT_Countdown_before_alarm_CONST 1147
#define TEXT_Countdown_before_armed_CONST 1148
#define TEXT_Short_countdown_before_alarm_CONST 1149
#define TEXT_Short_countdown_before_armed_CONST 1150
#define TEXT_Wait_to_Arm_CONST 1151
#define TEXT_Try_Again_CONST 1152
#define TEXT_ViewSet_Attributes_CONST 1153
#define TEXT_Reset_signal_sent_CONST 1154
#define TEXT_Pending_Tasks_CONST 1155
#define TEXT_view_button_CONST 1156
#define TEXT_speak_CONST 1157
#define TEXT_open_CONST 1158
#define TEXT_sound_for_CONST 1159
#define TEXT_1_sec_CONST 1160
#define TEXT_5_sec_CONST 1161
#define TEXT_15_sec_CONST 1162
#define TEXT_30_sec_CONST 1163
#define TEXT_60_sec_CONST 1164
#define TEXT_Advanced_Options_CONST 1165
#define TEXT_Edit_Attribute_CONST 1166
#define TEXT_Random_CONST 1167
#define TEXT_Main_menu_CONST 1168
#define TEXT_mobile_signal_strength_CONST 1169
#define TEXT_New_Devices_Configured_CONST 1170
#define TEXT_Hide_Popup_CONST 1171
#define TEXT_Select_current_user_CONST 1172
#define TEXT_Select_room_CONST 1173
#define TEXT_Ligthing_scenarios_CONST 1174
#define TEXT_Media_Scenarios_CONST 1175
#define TEXT_Other_options_CONST 1176
#define TEXT_Security_scenarios_CONST 1177
#define TEXT_Telecom_scenarios_CONST 1178
#define TEXT_Climate_scenarios_CONST 1179
#define TEXT_Bookmarks_CONST 1180
#define TEXT_Save_Bookmark_CONST 1181
#define TEXT_Delete_Bookmark_CONST 1182
#define TEXT_Name_Bookmark_CONST 1183
#define TEXT_How_to_create_bookmark_CONST 1184
#define TEXT_Cannot_play_media_CONST 1185
#define TEXT_Cannot_bookmark_CONST 1186
#define TEXT_problem_ripping_CONST 1187
#define TEXT_Only_rip_drives_CONST 1188
#define TEXT_ripping_cant_play_disc_CONST 1189
#define TEXT_Abort_ripping_CONST 1190
#define TEXT_Last_Datagrid_Cell_CONST 1191
#define TEXT_Bookmark_here_CONST 1193
#define TEXT_Ask_to_resume_CONST 1194
#define TEXT_Always_Resume_CONST 1195
#define TEXT_Never_Resume_CONST 1196
#define TEXT_Unknown_Disc_CONST 1197
#define TEXT_Mouse_CONST 1198
#define TEXT_Car_Setup_CONST 1201
#define TEXT_Home_CONST 1202
#define TEXT_Radio_CONST 1203
#define TEXT_TV_CONST 1204
#define TEXT_CD_CONST 1205
#define TEXT_Hard_drive_CONST 1206
#define TEXT_Internet_CONST 1207
#define TEXT_Email_CONST 1208
#define TEXT_Agenda_CONST 1209
#define TEXT_Lighting_CONST 1211
#define TEXT_Nav_CONST 1215
#define TEXT_Info_CONST 1216
#define TEXT_Car_CONST 1217
#define TEXT_Setup_CONST 1218
#define TEXT_Memory_CONST 1219
#define TEXT_Radio_control_CONST 1220
#define TEXT_Frequency_CONST 1221
#define TEXT_Sound_CONST 1222
#define TEXT_Live_TV_CONST 1223
#define TEXT_Recorded_TV_CONST 1224
#define TEXT_Program_Guide_CONST 1225
#define TEXT_Recording_list_CONST 1226
#define TEXT_Control_CONST 1227
#define TEXT_Track_list_CONST 1228
#define TEXT_Changer_CONST 1229
#define TEXT_Sound_cd_CONST 1230
#define TEXT_Music_CONST 1231
#define TEXT_Video_CONST 1232
#define TEXT_Pictures_CONST 1233
#define TEXT_Control_i9nternet_CONST 1235
#define TEXT_Manual_CONST 1236
#define TEXT_Full_screen_internet_CONST 1237
#define TEXT_Read_CONST 1238
#define TEXT_Write_CONST 1239
#define TEXT_SendReceive_CONST 1240
#define TEXT_User_CONST 1241
#define TEXT_Calendar_CONST 1242
#define TEXT_Contacts_CONST 1243
#define TEXT_To_do_CONST 1244
#define TEXT_User_agenda_CONST 1245
#define TEXT_Program_list_CONST 1246
#define TEXT_Documents_CONST 1247
#define TEXT_Install_Remove_CONST 1248
#define TEXT_User_other_CONST 1249
#define TEXT_Memory_nav_CONST 1250
#define TEXT_Nav_info_CONST 1251
#define TEXT_Route_CONST 1252
#define TEXT_Map_CONST 1253
#define TEXT_TP_Memo_CONST 1254
#define TEXT_Telematics_CONST 1255
#define TEXT_Source_CONST 1256
#define TEXT_User_car_CONST 1257
#define TEXT_Systems_CONST 1258
#define TEXT_Handbook_CONST 1259
#define TEXT_Directory_CONST 1261
#define TEXT_Settings_CONST 1263
#define TEXT_Sound_setup_CONST 1264
#define TEXT_opt1_CONST 1265
#define TEXT_List_lighting_CONST 1266
#define TEXT_Map_lighting_CONST 1267
#define TEXT_List_telecom_CONST 1268
#define TEXT_Map_telecom_CONST 1269
#define TEXT_Make_call_CONST 1270
#define TEXT_Intercom_CONST 1271
#define TEXT_List_security_CONST 1272
#define TEXT_Map_security_CONST 1273
#define TEXT_Cameras_CONST 1274
#define TEXT_Doors_CONST 1275
#define TEXT_List_climate_CONST 1276
#define TEXT_Map_climate_CONST 1277
#define TEXT_adaptive_air_suspension_CONST 1279
#define TEXT_lift_CONST 1280
#define TEXT_Maximilian_CONST 1281
#define TEXT_Alexander_CONST 1282
#define TEXT_Sophie_CONST 1283
#define TEXT_user4_CONST 1284
#define TEXT_comfort_CONST 1285
#define TEXT_automatic_CONST 1286
#define TEXT_dynamic_CONST 1287
#define TEXT_Bayern_5_CONST 1288
#define TEXT_Radio_in_CONST 1289
#define TEXT_Bayern_2_CONST 1290
#define TEXT_Bayern_1_CONST 1291
#define TEXT_Bayern_4_CONST 1292
#define TEXT_Control_dvd_CONST 1293
#define TEXT_Sound_dvd_CONST 1294
#define TEXT_Options_CONST 1295
#define TEXT_DVD_CONST 1297
#define TEXT_media_description_CONST 1298
#define TEXT_Rewind_CONST 1299
#define TEXT_Previous_CONST 1300
#define TEXT_Scan_CONST 1301
#define TEXT_Name_CONST 1302
#define TEXT_Shuffle_cd_CONST 1303
#define TEXT_Next_CONST 1304
#define TEXT_Forward_CONST 1305
#define TEXT_Tune_down_CONST 1306
#define TEXT_Tune_up_CONST 1307
#define TEXT_Seek_up_CONST 1308
#define TEXT_Seek_down_CONST 1309
#define TEXT_Scan_redio_CONST 1310
#define TEXT_Store_CONST 1311
#define TEXT_Bayern_3_CONST 1312
#define TEXT_destinations_CONST 1313
#define TEXT_Route_planning_CONST 1314
#define TEXT_Route_list_CONST 1315
#define TEXT_Route_criteria_CONST 1316
#define TEXT_Exclude_route_from_here_CONST 1317
#define TEXT_Country_CONST 1318
#define TEXT_Town_Zip_CONST 1319
#define TEXT_Street_CONST 1320
#define TEXT_Special_destination_CONST 1321
#define TEXT_Start_route_guidance_CONST 1322
#define TEXT_Towing_mode_CONST 1323
#define TEXT_Car_jack_mode_CONST 1324
#define TEXT_Find_entry_CONST 1325
#define TEXT_Show_list_CONST 1326
#define TEXT_Display_points_of_interest_CONST 1327
#define TEXT_New_entry_CONST 1328
#define TEXT_Delete_directory_CONST 1329
#define TEXT_Menu_lang_CONST 1330
#define TEXT_Measurement_units_CONST 1331
#define TEXT_Time_settings_CONST 1332
#define TEXT_System_tones_CONST 1333
#define TEXT_Speech_dialog_controls_CONST 1334
#define TEXT_Factory_settings_CONST 1335
#define TEXT_CD_DVD_CONST 1336
#define TEXT_Loading_from_device_CONST 1337
#define TEXT_Full_screen_CONST 1338
#define TEXT_Audio_tracks_CONST 1341
#define TEXT_Sound_dvd_options_CONST 1342
#define TEXT_Last_destionations_CONST 1343
#define TEXT_Top_categories_CONST 1344
#define TEXT_brightness_CONST 1345
#define TEXT_Balance_CONST 1346
#define TEXT_Fader_CONST 1347
#define TEXT_Treble_CONST 1348
#define TEXT_Bass_CONST 1349
#define TEXT_Subwoofer_CONST 1350
#define TEXT_FM_very_high_frequency_CONST 1351
#define TEXT_MW_medium_wave_CONST 1352
#define TEXT_LW_long_wave_CONST 1353
#define TEXT_CD_1_ACDC_Stiff_Upper_Lip_CONST 1354
#define TEXT_CD_2_Best_of_the_Millennium_Classical_CONST 1355
#define TEXT_CD_3_Chris_Botti_When_I_Fall_In_Lov_CONST 1356
#define TEXT_CD_4_Regis_Philbin_When_Youre_Smili_CONST 1357
#define TEXT_891_MHz_CONST 1358
#define TEXT_Sending_and_receiving_emails_CONST 1359
#define TEXT_acoustic_parking_system_CONST 1360
#define TEXT_adaptive_cruise_control_CONST 1361
#define TEXT_exterior_lighting_CONST 1362
#define TEXT_battery_level_CONST 1363
#define TEXT_previous_dvd_CONST 1364
#define TEXT_step_backward_CONST 1365
#define TEXT_pause_CONST 1366
#define TEXT_play_CONST 1367
#define TEXT_stop_dvd_CONST 1368
#define TEXT_step_forward_CONST 1369
#define TEXT_next_dvd_CONST 1370
#define TEXT_save_CONST 1371
#define TEXT_fast_forward_CONST 1372
#define TEXT_fast_rewind_CONST 1373
#define TEXT_Save_dafsad_CONST 1374
#define TEXT_Stored_DVDs_CONST 1375
#define TEXT_Recorded_TV_hard_drive_CONST 1376
#define TEXT_Queue_CONST 1377
#define TEXT_Control_video_hard_drive_CONST 1378
#define TEXT_Playlists_CONST 1379
#define TEXT_Programs_CONST 1380
#define TEXT_Num_CONST 1391
#define TEXT__CONST 1392
#define TEXT_FM_CONST 1393
#define TEXT_LW_CONST 1394
#define TEXT_MW_CONST 1395
#define TEXT_test_CONST 1396
#define TEXT_back_CONST 1397
#define TEXT_stop_CONST 1398
#define TEXT_reload_CONST 1399
#define TEXT_Front_door_CONST 1400
#define TEXT_Back_door_CONST 1401
#define TEXT_bedroom_extension_101_CONST 1402
#define TEXT_kitchen_extension_102_CONST 1403
#define TEXT_front_door_extension_103_CONST 1404
#define TEXT_office_extension_104_CONST 1405
#define TEXT_Type_entry_on_the_phone_CONST 1406
#define TEXT_resave_this_queue_as__11_CONST 1407
#define TEXT_save_this_queue_as_a_new_playlist_CONST 1408
#define TEXT_rearrange_queue_CONST 1409
#define TEXT_delete_something_from_the_queue_CONST 1410
#define TEXT_rename_the_playlist__11_CONST 1411
#define TEXT_delete_the_playlist__11_CONST 1412
#define TEXT_scroll_CONST 1414
#define TEXT_Seek_In_Data_Grid_CONST 1415
#define TEXT_Path_CONST 1416
#define TEXT_Audio_CONST 1417
#define TEXT_Video_hd_CONST 1418
#define TEXT_read_from_phone_keyboard_CONST 1419
#define TEXT_Inbox_CONST 1420
#define TEXT_Message_from_Alexander_CONST 1421
#define TEXT_How_are_you_CONST 1422
#define TEXT_Compose_CONST 1423
#define TEXT_TO_CONST 1424
#define TEXT_Subject_CONST 1425
#define TEXT_Message_CONST 1426
#define TEXT_New_phone_CONST 1427
#define TEXT_Device_Ready_CONST 1428
#define TEXT_FAILED_TO_UPLOAD_SIS_FILE_CONST 1429
#define TEXT_Watching_TV_CONST 1430
#define TEXT_Live_TV_Browse_Mode_CONST 1431
#define TEXT_Playback_Recording_CONST 1432
#define TEXT_All_MythTv_controls_CONST 1433
#define TEXT_Change_Inputs_CONST 1434
#define TEXT_Ripping_Instructions_CONST 1435
#define TEXT_Total_CONST 1436
#define TEXT_Now_Playing_Section_CONST 1437
#define TEXT_Now_Playing_Timecode_CONST 1438
#define TEXT_Now_Playing_Speed_CONST 1442
#define TEXT_Playlist_Saved_CONST 1443

#define TEXT_TABLE "Text"
#define TEXT_PK_TEXT_FIELD "PK_Text"
#define TEXT_PK_TEXT_TABLE_FIELD "Text.PK_Text"
#define TEXT_FK_TEXTCATEGORY_FIELD "FK_TextCategory"
#define TEXT_FK_TEXTCATEGORY_TABLE_FIELD "Text.FK_TextCategory"
#define TEXT_DESCRIPTION_FIELD "Description"
#define TEXT_DESCRIPTION_TABLE_FIELD "Text.Description"
#define TEXT_DEFINE_FIELD "Define"
#define TEXT_DEFINE_TABLE_FIELD "Text.Define"
#define TEXT_ADDTOORBITER_FIELD "AddToOrbiter"
#define TEXT_ADDTOORBITER_TABLE_FIELD "Text.AddToOrbiter"
#define TEXT_PSC_ID_FIELD "psc_id"
#define TEXT_PSC_ID_TABLE_FIELD "Text.psc_id"
#define TEXT_PSC_BATCH_FIELD "psc_batch"
#define TEXT_PSC_BATCH_TABLE_FIELD "Text.psc_batch"
#define TEXT_PSC_USER_FIELD "psc_user"
#define TEXT_PSC_USER_TABLE_FIELD "Text.psc_user"
#define TEXT_PSC_FROZEN_FIELD "psc_frozen"
#define TEXT_PSC_FROZEN_TABLE_FIELD "Text.psc_frozen"
#define TEXT_PSC_MOD_FIELD "psc_mod"
#define TEXT_PSC_MOD_TABLE_FIELD "Text.psc_mod"
#define TEXT_PSC_RESTRICT_FIELD "psc_restrict"
#define TEXT_PSC_RESTRICT_TABLE_FIELD "Text.psc_restrict"


#endif

