#ifndef __Define_MediaType_H__
#define __Define_MediaType_H__

#define MEDIATYPE_pluto_LiveTV_CONST 1
#define MEDIATYPE_pluto_CD_CONST 2
#define MEDIATYPE_pluto_DVD_CONST 3
#define MEDIATYPE_pluto_StoredAudio_CONST 4
#define MEDIATYPE_pluto_StoredVideo_CONST 5
#define MEDIATYPE_pluto_LiveRadio_CONST 6
#define MEDIATYPE_pluto_Pictures_CONST 7
#define MEDIATYPE_np_LiveTV_CONST 11
#define MEDIATYPE_np_DVD_CONST 12
#define MEDIATYPE_np_OTARadio_CONST 13
#define MEDIATYPE_np_SatelliteRadio_CONST 14
#define MEDIATYPE_np_CableRadio_CONST 15
#define MEDIATYPE_np_VideoTape_CONST 16
#define MEDIATYPE_np_LaserDisc_CONST 17
#define MEDIATYPE_np_Game_CONST 18
#define MEDIATYPE_np_CD_CONST 19
#define MEDIATYPE_misc_Burning_CONST 20
#define MEDIATYPE_misc_Playlist_CONST 21
#define MEDIATYPE_misc_EditPlaylist_CONST 22
#define MEDIATYPE_misc_BlankMedia_CONST 23
#define MEDIATYPE_misc_DocViewer_CONST 24
#define MEDIATYPE_np_Cassette_CONST 25
#define MEDIATYPE_np_Picture_CONST 26
#define MEDIATYPE_pluto_HDDVD_CONST 27
#define MEDIATYPE_pluto_BD_CONST 28
#define MEDIATYPE_lmce_Game_CONST 29
#define MEDIATYPE_lmce_Game_a2600_CONST 30
#define MEDIATYPE_np_BluRay_CONST 31
#define MEDIATYPE_lmce_Game_a5200_CONST 32
#define MEDIATYPE_lmce_Game_a7800_CONST 33
#define MEDIATYPE_lmce_Game_coleco_CONST 34
#define MEDIATYPE_lmce_Game_intv_CONST 35
#define MEDIATYPE_lmce_Game_famicom_CONST 36
#define MEDIATYPE_lmce_Game_nes_CONST 37
#define MEDIATYPE_lmce_Game_sms_CONST 38
#define MEDIATYPE_lmce_Game_sg1000_CONST 39
#define MEDIATYPE_np_Tivo3_CONST 40
#define MEDIATYPE_np_Tivo2_CONST 41
#define MEDIATYPE_lmce_Hulu_CONST 42
#define MEDIATYPE_lmce_StreamedAudio_CONST 43
#define MEDIATYPE_lmce_StreamedVideo_CONST 44
#define MEDIATYPE_lmce_Game_vectrex_CONST 45
#define MEDIATYPE_lmce_Game_tg16_CONST 46
#define MEDIATYPE_lmce_Game_genesis_CONST 47
#define MEDIATYPE_lmce_Game_snes_CONST 48
#define MEDIATYPE_lmce_Game_megadriv_CONST 49
#define MEDIATYPE_lmce_Game_snespal_CONST 50
#define MEDIATYPE_lmce_Game_sgx_CONST 51
#define MEDIATYPE_lmce_Game_pce_CONST 52
#define MEDIATYPE_lmce_Game_apple2_CONST 53
#define MEDIATYPE_lmce_Game_ps1_CONST 54
#define MEDIATYPE_lmce_Game_ps2_CONST 55
#define MEDIATYPE_lmce_Game_jaguar_CONST 56
#define MEDIATYPE_lmce_Game_vic20_CONST 57
#define MEDIATYPE_lmce_Game_c64_CONST 58
#define MEDIATYPE_lmce_Game_Atari800_CONST 59
#define MEDIATYPE_lmce_Airplay_audio_CONST 60
#define MEDIATYPE_lmce_AirPlay_video_CONST 61
#define MEDIATYPE_lmce_AirPlay_photos_CONST 62
#define MEDIATYPE_lmce_YouTube_CONST 63
#define MEDIATYPE_np_InternetMedia_CONST 64
#define MEDIATYPE_lmce_Game_amiga_CONST 65
#define MEDIATYPE_np_NetworkMedia_CONST 66
#define MEDIATYPE_np_XBOX360_CONST 67
#define MEDIATYPE_np_PVR_CONST 68
#define MEDIATYPE_np_Playstation_CONST 69
#define MEDIATYPE_lmce_Game_TI99_CONST 70

#define MEDIATYPE_TABLE "MediaType"
#define MEDIATYPE_PK_MEDIATYPE_FIELD "PK_MediaType"
#define MEDIATYPE_PK_MEDIATYPE_TABLE_FIELD "MediaType.PK_MediaType"
#define MEDIATYPE_DEFINE_FIELD "Define"
#define MEDIATYPE_DEFINE_TABLE_FIELD "MediaType.Define"
#define MEDIATYPE_DESCRIPTION_FIELD "Description"
#define MEDIATYPE_DESCRIPTION_TABLE_FIELD "MediaType.Description"
#define MEDIATYPE_FK_DESIGNOBJ_FIELD "FK_DesignObj"
#define MEDIATYPE_FK_DESIGNOBJ_TABLE_FIELD "MediaType.FK_DesignObj"
#define MEDIATYPE_DCEAWARE_FIELD "DCEAware"
#define MEDIATYPE_DCEAWARE_TABLE_FIELD "MediaType.DCEAware"
#define MEDIATYPE_EXTENSIONS_FIELD "Extensions"
#define MEDIATYPE_EXTENSIONS_TABLE_FIELD "MediaType.Extensions"
#define MEDIATYPE_SUBDIRECTORY_FIELD "Subdirectory"
#define MEDIATYPE_SUBDIRECTORY_TABLE_FIELD "MediaType.Subdirectory"
#define MEDIATYPE_ISEXTERNALTRANSMISSION_FIELD "IsExternalTransmission"
#define MEDIATYPE_ISEXTERNALTRANSMISSION_TABLE_FIELD "MediaType.IsExternalTransmission"
#define MEDIATYPE_FK_PIPE_FIELD "FK_Pipe"
#define MEDIATYPE_FK_PIPE_TABLE_FIELD "MediaType.FK_Pipe"
#define MEDIATYPE_CANBOOKMARK_FIELD "CanBookmark"
#define MEDIATYPE_CANBOOKMARK_TABLE_FIELD "MediaType.CanBookmark"
#define MEDIATYPE_EK_ATTRIBUTETYPE_DEFAULTSORT_FIELD "EK_AttributeType_DefaultSort"
#define MEDIATYPE_EK_ATTRIBUTETYPE_DEFAULTSORT_TABLE_FIELD "MediaType.EK_AttributeType_DefaultSort"
#define MEDIATYPE_PSC_ID_FIELD "psc_id"
#define MEDIATYPE_PSC_ID_TABLE_FIELD "MediaType.psc_id"
#define MEDIATYPE_PSC_BATCH_FIELD "psc_batch"
#define MEDIATYPE_PSC_BATCH_TABLE_FIELD "MediaType.psc_batch"
#define MEDIATYPE_PSC_USER_FIELD "psc_user"
#define MEDIATYPE_PSC_USER_TABLE_FIELD "MediaType.psc_user"
#define MEDIATYPE_PSC_FROZEN_FIELD "psc_frozen"
#define MEDIATYPE_PSC_FROZEN_TABLE_FIELD "MediaType.psc_frozen"
#define MEDIATYPE_PSC_MOD_FIELD "psc_mod"
#define MEDIATYPE_PSC_MOD_TABLE_FIELD "MediaType.psc_mod"
#define MEDIATYPE_PSC_RESTRICT_FIELD "psc_restrict"
#define MEDIATYPE_PSC_RESTRICT_TABLE_FIELD "MediaType.psc_restrict"


#endif

