#ifndef __Define_Firewall_H__
#define __Define_Firewall_H__


#define FIREWALL_TABLE "Firewall"
#define FIREWALL_PK_FIREWALL_FIELD "PK_Firewall"
#define FIREWALL_PK_FIREWALL_TABLE_FIELD "Firewall.PK_Firewall"
#define FIREWALL_PLACE_FIELD "Place"
#define FIREWALL_PLACE_TABLE_FIELD "Firewall.Place"
#define FIREWALL_MATCHNAME_FIELD "Matchname"
#define FIREWALL_MATCHNAME_TABLE_FIELD "Firewall.Matchname"
#define FIREWALL_INTIF_FIELD "IntIF"
#define FIREWALL_INTIF_TABLE_FIELD "Firewall.IntIF"
#define FIREWALL_EXTIF_FIELD "ExtIF"
#define FIREWALL_EXTIF_TABLE_FIELD "Firewall.ExtIF"
#define FIREWALL_PROTOCOL_FIELD "Protocol"
#define FIREWALL_PROTOCOL_TABLE_FIELD "Firewall.Protocol"
#define FIREWALL_SOURCEPORT_FIELD "SourcePort"
#define FIREWALL_SOURCEPORT_TABLE_FIELD "Firewall.SourcePort"
#define FIREWALL_SOURCEPORTEND_FIELD "SourcePortEnd"
#define FIREWALL_SOURCEPORTEND_TABLE_FIELD "Firewall.SourcePortEnd"
#define FIREWALL_DESTINATIONPORT_FIELD "DestinationPort"
#define FIREWALL_DESTINATIONPORT_TABLE_FIELD "Firewall.DestinationPort"
#define FIREWALL_SOURCEIP_FIELD "SourceIP"
#define FIREWALL_SOURCEIP_TABLE_FIELD "Firewall.SourceIP"
#define FIREWALL_DESTINATIONIP_FIELD "DestinationIP"
#define FIREWALL_DESTINATIONIP_TABLE_FIELD "Firewall.DestinationIP"
#define FIREWALL_RULETYPE_FIELD "RuleType"
#define FIREWALL_RULETYPE_TABLE_FIELD "Firewall.RuleType"
#define FIREWALL_DISABLED_FIELD "Disabled"
#define FIREWALL_DISABLED_TABLE_FIELD "Firewall.Disabled"
#define FIREWALL_OFFLINE_FIELD "Offline"
#define FIREWALL_OFFLINE_TABLE_FIELD "Firewall.Offline"
#define FIREWALL_RPOLICY_FIELD "RPolicy"
#define FIREWALL_RPOLICY_TABLE_FIELD "Firewall.RPolicy"
#define FIREWALL_DESCRIPTION_FIELD "Description"
#define FIREWALL_DESCRIPTION_TABLE_FIELD "Firewall.Description"
#define FIREWALL_BANTIME_FIELD "Bantime"
#define FIREWALL_BANTIME_TABLE_FIELD "Firewall.Bantime"
#define FIREWALL_PSC_ID_FIELD "psc_id"
#define FIREWALL_PSC_ID_TABLE_FIELD "Firewall.psc_id"
#define FIREWALL_PSC_BATCH_FIELD "psc_batch"
#define FIREWALL_PSC_BATCH_TABLE_FIELD "Firewall.psc_batch"
#define FIREWALL_PSC_USER_FIELD "psc_user"
#define FIREWALL_PSC_USER_TABLE_FIELD "Firewall.psc_user"
#define FIREWALL_PSC_FROZEN_FIELD "psc_frozen"
#define FIREWALL_PSC_FROZEN_TABLE_FIELD "Firewall.psc_frozen"
#define FIREWALL_PSC_MOD_FIELD "psc_mod"
#define FIREWALL_PSC_MOD_TABLE_FIELD "Firewall.psc_mod"
#define FIREWALL_PSC_RESTRICT_FIELD "psc_restrict"
#define FIREWALL_PSC_RESTRICT_TABLE_FIELD "Firewall.psc_restrict"


#endif

