#ifndef __Define_CommMethod_pschmask_H__
#define __Define_CommMethod_pschmask_H__


#define COMMMETHOD_PSCHMASK_TABLE "CommMethod_pschmask"
#define COMMMETHOD_PSCHMASK_PK_COMMMETHOD_FIELD "PK_CommMethod"
#define COMMMETHOD_PSCHMASK_PK_COMMMETHOD_TABLE_FIELD "CommMethod_pschmask.PK_CommMethod"
#define COMMMETHOD_PSCHMASK_DESCRIPTION_FIELD "Description"
#define COMMMETHOD_PSCHMASK_DESCRIPTION_TABLE_FIELD "CommMethod_pschmask.Description"
#define COMMMETHOD_PSCHMASK_DEFINE_FIELD "Define"
#define COMMMETHOD_PSCHMASK_DEFINE_TABLE_FIELD "CommMethod_pschmask.Define"
#define COMMMETHOD_PSCHMASK_PSC_ID_FIELD "psc_id"
#define COMMMETHOD_PSCHMASK_PSC_ID_TABLE_FIELD "CommMethod_pschmask.psc_id"
#define COMMMETHOD_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define COMMMETHOD_PSCHMASK_PSC_BATCH_TABLE_FIELD "CommMethod_pschmask.psc_batch"
#define COMMMETHOD_PSCHMASK_PSC_USER_FIELD "psc_user"
#define COMMMETHOD_PSCHMASK_PSC_USER_TABLE_FIELD "CommMethod_pschmask.psc_user"
#define COMMMETHOD_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define COMMMETHOD_PSCHMASK_PSC_FROZEN_TABLE_FIELD "CommMethod_pschmask.psc_frozen"
#define COMMMETHOD_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define COMMMETHOD_PSCHMASK_PSC_MOD_TABLE_FIELD "CommMethod_pschmask.psc_mod"
#define COMMMETHOD_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMMETHOD_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "CommMethod_pschmask.psc_restrict"


#endif

