#ifndef __Define_Criteria_pschist_H__
#define __Define_Criteria_pschist_H__


#define CRITERIA_PSCHIST_TABLE "Criteria_pschist"
#define CRITERIA_PSCHIST_PK_CRITERIA_FIELD "PK_Criteria"
#define CRITERIA_PSCHIST_PK_CRITERIA_TABLE_FIELD "Criteria_pschist.PK_Criteria"
#define CRITERIA_PSCHIST_FK_CRITERIAPARMNESTING_FIELD "FK_CriteriaParmNesting"
#define CRITERIA_PSCHIST_FK_CRITERIAPARMNESTING_TABLE_FIELD "Criteria_pschist.FK_CriteriaParmNesting"
#define CRITERIA_PSCHIST_FK_CRITERIALIST_FIELD "FK_CriteriaList"
#define CRITERIA_PSCHIST_FK_CRITERIALIST_TABLE_FIELD "Criteria_pschist.FK_CriteriaList"
#define CRITERIA_PSCHIST_FK_INSTALLATION_FIELD "FK_Installation"
#define CRITERIA_PSCHIST_FK_INSTALLATION_TABLE_FIELD "Criteria_pschist.FK_Installation"
#define CRITERIA_PSCHIST_DESCRIPTION_FIELD "Description"
#define CRITERIA_PSCHIST_DESCRIPTION_TABLE_FIELD "Criteria_pschist.Description"
#define CRITERIA_PSCHIST_DEFINE_FIELD "Define"
#define CRITERIA_PSCHIST_DEFINE_TABLE_FIELD "Criteria_pschist.Define"
#define CRITERIA_PSCHIST_PSC_ID_FIELD "psc_id"
#define CRITERIA_PSCHIST_PSC_ID_TABLE_FIELD "Criteria_pschist.psc_id"
#define CRITERIA_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define CRITERIA_PSCHIST_PSC_BATCH_TABLE_FIELD "Criteria_pschist.psc_batch"
#define CRITERIA_PSCHIST_PSC_USER_FIELD "psc_user"
#define CRITERIA_PSCHIST_PSC_USER_TABLE_FIELD "Criteria_pschist.psc_user"
#define CRITERIA_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define CRITERIA_PSCHIST_PSC_FROZEN_TABLE_FIELD "Criteria_pschist.psc_frozen"
#define CRITERIA_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define CRITERIA_PSCHIST_PSC_MOD_TABLE_FIELD "Criteria_pschist.psc_mod"
#define CRITERIA_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define CRITERIA_PSCHIST_PSC_TOC_TABLE_FIELD "Criteria_pschist.psc_toc"
#define CRITERIA_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define CRITERIA_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Criteria_pschist.psc_restrict"


#endif

