#ifndef __Define_Room_Users_pschist_H__
#define __Define_Room_Users_pschist_H__


#define ROOM_USERS_PSCHIST_TABLE "Room_Users_pschist"
#define ROOM_USERS_PSCHIST_PK_ROOM_USERS_FIELD "PK_Room_Users"
#define ROOM_USERS_PSCHIST_PK_ROOM_USERS_TABLE_FIELD "Room_Users_pschist.PK_Room_Users"
#define ROOM_USERS_PSCHIST_FK_ROOM_FIELD "FK_Room"
#define ROOM_USERS_PSCHIST_FK_ROOM_TABLE_FIELD "Room_Users_pschist.FK_Room"
#define ROOM_USERS_PSCHIST_FK_USERS_FIELD "FK_Users"
#define ROOM_USERS_PSCHIST_FK_USERS_TABLE_FIELD "Room_Users_pschist.FK_Users"
#define ROOM_USERS_PSCHIST_FK_ORBITER_FIELD "FK_Orbiter"
#define ROOM_USERS_PSCHIST_FK_ORBITER_TABLE_FIELD "Room_Users_pschist.FK_Orbiter"
#define ROOM_USERS_PSCHIST_PSC_ID_FIELD "psc_id"
#define ROOM_USERS_PSCHIST_PSC_ID_TABLE_FIELD "Room_Users_pschist.psc_id"
#define ROOM_USERS_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define ROOM_USERS_PSCHIST_PSC_BATCH_TABLE_FIELD "Room_Users_pschist.psc_batch"
#define ROOM_USERS_PSCHIST_PSC_USER_FIELD "psc_user"
#define ROOM_USERS_PSCHIST_PSC_USER_TABLE_FIELD "Room_Users_pschist.psc_user"
#define ROOM_USERS_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define ROOM_USERS_PSCHIST_PSC_FROZEN_TABLE_FIELD "Room_Users_pschist.psc_frozen"
#define ROOM_USERS_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define ROOM_USERS_PSCHIST_PSC_MOD_TABLE_FIELD "Room_Users_pschist.psc_mod"
#define ROOM_USERS_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define ROOM_USERS_PSCHIST_PSC_TOC_TABLE_FIELD "Room_Users_pschist.psc_toc"
#define ROOM_USERS_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define ROOM_USERS_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Room_Users_pschist.psc_restrict"


#endif

