#ifndef __Define_Package_Package_pschist_H__
#define __Define_Package_Package_pschist_H__


#define PACKAGE_PACKAGE_PSCHIST_TABLE "Package_Package_pschist"
#define PACKAGE_PACKAGE_PSCHIST_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_PACKAGE_PSCHIST_FK_PACKAGE_TABLE_FIELD "Package_Package_pschist.FK_Package"
#define PACKAGE_PACKAGE_PSCHIST_FK_PACKAGE_DEPENDSON_FIELD "FK_Package_DependsOn"
#define PACKAGE_PACKAGE_PSCHIST_FK_PACKAGE_DEPENDSON_TABLE_FIELD "Package_Package_pschist.FK_Package_DependsOn"
#define PACKAGE_PACKAGE_PSCHIST_ONLYTOBUILD_FIELD "OnlyToBuild"
#define PACKAGE_PACKAGE_PSCHIST_ONLYTOBUILD_TABLE_FIELD "Package_Package_pschist.OnlyToBuild"
#define PACKAGE_PACKAGE_PSCHIST_PREDEPENDENCY_FIELD "PreDependency"
#define PACKAGE_PACKAGE_PSCHIST_PREDEPENDENCY_TABLE_FIELD "Package_Package_pschist.PreDependency"
#define PACKAGE_PACKAGE_PSCHIST_PSC_ID_FIELD "psc_id"
#define PACKAGE_PACKAGE_PSCHIST_PSC_ID_TABLE_FIELD "Package_Package_pschist.psc_id"
#define PACKAGE_PACKAGE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_PACKAGE_PSCHIST_PSC_BATCH_TABLE_FIELD "Package_Package_pschist.psc_batch"
#define PACKAGE_PACKAGE_PSCHIST_PSC_USER_FIELD "psc_user"
#define PACKAGE_PACKAGE_PSCHIST_PSC_USER_TABLE_FIELD "Package_Package_pschist.psc_user"
#define PACKAGE_PACKAGE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_PACKAGE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Package_Package_pschist.psc_frozen"
#define PACKAGE_PACKAGE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_PACKAGE_PSCHIST_PSC_MOD_TABLE_FIELD "Package_Package_pschist.psc_mod"
#define PACKAGE_PACKAGE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PACKAGE_PACKAGE_PSCHIST_PSC_TOC_TABLE_FIELD "Package_Package_pschist.psc_toc"
#define PACKAGE_PACKAGE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_PACKAGE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Package_Package_pschist.psc_restrict"


#endif

