#ifndef __Define_PageSetup_pschist_H__
#define __Define_PageSetup_pschist_H__


#define PAGESETUP_PSCHIST_TABLE "PageSetup_pschist"
#define PAGESETUP_PSCHIST_PK_PAGESETUP_FIELD "PK_PageSetup"
#define PAGESETUP_PSCHIST_PK_PAGESETUP_TABLE_FIELD "PageSetup_pschist.PK_PageSetup"
#define PAGESETUP_PSCHIST_FK_PAGESETUP_PARENT_FIELD "FK_PageSetup_Parent"
#define PAGESETUP_PSCHIST_FK_PAGESETUP_PARENT_TABLE_FIELD "PageSetup_pschist.FK_PageSetup_Parent"
#define PAGESETUP_PSCHIST_WEBSITE_FIELD "Website"
#define PAGESETUP_PSCHIST_WEBSITE_TABLE_FIELD "PageSetup_pschist.Website"
#define PAGESETUP_PSCHIST_ORDERNUM_FIELD "OrderNum"
#define PAGESETUP_PSCHIST_ORDERNUM_TABLE_FIELD "PageSetup_pschist.OrderNum"
#define PAGESETUP_PSCHIST_FK_PACKAGE_FIELD "FK_Package"
#define PAGESETUP_PSCHIST_FK_PACKAGE_TABLE_FIELD "PageSetup_pschist.FK_Package"
#define PAGESETUP_PSCHIST_DESCRIPTION_FIELD "Description"
#define PAGESETUP_PSCHIST_DESCRIPTION_TABLE_FIELD "PageSetup_pschist.Description"
#define PAGESETUP_PSCHIST_PAGEURL_FIELD "pageURL"
#define PAGESETUP_PSCHIST_PAGEURL_TABLE_FIELD "PageSetup_pschist.pageURL"
#define PAGESETUP_PSCHIST_SHOWINTOPMENU_FIELD "showInTopMenu"
#define PAGESETUP_PSCHIST_SHOWINTOPMENU_TABLE_FIELD "PageSetup_pschist.showInTopMenu"
#define PAGESETUP_PSCHIST_PSC_ID_FIELD "psc_id"
#define PAGESETUP_PSCHIST_PSC_ID_TABLE_FIELD "PageSetup_pschist.psc_id"
#define PAGESETUP_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PAGESETUP_PSCHIST_PSC_BATCH_TABLE_FIELD "PageSetup_pschist.psc_batch"
#define PAGESETUP_PSCHIST_PSC_USER_FIELD "psc_user"
#define PAGESETUP_PSCHIST_PSC_USER_TABLE_FIELD "PageSetup_pschist.psc_user"
#define PAGESETUP_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PAGESETUP_PSCHIST_PSC_FROZEN_TABLE_FIELD "PageSetup_pschist.psc_frozen"
#define PAGESETUP_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PAGESETUP_PSCHIST_PSC_MOD_TABLE_FIELD "PageSetup_pschist.psc_mod"
#define PAGESETUP_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PAGESETUP_PSCHIST_PSC_TOC_TABLE_FIELD "PageSetup_pschist.psc_toc"
#define PAGESETUP_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PAGESETUP_PSCHIST_PSC_RESTRICT_TABLE_FIELD "PageSetup_pschist.psc_restrict"


#endif

