#ifndef __Define_Device_Device_Related_pschist_H__
#define __Define_Device_Device_Related_pschist_H__


#define DEVICE_DEVICE_RELATED_PSCHIST_TABLE "Device_Device_Related_pschist"
#define DEVICE_DEVICE_RELATED_PSCHIST_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_DEVICE_RELATED_PSCHIST_FK_DEVICE_TABLE_FIELD "Device_Device_Related_pschist.FK_Device"
#define DEVICE_DEVICE_RELATED_PSCHIST_FK_DEVICE_RELATED_FIELD "FK_Device_Related"
#define DEVICE_DEVICE_RELATED_PSCHIST_FK_DEVICE_RELATED_TABLE_FIELD "Device_Device_Related_pschist.FK_Device_Related"
#define DEVICE_DEVICE_RELATED_PSCHIST_VALUE_FIELD "Value"
#define DEVICE_DEVICE_RELATED_PSCHIST_VALUE_TABLE_FIELD "Device_Device_Related_pschist.Value"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_ID_FIELD "psc_id"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_ID_TABLE_FIELD "Device_Device_Related_pschist.psc_id"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_BATCH_TABLE_FIELD "Device_Device_Related_pschist.psc_batch"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_USER_FIELD "psc_user"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_USER_TABLE_FIELD "Device_Device_Related_pschist.psc_user"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_FROZEN_TABLE_FIELD "Device_Device_Related_pschist.psc_frozen"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_MOD_TABLE_FIELD "Device_Device_Related_pschist.psc_mod"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_TOC_TABLE_FIELD "Device_Device_Related_pschist.psc_toc"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_DEVICE_RELATED_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Device_Device_Related_pschist.psc_restrict"


#endif

