#ifndef __Define_Text_LS_AltVersions_H__
#define __Define_Text_LS_AltVersions_H__


#define TEXT_LS_ALTVERSIONS_TABLE "Text_LS_AltVersions"
#define TEXT_LS_ALTVERSIONS_FK_TEXT_FIELD "FK_Text"
#define TEXT_LS_ALTVERSIONS_FK_TEXT_TABLE_FIELD "Text_LS_AltVersions.FK_Text"
#define TEXT_LS_ALTVERSIONS_FK_LANGUAGE_FIELD "FK_Language"
#define TEXT_LS_ALTVERSIONS_FK_LANGUAGE_TABLE_FIELD "Text_LS_AltVersions.FK_Language"
#define TEXT_LS_ALTVERSIONS_VERSION_FIELD "Version"
#define TEXT_LS_ALTVERSIONS_VERSION_TABLE_FIELD "Text_LS_AltVersions.Version"
#define TEXT_LS_ALTVERSIONS_DESCRIPTION_FIELD "Description"
#define TEXT_LS_ALTVERSIONS_DESCRIPTION_TABLE_FIELD "Text_LS_AltVersions.Description"
#define TEXT_LS_ALTVERSIONS_PSC_ID_FIELD "psc_id"
#define TEXT_LS_ALTVERSIONS_PSC_ID_TABLE_FIELD "Text_LS_AltVersions.psc_id"
#define TEXT_LS_ALTVERSIONS_PSC_BATCH_FIELD "psc_batch"
#define TEXT_LS_ALTVERSIONS_PSC_BATCH_TABLE_FIELD "Text_LS_AltVersions.psc_batch"
#define TEXT_LS_ALTVERSIONS_PSC_USER_FIELD "psc_user"
#define TEXT_LS_ALTVERSIONS_PSC_USER_TABLE_FIELD "Text_LS_AltVersions.psc_user"
#define TEXT_LS_ALTVERSIONS_PSC_FROZEN_FIELD "psc_frozen"
#define TEXT_LS_ALTVERSIONS_PSC_FROZEN_TABLE_FIELD "Text_LS_AltVersions.psc_frozen"
#define TEXT_LS_ALTVERSIONS_PSC_MOD_FIELD "psc_mod"
#define TEXT_LS_ALTVERSIONS_PSC_MOD_TABLE_FIELD "Text_LS_AltVersions.psc_mod"
#define TEXT_LS_ALTVERSIONS_PSC_RESTRICT_FIELD "psc_restrict"
#define TEXT_LS_ALTVERSIONS_PSC_RESTRICT_TABLE_FIELD "Text_LS_AltVersions.psc_restrict"


#endif

