#ifndef __Define_Language_pschist_H__
#define __Define_Language_pschist_H__


#define LANGUAGE_PSCHIST_TABLE "Language_pschist"
#define LANGUAGE_PSCHIST_PK_LANGUAGE_FIELD "PK_Language"
#define LANGUAGE_PSCHIST_PK_LANGUAGE_TABLE_FIELD "Language_pschist.PK_Language"
#define LANGUAGE_PSCHIST_DESCRIPTION_FIELD "Description"
#define LANGUAGE_PSCHIST_DESCRIPTION_TABLE_FIELD "Language_pschist.Description"
#define LANGUAGE_PSCHIST_FK_LANGUAGE_TEXTPLACEMENT_FIELD "FK_Language_TextPlacement"
#define LANGUAGE_PSCHIST_FK_LANGUAGE_TEXTPLACEMENT_TABLE_FIELD "Language_pschist.FK_Language_TextPlacement"
#define LANGUAGE_PSCHIST_PSC_ID_FIELD "psc_id"
#define LANGUAGE_PSCHIST_PSC_ID_TABLE_FIELD "Language_pschist.psc_id"
#define LANGUAGE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define LANGUAGE_PSCHIST_PSC_BATCH_TABLE_FIELD "Language_pschist.psc_batch"
#define LANGUAGE_PSCHIST_PSC_USER_FIELD "psc_user"
#define LANGUAGE_PSCHIST_PSC_USER_TABLE_FIELD "Language_pschist.psc_user"
#define LANGUAGE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define LANGUAGE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Language_pschist.psc_frozen"
#define LANGUAGE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define LANGUAGE_PSCHIST_PSC_MOD_TABLE_FIELD "Language_pschist.psc_mod"
#define LANGUAGE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define LANGUAGE_PSCHIST_PSC_TOC_TABLE_FIELD "Language_pschist.psc_toc"
#define LANGUAGE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define LANGUAGE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Language_pschist.psc_restrict"


#endif

