#ifndef __Define_Installation_Users_pschist_H__
#define __Define_Installation_Users_pschist_H__


#define INSTALLATION_USERS_PSCHIST_TABLE "Installation_Users_pschist"
#define INSTALLATION_USERS_PSCHIST_FK_INSTALLATION_FIELD "FK_Installation"
#define INSTALLATION_USERS_PSCHIST_FK_INSTALLATION_TABLE_FIELD "Installation_Users_pschist.FK_Installation"
#define INSTALLATION_USERS_PSCHIST_FK_USERS_FIELD "FK_Users"
#define INSTALLATION_USERS_PSCHIST_FK_USERS_TABLE_FIELD "Installation_Users_pschist.FK_Users"
#define INSTALLATION_USERS_PSCHIST_USERCANMODIFYINSTALLATION_FIELD "userCanModifyInstallation"
#define INSTALLATION_USERS_PSCHIST_USERCANMODIFYINSTALLATION_TABLE_FIELD "Installation_Users_pschist.userCanModifyInstallation"
#define INSTALLATION_USERS_PSCHIST_USERCANCHANGEHOUSEMODE_FIELD "userCanChangeHouseMode"
#define INSTALLATION_USERS_PSCHIST_USERCANCHANGEHOUSEMODE_TABLE_FIELD "Installation_Users_pschist.userCanChangeHouseMode"
#define INSTALLATION_USERS_PSCHIST_PSC_ID_FIELD "psc_id"
#define INSTALLATION_USERS_PSCHIST_PSC_ID_TABLE_FIELD "Installation_Users_pschist.psc_id"
#define INSTALLATION_USERS_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define INSTALLATION_USERS_PSCHIST_PSC_BATCH_TABLE_FIELD "Installation_Users_pschist.psc_batch"
#define INSTALLATION_USERS_PSCHIST_PSC_USER_FIELD "psc_user"
#define INSTALLATION_USERS_PSCHIST_PSC_USER_TABLE_FIELD "Installation_Users_pschist.psc_user"
#define INSTALLATION_USERS_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define INSTALLATION_USERS_PSCHIST_PSC_FROZEN_TABLE_FIELD "Installation_Users_pschist.psc_frozen"
#define INSTALLATION_USERS_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define INSTALLATION_USERS_PSCHIST_PSC_MOD_TABLE_FIELD "Installation_Users_pschist.psc_mod"
#define INSTALLATION_USERS_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define INSTALLATION_USERS_PSCHIST_PSC_TOC_TABLE_FIELD "Installation_Users_pschist.psc_toc"
#define INSTALLATION_USERS_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define INSTALLATION_USERS_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Installation_Users_pschist.psc_restrict"


#endif

