#ifndef __Define_CommandCategory_pschist_H__
#define __Define_CommandCategory_pschist_H__


#define COMMANDCATEGORY_PSCHIST_TABLE "CommandCategory_pschist"
#define COMMANDCATEGORY_PSCHIST_PK_COMMANDCATEGORY_FIELD "PK_CommandCategory"
#define COMMANDCATEGORY_PSCHIST_PK_COMMANDCATEGORY_TABLE_FIELD "CommandCategory_pschist.PK_CommandCategory"
#define COMMANDCATEGORY_PSCHIST_FK_COMMANDCATEGORY_PARENT_FIELD "FK_CommandCategory_Parent"
#define COMMANDCATEGORY_PSCHIST_FK_COMMANDCATEGORY_PARENT_TABLE_FIELD "CommandCategory_pschist.FK_CommandCategory_Parent"
#define COMMANDCATEGORY_PSCHIST_DESCRIPTION_FIELD "Description"
#define COMMANDCATEGORY_PSCHIST_DESCRIPTION_TABLE_FIELD "CommandCategory_pschist.Description"
#define COMMANDCATEGORY_PSCHIST_PSC_ID_FIELD "psc_id"
#define COMMANDCATEGORY_PSCHIST_PSC_ID_TABLE_FIELD "CommandCategory_pschist.psc_id"
#define COMMANDCATEGORY_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define COMMANDCATEGORY_PSCHIST_PSC_BATCH_TABLE_FIELD "CommandCategory_pschist.psc_batch"
#define COMMANDCATEGORY_PSCHIST_PSC_USER_FIELD "psc_user"
#define COMMANDCATEGORY_PSCHIST_PSC_USER_TABLE_FIELD "CommandCategory_pschist.psc_user"
#define COMMANDCATEGORY_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define COMMANDCATEGORY_PSCHIST_PSC_FROZEN_TABLE_FIELD "CommandCategory_pschist.psc_frozen"
#define COMMANDCATEGORY_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define COMMANDCATEGORY_PSCHIST_PSC_MOD_TABLE_FIELD "CommandCategory_pschist.psc_mod"
#define COMMANDCATEGORY_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define COMMANDCATEGORY_PSCHIST_PSC_TOC_TABLE_FIELD "CommandCategory_pschist.psc_toc"
#define COMMANDCATEGORY_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMANDCATEGORY_PSCHIST_PSC_RESTRICT_TABLE_FIELD "CommandCategory_pschist.psc_restrict"


#endif

