#ifndef __Define_HorizAlignment_pschist_H__
#define __Define_HorizAlignment_pschist_H__


#define HORIZALIGNMENT_PSCHIST_TABLE "HorizAlignment_pschist"
#define HORIZALIGNMENT_PSCHIST_PK_HORIZALIGNMENT_FIELD "PK_HorizAlignment"
#define HORIZALIGNMENT_PSCHIST_PK_HORIZALIGNMENT_TABLE_FIELD "HorizAlignment_pschist.PK_HorizAlignment"
#define HORIZALIGNMENT_PSCHIST_DESCRIPTION_FIELD "Description"
#define HORIZALIGNMENT_PSCHIST_DESCRIPTION_TABLE_FIELD "HorizAlignment_pschist.Description"
#define HORIZALIGNMENT_PSCHIST_DEFINE_FIELD "Define"
#define HORIZALIGNMENT_PSCHIST_DEFINE_TABLE_FIELD "HorizAlignment_pschist.Define"
#define HORIZALIGNMENT_PSCHIST_PSC_ID_FIELD "psc_id"
#define HORIZALIGNMENT_PSCHIST_PSC_ID_TABLE_FIELD "HorizAlignment_pschist.psc_id"
#define HORIZALIGNMENT_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define HORIZALIGNMENT_PSCHIST_PSC_BATCH_TABLE_FIELD "HorizAlignment_pschist.psc_batch"
#define HORIZALIGNMENT_PSCHIST_PSC_USER_FIELD "psc_user"
#define HORIZALIGNMENT_PSCHIST_PSC_USER_TABLE_FIELD "HorizAlignment_pschist.psc_user"
#define HORIZALIGNMENT_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define HORIZALIGNMENT_PSCHIST_PSC_FROZEN_TABLE_FIELD "HorizAlignment_pschist.psc_frozen"
#define HORIZALIGNMENT_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define HORIZALIGNMENT_PSCHIST_PSC_MOD_TABLE_FIELD "HorizAlignment_pschist.psc_mod"
#define HORIZALIGNMENT_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define HORIZALIGNMENT_PSCHIST_PSC_TOC_TABLE_FIELD "HorizAlignment_pschist.psc_toc"
#define HORIZALIGNMENT_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define HORIZALIGNMENT_PSCHIST_PSC_RESTRICT_TABLE_FIELD "HorizAlignment_pschist.psc_restrict"


#endif

