#ifndef __Define_CommandGroup_Room_pschist_H__
#define __Define_CommandGroup_Room_pschist_H__


#define COMMANDGROUP_ROOM_PSCHIST_TABLE "CommandGroup_Room_pschist"
#define COMMANDGROUP_ROOM_PSCHIST_FK_COMMANDGROUP_FIELD "FK_CommandGroup"
#define COMMANDGROUP_ROOM_PSCHIST_FK_COMMANDGROUP_TABLE_FIELD "CommandGroup_Room_pschist.FK_CommandGroup"
#define COMMANDGROUP_ROOM_PSCHIST_FK_ROOM_FIELD "FK_Room"
#define COMMANDGROUP_ROOM_PSCHIST_FK_ROOM_TABLE_FIELD "CommandGroup_Room_pschist.FK_Room"
#define COMMANDGROUP_ROOM_PSCHIST_SORT_FIELD "Sort"
#define COMMANDGROUP_ROOM_PSCHIST_SORT_TABLE_FIELD "CommandGroup_Room_pschist.Sort"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_ID_FIELD "psc_id"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_ID_TABLE_FIELD "CommandGroup_Room_pschist.psc_id"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_BATCH_TABLE_FIELD "CommandGroup_Room_pschist.psc_batch"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_USER_FIELD "psc_user"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_USER_TABLE_FIELD "CommandGroup_Room_pschist.psc_user"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_FROZEN_TABLE_FIELD "CommandGroup_Room_pschist.psc_frozen"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_MOD_TABLE_FIELD "CommandGroup_Room_pschist.psc_mod"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_TOC_TABLE_FIELD "CommandGroup_Room_pschist.psc_toc"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMANDGROUP_ROOM_PSCHIST_PSC_RESTRICT_TABLE_FIELD "CommandGroup_Room_pschist.psc_restrict"


#endif

