#ifndef __Define_ConnectorType_pschmask_H__
#define __Define_ConnectorType_pschmask_H__


#define CONNECTORTYPE_PSCHMASK_TABLE "ConnectorType_pschmask"
#define CONNECTORTYPE_PSCHMASK_PK_CONNECTORTYPE_FIELD "PK_ConnectorType"
#define CONNECTORTYPE_PSCHMASK_PK_CONNECTORTYPE_TABLE_FIELD "ConnectorType_pschmask.PK_ConnectorType"
#define CONNECTORTYPE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define CONNECTORTYPE_PSCHMASK_DESCRIPTION_TABLE_FIELD "ConnectorType_pschmask.Description"
#define CONNECTORTYPE_PSCHMASK_DEFINE_FIELD "Define"
#define CONNECTORTYPE_PSCHMASK_DEFINE_TABLE_FIELD "ConnectorType_pschmask.Define"
#define CONNECTORTYPE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define CONNECTORTYPE_PSCHMASK_PSC_ID_TABLE_FIELD "ConnectorType_pschmask.psc_id"
#define CONNECTORTYPE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define CONNECTORTYPE_PSCHMASK_PSC_BATCH_TABLE_FIELD "ConnectorType_pschmask.psc_batch"
#define CONNECTORTYPE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define CONNECTORTYPE_PSCHMASK_PSC_USER_TABLE_FIELD "ConnectorType_pschmask.psc_user"
#define CONNECTORTYPE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define CONNECTORTYPE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "ConnectorType_pschmask.psc_frozen"
#define CONNECTORTYPE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define CONNECTORTYPE_PSCHMASK_PSC_MOD_TABLE_FIELD "ConnectorType_pschmask.psc_mod"
#define CONNECTORTYPE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define CONNECTORTYPE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "ConnectorType_pschmask.psc_restrict"


#endif

