#ifndef __Define_ConfigType_pschist_H__
#define __Define_ConfigType_pschist_H__


#define CONFIGTYPE_PSCHIST_TABLE "ConfigType_pschist"
#define CONFIGTYPE_PSCHIST_PK_CONFIGTYPE_FIELD "PK_ConfigType"
#define CONFIGTYPE_PSCHIST_PK_CONFIGTYPE_TABLE_FIELD "ConfigType_pschist.PK_ConfigType"
#define CONFIGTYPE_PSCHIST_DESCRIPTION_FIELD "Description"
#define CONFIGTYPE_PSCHIST_DESCRIPTION_TABLE_FIELD "ConfigType_pschist.Description"
#define CONFIGTYPE_PSCHIST_DEFINE_FIELD "Define"
#define CONFIGTYPE_PSCHIST_DEFINE_TABLE_FIELD "ConfigType_pschist.Define"
#define CONFIGTYPE_PSCHIST_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define CONFIGTYPE_PSCHIST_FK_DEVICETEMPLATE_TABLE_FIELD "ConfigType_pschist.FK_DeviceTemplate"
#define CONFIGTYPE_PSCHIST_FK_DEVICECATEGORY_FIELD "FK_DeviceCategory"
#define CONFIGTYPE_PSCHIST_FK_DEVICECATEGORY_TABLE_FIELD "ConfigType_pschist.FK_DeviceCategory"
#define CONFIGTYPE_PSCHIST_PSC_ID_FIELD "psc_id"
#define CONFIGTYPE_PSCHIST_PSC_ID_TABLE_FIELD "ConfigType_pschist.psc_id"
#define CONFIGTYPE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define CONFIGTYPE_PSCHIST_PSC_BATCH_TABLE_FIELD "ConfigType_pschist.psc_batch"
#define CONFIGTYPE_PSCHIST_PSC_USER_FIELD "psc_user"
#define CONFIGTYPE_PSCHIST_PSC_USER_TABLE_FIELD "ConfigType_pschist.psc_user"
#define CONFIGTYPE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define CONFIGTYPE_PSCHIST_PSC_FROZEN_TABLE_FIELD "ConfigType_pschist.psc_frozen"
#define CONFIGTYPE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define CONFIGTYPE_PSCHIST_PSC_MOD_TABLE_FIELD "ConfigType_pschist.psc_mod"
#define CONFIGTYPE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define CONFIGTYPE_PSCHIST_PSC_TOC_TABLE_FIELD "ConfigType_pschist.psc_toc"
#define CONFIGTYPE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define CONFIGTYPE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "ConfigType_pschist.psc_restrict"


#endif

