#ifndef __Define_Device_HouseMode_pschist_H__
#define __Define_Device_HouseMode_pschist_H__


#define DEVICE_HOUSEMODE_PSCHIST_TABLE "Device_HouseMode_pschist"
#define DEVICE_HOUSEMODE_PSCHIST_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_HOUSEMODE_PSCHIST_FK_DEVICE_TABLE_FIELD "Device_HouseMode_pschist.FK_Device"
#define DEVICE_HOUSEMODE_PSCHIST_FK_HOUSEMODE_FIELD "FK_HouseMode"
#define DEVICE_HOUSEMODE_PSCHIST_FK_HOUSEMODE_TABLE_FIELD "Device_HouseMode_pschist.FK_HouseMode"
#define DEVICE_HOUSEMODE_PSCHIST_FK_EVENT_FIELD "FK_Event"
#define DEVICE_HOUSEMODE_PSCHIST_FK_EVENT_TABLE_FIELD "Device_HouseMode_pschist.FK_Event"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_ID_FIELD "psc_id"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_ID_TABLE_FIELD "Device_HouseMode_pschist.psc_id"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_BATCH_TABLE_FIELD "Device_HouseMode_pschist.psc_batch"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_USER_FIELD "psc_user"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_USER_TABLE_FIELD "Device_HouseMode_pschist.psc_user"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Device_HouseMode_pschist.psc_frozen"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_MOD_TABLE_FIELD "Device_HouseMode_pschist.psc_mod"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_TOC_TABLE_FIELD "Device_HouseMode_pschist.psc_toc"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_HOUSEMODE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Device_HouseMode_pschist.psc_restrict"


#endif

