#ifndef __Define_EffectType_pschmask_H__
#define __Define_EffectType_pschmask_H__


#define EFFECTTYPE_PSCHMASK_TABLE "EffectType_pschmask"
#define EFFECTTYPE_PSCHMASK_PK_EFFECTTYPE_FIELD "PK_EffectType"
#define EFFECTTYPE_PSCHMASK_PK_EFFECTTYPE_TABLE_FIELD "EffectType_pschmask.PK_EffectType"
#define EFFECTTYPE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define EFFECTTYPE_PSCHMASK_DESCRIPTION_TABLE_FIELD "EffectType_pschmask.Description"
#define EFFECTTYPE_PSCHMASK_DEFINE_FIELD "Define"
#define EFFECTTYPE_PSCHMASK_DEFINE_TABLE_FIELD "EffectType_pschmask.Define"
#define EFFECTTYPE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define EFFECTTYPE_PSCHMASK_PSC_ID_TABLE_FIELD "EffectType_pschmask.psc_id"
#define EFFECTTYPE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define EFFECTTYPE_PSCHMASK_PSC_BATCH_TABLE_FIELD "EffectType_pschmask.psc_batch"
#define EFFECTTYPE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define EFFECTTYPE_PSCHMASK_PSC_USER_TABLE_FIELD "EffectType_pschmask.psc_user"
#define EFFECTTYPE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define EFFECTTYPE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "EffectType_pschmask.psc_frozen"
#define EFFECTTYPE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define EFFECTTYPE_PSCHMASK_PSC_MOD_TABLE_FIELD "EffectType_pschmask.psc_mod"
#define EFFECTTYPE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define EFFECTTYPE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "EffectType_pschmask.psc_restrict"


#endif

