#ifndef __Define_TextCategory_pschmask_H__
#define __Define_TextCategory_pschmask_H__


#define TEXTCATEGORY_PSCHMASK_TABLE "TextCategory_pschmask"
#define TEXTCATEGORY_PSCHMASK_PK_TEXTCATEGORY_FIELD "PK_TextCategory"
#define TEXTCATEGORY_PSCHMASK_PK_TEXTCATEGORY_TABLE_FIELD "TextCategory_pschmask.PK_TextCategory"
#define TEXTCATEGORY_PSCHMASK_FK_TEXTCATEGORY_PARENT_FIELD "FK_TextCategory_Parent"
#define TEXTCATEGORY_PSCHMASK_FK_TEXTCATEGORY_PARENT_TABLE_FIELD "TextCategory_pschmask.FK_TextCategory_Parent"
#define TEXTCATEGORY_PSCHMASK_DESCRIPTION_FIELD "Description"
#define TEXTCATEGORY_PSCHMASK_DESCRIPTION_TABLE_FIELD "TextCategory_pschmask.Description"
#define TEXTCATEGORY_PSCHMASK_PSC_ID_FIELD "psc_id"
#define TEXTCATEGORY_PSCHMASK_PSC_ID_TABLE_FIELD "TextCategory_pschmask.psc_id"
#define TEXTCATEGORY_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define TEXTCATEGORY_PSCHMASK_PSC_BATCH_TABLE_FIELD "TextCategory_pschmask.psc_batch"
#define TEXTCATEGORY_PSCHMASK_PSC_USER_FIELD "psc_user"
#define TEXTCATEGORY_PSCHMASK_PSC_USER_TABLE_FIELD "TextCategory_pschmask.psc_user"
#define TEXTCATEGORY_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define TEXTCATEGORY_PSCHMASK_PSC_FROZEN_TABLE_FIELD "TextCategory_pschmask.psc_frozen"
#define TEXTCATEGORY_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define TEXTCATEGORY_PSCHMASK_PSC_MOD_TABLE_FIELD "TextCategory_pschmask.psc_mod"
#define TEXTCATEGORY_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define TEXTCATEGORY_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "TextCategory_pschmask.psc_restrict"


#endif

