#ifndef __Define_CannedEvents_pschist_H__
#define __Define_CannedEvents_pschist_H__


#define CANNEDEVENTS_PSCHIST_TABLE "CannedEvents_pschist"
#define CANNEDEVENTS_PSCHIST_PK_CANNEDEVENTS_FIELD "PK_CannedEvents"
#define CANNEDEVENTS_PSCHIST_PK_CANNEDEVENTS_TABLE_FIELD "CannedEvents_pschist.PK_CannedEvents"
#define CANNEDEVENTS_PSCHIST_DESCRIPTION_FIELD "Description"
#define CANNEDEVENTS_PSCHIST_DESCRIPTION_TABLE_FIELD "CannedEvents_pschist.Description"
#define CANNEDEVENTS_PSCHIST_FK_EVENT_FIELD "FK_Event"
#define CANNEDEVENTS_PSCHIST_FK_EVENT_TABLE_FIELD "CannedEvents_pschist.FK_Event"
#define CANNEDEVENTS_PSCHIST_BISAND_FIELD "bIsAnd"
#define CANNEDEVENTS_PSCHIST_BISAND_TABLE_FIELD "CannedEvents_pschist.bIsAnd"
#define CANNEDEVENTS_PSCHIST_BISNOT_FIELD "bIsNot"
#define CANNEDEVENTS_PSCHIST_BISNOT_TABLE_FIELD "CannedEvents_pschist.bIsNot"
#define CANNEDEVENTS_PSCHIST_PSC_ID_FIELD "psc_id"
#define CANNEDEVENTS_PSCHIST_PSC_ID_TABLE_FIELD "CannedEvents_pschist.psc_id"
#define CANNEDEVENTS_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define CANNEDEVENTS_PSCHIST_PSC_BATCH_TABLE_FIELD "CannedEvents_pschist.psc_batch"
#define CANNEDEVENTS_PSCHIST_PSC_USER_FIELD "psc_user"
#define CANNEDEVENTS_PSCHIST_PSC_USER_TABLE_FIELD "CannedEvents_pschist.psc_user"
#define CANNEDEVENTS_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define CANNEDEVENTS_PSCHIST_PSC_FROZEN_TABLE_FIELD "CannedEvents_pschist.psc_frozen"
#define CANNEDEVENTS_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define CANNEDEVENTS_PSCHIST_PSC_MOD_TABLE_FIELD "CannedEvents_pschist.psc_mod"
#define CANNEDEVENTS_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define CANNEDEVENTS_PSCHIST_PSC_TOC_TABLE_FIELD "CannedEvents_pschist.psc_toc"
#define CANNEDEVENTS_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define CANNEDEVENTS_PSCHIST_PSC_RESTRICT_TABLE_FIELD "CannedEvents_pschist.psc_restrict"


#endif

