#ifndef __Define_Package_Users_pschist_H__
#define __Define_Package_Users_pschist_H__


#define PACKAGE_USERS_PSCHIST_TABLE "Package_Users_pschist"
#define PACKAGE_USERS_PSCHIST_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_USERS_PSCHIST_FK_PACKAGE_TABLE_FIELD "Package_Users_pschist.FK_Package"
#define PACKAGE_USERS_PSCHIST_FK_USERS_FIELD "FK_Users"
#define PACKAGE_USERS_PSCHIST_FK_USERS_TABLE_FIELD "Package_Users_pschist.FK_Users"
#define PACKAGE_USERS_PSCHIST_ADMINISTRATOR_FIELD "Administrator"
#define PACKAGE_USERS_PSCHIST_ADMINISTRATOR_TABLE_FIELD "Package_Users_pschist.Administrator"
#define PACKAGE_USERS_PSCHIST_COMMENTS_FIELD "Comments"
#define PACKAGE_USERS_PSCHIST_COMMENTS_TABLE_FIELD "Package_Users_pschist.Comments"
#define PACKAGE_USERS_PSCHIST_PSC_ID_FIELD "psc_id"
#define PACKAGE_USERS_PSCHIST_PSC_ID_TABLE_FIELD "Package_Users_pschist.psc_id"
#define PACKAGE_USERS_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_USERS_PSCHIST_PSC_BATCH_TABLE_FIELD "Package_Users_pschist.psc_batch"
#define PACKAGE_USERS_PSCHIST_PSC_USER_FIELD "psc_user"
#define PACKAGE_USERS_PSCHIST_PSC_USER_TABLE_FIELD "Package_Users_pschist.psc_user"
#define PACKAGE_USERS_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_USERS_PSCHIST_PSC_FROZEN_TABLE_FIELD "Package_Users_pschist.psc_frozen"
#define PACKAGE_USERS_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_USERS_PSCHIST_PSC_MOD_TABLE_FIELD "Package_Users_pschist.psc_mod"
#define PACKAGE_USERS_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PACKAGE_USERS_PSCHIST_PSC_TOC_TABLE_FIELD "Package_Users_pschist.psc_toc"
#define PACKAGE_USERS_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_USERS_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Package_Users_pschist.psc_restrict"


#endif

