#ifndef __Define_Language_pschmask_H__
#define __Define_Language_pschmask_H__


#define LANGUAGE_PSCHMASK_TABLE "Language_pschmask"
#define LANGUAGE_PSCHMASK_PK_LANGUAGE_FIELD "PK_Language"
#define LANGUAGE_PSCHMASK_PK_LANGUAGE_TABLE_FIELD "Language_pschmask.PK_Language"
#define LANGUAGE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define LANGUAGE_PSCHMASK_DESCRIPTION_TABLE_FIELD "Language_pschmask.Description"
#define LANGUAGE_PSCHMASK_FK_LANGUAGE_TEXTPLACEMENT_FIELD "FK_Language_TextPlacement"
#define LANGUAGE_PSCHMASK_FK_LANGUAGE_TEXTPLACEMENT_TABLE_FIELD "Language_pschmask.FK_Language_TextPlacement"
#define LANGUAGE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define LANGUAGE_PSCHMASK_PSC_ID_TABLE_FIELD "Language_pschmask.psc_id"
#define LANGUAGE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define LANGUAGE_PSCHMASK_PSC_BATCH_TABLE_FIELD "Language_pschmask.psc_batch"
#define LANGUAGE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define LANGUAGE_PSCHMASK_PSC_USER_TABLE_FIELD "Language_pschmask.psc_user"
#define LANGUAGE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define LANGUAGE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Language_pschmask.psc_frozen"
#define LANGUAGE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define LANGUAGE_PSCHMASK_PSC_MOD_TABLE_FIELD "Language_pschmask.psc_mod"
#define LANGUAGE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define LANGUAGE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Language_pschmask.psc_restrict"


#endif

