#ifndef __Define_PnpQueue_H__
#define __Define_PnpQueue_H__


#define PNPQUEUE_TABLE "PnpQueue"
#define PNPQUEUE_PK_PNPQUEUE_FIELD "PK_PnpQueue"
#define PNPQUEUE_PK_PNPQUEUE_TABLE_FIELD "PnpQueue.PK_PnpQueue"
#define PNPQUEUE_DETECTEDDATE_FIELD "DetectedDate"
#define PNPQUEUE_DETECTEDDATE_TABLE_FIELD "PnpQueue.DetectedDate"
#define PNPQUEUE_VENDORMODELID_FIELD "VendorModelId"
#define PNPQUEUE_VENDORMODELID_TABLE_FIELD "PnpQueue.VendorModelId"
#define PNPQUEUE_PATH_FIELD "Path"
#define PNPQUEUE_PATH_TABLE_FIELD "PnpQueue.Path"
#define PNPQUEUE_IPADDRESS_FIELD "IPaddress"
#define PNPQUEUE_IPADDRESS_TABLE_FIELD "PnpQueue.IPaddress"
#define PNPQUEUE_MACADDRESS_FIELD "MACaddress"
#define PNPQUEUE_MACADDRESS_TABLE_FIELD "PnpQueue.MACaddress"
#define PNPQUEUE_CATEGORY_FIELD "Category"
#define PNPQUEUE_CATEGORY_TABLE_FIELD "PnpQueue.Category"
#define PNPQUEUE_SERIALNUMBER_FIELD "SerialNumber"
#define PNPQUEUE_SERIALNUMBER_TABLE_FIELD "PnpQueue.SerialNumber"
#define PNPQUEUE_FK_COMMMETHOD_FIELD "FK_CommMethod"
#define PNPQUEUE_FK_COMMMETHOD_TABLE_FIELD "PnpQueue.FK_CommMethod"
#define PNPQUEUE_FK_PNPPROTOCOL_FIELD "FK_PnpProtocol"
#define PNPQUEUE_FK_PNPPROTOCOL_TABLE_FIELD "PnpQueue.FK_PnpProtocol"
#define PNPQUEUE_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define PNPQUEUE_FK_DEVICETEMPLATE_TABLE_FIELD "PnpQueue.FK_DeviceTemplate"
#define PNPQUEUE_FK_DEVICE_CREATED_FIELD "FK_Device_Created"
#define PNPQUEUE_FK_DEVICE_CREATED_TABLE_FIELD "PnpQueue.FK_Device_Created"
#define PNPQUEUE_FK_DEVICE_REPORTED_FIELD "FK_Device_Reported"
#define PNPQUEUE_FK_DEVICE_REPORTED_TABLE_FIELD "PnpQueue.FK_Device_Reported"
#define PNPQUEUE_SIGNATURE_FIELD "Signature"
#define PNPQUEUE_SIGNATURE_TABLE_FIELD "PnpQueue.Signature"
#define PNPQUEUE_REMOVED_FIELD "Removed"
#define PNPQUEUE_REMOVED_TABLE_FIELD "PnpQueue.Removed"
#define PNPQUEUE_STAGE_FIELD "Stage"
#define PNPQUEUE_STAGE_TABLE_FIELD "PnpQueue.Stage"
#define PNPQUEUE_PROCESSED_FIELD "Processed"
#define PNPQUEUE_PROCESSED_TABLE_FIELD "PnpQueue.Processed"
#define PNPQUEUE_PARMS_FIELD "Parms"
#define PNPQUEUE_PARMS_TABLE_FIELD "PnpQueue.Parms"
#define PNPQUEUE_PSC_ID_FIELD "psc_id"
#define PNPQUEUE_PSC_ID_TABLE_FIELD "PnpQueue.psc_id"
#define PNPQUEUE_PSC_BATCH_FIELD "psc_batch"
#define PNPQUEUE_PSC_BATCH_TABLE_FIELD "PnpQueue.psc_batch"
#define PNPQUEUE_PSC_USER_FIELD "psc_user"
#define PNPQUEUE_PSC_USER_TABLE_FIELD "PnpQueue.psc_user"
#define PNPQUEUE_PSC_FROZEN_FIELD "psc_frozen"
#define PNPQUEUE_PSC_FROZEN_TABLE_FIELD "PnpQueue.psc_frozen"
#define PNPQUEUE_PSC_MOD_FIELD "psc_mod"
#define PNPQUEUE_PSC_MOD_TABLE_FIELD "PnpQueue.psc_mod"
#define PNPQUEUE_PSC_RESTRICT_FIELD "psc_restrict"
#define PNPQUEUE_PSC_RESTRICT_TABLE_FIELD "PnpQueue.psc_restrict"


#endif

