#ifndef __Define_CommMethod_pschist_H__
#define __Define_CommMethod_pschist_H__


#define COMMMETHOD_PSCHIST_TABLE "CommMethod_pschist"
#define COMMMETHOD_PSCHIST_PK_COMMMETHOD_FIELD "PK_CommMethod"
#define COMMMETHOD_PSCHIST_PK_COMMMETHOD_TABLE_FIELD "CommMethod_pschist.PK_CommMethod"
#define COMMMETHOD_PSCHIST_DESCRIPTION_FIELD "Description"
#define COMMMETHOD_PSCHIST_DESCRIPTION_TABLE_FIELD "CommMethod_pschist.Description"
#define COMMMETHOD_PSCHIST_DEFINE_FIELD "Define"
#define COMMMETHOD_PSCHIST_DEFINE_TABLE_FIELD "CommMethod_pschist.Define"
#define COMMMETHOD_PSCHIST_PSC_ID_FIELD "psc_id"
#define COMMMETHOD_PSCHIST_PSC_ID_TABLE_FIELD "CommMethod_pschist.psc_id"
#define COMMMETHOD_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define COMMMETHOD_PSCHIST_PSC_BATCH_TABLE_FIELD "CommMethod_pschist.psc_batch"
#define COMMMETHOD_PSCHIST_PSC_USER_FIELD "psc_user"
#define COMMMETHOD_PSCHIST_PSC_USER_TABLE_FIELD "CommMethod_pschist.psc_user"
#define COMMMETHOD_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define COMMMETHOD_PSCHIST_PSC_FROZEN_TABLE_FIELD "CommMethod_pschist.psc_frozen"
#define COMMMETHOD_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define COMMMETHOD_PSCHIST_PSC_MOD_TABLE_FIELD "CommMethod_pschist.psc_mod"
#define COMMMETHOD_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMMETHOD_PSCHIST_PSC_RESTRICT_TABLE_FIELD "CommMethod_pschist.psc_restrict"
#define COMMMETHOD_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define COMMMETHOD_PSCHIST_PSC_TOC_TABLE_FIELD "CommMethod_pschist.psc_toc"


#endif

