#ifndef __Define_ConnectorType_pschist_H__
#define __Define_ConnectorType_pschist_H__


#define CONNECTORTYPE_PSCHIST_TABLE "ConnectorType_pschist"
#define CONNECTORTYPE_PSCHIST_PK_CONNECTORTYPE_FIELD "PK_ConnectorType"
#define CONNECTORTYPE_PSCHIST_PK_CONNECTORTYPE_TABLE_FIELD "ConnectorType_pschist.PK_ConnectorType"
#define CONNECTORTYPE_PSCHIST_DESCRIPTION_FIELD "Description"
#define CONNECTORTYPE_PSCHIST_DESCRIPTION_TABLE_FIELD "ConnectorType_pschist.Description"
#define CONNECTORTYPE_PSCHIST_DEFINE_FIELD "Define"
#define CONNECTORTYPE_PSCHIST_DEFINE_TABLE_FIELD "ConnectorType_pschist.Define"
#define CONNECTORTYPE_PSCHIST_PSC_ID_FIELD "psc_id"
#define CONNECTORTYPE_PSCHIST_PSC_ID_TABLE_FIELD "ConnectorType_pschist.psc_id"
#define CONNECTORTYPE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define CONNECTORTYPE_PSCHIST_PSC_BATCH_TABLE_FIELD "ConnectorType_pschist.psc_batch"
#define CONNECTORTYPE_PSCHIST_PSC_USER_FIELD "psc_user"
#define CONNECTORTYPE_PSCHIST_PSC_USER_TABLE_FIELD "ConnectorType_pschist.psc_user"
#define CONNECTORTYPE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define CONNECTORTYPE_PSCHIST_PSC_FROZEN_TABLE_FIELD "ConnectorType_pschist.psc_frozen"
#define CONNECTORTYPE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define CONNECTORTYPE_PSCHIST_PSC_MOD_TABLE_FIELD "ConnectorType_pschist.psc_mod"
#define CONNECTORTYPE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define CONNECTORTYPE_PSCHIST_PSC_TOC_TABLE_FIELD "ConnectorType_pschist.psc_toc"
#define CONNECTORTYPE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define CONNECTORTYPE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "ConnectorType_pschist.psc_restrict"


#endif

