#ifndef __Define_Text_H__
#define __Define_Text_H__

#define TEXT_ARRAY_DESCRIPTION_CONST 316
#define TEXT_MORE_CONST 317
#define TEXT_DROP_CALL_CONST 318
#define TEXT_ANSWER_HERE_CONST 320
#define TEXT_SEND_VM_CONST 321
#define TEXT_MOVE_CALL_CONST 322
#define TEXT_TRANSFER_CONST 323
#define TEXT_CALLER_NAME_CONST 324
#define TEXT_CALLER_NUMBER_CONST 325
#define TEXT_NO_VIDEO_CONST 326
#define TEXT_INCOMING_CALL_CONST 327
#define TEXT_CALL_MNGR_CONST 328
#define TEXT_USER_STATS_CONST 329
#define TEXT_CALL_PB_CONST 343
#define TEXT_CALL_DNUM_CONST 344
#define TEXT_CALL_SPEED_CONST 345
#define TEXT_CALL_PLUTO_CONST 346
#define TEXT_USR_ENTRY_CONST 347
#define TEXT_CALL_CONST 348
#define TEXT_A_CONST 351
#define TEXT_B_CONST 352
#define TEXT_C_CONST 353
#define TEXT_D_CONST 354
#define TEXT_E_CONST 355
#define TEXT_F_CONST 356
#define TEXT_G_CONST 357
#define TEXT_H_CONST 358
#define TEXT_I_CONST 359
#define TEXT_J_CONST 360
#define TEXT_K_CONST 361
#define TEXT_L_CONST 362
#define TEXT_M_CONST 363
#define TEXT_N_CONST 364
#define TEXT_O_CONST 365
#define TEXT_P_CONST 366
#define TEXT_Q_CONST 367
#define TEXT_R_CONST 368
#define TEXT_S_CONST 369
#define TEXT_T_CONST 370
#define TEXT_U_CONST 371
#define TEXT_V_CONST 372
#define TEXT_W_CONST 373
#define TEXT_X_CONST 374
#define TEXT_Y_CONST 375
#define TEXT_Z_CONST 376
#define TEXT_1_CONST 377
#define TEXT_2_CONST 378
#define TEXT_3_CONST 379
#define TEXT_4_CONST 380
#define TEXT_5_CONST 381
#define TEXT_6_CONST 382
#define TEXT_7_CONST 383
#define TEXT_8_CONST 384
#define TEXT_9_CONST 385
#define TEXT_0_CONST 386
#define TEXT_SPACE_CONST 388
#define TEXT_RECENT_CALLS_CONST 389
#define TEXT_SPEED_DIAL_CONST 390
#define TEXT_SECURITY_ALERTS_CONST 394
#define TEXT_TRIPPED_SENSOR_CONST 395
#define TEXT_SEC_ALERTS_CONST 396
#define TEXT_TRIPPED_SENSORS_CONST 397
#define TEXT_CONNECTION_LOST_CONST 398
#define TEXT_ALERT_CONST 399
#define TEXT_Location_Description_CONST 400
#define TEXT_TOUCHSCREEN_UNLOCK_CONST 401
#define TEXT_ASK_TO_LEAVE_CONST 402
#define TEXT_CAMERA1_CONST 403
#define TEXT_CAMERA2_CONST 404
#define TEXT_CAMERA3_CONST 405
#define TEXT_CAMERA4_CONST 406
#define TEXT_GO_CONST 407
#define TEXT_EPG_SHOW_PREVIEW_CONST 408
#define TEXT_SEARCH_TITLE_CONST 409
#define TEXT_SEARCH_CREDITS_CONST 410
#define TEXT_SEARCH_GENRE_CONST 411
#define TEXT_SEARCH_YEAR_CONST 412
#define TEXT_SEARCH_RATING_CONST 413
#define TEXT_SEACH_ALL_CONST 414
#define TEXT_SEARCH_BY_DESC_CONST 415
#define TEXT_SHOW_STARS_DESC_CONST 416
#define TEXT_SEARCH_SHOW_DESC_CONST 417
#define TEXT_SEARCH_TV_RATING_CONST 418
#define TEXT_PVR_FUTURE_RECORD_CONST 419
#define TEXT_PVR_RECORD_FUTURE_NEW_CONST 420
#define TEXT_PVR_FUTURE_REC_EPISODE_CONST 421
#define TEXT_AUTOMATICALLY_TUNE_CONST 422
#define TEXT_PVR_RECORD_BUSY_CONST 423
#define TEXT_PVR_DONT_RECORD_CONST 424
#define TEXT_PVR_SKIP_RECORDING_CONST 426
#define TEXT_PVR_NOT_MY_SHOW_CONST 427
#define TEXT_PVR_FORCE_RECORD_CONST 428
#define TEXT_PVR_RECORD_SELECTMC_CONST 429
#define TEXT_PVR_ALREADY_RECORDING_CONST 430
#define TEXT_CANCEL_RECORDING_CONST 431
#define TEXT_PVR_CANNOT_CHANGE_CHANNEL_CONST 432
#define TEXT_PVR_CANNOT_USE_CONST 433
#define TEXT_BROWSE_MEDIA_ALL_CONST 437
#define TEXT_VIEW_OTHER_CONSOLE_CONST 438
#define TEXT_VIEW_CURRENT_BROADCAST_CONST 439
#define TEXT_REFRESH_CONST 442
#define TEXT_PLAY_CONST 443
#define TEXT_ADD_ALL_CONST 444
#define TEXT_NEXT_CONST 446
#define TEXT_FILE_LIST_DESC_CONST 447
#define TEXT_SAVE_FILE_DESC_CONST 448
#define TEXT_SAVE_CONST 449
#define TEXT_DISC_DRIVE_BUSY_CONST 452
#define TEXT_CANCEL_CONST 453
#define TEXT_DRIVE_ACTION_CONST 454
#define TEXT_PROGRESS_CONST 455
#define TEXT_BROADCAST_CONST 456
#define TEXT_CLEAR_CONST 457
#define TEXT_SEARCH_MOVIE_RATING_CONST 463
#define TEXT_SEARCH_TV_MPAA_RATING_CONST 464
#define TEXT_SEARCH_1950_CONST 465
#define TEXT_SEARCH_1960_CONST 466
#define TEXT_SEARCH_1970_CONST 467
#define TEXT_SEARCH_1980_CONST 468
#define TEXT_SEARCH_1990_CONST 469
#define TEXT_SEARCH_CONST 471
#define TEXT_GUIDE_CONST 472
#define TEXT_RECORDED_TV_CONST 473
#define TEXT_REMOTE_CONST 474
#define TEXT_FAVORITES_CONST 475
#define TEXT_CALL_INTERCOM_CONST 476
#define TEXT_EPG_SHOW_NAME_CONST 477
#define TEXT_EPG_CHANNEL_NAME_CONST 478
#define TEXT_BURN_CD_AUDIO_CONST 482
#define TEXT_BURN_CD_DATA_CONST 483
#define TEXT_BURN_DVD_VIDEO_CONST 484
#define TEXT_BURN_DVD_DATA_CONST 485
#define TEXT_BURN_LAST_IMAGE_CONST 486
#define TEXT_CREATE_MEDIA_INST_CONST 487
#define TEXT_INSERT_MEDIA_CONST 488
#define TEXT_CONTINUE_CONST 489
#define TEXT_VERIFY_MEDIA_CONST 490
#define TEXT_RIP_CD_TRACKS_CONST 499
#define TEXT_ALL_TRACKS_CONST 500
#define TEXT_SCREEN_TALLER_CONST 501
#define TEXT_SCREEN_SHORTER_CONST 502
#define TEXT_SCREEN_WIDER_CONST 503
#define TEXT_SCREEN_Narrow_CONST 504
#define TEXT_SCREEN_UP_CONST 505
#define TEXT_SCREEN_DOWN_CONST 506
#define TEXT_SCREEN_LEFT_CONST 507
#define TEXT_SCREEN_RIGHT_CONST 508
#define TEXT_PVR_OPTIONS_CONST 510
#define TEXT_PVR_REC_SHOW_CONST 511
#define TEXT_PVR_REC_NOW_CONST 512
#define TEXT_PVR_REC_EVERYTHING_CONST 513
#define TEXT_PVR_REC_DURATION_CONST 514
#define TEXT_PVR_REC_30M_CONST 515
#define TEXT_PVR_REC_60M_CONST 516
#define TEXT_PVR_REC_INDEFINATE_CONST 517
#define TEXT_PVR_REC_ENDOFSHOW_CONST 518
#define TEXT_DV_START_CONST 519
#define TEXT_DV_STOP_CAPTURE_CONST 520
#define TEXT_ADD_CONTACT_CONST 521
#define TEXT_ADD_FAVORITES_CHANNEL_CONST 522
#define TEXT_CONTROLLER_STATUS_CONST 523
#define TEXT_ADD_FAVORITES_SHOWS_CONST 525
#define TEXT_REMOVE_FAVORITES_CHANNEL_CONST 526
#define TEXT_REMOVE_FAVORITES_SHOWS_CONST 527
#define TEXT_KEEP_RECORDING_CONST 529
#define TEXT_Choose_Filename_CONST 530
#define TEXT_EPG_FILE_NAME_CONST 531
#define TEXT_ADD_SPEED_DIAL_CONST 532
#define TEXT_ADDING_SPEED_DIAL_CONST 533
#define TEXT_QUESTION_MARK_CONST 534
#define TEXT_AMPERSAND_CONST 535
#define TEXT_HYPHEN_CONST 536
#define TEXT_AT_SYMBOL_CONST 537
#define TEXT_PERIOD_CONST 538
#define TEXT_RETRANSMIT_IR_CONST 541
#define TEXT_CALL_FROM_WHAT_DEVICE_CONST 542
#define TEXT_CALL_TO_WHICH_INTERCOM_CONST 543
#define TEXT_SAVE_PUBLIC_CONST 545
#define TEXT_SAVE_PRIVATE_CONST 546
#define TEXT_CONFIRM_DELETE_CONST 547
#define TEXT_DELETE_CONST 548
#define TEXT_ENTER_URL_CONST 550
#define TEXT_GOTO_URL_CONST 551
#define TEXT_PLUTO_BROWSER_CONST 552
#define TEXT_MAP_CONST 553
#define TEXT_NO_MEDIA_IN_DRIVE_CONST 555
#define TEXT_ENTER_MODE_CONST 556
#define TEXT_CHANGED_MODE_CONST 557
#define TEXT_HOUSE_MODE_CONST 558
#define TEXT_TOUCH_CONTINUE_CONST 559
#define TEXT_WAIT_FOR_SENSORS_CONST 560
#define TEXT_BYPASS_SENSORS_CONST 561
#define TEXT_ARM_WHEN_READY_CONST 562
#define TEXT_Copy_Disc_CONST 566
#define TEXT_ADVANCED_REMOTE_CONST 567
#define TEXT_REJECT_CALL_CONST 568
#define TEXT_HOME_VIDEOS_CONST 569
#define TEXT_STORED_MUSIC_CONST 570
#define TEXT_OTHER_MEDIA_CONST 571
#define TEXT_JUMP_TO_CONST 572
#define TEXT_INFO_CONST 573
#define TEXT_KEEP_PVR_NAME_CONST 581
#define TEXT_ADD_THIS_NUMBER_CONST 582
#define TEXT_SORT_CONST 583
#define TEXT_FIND_ALL_CONST 584
#define TEXT_EPG_SHOW_INFO_CONST 585
#define TEXT_DEVICE_PROBLEM_CONST 586
#define TEXT_PROBLEM_DEVICE_CONST 587
#define TEXT_YES_CONST 588
#define TEXT_NO_CONST 589
#define TEXT_DEVICE_PROBLEM_TITLE_CONST 590
#define TEXT_ADD_WWW_CONST 591
#define TEXT_CREATE_DOC_CONST 592
#define TEXT_CREATE_SPREADSHEET_CONST 593
#define TEXT_OPEN_WWW_PDA_CONST 594
#define TEXT_OPEN_WWW_TV_CONST 595
#define TEXT_OPEN_FILE_CONST 596
#define TEXT_ALL_Files_CONST 597
#define TEXT_RECENT_DOCUMENTS_CONST 598
#define TEXT_REMOVE_WWW_CONST 599
#define TEXT_Specific_FOLDER_CONST 600
#define TEXT_PRINT_CONST 601
#define TEXT_EMAIL_CONST 602
#define TEXT_EXIT_CONTROLLER_CONST 603
#define TEXT_RESET_PLUTO_UNIVERSE_CONST 604
#define TEXT_RESET_CONSOLE_CONST 605
#define TEXT_CALLING_CONST 606
#define TEXT_PICK_A_USER_CONST 607
#define TEXT_BROADCAST_LINPHONE_CONST 608
#define TEXT_END_LINPHONE_BROADCAST_CONST 609
#define TEXT_Restart_Router_CONST 610
#define TEXT_CONTROL_AV_CONST 611
#define TEXT_CONTROL_MISC_CONST 612
#define TEXT_CONTROL_ALL_DEV_CONST 613
#define TEXT_MOVE_CALL_HERE_CONST 614
#define TEXT_PLACE_FROM_HERE_CONST 615
#define TEXT_PIN_Code_CONST 617
#define TEXT_ADD_REMOVE_CONST 618
#define TEXT_JUKEBOX_CONST 619
#define TEXT_BROWSE_TITLE_CONST 620
#define TEXT_BROWSE_GENRE_CONST 621
#define TEXT_BROWSE_FOLDERS_CONST 622
#define TEXT_BROWSE_PERFORMER_CONST 626
#define TEXT_BROWSE_BY_CONST 627
#define TEXT_HOME_VIDS_CONST 628
#define TEXT_MOVIES_CONST 629
#define TEXT_MUSIC_CONST 630
#define TEXT_PLAYLIST_CONST 631
#define TEXT_View_CONST 632
#define TEXT_Close_CONST 633
#define TEXT_CURRENTLY_USING_CONST 637
#define TEXT_ENT_GUIDE_CONST 638
#define TEXT_MEDIA_CENTRAL_CONST 639
#define TEXT_REMOTE_A_CONST 640
#define TEXT_REMOTE_B_CONST 641
#define TEXT_REMOTE1_TAB_CONST 642
#define TEXT_REMOTE2_TAB_CONST 643
#define TEXT_GUIDE_TAB_CONST 644
#define TEXT_HOUSE_GLANCE_CONST 645
#define TEXT_RECORD_AND_TURN_OFF_CONST 646
#define TEXT_CONFERENCE_CONST 647
#define TEXT_STEP_ONE_CONST 648
#define TEXT_STEP_TWO_CONST 649
#define TEXT_OR_CONST 650
#define TEXT_CALL_IN_PROGRESS_CONST 651
#define TEXT_XFER_MD_CONST 652
#define TEXT_XFER_PHONE_CONST 653
#define TEXT_XFER_ORBITER_CONST 654
#define TEXT_NET_MEDIA_CONST 655
#define TEXT_CHANGE_MEDIA_GROUP_CONST 659
#define TEXT_SAVE_PLAYLIST_CONST 664
#define TEXT_RUNTIME_ARRAY_DESCRIPTION_CONST 668
#define TEXT_RUNTIME_ARRAY_ID_CONST 669
#define TEXT_STATUS_CONST 670
#define TEXT_STATUS_VARIABLE_CONST 671
#define TEXT_LEARN_IR_CODE_CONST 672
#define TEXT_RESET_AV_CONST 673
#define TEXT_RESET_AV_2_CONST 674
#define TEXT_Khz33_CONST 675
#define TEXT_Khz45_CONST 676
#define TEXT_Khz60_CONST 677
#define TEXT_TELECOM_OVERVIEW_CONST 678
#define TEXT_ON_100_CONST 679
#define TEXT_PERCENT_90_CONST 680
#define TEXT_PERCENT_70_CONST 681
#define TEXT_PERCENT_50_CONST 682
#define TEXT_PERCENT_30_CONST 683
#define TEXT_PERCENT_10_CONST 684
#define TEXT_OFF_CONST 685
#define TEXT_AUTO_CONST 686
#define TEXT_HEAT_CONST 687
#define TEXT_COOL_CONST 688
#define TEXT_FAN_CONST 689
#define TEXT_PLUS_CONST 690
#define TEXT_MINUS_CONST 691
#define TEXT_VOL_CONST 692
#define TEXT_CH_CONST 693
#define TEXT_Name_Playlist_CONST 696
#define TEXT_CANNOT_ADD_TO_PLAYLIST_CONST 698
#define TEXT_CHOOSE_SOMETHING_ELSE_CONST 699
#define TEXT_FAN_AUTO_CONST 700
#define TEXT_RESTART_AS_WINDOWS_CONST 701
#define TEXT_HOUSE_DISARMED_CONST 710
#define TEXT_HOUSE_ARMED_CONST 711
#define TEXT_AT_HOME_SEC_CONST 712
#define TEXT_SLEEPING_CONST 713
#define TEXT_EXTENDED_AWAY_CONST 714
#define TEXT_ENTERTAINING_CONST 715
#define TEXT_Start_As_Pluto_CONST 717
#define TEXT_DRIVE_BEING_USED_CONST 718
#define TEXT_DVD_REMOTE_CONST 719
#define TEXT_STILL_BUILDING_EPG_CONST 720
#define TEXT_GOT_NEW_EPG_DATA_CONST 721
#define TEXT_AVENTER_CONST 722
#define TEXT_EPG_SHOW_1_CONST 723
#define TEXT_EPG_SHOW_2_CONST 724
#define TEXT_FINISHED_EPG_CONST 725
#define TEXT_Preview_Auto_CONST 726
#define TEXT_LOCK_PREVIEW_CONST 727
#define TEXT_Show_Nothing_CONST 728
#define TEXT_PLAY_ALL_CONST 729
#define TEXT_OUTSIDE_NUMBER_CONST 730
#define TEXT_REBOOT_MD_CONST 731
#define TEXT_Delete_Rule_CONST 734
#define TEXT_Delete_Rule_And_Shows_CONST 735
#define TEXT_Hangup_All_TVs_CONST 736
#define TEXT_ADVANCED_MEDIA_OPTIONS_CONST 738
#define TEXT_NOW_PLAYING_LONG_CONST 740
#define TEXT_FILE_LIST_CONST 741
#define TEXT_ONE_EXCLAMATION_CONST 742
#define TEXT_TWO_AT_CONST 743
#define TEXT_THREE_NUMBER_CONST 744
#define TEXT_FOUR_DOLLAR_CONST 745
#define TEXT_Five_Percent_CONST 746
#define TEXT_Six_Caret_CONST 747
#define TEXT_Seven_Ampersand_CONST 748
#define TEXT_Eight_Asterisk_CONST 749
#define TEXT_Nine_Left_Parent_CONST 750
#define TEXT_Zero_Right_Parenth_CONST 751
#define TEXT_dash_underscore_CONST 752
#define TEXT_Equals_Plus_CONST 753
#define TEXT_Colon_SemiColon_CONST 754
#define TEXT_Quotations_CONST 755
#define TEXT_Comma_CONST 756
#define TEXT_Shift_CONST 758
#define TEXT_Back_CONST 759
#define TEXT_CAPS_LOCK_CONST 760
#define TEXT_Instant_Replay_CONST 761
#define TEXT_Previous_Channel_CONST 762
#define TEXT_Return_To_Live_CONST 763
#define TEXT_Menu_CONST 765
#define TEXT_Search_Media_CONST 766
#define TEXT_Files_CONST 767
#define TEXT_Collections_CONST 768
#define TEXT_Attributes_CONST 770
#define TEXT_GOTO_REMOTE_CONST 772
#define TEXT_NON_PLUTO_TV_CONST 773
#define TEXT_PLUTO_TV_CONST 774
#define TEXT_Exit_CONST 775
#define TEXT_AVInfo_CONST 776
#define TEXT_SATMusic_CONST 777
#define TEXT_QUEUE_CONST 779
#define TEXT_CHANNEL_CONST 780
#define TEXT_MUTE_CONST 781
#define TEXT_AVGuide_CONST 784
#define TEXT_dot_dot_dot_CONST 785
#define TEXT_On_CONST 786
#define TEXT_MIN_5_CONST 787
#define TEXT_MIN_10_CONST 788
#define TEXT_MIN_20_CONST 789
#define TEXT_MIN_30_CONST 790
#define TEXT_MIN_45_CONST 791
#define TEXT_HOUR_1_CONST 792
#define TEXT_STOP_COMPUTING_CONST 793
#define TEXT_DVD_OPTIONS_CONST 794
#define TEXT_Lights_CONST 795
#define TEXT_Media_CONST 796
#define TEXT_Climate_CONST 797
#define TEXT_Telecom_CONST 798
#define TEXT_Security_CONST 799
#define TEXT_Other_CONST 800
#define TEXT_location_CONST 801
#define TEXT_Hold_C_Help_15_follow_CONST 802
#define TEXT_playing_CONST 803
#define TEXT_music_media_CONST 816
#define TEXT_Yes_Install_the_software_CONST 1065
#define TEXT_No_This_device_is_not_a_mobile_phone_CONST 1066
#define TEXT_new_phone_detected_CONST 1067
#define TEXT_Next_myth_CONST 1068
#define TEXT_myth_setup_CONST 1069
#define TEXT_Setup_Myth_TV_CONST 1070
#define TEXT_First_Time_CONST 1071
#define TEXT_No_Media_CONST 1072
#define TEXT_go_to_main_menu_CONST 1073
#define TEXT_Load_playlist_CONST 1074
#define TEXT_Enter_CONST 1075
#define TEXT_Launch_MythTV_configuration_CONST 1076
#define TEXT_Dial_number_CONST 1077
#define TEXT_Dial_user_CONST 1078
#define TEXT_Voicemail_CONST 1079
#define TEXT_transfer_call_or_conference_CONST 1080
#define TEXT_Choose_user_CONST 1081
#define TEXT_Vol_up_CONST 1082
#define TEXT_Vol_down_CONST 1083
#define TEXT_At_home_CONST 1084
#define TEXT_Away_CONST 1085
#define TEXT_Disturb_CONST 1086
#define TEXT_Sleeping_phone_status_CONST 1087
#define TEXT_Press_enter_to_go_to_security_alerts_CONST 1088
#define TEXT_To_enter_PIN_press_Enter_CONST 1089
#define TEXT_Choose_a_user_CONST 1090
#define TEXT_House_Mode_Time_CONST 1091
#define TEXT_Alerts_since_last_change_CONST 1092
#define TEXT_Alerts_Placeholder_CONST 1093
#define TEXT_Manage_Playlist_CONST 1094
#define TEXT_Version_CONST 1095
#define TEXT_Try_other_codes_CONST 1096
#define TEXT_Device_Info_CONST 1097
#define TEXT_Computing_CONST 1098
#define TEXT_Sleeping_menu_CONST 1099
#define TEXT_Time_CONST 1100
#define TEXT_Date_CONST 1101
#define TEXT_Temp_outside_CONST 1102
#define TEXT_Temp_inside_CONST 1103
#define TEXT_Wake_Up_CONST 1104
#define TEXT_Email_Contacts_CONST 1105
#define TEXT_KDE_desktop_CONST 1106
#define TEXT_Installed_Programs_CONST 1107
#define TEXT_Recent_files_CONST 1108
#define TEXT_Go_to_Pluto_Admin_web_site_CONST 1109
#define TEXT_Display_Off_CONST 1110
#define TEXT_instructions_CONST 1111
#define TEXT_Alarms_CONST 1112
#define TEXT_Regen_Orbiter_CONST 1113
#define TEXT_Delete_entry_CONST 1114
#define TEXT_Delete_Playlist_CONST 1115
#define TEXT_Addgc_CONST 1116
#define TEXT_New_PnP_CONST 1117
#define TEXT_Regen_all_Orbiters_CONST 1118
#define TEXT_Orbiter_in_control_CONST 1119
#define TEXT_Orbiter_I_am_CONST 1120
#define TEXT_ON_display_CONST 1121
#define TEXT_OFF_display_CONST 1122
#define TEXT_Display_CONST 1123
#define TEXT_Power_ON_CONST 1124
#define TEXT_Current_media_CONST 1125
#define TEXT_Halt_CONST 1126
#define TEXT_My_Media_CONST 1127
#define TEXT_Yes_its_a_phone_CONST 1128
#define TEXT_choose_room_CONST 1129
#define TEXT_Orbiters_Regenerated_CONST 1130
#define TEXT_Checking_drive_CONST 1131
#define TEXT_Cannot_play_DVD_CONST 1132
#define TEXT_Exit_Pluto_CONST 1133
#define TEXT_advanced_CONST 1134
#define TEXT_asterisc_CONST 1135
#define TEXT_pound_CONST 1136
#define TEXT_Quad_view_CONST 1137
#define TEXT_Choose_camerav_CONST 1138
#define TEXT_Single_camera_view_CONST 1139
#define TEXT_orbiter_regenerated_CONST 1140
#define TEXT_Angles_CONST 1141
#define TEXT_Audio_Options_CONST 1142
#define TEXT_Subtitles_CONST 1143
#define TEXT_Selected_Devices_CONST 1144
#define TEXT_press_pencil_to_go_to_floorplan_CONST 1145
#define TEXT_type_channel_number_CONST 1146
#define TEXT_Countdown_before_alarm_CONST 1147
#define TEXT_Countdown_before_armed_CONST 1148
#define TEXT_Short_countdown_before_alarm_CONST 1149
#define TEXT_Short_countdown_before_armed_CONST 1150
#define TEXT_Wait_to_Arm_CONST 1151
#define TEXT_Try_Again_CONST 1152
#define TEXT_ViewSet_Attributes_CONST 1153
#define TEXT_Reset_signal_sent_CONST 1154
#define TEXT_Pending_Tasks_CONST 1155
#define TEXT_view_button_CONST 1156
#define TEXT_speak_CONST 1157
#define TEXT_open_CONST 1158
#define TEXT_sound_for_CONST 1159
#define TEXT_1_sec_CONST 1160
#define TEXT_5_sec_CONST 1161
#define TEXT_15_sec_CONST 1162
#define TEXT_30_sec_CONST 1163
#define TEXT_60_sec_CONST 1164
#define TEXT_Advanced_Options_CONST 1165
#define TEXT_Edit_Attribute_CONST 1166
#define TEXT_Random_CONST 1167
#define TEXT_Main_menu_CONST 1168
#define TEXT_mobile_signal_strength_CONST 1169
#define TEXT_New_Devices_Configured_CONST 1170
#define TEXT_Hide_Popup_CONST 1171
#define TEXT_Select_current_user_CONST 1172
#define TEXT_Select_room_CONST 1173
#define TEXT_Ligthing_scenarios_CONST 1174
#define TEXT_Media_Scenarios_CONST 1175
#define TEXT_Other_options_CONST 1176
#define TEXT_Security_scenarios_CONST 1177
#define TEXT_Telecom_scenarios_CONST 1178
#define TEXT_Climate_scenarios_CONST 1179
#define TEXT_Bookmarks_CONST 1180
#define TEXT_Save_Bookmark_CONST 1181
#define TEXT_Delete_Bookmark_CONST 1182
#define TEXT_Name_Bookmark_CONST 1183
#define TEXT_How_to_create_bookmark_CONST 1184
#define TEXT_Cannot_play_media_CONST 1185
#define TEXT_Cannot_bookmark_CONST 1186
#define TEXT_problem_ripping_CONST 1187
#define TEXT_Only_rip_drives_CONST 1188
#define TEXT_ripping_cant_play_disc_CONST 1189
#define TEXT_Abort_ripping_CONST 1190
#define TEXT_Last_Datagrid_Cell_CONST 1191
#define TEXT_Bookmark_here_CONST 1193
#define TEXT_Ask_to_resume_CONST 1194
#define TEXT_Always_Resume_CONST 1195
#define TEXT_Never_Resume_CONST 1196
#define TEXT_Unknown_Disc_CONST 1197
#define TEXT_Mouse_CONST 1198
#define TEXT_Device_Ready_CONST 1428
#define TEXT_FAILED_TO_UPLOAD_SIS_FILE_CONST 1429
#define TEXT_Watching_TV_CONST 1430
#define TEXT_Live_TV_Browse_Mode_CONST 1431
#define TEXT_Playback_Recording_CONST 1432
#define TEXT_All_MythTv_controls_CONST 1433
#define TEXT_Change_Inputs_CONST 1434
#define TEXT_Ripping_Instructions_CONST 1435
#define TEXT_Total_CONST 1436
#define TEXT_Now_Playing_Section_CONST 1437
#define TEXT_Now_Playing_Timecode_CONST 1438
#define TEXT_Now_Playing_Speed_CONST 1442
#define TEXT_Playlist_Saved_CONST 1443
#define TEXT_Monitor_progress_CONST 1444
#define TEXT_Zoom_in_CONST 1445
#define TEXT_Zoom_out_CONST 1446
#define TEXT_Escape_CONST 1447
#define TEXT_Tab_CONST 1448
#define TEXT_Remote_control_CONST 1449
#define TEXT_New_Room_CONST 1450
#define TEXT_name_new_room_CONST 1451
#define TEXT_Reload__Regen_Orbiter_CONST 1452
#define TEXT_Reload__Regen_All_Orbiters_CONST 1453
#define TEXT_Mozilla_bookmarks_CONST 1454
#define TEXT_Stop_Ping_CONST 1455
#define TEXT_Show_Ping_Test_CONST 1456
#define TEXT_Waiting_for_related_devices_CONST 1457
#define TEXT_Not_all_devices_started_CONST 1458
#define TEXT_Broadcast_Info_CONST 1459
#define TEXT_Title_EPG_CONST 1460
#define TEXT_Overview_CONST 1461
#define TEXT_Synopsis_CONST 1462
#define TEXT_Misc_Data_1_CONST 1463
#define TEXT_Misc_Data_2_CONST 1464
#define TEXT_Misc_Data_3_CONST 1465
#define TEXT_Misc_Data_4_CONST 1466
#define TEXT_Find_other_broadcasts_CONST 1467
#define TEXT_Use_OSD_CONST 1468
#define TEXT_Web_Sites_CONST 1470
#define TEXT_What_Type_Phone_CONST 1471
#define TEXT_Floorplan_CONST 1472
#define TEXT_See_playlist_CONST 1473
#define TEXT_new_pnp_device_CONST 1474
#define TEXT_No_ignore_it_CONST 1475
#define TEXT_Yes_use_it_CONST 1476
#define TEXT_Force_Reload_Router_CONST 1477
#define TEXT_Press_green_button_CONST 1478
#define TEXT_Audio_VDR_CONST 1479
#define TEXT_Stop_VDR_CONST 1480
#define TEXT_Record_CONST 1481
#define TEXT_Play_VDR_CONST 1482
#define TEXT_Commands_CONST 1483
#define TEXT_Recordings_CONST 1484
#define TEXT_Timers_CONST 1485
#define TEXT_Channels_CONST 1486
#define TEXT_Schedule_CONST 1487
#define TEXT_Setup_VDR_CONST 1488
#define TEXT_Red_CONST 1489
#define TEXT_Blue_CONST 1490
#define TEXT_Green_CONST 1491
#define TEXT_Yellow_CONST 1492
#define TEXT_Back_VDR_CONST 1493
#define TEXT_Ok_CONST 1494
#define TEXT_Pause_VDR_CONST 1495
#define TEXT_Menu_VDR_CONST 1496
#define TEXT_Start_Wizard_CONST 1497
#define TEXT_Greetings_CONST 1498
#define TEXT_Repeat_CONST 1499
#define TEXT_Names_CONST 1500
#define TEXT_Family_Members_CONST 1501
#define TEXT_Rooms_CONST 1502
#define TEXT_Confirm_Names_CONST 1503
#define TEXT_AV_connection_CONST 1504
#define TEXT_Model_CONST 1505
#define TEXT_Connect_directly_to_the_TV_CONST 1506
#define TEXT_Use_a_receiver_CONST 1507
#define TEXT_AV_devices_CONST 1508
#define TEXT_Other_AV_devices_CONST 1509
#define TEXT_12_Lights_CONST 1510
#define TEXT_Lights_Setup_CONST 1511
#define TEXT_Confirm_lights_CONST 1512
#define TEXT_Which_room_is_this_in_CONST 1513
#define TEXT_16_Light_test_CONST 1514
#define TEXT_Light_type_CONST 1515
#define TEXT_Light_name_CONST 1516
#define TEXT_VOIP_Provider_CONST 1517
#define TEXT_I_can_hear_you_CONST 1518
#define TEXT_dont_control_my_TV_CONST 1519
#define TEXT_Add_user_CONST 1520
#define TEXT_KVC61M_51M_42M_CONST 1521
#define TEXT_KVL60P_CONST 1522
#define TEXT_KXV52P_CONST 1523
#define TEXT_Other_model_CONST 1524
#define TEXT_yes_i_use_HDMI_input_CONST 1525
#define TEXT_no_i_use_another_input_CONST 1526
#define TEXT_Video1_Composite_CONST 1527
#define TEXT_Video2_SVideo_CONST 1528
#define TEXT_Video3_Component_CONST 1529
#define TEXT_Video4_Component_CONST 1530
#define TEXT_Using_the_TVs_speakers_CONST 1531
#define TEXT_Using_a_receiver_CONST 1532
#define TEXT_yes_I_have_one_CONST 1533
#define TEXT_Tell_me_more_CONST 1534
#define TEXT_I_have_another_brand_CONST 1535
#define TEXT_no_i_dont_have_lighting_system_CONST 1536
#define TEXT_15_CONST 1537
#define TEXT_Living_Room_CONST 1538
#define TEXT_Master_Bedroom_CONST 1539
#define TEXT_Johns_Room_CONST 1540
#define TEXT_Den_CONST 1541
#define TEXT_Kitchen_CONST 1542
#define TEXT_Other_new_room_CONST 1543
#define TEXT_Floor_lamp_CONST 1544
#define TEXT_Table_lamp_CONST 1545
#define TEXT_Chandelier_CONST 1546
#define TEXT_Track_light_CONST 1547
#define TEXT_Recessed_lighting_CONST 1548
#define TEXT_Start_Using_the_Monster_Vault_CONST 1549
#define TEXT_Next_CONST 1550
#define TEXT_Can_you_see_me_and_hear_me_CONST 1551
#define TEXT_Stop_video_CONST 1552
#define TEXT_Whats_your_name_CONST 1553
#define TEXT_Other_family_members_CONST 1554
#define TEXT_What_country_are_you_in_CONST 1555
#define TEXT_Remove_user_CONST 1556
#define TEXT_Confirm_postal_code_CONST 1557
#define TEXT_What_rooms_are_in_your_house_CONST 1558
#define TEXT_TV_Provider_CONST 1559
#define TEXT_Alarm_Panel_CONST 1560
#define TEXT_Do_you_use_cable_satellite_or_antenna_CONST 1561
#define TEXT_Manufacturer_of_box_CONST 1562
#define TEXT_Model_of_box_CONST 1563
#define TEXT_Who_made_the_TV_you_are_using_CONST 1564
#define TEXT_Do_you_use_a_receiver_CONST 1565
#define TEXT_Receiver_CONST 1566
#define TEXT_Who_made_the_Receiver_you_are_using_CONST 1567
#define TEXT_Which_input_did_you_use_CONST 1568
#define TEXT_Who_made_the_device_CONST 1569
#define TEXT_AV_Outputs_CONST 1570
#define TEXT_Do_you_have_a_Monster_lighting_system_CONST 1571
#define TEXT_Prepare_Monster_Lighting_CONST 1572
#define TEXT_Setup_later_CONST 1573
#define TEXT_Do_you_have_an_alarm_panel_CONST 1574
#define TEXT_Found_the_alarm_panel_CONST 1575
#define TEXT_Do_you_have_a_VOIP_provider_CONST 1576
#define TEXT_Configure_Account_CONST 1577
#define TEXT_VOIP_Username_CONST 1578
#define TEXT_VOIP_Password_CONST 1579
#define TEXT_All_done_CONST 1580
#define TEXT_Broadvoice_CONST 1581
#define TEXT_Free_World_Dialup_CONST 1582
#define TEXT_InPhonex_CONST 1583
#define TEXT_Efon_CONST 1584
#define TEXT_Teliax_CONST 1585
#define TEXT_VOIP_Number_CONST 1586
#define TEXT_Add_CONST 1587
#define TEXT_Remove_CONST 1588
#define TEXT_No_recommended_directory_structure_CONST 1589
#define TEXT_Auto_Use_NAS_CONST 1590
#define TEXT_dont_auto_use_nas_CONST 1591
#define TEXT_Use_recommended_directory_structure_CONST 1592
#define TEXT_Enter_your_postal_code_CONST 1593
#define TEXT_Bad_Zip_Code_CONST 1594
#define TEXT_Voip_Container_CONST 1600
#define TEXT_You_choose_Broadvoice_CONST 1601
#define TEXT_Directly_to_TV_CONST 1602
#define TEXT_To_a_receiver_CONST 1603
#define TEXT_Neither_I_have_a_special_setup_like_a_CONST 1604
#define TEXT_DSC_CONST 1605
#define TEXT_APEX_CONST 1606
#define TEXT_Installed_AV_Devices_CONST 1607
#define TEXT_Another_AV_Device_CONST 1608
#define TEXT_Alarm_Panel_Model_CONST 1609
#define TEXT_What_port_did_you_connect_it_to_CONST 1610
#define TEXT_Looking_for_alarm_panel_Please_wait_CONST 1611
#define TEXT_Panel_not_found_CONST 1612
#define TEXT_input_from_Receiver_to_TV_CONST 1613
#define TEXT_input_from_md_CONST 1614
#define TEXT_TV_CONST 1615
#define TEXT_Monster_Remote_Found_CONST 1616
#define TEXT_Error_getting_data_CONST 1617
#define TEXT_Num_Lights_CONST 1618
#define TEXT_No_Lights_Found_CONST 1619
#define TEXT_Does_this_device_have_a_video_output_tha_CONST 1620
#define TEXT_Inputs_CONST 1621
#define TEXT_Does_this_device_have_an_audio_output_th_CONST 1622
#define TEXT_no_pnp_CONST 1623
#define TEXT_After_you_press_this_button_the_system_w_CONST 1624
#define TEXT_alarm_error_CONST 1625
#define TEXT_which_room_is_this_system_in_CONST 1626
#define TEXT_Please_enter_your_phone_number_for_this_CONST 1627
#define TEXT_CableAntenna_input_CONST 1628
#define TEXT_External_Tuner_CONST 1629
#define TEXT_Need_to_reload_CONST 1630
#define TEXT_Yes_reload_router_CONST 1631
#define TEXT_No_dont_reload_router_CONST 1632
#define TEXT_Need_to_regen_CONST 1633
#define TEXT_Yes_Regen_this_CONST 1634
#define TEXT_Yes_Regen_All_CONST 1635
#define TEXT_No_Regen_Later_CONST 1636
#define TEXT_I_dont_have_a_receiver_to_setup_CONST 1637
#define TEXT_Yes_I_use_a_receiver_CONST 1638
#define TEXT_Which_Sensors_Viewed_CONST 1639
#define TEXT_Display_On_CONST 1640
#define TEXT_Minimize_Pluto_Orbiter_CONST 1641
#define TEXT_Download_finnished_CONST 1642
#define TEXT_ForceUpgradeNow_CONST 1643
#define TEXT_TVManufNotListed_CONST 1644
#define TEXT_Monster_Demo_CONST 1645
#define TEXT_IR_Group_CONST 1646
#define TEXT_TVModelNotListed_CONST 1647
#define TEXT_LearIRCodes_CONST 1648
#define TEXT_TVReceiver_CONST 1649
#define TEXT_ConfirmIRCodes_CONST 1650
#define TEXT_TVTypeNotListed_CONST 1651
#define TEXT_List_of_all_bookmarksList_of_all_bookmar_CONST 1652
#define TEXT_View_bookmarks_for_this_file_CONST 1653
#define TEXT_ManufNotListed_CONST 1654
#define TEXT_What_Delay_CONST 1655
#define TEXT_How_to_tune_CONST 1656
#define TEXT_DoYouHaveMultipleInputs_CONST 1657
#define TEXT_Single_Input_CONST 1658
#define TEXT_Multiple_Inputs_CONST 1659
#define TEXT_DSPModes_CONST 1660
#define TEXT_noDSPModes_CONST 1661
#define TEXT_yes_I_have_DSPModes_CONST 1662
#define TEXT_DiscreteCodesDSPModes_CONST 1663
#define TEXT_ToggleCodesDSPModes_CONST 1664
#define TEXT_ModelNotListed_CONST 1665
#define TEXT_Start_Time_CONST 1666
#define TEXT_Stop_Time_CONST 1667
#define TEXT_Current_Time_CONST 1668
#define TEXT_Tunepart1_CONST 1669
#define TEXT_Tunepart2_CONST 1670
#define TEXT_TVOnOffCodes_CONST 1671
#define TEXT_Select_Toggle_or_Discrete_On_Off_CONST 1672
#define TEXT_DiscreteOnOff_CONST 1673
#define TEXT_ToggleOnOff_CONST 1674
#define TEXT_ConfirmDiscreteOnOff_CONST 1675
#define TEXT_TVConfirmOnOffDiscrete_CONST 1676
#define TEXT_TVConfirmOnOffToggle_CONST 1677
#define TEXT_ConfirmOnOffToggle_CONST 1678
#define TEXT_Most_Sensitive_CONST 1679
#define TEXT_Middle_Sensitivity_CONST 1680
#define TEXT_Least_Sensitive_CONST 1681
#define TEXT_Filename_CONST 1682

#define TEXT_TABLE "Text"
#define TEXT_PK_TEXT_FIELD "PK_Text"
#define TEXT_PK_TEXT_TABLE_FIELD "Text.PK_Text"
#define TEXT_FK_TEXTCATEGORY_FIELD "FK_TextCategory"
#define TEXT_FK_TEXTCATEGORY_TABLE_FIELD "Text.FK_TextCategory"
#define TEXT_DESCRIPTION_FIELD "Description"
#define TEXT_DESCRIPTION_TABLE_FIELD "Text.Description"
#define TEXT_DEFINE_FIELD "Define"
#define TEXT_DEFINE_TABLE_FIELD "Text.Define"
#define TEXT_ADDTOORBITER_FIELD "AddToOrbiter"
#define TEXT_ADDTOORBITER_TABLE_FIELD "Text.AddToOrbiter"
#define TEXT_PSC_ID_FIELD "psc_id"
#define TEXT_PSC_ID_TABLE_FIELD "Text.psc_id"
#define TEXT_PSC_BATCH_FIELD "psc_batch"
#define TEXT_PSC_BATCH_TABLE_FIELD "Text.psc_batch"
#define TEXT_PSC_USER_FIELD "psc_user"
#define TEXT_PSC_USER_TABLE_FIELD "Text.psc_user"
#define TEXT_PSC_FROZEN_FIELD "psc_frozen"
#define TEXT_PSC_FROZEN_TABLE_FIELD "Text.psc_frozen"
#define TEXT_PSC_MOD_FIELD "psc_mod"
#define TEXT_PSC_MOD_TABLE_FIELD "Text.psc_mod"
#define TEXT_PSC_RESTRICT_FIELD "psc_restrict"
#define TEXT_PSC_RESTRICT_TABLE_FIELD "Text.psc_restrict"


#endif

