#ifndef __Define_Device_pschist_H__
#define __Define_Device_pschist_H__


#define DEVICE_PSCHIST_TABLE "Device_pschist"
#define DEVICE_PSCHIST_PK_DEVICE_FIELD "PK_Device"
#define DEVICE_PSCHIST_PK_DEVICE_TABLE_FIELD "Device_pschist.PK_Device"
#define DEVICE_PSCHIST_DISABLED_FIELD "Disabled"
#define DEVICE_PSCHIST_DISABLED_TABLE_FIELD "Device_pschist.Disabled"
#define DEVICE_PSCHIST_FK_ROOM_FIELD "FK_Room"
#define DEVICE_PSCHIST_FK_ROOM_TABLE_FIELD "Device_pschist.FK_Room"
#define DEVICE_PSCHIST_FK_INSTALLATION_FIELD "FK_Installation"
#define DEVICE_PSCHIST_FK_INSTALLATION_TABLE_FIELD "Device_pschist.FK_Installation"
#define DEVICE_PSCHIST_FK_DESIGNOBJ_FIELD "FK_DesignObj"
#define DEVICE_PSCHIST_FK_DESIGNOBJ_TABLE_FIELD "Device_pschist.FK_DesignObj"
#define DEVICE_PSCHIST_DESCRIPTION_FIELD "Description"
#define DEVICE_PSCHIST_DESCRIPTION_TABLE_FIELD "Device_pschist.Description"
#define DEVICE_PSCHIST_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define DEVICE_PSCHIST_FK_DEVICETEMPLATE_TABLE_FIELD "Device_pschist.FK_DeviceTemplate"
#define DEVICE_PSCHIST_FK_DEVICE_CONTROLLEDVIA_FIELD "FK_Device_ControlledVia"
#define DEVICE_PSCHIST_FK_DEVICE_CONTROLLEDVIA_TABLE_FIELD "Device_pschist.FK_Device_ControlledVia"
#define DEVICE_PSCHIST_IPADDRESS_FIELD "IPaddress"
#define DEVICE_PSCHIST_IPADDRESS_TABLE_FIELD "Device_pschist.IPaddress"
#define DEVICE_PSCHIST_MACADDRESS_FIELD "MACaddress"
#define DEVICE_PSCHIST_MACADDRESS_TABLE_FIELD "Device_pschist.MACaddress"
#define DEVICE_PSCHIST_IGNOREONOFF_FIELD "IgnoreOnOff"
#define DEVICE_PSCHIST_IGNOREONOFF_TABLE_FIELD "Device_pschist.IgnoreOnOff"
#define DEVICE_PSCHIST_FK_DEVICE_ROUTETO_FIELD "FK_Device_RouteTo"
#define DEVICE_PSCHIST_FK_DEVICE_ROUTETO_TABLE_FIELD "Device_pschist.FK_Device_RouteTo"
#define DEVICE_PSCHIST_NEEDCONFIGURE_FIELD "NeedConfigure"
#define DEVICE_PSCHIST_NEEDCONFIGURE_TABLE_FIELD "Device_pschist.NeedConfigure"
#define DEVICE_PSCHIST_STATE_FIELD "State"
#define DEVICE_PSCHIST_STATE_TABLE_FIELD "Device_pschist.State"
#define DEVICE_PSCHIST_STATUS_FIELD "Status"
#define DEVICE_PSCHIST_STATUS_TABLE_FIELD "Device_pschist.Status"
#define DEVICE_PSCHIST_PINGTEST_FIELD "PingTest"
#define DEVICE_PSCHIST_PINGTEST_TABLE_FIELD "Device_pschist.PingTest"
#define DEVICE_PSCHIST_EK_LICENSEDDEVICE_FIELD "EK_LicensedDevice"
#define DEVICE_PSCHIST_EK_LICENSEDDEVICE_TABLE_FIELD "Device_pschist.EK_LicensedDevice"
#define DEVICE_PSCHIST_ISNEWDEVICE_FIELD "IsNewDevice"
#define DEVICE_PSCHIST_ISNEWDEVICE_TABLE_FIELD "Device_pschist.IsNewDevice"
#define DEVICE_PSCHIST_MANUALLYCONFIGUREEA_FIELD "ManuallyConfigureEA"
#define DEVICE_PSCHIST_MANUALLYCONFIGUREEA_TABLE_FIELD "Device_pschist.ManuallyConfigureEA"
#define DEVICE_PSCHIST_REGISTERED_FIELD "Registered"
#define DEVICE_PSCHIST_REGISTERED_TABLE_FIELD "Device_pschist.Registered"
#define DEVICE_PSCHIST_PSC_ID_FIELD "psc_id"
#define DEVICE_PSCHIST_PSC_ID_TABLE_FIELD "Device_pschist.psc_id"
#define DEVICE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_PSCHIST_PSC_BATCH_TABLE_FIELD "Device_pschist.psc_batch"
#define DEVICE_PSCHIST_PSC_USER_FIELD "psc_user"
#define DEVICE_PSCHIST_PSC_USER_TABLE_FIELD "Device_pschist.psc_user"
#define DEVICE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Device_pschist.psc_frozen"
#define DEVICE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DEVICE_PSCHIST_PSC_MOD_TABLE_FIELD "Device_pschist.psc_mod"
#define DEVICE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DEVICE_PSCHIST_PSC_TOC_TABLE_FIELD "Device_pschist.psc_toc"
#define DEVICE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Device_pschist.psc_restrict"


#endif

