#ifndef __Define_MediaType_Broadcast_pschist_H__
#define __Define_MediaType_Broadcast_pschist_H__


#define MEDIATYPE_BROADCAST_PSCHIST_TABLE "MediaType_Broadcast_pschist"
#define MEDIATYPE_BROADCAST_PSCHIST_FK_MEDIATYPE_FIELD "FK_MediaType"
#define MEDIATYPE_BROADCAST_PSCHIST_FK_MEDIATYPE_TABLE_FIELD "MediaType_Broadcast_pschist.FK_MediaType"
#define MEDIATYPE_BROADCAST_PSCHIST_FK_BROADCAST_FIELD "FK_Broadcast"
#define MEDIATYPE_BROADCAST_PSCHIST_FK_BROADCAST_TABLE_FIELD "MediaType_Broadcast_pschist.FK_Broadcast"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_ID_FIELD "psc_id"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_ID_TABLE_FIELD "MediaType_Broadcast_pschist.psc_id"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_BATCH_TABLE_FIELD "MediaType_Broadcast_pschist.psc_batch"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_USER_FIELD "psc_user"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_USER_TABLE_FIELD "MediaType_Broadcast_pschist.psc_user"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_FROZEN_TABLE_FIELD "MediaType_Broadcast_pschist.psc_frozen"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_MOD_TABLE_FIELD "MediaType_Broadcast_pschist.psc_mod"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_TOC_TABLE_FIELD "MediaType_Broadcast_pschist.psc_toc"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define MEDIATYPE_BROADCAST_PSCHIST_PSC_RESTRICT_TABLE_FIELD "MediaType_Broadcast_pschist.psc_restrict"


#endif

