#ifndef __Define_Command_H__
#define __Define_Command_H__

#define COMMAND_Capture_Keyboard_To_Variable_CONST 1
#define COMMAND_Orbiter_Beep_CONST 2
#define COMMAND_Display_OnOff_CONST 3
#define COMMAND_Go_back_CONST 4
#define COMMAND_Goto_Screen_CONST 5
#define COMMAND_Show_Object_CONST 6
#define COMMAND_Terminate_Orbiter_CONST 7
#define COMMAND_Remove_Screen_From_History_CONST 8
#define COMMAND_Scroll_Grid_CONST 9
#define COMMAND_Move_Highlight_CONST 10
#define COMMAND_Play_Sound_CONST 13
#define COMMAND_Refresh_CONST 14
#define COMMAND_Regen_Screen_CONST 15
#define COMMAND_Requires_Special_Handling_CONST 16
#define COMMAND_Seek_Data_Grid_CONST 17
#define COMMAND_Set_Graphic_To_Display_CONST 18
#define COMMAND_Set_House_Mode_CONST 19
#define COMMAND_Set_Object_Parameter_CONST 20
#define COMMAND_Set_Object_Position_CONST 21
#define COMMAND_Set_Object_Size_CONST 22
#define COMMAND_Set_Pos_Rel_To_Parent_CONST 23
#define COMMAND_Set_Size_Rel_To_Parent_CONST 24
#define COMMAND_Set_Text_CONST 25
#define COMMAND_Set_Bound_Icon_CONST 26
#define COMMAND_Set_Variable_CONST 27
#define COMMAND_Simulate_Keypress_CONST 28
#define COMMAND_Simulate_Mouse_Click_CONST 29
#define COMMAND_Stop_Sound_CONST 30
#define COMMAND_Store_Variables_CONST 31
#define COMMAND_Update_Object_Image_CONST 32
#define COMMAND_Start_Media_CONST 33
#define COMMAND_Request_Datagrid_Contents_CONST 34
#define COMMAND_Populate_Datagrid_CONST 35
#define COMMAND_Create_Media_CONST 36
#define COMMAND_Play_Media_CONST 37
#define COMMAND_Stop_Media_CONST 38
#define COMMAND_Pause_Media_CONST 39
#define COMMAND_Restart_Media_CONST 40
#define COMMAND_Change_Playback_Speed_CONST 41
#define COMMAND_Rewind_Playback_CONST 42
#define COMMAND_MH_Play_Media_CONST 43
#define COMMAND_MH_Stop_Media_CONST 44
#define COMMAND_Disk_Drive_Monitoring_ON_CONST 45
#define COMMAND_Disk_Drive_Monitoring_OFF_CONST 46
#define COMMAND_Reset_Disk_Drive_CONST 47
#define COMMAND_Eject_Disk_CONST 48
#define COMMAND_Start_Burn_Session_CONST 49
#define COMMAND_Start_Ripping_Session_CONST 50
#define COMMAND_Add_File_To_Burning_Session_CONST 51
#define COMMAND_Start_Burning_CONST 52
#define COMMAND_Abort_Burning_CONST 53
#define COMMAND_Mount_Disk_Image_CONST 54
#define COMMAND_Start_Ripping_DVD_CONST 55
#define COMMAND_Format_Drive_CONST 56
#define COMMAND_Close_Tray_CONST 57
#define COMMAND_Set_Current_User_CONST 58
#define COMMAND_Set_Entertainment_Area_CONST 59
#define COMMAND_Link_with_mobile_orbiter_CONST 60
#define COMMAND_Get_Signal_Strength_CONST 61
#define COMMAND_Create_Mobile_Orbiter_CONST 62
#define COMMAND_Skip_Fwd_ChannelTrack_Greater_CONST 63
#define COMMAND_Skip_Back_ChannelTrack_Lower_CONST 64
#define COMMAND_Jump_Position_In_Playlist_CONST 65
#define COMMAND_Select_Object_CONST 66
#define COMMAND_Spawn_Application_CONST 67
#define COMMAND_Get_Device_Data_CONST 68
#define COMMAND_Kill_Application_CONST 69
#define COMMAND_Hide_Application_CONST 70
#define COMMAND_Request_File_CONST 71
#define COMMAND_Surrender_to_OS_CONST 72
#define COMMAND_MH_Send_Me_To_Remote_CONST 73
#define COMMAND_Bind_to_Media_Remote_CONST 74
#define COMMAND_Start_TV_CONST 75
#define COMMAND_Stop_TV_CONST 76
#define COMMAND_Set_Current_Room_CONST 77
#define COMMAND_New_Mobile_Orbiter_CONST 78
#define COMMAND_Add_Unknown_Device_CONST 79
#define COMMAND_Send_File_To_Device_CONST 80
#define COMMAND_Navigate_Next_CONST 81
#define COMMAND_Navigate_Prev_CONST 82
#define COMMAND_Get_Video_Frame_CONST 84
#define COMMAND_Reset_Highlight_CONST 85
#define COMMAND_Menu_Show_Menu_CONST 86
#define COMMAND_Goto_Media_Menu_CONST 87
#define COMMAND_Set_Current_Location_CONST 88
#define COMMAND_Vol_Up_CONST 89
#define COMMAND_Vol_Down_CONST 90
#define COMMAND_Input_Select_CONST 91
#define COMMAND_Pause_CONST 92
#define COMMAND_Scan_FwdFast_Fwd_CONST 93
#define COMMAND_Stop_CONST 95
#define COMMAND_Change_Disc_CONST 96
#define COMMAND_Mute_CONST 97
#define COMMAND_Slow_Scan_Back_CONST 98
#define COMMAND_Slow_Scan_Forward_CONST 99
#define COMMAND_Record_CONST 102
#define COMMAND_Random_CONST 103
#define COMMAND_Repeat_CONST 104
#define COMMAND_Fwd_14x_CONST 105
#define COMMAND_Fwd_12x_CONST 106
#define COMMAND_Fwd_2x_CONST 107
#define COMMAND_Fwd_4x_CONST 108
#define COMMAND_Fwd_8x_CONST 109
#define COMMAND_Back_14x_CONST 110
#define COMMAND_Back_12x_CONST 111
#define COMMAND_Back_1x_CONST 112
#define COMMAND_Back_2x_CONST 113
#define COMMAND_Back_4x_CONST 114
#define COMMAND_Back_8x_CONST 115
#define COMMAND_DSP_Mode_CONST 116
#define COMMAND_Skip_To_End_CONST 117
#define COMMAND_Back_16x_CONST 119
#define COMMAND_Back_32X_CONST 120
#define COMMAND_Fwd_16x_CONST 121
#define COMMAND_Fwd_32x_CONST 122
#define COMMAND_Info_CONST 123
#define COMMAND_Favorites_CONST 124
#define COMMAND_Scan_BackRewind_CONST 125
#define COMMAND_Guide_CONST 126
#define COMMAND_PIP_ON_CONST 127
#define COMMAND_PIP_OFF_CONST 128
#define COMMAND_PIP_Channel_Up_CONST 129
#define COMMAND_PIP_Channel_Down_CONST 130
#define COMMAND_PIP_Channel_Number_CONST 131
#define COMMAND_Taller_CONST 132
#define COMMAND_Shorter_CONST 133
#define COMMAND_Wider_CONST 134
#define COMMAND_Narrower_CONST 135
#define COMMAND_Previous_Channel_CONST 136
#define COMMAND_Music_CONST 137
#define COMMAND_Eject_CONST 138
#define COMMAND_Play_CONST 139
#define COMMAND_Audio_Track_CONST 140
#define COMMAND_Subtitle_CONST 141
#define COMMAND_Angle_CONST 142
#define COMMAND_Progressive_CONST 144
#define COMMAND_Back_10_seconds_CONST 145
#define COMMAND_Multi_Channel_CONST 146
#define COMMAND_Hall_CONST 147
#define COMMAND_Church_CONST 148
#define COMMAND_Jazz_Club_CONST 149
#define COMMAND_Rock_Concert_CONST 150
#define COMMAND_Entertainment_CONST 151
#define COMMAND_Music_Video_CONST 152
#define COMMAND_Classical_CONST 153
#define COMMAND_RGB_CONST 154
#define COMMAND_Video_1_CONST 155
#define COMMAND_Video_2_CONST 156
#define COMMAND_Video_3_CONST 157
#define COMMAND_Video_4_CONST 158
#define COMMAND_Video_5_CONST 159
#define COMMAND_Tape_Tape_1_CONST 160
#define COMMAND_TV_CONST 161
#define COMMAND_CD_CONST 162
#define COMMAND_Phono_CONST 163
#define COMMAND_Aux_CONST 164
#define COMMAND_DVD_CONST 165
#define COMMAND_Tuner_CONST 166
#define COMMAND_Video_6_CONST 167
#define COMMAND_Video_7_CONST 168
#define COMMAND_AM_CONST 169
#define COMMAND_FM_CONST 170
#define COMMAND_DVD_Multi_CONST 171
#define COMMAND_Aux_2_CONST 172
#define COMMAND_Tape_2_CONST 173
#define COMMAND_Minidisc_CONST 174
#define COMMAND_Tuner_2_CONST 175
#define COMMAND_VDP_CONST 176
#define COMMAND_Laserdisc_CONST 177
#define COMMAND_DSS_CONST 178
#define COMMAND_DVI_CONST 179
#define COMMAND_Svideo_CONST 180
#define COMMAND_Composite_CONST 181
#define COMMAND_RF_Input_CONST 182
#define COMMAND_Get_Floorplan_Layout_CONST 183
#define COMMAND_Set_Level_CONST 184
#define COMMAND_Schedule_Recording_CONST 185
#define COMMAND_Get_Current_Floorplan_CONST 186
#define COMMAND_Tune_to_channel_CONST 187
#define COMMAND_Get_Infrared_Codes_CONST 188
#define COMMAND_Send_Generic_EnterGo_CONST 190
#define COMMAND_Send_Code_CONST 191
#define COMMAND_Generic_On_CONST 192
#define COMMAND_Generic_Off_CONST 193
#define COMMAND_Toggle_Power_CONST 194
#define COMMAND_Dial_CONST 195
#define COMMAND_Cool_CONST 196
#define COMMAND_Heat_CONST 197
#define COMMAND_Move_Up_CONST 200
#define COMMAND_Move_Down_CONST 201
#define COMMAND_Move_Left_CONST 202
#define COMMAND_Move_Right_CONST 203
#define COMMAND_0_CONST 204
#define COMMAND_1_CONST 205
#define COMMAND_2_CONST 206
#define COMMAND_3_CONST 207
#define COMMAND_4_CONST 208
#define COMMAND_5_CONST 209
#define COMMAND_6_CONST 210
#define COMMAND_7_CONST 211
#define COMMAND_8_CONST 212
#define COMMAND_9_CONST 213
#define COMMAND_Save_playlist_CONST 214
#define COMMAND__CONST 215
#define COMMAND_Balance_Sel_CONST 216
#define COMMAND_Balance_Left_CONST 217
#define COMMAND_Balance_Right_CONST 218
#define COMMAND_Contrast_Sel_CONST 219
#define COMMAND_Contrast_Up_CONST 220
#define COMMAND_Contrast_Down_CONST 221
#define COMMAND_Brightness_Sel_CONST 222
#define COMMAND_Brightness_Up_CONST 223
#define COMMAND_Brightness_Down_CONST 224
#define COMMAND_Display_CONST 225
#define COMMAND_Originate_Renamed_To_Not_Break_Compiles_CONST 226
#define COMMAND_Originate_CONST 227
#define COMMAND_Bass_Sel_CONST 228
#define COMMAND_Bass_Up_CONST 229
#define COMMAND_Bass_Down_CONST 230
#define COMMAND_Load_Playlist_CONST 231
#define COMMAND_PL_Originate_CONST 232
#define COMMAND_PBX_Originate_CONST 233
#define COMMAND_PL_TransferConferenceDevice_CONST 234
#define COMMAND_PBX_Transfer_CONST 235
#define COMMAND_PL_Hangup_CONST 236
#define COMMAND_PBX_Hangup_CONST 237
#define COMMAND_Continuous_Refresh_CONST 238
#define COMMAND_Request_File_And_Checksum_CONST 239
#define COMMAND_Back_Prior_Menu_CONST 240
#define COMMAND_MH_Move_Media_CONST 241
#define COMMAND_Set_Now_Playing_CONST 242
#define COMMAND_Enable_Broadcasting_CONST 243
#define COMMAND_Output_Select_CONST 244
#define COMMAND_Learn_IR_CONST 245
#define COMMAND_Set_Device_Data_CONST 246
#define COMMAND_Get_Device_State_CONST 247
#define COMMAND_Get_Device_Status_CONST 248
#define COMMAND_Start_Streaming_CONST 249
#define COMMAND_Store_Infrared_Code_CONST 250
#define COMMAND_Save_Current_Frame_CONST 251
#define COMMAND_Send_Audio_To_Device_CONST 253
#define COMMAND_Bind_Icon_CONST 254
#define COMMAND_Orbiter_Registered_CONST 255
#define COMMAND_Text_To_Wave_CONST 256
#define COMMAND_Delay_CONST 257
#define COMMAND_Clear_Selected_Devices_CONST 258
#define COMMAND_Report_Playback_Position_CONST 259
#define COMMAND_Set_Main_Menu_CONST 260
#define COMMAND_Set_FollowMe_CONST 261
#define COMMAND_Stop_Streaming_CONST 262
#define COMMAND_Toggle_Event_Handler_CONST 263
#define COMMAND_Track_Frontend_At_IP_CONST 264
#define COMMAND_Quit_CONST 265
#define COMMAND_Regen_Orbiter_CONST 266
#define COMMAND_Regen_Orbiter_Finished_CONST 267
#define COMMAND_Move_Playlist_entry_Up_CONST 269
#define COMMAND_Move_Playlist_entry_Down_CONST 270
#define COMMAND_Remove_playlist_entry_CONST 271
#define COMMAND_Restart_DCERouter_CONST 272
#define COMMAND_EIB_Write_CONST 273
#define COMMAND_Set_Room_For_Device_CONST 274
#define COMMAND_EIB_Read_CONST 275
#define COMMAND_Add_GC100_CONST 276
#define COMMAND_Get_Capture_Video_Frame_CONST 277
#define COMMAND_Set_Temperature_CONST 278
#define COMMAND_Set_Fan_CONST 279
#define COMMAND_Set_HeatCool_CONST 280
#define COMMAND_DBSSatellite_CONST 281
#define COMMAND_VCR1_CONST 282
#define COMMAND_VCR2_CONST 283
#define COMMAND_VCR3_CONST 284
#define COMMAND_VAUX_CONST 285
#define COMMAND_Pure_Direct_CONST 286
#define COMMAND_Multi_Channel_In_CONST 287
#define COMMAND_Multi_Channel_Direct_CONST 288
#define COMMAND_Multi_Channel_Pure_Direct_CONST 289
#define COMMAND_Dolby_Pro_Logic_CONST 290
#define COMMAND_Dolby_Pro_Logic_2_CONST 291
#define COMMAND_Dolby_Digital_CONST 292
#define COMMAND_Dolby_Digital_EX_CONST 293
#define COMMAND_61_Surround_CONST 294
#define COMMAND_DTS_NEO_6_CONST 295
#define COMMAND_DTS_Surround_CONST 296
#define COMMAND_DTS_ES_DSCRT61_CONST 297
#define COMMAND_DTS_ES_MTRX61_CONST 298
#define COMMAND_Home_THX_Cinema_CONST 299
#define COMMAND_THX_51_CONST 300
#define COMMAND_THX_U2_Cinema_CONST 301
#define COMMAND_THX_Music_CONST 302
#define COMMAND_THX_61_CONST 303
#define COMMAND_THX_Surround_EX_CONST 304
#define COMMAND_Wide_Screen_CONST 305
#define COMMAND_5_CH_Stereo_CONST 306
#define COMMAND_7_Ch_Stereo_CONST 307
#define COMMAND_Direct_CONST 308
#define COMMAND_Matrix_CONST 309
#define COMMAND_Mono_Movie_CONST 310
#define COMMAND_Stereo_CONST 311
#define COMMAND_Stadium_CONST 312
#define COMMAND_Set_Volume_CONST 313
#define COMMAND_Identify_Media_CONST 314
#define COMMAND_Key_Pressed_CONST 315
#define COMMAND_AV_1_CONST 316
#define COMMAND_AV_2_CONST 317
#define COMMAND_AV_3_CONST 318
#define COMMAND_SVideoYC_1_CONST 319
#define COMMAND_SVideoYC_2_CONST 320
#define COMMAND_SVideoYC_3_CONST 321
#define COMMAND_Wake_Device_CONST 322
#define COMMAND_Halt_Device_CONST 323
#define COMMAND_Set_Timeout_CONST 324
#define COMMAND_Keep_Screen_On_CONST 325
#define COMMAND_Tuner_3_CONST 326
#define COMMAND_WB_CONST 327
#define COMMAND_SW_CONST 328
#define COMMAND_Set_Mouse_Pointer_Over_Object_CONST 330
#define COMMAND_Get_EntAreas_For_Device_CONST 331
#define COMMAND_Ignore_MAC_Address_CONST 332
#define COMMAND_Disconnect_From_Mobile_Orbiter_CONST 333
#define COMMAND_Phone_Initiate_CONST 334
#define COMMAND_Phone_Answer_CONST 335
#define COMMAND_Phone_Drop_CONST 336
#define COMMAND_Rip_Disk_CONST 337
#define COMMAND_Process_Incoming_Data_CONST 350
#define COMMAND_Process_IDLE_CONST 351
#define COMMAND_Show_Mouse_Pointer_CONST 354
#define COMMAND_Process_Initialize_CONST 355
#define COMMAND_Process_Release_CONST 356
#define COMMAND_HDMI_CONST 361
#define COMMAND_D4_CONST 362
#define COMMAND_Back_Clear_Entry_CONST 363
#define COMMAND_Get_Room_Description_CONST 365
#define COMMAND_Activate_Window_CONST 366
#define COMMAND_Text_CONST 367
#define COMMAND_Help_CONST 368
#define COMMAND_Radio_CONST 369
#define COMMAND_Execute_Command_Group_CONST 370
#define COMMAND_Is_Daytime_CONST 371
#define COMMAND_MH_Set_Volume_CONST 372

#define COMMAND_TABLE "Command"
#define COMMAND_PK_COMMAND_FIELD "PK_Command"
#define COMMAND_PK_COMMAND_TABLE_FIELD "Command.PK_Command"
#define COMMAND_DESCRIPTION_FIELD "Description"
#define COMMAND_DESCRIPTION_TABLE_FIELD "Command.Description"
#define COMMAND_DEFINE_FIELD "Define"
#define COMMAND_DEFINE_TABLE_FIELD "Command.Define"
#define COMMAND_FK_COMMANDCATEGORY_FIELD "FK_CommandCategory"
#define COMMAND_FK_COMMANDCATEGORY_TABLE_FIELD "Command.FK_CommandCategory"
#define COMMAND_AVCOMMAND_FIELD "AVCommand"
#define COMMAND_AVCOMMAND_TABLE_FIELD "Command.AVCommand"
#define COMMAND_COMMENTS_FIELD "Comments"
#define COMMAND_COMMENTS_TABLE_FIELD "Command.Comments"
#define COMMAND_PSC_ID_FIELD "psc_id"
#define COMMAND_PSC_ID_TABLE_FIELD "Command.psc_id"
#define COMMAND_PSC_BATCH_FIELD "psc_batch"
#define COMMAND_PSC_BATCH_TABLE_FIELD "Command.psc_batch"
#define COMMAND_PSC_USER_FIELD "psc_user"
#define COMMAND_PSC_USER_TABLE_FIELD "Command.psc_user"
#define COMMAND_PSC_FROZEN_FIELD "psc_frozen"
#define COMMAND_PSC_FROZEN_TABLE_FIELD "Command.psc_frozen"
#define COMMAND_PSC_MOD_FIELD "psc_mod"
#define COMMAND_PSC_MOD_TABLE_FIELD "Command.psc_mod"


#endif

