#ifndef __Define_Package_Source_pschist_H__
#define __Define_Package_Source_pschist_H__


#define PACKAGE_SOURCE_PSCHIST_TABLE "Package_Source_pschist"
#define PACKAGE_SOURCE_PSCHIST_PK_PACKAGE_SOURCE_FIELD "PK_Package_Source"
#define PACKAGE_SOURCE_PSCHIST_PK_PACKAGE_SOURCE_TABLE_FIELD "Package_Source_pschist.PK_Package_Source"
#define PACKAGE_SOURCE_PSCHIST_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_SOURCE_PSCHIST_FK_PACKAGE_TABLE_FIELD "Package_Source_pschist.FK_Package"
#define PACKAGE_SOURCE_PSCHIST_NAME_FIELD "Name"
#define PACKAGE_SOURCE_PSCHIST_NAME_TABLE_FIELD "Package_Source_pschist.Name"
#define PACKAGE_SOURCE_PSCHIST_FK_REPOSITORYSOURCE_FIELD "FK_RepositorySource"
#define PACKAGE_SOURCE_PSCHIST_FK_REPOSITORYSOURCE_TABLE_FIELD "Package_Source_pschist.FK_RepositorySource"
#define PACKAGE_SOURCE_PSCHIST_REPOSITORY_FIELD "Repository"
#define PACKAGE_SOURCE_PSCHIST_REPOSITORY_TABLE_FIELD "Package_Source_pschist.Repository"
#define PACKAGE_SOURCE_PSCHIST_VERSION_FIELD "Version"
#define PACKAGE_SOURCE_PSCHIST_VERSION_TABLE_FIELD "Package_Source_pschist.Version"
#define PACKAGE_SOURCE_PSCHIST_PARMS_FIELD "Parms"
#define PACKAGE_SOURCE_PSCHIST_PARMS_TABLE_FIELD "Package_Source_pschist.Parms"
#define PACKAGE_SOURCE_PSCHIST_REPLACES_FIELD "Replaces"
#define PACKAGE_SOURCE_PSCHIST_REPLACES_TABLE_FIELD "Package_Source_pschist.Replaces"
#define PACKAGE_SOURCE_PSCHIST_CONFLICTS_FIELD "Conflicts"
#define PACKAGE_SOURCE_PSCHIST_CONFLICTS_TABLE_FIELD "Package_Source_pschist.Conflicts"
#define PACKAGE_SOURCE_PSCHIST_PROVIDES_FIELD "Provides"
#define PACKAGE_SOURCE_PSCHIST_PROVIDES_TABLE_FIELD "Package_Source_pschist.Provides"
#define PACKAGE_SOURCE_PSCHIST_PSC_ID_FIELD "psc_id"
#define PACKAGE_SOURCE_PSCHIST_PSC_ID_TABLE_FIELD "Package_Source_pschist.psc_id"
#define PACKAGE_SOURCE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_SOURCE_PSCHIST_PSC_BATCH_TABLE_FIELD "Package_Source_pschist.psc_batch"
#define PACKAGE_SOURCE_PSCHIST_PSC_USER_FIELD "psc_user"
#define PACKAGE_SOURCE_PSCHIST_PSC_USER_TABLE_FIELD "Package_Source_pschist.psc_user"
#define PACKAGE_SOURCE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_SOURCE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Package_Source_pschist.psc_frozen"
#define PACKAGE_SOURCE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_SOURCE_PSCHIST_PSC_MOD_TABLE_FIELD "Package_Source_pschist.psc_mod"
#define PACKAGE_SOURCE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PACKAGE_SOURCE_PSCHIST_PSC_TOC_TABLE_FIELD "Package_Source_pschist.psc_toc"
#define PACKAGE_SOURCE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_SOURCE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Package_Source_pschist.psc_restrict"


#endif

