#ifndef __Define_EventCategory_pschmask_H__
#define __Define_EventCategory_pschmask_H__


#define EVENTCATEGORY_PSCHMASK_TABLE "EventCategory_pschmask"
#define EVENTCATEGORY_PSCHMASK_PK_EVENTCATEGORY_FIELD "PK_EventCategory"
#define EVENTCATEGORY_PSCHMASK_PK_EVENTCATEGORY_TABLE_FIELD "EventCategory_pschmask.PK_EventCategory"
#define EVENTCATEGORY_PSCHMASK_FK_EVENTCATEGORY_PARENT_FIELD "FK_EventCategory_Parent"
#define EVENTCATEGORY_PSCHMASK_FK_EVENTCATEGORY_PARENT_TABLE_FIELD "EventCategory_pschmask.FK_EventCategory_Parent"
#define EVENTCATEGORY_PSCHMASK_DESCRIPTION_FIELD "Description"
#define EVENTCATEGORY_PSCHMASK_DESCRIPTION_TABLE_FIELD "EventCategory_pschmask.Description"
#define EVENTCATEGORY_PSCHMASK_PSC_ID_FIELD "psc_id"
#define EVENTCATEGORY_PSCHMASK_PSC_ID_TABLE_FIELD "EventCategory_pschmask.psc_id"
#define EVENTCATEGORY_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define EVENTCATEGORY_PSCHMASK_PSC_BATCH_TABLE_FIELD "EventCategory_pschmask.psc_batch"
#define EVENTCATEGORY_PSCHMASK_PSC_USER_FIELD "psc_user"
#define EVENTCATEGORY_PSCHMASK_PSC_USER_TABLE_FIELD "EventCategory_pschmask.psc_user"
#define EVENTCATEGORY_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define EVENTCATEGORY_PSCHMASK_PSC_FROZEN_TABLE_FIELD "EventCategory_pschmask.psc_frozen"
#define EVENTCATEGORY_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define EVENTCATEGORY_PSCHMASK_PSC_MOD_TABLE_FIELD "EventCategory_pschmask.psc_mod"
#define EVENTCATEGORY_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define EVENTCATEGORY_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "EventCategory_pschmask.psc_restrict"


#endif

