#ifndef __Define_Screen_DesignObj_H__
#define __Define_Screen_DesignObj_H__


#define SCREEN_DESIGNOBJ_TABLE "Screen_DesignObj"
#define SCREEN_DESIGNOBJ_PK_SCREEN_DESIGNOBJ_FIELD "PK_Screen_DesignObj"
#define SCREEN_DESIGNOBJ_PK_SCREEN_DESIGNOBJ_TABLE_FIELD "Screen_DesignObj.PK_Screen_DesignObj"
#define SCREEN_DESIGNOBJ_FK_SCREEN_FIELD "FK_Screen"
#define SCREEN_DESIGNOBJ_FK_SCREEN_TABLE_FIELD "Screen_DesignObj.FK_Screen"
#define SCREEN_DESIGNOBJ_FK_DESIGNOBJ_FIELD "FK_DesignObj"
#define SCREEN_DESIGNOBJ_FK_DESIGNOBJ_TABLE_FIELD "Screen_DesignObj.FK_DesignObj"
#define SCREEN_DESIGNOBJ_FK_UI_FIELD "FK_UI"
#define SCREEN_DESIGNOBJ_FK_UI_TABLE_FIELD "Screen_DesignObj.FK_UI"
#define SCREEN_DESIGNOBJ_FK_SKIN_FIELD "FK_Skin"
#define SCREEN_DESIGNOBJ_FK_SKIN_TABLE_FIELD "Screen_DesignObj.FK_Skin"
#define SCREEN_DESIGNOBJ_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define SCREEN_DESIGNOBJ_FK_DEVICETEMPLATE_TABLE_FIELD "Screen_DesignObj.FK_DeviceTemplate"
#define SCREEN_DESIGNOBJ_ASPOPUP_FIELD "AsPopup"
#define SCREEN_DESIGNOBJ_ASPOPUP_TABLE_FIELD "Screen_DesignObj.AsPopup"
#define SCREEN_DESIGNOBJ_POPUP_X_FIELD "Popup_X"
#define SCREEN_DESIGNOBJ_POPUP_X_TABLE_FIELD "Screen_DesignObj.Popup_X"
#define SCREEN_DESIGNOBJ_POPUP_Y_FIELD "Popup_Y"
#define SCREEN_DESIGNOBJ_POPUP_Y_TABLE_FIELD "Screen_DesignObj.Popup_Y"
#define SCREEN_DESIGNOBJ_PSC_ID_FIELD "psc_id"
#define SCREEN_DESIGNOBJ_PSC_ID_TABLE_FIELD "Screen_DesignObj.psc_id"
#define SCREEN_DESIGNOBJ_PSC_BATCH_FIELD "psc_batch"
#define SCREEN_DESIGNOBJ_PSC_BATCH_TABLE_FIELD "Screen_DesignObj.psc_batch"
#define SCREEN_DESIGNOBJ_PSC_USER_FIELD "psc_user"
#define SCREEN_DESIGNOBJ_PSC_USER_TABLE_FIELD "Screen_DesignObj.psc_user"
#define SCREEN_DESIGNOBJ_PSC_FROZEN_FIELD "psc_frozen"
#define SCREEN_DESIGNOBJ_PSC_FROZEN_TABLE_FIELD "Screen_DesignObj.psc_frozen"
#define SCREEN_DESIGNOBJ_PSC_MOD_FIELD "psc_mod"
#define SCREEN_DESIGNOBJ_PSC_MOD_TABLE_FIELD "Screen_DesignObj.psc_mod"
#define SCREEN_DESIGNOBJ_PSC_RESTRICT_FIELD "psc_restrict"
#define SCREEN_DESIGNOBJ_PSC_RESTRICT_TABLE_FIELD "Screen_DesignObj.psc_restrict"


#endif

