#ifndef __Define_ParameterType_pschmask_H__
#define __Define_ParameterType_pschmask_H__


#define PARAMETERTYPE_PSCHMASK_TABLE "ParameterType_pschmask"
#define PARAMETERTYPE_PSCHMASK_PK_PARAMETERTYPE_FIELD "PK_ParameterType"
#define PARAMETERTYPE_PSCHMASK_PK_PARAMETERTYPE_TABLE_FIELD "ParameterType_pschmask.PK_ParameterType"
#define PARAMETERTYPE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define PARAMETERTYPE_PSCHMASK_DESCRIPTION_TABLE_FIELD "ParameterType_pschmask.Description"
#define PARAMETERTYPE_PSCHMASK_DEFINE_FIELD "Define"
#define PARAMETERTYPE_PSCHMASK_DEFINE_TABLE_FIELD "ParameterType_pschmask.Define"
#define PARAMETERTYPE_PSCHMASK_CPPTYPE_FIELD "CPPType"
#define PARAMETERTYPE_PSCHMASK_CPPTYPE_TABLE_FIELD "ParameterType_pschmask.CPPType"
#define PARAMETERTYPE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PARAMETERTYPE_PSCHMASK_PSC_ID_TABLE_FIELD "ParameterType_pschmask.psc_id"
#define PARAMETERTYPE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PARAMETERTYPE_PSCHMASK_PSC_BATCH_TABLE_FIELD "ParameterType_pschmask.psc_batch"
#define PARAMETERTYPE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PARAMETERTYPE_PSCHMASK_PSC_USER_TABLE_FIELD "ParameterType_pschmask.psc_user"
#define PARAMETERTYPE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PARAMETERTYPE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "ParameterType_pschmask.psc_frozen"
#define PARAMETERTYPE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PARAMETERTYPE_PSCHMASK_PSC_MOD_TABLE_FIELD "ParameterType_pschmask.psc_mod"
#define PARAMETERTYPE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PARAMETERTYPE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "ParameterType_pschmask.psc_restrict"


#endif

