#ifndef __Define_Command_H__
#define __Define_Command_H__

#define COMMAND_Capture_Keyboard_To_Variable_CONST 1
#define COMMAND_Orbiter_Beep_CONST 2
#define COMMAND_Display_OnOff_CONST 3
#define COMMAND_Go_back_CONST 4
#define COMMAND_Goto_Screen_CONST 5
#define COMMAND_Show_Object_CONST 6
#define COMMAND_Terminate_Orbiter_CONST 7
#define COMMAND_Remove_Screen_From_History_CONST 8
#define COMMAND_Scroll_Grid_CONST 9
#define COMMAND_Move_Highlight_CONST 10
#define COMMAND_Play_Sound_CONST 13
#define COMMAND_Refresh_CONST 14
#define COMMAND_Regen_Screen_CONST 15
#define COMMAND_Requires_Special_Handling_CONST 16
#define COMMAND_Seek_Data_Grid_CONST 17
#define COMMAND_Set_Graphic_To_Display_CONST 18
#define COMMAND_Set_House_Mode_CONST 19
#define COMMAND_Set_Object_Parameter_CONST 20
#define COMMAND_Set_Object_Position_CONST 21
#define COMMAND_Set_Object_Size_CONST 22
#define COMMAND_Set_Pos_Rel_To_Parent_CONST 23
#define COMMAND_Set_Size_Rel_To_Parent_CONST 24
#define COMMAND_Set_Text_CONST 25
#define COMMAND_Set_Bound_Icon_CONST 26
#define COMMAND_Set_Variable_CONST 27
#define COMMAND_Simulate_Keypress_CONST 28
#define COMMAND_Simulate_Mouse_Click_CONST 29
#define COMMAND_Stop_Sound_CONST 30
#define COMMAND_Store_Variables_CONST 31
#define COMMAND_Update_Object_Image_CONST 32
#define COMMAND_Start_Media_CONST 33
#define COMMAND_Request_Datagrid_Contents_CONST 34
#define COMMAND_Populate_Datagrid_CONST 35
#define COMMAND_Create_Media_CONST 36
#define COMMAND_Play_Media_CONST 37
#define COMMAND_Stop_Media_CONST 38
#define COMMAND_Pause_Media_CONST 39
#define COMMAND_Restart_Media_CONST 40
#define COMMAND_Change_Playback_Speed_CONST 41
#define COMMAND_Jump_to_Position_in_Stream_CONST 42
#define COMMAND_MH_Play_Media_CONST 43
#define COMMAND_MH_Stop_Media_CONST 44
#define COMMAND_Disk_Drive_Monitoring_ON_CONST 45
#define COMMAND_Disk_Drive_Monitoring_OFF_CONST 46
#define COMMAND_Reset_Disk_Drive_CONST 47
#define COMMAND_Eject_Disk_CONST 48
#define COMMAND_Start_Burn_Session_CONST 49
#define COMMAND_Start_Ripping_Session_CONST 50
#define COMMAND_Add_File_To_Burning_Session_CONST 51
#define COMMAND_Start_Burning_CONST 52
#define COMMAND_Abort_Burning_CONST 53
#define COMMAND_Mount_Disk_Image_CONST 54
#define COMMAND_Abort_Ripping_CONST 55
#define COMMAND_Format_Drive_CONST 56
#define COMMAND_Close_Tray_CONST 57
#define COMMAND_Set_Current_User_CONST 58
#define COMMAND_Set_Entertainment_Area_CONST 59
#define COMMAND_Link_with_mobile_orbiter_CONST 60
#define COMMAND_Get_Signal_Strength_CONST 61
#define COMMAND_Create_Mobile_Orbiter_CONST 62
#define COMMAND_Skip_Fwd_ChannelTrack_Greater_CONST 63
#define COMMAND_Skip_Back_ChannelTrack_Lower_CONST 64
#define COMMAND_Jump_Position_In_Playlist_CONST 65
#define COMMAND_Select_Object_CONST 66
#define COMMAND_Spawn_Application_CONST 67
#define COMMAND_Get_Device_Data_CONST 68
#define COMMAND_Kill_Application_CONST 69
#define COMMAND_Hide_Application_CONST 70
#define COMMAND_Request_File_CONST 71
#define COMMAND_Surrender_to_OS_CONST 72
#define COMMAND_Bind_to_Media_Remote_CONST 74
#define COMMAND_Set_Current_Room_CONST 77
#define COMMAND_New_Mobile_Orbiter_CONST 78
#define COMMAND_Add_Unknown_Device_CONST 79
#define COMMAND_Send_File_To_Device_CONST 80
#define COMMAND_Navigate_Next_CONST 81
#define COMMAND_Navigate_Prev_CONST 82
#define COMMAND_Get_Video_Frame_CONST 84
#define COMMAND_Reset_Highlight_CONST 85
#define COMMAND_Menu_Show_Menu_CONST 86
#define COMMAND_Goto_Media_Menu_CONST 87
#define COMMAND_Set_Current_Location_CONST 88
#define COMMAND_Vol_Up_CONST 89
#define COMMAND_Vol_Down_CONST 90
#define COMMAND_Input_Select_CONST 91
#define COMMAND_Pause_CONST 92
#define COMMAND_Scan_FwdFast_Fwd_CONST 93
#define COMMAND_Stop_CONST 95
#define COMMAND_Change_Disc_CONST 96
#define COMMAND_Mute_CONST 97
#define COMMAND_Slow_Scan_Back_CONST 98
#define COMMAND_Slow_Scan_Forward_CONST 99
#define COMMAND_Record_CONST 102
#define COMMAND_Random_CONST 103
#define COMMAND_Repeat_CONST 104
#define COMMAND_Fwd_14x_CONST 105
#define COMMAND_Fwd_12x_CONST 106
#define COMMAND_Fwd_2x_CONST 107
#define COMMAND_Fwd_4x_CONST 108
#define COMMAND_Fwd_8x_CONST 109
#define COMMAND_Back_14x_CONST 110
#define COMMAND_Back_12x_CONST 111
#define COMMAND_Back_1x_CONST 112
#define COMMAND_Back_2x_CONST 113
#define COMMAND_Back_4x_CONST 114
#define COMMAND_Back_8x_CONST 115
#define COMMAND_DSP_Mode_CONST 116
#define COMMAND_Skip_To_End_CONST 117
#define COMMAND_Back_16x_CONST 119
#define COMMAND_Back_32X_CONST 120
#define COMMAND_Fwd_16x_CONST 121
#define COMMAND_Fwd_32x_CONST 122
#define COMMAND_Info_CONST 123
#define COMMAND_Favorites_CONST 124
#define COMMAND_Scan_BackRewind_CONST 125
#define COMMAND_Guide_CONST 126
#define COMMAND_PIP_ON_CONST 127
#define COMMAND_PIP_OFF_CONST 128
#define COMMAND_PIP_Channel_Up_CONST 129
#define COMMAND_PIP_Channel_Down_CONST 130
#define COMMAND_PIP_Channel_Number_CONST 131
#define COMMAND_Taller_CONST 132
#define COMMAND_Shorter_CONST 133
#define COMMAND_Wider_CONST 134
#define COMMAND_Narrower_CONST 135
#define COMMAND_Previous_Channel_CONST 136
#define COMMAND_Music_CONST 137
#define COMMAND_Eject_CONST 138
#define COMMAND_Play_CONST 139
#define COMMAND_Audio_Track_CONST 140
#define COMMAND_Subtitle_CONST 141
#define COMMAND_Angle_CONST 142
#define COMMAND_Progressive_CONST 144
#define COMMAND_Back_10_seconds_CONST 145
#define COMMAND_Multi_Channel_CONST 146
#define COMMAND_Hall_CONST 147
#define COMMAND_Church_CONST 148
#define COMMAND_Jazz_Club_CONST 149
#define COMMAND_Rock_Concert_CONST 150
#define COMMAND_Entertainment_CONST 151
#define COMMAND_Music_Video_CONST 152
#define COMMAND_Classical_CONST 153
#define COMMAND_RGB_CONST 154
#define COMMAND_Video_1_CONST 155
#define COMMAND_Video_2_CONST 156
#define COMMAND_Video_3_CONST 157
#define COMMAND_Video_4_CONST 158
#define COMMAND_Video_5_CONST 159
#define COMMAND_Tape_Tape_1_CONST 160
#define COMMAND_TV_CONST 161
#define COMMAND_CD_CONST 162
#define COMMAND_Phono_CONST 163
#define COMMAND_Aux_CONST 164
#define COMMAND_DVD_CONST 165
#define COMMAND_Tuner_CONST 166
#define COMMAND_Video_6_CONST 167
#define COMMAND_Video_7_CONST 168
#define COMMAND_AM_CONST 169
#define COMMAND_FM_CONST 170
#define COMMAND_DVD_Multi_CONST 171
#define COMMAND_Aux_2_CONST 172
#define COMMAND_Tape_2_CONST 173
#define COMMAND_Minidisc_CONST 174
#define COMMAND_Tuner_2_CONST 175
#define COMMAND_VDP_CONST 176
#define COMMAND_Laserdisc_CONST 177
#define COMMAND_DSS_CONST 178
#define COMMAND_DVI_CONST 179
#define COMMAND_Svideo_CONST 180
#define COMMAND_Composite_CONST 181
#define COMMAND_RF_Input_CONST 182
#define COMMAND_Get_Floorplan_Layout_CONST 183
#define COMMAND_Set_Level_CONST 184
#define COMMAND_Schedule_Recording_CONST 185
#define COMMAND_Get_Current_Floorplan_CONST 186
#define COMMAND_Tune_to_channel_CONST 187
#define COMMAND_Get_Infrared_Codes_CONST 188
#define COMMAND_Send_Generic_EnterGo_CONST 190
#define COMMAND_Send_Code_CONST 191
#define COMMAND_Generic_On_CONST 192
#define COMMAND_Generic_Off_CONST 193
#define COMMAND_Toggle_Power_CONST 194
#define COMMAND_Dial_CONST 195
#define COMMAND_Move_Up_CONST 200
#define COMMAND_Move_Down_CONST 201
#define COMMAND_Move_Left_CONST 202
#define COMMAND_Move_Right_CONST 203
#define COMMAND_0_CONST 204
#define COMMAND_1_CONST 205
#define COMMAND_2_CONST 206
#define COMMAND_3_CONST 207
#define COMMAND_4_CONST 208
#define COMMAND_5_CONST 209
#define COMMAND_6_CONST 210
#define COMMAND_7_CONST 211
#define COMMAND_8_CONST 212
#define COMMAND_9_CONST 213
#define COMMAND_Save_playlist_CONST 214
#define COMMAND__CONST 215
#define COMMAND_Balance_Sel_CONST 216
#define COMMAND_Balance_Left_CONST 217
#define COMMAND_Balance_Right_CONST 218
#define COMMAND_Contrast_Sel_CONST 219
#define COMMAND_Contrast_Up_CONST 220
#define COMMAND_Contrast_Down_CONST 221
#define COMMAND_Brightness_Sel_CONST 222
#define COMMAND_Brightness_Up_CONST 223
#define COMMAND_Brightness_Down_CONST 224
#define COMMAND_Display_CONST 225
#define COMMAND_Originate_Renamed_To_Not_Break_Compiles_CONST 226
#define COMMAND_Originate_CONST 227
#define COMMAND_Bass_Sel_CONST 228
#define COMMAND_Bass_Up_CONST 229
#define COMMAND_Bass_Down_CONST 230
#define COMMAND_Load_Playlist_CONST 231
#define COMMAND_PL_Originate_CONST 232
#define COMMAND_PBX_Originate_CONST 233
#define COMMAND_PL_TransferConferenceDevice_CONST 234
#define COMMAND_PBX_Transfer_CONST 235
#define COMMAND_PL_Hangup_CONST 236
#define COMMAND_PBX_Hangup_CONST 237
#define COMMAND_Continuous_Refresh_CONST 238
#define COMMAND_Request_File_And_Checksum_CONST 239
#define COMMAND_Back_Prior_Menu_CONST 240
#define COMMAND_MH_Move_Media_CONST 241
#define COMMAND_Set_Now_Playing_CONST 242
#define COMMAND_Output_Select_CONST 244
#define COMMAND_Learn_IR_CONST 245
#define COMMAND_Set_Device_Data_CONST 246
#define COMMAND_Get_Device_State_CONST 247
#define COMMAND_Get_Device_Status_CONST 248
#define COMMAND_Start_Streaming_CONST 249
#define COMMAND_Store_Infrared_Code_CONST 250
#define COMMAND_Save_Current_Frame_CONST 251
#define COMMAND_Send_Audio_To_Device_CONST 253
#define COMMAND_Bind_Icon_CONST 254
#define COMMAND_Orbiter_Registered_CONST 255
#define COMMAND_Text_To_Wave_CONST 256
#define COMMAND_Delay_CONST 257
#define COMMAND_Clear_Selected_Devices_CONST 258
#define COMMAND_Report_Playback_Position_CONST 259
#define COMMAND_Set_Main_Menu_CONST 260
#define COMMAND_Set_FollowMe_CONST 261
#define COMMAND_Stop_Streaming_CONST 262
#define COMMAND_Toggle_Event_Handler_CONST 263
#define COMMAND_Track_Frontend_At_IP_CONST 264
#define COMMAND_Quit_CONST 265
#define COMMAND_Regen_Orbiter_CONST 266
#define COMMAND_Regen_Orbiter_Finished_CONST 267
#define COMMAND_Move_Playlist_entry_Up_CONST 269
#define COMMAND_Move_Playlist_entry_Down_CONST 270
#define COMMAND_Remove_playlist_entry_CONST 271
#define COMMAND_Restart_DCERouter_CONST 272
#define COMMAND_EIB_Write_CONST 273
#define COMMAND_Set_Room_For_Device_CONST 274
#define COMMAND_EIB_Read_CONST 275
#define COMMAND_Add_GC100_CONST 276
#define COMMAND_Get_Capture_Video_Frame_CONST 277
#define COMMAND_Set_Temperature_CONST 278
#define COMMAND_Set_Fan_CONST 279
#define COMMAND_Set_HeatCool_CONST 280
#define COMMAND_DBSSatellite_CONST 281
#define COMMAND_VCR1_CONST 282
#define COMMAND_VCR2_CONST 283
#define COMMAND_VCR3_CONST 284
#define COMMAND_VAUX_CONST 285
#define COMMAND_Pure_Direct_CONST 286
#define COMMAND_Multi_Channel_In_CONST 287
#define COMMAND_Multi_Channel_Direct_CONST 288
#define COMMAND_Multi_Channel_Pure_Direct_CONST 289
#define COMMAND_Dolby_Pro_Logic_CONST 290
#define COMMAND_Dolby_Pro_Logic_2_CONST 291
#define COMMAND_Dolby_Digital_CONST 292
#define COMMAND_Dolby_Digital_EX_CONST 293
#define COMMAND_61_Surround_CONST 294
#define COMMAND_DTS_NEO_6_CONST 295
#define COMMAND_DTS_Surround_CONST 296
#define COMMAND_DTS_ES_DSCRT61_CONST 297
#define COMMAND_DTS_ES_MTRX61_CONST 298
#define COMMAND_Home_THX_Cinema_CONST 299
#define COMMAND_THX_51_CONST 300
#define COMMAND_THX_U2_Cinema_CONST 301
#define COMMAND_THX_Music_CONST 302
#define COMMAND_THX_61_CONST 303
#define COMMAND_THX_Surround_EX_CONST 304
#define COMMAND_Wide_Screen_CONST 305
#define COMMAND_5_CH_Stereo_CONST 306
#define COMMAND_7_Ch_Stereo_CONST 307
#define COMMAND_Direct_CONST 308
#define COMMAND_Matrix_CONST 309
#define COMMAND_Mono_Movie_CONST 310
#define COMMAND_Stereo_CONST 311
#define COMMAND_Stadium_CONST 312
#define COMMAND_Set_Volume_CONST 313
#define COMMAND_Identify_Media_CONST 314
#define COMMAND_Key_Pressed_CONST 315
#define COMMAND_AV_1_CONST 316
#define COMMAND_AV_2_CONST 317
#define COMMAND_AV_3_CONST 318
#define COMMAND_SVideoYC_1_CONST 319
#define COMMAND_SVideoYC_2_CONST 320
#define COMMAND_SVideoYC_3_CONST 321
#define COMMAND_Wake_Device_CONST 322
#define COMMAND_Halt_Device_CONST 323
#define COMMAND_Set_Timeout_CONST 324
#define COMMAND_Keep_Screen_On_CONST 325
#define COMMAND_Tuner_3_CONST 326
#define COMMAND_WB_CONST 327
#define COMMAND_SW_CONST 328
#define COMMAND_Set_Mouse_Pointer_Over_Object_CONST 330
#define COMMAND_Get_EntAreas_For_Device_CONST 331
#define COMMAND_Ignore_MAC_Address_CONST 332
#define COMMAND_Disconnect_From_Mobile_Orbiter_CONST 333
#define COMMAND_Phone_Initiate_CONST 334
#define COMMAND_Phone_Answer_CONST 335
#define COMMAND_Phone_Drop_CONST 336
#define COMMAND_Rip_Disk_CONST 337
#define COMMAND_Process_Incoming_Data_CONST 350
#define COMMAND_Process_IDLE_CONST 351
#define COMMAND_Show_Mouse_Pointer_CONST 354
#define COMMAND_Process_Initialize_CONST 355
#define COMMAND_Process_Release_CONST 356
#define COMMAND_HDMI_CONST 361
#define COMMAND_D4_CONST 362
#define COMMAND_Back_Clear_Entry_CONST 363
#define COMMAND_Get_Room_Description_CONST 365
#define COMMAND_Activate_Window_CONST 366
#define COMMAND_Text_CONST 367
#define COMMAND_Help_CONST 368
#define COMMAND_Radio_Mode_CONST 369
#define COMMAND_Execute_Command_Group_CONST 370
#define COMMAND_Is_Daytime_CONST 371
#define COMMAND_MH_Set_Volume_CONST 372
#define COMMAND_Private_Method_Listing_CONST 373
#define COMMAND_Input_1_CONST 374
#define COMMAND_Input_2_CONST 375
#define COMMAND_Input_3_CONST 376
#define COMMAND_Input_4_CONST 377
#define COMMAND_Input_5_CONST 378
#define COMMAND_Input_6_CONST 379
#define COMMAND_Input_7_CONST 380
#define COMMAND_Input_8_CONST 381
#define COMMAND_Input_9_CONST 382
#define COMMAND_Input_10_CONST 383
#define COMMAND_Process_Receive_Command_For_Child_CONST 384
#define COMMAND_Verify_PIN_CONST 387
#define COMMAND_Set_Media_Private_CONST 388
#define COMMAND_Send_Message_CONST 389
#define COMMAND_Add_Media_Attribute_CONST 391
#define COMMAND_Set_Media_Attribute_Text_CONST 392
#define COMMAND_Get_Attribute_CONST 393
#define COMMAND_Radio_CONST 394
#define COMMAND_Check_for_updates_CONST 395
#define COMMAND_Check_for_updates_done_CONST 396
#define COMMAND_Show_Popup_CONST 397
#define COMMAND_Remove_Popup_CONST 398
#define COMMAND_Show_Shortcuts_CONST 399
#define COMMAND_Show_File_List_CONST 401
#define COMMAND_Use_Popup_Remote_Controls_CONST 402
#define COMMAND_Use_Popup_File_List_CONST 403
#define COMMAND_Set_Auto_Switch_to_Remote_CONST 404
#define COMMAND_Scale_this_object_CONST 405
#define COMMAND_Display_Message_On_Orbiter_CONST 406
#define COMMAND_Set_Floorplan_CONST 407
#define COMMAND_Show_Floorplan_CONST 408
#define COMMAND_Save_Bookmark_CONST 409
#define COMMAND_Delete_Bookmark_CONST 410
#define COMMAND_Rename_Bookmark_CONST 411
#define COMMAND_Set_Media_Position_CONST 412
#define COMMAND_Forward_local_kb_to_OSD_CONST 413
#define COMMAND_PL_External_Originate_CONST 414
#define COMMAND_Set_Mouse_Position_Relative_CONST 415
#define COMMAND_Simulate_Mouse_Click_At_Present_Pos_CONST 416
#define COMMAND_Set_Auto_Resume_Options_CONST 417
#define COMMAND_AC3_CONST 418
#define COMMAND_Antenna_CONST 419
#define COMMAND_CDR_CONST 420
#define COMMAND_DAT_CONST 421
#define COMMAND_Dolby_B_CONST 422
#define COMMAND_Dolby_C_CONST 423
#define COMMAND_External_1_CONST 424
#define COMMAND_External_2_CONST 425
#define COMMAND_External_3_CONST 426
#define COMMAND_10_CONST 427
#define COMMAND_116_CONST 428
#define COMMAND_1732_CONST 429
#define COMMAND_20_CONST 430
#define COMMAND_30_CONST 431
#define COMMAND_3stereo_CONST 432
#define COMMAND_A_CONST 433
#define COMMAND_AB_CONST 434
#define COMMAND_ACH_CONST 435
#define COMMAND_AV_Status_CONST 436
#define COMMAND_Acoustic_Memo_CONST 437
#define COMMAND_Acoustic_Select_CONST 438
#define COMMAND_All_Off_CONST 439
#define COMMAND_All_On_CONST 440
#define COMMAND_AMS_CONST 441
#define COMMAND_Analogue_Down_CONST 442
#define COMMAND_Analogue_Menu_CONST 443
#define COMMAND_Analogue_Up_CONST 444
#define COMMAND_Audio_CONST 445
#define COMMAND_Audio_Menu_CONST 446
#define COMMAND_Auto_Search_CONST 447
#define COMMAND_Auto_Tracking_CONST 448
#define COMMAND_AV_CONST 449
#define COMMAND_B_CONST 450
#define COMMAND_Bass_Min_CONST 451
#define COMMAND_Bass_Plus_CONST 452
#define COMMAND_Blank_CONST 453
#define COMMAND_Blank_Search_CONST 454
#define COMMAND_Blue_CONST 455
#define COMMAND_Boost_CONST 456
#define COMMAND_Bright_CONST 457
#define COMMAND_C_CONST 458
#define COMMAND_CC_CONST 459
#define COMMAND_CD_Synch_CONST 460
#define COMMAND_CDText_CONST 461
#define COMMAND_Center_Down_CONST 462
#define COMMAND_Center_Up_CONST 463
#define COMMAND_Center_Volume_Down_CONST 464
#define COMMAND_Center_Volume_Up_CONST 465
#define COMMAND_Chapter_CONST 466
#define COMMAND_Child_Lock_CONST 467
#define COMMAND_Close_CONST 468
#define COMMAND_Closed_Caption_CONST 469
#define COMMAND_Coax_CONST 470
#define COMMAND_Color_Down_CONST 471
#define COMMAND_Color_Up_CONST 472
#define COMMAND_Continue_CONST 473
#define COMMAND_Counter_Reset_CONST 474
#define COMMAND_DailyWeekly_CONST 475
#define COMMAND_Day_Down_CONST 476
#define COMMAND_Day_Up_CONST 477
#define COMMAND_Delay_Down_CONST 478
#define COMMAND_Delay_Up_CONST 479
#define COMMAND_Delimiter_CONST 480
#define COMMAND_Digit_10_CONST 481
#define COMMAND_Digit_11_CONST 482
#define COMMAND_Digit_12_CONST 483
#define COMMAND_Digit_13_CONST 484
#define COMMAND_Digit_14_CONST 485
#define COMMAND_Digit_15_CONST 486
#define COMMAND_Digit_16_CONST 487
#define COMMAND_Dim_CONST 488
#define COMMAND_Direction_CONST 489
#define COMMAND_Disc_CONST 490
#define COMMAND_Disc_1_CONST 491
#define COMMAND_Disc_2_CONST 492
#define COMMAND_Disc_3_CONST 493
#define COMMAND_Disc_4_CONST 494
#define COMMAND_Disc_5_CONST 495
#define COMMAND_Disc_6_CONST 496
#define COMMAND_Disc_Down_CONST 497
#define COMMAND_Disc_Menu_CONST 498
#define COMMAND_Disc_Up_CONST 499
#define COMMAND_DiSeqC_CONST 500
#define COMMAND_DNR_CONST 501
#define COMMAND_Dual_CONST 502
#define COMMAND_Dub_CONST 503
#define COMMAND_Edit_CONST 504
#define COMMAND_Expand_CONST 505
#define COMMAND_Explore_CONST 506
#define COMMAND_Fade_In_CONST 507
#define COMMAND_Fade_Out_CONST 508
#define COMMAND_Favorite_CONST 509
#define COMMAND_Feature_CONST 510
#define COMMAND_Finalize_CONST 511
#define COMMAND_Format_CONST 512
#define COMMAND_Front_CONST 513
#define COMMAND_Front_Down_CONST 514
#define COMMAND_Front_Up_CONST 515
#define COMMAND_Go_To_CONST 516
#define COMMAND_Goto_CONST 517
#define COMMAND_Green_CONST 518
#define COMMAND_Group_CONST 519
#define COMMAND_Hold_CONST 520
#define COMMAND_Home_CONST 521
#define COMMAND_Index_Down_CONST 522
#define COMMAND_Index_Forward_CONST 523
#define COMMAND_Index_Mark_CONST 524
#define COMMAND_Index_Reverse_CONST 525
#define COMMAND_Index_Scan_CONST 526
#define COMMAND_Index_Up_CONST 527
#define COMMAND_Instant_Replay_CONST 528
#define COMMAND_Karaoke_Melody_CONST 529
#define COMMAND_Karaoke_Mode_CONST 530
#define COMMAND_Karaoke_OnOff_CONST 531
#define COMMAND_Karaoke_Once_More_CONST 532
#define COMMAND_Karaoke_Vocal_CONST 533
#define COMMAND_Language_CONST 534
#define COMMAND_Last_Play_CONST 535
#define COMMAND_Last_Record_Cancel_CONST 536
#define COMMAND_Level_Down_CONST 537
#define COMMAND_Level_Up_CONST 538
#define COMMAND_Light_CONST 539
#define COMMAND_LNB_CONST 540
#define COMMAND_LocalDistant_CONST 541
#define COMMAND_Mail_CONST 542
#define COMMAND_Main_Freeze_CONST 543
#define COMMAND_Main_Stored_CONST 544
#define COMMAND_Memclr_CONST 545
#define COMMAND_Memo_Clear_CONST 546
#define COMMAND_Memory_CONST 547
#define COMMAND_Menu_CONST 548
#define COMMAND_Mix_CONST 549
#define COMMAND_Mode_CONST 550
#define COMMAND_Monitor_CONST 551
#define COMMAND_Mosaic_CONST 552
#define COMMAND_Movie_CONST 553
#define COMMAND_Multi_Screen_CONST 554
#define COMMAND_Multiroom_CONST 555
#define COMMAND_Natural_Colour_CONST 556
#define COMMAND_New_Track_CONST 557
#define COMMAND_NewsTA_CONST 558
#define COMMAND_Next_CONST 559
#define COMMAND_Next_Speaker_CONST 560
#define COMMAND_Night_CONST 561
#define COMMAND_Normal_Backward_CONST 562
#define COMMAND_Normal_Forward_CONST 563
#define COMMAND_Normal_Picture_CONST 564
#define COMMAND_Normal_Rewind_CONST 565
#define COMMAND_Open_CONST 566
#define COMMAND_Opt_CONST 567
#define COMMAND_Options_CONST 568
#define COMMAND_Oscillate_CONST 569
#define COMMAND_OTR_CONST 570
#define COMMAND_Page_Down_CONST 571
#define COMMAND_Page_Up_CONST 572
#define COMMAND_PAP_CONST 573
#define COMMAND_Parental_Lock_CONST 574
#define COMMAND_Pay_Per_View_CONST 575
#define COMMAND_PBC_CONST 576
#define COMMAND_Peak_Hold_CONST 577
#define COMMAND_Picture_Menu_CONST 578
#define COMMAND_PIP_Freeze_CONST 579
#define COMMAND_PIP_Main_Swap_CONST 580
#define COMMAND_PIP_Select_CONST 581
#define COMMAND_PIP_Shift_CONST 582
#define COMMAND_PIP_Strobe_CONST 583
#define COMMAND_Prefs_CONST 584
#define COMMAND_Preset_Down_CONST 585
#define COMMAND_Preset_Up_CONST 586
#define COMMAND_PresetProgFreq_CONST 587
#define COMMAND_Previous_CONST 588
#define COMMAND_Previous_Program_CONST 589
#define COMMAND_Program_CONST 590
#define COMMAND_PTY_CONST 591
#define COMMAND_PVR_Menu_CONST 592
#define COMMAND_Quick_Skip_CONST 593
#define COMMAND_RDS_info_CONST 594
#define COMMAND_Rear_CONST 595
#define COMMAND_Rear_Down_CONST 596
#define COMMAND_Rear_Up_CONST 597
#define COMMAND_Recall_CONST 598
#define COMMAND_Recall_Main_CONST 599
#define COMMAND_Recent_CONST 600
#define COMMAND_Record_Blank_CONST 601
#define COMMAND_Record_Level_Down_CONST 602
#define COMMAND_Record_Level_Up_CONST 603
#define COMMAND_Record_Mode_CONST 604
#define COMMAND_Red_CONST 605
#define COMMAND_Reload_CONST 606
#define COMMAND_Repeat_AB_CONST 607
#define COMMAND_Repeat_All_CONST 609
#define COMMAND_Repeat_One_CONST 610
#define COMMAND_Return_to_Live_CONST 611
#define COMMAND_Reveal_CONST 612
#define COMMAND_RF_CONST 613
#define COMMAND_Save_CONST 614
#define COMMAND_Scan_CONST 615
#define COMMAND_Select_A_CONST 616
#define COMMAND_Select_B_CONST 617
#define COMMAND_Select_Down_CONST 618
#define COMMAND_Select_Up_CONST 619
#define COMMAND_Select_VPS_CONST 620
#define COMMAND_Sequential_CONST 621
#define COMMAND_Setup_Menu_CONST 622
#define COMMAND_Shuffle_CONST 623
#define COMMAND_Shuffle_All_CONST 624
#define COMMAND_Shuffle_One_CONST 625
#define COMMAND_Size_CONST 626
#define COMMAND_Skip_30_CONST 627
#define COMMAND_Sleep_CONST 628
#define COMMAND_Smart_Picture_CONST 629
#define COMMAND_Sound_Menu_CONST 630
#define COMMAND_Sound_Scroll_CONST 631
#define COMMAND_SPLP_CONST 632
#define COMMAND_Spatial_Sound_CONST 633
#define COMMAND_Speaker_CONST 634
#define COMMAND_Speed_CONST 635
#define COMMAND_Step_Down_CONST 636
#define COMMAND_Step_Up_CONST 637
#define COMMAND_StereoMono_CONST 638
#define COMMAND_Still_CONST 639
#define COMMAND_Store_CONST 640
#define COMMAND_Strobe_CONST 641
#define COMMAND_Subpage_CONST 642
#define COMMAND_Surround_CONST 643
#define COMMAND_Surround_Down_CONST 644
#define COMMAND_Surround_Mode_CONST 645
#define COMMAND_Surround_Up_CONST 646
#define COMMAND_System_Select_CONST 647
#define COMMAND_Tape_Select_CONST 648
#define COMMAND_Test_Tone_On_CONST 649
#define COMMAND_Text_Off_CONST 650
#define COMMAND_Thumbs_Down_CONST 651
#define COMMAND_Thumbs_Up_CONST 652
#define COMMAND_Time_Page_CONST 653
#define COMMAND_Timer_CONST 654
#define COMMAND_Timer_Prog_View_CONST 655
#define COMMAND_Timer_Program_CONST 656
#define COMMAND_Timer_Standby_CONST 657
#define COMMAND_Title_CONST 658
#define COMMAND_Today_CONST 659
#define COMMAND_Track_CONST 660
#define COMMAND_Tracking_Down_CONST 661
#define COMMAND_Tracking_Up_CONST 662
#define COMMAND_Treble_Down_CONST 663
#define COMMAND_Treble_Min_CONST 664
#define COMMAND_Treble_Plus_CONST 665
#define COMMAND_Treble_Up_CONST 666
#define COMMAND_TVCable_CONST 667
#define COMMAND_TVDVD_CONST 668
#define COMMAND_TVLD_CONST 669
#define COMMAND_TVRadio_CONST 670
#define COMMAND_TVSAT_CONST 671
#define COMMAND_TVVCR_CONST 672
#define COMMAND_TVVideo_CONST 673
#define COMMAND_Update_CONST 674
#define COMMAND_Video_Menu_CONST 675
#define COMMAND_Video_Mute_CONST 676
#define COMMAND_VideoShowview_CONST 677
#define COMMAND_View_CONST 678
#define COMMAND_VISS_Index_Next_CONST 679
#define COMMAND_VISS_Index_Previous_CONST 680
#define COMMAND_White_CONST 681
#define COMMAND_Yellow_CONST 682
#define COMMAND_Zoom_CONST 683
#define COMMAND_Zoom_In_CONST 684
#define COMMAND_Zoom_Out_CONST 685
#define COMMAND_Display_Dialog_Box_On_Orbiter_CONST 686
#define COMMAND_Set_Screen_Type_CONST 687
#define COMMAND_Get_Remote_Control_Mapping_CONST 688

#define COMMAND_TABLE "Command"
#define COMMAND_PK_COMMAND_FIELD "PK_Command"
#define COMMAND_PK_COMMAND_TABLE_FIELD "Command.PK_Command"
#define COMMAND_DESCRIPTION_FIELD "Description"
#define COMMAND_DESCRIPTION_TABLE_FIELD "Command.Description"
#define COMMAND_DEFINE_FIELD "Define"
#define COMMAND_DEFINE_TABLE_FIELD "Command.Define"
#define COMMAND_FK_COMMANDCATEGORY_FIELD "FK_CommandCategory"
#define COMMAND_FK_COMMANDCATEGORY_TABLE_FIELD "Command.FK_CommandCategory"
#define COMMAND_AVCOMMAND_FIELD "AVCommand"
#define COMMAND_AVCOMMAND_TABLE_FIELD "Command.AVCommand"
#define COMMAND_COMMENTS_FIELD "Comments"
#define COMMAND_COMMENTS_TABLE_FIELD "Command.Comments"
#define COMMAND_PSC_ID_FIELD "psc_id"
#define COMMAND_PSC_ID_TABLE_FIELD "Command.psc_id"
#define COMMAND_PSC_BATCH_FIELD "psc_batch"
#define COMMAND_PSC_BATCH_TABLE_FIELD "Command.psc_batch"
#define COMMAND_PSC_USER_FIELD "psc_user"
#define COMMAND_PSC_USER_TABLE_FIELD "Command.psc_user"
#define COMMAND_PSC_FROZEN_FIELD "psc_frozen"
#define COMMAND_PSC_FROZEN_TABLE_FIELD "Command.psc_frozen"
#define COMMAND_PSC_MOD_FIELD "psc_mod"
#define COMMAND_PSC_MOD_TABLE_FIELD "Command.psc_mod"
#define COMMAND_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMAND_PSC_RESTRICT_TABLE_FIELD "Command.psc_restrict"


#endif

