#ifndef __Define_TextCategory_pschist_H__
#define __Define_TextCategory_pschist_H__


#define TEXTCATEGORY_PSCHIST_TABLE "TextCategory_pschist"
#define TEXTCATEGORY_PSCHIST_PK_TEXTCATEGORY_FIELD "PK_TextCategory"
#define TEXTCATEGORY_PSCHIST_PK_TEXTCATEGORY_TABLE_FIELD "TextCategory_pschist.PK_TextCategory"
#define TEXTCATEGORY_PSCHIST_FK_TEXTCATEGORY_PARENT_FIELD "FK_TextCategory_Parent"
#define TEXTCATEGORY_PSCHIST_FK_TEXTCATEGORY_PARENT_TABLE_FIELD "TextCategory_pschist.FK_TextCategory_Parent"
#define TEXTCATEGORY_PSCHIST_DESCRIPTION_FIELD "Description"
#define TEXTCATEGORY_PSCHIST_DESCRIPTION_TABLE_FIELD "TextCategory_pschist.Description"
#define TEXTCATEGORY_PSCHIST_PSC_ID_FIELD "psc_id"
#define TEXTCATEGORY_PSCHIST_PSC_ID_TABLE_FIELD "TextCategory_pschist.psc_id"
#define TEXTCATEGORY_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define TEXTCATEGORY_PSCHIST_PSC_BATCH_TABLE_FIELD "TextCategory_pschist.psc_batch"
#define TEXTCATEGORY_PSCHIST_PSC_USER_FIELD "psc_user"
#define TEXTCATEGORY_PSCHIST_PSC_USER_TABLE_FIELD "TextCategory_pschist.psc_user"
#define TEXTCATEGORY_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define TEXTCATEGORY_PSCHIST_PSC_FROZEN_TABLE_FIELD "TextCategory_pschist.psc_frozen"
#define TEXTCATEGORY_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define TEXTCATEGORY_PSCHIST_PSC_MOD_TABLE_FIELD "TextCategory_pschist.psc_mod"
#define TEXTCATEGORY_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define TEXTCATEGORY_PSCHIST_PSC_TOC_TABLE_FIELD "TextCategory_pschist.psc_toc"
#define TEXTCATEGORY_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define TEXTCATEGORY_PSCHIST_PSC_RESTRICT_TABLE_FIELD "TextCategory_pschist.psc_restrict"


#endif

