#ifndef __Define_Package_Compat_pschmask_H__
#define __Define_Package_Compat_pschmask_H__


#define PACKAGE_COMPAT_PSCHMASK_TABLE "Package_Compat_pschmask"
#define PACKAGE_COMPAT_PSCHMASK_PK_PACKAGE_COMPAT_FIELD "PK_Package_Compat"
#define PACKAGE_COMPAT_PSCHMASK_PK_PACKAGE_COMPAT_TABLE_FIELD "Package_Compat_pschmask.PK_Package_Compat"
#define PACKAGE_COMPAT_PSCHMASK_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_COMPAT_PSCHMASK_FK_PACKAGE_TABLE_FIELD "Package_Compat_pschmask.FK_Package"
#define PACKAGE_COMPAT_PSCHMASK_FK_DISTRO_FIELD "FK_Distro"
#define PACKAGE_COMPAT_PSCHMASK_FK_DISTRO_TABLE_FIELD "Package_Compat_pschmask.FK_Distro"
#define PACKAGE_COMPAT_PSCHMASK_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define PACKAGE_COMPAT_PSCHMASK_FK_OPERATINGSYSTEM_TABLE_FIELD "Package_Compat_pschmask.FK_OperatingSystem"
#define PACKAGE_COMPAT_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PACKAGE_COMPAT_PSCHMASK_PSC_ID_TABLE_FIELD "Package_Compat_pschmask.psc_id"
#define PACKAGE_COMPAT_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_COMPAT_PSCHMASK_PSC_BATCH_TABLE_FIELD "Package_Compat_pschmask.psc_batch"
#define PACKAGE_COMPAT_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PACKAGE_COMPAT_PSCHMASK_PSC_USER_TABLE_FIELD "Package_Compat_pschmask.psc_user"
#define PACKAGE_COMPAT_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_COMPAT_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Package_Compat_pschmask.psc_frozen"
#define PACKAGE_COMPAT_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_COMPAT_PSCHMASK_PSC_MOD_TABLE_FIELD "Package_Compat_pschmask.psc_mod"
#define PACKAGE_COMPAT_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_COMPAT_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Package_Compat_pschmask.psc_restrict"


#endif

