#ifndef __Define_Document_Comment_pschmask_H__
#define __Define_Document_Comment_pschmask_H__


#define DOCUMENT_COMMENT_PSCHMASK_TABLE "Document_Comment_pschmask"
#define DOCUMENT_COMMENT_PSCHMASK_PK_DOCUMENT_COMMENT_FIELD "PK_Document_Comment"
#define DOCUMENT_COMMENT_PSCHMASK_PK_DOCUMENT_COMMENT_TABLE_FIELD "Document_Comment_pschmask.PK_Document_Comment"
#define DOCUMENT_COMMENT_PSCHMASK_FK_DOCUMENT_FIELD "FK_Document"
#define DOCUMENT_COMMENT_PSCHMASK_FK_DOCUMENT_TABLE_FIELD "Document_Comment_pschmask.FK_Document"
#define DOCUMENT_COMMENT_PSCHMASK_FK_USERS_FIELD "FK_Users"
#define DOCUMENT_COMMENT_PSCHMASK_FK_USERS_TABLE_FIELD "Document_Comment_pschmask.FK_Users"
#define DOCUMENT_COMMENT_PSCHMASK_COMMENT_FIELD "Comment"
#define DOCUMENT_COMMENT_PSCHMASK_COMMENT_TABLE_FIELD "Document_Comment_pschmask.Comment"
#define DOCUMENT_COMMENT_PSCHMASK_DATE_FIELD "Date"
#define DOCUMENT_COMMENT_PSCHMASK_DATE_TABLE_FIELD "Document_Comment_pschmask.Date"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_ID_TABLE_FIELD "Document_Comment_pschmask.psc_id"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_BATCH_TABLE_FIELD "Document_Comment_pschmask.psc_batch"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_USER_TABLE_FIELD "Document_Comment_pschmask.psc_user"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Document_Comment_pschmask.psc_frozen"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_MOD_TABLE_FIELD "Document_Comment_pschmask.psc_mod"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DOCUMENT_COMMENT_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Document_Comment_pschmask.psc_restrict"


#endif

