#ifndef __Define_psc_website_tables_H__
#define __Define_psc_website_tables_H__


#define PSC_WEBSITE_TABLES_TABLE "psc_website_tables"
#define PSC_WEBSITE_TABLES_PK_PSC_WEBSITE_TABLES_FIELD "PK_psc_website_tables"
#define PSC_WEBSITE_TABLES_PK_PSC_WEBSITE_TABLES_TABLE_FIELD "psc_website_tables.PK_psc_website_tables"
#define PSC_WEBSITE_TABLES_TABLENAME_FIELD "Tablename"
#define PSC_WEBSITE_TABLES_TABLENAME_TABLE_FIELD "psc_website_tables.Tablename"
#define PSC_WEBSITE_TABLES_FILTER_FIELD "filter"
#define PSC_WEBSITE_TABLES_FILTER_TABLE_FIELD "psc_website_tables.filter"
#define PSC_WEBSITE_TABLES_FROZEN_FIELD "frozen"
#define PSC_WEBSITE_TABLES_FROZEN_TABLE_FIELD "psc_website_tables.frozen"
#define PSC_WEBSITE_TABLES_ANONYMOUS_FIELD "anonymous"
#define PSC_WEBSITE_TABLES_ANONYMOUS_TABLE_FIELD "psc_website_tables.anonymous"
#define PSC_WEBSITE_TABLES_LAST_PSC_ID_FIELD "last_psc_id"
#define PSC_WEBSITE_TABLES_LAST_PSC_ID_TABLE_FIELD "psc_website_tables.last_psc_id"
#define PSC_WEBSITE_TABLES_LAST_PSC_BATCH_FIELD "last_psc_batch"
#define PSC_WEBSITE_TABLES_LAST_PSC_BATCH_TABLE_FIELD "psc_website_tables.last_psc_batch"


#endif

