#ifndef __Define_Package_Directory_H__
#define __Define_Package_Directory_H__


#define PACKAGE_DIRECTORY_TABLE "Package_Directory"
#define PACKAGE_DIRECTORY_PK_PACKAGE_DIRECTORY_FIELD "PK_Package_Directory"
#define PACKAGE_DIRECTORY_PK_PACKAGE_DIRECTORY_TABLE_FIELD "Package_Directory.PK_Package_Directory"
#define PACKAGE_DIRECTORY_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_DIRECTORY_FK_PACKAGE_TABLE_FIELD "Package_Directory.FK_Package"
#define PACKAGE_DIRECTORY_FK_DIRECTORY_FIELD "FK_Directory"
#define PACKAGE_DIRECTORY_FK_DIRECTORY_TABLE_FIELD "Package_Directory.FK_Directory"
#define PACKAGE_DIRECTORY_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define PACKAGE_DIRECTORY_FK_OPERATINGSYSTEM_TABLE_FIELD "Package_Directory.FK_OperatingSystem"
#define PACKAGE_DIRECTORY_FK_DISTRO_FIELD "FK_Distro"
#define PACKAGE_DIRECTORY_FK_DISTRO_TABLE_FIELD "Package_Directory.FK_Distro"
#define PACKAGE_DIRECTORY_PATH_FIELD "Path"
#define PACKAGE_DIRECTORY_PATH_TABLE_FIELD "Package_Directory.Path"
#define PACKAGE_DIRECTORY_INPUTPATH_FIELD "InputPath"
#define PACKAGE_DIRECTORY_INPUTPATH_TABLE_FIELD "Package_Directory.InputPath"
#define PACKAGE_DIRECTORY_FLIPSOURCE_FIELD "FlipSource"
#define PACKAGE_DIRECTORY_FLIPSOURCE_TABLE_FIELD "Package_Directory.FlipSource"
#define PACKAGE_DIRECTORY_GENERATEDOXYGEN_FIELD "GenerateDoxygen"
#define PACKAGE_DIRECTORY_GENERATEDOXYGEN_TABLE_FIELD "Package_Directory.GenerateDoxygen"
#define PACKAGE_DIRECTORY_PSC_ID_FIELD "psc_id"
#define PACKAGE_DIRECTORY_PSC_ID_TABLE_FIELD "Package_Directory.psc_id"
#define PACKAGE_DIRECTORY_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_DIRECTORY_PSC_BATCH_TABLE_FIELD "Package_Directory.psc_batch"
#define PACKAGE_DIRECTORY_PSC_USER_FIELD "psc_user"
#define PACKAGE_DIRECTORY_PSC_USER_TABLE_FIELD "Package_Directory.psc_user"
#define PACKAGE_DIRECTORY_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_DIRECTORY_PSC_FROZEN_TABLE_FIELD "Package_Directory.psc_frozen"
#define PACKAGE_DIRECTORY_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_DIRECTORY_PSC_MOD_TABLE_FIELD "Package_Directory.psc_mod"
#define PACKAGE_DIRECTORY_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_DIRECTORY_PSC_RESTRICT_TABLE_FIELD "Package_Directory.psc_restrict"


#endif

