#ifndef __Define_ConfigType_Setting_pschist_H__
#define __Define_ConfigType_Setting_pschist_H__


#define CONFIGTYPE_SETTING_PSCHIST_TABLE "ConfigType_Setting_pschist"
#define CONFIGTYPE_SETTING_PSCHIST_PK_CONFIGTYPE_SETTING_FIELD "PK_ConfigType_Setting"
#define CONFIGTYPE_SETTING_PSCHIST_PK_CONFIGTYPE_SETTING_TABLE_FIELD "ConfigType_Setting_pschist.PK_ConfigType_Setting"
#define CONFIGTYPE_SETTING_PSCHIST_FK_CONFIGTYPE_FIELD "FK_ConfigType"
#define CONFIGTYPE_SETTING_PSCHIST_FK_CONFIGTYPE_TABLE_FIELD "ConfigType_Setting_pschist.FK_ConfigType"
#define CONFIGTYPE_SETTING_PSCHIST_DESCRIPTION_FIELD "Description"
#define CONFIGTYPE_SETTING_PSCHIST_DESCRIPTION_TABLE_FIELD "ConfigType_Setting_pschist.Description"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_ID_FIELD "psc_id"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_ID_TABLE_FIELD "ConfigType_Setting_pschist.psc_id"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_BATCH_TABLE_FIELD "ConfigType_Setting_pschist.psc_batch"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_USER_FIELD "psc_user"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_USER_TABLE_FIELD "ConfigType_Setting_pschist.psc_user"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_FROZEN_TABLE_FIELD "ConfigType_Setting_pschist.psc_frozen"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_MOD_TABLE_FIELD "ConfigType_Setting_pschist.psc_mod"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_TOC_TABLE_FIELD "ConfigType_Setting_pschist.psc_toc"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define CONFIGTYPE_SETTING_PSCHIST_PSC_RESTRICT_TABLE_FIELD "ConfigType_Setting_pschist.psc_restrict"


#endif

