#ifndef __Define_DataGrid_H__
#define __Define_DataGrid_H__

#define DATAGRID_Directory_Listing_CONST 1
#define DATAGRID_DVD_Subtitles_CONST 2
#define DATAGRID_Mozilla_Bookmarks_CONST 3
#define DATAGRID_Lighting_Scenarios_CONST 4
#define DATAGRID_Media_Scenarios_CONST 5
#define DATAGRID_Climate_Scenarios_CONST 6
#define DATAGRID_Telecom_Scenarios_CONST 7
#define DATAGRID_Security_Scenarios_CONST 8
#define DATAGRID_EPG_Current_Shows_CONST 9
#define DATAGRID_Floorplan_Media_Streams_CONST 10
#define DATAGRID_EPG_All_Shows_CONST 11
#define DATAGRID_Media_Search_Auto_Compl_CONST 12
#define DATAGRID_Media_Attr_Files_CONST 13
#define DATAGRID_Media_Attr_Collections_CONST 14
#define DATAGRID_Media_Attr_Xref_CONST 15
#define DATAGRID_EPG_All_Shows_Mobile_CONST 16
#define DATAGRID_Media_Item_Attr_CONST 17
#define DATAGRID_Current_Media_Sections_CONST 18
#define DATAGRID_Floorplan_Media_Choices_CONST 19
#define DATAGRID_Playlists_CONST 20
#define DATAGRID_Phone_Book_Auto_Compl_CONST 21
#define DATAGRID_Phone_Book_List_of_Nos_CONST 22
#define DATAGRID_Devices_by_Room_CONST 23
#define DATAGRID_Commmands_By_Device_CONST 24
#define DATAGRID_Manufacturers_CONST 25
#define DATAGRID_Infrared_Groups_CONST 26
#define DATAGRID_Infrared_Group_Categories_CONST 27
#define DATAGRID_Infrared_Codes_CONST 28
#define DATAGRID_Alarms_In_Room_CONST 29
#define DATAGRID_Devices__Pipes_CONST 30
#define DATAGRID_Media_Attr_Cur_Stream_CONST 31
#define DATAGRID_Pending_Tasks_CONST 32
#define DATAGRID_DVD_Audio_Tracks_CONST 33
#define DATAGRID_DVD_Angles_CONST 34
#define DATAGRID_Bookmarks_CONST 35
#define DATAGRID_Quick_Start_Apps_CONST 36
#define DATAGRID_MRU_Documents_CONST 37
#define DATAGRID_Bookmarks_by_MediaType_CONST 38
#define DATAGRID_Rooms_CONST 39
#define DATAGRID_Favorite_Channels_CONST 40
#define DATAGRID_Favorite_Shows_CONST 41
#define DATAGRID_Other_Showtimes_CONST 42
#define DATAGRID_Types_Of_Mobile_Phones_CONST 43
#define DATAGRID_New_PNP_Devices_CONST 44
#define DATAGRID_Powerfile_CONST 45
#define DATAGRID_Users_CONST 46
#define DATAGRID_Countries_CONST 47
#define DATAGRID_Device_Template_by_Mfr_Mo_CONST 48
#define DATAGRID_Available_Inputs_CONST 49
#define DATAGRID_AVDeviceTypes_CONST 50
#define DATAGRID_TV_Providers_CONST 51
#define DATAGRID_LightType_CONST 53
#define DATAGRID_Devices_Children_Of_CONST 54
#define DATAGRID_Room_Types_CONST 55
#define DATAGRID_Available_Serial_Ports_CONST 56
#define DATAGRID_Installed_AV_Devices_CONST 57
#define DATAGRID_Sensor_Type_CONST 58
#define DATAGRID_Devices_Of_Category_CONST 59
#define DATAGRID_Floorplan_Telecom_Streams_CONST 60
#define DATAGRID_Recent_Calls_CONST 61
#define DATAGRID_Speed_Dial_CONST 62
#define DATAGRID_Media_Browser_CONST 63
#define DATAGRID_TVWhatDelays_CONST 64
#define DATAGRID_User_VoiceMail_CONST 65
#define DATAGRID_Confirm_On_Off_Codes_CONST 66
#define DATAGRID_Media_Type_CONST 67
#define DATAGRID_Select_Available_Inputs_CONST 68
#define DATAGRID_Media_Connector_Type_CONST 69
#define DATAGRID_Confirm_Inputs_Codes_CONST 70
#define DATAGRID_Select_Available_DSPModes_CONST 71
#define DATAGRID_Confirm_Inputs_Order_CONST 72
#define DATAGRID_Confirm_DSPModes_Order_CONST 73
#define DATAGRID_IR_Codes_Sets_CONST 74
#define DATAGRID_Learn_IR_Codes_CONST 75
#define DATAGRID_IR_Codes_Variations_CONST 76
#define DATAGRID_Device_Templates_By_Categ_CONST 77
#define DATAGRID_IR_Commands_CONST 78
#define DATAGRID_Cities_CONST 79
#define DATAGRID_Installable_Apps_CONST 80
#define DATAGRID_Storage_Devices_CONST 82
#define DATAGRID_Media_Attributes_For_File_CONST 83
#define DATAGRID_Provider_Source_CONST 84
#define DATAGRID_Capture_Card_Ports_CONST 85
#define DATAGRID_Discs_CONST 86
#define DATAGRID_JukeBoxes_CONST 87
#define DATAGRID_HardDiscs_CONST 88
#define DATAGRID_CompactFlashes_CONST 89
#define DATAGRID_NetworkStorage_CONST 90
#define DATAGRID_Capture_Card_Port_Devices_CONST 91
#define DATAGRID_Devices_Needing_Providers_CONST 92
#define DATAGRID_Providers_For_Device_CONST 93
#define DATAGRID_Floorplan_Devices_CONST 94
#define DATAGRID_Thumbnailable_Attributes_CONST 95
#define DATAGRID_Jukebox_Drives_CONST 96
#define DATAGRID_Jukebox_Slots_CONST 97
#define DATAGRID_CD_Tracks_CONST 98
#define DATAGRID_Active_Channels_CONST 99
#define DATAGRID_Active_Users_On_Channel_CONST 100

#define DATAGRID_TABLE "DataGrid"
#define DATAGRID_PK_DATAGRID_FIELD "PK_DataGrid"
#define DATAGRID_PK_DATAGRID_TABLE_FIELD "DataGrid.PK_DataGrid"
#define DATAGRID_DESCRIPTION_FIELD "Description"
#define DATAGRID_DESCRIPTION_TABLE_FIELD "DataGrid.Description"
#define DATAGRID_DEFINE_FIELD "Define"
#define DATAGRID_DEFINE_TABLE_FIELD "DataGrid.Define"
#define DATAGRID_COMMENTS_FIELD "Comments"
#define DATAGRID_COMMENTS_TABLE_FIELD "DataGrid.Comments"
#define DATAGRID_PSC_ID_FIELD "psc_id"
#define DATAGRID_PSC_ID_TABLE_FIELD "DataGrid.psc_id"
#define DATAGRID_PSC_BATCH_FIELD "psc_batch"
#define DATAGRID_PSC_BATCH_TABLE_FIELD "DataGrid.psc_batch"
#define DATAGRID_PSC_USER_FIELD "psc_user"
#define DATAGRID_PSC_USER_TABLE_FIELD "DataGrid.psc_user"
#define DATAGRID_PSC_FROZEN_FIELD "psc_frozen"
#define DATAGRID_PSC_FROZEN_TABLE_FIELD "DataGrid.psc_frozen"
#define DATAGRID_PSC_MOD_FIELD "psc_mod"
#define DATAGRID_PSC_MOD_TABLE_FIELD "DataGrid.psc_mod"
#define DATAGRID_PSC_RESTRICT_FIELD "psc_restrict"
#define DATAGRID_PSC_RESTRICT_TABLE_FIELD "DataGrid.psc_restrict"


#endif

