#ifndef __Define_Orbiter_Variable_pschmask_H__
#define __Define_Orbiter_Variable_pschmask_H__


#define ORBITER_VARIABLE_PSCHMASK_TABLE "Orbiter_Variable_pschmask"
#define ORBITER_VARIABLE_PSCHMASK_FK_ORBITER_FIELD "FK_Orbiter"
#define ORBITER_VARIABLE_PSCHMASK_FK_ORBITER_TABLE_FIELD "Orbiter_Variable_pschmask.FK_Orbiter"
#define ORBITER_VARIABLE_PSCHMASK_FK_VARIABLE_FIELD "FK_Variable"
#define ORBITER_VARIABLE_PSCHMASK_FK_VARIABLE_TABLE_FIELD "Orbiter_Variable_pschmask.FK_Variable"
#define ORBITER_VARIABLE_PSCHMASK_VALUE_FIELD "Value"
#define ORBITER_VARIABLE_PSCHMASK_VALUE_TABLE_FIELD "Orbiter_Variable_pschmask.Value"
#define ORBITER_VARIABLE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define ORBITER_VARIABLE_PSCHMASK_PSC_ID_TABLE_FIELD "Orbiter_Variable_pschmask.psc_id"
#define ORBITER_VARIABLE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define ORBITER_VARIABLE_PSCHMASK_PSC_BATCH_TABLE_FIELD "Orbiter_Variable_pschmask.psc_batch"
#define ORBITER_VARIABLE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define ORBITER_VARIABLE_PSCHMASK_PSC_USER_TABLE_FIELD "Orbiter_Variable_pschmask.psc_user"
#define ORBITER_VARIABLE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define ORBITER_VARIABLE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Orbiter_Variable_pschmask.psc_frozen"
#define ORBITER_VARIABLE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define ORBITER_VARIABLE_PSCHMASK_PSC_MOD_TABLE_FIELD "Orbiter_Variable_pschmask.psc_mod"
#define ORBITER_VARIABLE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define ORBITER_VARIABLE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Orbiter_Variable_pschmask.psc_restrict"


#endif

