#ifndef __Define_Button_H__
#define __Define_Button_H__

#define BUTTON_Up_Arrow_CONST 1
#define BUTTON_Down_Arrow_CONST 2
#define BUTTON_Left_Arrow_CONST 3
#define BUTTON_Right_Arrow_CONST 4
#define BUTTON_Enter_CONST 5
#define BUTTON_Scroll_Up_CONST 6
#define BUTTON_Scroll_Down_CONST 7
#define BUTTON_Scroll_Enter_CONST 8
#define BUTTON_F1_CONST 10
#define BUTTON_F2_CONST 11
#define BUTTON_F3_CONST 12
#define BUTTON_F4_CONST 13
#define BUTTON_F5_CONST 14
#define BUTTON_Record_CONST 15
#define BUTTON_1_CONST 16
#define BUTTON_2_CONST 17
#define BUTTON_3_CONST 18
#define BUTTON_4_CONST 19
#define BUTTON_5_CONST 20
#define BUTTON_6_CONST 21
#define BUTTON_7_CONST 22
#define BUTTON_8_CONST 23
#define BUTTON_9_CONST 24
#define BUTTON_0_CONST 25
#define BUTTON_Phone_C_CONST 26
#define BUTTON_Phone_Pencil_CONST 27
#define BUTTON_Phone_Talk_CONST 28
#define BUTTON_Phone_End_CONST 29
#define BUTTON_Phone_Soft_left_CONST 30
#define BUTTON_Phone_Soft_right_CONST 31
#define BUTTON_Asterisk_CONST 32
#define BUTTON_Pound_CONST 33
#define BUTTON_Rept_1_CONST 89
#define BUTTON_Rept_2_CONST 90
#define BUTTON_Rept_3_CONST 91
#define BUTTON_Rept_4_CONST 92
#define BUTTON_Rept_5_CONST 93
#define BUTTON_Rept_6_CONST 94
#define BUTTON_Rept_7_CONST 95
#define BUTTON_Rept_8_CONST 96
#define BUTTON_Rept_9_CONST 97
#define BUTTON_Rept_0_CONST 98
#define BUTTON_Rept_Phone_C_CONST 99
#define BUTTON_Rept_Phone_Pencil_CONST 100
#define BUTTON_Rept_Phone_Talk_CONST 101
#define BUTTON_Rept_Phone_End_CONST 102
#define BUTTON_Rept_Phone_Soft_left_CONST 103
#define BUTTON_Rept_Phone_Soft_right_CONST 104
#define BUTTON_Rept_Asterisk_CONST 105
#define BUTTON_Rept_Pound_CONST 106
#define BUTTON_Any_key_CONST 107
#define BUTTON_Shift_Up_Arrow_CONST 108
#define BUTTON_Shift_Down_Arrow_CONST 109
#define BUTTON_Shift_Left_Arrow_CONST 110
#define BUTTON_Shift_Right_Arrow_CONST 111
#define BUTTON_Back_CONST 112
#define BUTTON_a_CONST 113
#define BUTTON_b_CONST 114
#define BUTTON_c_CONST 115
#define BUTTON_d_CONST 116
#define BUTTON_e_CONST 117
#define BUTTON_f_CONST 118
#define BUTTON_g_CONST 119
#define BUTTON_h_CONST 120
#define BUTTON_i_CONST 121
#define BUTTON_j_CONST 122
#define BUTTON_k_CONST 123
#define BUTTON_l_CONST 124
#define BUTTON_m_CONST 125
#define BUTTON_n_CONST 126
#define BUTTON_o_CONST 127
#define BUTTON_p_CONST 128
#define BUTTON_q_CONST 129
#define BUTTON_r_CONST 130
#define BUTTON_s_CONST 131
#define BUTTON_t_CONST 132
#define BUTTON_u_CONST 133
#define BUTTON_v_CONST 134
#define BUTTON_w_CONST 135
#define BUTTON_x_CONST 136
#define BUTTON_y_CONST 137
#define BUTTON_z_CONST 138
#define BUTTON_A_CONST 139
#define BUTTON_B_CONST 140
#define BUTTON_C_CONST 141
#define BUTTON_D_CONST 142
#define BUTTON_E_CONST 143
#define BUTTON_F_CONST 144
#define BUTTON_G_CONST 145
#define BUTTON_H_CONST 146
#define BUTTON_I_CONST 147
#define BUTTON_J_CONST 148
#define BUTTON_K_CONST 149
#define BUTTON_L_CONST 150
#define BUTTON_M_CONST 151
#define BUTTON_N_CONST 152
#define BUTTON_O_CONST 153
#define BUTTON_P_CONST 154
#define BUTTON_Q_CONST 155
#define BUTTON_R_CONST 156
#define BUTTON_S_CONST 157
#define BUTTON_T_CONST 158
#define BUTTON_U_CONST 159
#define BUTTON_V_CONST 160
#define BUTTON_W_CONST 161
#define BUTTON_X_CONST 162
#define BUTTON_Y_CONST 163
#define BUTTON_Z_CONST 164
#define BUTTON_space_CONST 165
#define BUTTON_comma_CONST 166
#define BUTTON_period_CONST 167
#define BUTTON_left_shift_CONST 168
#define BUTTON_right_shift_CONST 169
#define BUTTON_caps_lock_CONST 170
#define BUTTON_both_soft_buttons_CONST 173
#define BUTTON_Terminate_Text_CONST 175
#define BUTTON_F6_CONST 176
#define BUTTON_F7_CONST 177
#define BUTTON_F8_CONST 178
#define BUTTON_F9_CONST 179
#define BUTTON_F10_CONST 180

#define BUTTON_TABLE "Button"
#define BUTTON_PK_BUTTON_FIELD "PK_Button"
#define BUTTON_PK_BUTTON_TABLE_FIELD "Button.PK_Button"
#define BUTTON_DESCRIPTION_FIELD "Description"
#define BUTTON_DESCRIPTION_TABLE_FIELD "Button.Description"
#define BUTTON_DEFINE_FIELD "Define"
#define BUTTON_DEFINE_TABLE_FIELD "Button.Define"
#define BUTTON_PSC_ID_FIELD "psc_id"
#define BUTTON_PSC_ID_TABLE_FIELD "Button.psc_id"
#define BUTTON_PSC_BATCH_FIELD "psc_batch"
#define BUTTON_PSC_BATCH_TABLE_FIELD "Button.psc_batch"
#define BUTTON_PSC_USER_FIELD "psc_user"
#define BUTTON_PSC_USER_TABLE_FIELD "Button.psc_user"
#define BUTTON_PSC_FROZEN_FIELD "psc_frozen"
#define BUTTON_PSC_FROZEN_TABLE_FIELD "Button.psc_frozen"
#define BUTTON_PSC_MOD_FIELD "psc_mod"
#define BUTTON_PSC_MOD_TABLE_FIELD "Button.psc_mod"
#define BUTTON_PSC_RESTRICT_FIELD "psc_restrict"
#define BUTTON_PSC_RESTRICT_TABLE_FIELD "Button.psc_restrict"


#endif

