#ifndef __Define_CriteriaList_pschist_H__
#define __Define_CriteriaList_pschist_H__


#define CRITERIALIST_PSCHIST_TABLE "CriteriaList_pschist"
#define CRITERIALIST_PSCHIST_PK_CRITERIALIST_FIELD "PK_CriteriaList"
#define CRITERIALIST_PSCHIST_PK_CRITERIALIST_TABLE_FIELD "CriteriaList_pschist.PK_CriteriaList"
#define CRITERIALIST_PSCHIST_DESCRIPTION_FIELD "Description"
#define CRITERIALIST_PSCHIST_DESCRIPTION_TABLE_FIELD "CriteriaList_pschist.Description"
#define CRITERIALIST_PSCHIST_DEFINE_FIELD "Define"
#define CRITERIALIST_PSCHIST_DEFINE_TABLE_FIELD "CriteriaList_pschist.Define"
#define CRITERIALIST_PSCHIST_PSC_ID_FIELD "psc_id"
#define CRITERIALIST_PSCHIST_PSC_ID_TABLE_FIELD "CriteriaList_pschist.psc_id"
#define CRITERIALIST_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define CRITERIALIST_PSCHIST_PSC_BATCH_TABLE_FIELD "CriteriaList_pschist.psc_batch"
#define CRITERIALIST_PSCHIST_PSC_USER_FIELD "psc_user"
#define CRITERIALIST_PSCHIST_PSC_USER_TABLE_FIELD "CriteriaList_pschist.psc_user"
#define CRITERIALIST_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define CRITERIALIST_PSCHIST_PSC_FROZEN_TABLE_FIELD "CriteriaList_pschist.psc_frozen"
#define CRITERIALIST_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define CRITERIALIST_PSCHIST_PSC_MOD_TABLE_FIELD "CriteriaList_pschist.psc_mod"
#define CRITERIALIST_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define CRITERIALIST_PSCHIST_PSC_TOC_TABLE_FIELD "CriteriaList_pschist.psc_toc"
#define CRITERIALIST_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define CRITERIALIST_PSCHIST_PSC_RESTRICT_TABLE_FIELD "CriteriaList_pschist.psc_restrict"


#endif

