#ifndef __Define_Package_Compat_pschist_H__
#define __Define_Package_Compat_pschist_H__


#define PACKAGE_COMPAT_PSCHIST_TABLE "Package_Compat_pschist"
#define PACKAGE_COMPAT_PSCHIST_PK_PACKAGE_COMPAT_FIELD "PK_Package_Compat"
#define PACKAGE_COMPAT_PSCHIST_PK_PACKAGE_COMPAT_TABLE_FIELD "Package_Compat_pschist.PK_Package_Compat"
#define PACKAGE_COMPAT_PSCHIST_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_COMPAT_PSCHIST_FK_PACKAGE_TABLE_FIELD "Package_Compat_pschist.FK_Package"
#define PACKAGE_COMPAT_PSCHIST_FK_DISTRO_FIELD "FK_Distro"
#define PACKAGE_COMPAT_PSCHIST_FK_DISTRO_TABLE_FIELD "Package_Compat_pschist.FK_Distro"
#define PACKAGE_COMPAT_PSCHIST_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define PACKAGE_COMPAT_PSCHIST_FK_OPERATINGSYSTEM_TABLE_FIELD "Package_Compat_pschist.FK_OperatingSystem"
#define PACKAGE_COMPAT_PSCHIST_PSC_ID_FIELD "psc_id"
#define PACKAGE_COMPAT_PSCHIST_PSC_ID_TABLE_FIELD "Package_Compat_pschist.psc_id"
#define PACKAGE_COMPAT_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_COMPAT_PSCHIST_PSC_BATCH_TABLE_FIELD "Package_Compat_pschist.psc_batch"
#define PACKAGE_COMPAT_PSCHIST_PSC_USER_FIELD "psc_user"
#define PACKAGE_COMPAT_PSCHIST_PSC_USER_TABLE_FIELD "Package_Compat_pschist.psc_user"
#define PACKAGE_COMPAT_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_COMPAT_PSCHIST_PSC_FROZEN_TABLE_FIELD "Package_Compat_pschist.psc_frozen"
#define PACKAGE_COMPAT_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_COMPAT_PSCHIST_PSC_MOD_TABLE_FIELD "Package_Compat_pschist.psc_mod"
#define PACKAGE_COMPAT_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PACKAGE_COMPAT_PSCHIST_PSC_TOC_TABLE_FIELD "Package_Compat_pschist.psc_toc"
#define PACKAGE_COMPAT_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_COMPAT_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Package_Compat_pschist.psc_restrict"


#endif

