#ifndef __Define_psc_website_batdet_H__
#define __Define_psc_website_batdet_H__


#define PSC_WEBSITE_BATDET_TABLE "psc_website_batdet"
#define PSC_WEBSITE_BATDET_PK_PSC_WEBSITE_BATDET_FIELD "PK_psc_website_batdet"
#define PSC_WEBSITE_BATDET_PK_PSC_WEBSITE_BATDET_TABLE_FIELD "psc_website_batdet.PK_psc_website_batdet"
#define PSC_WEBSITE_BATDET_FK_PSC_WEBSITE_BATHDR_FIELD "FK_psc_website_bathdr"
#define PSC_WEBSITE_BATDET_FK_PSC_WEBSITE_BATHDR_TABLE_FIELD "psc_website_batdet.FK_psc_website_bathdr"
#define PSC_WEBSITE_BATDET_TABLENAME_FIELD "Tablename"
#define PSC_WEBSITE_BATDET_TABLENAME_TABLE_FIELD "psc_website_batdet.Tablename"
#define PSC_WEBSITE_BATDET_NEW_FIELD "New"
#define PSC_WEBSITE_BATDET_NEW_TABLE_FIELD "psc_website_batdet.New"
#define PSC_WEBSITE_BATDET_DELETED_FIELD "Deleted"
#define PSC_WEBSITE_BATDET_DELETED_TABLE_FIELD "psc_website_batdet.Deleted"
#define PSC_WEBSITE_BATDET_MODIFIED_FIELD "Modified"
#define PSC_WEBSITE_BATDET_MODIFIED_TABLE_FIELD "psc_website_batdet.Modified"
#define PSC_WEBSITE_BATDET_FK_PSC_WEBSITE_BATHDR_ORIG_FIELD "FK_psc_website_bathdr_orig"
#define PSC_WEBSITE_BATDET_FK_PSC_WEBSITE_BATHDR_ORIG_TABLE_FIELD "psc_website_batdet.FK_psc_website_bathdr_orig"
#define PSC_WEBSITE_BATDET_FK_PSC_WEBSITE_BATHDR_AUTH_FIELD "FK_psc_website_bathdr_auth"
#define PSC_WEBSITE_BATDET_FK_PSC_WEBSITE_BATHDR_AUTH_TABLE_FIELD "psc_website_batdet.FK_psc_website_bathdr_auth"
#define PSC_WEBSITE_BATDET_FK_PSC_WEBSITE_BATHDR_UNAUTH_FIELD "FK_psc_website_bathdr_unauth"
#define PSC_WEBSITE_BATDET_FK_PSC_WEBSITE_BATHDR_UNAUTH_TABLE_FIELD "psc_website_batdet.FK_psc_website_bathdr_unauth"


#endif

