#ifndef __Define_Size_pschist_H__
#define __Define_Size_pschist_H__


#define SIZE_PSCHIST_TABLE "Size_pschist"
#define SIZE_PSCHIST_PK_SIZE_FIELD "PK_Size"
#define SIZE_PSCHIST_PK_SIZE_TABLE_FIELD "Size_pschist.PK_Size"
#define SIZE_PSCHIST_DESCRIPTION_FIELD "Description"
#define SIZE_PSCHIST_DESCRIPTION_TABLE_FIELD "Size_pschist.Description"
#define SIZE_PSCHIST_DEFINE_FIELD "Define"
#define SIZE_PSCHIST_DEFINE_TABLE_FIELD "Size_pschist.Define"
#define SIZE_PSCHIST_WIDTH_FIELD "Width"
#define SIZE_PSCHIST_WIDTH_TABLE_FIELD "Size_pschist.Width"
#define SIZE_PSCHIST_HEIGHT_FIELD "Height"
#define SIZE_PSCHIST_HEIGHT_TABLE_FIELD "Size_pschist.Height"
#define SIZE_PSCHIST_SCALEX_FIELD "ScaleX"
#define SIZE_PSCHIST_SCALEX_TABLE_FIELD "Size_pschist.ScaleX"
#define SIZE_PSCHIST_SCALEY_FIELD "ScaleY"
#define SIZE_PSCHIST_SCALEY_TABLE_FIELD "Size_pschist.ScaleY"
#define SIZE_PSCHIST_PRESERVEASPECTRATIO_FIELD "PreserveAspectRatio"
#define SIZE_PSCHIST_PRESERVEASPECTRATIO_TABLE_FIELD "Size_pschist.PreserveAspectRatio"
#define SIZE_PSCHIST_FK_UI_FIELD "FK_UI"
#define SIZE_PSCHIST_FK_UI_TABLE_FIELD "Size_pschist.FK_UI"
#define SIZE_PSCHIST_SCALEMENUBG_FIELD "ScaleMenuBg"
#define SIZE_PSCHIST_SCALEMENUBG_TABLE_FIELD "Size_pschist.ScaleMenuBg"
#define SIZE_PSCHIST_SCALEOTHERGRAPHICS_FIELD "ScaleOtherGraphics"
#define SIZE_PSCHIST_SCALEOTHERGRAPHICS_TABLE_FIELD "Size_pschist.ScaleOtherGraphics"
#define SIZE_PSCHIST_PSC_ID_FIELD "psc_id"
#define SIZE_PSCHIST_PSC_ID_TABLE_FIELD "Size_pschist.psc_id"
#define SIZE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define SIZE_PSCHIST_PSC_BATCH_TABLE_FIELD "Size_pschist.psc_batch"
#define SIZE_PSCHIST_PSC_USER_FIELD "psc_user"
#define SIZE_PSCHIST_PSC_USER_TABLE_FIELD "Size_pschist.psc_user"
#define SIZE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define SIZE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Size_pschist.psc_frozen"
#define SIZE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define SIZE_PSCHIST_PSC_MOD_TABLE_FIELD "Size_pschist.psc_mod"
#define SIZE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define SIZE_PSCHIST_PSC_TOC_TABLE_FIELD "Size_pschist.psc_toc"
#define SIZE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define SIZE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Size_pschist.psc_restrict"


#endif

