#ifndef __Define_RemoteMapping_pschmask_H__
#define __Define_RemoteMapping_pschmask_H__


#define REMOTEMAPPING_PSCHMASK_TABLE "RemoteMapping_pschmask"
#define REMOTEMAPPING_PSCHMASK_PK_REMOTEMAPPING_FIELD "PK_RemoteMapping"
#define REMOTEMAPPING_PSCHMASK_PK_REMOTEMAPPING_TABLE_FIELD "RemoteMapping_pschmask.PK_RemoteMapping"
#define REMOTEMAPPING_PSCHMASK_DESCRIPTION_FIELD "Description"
#define REMOTEMAPPING_PSCHMASK_DESCRIPTION_TABLE_FIELD "RemoteMapping_pschmask.Description"
#define REMOTEMAPPING_PSCHMASK_SCREENTYPE_FIELD "ScreenType"
#define REMOTEMAPPING_PSCHMASK_SCREENTYPE_TABLE_FIELD "RemoteMapping_pschmask.ScreenType"
#define REMOTEMAPPING_PSCHMASK_REMOTELAYOUT_FIELD "RemoteLayout"
#define REMOTEMAPPING_PSCHMASK_REMOTELAYOUT_TABLE_FIELD "RemoteMapping_pschmask.RemoteLayout"
#define REMOTEMAPPING_PSCHMASK_MAPPING_FIELD "Mapping"
#define REMOTEMAPPING_PSCHMASK_MAPPING_TABLE_FIELD "RemoteMapping_pschmask.Mapping"
#define REMOTEMAPPING_PSCHMASK_PSC_ID_FIELD "psc_id"
#define REMOTEMAPPING_PSCHMASK_PSC_ID_TABLE_FIELD "RemoteMapping_pschmask.psc_id"
#define REMOTEMAPPING_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define REMOTEMAPPING_PSCHMASK_PSC_BATCH_TABLE_FIELD "RemoteMapping_pschmask.psc_batch"
#define REMOTEMAPPING_PSCHMASK_PSC_USER_FIELD "psc_user"
#define REMOTEMAPPING_PSCHMASK_PSC_USER_TABLE_FIELD "RemoteMapping_pschmask.psc_user"
#define REMOTEMAPPING_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define REMOTEMAPPING_PSCHMASK_PSC_FROZEN_TABLE_FIELD "RemoteMapping_pschmask.psc_frozen"
#define REMOTEMAPPING_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define REMOTEMAPPING_PSCHMASK_PSC_MOD_TABLE_FIELD "RemoteMapping_pschmask.psc_mod"
#define REMOTEMAPPING_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define REMOTEMAPPING_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "RemoteMapping_pschmask.psc_restrict"


#endif

