#ifndef __Define_CannedEvents_pschmask_H__
#define __Define_CannedEvents_pschmask_H__


#define CANNEDEVENTS_PSCHMASK_TABLE "CannedEvents_pschmask"
#define CANNEDEVENTS_PSCHMASK_PK_CANNEDEVENTS_FIELD "PK_CannedEvents"
#define CANNEDEVENTS_PSCHMASK_PK_CANNEDEVENTS_TABLE_FIELD "CannedEvents_pschmask.PK_CannedEvents"
#define CANNEDEVENTS_PSCHMASK_DESCRIPTION_FIELD "Description"
#define CANNEDEVENTS_PSCHMASK_DESCRIPTION_TABLE_FIELD "CannedEvents_pschmask.Description"
#define CANNEDEVENTS_PSCHMASK_FK_EVENT_FIELD "FK_Event"
#define CANNEDEVENTS_PSCHMASK_FK_EVENT_TABLE_FIELD "CannedEvents_pschmask.FK_Event"
#define CANNEDEVENTS_PSCHMASK_BISAND_FIELD "bIsAnd"
#define CANNEDEVENTS_PSCHMASK_BISAND_TABLE_FIELD "CannedEvents_pschmask.bIsAnd"
#define CANNEDEVENTS_PSCHMASK_BISNOT_FIELD "bIsNot"
#define CANNEDEVENTS_PSCHMASK_BISNOT_TABLE_FIELD "CannedEvents_pschmask.bIsNot"
#define CANNEDEVENTS_PSCHMASK_PSC_ID_FIELD "psc_id"
#define CANNEDEVENTS_PSCHMASK_PSC_ID_TABLE_FIELD "CannedEvents_pschmask.psc_id"
#define CANNEDEVENTS_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define CANNEDEVENTS_PSCHMASK_PSC_BATCH_TABLE_FIELD "CannedEvents_pschmask.psc_batch"
#define CANNEDEVENTS_PSCHMASK_PSC_USER_FIELD "psc_user"
#define CANNEDEVENTS_PSCHMASK_PSC_USER_TABLE_FIELD "CannedEvents_pschmask.psc_user"
#define CANNEDEVENTS_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define CANNEDEVENTS_PSCHMASK_PSC_FROZEN_TABLE_FIELD "CannedEvents_pschmask.psc_frozen"
#define CANNEDEVENTS_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define CANNEDEVENTS_PSCHMASK_PSC_MOD_TABLE_FIELD "CannedEvents_pschmask.psc_mod"
#define CANNEDEVENTS_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define CANNEDEVENTS_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "CannedEvents_pschmask.psc_restrict"


#endif

