#ifndef __Define_Users_pschist_H__
#define __Define_Users_pschist_H__


#define USERS_PSCHIST_TABLE "Users_pschist"
#define USERS_PSCHIST_PK_USERS_FIELD "PK_Users"
#define USERS_PSCHIST_PK_USERS_TABLE_FIELD "Users_pschist.PK_Users"
#define USERS_PSCHIST_USERNAME_FIELD "UserName"
#define USERS_PSCHIST_USERNAME_TABLE_FIELD "Users_pschist.UserName"
#define USERS_PSCHIST_PASSWORD_FIELD "Password"
#define USERS_PSCHIST_PASSWORD_TABLE_FIELD "Users_pschist.Password"
#define USERS_PSCHIST_PINCODE_FIELD "PINCode"
#define USERS_PSCHIST_PINCODE_TABLE_FIELD "Users_pschist.PINCode"
#define USERS_PSCHIST_HASMAILBOX_FIELD "HasMailbox"
#define USERS_PSCHIST_HASMAILBOX_TABLE_FIELD "Users_pschist.HasMailbox"
#define USERS_PSCHIST_ACCESSGENERALMAILBOX_FIELD "AccessGeneralMailbox"
#define USERS_PSCHIST_ACCESSGENERALMAILBOX_TABLE_FIELD "Users_pschist.AccessGeneralMailbox"
#define USERS_PSCHIST_EXTENSION_FIELD "Extension"
#define USERS_PSCHIST_EXTENSION_TABLE_FIELD "Users_pschist.Extension"
#define USERS_PSCHIST_FIRSTNAME_FIELD "FirstName"
#define USERS_PSCHIST_FIRSTNAME_TABLE_FIELD "Users_pschist.FirstName"
#define USERS_PSCHIST_LASTNAME_FIELD "LastName"
#define USERS_PSCHIST_LASTNAME_TABLE_FIELD "Users_pschist.LastName"
#define USERS_PSCHIST_NICKNAME_FIELD "Nickname"
#define USERS_PSCHIST_NICKNAME_TABLE_FIELD "Users_pschist.Nickname"
#define USERS_PSCHIST_EXTENSIONRINGTIMEOUT_FIELD "ExtensionRingTimeout"
#define USERS_PSCHIST_EXTENSIONRINGTIMEOUT_TABLE_FIELD "Users_pschist.ExtensionRingTimeout"
#define USERS_PSCHIST_FORWARDEMAIL_FIELD "ForwardEmail"
#define USERS_PSCHIST_FORWARDEMAIL_TABLE_FIELD "Users_pschist.ForwardEmail"
#define USERS_PSCHIST_FK_LANGUAGE_FIELD "FK_Language"
#define USERS_PSCHIST_FK_LANGUAGE_TABLE_FIELD "Users_pschist.FK_Language"
#define USERS_PSCHIST_FK_INSTALLATION_MAIN_FIELD "FK_Installation_Main"
#define USERS_PSCHIST_FK_INSTALLATION_MAIN_TABLE_FIELD "Users_pschist.FK_Installation_Main"
#define USERS_PSCHIST_HIDEFROMORBITER_FIELD "HideFromOrbiter"
#define USERS_PSCHIST_HIDEFROMORBITER_TABLE_FIELD "Users_pschist.HideFromOrbiter"
#define USERS_PSCHIST_STAFF_FIELD "Staff"
#define USERS_PSCHIST_STAFF_TABLE_FIELD "Users_pschist.Staff"
#define USERS_PSCHIST_PASSWORD_UNIX_FIELD "Password_Unix"
#define USERS_PSCHIST_PASSWORD_UNIX_TABLE_FIELD "Users_pschist.Password_Unix"
#define USERS_PSCHIST_PASSWORD_SAMBA_FIELD "Password_Samba"
#define USERS_PSCHIST_PASSWORD_SAMBA_TABLE_FIELD "Users_pschist.Password_Samba"
#define USERS_PSCHIST_FK_USERMODE_FIELD "FK_UserMode"
#define USERS_PSCHIST_FK_USERMODE_TABLE_FIELD "Users_pschist.FK_UserMode"
#define USERS_PSCHIST_EK_DEALER_FIELD "EK_Dealer"
#define USERS_PSCHIST_EK_DEALER_TABLE_FIELD "Users_pschist.EK_Dealer"
#define USERS_PSCHIST_EK_MANUFACTURER_FIELD "EK_Manufacturer"
#define USERS_PSCHIST_EK_MANUFACTURER_TABLE_FIELD "Users_pschist.EK_Manufacturer"
#define USERS_PSCHIST_REQUIREPINTOSELECT_FIELD "RequirePinToSelect"
#define USERS_PSCHIST_REQUIREPINTOSELECT_TABLE_FIELD "Users_pschist.RequirePinToSelect"
#define USERS_PSCHIST_PSC_ID_FIELD "psc_id"
#define USERS_PSCHIST_PSC_ID_TABLE_FIELD "Users_pschist.psc_id"
#define USERS_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define USERS_PSCHIST_PSC_BATCH_TABLE_FIELD "Users_pschist.psc_batch"
#define USERS_PSCHIST_PSC_USER_FIELD "psc_user"
#define USERS_PSCHIST_PSC_USER_TABLE_FIELD "Users_pschist.psc_user"
#define USERS_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define USERS_PSCHIST_PSC_FROZEN_TABLE_FIELD "Users_pschist.psc_frozen"
#define USERS_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define USERS_PSCHIST_PSC_MOD_TABLE_FIELD "Users_pschist.psc_mod"
#define USERS_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define USERS_PSCHIST_PSC_TOC_TABLE_FIELD "Users_pschist.psc_toc"
#define USERS_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define USERS_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Users_pschist.psc_restrict"


#endif

