#ifndef __Define_PhoneLineType_pschist_H__
#define __Define_PhoneLineType_pschist_H__


#define PHONELINETYPE_PSCHIST_TABLE "PhoneLineType_pschist"
#define PHONELINETYPE_PSCHIST_PK_PHONELINETYPE_FIELD "PK_PhoneLineType"
#define PHONELINETYPE_PSCHIST_PK_PHONELINETYPE_TABLE_FIELD "PhoneLineType_pschist.PK_PhoneLineType"
#define PHONELINETYPE_PSCHIST_DESCRIPTION_FIELD "Description"
#define PHONELINETYPE_PSCHIST_DESCRIPTION_TABLE_FIELD "PhoneLineType_pschist.Description"
#define PHONELINETYPE_PSCHIST_DEFINE_FIELD "Define"
#define PHONELINETYPE_PSCHIST_DEFINE_TABLE_FIELD "PhoneLineType_pschist.Define"
#define PHONELINETYPE_PSCHIST_PSC_ID_FIELD "psc_id"
#define PHONELINETYPE_PSCHIST_PSC_ID_TABLE_FIELD "PhoneLineType_pschist.psc_id"
#define PHONELINETYPE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PHONELINETYPE_PSCHIST_PSC_BATCH_TABLE_FIELD "PhoneLineType_pschist.psc_batch"
#define PHONELINETYPE_PSCHIST_PSC_USER_FIELD "psc_user"
#define PHONELINETYPE_PSCHIST_PSC_USER_TABLE_FIELD "PhoneLineType_pschist.psc_user"
#define PHONELINETYPE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PHONELINETYPE_PSCHIST_PSC_FROZEN_TABLE_FIELD "PhoneLineType_pschist.psc_frozen"
#define PHONELINETYPE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PHONELINETYPE_PSCHIST_PSC_MOD_TABLE_FIELD "PhoneLineType_pschist.psc_mod"
#define PHONELINETYPE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PHONELINETYPE_PSCHIST_PSC_TOC_TABLE_FIELD "PhoneLineType_pschist.psc_toc"
#define PHONELINETYPE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PHONELINETYPE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "PhoneLineType_pschist.psc_restrict"


#endif

