#ifndef __Define_CommandCategory_pschmask_H__
#define __Define_CommandCategory_pschmask_H__


#define COMMANDCATEGORY_PSCHMASK_TABLE "CommandCategory_pschmask"
#define COMMANDCATEGORY_PSCHMASK_PK_COMMANDCATEGORY_FIELD "PK_CommandCategory"
#define COMMANDCATEGORY_PSCHMASK_PK_COMMANDCATEGORY_TABLE_FIELD "CommandCategory_pschmask.PK_CommandCategory"
#define COMMANDCATEGORY_PSCHMASK_FK_COMMANDCATEGORY_PARENT_FIELD "FK_CommandCategory_Parent"
#define COMMANDCATEGORY_PSCHMASK_FK_COMMANDCATEGORY_PARENT_TABLE_FIELD "CommandCategory_pschmask.FK_CommandCategory_Parent"
#define COMMANDCATEGORY_PSCHMASK_DESCRIPTION_FIELD "Description"
#define COMMANDCATEGORY_PSCHMASK_DESCRIPTION_TABLE_FIELD "CommandCategory_pschmask.Description"
#define COMMANDCATEGORY_PSCHMASK_PSC_ID_FIELD "psc_id"
#define COMMANDCATEGORY_PSCHMASK_PSC_ID_TABLE_FIELD "CommandCategory_pschmask.psc_id"
#define COMMANDCATEGORY_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define COMMANDCATEGORY_PSCHMASK_PSC_BATCH_TABLE_FIELD "CommandCategory_pschmask.psc_batch"
#define COMMANDCATEGORY_PSCHMASK_PSC_USER_FIELD "psc_user"
#define COMMANDCATEGORY_PSCHMASK_PSC_USER_TABLE_FIELD "CommandCategory_pschmask.psc_user"
#define COMMANDCATEGORY_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define COMMANDCATEGORY_PSCHMASK_PSC_FROZEN_TABLE_FIELD "CommandCategory_pschmask.psc_frozen"
#define COMMANDCATEGORY_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define COMMANDCATEGORY_PSCHMASK_PSC_MOD_TABLE_FIELD "CommandCategory_pschmask.psc_mod"
#define COMMANDCATEGORY_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMANDCATEGORY_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "CommandCategory_pschmask.psc_restrict"


#endif

