#ifndef __Define_InstallWizard_pschist_H__
#define __Define_InstallWizard_pschist_H__


#define INSTALLWIZARD_PSCHIST_TABLE "InstallWizard_pschist"
#define INSTALLWIZARD_PSCHIST_PK_INSTALLWIZARD_FIELD "PK_InstallWizard"
#define INSTALLWIZARD_PSCHIST_PK_INSTALLWIZARD_TABLE_FIELD "InstallWizard_pschist.PK_InstallWizard"
#define INSTALLWIZARD_PSCHIST_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define INSTALLWIZARD_PSCHIST_FK_DEVICETEMPLATE_TABLE_FIELD "InstallWizard_pschist.FK_DeviceTemplate"
#define INSTALLWIZARD_PSCHIST_STEP_FIELD "Step"
#define INSTALLWIZARD_PSCHIST_STEP_TABLE_FIELD "InstallWizard_pschist.Step"
#define INSTALLWIZARD_PSCHIST_DEFAULT_FIELD "Default"
#define INSTALLWIZARD_PSCHIST_DEFAULT_TABLE_FIELD "InstallWizard_pschist.Default"
#define INSTALLWIZARD_PSCHIST_COMMENTS_FIELD "Comments"
#define INSTALLWIZARD_PSCHIST_COMMENTS_TABLE_FIELD "InstallWizard_pschist.Comments"
#define INSTALLWIZARD_PSCHIST_PSC_ID_FIELD "psc_id"
#define INSTALLWIZARD_PSCHIST_PSC_ID_TABLE_FIELD "InstallWizard_pschist.psc_id"
#define INSTALLWIZARD_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define INSTALLWIZARD_PSCHIST_PSC_BATCH_TABLE_FIELD "InstallWizard_pschist.psc_batch"
#define INSTALLWIZARD_PSCHIST_PSC_USER_FIELD "psc_user"
#define INSTALLWIZARD_PSCHIST_PSC_USER_TABLE_FIELD "InstallWizard_pschist.psc_user"
#define INSTALLWIZARD_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define INSTALLWIZARD_PSCHIST_PSC_FROZEN_TABLE_FIELD "InstallWizard_pschist.psc_frozen"
#define INSTALLWIZARD_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define INSTALLWIZARD_PSCHIST_PSC_MOD_TABLE_FIELD "InstallWizard_pschist.psc_mod"
#define INSTALLWIZARD_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define INSTALLWIZARD_PSCHIST_PSC_TOC_TABLE_FIELD "InstallWizard_pschist.psc_toc"
#define INSTALLWIZARD_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define INSTALLWIZARD_PSCHIST_PSC_RESTRICT_TABLE_FIELD "InstallWizard_pschist.psc_restrict"


#endif

