#ifndef __Define_FloorplanType_pschmask_H__
#define __Define_FloorplanType_pschmask_H__


#define FLOORPLANTYPE_PSCHMASK_TABLE "FloorplanType_pschmask"
#define FLOORPLANTYPE_PSCHMASK_PK_FLOORPLANTYPE_FIELD "PK_FloorplanType"
#define FLOORPLANTYPE_PSCHMASK_PK_FLOORPLANTYPE_TABLE_FIELD "FloorplanType_pschmask.PK_FloorplanType"
#define FLOORPLANTYPE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define FLOORPLANTYPE_PSCHMASK_DESCRIPTION_TABLE_FIELD "FloorplanType_pschmask.Description"
#define FLOORPLANTYPE_PSCHMASK_DEFINE_FIELD "Define"
#define FLOORPLANTYPE_PSCHMASK_DEFINE_TABLE_FIELD "FloorplanType_pschmask.Define"
#define FLOORPLANTYPE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define FLOORPLANTYPE_PSCHMASK_PSC_ID_TABLE_FIELD "FloorplanType_pschmask.psc_id"
#define FLOORPLANTYPE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define FLOORPLANTYPE_PSCHMASK_PSC_BATCH_TABLE_FIELD "FloorplanType_pschmask.psc_batch"
#define FLOORPLANTYPE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define FLOORPLANTYPE_PSCHMASK_PSC_USER_TABLE_FIELD "FloorplanType_pschmask.psc_user"
#define FLOORPLANTYPE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define FLOORPLANTYPE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "FloorplanType_pschmask.psc_frozen"
#define FLOORPLANTYPE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define FLOORPLANTYPE_PSCHMASK_PSC_MOD_TABLE_FIELD "FloorplanType_pschmask.psc_mod"
#define FLOORPLANTYPE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define FLOORPLANTYPE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "FloorplanType_pschmask.psc_restrict"


#endif

