#ifndef __Define_CommandGroup_D_pschist_H__
#define __Define_CommandGroup_D_pschist_H__


#define COMMANDGROUP_D_PSCHIST_TABLE "CommandGroup_D_pschist"
#define COMMANDGROUP_D_PSCHIST_PK_COMMANDGROUP_D_FIELD "PK_CommandGroup_D"
#define COMMANDGROUP_D_PSCHIST_PK_COMMANDGROUP_D_TABLE_FIELD "CommandGroup_D_pschist.PK_CommandGroup_D"
#define COMMANDGROUP_D_PSCHIST_FK_CRITERIA_ORBITER_FIELD "FK_Criteria_Orbiter"
#define COMMANDGROUP_D_PSCHIST_FK_CRITERIA_ORBITER_TABLE_FIELD "CommandGroup_D_pschist.FK_Criteria_Orbiter"
#define COMMANDGROUP_D_PSCHIST_PSC_ID_FIELD "psc_id"
#define COMMANDGROUP_D_PSCHIST_PSC_ID_TABLE_FIELD "CommandGroup_D_pschist.psc_id"
#define COMMANDGROUP_D_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define COMMANDGROUP_D_PSCHIST_PSC_BATCH_TABLE_FIELD "CommandGroup_D_pschist.psc_batch"
#define COMMANDGROUP_D_PSCHIST_PSC_USER_FIELD "psc_user"
#define COMMANDGROUP_D_PSCHIST_PSC_USER_TABLE_FIELD "CommandGroup_D_pschist.psc_user"
#define COMMANDGROUP_D_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define COMMANDGROUP_D_PSCHIST_PSC_FROZEN_TABLE_FIELD "CommandGroup_D_pschist.psc_frozen"
#define COMMANDGROUP_D_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define COMMANDGROUP_D_PSCHIST_PSC_MOD_TABLE_FIELD "CommandGroup_D_pschist.psc_mod"
#define COMMANDGROUP_D_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define COMMANDGROUP_D_PSCHIST_PSC_TOC_TABLE_FIELD "CommandGroup_D_pschist.psc_toc"
#define COMMANDGROUP_D_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMANDGROUP_D_PSCHIST_PSC_RESTRICT_TABLE_FIELD "CommandGroup_D_pschist.psc_restrict"


#endif

