#ifndef __Define_Licensing_pschist_H__
#define __Define_Licensing_pschist_H__


#define LICENSING_PSCHIST_TABLE "Licensing_pschist"
#define LICENSING_PSCHIST_PK_LICENSING_FIELD "PK_Licensing"
#define LICENSING_PSCHIST_PK_LICENSING_TABLE_FIELD "Licensing_pschist.PK_Licensing"
#define LICENSING_PSCHIST_DESCRIPTION_FIELD "Description"
#define LICENSING_PSCHIST_DESCRIPTION_TABLE_FIELD "Licensing_pschist.Description"
#define LICENSING_PSCHIST_REQUIRESPAYMENT_FIELD "RequiresPayment"
#define LICENSING_PSCHIST_REQUIRESPAYMENT_TABLE_FIELD "Licensing_pschist.RequiresPayment"
#define LICENSING_PSCHIST_RECOMMENDSPAYMENT_FIELD "RecommendsPayment"
#define LICENSING_PSCHIST_RECOMMENDSPAYMENT_TABLE_FIELD "Licensing_pschist.RecommendsPayment"
#define LICENSING_PSCHIST_FREETRIAL_FIELD "FreeTrial"
#define LICENSING_PSCHIST_FREETRIAL_TABLE_FIELD "Licensing_pschist.FreeTrial"
#define LICENSING_PSCHIST_PSC_ID_FIELD "psc_id"
#define LICENSING_PSCHIST_PSC_ID_TABLE_FIELD "Licensing_pschist.psc_id"
#define LICENSING_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define LICENSING_PSCHIST_PSC_BATCH_TABLE_FIELD "Licensing_pschist.psc_batch"
#define LICENSING_PSCHIST_PSC_USER_FIELD "psc_user"
#define LICENSING_PSCHIST_PSC_USER_TABLE_FIELD "Licensing_pschist.psc_user"
#define LICENSING_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define LICENSING_PSCHIST_PSC_FROZEN_TABLE_FIELD "Licensing_pschist.psc_frozen"
#define LICENSING_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define LICENSING_PSCHIST_PSC_MOD_TABLE_FIELD "Licensing_pschist.psc_mod"
#define LICENSING_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define LICENSING_PSCHIST_PSC_TOC_TABLE_FIELD "Licensing_pschist.psc_toc"
#define LICENSING_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define LICENSING_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Licensing_pschist.psc_restrict"


#endif

