#ifndef __Define_Device_Command_pschmask_H__
#define __Define_Device_Command_pschmask_H__


#define DEVICE_COMMAND_PSCHMASK_TABLE "Device_Command_pschmask"
#define DEVICE_COMMAND_PSCHMASK_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_COMMAND_PSCHMASK_FK_DEVICE_TABLE_FIELD "Device_Command_pschmask.FK_Device"
#define DEVICE_COMMAND_PSCHMASK_FK_COMMAND_FIELD "FK_Command"
#define DEVICE_COMMAND_PSCHMASK_FK_COMMAND_TABLE_FIELD "Device_Command_pschmask.FK_Command"
#define DEVICE_COMMAND_PSCHMASK_SORT_FIELD "Sort"
#define DEVICE_COMMAND_PSCHMASK_SORT_TABLE_FIELD "Device_Command_pschmask.Sort"
#define DEVICE_COMMAND_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DEVICE_COMMAND_PSCHMASK_PSC_ID_TABLE_FIELD "Device_Command_pschmask.psc_id"
#define DEVICE_COMMAND_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_COMMAND_PSCHMASK_PSC_BATCH_TABLE_FIELD "Device_Command_pschmask.psc_batch"
#define DEVICE_COMMAND_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DEVICE_COMMAND_PSCHMASK_PSC_USER_TABLE_FIELD "Device_Command_pschmask.psc_user"
#define DEVICE_COMMAND_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_COMMAND_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Device_Command_pschmask.psc_frozen"
#define DEVICE_COMMAND_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DEVICE_COMMAND_PSCHMASK_PSC_MOD_TABLE_FIELD "Device_Command_pschmask.psc_mod"
#define DEVICE_COMMAND_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_COMMAND_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Device_Command_pschmask.psc_restrict"


#endif

