#ifndef __Define_Screen_H__
#define __Define_Screen_H__

#define SCREEN_Main_CONST 1
#define SCREEN_Lights_CONST 2
#define SCREEN_Media_CONST 3
#define SCREEN_Climate_CONST 4
#define SCREEN_Security_CONST 5
#define SCREEN_Telephony_CONST 6
#define SCREEN_Misc_CONST 7
#define SCREEN_UserStatus_CONST 8
#define SCREEN_MakeCallPhonebook_CONST 9
#define SCREEN_MakeCallFavorites_CONST 10
#define SCREEN_MakeCallDialNumber_CONST 11
#define SCREEN_MakeCallPlutoUser_CONST 12
#define SCREEN_SecurityPanel_CONST 13
#define SCREEN_SecurityStatusReport_CONST 14
#define SCREEN_SingleCameraViewOnly_CONST 15
#define SCREEN_Intercom_CONST 16
#define SCREEN_QuadViewCameras_CONST 17
#define SCREEN_VideoCallInProgress_CONST 18
#define SCREEN_FileSave_CONST 19
#define SCREEN_ManagePlaylist_CONST 20
#define SCREEN_MakeCallDevice_CONST 21
#define SCREEN_MakeCallPhonebook2_CONST 22
#define SCREEN_MakeCallIntercom_CONST 23
#define SCREEN_CurrentUser_CONST 24
#define SCREEN_CDTrackCopy_CONST 25
#define SCREEN_CDRemote_CONST 26
#define SCREEN_VoicemailMain_CONST 27
#define SCREEN_TransferAllUsers_CONST 28
#define SCREEN_Sleeping_CONST 29
#define SCREEN_ControllerStatus_CONST 30
#define SCREEN_OtherFolders_CONST 31
#define SCREEN_ConfirmDelete_CONST 32
#define SCREEN_WebURL_CONST 33
#define SCREEN_Browser_CONST 34
#define SCREEN_ModeChanged_CONST 35
#define SCREEN_SensorsNotReady_CONST 36
#define SCREEN_RecordedTVShows_CONST 37
#define SCREEN_DeviceControl_CONST 38
#define SCREEN_Computing_CONST 39
#define SCREEN_OpenFile_CONST 40
#define SCREEN_BrowserConsole_CONST 41
#define SCREEN_FavoritesPDA_CONST 42
#define SCREEN_PCFileTools_CONST 43
#define SCREEN_AdvancedOptions_CONST 44
#define SCREEN_MakingCall_CONST 45
#define SCREEN_MakingLinPhoneBroadcast_CONST 46
#define SCREEN_FileList_Music_Movies_Video_CONST 47
#define SCREEN_PVR_CONST 48
#define SCREEN_DVDRemote_CONST 49
#define SCREEN_DVDMenu_CONST 50
#define SCREEN_MapMedia_CONST 51
#define SCREEN_AdvancedMediaOptions_CONST 52
#define SCREEN_PopupMessage_CONST 53
#define SCREEN_MusicRemote_CONST 54
#define SCREEN_LinPhones_CONST 55
#define SCREEN_Orbiters_CONST 56
#define SCREEN_Phones_CONST 57
#define SCREEN_DVDOptions_CONST 58
#define SCREEN_AnswertoLinPhones_CONST 59
#define SCREEN_UserPinCode_CONST 60
#define SCREEN_PreviewOptions_CONST 61
#define SCREEN_TransferOutside_CONST 62
#define SCREEN_SatelliteCableBox_CONST 63
#define SCREEN_CurrentLocation_CONST 64
#define SCREEN_MediaAttributeSearchInput_CONST 65
#define SCREEN_MediaAttributeSearchResult_CONST 66
#define SCREEN_NewPhoneDetected_CONST 67
#define SCREEN_FirstTime_CONST 68
#define SCREEN_FileList_PlayLists_CONST 69
#define SCREEN_VideosRemote_CONST 70
#define SCREEN_FileList_Pictures_Docs_CONST 71
#define SCREEN_GenericTwoButtonQuestion_CONST 72
#define SCREEN_TryCodes_CONST 73
#define SCREEN_ScreenSaver_CONST 74
#define SCREEN_Pick_Room_For_Device_CONST 75
#define SCREEN_Power_CONST 76
#define SCREEN_GenericDvdRemote_CONST 77
#define SCREEN_ViewPlaylist_CONST 78
#define SCREEN_FileList_withPictures_Mobil_CONST 79
#define SCREEN_GenericDvdMenu_CONST 80
#define SCREEN_ViewAttributes_CONST 81
#define SCREEN_PendingTasks_CONST 82
#define SCREEN_AddAttribute_CONST 83
#define SCREEN_RadioRemote_CONST 84
#define SCREEN_GenericCDRemote_CONST 85
#define SCREEN_FileList_Popup_Container_CONST 86
#define SCREEN_CreateViewBookmarks_CONST 87
#define SCREEN_BrowseBookmarks_CONST 88
#define SCREEN_GenericAppController_CONST 89
#define SCREEN_BookmarksByMediaType_CONST 90
#define SCREEN_MythTvRemote_CONST 92
#define SCREEN_Myth_all_commands_CONST 93
#define SCREEN_Mytv_watching_tv_CONST 94
#define SCREEN_Myth_live_tv_browse_mode_CONST 95
#define SCREEN_Myth_playback_recording_CONST 96
#define SCREEN_GenericKeyboard_CONST 97
#define SCREEN_PingPong_CONST 98
#define SCREEN_TVEPG1_CONST 99
#define SCREEN_TVEPG2_CONST 100
#define SCREEN_TVEPG3_CONST 101
#define SCREEN_ShowInfo_CONST 102
#define SCREEN_CreateViewBookmarksTV_CONST 103
#define SCREEN_WebSites_CONST 105
#define SCREEN_WhatModelMobileOrbiter_CONST 106
#define SCREEN_Filelist_CONST 107
#define SCREEN_DVDmenu_CONST 108
#define SCREEN_Attributes_CONST 109
#define SCREEN_DVDoptions_CONST 110
#define SCREEN_AdvRemote_CONST 111
#define SCREEN_Playlist_CONST 112
#define SCREEN_AudioOptions_CONST 113
#define SCREEN_Subtitles_CONST 114
#define SCREEN_Angles_CONST 115
#define SCREEN_NewPnpDevice_CONST 116
#define SCREEN_VdrRemote_CONST 117
#define SCREEN_CdRemote_CONST 118
#define SCREEN_PowerFile_CONST 119
#define SCREEN_DevCallInProgress_CONST 120
#define SCREEN_DevIncomingCall_CONST 121
#define SCREEN_DevMoveCallsInProgress_CONST 122
#define SCREEN_MapSecurity_CONST 123
#define SCREEN_MapLighting_CONST 124
#define SCREEN_MapClimate_CONST 125
#define SCREEN_MapTelecom_CONST 126
#define SCREEN_NavMode_CONST 127
#define SCREEN_PvrFullScreen_CONST 128
#define SCREEN_Epg_CONST 129
#define SCREEN_Help01_CONST 130
#define SCREEN_Help02_CONST 131
#define SCREEN_Help03_CONST 132
#define SCREEN_SetupMythTv01_CONST 133
#define SCREEN_SetupMythTv02_CONST 134
#define SCREEN_SetupMythTv03_CONST 135
#define SCREEN_SetupMythTv04_CONST 136
#define SCREEN_PvrFullScreenOpt_CONST 137
#define SCREEN_DVDFullScreen_CONST 138
#define SCREEN_DVDFullScreenOpt_CONST 139
#define SCREEN_VideosFullScreen_CONST 140
#define SCREEN_VideosFullScreenOpt_CONST 141
#define SCREEN_GenericAppFullScreen_CONST 142
#define SCREEN_DVDMenuFullScreen_CONST 143
#define SCREEN_DVDMenuFullScreenOpt_CONST 144
#define SCREEN_VlcFullScreen_CONST 145
#define SCREEN_VlcFullScreenOpt_CONST 146
#define SCREEN_popLights_CONST 147
#define SCREEN_popMedia_CONST 148
#define SCREEN_popClimate_CONST 149
#define SCREEN_popTelecom_CONST 150
#define SCREEN_popSecurity_CONST 151
#define SCREEN_popOthers_CONST 152
#define SCREEN_AudiCarSetup_CONST 153
#define SCREEN_AudiMedia_CONST 154
#define SCREEN_AudiComputing_CONST 155
#define SCREEN_AudiRadio_CONST 156
#define SCREEN_AudiTV_CONST 157
#define SCREEN_AudiCD_CONST 158
#define SCREEN_AudiStoredMedia_CONST 159
#define SCREEN_AudiInternet_CONST 160
#define SCREEN_AudiEmail_CONST 161
#define SCREEN_AudiAgenda_CONST 162
#define SCREEN_AudiOther_CONST 163
#define SCREEN_AudiNav_CONST 164
#define SCREEN_AudiInfo_CONST 165
#define SCREEN_AudiCar_CONST 166
#define SCREEN_AudiSetup_CONST 167
#define SCREEN_AudiLighting_CONST 168
#define SCREEN_AudiClimate_CONST 169
#define SCREEN_AudiSecurity_CONST 170
#define SCREEN_AudiTelecom_CONST 171
#define SCREEN_AudiFullScreen_CONST 172
#define SCREEN_AudiVideoRemote_CONST 173
#define SCREEN_AudiAudioRemote_CONST 174
#define SCREEN_VideoWizard_CONST 175
#define SCREEN_DialogCannotPlayMedia_CONST 176
#define SCREEN_DialogRippingInProgress_CONST 178
#define SCREEN_DialogCheckingDrive_CONST 179
#define SCREEN_DialogUnableToSavePlaylist_CONST 180
#define SCREEN_DialogPlaylistSaved_CONST 181
#define SCREEN_DialogUnableToLoadPlaylist_CONST 182
#define SCREEN_DialogRippingError_CONST 183
#define SCREEN_DialogRippingInstructions_CONST 184
#define SCREEN_DialogGenericError_CONST 185
#define SCREEN_DialogCannotBookmark_CONST 186
#define SCREEN_DialogAskToResume_CONST 187
#define SCREEN_DialogGC100Error_CONST 188
#define SCREEN_DialogPhoneInstructions_CONST 189
#define SCREEN_DialogSendFileToPhoneFailed_CONST 190
#define SCREEN_AudiHome_CONST 191
#define SCREEN_RoomsWizard_CONST 192
#define SCREEN_UsersWizard_CONST 193
#define SCREEN_CountryWizard_CONST 194
#define SCREEN_TV_Manufacturer_CONST 196
#define SCREEN_Receiver_CONST 197
#define SCREEN_LightsSetup_CONST 198
#define SCREEN_AlarmPanel_CONST 199
#define SCREEN_VOIP_Provider_CONST 200
#define SCREEN_AV_Devices_CONST 201
#define SCREEN_NAS_Options_CONST 202
#define SCREEN_Need_Reload_Router_CONST 204
#define SCREEN_Need_Regen_Orbiter_CONST 205
#define SCREEN_Sensors_Viewed_By_Camera_CONST 206
#define SCREEN_mnuPVROSD_CONST 207
#define SCREEN_mnuPVRRecording_CONST 208
#define SCREEN_Demo_Media_CONST 209
#define SCREEN_Download_are_ready_to_install_CONST 210
#define SCREEN_mnuAmbiance_CONST 212
#define SCREEN_TVConfirmInputsToggle_CONST 216
#define SCREEN_mnuPVR_OSD_Full_Screen_CONST 218
#define SCREEN_mnuPVRRecording_Full_Screen_CONST 219
#define SCREEN_CurrentlyActiveRemote_CONST 220
#define SCREEN_mnuLights_CONST 222
#define SCREEN_mnuPlaybackControl_CONST 223
#define SCREEN_mnuSpeedControl_CONST 224
#define SCREEN_mnuVolume_CONST 225
#define SCREEN_Media_Tracks_CONST 230
#define SCREEN_Which_Wizard_CONST 231
#define SCREEN_This_Room_CONST 232
#define SCREEN_NAS_Options_when_Mounting_device_CONST 234
#define SCREEN_New_Pnp_Device_One_Possibility_CONST 235
#define SCREEN_Wizard_Done_CONST 236
#define SCREEN_House_Setup_Popup_Message_CONST 237
#define SCREEN_Media_Player_Setup_Popup_Message_CONST 238
#define SCREEN_Add_Software_CONST 239
#define SCREEN_Choose_Folder_CONST 240
#define SCREEN_Choose_Drive_CONST 241
#define SCREEN_TV_Channels_CONST 242
#define SCREEN_CD_Full_Screen_OSD_CONST 243
#define SCREEN_Music_Full_Screen_OSD_CONST 244
#define SCREEN_Choose_Provider_for_Device_CONST 245
#define SCREEN_Get_Username_Password_For_Devices_CONST 246
#define SCREEN_Get_Capture_Card_Port_CONST 247
#define SCREEN_Floorplan_CONST 248
#define SCREEN_Halt_System_CONST 249
#define SCREEN_Floorplan_Editor_CONST 250
#define SCREEN_Final_House_Setup_CONST 251
#define SCREEN_ExternalDeviceFullScreen_CONST 252
#define SCREEN_ExternalDeviceFullScreen_Opts_CONST 253
#define SCREEN_Remote_Assistance_CONST 255
#define SCREEN_Legacy_AV_Speed_Control_CONST 256
#define SCREEN_Thumbnail_CONST 257
#define SCREEN_Scanning_Progress_CONST 258
#define SCREEN_Drive_Overview_CONST 259
#define SCREEN_Jukebox_Manager_CONST 260
#define SCREEN_NAS_Manager_CONST 261
#define SCREEN_AutoConfigure_TV_CONST 262

#define SCREEN_TABLE "Screen"
#define SCREEN_PK_SCREEN_FIELD "PK_Screen"
#define SCREEN_PK_SCREEN_TABLE_FIELD "Screen.PK_Screen"
#define SCREEN_DESCRIPTION_FIELD "Description"
#define SCREEN_DESCRIPTION_TABLE_FIELD "Screen.Description"
#define SCREEN_DEFINE_FIELD "Define"
#define SCREEN_DEFINE_TABLE_FIELD "Screen.Define"
#define SCREEN_COMMENTS_FIELD "Comments"
#define SCREEN_COMMENTS_TABLE_FIELD "Screen.Comments"
#define SCREEN_SPECIALHANDINGRECOMMENDED_FIELD "SpecialHandingRecommended"
#define SCREEN_SPECIALHANDINGRECOMMENDED_TABLE_FIELD "Screen.SpecialHandingRecommended"
#define SCREEN_ALWAYSINCLUDE_FIELD "AlwaysInclude"
#define SCREEN_ALWAYSINCLUDE_TABLE_FIELD "Screen.AlwaysInclude"
#define SCREEN_PRESERVECALLBACKS_FIELD "PreserveCallBacks"
#define SCREEN_PRESERVECALLBACKS_TABLE_FIELD "Screen.PreserveCallBacks"
#define SCREEN_GOBACKTOSCREEN_FIELD "GoBackToScreen"
#define SCREEN_GOBACKTOSCREEN_TABLE_FIELD "Screen.GoBackToScreen"
#define SCREEN_ALLOWINTERRUPTIONS_FIELD "AllowInterruptions"
#define SCREEN_ALLOWINTERRUPTIONS_TABLE_FIELD "Screen.AllowInterruptions"
#define SCREEN_PSC_ID_FIELD "psc_id"
#define SCREEN_PSC_ID_TABLE_FIELD "Screen.psc_id"
#define SCREEN_PSC_BATCH_FIELD "psc_batch"
#define SCREEN_PSC_BATCH_TABLE_FIELD "Screen.psc_batch"
#define SCREEN_PSC_USER_FIELD "psc_user"
#define SCREEN_PSC_USER_TABLE_FIELD "Screen.psc_user"
#define SCREEN_PSC_FROZEN_FIELD "psc_frozen"
#define SCREEN_PSC_FROZEN_TABLE_FIELD "Screen.psc_frozen"
#define SCREEN_PSC_MOD_FIELD "psc_mod"
#define SCREEN_PSC_MOD_TABLE_FIELD "Screen.psc_mod"
#define SCREEN_PSC_RESTRICT_FIELD "psc_restrict"
#define SCREEN_PSC_RESTRICT_TABLE_FIELD "Screen.psc_restrict"


#endif

