#ifndef __Define_ParameterType_pschist_H__
#define __Define_ParameterType_pschist_H__


#define PARAMETERTYPE_PSCHIST_TABLE "ParameterType_pschist"
#define PARAMETERTYPE_PSCHIST_PK_PARAMETERTYPE_FIELD "PK_ParameterType"
#define PARAMETERTYPE_PSCHIST_PK_PARAMETERTYPE_TABLE_FIELD "ParameterType_pschist.PK_ParameterType"
#define PARAMETERTYPE_PSCHIST_DESCRIPTION_FIELD "Description"
#define PARAMETERTYPE_PSCHIST_DESCRIPTION_TABLE_FIELD "ParameterType_pschist.Description"
#define PARAMETERTYPE_PSCHIST_DEFINE_FIELD "Define"
#define PARAMETERTYPE_PSCHIST_DEFINE_TABLE_FIELD "ParameterType_pschist.Define"
#define PARAMETERTYPE_PSCHIST_CPPTYPE_FIELD "CPPType"
#define PARAMETERTYPE_PSCHIST_CPPTYPE_TABLE_FIELD "ParameterType_pschist.CPPType"
#define PARAMETERTYPE_PSCHIST_PSC_ID_FIELD "psc_id"
#define PARAMETERTYPE_PSCHIST_PSC_ID_TABLE_FIELD "ParameterType_pschist.psc_id"
#define PARAMETERTYPE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PARAMETERTYPE_PSCHIST_PSC_BATCH_TABLE_FIELD "ParameterType_pschist.psc_batch"
#define PARAMETERTYPE_PSCHIST_PSC_USER_FIELD "psc_user"
#define PARAMETERTYPE_PSCHIST_PSC_USER_TABLE_FIELD "ParameterType_pschist.psc_user"
#define PARAMETERTYPE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PARAMETERTYPE_PSCHIST_PSC_FROZEN_TABLE_FIELD "ParameterType_pschist.psc_frozen"
#define PARAMETERTYPE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PARAMETERTYPE_PSCHIST_PSC_MOD_TABLE_FIELD "ParameterType_pschist.psc_mod"
#define PARAMETERTYPE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PARAMETERTYPE_PSCHIST_PSC_TOC_TABLE_FIELD "ParameterType_pschist.psc_toc"
#define PARAMETERTYPE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PARAMETERTYPE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "ParameterType_pschist.psc_restrict"


#endif

