#ifndef __Define_ConfigType_Setting_pschmask_H__
#define __Define_ConfigType_Setting_pschmask_H__


#define CONFIGTYPE_SETTING_PSCHMASK_TABLE "ConfigType_Setting_pschmask"
#define CONFIGTYPE_SETTING_PSCHMASK_PK_CONFIGTYPE_SETTING_FIELD "PK_ConfigType_Setting"
#define CONFIGTYPE_SETTING_PSCHMASK_PK_CONFIGTYPE_SETTING_TABLE_FIELD "ConfigType_Setting_pschmask.PK_ConfigType_Setting"
#define CONFIGTYPE_SETTING_PSCHMASK_FK_CONFIGTYPE_FIELD "FK_ConfigType"
#define CONFIGTYPE_SETTING_PSCHMASK_FK_CONFIGTYPE_TABLE_FIELD "ConfigType_Setting_pschmask.FK_ConfigType"
#define CONFIGTYPE_SETTING_PSCHMASK_DESCRIPTION_FIELD "Description"
#define CONFIGTYPE_SETTING_PSCHMASK_DESCRIPTION_TABLE_FIELD "ConfigType_Setting_pschmask.Description"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_ID_FIELD "psc_id"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_ID_TABLE_FIELD "ConfigType_Setting_pschmask.psc_id"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_BATCH_TABLE_FIELD "ConfigType_Setting_pschmask.psc_batch"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_USER_FIELD "psc_user"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_USER_TABLE_FIELD "ConfigType_Setting_pschmask.psc_user"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_FROZEN_TABLE_FIELD "ConfigType_Setting_pschmask.psc_frozen"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_MOD_TABLE_FIELD "ConfigType_Setting_pschmask.psc_mod"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define CONFIGTYPE_SETTING_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "ConfigType_Setting_pschmask.psc_restrict"


#endif

