#ifndef __Define_Device_EntertainArea_pschmask_H__
#define __Define_Device_EntertainArea_pschmask_H__


#define DEVICE_ENTERTAINAREA_PSCHMASK_TABLE "Device_EntertainArea_pschmask"
#define DEVICE_ENTERTAINAREA_PSCHMASK_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_ENTERTAINAREA_PSCHMASK_FK_DEVICE_TABLE_FIELD "Device_EntertainArea_pschmask.FK_Device"
#define DEVICE_ENTERTAINAREA_PSCHMASK_FK_ENTERTAINAREA_FIELD "FK_EntertainArea"
#define DEVICE_ENTERTAINAREA_PSCHMASK_FK_ENTERTAINAREA_TABLE_FIELD "Device_EntertainArea_pschmask.FK_EntertainArea"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_ID_TABLE_FIELD "Device_EntertainArea_pschmask.psc_id"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_BATCH_TABLE_FIELD "Device_EntertainArea_pschmask.psc_batch"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_USER_TABLE_FIELD "Device_EntertainArea_pschmask.psc_user"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Device_EntertainArea_pschmask.psc_frozen"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_MOD_TABLE_FIELD "Device_EntertainArea_pschmask.psc_mod"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_ENTERTAINAREA_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Device_EntertainArea_pschmask.psc_restrict"


#endif

