#ifndef __Define_StabilityStatus_pschist_H__
#define __Define_StabilityStatus_pschist_H__


#define STABILITYSTATUS_PSCHIST_TABLE "StabilityStatus_pschist"
#define STABILITYSTATUS_PSCHIST_PK_STABILITYSTATUS_FIELD "PK_StabilityStatus"
#define STABILITYSTATUS_PSCHIST_PK_STABILITYSTATUS_TABLE_FIELD "StabilityStatus_pschist.PK_StabilityStatus"
#define STABILITYSTATUS_PSCHIST_DESCRIPTION_FIELD "Description"
#define STABILITYSTATUS_PSCHIST_DESCRIPTION_TABLE_FIELD "StabilityStatus_pschist.Description"
#define STABILITYSTATUS_PSCHIST_DEFINE_FIELD "Define"
#define STABILITYSTATUS_PSCHIST_DEFINE_TABLE_FIELD "StabilityStatus_pschist.Define"
#define STABILITYSTATUS_PSCHIST_PSC_ID_FIELD "psc_id"
#define STABILITYSTATUS_PSCHIST_PSC_ID_TABLE_FIELD "StabilityStatus_pschist.psc_id"
#define STABILITYSTATUS_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define STABILITYSTATUS_PSCHIST_PSC_BATCH_TABLE_FIELD "StabilityStatus_pschist.psc_batch"
#define STABILITYSTATUS_PSCHIST_PSC_USER_FIELD "psc_user"
#define STABILITYSTATUS_PSCHIST_PSC_USER_TABLE_FIELD "StabilityStatus_pschist.psc_user"
#define STABILITYSTATUS_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define STABILITYSTATUS_PSCHIST_PSC_FROZEN_TABLE_FIELD "StabilityStatus_pschist.psc_frozen"
#define STABILITYSTATUS_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define STABILITYSTATUS_PSCHIST_PSC_MOD_TABLE_FIELD "StabilityStatus_pschist.psc_mod"
#define STABILITYSTATUS_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define STABILITYSTATUS_PSCHIST_PSC_TOC_TABLE_FIELD "StabilityStatus_pschist.psc_toc"
#define STABILITYSTATUS_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define STABILITYSTATUS_PSCHIST_PSC_RESTRICT_TABLE_FIELD "StabilityStatus_pschist.psc_restrict"


#endif

