#ifndef __Define_Distro_pschist_H__
#define __Define_Distro_pschist_H__


#define DISTRO_PSCHIST_TABLE "Distro_pschist"
#define DISTRO_PSCHIST_PK_DISTRO_FIELD "PK_Distro"
#define DISTRO_PSCHIST_PK_DISTRO_TABLE_FIELD "Distro_pschist.PK_Distro"
#define DISTRO_PSCHIST_DESCRIPTION_FIELD "Description"
#define DISTRO_PSCHIST_DESCRIPTION_TABLE_FIELD "Distro_pschist.Description"
#define DISTRO_PSCHIST_DEFINE_FIELD "Define"
#define DISTRO_PSCHIST_DEFINE_TABLE_FIELD "Distro_pschist.Define"
#define DISTRO_PSCHIST_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define DISTRO_PSCHIST_FK_OPERATINGSYSTEM_TABLE_FIELD "Distro_pschist.FK_OperatingSystem"
#define DISTRO_PSCHIST_INSTALLER_FIELD "Installer"
#define DISTRO_PSCHIST_INSTALLER_TABLE_FIELD "Distro_pschist.Installer"
#define DISTRO_PSCHIST_KICKSTARTCD_FIELD "KickStartCD"
#define DISTRO_PSCHIST_KICKSTARTCD_TABLE_FIELD "Distro_pschist.KickStartCD"
#define DISTRO_PSCHIST_BINARIES_FIELD "Binaries"
#define DISTRO_PSCHIST_BINARIES_TABLE_FIELD "Distro_pschist.Binaries"
#define DISTRO_PSCHIST_SOURCECODE_FIELD "SourceCode"
#define DISTRO_PSCHIST_SOURCECODE_TABLE_FIELD "Distro_pschist.SourceCode"
#define DISTRO_PSCHIST_CONFIRMED_FIELD "Confirmed"
#define DISTRO_PSCHIST_CONFIRMED_TABLE_FIELD "Distro_pschist.Confirmed"
#define DISTRO_PSCHIST_CORE_FIELD "Core"
#define DISTRO_PSCHIST_CORE_TABLE_FIELD "Distro_pschist.Core"
#define DISTRO_PSCHIST_MEDIADIRECTOR_FIELD "MediaDirector"
#define DISTRO_PSCHIST_MEDIADIRECTOR_TABLE_FIELD "Distro_pschist.MediaDirector"
#define DISTRO_PSCHIST_ORBITER_FIELD "Orbiter"
#define DISTRO_PSCHIST_ORBITER_TABLE_FIELD "Distro_pschist.Orbiter"
#define DISTRO_PSCHIST_INSTALLERURL_FIELD "InstallerURL"
#define DISTRO_PSCHIST_INSTALLERURL_TABLE_FIELD "Distro_pschist.InstallerURL"
#define DISTRO_PSCHIST_PSC_ID_FIELD "psc_id"
#define DISTRO_PSCHIST_PSC_ID_TABLE_FIELD "Distro_pschist.psc_id"
#define DISTRO_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DISTRO_PSCHIST_PSC_BATCH_TABLE_FIELD "Distro_pschist.psc_batch"
#define DISTRO_PSCHIST_PSC_USER_FIELD "psc_user"
#define DISTRO_PSCHIST_PSC_USER_TABLE_FIELD "Distro_pschist.psc_user"
#define DISTRO_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DISTRO_PSCHIST_PSC_FROZEN_TABLE_FIELD "Distro_pschist.psc_frozen"
#define DISTRO_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DISTRO_PSCHIST_PSC_MOD_TABLE_FIELD "Distro_pschist.psc_mod"
#define DISTRO_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DISTRO_PSCHIST_PSC_TOC_TABLE_FIELD "Distro_pschist.psc_toc"
#define DISTRO_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DISTRO_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Distro_pschist.psc_restrict"


#endif

