#ifndef __Define_CriteriaList_pschmask_H__
#define __Define_CriteriaList_pschmask_H__


#define CRITERIALIST_PSCHMASK_TABLE "CriteriaList_pschmask"
#define CRITERIALIST_PSCHMASK_PK_CRITERIALIST_FIELD "PK_CriteriaList"
#define CRITERIALIST_PSCHMASK_PK_CRITERIALIST_TABLE_FIELD "CriteriaList_pschmask.PK_CriteriaList"
#define CRITERIALIST_PSCHMASK_DESCRIPTION_FIELD "Description"
#define CRITERIALIST_PSCHMASK_DESCRIPTION_TABLE_FIELD "CriteriaList_pschmask.Description"
#define CRITERIALIST_PSCHMASK_DEFINE_FIELD "Define"
#define CRITERIALIST_PSCHMASK_DEFINE_TABLE_FIELD "CriteriaList_pschmask.Define"
#define CRITERIALIST_PSCHMASK_PSC_ID_FIELD "psc_id"
#define CRITERIALIST_PSCHMASK_PSC_ID_TABLE_FIELD "CriteriaList_pschmask.psc_id"
#define CRITERIALIST_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define CRITERIALIST_PSCHMASK_PSC_BATCH_TABLE_FIELD "CriteriaList_pschmask.psc_batch"
#define CRITERIALIST_PSCHMASK_PSC_USER_FIELD "psc_user"
#define CRITERIALIST_PSCHMASK_PSC_USER_TABLE_FIELD "CriteriaList_pschmask.psc_user"
#define CRITERIALIST_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define CRITERIALIST_PSCHMASK_PSC_FROZEN_TABLE_FIELD "CriteriaList_pschmask.psc_frozen"
#define CRITERIALIST_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define CRITERIALIST_PSCHMASK_PSC_MOD_TABLE_FIELD "CriteriaList_pschmask.psc_mod"
#define CRITERIALIST_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define CRITERIALIST_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "CriteriaList_pschmask.psc_restrict"


#endif

