#ifndef __Define_Device_MRU_pschmask_H__
#define __Define_Device_MRU_pschmask_H__


#define DEVICE_MRU_PSCHMASK_TABLE "Device_MRU_pschmask"
#define DEVICE_MRU_PSCHMASK_PK_DEVICE_MRU_FIELD "PK_Device_MRU"
#define DEVICE_MRU_PSCHMASK_PK_DEVICE_MRU_TABLE_FIELD "Device_MRU_pschmask.PK_Device_MRU"
#define DEVICE_MRU_PSCHMASK_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_MRU_PSCHMASK_FK_DEVICE_TABLE_FIELD "Device_MRU_pschmask.FK_Device"
#define DEVICE_MRU_PSCHMASK_FILENAME_FIELD "Filename"
#define DEVICE_MRU_PSCHMASK_FILENAME_TABLE_FIELD "Device_MRU_pschmask.Filename"
#define DEVICE_MRU_PSCHMASK_LASTUSED_FIELD "LastUsed"
#define DEVICE_MRU_PSCHMASK_LASTUSED_TABLE_FIELD "Device_MRU_pschmask.LastUsed"
#define DEVICE_MRU_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DEVICE_MRU_PSCHMASK_PSC_ID_TABLE_FIELD "Device_MRU_pschmask.psc_id"
#define DEVICE_MRU_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_MRU_PSCHMASK_PSC_BATCH_TABLE_FIELD "Device_MRU_pschmask.psc_batch"
#define DEVICE_MRU_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DEVICE_MRU_PSCHMASK_PSC_USER_TABLE_FIELD "Device_MRU_pschmask.psc_user"
#define DEVICE_MRU_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_MRU_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Device_MRU_pschmask.psc_frozen"
#define DEVICE_MRU_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DEVICE_MRU_PSCHMASK_PSC_MOD_TABLE_FIELD "Device_MRU_pschmask.psc_mod"
#define DEVICE_MRU_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_MRU_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Device_MRU_pschmask.psc_restrict"


#endif

