#ifndef __Define_CriteriaParm_D_H__
#define __Define_CriteriaParm_D_H__


#define CRITERIAPARM_D_TABLE "CriteriaParm_D"
#define CRITERIAPARM_D_PK_CRITERIAPARM_FIELD "PK_CriteriaParm"
#define CRITERIAPARM_D_PK_CRITERIAPARM_TABLE_FIELD "CriteriaParm_D.PK_CriteriaParm"
#define CRITERIAPARM_D_FK_CRITERIAPARMNESTING_D_FIELD "FK_CriteriaParmNesting_D"
#define CRITERIAPARM_D_FK_CRITERIAPARMNESTING_D_TABLE_FIELD "CriteriaParm_D.FK_CriteriaParmNesting_D"
#define CRITERIAPARM_D_FK_CRITERIAPARMLIST_FIELD "FK_CriteriaParmList"
#define CRITERIAPARM_D_FK_CRITERIAPARMLIST_TABLE_FIELD "CriteriaParm_D.FK_CriteriaParmList"
#define CRITERIAPARM_D_OPERATOR_FIELD "Operator"
#define CRITERIAPARM_D_OPERATOR_TABLE_FIELD "CriteriaParm_D.Operator"
#define CRITERIAPARM_D_VALUE_FIELD "Value"
#define CRITERIAPARM_D_VALUE_TABLE_FIELD "CriteriaParm_D.Value"
#define CRITERIAPARM_D_FK_CANNEDEVENTS_CRITERIAPARMLIST_FIELD "FK_CannedEvents_CriteriaParmList"
#define CRITERIAPARM_D_FK_CANNEDEVENTS_CRITERIAPARMLIST_TABLE_FIELD "CriteriaParm_D.FK_CannedEvents_CriteriaParmList"
#define CRITERIAPARM_D_PSC_ID_FIELD "psc_id"
#define CRITERIAPARM_D_PSC_ID_TABLE_FIELD "CriteriaParm_D.psc_id"
#define CRITERIAPARM_D_PSC_BATCH_FIELD "psc_batch"
#define CRITERIAPARM_D_PSC_BATCH_TABLE_FIELD "CriteriaParm_D.psc_batch"
#define CRITERIAPARM_D_PSC_USER_FIELD "psc_user"
#define CRITERIAPARM_D_PSC_USER_TABLE_FIELD "CriteriaParm_D.psc_user"
#define CRITERIAPARM_D_PSC_FROZEN_FIELD "psc_frozen"
#define CRITERIAPARM_D_PSC_FROZEN_TABLE_FIELD "CriteriaParm_D.psc_frozen"
#define CRITERIAPARM_D_PSC_MOD_FIELD "psc_mod"
#define CRITERIAPARM_D_PSC_MOD_TABLE_FIELD "CriteriaParm_D.psc_mod"
#define CRITERIAPARM_D_PSC_RESTRICT_FIELD "psc_restrict"
#define CRITERIAPARM_D_PSC_RESTRICT_TABLE_FIELD "CriteriaParm_D.psc_restrict"


#endif

