#ifndef __Define_OperatingSystem_pschist_H__
#define __Define_OperatingSystem_pschist_H__


#define OPERATINGSYSTEM_PSCHIST_TABLE "OperatingSystem_pschist"
#define OPERATINGSYSTEM_PSCHIST_PK_OPERATINGSYSTEM_FIELD "PK_OperatingSystem"
#define OPERATINGSYSTEM_PSCHIST_PK_OPERATINGSYSTEM_TABLE_FIELD "OperatingSystem_pschist.PK_OperatingSystem"
#define OPERATINGSYSTEM_PSCHIST_DESCRIPTION_FIELD "Description"
#define OPERATINGSYSTEM_PSCHIST_DESCRIPTION_TABLE_FIELD "OperatingSystem_pschist.Description"
#define OPERATINGSYSTEM_PSCHIST_DEFINE_FIELD "Define"
#define OPERATINGSYSTEM_PSCHIST_DEFINE_TABLE_FIELD "OperatingSystem_pschist.Define"
#define OPERATINGSYSTEM_PSCHIST_PSC_ID_FIELD "psc_id"
#define OPERATINGSYSTEM_PSCHIST_PSC_ID_TABLE_FIELD "OperatingSystem_pschist.psc_id"
#define OPERATINGSYSTEM_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define OPERATINGSYSTEM_PSCHIST_PSC_BATCH_TABLE_FIELD "OperatingSystem_pschist.psc_batch"
#define OPERATINGSYSTEM_PSCHIST_PSC_USER_FIELD "psc_user"
#define OPERATINGSYSTEM_PSCHIST_PSC_USER_TABLE_FIELD "OperatingSystem_pschist.psc_user"
#define OPERATINGSYSTEM_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define OPERATINGSYSTEM_PSCHIST_PSC_FROZEN_TABLE_FIELD "OperatingSystem_pschist.psc_frozen"
#define OPERATINGSYSTEM_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define OPERATINGSYSTEM_PSCHIST_PSC_MOD_TABLE_FIELD "OperatingSystem_pschist.psc_mod"
#define OPERATINGSYSTEM_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define OPERATINGSYSTEM_PSCHIST_PSC_TOC_TABLE_FIELD "OperatingSystem_pschist.psc_toc"
#define OPERATINGSYSTEM_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define OPERATINGSYSTEM_PSCHIST_PSC_RESTRICT_TABLE_FIELD "OperatingSystem_pschist.psc_restrict"


#endif

