#ifndef __Define_PnpProtocol_pschmask_H__
#define __Define_PnpProtocol_pschmask_H__


#define PNPPROTOCOL_PSCHMASK_TABLE "PnpProtocol_pschmask"
#define PNPPROTOCOL_PSCHMASK_PK_PNPPROTOCOL_FIELD "PK_PnpProtocol"
#define PNPPROTOCOL_PSCHMASK_PK_PNPPROTOCOL_TABLE_FIELD "PnpProtocol_pschmask.PK_PnpProtocol"
#define PNPPROTOCOL_PSCHMASK_DESCRIPTION_FIELD "Description"
#define PNPPROTOCOL_PSCHMASK_DESCRIPTION_TABLE_FIELD "PnpProtocol_pschmask.Description"
#define PNPPROTOCOL_PSCHMASK_DEFINE_FIELD "Define"
#define PNPPROTOCOL_PSCHMASK_DEFINE_TABLE_FIELD "PnpProtocol_pschmask.Define"
#define PNPPROTOCOL_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PNPPROTOCOL_PSCHMASK_PSC_ID_TABLE_FIELD "PnpProtocol_pschmask.psc_id"
#define PNPPROTOCOL_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PNPPROTOCOL_PSCHMASK_PSC_BATCH_TABLE_FIELD "PnpProtocol_pschmask.psc_batch"
#define PNPPROTOCOL_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PNPPROTOCOL_PSCHMASK_PSC_USER_TABLE_FIELD "PnpProtocol_pschmask.psc_user"
#define PNPPROTOCOL_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PNPPROTOCOL_PSCHMASK_PSC_FROZEN_TABLE_FIELD "PnpProtocol_pschmask.psc_frozen"
#define PNPPROTOCOL_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PNPPROTOCOL_PSCHMASK_PSC_MOD_TABLE_FIELD "PnpProtocol_pschmask.psc_mod"
#define PNPPROTOCOL_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PNPPROTOCOL_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "PnpProtocol_pschmask.psc_restrict"


#endif

