#ifndef __Define_Package_Device_pschist_H__
#define __Define_Package_Device_pschist_H__


#define PACKAGE_DEVICE_PSCHIST_TABLE "Package_Device_pschist"
#define PACKAGE_DEVICE_PSCHIST_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_DEVICE_PSCHIST_FK_PACKAGE_TABLE_FIELD "Package_Device_pschist.FK_Package"
#define PACKAGE_DEVICE_PSCHIST_FK_DEVICE_FIELD "FK_Device"
#define PACKAGE_DEVICE_PSCHIST_FK_DEVICE_TABLE_FIELD "Package_Device_pschist.FK_Device"
#define PACKAGE_DEVICE_PSCHIST_VERSION_FIELD "Version"
#define PACKAGE_DEVICE_PSCHIST_VERSION_TABLE_FIELD "Package_Device_pschist.Version"
#define PACKAGE_DEVICE_PSCHIST_INSTALLDATE_FIELD "InstallDate"
#define PACKAGE_DEVICE_PSCHIST_INSTALLDATE_TABLE_FIELD "Package_Device_pschist.InstallDate"
#define PACKAGE_DEVICE_PSCHIST_PSC_ID_FIELD "psc_id"
#define PACKAGE_DEVICE_PSCHIST_PSC_ID_TABLE_FIELD "Package_Device_pschist.psc_id"
#define PACKAGE_DEVICE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_DEVICE_PSCHIST_PSC_BATCH_TABLE_FIELD "Package_Device_pschist.psc_batch"
#define PACKAGE_DEVICE_PSCHIST_PSC_USER_FIELD "psc_user"
#define PACKAGE_DEVICE_PSCHIST_PSC_USER_TABLE_FIELD "Package_Device_pschist.psc_user"
#define PACKAGE_DEVICE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_DEVICE_PSCHIST_PSC_FROZEN_TABLE_FIELD "Package_Device_pschist.psc_frozen"
#define PACKAGE_DEVICE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_DEVICE_PSCHIST_PSC_MOD_TABLE_FIELD "Package_Device_pschist.psc_mod"
#define PACKAGE_DEVICE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PACKAGE_DEVICE_PSCHIST_PSC_TOC_TABLE_FIELD "Package_Device_pschist.psc_toc"
#define PACKAGE_DEVICE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_DEVICE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Package_Device_pschist.psc_restrict"


#endif

