#ifndef __Define_CommandGroup_D_pschmask_H__
#define __Define_CommandGroup_D_pschmask_H__


#define COMMANDGROUP_D_PSCHMASK_TABLE "CommandGroup_D_pschmask"
#define COMMANDGROUP_D_PSCHMASK_PK_COMMANDGROUP_D_FIELD "PK_CommandGroup_D"
#define COMMANDGROUP_D_PSCHMASK_PK_COMMANDGROUP_D_TABLE_FIELD "CommandGroup_D_pschmask.PK_CommandGroup_D"
#define COMMANDGROUP_D_PSCHMASK_FK_CRITERIA_ORBITER_FIELD "FK_Criteria_Orbiter"
#define COMMANDGROUP_D_PSCHMASK_FK_CRITERIA_ORBITER_TABLE_FIELD "CommandGroup_D_pschmask.FK_Criteria_Orbiter"
#define COMMANDGROUP_D_PSCHMASK_PSC_ID_FIELD "psc_id"
#define COMMANDGROUP_D_PSCHMASK_PSC_ID_TABLE_FIELD "CommandGroup_D_pschmask.psc_id"
#define COMMANDGROUP_D_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define COMMANDGROUP_D_PSCHMASK_PSC_BATCH_TABLE_FIELD "CommandGroup_D_pschmask.psc_batch"
#define COMMANDGROUP_D_PSCHMASK_PSC_USER_FIELD "psc_user"
#define COMMANDGROUP_D_PSCHMASK_PSC_USER_TABLE_FIELD "CommandGroup_D_pschmask.psc_user"
#define COMMANDGROUP_D_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define COMMANDGROUP_D_PSCHMASK_PSC_FROZEN_TABLE_FIELD "CommandGroup_D_pschmask.psc_frozen"
#define COMMANDGROUP_D_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define COMMANDGROUP_D_PSCHMASK_PSC_MOD_TABLE_FIELD "CommandGroup_D_pschmask.psc_mod"
#define COMMANDGROUP_D_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMANDGROUP_D_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "CommandGroup_D_pschmask.psc_restrict"


#endif

