#ifndef __Define_Distro_pschmask_H__
#define __Define_Distro_pschmask_H__


#define DISTRO_PSCHMASK_TABLE "Distro_pschmask"
#define DISTRO_PSCHMASK_PK_DISTRO_FIELD "PK_Distro"
#define DISTRO_PSCHMASK_PK_DISTRO_TABLE_FIELD "Distro_pschmask.PK_Distro"
#define DISTRO_PSCHMASK_DESCRIPTION_FIELD "Description"
#define DISTRO_PSCHMASK_DESCRIPTION_TABLE_FIELD "Distro_pschmask.Description"
#define DISTRO_PSCHMASK_DEFINE_FIELD "Define"
#define DISTRO_PSCHMASK_DEFINE_TABLE_FIELD "Distro_pschmask.Define"
#define DISTRO_PSCHMASK_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define DISTRO_PSCHMASK_FK_OPERATINGSYSTEM_TABLE_FIELD "Distro_pschmask.FK_OperatingSystem"
#define DISTRO_PSCHMASK_INSTALLER_FIELD "Installer"
#define DISTRO_PSCHMASK_INSTALLER_TABLE_FIELD "Distro_pschmask.Installer"
#define DISTRO_PSCHMASK_KICKSTARTCD_FIELD "KickStartCD"
#define DISTRO_PSCHMASK_KICKSTARTCD_TABLE_FIELD "Distro_pschmask.KickStartCD"
#define DISTRO_PSCHMASK_BINARIES_FIELD "Binaries"
#define DISTRO_PSCHMASK_BINARIES_TABLE_FIELD "Distro_pschmask.Binaries"
#define DISTRO_PSCHMASK_SOURCECODE_FIELD "SourceCode"
#define DISTRO_PSCHMASK_SOURCECODE_TABLE_FIELD "Distro_pschmask.SourceCode"
#define DISTRO_PSCHMASK_CONFIRMED_FIELD "Confirmed"
#define DISTRO_PSCHMASK_CONFIRMED_TABLE_FIELD "Distro_pschmask.Confirmed"
#define DISTRO_PSCHMASK_CORE_FIELD "Core"
#define DISTRO_PSCHMASK_CORE_TABLE_FIELD "Distro_pschmask.Core"
#define DISTRO_PSCHMASK_MEDIADIRECTOR_FIELD "MediaDirector"
#define DISTRO_PSCHMASK_MEDIADIRECTOR_TABLE_FIELD "Distro_pschmask.MediaDirector"
#define DISTRO_PSCHMASK_ORBITER_FIELD "Orbiter"
#define DISTRO_PSCHMASK_ORBITER_TABLE_FIELD "Distro_pschmask.Orbiter"
#define DISTRO_PSCHMASK_INSTALLERURL_FIELD "InstallerURL"
#define DISTRO_PSCHMASK_INSTALLERURL_TABLE_FIELD "Distro_pschmask.InstallerURL"
#define DISTRO_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DISTRO_PSCHMASK_PSC_ID_TABLE_FIELD "Distro_pschmask.psc_id"
#define DISTRO_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DISTRO_PSCHMASK_PSC_BATCH_TABLE_FIELD "Distro_pschmask.psc_batch"
#define DISTRO_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DISTRO_PSCHMASK_PSC_USER_TABLE_FIELD "Distro_pschmask.psc_user"
#define DISTRO_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DISTRO_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Distro_pschmask.psc_frozen"
#define DISTRO_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DISTRO_PSCHMASK_PSC_MOD_TABLE_FIELD "Distro_pschmask.psc_mod"
#define DISTRO_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DISTRO_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Distro_pschmask.psc_restrict"


#endif

