#ifndef __Define_Manufacturer_pschist_H__
#define __Define_Manufacturer_pschist_H__


#define MANUFACTURER_PSCHIST_TABLE "Manufacturer_pschist"
#define MANUFACTURER_PSCHIST_PK_MANUFACTURER_FIELD "PK_Manufacturer"
#define MANUFACTURER_PSCHIST_PK_MANUFACTURER_TABLE_FIELD "Manufacturer_pschist.PK_Manufacturer"
#define MANUFACTURER_PSCHIST_DESCRIPTION_FIELD "Description"
#define MANUFACTURER_PSCHIST_DESCRIPTION_TABLE_FIELD "Manufacturer_pschist.Description"
#define MANUFACTURER_PSCHIST_IRFREQUENCY_FIELD "IRFrequency"
#define MANUFACTURER_PSCHIST_IRFREQUENCY_TABLE_FIELD "Manufacturer_pschist.IRFrequency"
#define MANUFACTURER_PSCHIST_PSC_ID_FIELD "psc_id"
#define MANUFACTURER_PSCHIST_PSC_ID_TABLE_FIELD "Manufacturer_pschist.psc_id"
#define MANUFACTURER_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define MANUFACTURER_PSCHIST_PSC_BATCH_TABLE_FIELD "Manufacturer_pschist.psc_batch"
#define MANUFACTURER_PSCHIST_PSC_USER_FIELD "psc_user"
#define MANUFACTURER_PSCHIST_PSC_USER_TABLE_FIELD "Manufacturer_pschist.psc_user"
#define MANUFACTURER_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define MANUFACTURER_PSCHIST_PSC_FROZEN_TABLE_FIELD "Manufacturer_pschist.psc_frozen"
#define MANUFACTURER_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define MANUFACTURER_PSCHIST_PSC_MOD_TABLE_FIELD "Manufacturer_pschist.psc_mod"
#define MANUFACTURER_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define MANUFACTURER_PSCHIST_PSC_TOC_TABLE_FIELD "Manufacturer_pschist.psc_toc"
#define MANUFACTURER_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define MANUFACTURER_PSCHIST_PSC_RESTRICT_TABLE_FIELD "Manufacturer_pschist.psc_restrict"


#endif

