#ifndef __Define_Package_Users_pschmask_H__
#define __Define_Package_Users_pschmask_H__


#define PACKAGE_USERS_PSCHMASK_TABLE "Package_Users_pschmask"
#define PACKAGE_USERS_PSCHMASK_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_USERS_PSCHMASK_FK_PACKAGE_TABLE_FIELD "Package_Users_pschmask.FK_Package"
#define PACKAGE_USERS_PSCHMASK_FK_USERS_FIELD "FK_Users"
#define PACKAGE_USERS_PSCHMASK_FK_USERS_TABLE_FIELD "Package_Users_pschmask.FK_Users"
#define PACKAGE_USERS_PSCHMASK_ADMINISTRATOR_FIELD "Administrator"
#define PACKAGE_USERS_PSCHMASK_ADMINISTRATOR_TABLE_FIELD "Package_Users_pschmask.Administrator"
#define PACKAGE_USERS_PSCHMASK_COMMENTS_FIELD "Comments"
#define PACKAGE_USERS_PSCHMASK_COMMENTS_TABLE_FIELD "Package_Users_pschmask.Comments"
#define PACKAGE_USERS_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PACKAGE_USERS_PSCHMASK_PSC_ID_TABLE_FIELD "Package_Users_pschmask.psc_id"
#define PACKAGE_USERS_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_USERS_PSCHMASK_PSC_BATCH_TABLE_FIELD "Package_Users_pschmask.psc_batch"
#define PACKAGE_USERS_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PACKAGE_USERS_PSCHMASK_PSC_USER_TABLE_FIELD "Package_Users_pschmask.psc_user"
#define PACKAGE_USERS_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_USERS_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Package_Users_pschmask.psc_frozen"
#define PACKAGE_USERS_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_USERS_PSCHMASK_PSC_MOD_TABLE_FIELD "Package_Users_pschmask.psc_mod"
#define PACKAGE_USERS_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_USERS_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Package_Users_pschmask.psc_restrict"


#endif

