#ifndef __Define_Device_HouseMode_pschmask_H__
#define __Define_Device_HouseMode_pschmask_H__


#define DEVICE_HOUSEMODE_PSCHMASK_TABLE "Device_HouseMode_pschmask"
#define DEVICE_HOUSEMODE_PSCHMASK_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_HOUSEMODE_PSCHMASK_FK_DEVICE_TABLE_FIELD "Device_HouseMode_pschmask.FK_Device"
#define DEVICE_HOUSEMODE_PSCHMASK_FK_HOUSEMODE_FIELD "FK_HouseMode"
#define DEVICE_HOUSEMODE_PSCHMASK_FK_HOUSEMODE_TABLE_FIELD "Device_HouseMode_pschmask.FK_HouseMode"
#define DEVICE_HOUSEMODE_PSCHMASK_FK_EVENT_FIELD "FK_Event"
#define DEVICE_HOUSEMODE_PSCHMASK_FK_EVENT_TABLE_FIELD "Device_HouseMode_pschmask.FK_Event"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_ID_TABLE_FIELD "Device_HouseMode_pschmask.psc_id"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_BATCH_TABLE_FIELD "Device_HouseMode_pschmask.psc_batch"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_USER_TABLE_FIELD "Device_HouseMode_pschmask.psc_user"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Device_HouseMode_pschmask.psc_frozen"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_MOD_TABLE_FIELD "Device_HouseMode_pschmask.psc_mod"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_HOUSEMODE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Device_HouseMode_pschmask.psc_restrict"


#endif

