#ifndef __Define_Package_Device_pschmask_H__
#define __Define_Package_Device_pschmask_H__


#define PACKAGE_DEVICE_PSCHMASK_TABLE "Package_Device_pschmask"
#define PACKAGE_DEVICE_PSCHMASK_FK_PACKAGE_FIELD "FK_Package"
#define PACKAGE_DEVICE_PSCHMASK_FK_PACKAGE_TABLE_FIELD "Package_Device_pschmask.FK_Package"
#define PACKAGE_DEVICE_PSCHMASK_FK_DEVICE_FIELD "FK_Device"
#define PACKAGE_DEVICE_PSCHMASK_FK_DEVICE_TABLE_FIELD "Package_Device_pschmask.FK_Device"
#define PACKAGE_DEVICE_PSCHMASK_VERSION_FIELD "Version"
#define PACKAGE_DEVICE_PSCHMASK_VERSION_TABLE_FIELD "Package_Device_pschmask.Version"
#define PACKAGE_DEVICE_PSCHMASK_INSTALLDATE_FIELD "InstallDate"
#define PACKAGE_DEVICE_PSCHMASK_INSTALLDATE_TABLE_FIELD "Package_Device_pschmask.InstallDate"
#define PACKAGE_DEVICE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PACKAGE_DEVICE_PSCHMASK_PSC_ID_TABLE_FIELD "Package_Device_pschmask.psc_id"
#define PACKAGE_DEVICE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_DEVICE_PSCHMASK_PSC_BATCH_TABLE_FIELD "Package_Device_pschmask.psc_batch"
#define PACKAGE_DEVICE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PACKAGE_DEVICE_PSCHMASK_PSC_USER_TABLE_FIELD "Package_Device_pschmask.psc_user"
#define PACKAGE_DEVICE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_DEVICE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Package_Device_pschmask.psc_frozen"
#define PACKAGE_DEVICE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_DEVICE_PSCHMASK_PSC_MOD_TABLE_FIELD "Package_Device_pschmask.psc_mod"
#define PACKAGE_DEVICE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGE_DEVICE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Package_Device_pschmask.psc_restrict"


#endif

