#ifndef __Define_EffectType_Effect_Skin_H__
#define __Define_EffectType_Effect_Skin_H__


#define EFFECTTYPE_EFFECT_SKIN_TABLE "EffectType_Effect_Skin"
#define EFFECTTYPE_EFFECT_SKIN_FK_EFFECTTYPE_FIELD "FK_EffectType"
#define EFFECTTYPE_EFFECT_SKIN_FK_EFFECTTYPE_TABLE_FIELD "EffectType_Effect_Skin.FK_EffectType"
#define EFFECTTYPE_EFFECT_SKIN_FK_EFFECT_FIELD "FK_Effect"
#define EFFECTTYPE_EFFECT_SKIN_FK_EFFECT_TABLE_FIELD "EffectType_Effect_Skin.FK_Effect"
#define EFFECTTYPE_EFFECT_SKIN_FK_SKIN_FIELD "FK_Skin"
#define EFFECTTYPE_EFFECT_SKIN_FK_SKIN_TABLE_FIELD "EffectType_Effect_Skin.FK_Skin"
#define EFFECTTYPE_EFFECT_SKIN_PSC_ID_FIELD "psc_id"
#define EFFECTTYPE_EFFECT_SKIN_PSC_ID_TABLE_FIELD "EffectType_Effect_Skin.psc_id"
#define EFFECTTYPE_EFFECT_SKIN_PSC_BATCH_FIELD "psc_batch"
#define EFFECTTYPE_EFFECT_SKIN_PSC_BATCH_TABLE_FIELD "EffectType_Effect_Skin.psc_batch"
#define EFFECTTYPE_EFFECT_SKIN_PSC_USER_FIELD "psc_user"
#define EFFECTTYPE_EFFECT_SKIN_PSC_USER_TABLE_FIELD "EffectType_Effect_Skin.psc_user"
#define EFFECTTYPE_EFFECT_SKIN_PSC_FROZEN_FIELD "psc_frozen"
#define EFFECTTYPE_EFFECT_SKIN_PSC_FROZEN_TABLE_FIELD "EffectType_Effect_Skin.psc_frozen"
#define EFFECTTYPE_EFFECT_SKIN_PSC_MOD_FIELD "psc_mod"
#define EFFECTTYPE_EFFECT_SKIN_PSC_MOD_TABLE_FIELD "EffectType_Effect_Skin.psc_mod"
#define EFFECTTYPE_EFFECT_SKIN_PSC_RESTRICT_FIELD "psc_restrict"
#define EFFECTTYPE_EFFECT_SKIN_PSC_RESTRICT_TABLE_FIELD "EffectType_Effect_Skin.psc_restrict"


#endif

