#ifndef __Define_Floorplan_pschmask_H__
#define __Define_Floorplan_pschmask_H__


#define FLOORPLAN_PSCHMASK_TABLE "Floorplan_pschmask"
#define FLOORPLAN_PSCHMASK_FK_INSTALLATION_FIELD "FK_Installation"
#define FLOORPLAN_PSCHMASK_FK_INSTALLATION_TABLE_FIELD "Floorplan_pschmask.FK_Installation"
#define FLOORPLAN_PSCHMASK_PAGE_FIELD "Page"
#define FLOORPLAN_PSCHMASK_PAGE_TABLE_FIELD "Floorplan_pschmask.Page"
#define FLOORPLAN_PSCHMASK_DESCRIPTION_FIELD "Description"
#define FLOORPLAN_PSCHMASK_DESCRIPTION_TABLE_FIELD "Floorplan_pschmask.Description"
#define FLOORPLAN_PSCHMASK_FK_ICON_FIELD "FK_Icon"
#define FLOORPLAN_PSCHMASK_FK_ICON_TABLE_FIELD "Floorplan_pschmask.FK_Icon"
#define FLOORPLAN_PSCHMASK_PSC_ID_FIELD "psc_id"
#define FLOORPLAN_PSCHMASK_PSC_ID_TABLE_FIELD "Floorplan_pschmask.psc_id"
#define FLOORPLAN_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define FLOORPLAN_PSCHMASK_PSC_BATCH_TABLE_FIELD "Floorplan_pschmask.psc_batch"
#define FLOORPLAN_PSCHMASK_PSC_USER_FIELD "psc_user"
#define FLOORPLAN_PSCHMASK_PSC_USER_TABLE_FIELD "Floorplan_pschmask.psc_user"
#define FLOORPLAN_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define FLOORPLAN_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Floorplan_pschmask.psc_frozen"
#define FLOORPLAN_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define FLOORPLAN_PSCHMASK_PSC_MOD_TABLE_FIELD "Floorplan_pschmask.psc_mod"
#define FLOORPLAN_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define FLOORPLAN_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Floorplan_pschmask.psc_restrict"


#endif

