#ifndef __Define_DeviceTemplate_Event_H__
#define __Define_DeviceTemplate_Event_H__


#define DEVICETEMPLATE_EVENT_TABLE "DeviceTemplate_Event"
#define DEVICETEMPLATE_EVENT_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define DEVICETEMPLATE_EVENT_FK_DEVICETEMPLATE_TABLE_FIELD "DeviceTemplate_Event.FK_DeviceTemplate"
#define DEVICETEMPLATE_EVENT_FK_EVENT_FIELD "FK_Event"
#define DEVICETEMPLATE_EVENT_FK_EVENT_TABLE_FIELD "DeviceTemplate_Event.FK_Event"
#define DEVICETEMPLATE_EVENT_DESCRIPTION_FIELD "Description"
#define DEVICETEMPLATE_EVENT_DESCRIPTION_TABLE_FIELD "DeviceTemplate_Event.Description"
#define DEVICETEMPLATE_EVENT_CODE_FIELD "Code"
#define DEVICETEMPLATE_EVENT_CODE_TABLE_FIELD "DeviceTemplate_Event.Code"
#define DEVICETEMPLATE_EVENT_PSC_ID_FIELD "psc_id"
#define DEVICETEMPLATE_EVENT_PSC_ID_TABLE_FIELD "DeviceTemplate_Event.psc_id"
#define DEVICETEMPLATE_EVENT_PSC_BATCH_FIELD "psc_batch"
#define DEVICETEMPLATE_EVENT_PSC_BATCH_TABLE_FIELD "DeviceTemplate_Event.psc_batch"
#define DEVICETEMPLATE_EVENT_PSC_USER_FIELD "psc_user"
#define DEVICETEMPLATE_EVENT_PSC_USER_TABLE_FIELD "DeviceTemplate_Event.psc_user"
#define DEVICETEMPLATE_EVENT_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICETEMPLATE_EVENT_PSC_FROZEN_TABLE_FIELD "DeviceTemplate_Event.psc_frozen"
#define DEVICETEMPLATE_EVENT_PSC_MOD_FIELD "psc_mod"
#define DEVICETEMPLATE_EVENT_PSC_MOD_TABLE_FIELD "DeviceTemplate_Event.psc_mod"
#define DEVICETEMPLATE_EVENT_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICETEMPLATE_EVENT_PSC_RESTRICT_TABLE_FIELD "DeviceTemplate_Event.psc_restrict"


#endif

