#ifndef __Define_Direction_pschmask_H__
#define __Define_Direction_pschmask_H__


#define DIRECTION_PSCHMASK_TABLE "Direction_pschmask"
#define DIRECTION_PSCHMASK_PK_DIRECTION_FIELD "PK_Direction"
#define DIRECTION_PSCHMASK_PK_DIRECTION_TABLE_FIELD "Direction_pschmask.PK_Direction"
#define DIRECTION_PSCHMASK_DESCRIPTION_FIELD "Description"
#define DIRECTION_PSCHMASK_DESCRIPTION_TABLE_FIELD "Direction_pschmask.Description"
#define DIRECTION_PSCHMASK_DEFINE_FIELD "Define"
#define DIRECTION_PSCHMASK_DEFINE_TABLE_FIELD "Direction_pschmask.Define"
#define DIRECTION_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DIRECTION_PSCHMASK_PSC_ID_TABLE_FIELD "Direction_pschmask.psc_id"
#define DIRECTION_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DIRECTION_PSCHMASK_PSC_BATCH_TABLE_FIELD "Direction_pschmask.psc_batch"
#define DIRECTION_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DIRECTION_PSCHMASK_PSC_USER_TABLE_FIELD "Direction_pschmask.psc_user"
#define DIRECTION_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DIRECTION_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Direction_pschmask.psc_frozen"
#define DIRECTION_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DIRECTION_PSCHMASK_PSC_MOD_TABLE_FIELD "Direction_pschmask.psc_mod"
#define DIRECTION_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DIRECTION_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Direction_pschmask.psc_restrict"


#endif

