#ifndef __Define_ConfigType_Token_pschist_H__
#define __Define_ConfigType_Token_pschist_H__


#define CONFIGTYPE_TOKEN_PSCHIST_TABLE "ConfigType_Token_pschist"
#define CONFIGTYPE_TOKEN_PSCHIST_FK_CONFIGTYPE_SETTING_FIELD "FK_ConfigType_Setting"
#define CONFIGTYPE_TOKEN_PSCHIST_FK_CONFIGTYPE_SETTING_TABLE_FIELD "ConfigType_Token_pschist.FK_ConfigType_Setting"
#define CONFIGTYPE_TOKEN_PSCHIST_FK_CONFIGTYPE_FILE_FIELD "FK_ConfigType_File"
#define CONFIGTYPE_TOKEN_PSCHIST_FK_CONFIGTYPE_FILE_TABLE_FIELD "ConfigType_Token_pschist.FK_ConfigType_File"
#define CONFIGTYPE_TOKEN_PSCHIST_FINDSTR_FIELD "FindStr"
#define CONFIGTYPE_TOKEN_PSCHIST_FINDSTR_TABLE_FIELD "ConfigType_Token_pschist.FindStr"
#define CONFIGTYPE_TOKEN_PSCHIST_REPLACESTR_FIELD "ReplaceStr"
#define CONFIGTYPE_TOKEN_PSCHIST_REPLACESTR_TABLE_FIELD "ConfigType_Token_pschist.ReplaceStr"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_ID_FIELD "psc_id"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_ID_TABLE_FIELD "ConfigType_Token_pschist.psc_id"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_BATCH_TABLE_FIELD "ConfigType_Token_pschist.psc_batch"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_USER_FIELD "psc_user"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_USER_TABLE_FIELD "ConfigType_Token_pschist.psc_user"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_FROZEN_TABLE_FIELD "ConfigType_Token_pschist.psc_frozen"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_MOD_TABLE_FIELD "ConfigType_Token_pschist.psc_mod"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_TOC_TABLE_FIELD "ConfigType_Token_pschist.psc_toc"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define CONFIGTYPE_TOKEN_PSCHIST_PSC_RESTRICT_TABLE_FIELD "ConfigType_Token_pschist.psc_restrict"


#endif

