#ifndef __Define_Device_CommandGroup_H__
#define __Define_Device_CommandGroup_H__


#define DEVICE_COMMANDGROUP_TABLE "Device_CommandGroup"
#define DEVICE_COMMANDGROUP_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_COMMANDGROUP_FK_DEVICE_TABLE_FIELD "Device_CommandGroup.FK_Device"
#define DEVICE_COMMANDGROUP_FK_COMMANDGROUP_FIELD "FK_CommandGroup"
#define DEVICE_COMMANDGROUP_FK_COMMANDGROUP_TABLE_FIELD "Device_CommandGroup.FK_CommandGroup"
#define DEVICE_COMMANDGROUP_SORT_FIELD "Sort"
#define DEVICE_COMMANDGROUP_SORT_TABLE_FIELD "Device_CommandGroup.Sort"
#define DEVICE_COMMANDGROUP_PSC_ID_FIELD "psc_id"
#define DEVICE_COMMANDGROUP_PSC_ID_TABLE_FIELD "Device_CommandGroup.psc_id"
#define DEVICE_COMMANDGROUP_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_COMMANDGROUP_PSC_BATCH_TABLE_FIELD "Device_CommandGroup.psc_batch"
#define DEVICE_COMMANDGROUP_PSC_USER_FIELD "psc_user"
#define DEVICE_COMMANDGROUP_PSC_USER_TABLE_FIELD "Device_CommandGroup.psc_user"
#define DEVICE_COMMANDGROUP_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_COMMANDGROUP_PSC_FROZEN_TABLE_FIELD "Device_CommandGroup.psc_frozen"
#define DEVICE_COMMANDGROUP_PSC_MOD_FIELD "psc_mod"
#define DEVICE_COMMANDGROUP_PSC_MOD_TABLE_FIELD "Device_CommandGroup.psc_mod"
#define DEVICE_COMMANDGROUP_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_COMMANDGROUP_PSC_RESTRICT_TABLE_FIELD "Device_CommandGroup.psc_restrict"


#endif

