#ifndef __Define_Device_DeviceData_pschmask_H__
#define __Define_Device_DeviceData_pschmask_H__


#define DEVICE_DEVICEDATA_PSCHMASK_TABLE "Device_DeviceData_pschmask"
#define DEVICE_DEVICEDATA_PSCHMASK_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_DEVICEDATA_PSCHMASK_FK_DEVICE_TABLE_FIELD "Device_DeviceData_pschmask.FK_Device"
#define DEVICE_DEVICEDATA_PSCHMASK_FK_DEVICEDATA_FIELD "FK_DeviceData"
#define DEVICE_DEVICEDATA_PSCHMASK_FK_DEVICEDATA_TABLE_FIELD "Device_DeviceData_pschmask.FK_DeviceData"
#define DEVICE_DEVICEDATA_PSCHMASK_IK_DEVICEDATA_FIELD "IK_DeviceData"
#define DEVICE_DEVICEDATA_PSCHMASK_IK_DEVICEDATA_TABLE_FIELD "Device_DeviceData_pschmask.IK_DeviceData"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_ID_TABLE_FIELD "Device_DeviceData_pschmask.psc_id"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_BATCH_TABLE_FIELD "Device_DeviceData_pschmask.psc_batch"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_USER_TABLE_FIELD "Device_DeviceData_pschmask.psc_user"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Device_DeviceData_pschmask.psc_frozen"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_MOD_TABLE_FIELD "Device_DeviceData_pschmask.psc_mod"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_DEVICEDATA_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Device_DeviceData_pschmask.psc_restrict"


#endif

