#ifndef __Define_Device_Device_Related_pschmask_H__
#define __Define_Device_Device_Related_pschmask_H__


#define DEVICE_DEVICE_RELATED_PSCHMASK_TABLE "Device_Device_Related_pschmask"
#define DEVICE_DEVICE_RELATED_PSCHMASK_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_DEVICE_RELATED_PSCHMASK_FK_DEVICE_TABLE_FIELD "Device_Device_Related_pschmask.FK_Device"
#define DEVICE_DEVICE_RELATED_PSCHMASK_FK_DEVICE_RELATED_FIELD "FK_Device_Related"
#define DEVICE_DEVICE_RELATED_PSCHMASK_FK_DEVICE_RELATED_TABLE_FIELD "Device_Device_Related_pschmask.FK_Device_Related"
#define DEVICE_DEVICE_RELATED_PSCHMASK_VALUE_FIELD "Value"
#define DEVICE_DEVICE_RELATED_PSCHMASK_VALUE_TABLE_FIELD "Device_Device_Related_pschmask.Value"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_ID_FIELD "psc_id"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_ID_TABLE_FIELD "Device_Device_Related_pschmask.psc_id"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_BATCH_TABLE_FIELD "Device_Device_Related_pschmask.psc_batch"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_USER_FIELD "psc_user"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_USER_TABLE_FIELD "Device_Device_Related_pschmask.psc_user"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Device_Device_Related_pschmask.psc_frozen"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_MOD_TABLE_FIELD "Device_Device_Related_pschmask.psc_mod"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICE_DEVICE_RELATED_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Device_Device_Related_pschmask.psc_restrict"


#endif

