#ifndef __Define_Orbiter_pschmask_H__
#define __Define_Orbiter_pschmask_H__


#define ORBITER_PSCHMASK_TABLE "Orbiter_pschmask"
#define ORBITER_PSCHMASK_PK_ORBITER_FIELD "PK_Orbiter"
#define ORBITER_PSCHMASK_PK_ORBITER_TABLE_FIELD "Orbiter_pschmask.PK_Orbiter"
#define ORBITER_PSCHMASK_FLOORPLANINFO_FIELD "FloorplanInfo"
#define ORBITER_PSCHMASK_FLOORPLANINFO_TABLE_FIELD "Orbiter_pschmask.FloorplanInfo"
#define ORBITER_PSCHMASK_MODIFICATION_LASTGEN_FIELD "Modification_LastGen"
#define ORBITER_PSCHMASK_MODIFICATION_LASTGEN_TABLE_FIELD "Orbiter_pschmask.Modification_LastGen"
#define ORBITER_PSCHMASK_REGEN_FIELD "Regen"
#define ORBITER_PSCHMASK_REGEN_TABLE_FIELD "Orbiter_pschmask.Regen"
#define ORBITER_PSCHMASK_SIZE_FIELD "Size"
#define ORBITER_PSCHMASK_SIZE_TABLE_FIELD "Orbiter_pschmask.Size"
#define ORBITER_PSCHMASK_REGENINPROGRESS_FIELD "RegenInProgress"
#define ORBITER_PSCHMASK_REGENINPROGRESS_TABLE_FIELD "Orbiter_pschmask.RegenInProgress"
#define ORBITER_PSCHMASK_REGENSTATUS_FIELD "RegenStatus"
#define ORBITER_PSCHMASK_REGENSTATUS_TABLE_FIELD "Orbiter_pschmask.RegenStatus"
#define ORBITER_PSCHMASK_REGENPERCENT_FIELD "RegenPercent"
#define ORBITER_PSCHMASK_REGENPERCENT_TABLE_FIELD "Orbiter_pschmask.RegenPercent"
#define ORBITER_PSCHMASK_SCENARIOSFLOORPLANS_FIELD "ScenariosFloorplans"
#define ORBITER_PSCHMASK_SCENARIOSFLOORPLANS_TABLE_FIELD "Orbiter_pschmask.ScenariosFloorplans"
#define ORBITER_PSCHMASK_PSC_ID_FIELD "psc_id"
#define ORBITER_PSCHMASK_PSC_ID_TABLE_FIELD "Orbiter_pschmask.psc_id"
#define ORBITER_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define ORBITER_PSCHMASK_PSC_BATCH_TABLE_FIELD "Orbiter_pschmask.psc_batch"
#define ORBITER_PSCHMASK_PSC_USER_FIELD "psc_user"
#define ORBITER_PSCHMASK_PSC_USER_TABLE_FIELD "Orbiter_pschmask.psc_user"
#define ORBITER_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define ORBITER_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Orbiter_pschmask.psc_frozen"
#define ORBITER_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define ORBITER_PSCHMASK_PSC_MOD_TABLE_FIELD "Orbiter_pschmask.psc_mod"
#define ORBITER_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define ORBITER_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Orbiter_pschmask.psc_restrict"
#define ORBITER_PSCHMASK_FIRSTREGEN_FIELD "FirstRegen"
#define ORBITER_PSCHMASK_FIRSTREGEN_TABLE_FIELD "Orbiter_pschmask.FirstRegen"


#endif

