#ifndef __Define_InstallWizard_pschmask_H__
#define __Define_InstallWizard_pschmask_H__


#define INSTALLWIZARD_PSCHMASK_TABLE "InstallWizard_pschmask"
#define INSTALLWIZARD_PSCHMASK_PK_INSTALLWIZARD_FIELD "PK_InstallWizard"
#define INSTALLWIZARD_PSCHMASK_PK_INSTALLWIZARD_TABLE_FIELD "InstallWizard_pschmask.PK_InstallWizard"
#define INSTALLWIZARD_PSCHMASK_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define INSTALLWIZARD_PSCHMASK_FK_DEVICETEMPLATE_TABLE_FIELD "InstallWizard_pschmask.FK_DeviceTemplate"
#define INSTALLWIZARD_PSCHMASK_STEP_FIELD "Step"
#define INSTALLWIZARD_PSCHMASK_STEP_TABLE_FIELD "InstallWizard_pschmask.Step"
#define INSTALLWIZARD_PSCHMASK_DEFAULT_FIELD "Default"
#define INSTALLWIZARD_PSCHMASK_DEFAULT_TABLE_FIELD "InstallWizard_pschmask.Default"
#define INSTALLWIZARD_PSCHMASK_COMMENTS_FIELD "Comments"
#define INSTALLWIZARD_PSCHMASK_COMMENTS_TABLE_FIELD "InstallWizard_pschmask.Comments"
#define INSTALLWIZARD_PSCHMASK_PSC_ID_FIELD "psc_id"
#define INSTALLWIZARD_PSCHMASK_PSC_ID_TABLE_FIELD "InstallWizard_pschmask.psc_id"
#define INSTALLWIZARD_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define INSTALLWIZARD_PSCHMASK_PSC_BATCH_TABLE_FIELD "InstallWizard_pschmask.psc_batch"
#define INSTALLWIZARD_PSCHMASK_PSC_USER_FIELD "psc_user"
#define INSTALLWIZARD_PSCHMASK_PSC_USER_TABLE_FIELD "InstallWizard_pschmask.psc_user"
#define INSTALLWIZARD_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define INSTALLWIZARD_PSCHMASK_PSC_FROZEN_TABLE_FIELD "InstallWizard_pschmask.psc_frozen"
#define INSTALLWIZARD_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define INSTALLWIZARD_PSCHMASK_PSC_MOD_TABLE_FIELD "InstallWizard_pschmask.psc_mod"
#define INSTALLWIZARD_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define INSTALLWIZARD_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "InstallWizard_pschmask.psc_restrict"


#endif

