#ifndef __Define_PhoneLineType_pschmask_H__
#define __Define_PhoneLineType_pschmask_H__


#define PHONELINETYPE_PSCHMASK_TABLE "PhoneLineType_pschmask"
#define PHONELINETYPE_PSCHMASK_PK_PHONELINETYPE_FIELD "PK_PhoneLineType"
#define PHONELINETYPE_PSCHMASK_PK_PHONELINETYPE_TABLE_FIELD "PhoneLineType_pschmask.PK_PhoneLineType"
#define PHONELINETYPE_PSCHMASK_DESCRIPTION_FIELD "Description"
#define PHONELINETYPE_PSCHMASK_DESCRIPTION_TABLE_FIELD "PhoneLineType_pschmask.Description"
#define PHONELINETYPE_PSCHMASK_DEFINE_FIELD "Define"
#define PHONELINETYPE_PSCHMASK_DEFINE_TABLE_FIELD "PhoneLineType_pschmask.Define"
#define PHONELINETYPE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define PHONELINETYPE_PSCHMASK_PSC_ID_TABLE_FIELD "PhoneLineType_pschmask.psc_id"
#define PHONELINETYPE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define PHONELINETYPE_PSCHMASK_PSC_BATCH_TABLE_FIELD "PhoneLineType_pschmask.psc_batch"
#define PHONELINETYPE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define PHONELINETYPE_PSCHMASK_PSC_USER_TABLE_FIELD "PhoneLineType_pschmask.psc_user"
#define PHONELINETYPE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define PHONELINETYPE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "PhoneLineType_pschmask.psc_frozen"
#define PHONELINETYPE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define PHONELINETYPE_PSCHMASK_PSC_MOD_TABLE_FIELD "PhoneLineType_pschmask.psc_mod"
#define PHONELINETYPE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define PHONELINETYPE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "PhoneLineType_pschmask.psc_restrict"


#endif

