#ifndef __Define_EventCategory_pschist_H__
#define __Define_EventCategory_pschist_H__


#define EVENTCATEGORY_PSCHIST_TABLE "EventCategory_pschist"
#define EVENTCATEGORY_PSCHIST_PK_EVENTCATEGORY_FIELD "PK_EventCategory"
#define EVENTCATEGORY_PSCHIST_PK_EVENTCATEGORY_TABLE_FIELD "EventCategory_pschist.PK_EventCategory"
#define EVENTCATEGORY_PSCHIST_FK_EVENTCATEGORY_PARENT_FIELD "FK_EventCategory_Parent"
#define EVENTCATEGORY_PSCHIST_FK_EVENTCATEGORY_PARENT_TABLE_FIELD "EventCategory_pschist.FK_EventCategory_Parent"
#define EVENTCATEGORY_PSCHIST_DESCRIPTION_FIELD "Description"
#define EVENTCATEGORY_PSCHIST_DESCRIPTION_TABLE_FIELD "EventCategory_pschist.Description"
#define EVENTCATEGORY_PSCHIST_PSC_ID_FIELD "psc_id"
#define EVENTCATEGORY_PSCHIST_PSC_ID_TABLE_FIELD "EventCategory_pschist.psc_id"
#define EVENTCATEGORY_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define EVENTCATEGORY_PSCHIST_PSC_BATCH_TABLE_FIELD "EventCategory_pschist.psc_batch"
#define EVENTCATEGORY_PSCHIST_PSC_USER_FIELD "psc_user"
#define EVENTCATEGORY_PSCHIST_PSC_USER_TABLE_FIELD "EventCategory_pschist.psc_user"
#define EVENTCATEGORY_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define EVENTCATEGORY_PSCHIST_PSC_FROZEN_TABLE_FIELD "EventCategory_pschist.psc_frozen"
#define EVENTCATEGORY_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define EVENTCATEGORY_PSCHIST_PSC_MOD_TABLE_FIELD "EventCategory_pschist.psc_mod"
#define EVENTCATEGORY_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define EVENTCATEGORY_PSCHIST_PSC_TOC_TABLE_FIELD "EventCategory_pschist.psc_toc"
#define EVENTCATEGORY_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define EVENTCATEGORY_PSCHIST_PSC_RESTRICT_TABLE_FIELD "EventCategory_pschist.psc_restrict"


#endif

