#ifndef __Define_DeviceGroup_pschist_H__
#define __Define_DeviceGroup_pschist_H__


#define DEVICEGROUP_PSCHIST_TABLE "DeviceGroup_pschist"
#define DEVICEGROUP_PSCHIST_PK_DEVICEGROUP_FIELD "PK_DeviceGroup"
#define DEVICEGROUP_PSCHIST_PK_DEVICEGROUP_TABLE_FIELD "DeviceGroup_pschist.PK_DeviceGroup"
#define DEVICEGROUP_PSCHIST_FK_DEVICEGROUP_PARENT_FIELD "FK_DeviceGroup_Parent"
#define DEVICEGROUP_PSCHIST_FK_DEVICEGROUP_PARENT_TABLE_FIELD "DeviceGroup_pschist.FK_DeviceGroup_Parent"
#define DEVICEGROUP_PSCHIST_FK_INSTALLATION_FIELD "FK_Installation"
#define DEVICEGROUP_PSCHIST_FK_INSTALLATION_TABLE_FIELD "DeviceGroup_pschist.FK_Installation"
#define DEVICEGROUP_PSCHIST_DESCRIPTION_FIELD "Description"
#define DEVICEGROUP_PSCHIST_DESCRIPTION_TABLE_FIELD "DeviceGroup_pschist.Description"
#define DEVICEGROUP_PSCHIST_TYPE_FIELD "Type"
#define DEVICEGROUP_PSCHIST_TYPE_TABLE_FIELD "DeviceGroup_pschist.Type"
#define DEVICEGROUP_PSCHIST_PSC_ID_FIELD "psc_id"
#define DEVICEGROUP_PSCHIST_PSC_ID_TABLE_FIELD "DeviceGroup_pschist.psc_id"
#define DEVICEGROUP_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DEVICEGROUP_PSCHIST_PSC_BATCH_TABLE_FIELD "DeviceGroup_pschist.psc_batch"
#define DEVICEGROUP_PSCHIST_PSC_USER_FIELD "psc_user"
#define DEVICEGROUP_PSCHIST_PSC_USER_TABLE_FIELD "DeviceGroup_pschist.psc_user"
#define DEVICEGROUP_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICEGROUP_PSCHIST_PSC_FROZEN_TABLE_FIELD "DeviceGroup_pschist.psc_frozen"
#define DEVICEGROUP_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DEVICEGROUP_PSCHIST_PSC_MOD_TABLE_FIELD "DeviceGroup_pschist.psc_mod"
#define DEVICEGROUP_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DEVICEGROUP_PSCHIST_PSC_TOC_TABLE_FIELD "DeviceGroup_pschist.psc_toc"
#define DEVICEGROUP_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICEGROUP_PSCHIST_PSC_RESTRICT_TABLE_FIELD "DeviceGroup_pschist.psc_restrict"


#endif

