#ifndef __Define_DeviceCategory_Event_pschist_H__
#define __Define_DeviceCategory_Event_pschist_H__


#define DEVICECATEGORY_EVENT_PSCHIST_TABLE "DeviceCategory_Event_pschist"
#define DEVICECATEGORY_EVENT_PSCHIST_FK_DEVICECATEGORY_FIELD "FK_DeviceCategory"
#define DEVICECATEGORY_EVENT_PSCHIST_FK_DEVICECATEGORY_TABLE_FIELD "DeviceCategory_Event_pschist.FK_DeviceCategory"
#define DEVICECATEGORY_EVENT_PSCHIST_FK_EVENT_FIELD "FK_Event"
#define DEVICECATEGORY_EVENT_PSCHIST_FK_EVENT_TABLE_FIELD "DeviceCategory_Event_pschist.FK_Event"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_ID_FIELD "psc_id"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_ID_TABLE_FIELD "DeviceCategory_Event_pschist.psc_id"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_BATCH_TABLE_FIELD "DeviceCategory_Event_pschist.psc_batch"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_USER_FIELD "psc_user"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_USER_TABLE_FIELD "DeviceCategory_Event_pschist.psc_user"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_FROZEN_TABLE_FIELD "DeviceCategory_Event_pschist.psc_frozen"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_MOD_TABLE_FIELD "DeviceCategory_Event_pschist.psc_mod"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_TOC_TABLE_FIELD "DeviceCategory_Event_pschist.psc_toc"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define DEVICECATEGORY_EVENT_PSCHIST_PSC_RESTRICT_TABLE_FIELD "DeviceCategory_Event_pschist.psc_restrict"


#endif

