#ifndef __Define_PackageType_pschist_H__
#define __Define_PackageType_pschist_H__


#define PACKAGETYPE_PSCHIST_TABLE "PackageType_pschist"
#define PACKAGETYPE_PSCHIST_PK_PACKAGETYPE_FIELD "PK_PackageType"
#define PACKAGETYPE_PSCHIST_PK_PACKAGETYPE_TABLE_FIELD "PackageType_pschist.PK_PackageType"
#define PACKAGETYPE_PSCHIST_DESCRIPTION_FIELD "Description"
#define PACKAGETYPE_PSCHIST_DESCRIPTION_TABLE_FIELD "PackageType_pschist.Description"
#define PACKAGETYPE_PSCHIST_DEFINE_FIELD "Define"
#define PACKAGETYPE_PSCHIST_DEFINE_TABLE_FIELD "PackageType_pschist.Define"
#define PACKAGETYPE_PSCHIST_PSC_ID_FIELD "psc_id"
#define PACKAGETYPE_PSCHIST_PSC_ID_TABLE_FIELD "PackageType_pschist.psc_id"
#define PACKAGETYPE_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define PACKAGETYPE_PSCHIST_PSC_BATCH_TABLE_FIELD "PackageType_pschist.psc_batch"
#define PACKAGETYPE_PSCHIST_PSC_USER_FIELD "psc_user"
#define PACKAGETYPE_PSCHIST_PSC_USER_TABLE_FIELD "PackageType_pschist.psc_user"
#define PACKAGETYPE_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGETYPE_PSCHIST_PSC_FROZEN_TABLE_FIELD "PackageType_pschist.psc_frozen"
#define PACKAGETYPE_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define PACKAGETYPE_PSCHIST_PSC_MOD_TABLE_FIELD "PackageType_pschist.psc_mod"
#define PACKAGETYPE_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define PACKAGETYPE_PSCHIST_PSC_TOC_TABLE_FIELD "PackageType_pschist.psc_toc"
#define PACKAGETYPE_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define PACKAGETYPE_PSCHIST_PSC_RESTRICT_TABLE_FIELD "PackageType_pschist.psc_restrict"


#endif

