#ifndef __Define_StabilityStatus_pschmask_H__
#define __Define_StabilityStatus_pschmask_H__


#define STABILITYSTATUS_PSCHMASK_TABLE "StabilityStatus_pschmask"
#define STABILITYSTATUS_PSCHMASK_PK_STABILITYSTATUS_FIELD "PK_StabilityStatus"
#define STABILITYSTATUS_PSCHMASK_PK_STABILITYSTATUS_TABLE_FIELD "StabilityStatus_pschmask.PK_StabilityStatus"
#define STABILITYSTATUS_PSCHMASK_DESCRIPTION_FIELD "Description"
#define STABILITYSTATUS_PSCHMASK_DESCRIPTION_TABLE_FIELD "StabilityStatus_pschmask.Description"
#define STABILITYSTATUS_PSCHMASK_DEFINE_FIELD "Define"
#define STABILITYSTATUS_PSCHMASK_DEFINE_TABLE_FIELD "StabilityStatus_pschmask.Define"
#define STABILITYSTATUS_PSCHMASK_PSC_ID_FIELD "psc_id"
#define STABILITYSTATUS_PSCHMASK_PSC_ID_TABLE_FIELD "StabilityStatus_pschmask.psc_id"
#define STABILITYSTATUS_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define STABILITYSTATUS_PSCHMASK_PSC_BATCH_TABLE_FIELD "StabilityStatus_pschmask.psc_batch"
#define STABILITYSTATUS_PSCHMASK_PSC_USER_FIELD "psc_user"
#define STABILITYSTATUS_PSCHMASK_PSC_USER_TABLE_FIELD "StabilityStatus_pschmask.psc_user"
#define STABILITYSTATUS_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define STABILITYSTATUS_PSCHMASK_PSC_FROZEN_TABLE_FIELD "StabilityStatus_pschmask.psc_frozen"
#define STABILITYSTATUS_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define STABILITYSTATUS_PSCHMASK_PSC_MOD_TABLE_FIELD "StabilityStatus_pschmask.psc_mod"
#define STABILITYSTATUS_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define STABILITYSTATUS_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "StabilityStatus_pschmask.psc_restrict"


#endif

