#ifndef __Define_Room_Users_pschmask_H__
#define __Define_Room_Users_pschmask_H__


#define ROOM_USERS_PSCHMASK_TABLE "Room_Users_pschmask"
#define ROOM_USERS_PSCHMASK_PK_ROOM_USERS_FIELD "PK_Room_Users"
#define ROOM_USERS_PSCHMASK_PK_ROOM_USERS_TABLE_FIELD "Room_Users_pschmask.PK_Room_Users"
#define ROOM_USERS_PSCHMASK_FK_ROOM_FIELD "FK_Room"
#define ROOM_USERS_PSCHMASK_FK_ROOM_TABLE_FIELD "Room_Users_pschmask.FK_Room"
#define ROOM_USERS_PSCHMASK_FK_USERS_FIELD "FK_Users"
#define ROOM_USERS_PSCHMASK_FK_USERS_TABLE_FIELD "Room_Users_pschmask.FK_Users"
#define ROOM_USERS_PSCHMASK_FK_ORBITER_FIELD "FK_Orbiter"
#define ROOM_USERS_PSCHMASK_FK_ORBITER_TABLE_FIELD "Room_Users_pschmask.FK_Orbiter"
#define ROOM_USERS_PSCHMASK_PSC_ID_FIELD "psc_id"
#define ROOM_USERS_PSCHMASK_PSC_ID_TABLE_FIELD "Room_Users_pschmask.psc_id"
#define ROOM_USERS_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define ROOM_USERS_PSCHMASK_PSC_BATCH_TABLE_FIELD "Room_Users_pschmask.psc_batch"
#define ROOM_USERS_PSCHMASK_PSC_USER_FIELD "psc_user"
#define ROOM_USERS_PSCHMASK_PSC_USER_TABLE_FIELD "Room_Users_pschmask.psc_user"
#define ROOM_USERS_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define ROOM_USERS_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Room_Users_pschmask.psc_frozen"
#define ROOM_USERS_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define ROOM_USERS_PSCHMASK_PSC_MOD_TABLE_FIELD "Room_Users_pschmask.psc_mod"
#define ROOM_USERS_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define ROOM_USERS_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Room_Users_pschmask.psc_restrict"


#endif

