#ifndef __Define_Criteria_pschmask_H__
#define __Define_Criteria_pschmask_H__


#define CRITERIA_PSCHMASK_TABLE "Criteria_pschmask"
#define CRITERIA_PSCHMASK_PK_CRITERIA_FIELD "PK_Criteria"
#define CRITERIA_PSCHMASK_PK_CRITERIA_TABLE_FIELD "Criteria_pschmask.PK_Criteria"
#define CRITERIA_PSCHMASK_FK_CRITERIAPARMNESTING_FIELD "FK_CriteriaParmNesting"
#define CRITERIA_PSCHMASK_FK_CRITERIAPARMNESTING_TABLE_FIELD "Criteria_pschmask.FK_CriteriaParmNesting"
#define CRITERIA_PSCHMASK_FK_CRITERIALIST_FIELD "FK_CriteriaList"
#define CRITERIA_PSCHMASK_FK_CRITERIALIST_TABLE_FIELD "Criteria_pschmask.FK_CriteriaList"
#define CRITERIA_PSCHMASK_FK_INSTALLATION_FIELD "FK_Installation"
#define CRITERIA_PSCHMASK_FK_INSTALLATION_TABLE_FIELD "Criteria_pschmask.FK_Installation"
#define CRITERIA_PSCHMASK_DESCRIPTION_FIELD "Description"
#define CRITERIA_PSCHMASK_DESCRIPTION_TABLE_FIELD "Criteria_pschmask.Description"
#define CRITERIA_PSCHMASK_DEFINE_FIELD "Define"
#define CRITERIA_PSCHMASK_DEFINE_TABLE_FIELD "Criteria_pschmask.Define"
#define CRITERIA_PSCHMASK_PSC_ID_FIELD "psc_id"
#define CRITERIA_PSCHMASK_PSC_ID_TABLE_FIELD "Criteria_pschmask.psc_id"
#define CRITERIA_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define CRITERIA_PSCHMASK_PSC_BATCH_TABLE_FIELD "Criteria_pschmask.psc_batch"
#define CRITERIA_PSCHMASK_PSC_USER_FIELD "psc_user"
#define CRITERIA_PSCHMASK_PSC_USER_TABLE_FIELD "Criteria_pschmask.psc_user"
#define CRITERIA_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define CRITERIA_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Criteria_pschmask.psc_frozen"
#define CRITERIA_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define CRITERIA_PSCHMASK_PSC_MOD_TABLE_FIELD "Criteria_pschmask.psc_mod"
#define CRITERIA_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define CRITERIA_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Criteria_pschmask.psc_restrict"


#endif

