#ifndef __Define_Manufacturer_pschmask_H__
#define __Define_Manufacturer_pschmask_H__


#define MANUFACTURER_PSCHMASK_TABLE "Manufacturer_pschmask"
#define MANUFACTURER_PSCHMASK_PK_MANUFACTURER_FIELD "PK_Manufacturer"
#define MANUFACTURER_PSCHMASK_PK_MANUFACTURER_TABLE_FIELD "Manufacturer_pschmask.PK_Manufacturer"
#define MANUFACTURER_PSCHMASK_DESCRIPTION_FIELD "Description"
#define MANUFACTURER_PSCHMASK_DESCRIPTION_TABLE_FIELD "Manufacturer_pschmask.Description"
#define MANUFACTURER_PSCHMASK_IRFREQUENCY_FIELD "IRFrequency"
#define MANUFACTURER_PSCHMASK_IRFREQUENCY_TABLE_FIELD "Manufacturer_pschmask.IRFrequency"
#define MANUFACTURER_PSCHMASK_PSC_ID_FIELD "psc_id"
#define MANUFACTURER_PSCHMASK_PSC_ID_TABLE_FIELD "Manufacturer_pschmask.psc_id"
#define MANUFACTURER_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define MANUFACTURER_PSCHMASK_PSC_BATCH_TABLE_FIELD "Manufacturer_pschmask.psc_batch"
#define MANUFACTURER_PSCHMASK_PSC_USER_FIELD "psc_user"
#define MANUFACTURER_PSCHMASK_PSC_USER_TABLE_FIELD "Manufacturer_pschmask.psc_user"
#define MANUFACTURER_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define MANUFACTURER_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Manufacturer_pschmask.psc_frozen"
#define MANUFACTURER_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define MANUFACTURER_PSCHMASK_PSC_MOD_TABLE_FIELD "Manufacturer_pschmask.psc_mod"
#define MANUFACTURER_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define MANUFACTURER_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Manufacturer_pschmask.psc_restrict"


#endif

