#ifndef __Define_HorizAlignment_pschmask_H__
#define __Define_HorizAlignment_pschmask_H__


#define HORIZALIGNMENT_PSCHMASK_TABLE "HorizAlignment_pschmask"
#define HORIZALIGNMENT_PSCHMASK_PK_HORIZALIGNMENT_FIELD "PK_HorizAlignment"
#define HORIZALIGNMENT_PSCHMASK_PK_HORIZALIGNMENT_TABLE_FIELD "HorizAlignment_pschmask.PK_HorizAlignment"
#define HORIZALIGNMENT_PSCHMASK_DESCRIPTION_FIELD "Description"
#define HORIZALIGNMENT_PSCHMASK_DESCRIPTION_TABLE_FIELD "HorizAlignment_pschmask.Description"
#define HORIZALIGNMENT_PSCHMASK_DEFINE_FIELD "Define"
#define HORIZALIGNMENT_PSCHMASK_DEFINE_TABLE_FIELD "HorizAlignment_pschmask.Define"
#define HORIZALIGNMENT_PSCHMASK_PSC_ID_FIELD "psc_id"
#define HORIZALIGNMENT_PSCHMASK_PSC_ID_TABLE_FIELD "HorizAlignment_pschmask.psc_id"
#define HORIZALIGNMENT_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define HORIZALIGNMENT_PSCHMASK_PSC_BATCH_TABLE_FIELD "HorizAlignment_pschmask.psc_batch"
#define HORIZALIGNMENT_PSCHMASK_PSC_USER_FIELD "psc_user"
#define HORIZALIGNMENT_PSCHMASK_PSC_USER_TABLE_FIELD "HorizAlignment_pschmask.psc_user"
#define HORIZALIGNMENT_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define HORIZALIGNMENT_PSCHMASK_PSC_FROZEN_TABLE_FIELD "HorizAlignment_pschmask.psc_frozen"
#define HORIZALIGNMENT_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define HORIZALIGNMENT_PSCHMASK_PSC_MOD_TABLE_FIELD "HorizAlignment_pschmask.psc_mod"
#define HORIZALIGNMENT_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define HORIZALIGNMENT_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "HorizAlignment_pschmask.psc_restrict"


#endif

