#ifndef __Define_VertAlignment_pschist_H__
#define __Define_VertAlignment_pschist_H__


#define VERTALIGNMENT_PSCHIST_TABLE "VertAlignment_pschist"
#define VERTALIGNMENT_PSCHIST_PK_VERTALIGNMENT_FIELD "PK_VertAlignment"
#define VERTALIGNMENT_PSCHIST_PK_VERTALIGNMENT_TABLE_FIELD "VertAlignment_pschist.PK_VertAlignment"
#define VERTALIGNMENT_PSCHIST_DESCRIPTION_FIELD "Description"
#define VERTALIGNMENT_PSCHIST_DESCRIPTION_TABLE_FIELD "VertAlignment_pschist.Description"
#define VERTALIGNMENT_PSCHIST_DEFINE_FIELD "Define"
#define VERTALIGNMENT_PSCHIST_DEFINE_TABLE_FIELD "VertAlignment_pschist.Define"
#define VERTALIGNMENT_PSCHIST_PSC_ID_FIELD "psc_id"
#define VERTALIGNMENT_PSCHIST_PSC_ID_TABLE_FIELD "VertAlignment_pschist.psc_id"
#define VERTALIGNMENT_PSCHIST_PSC_BATCH_FIELD "psc_batch"
#define VERTALIGNMENT_PSCHIST_PSC_BATCH_TABLE_FIELD "VertAlignment_pschist.psc_batch"
#define VERTALIGNMENT_PSCHIST_PSC_USER_FIELD "psc_user"
#define VERTALIGNMENT_PSCHIST_PSC_USER_TABLE_FIELD "VertAlignment_pschist.psc_user"
#define VERTALIGNMENT_PSCHIST_PSC_FROZEN_FIELD "psc_frozen"
#define VERTALIGNMENT_PSCHIST_PSC_FROZEN_TABLE_FIELD "VertAlignment_pschist.psc_frozen"
#define VERTALIGNMENT_PSCHIST_PSC_MOD_FIELD "psc_mod"
#define VERTALIGNMENT_PSCHIST_PSC_MOD_TABLE_FIELD "VertAlignment_pschist.psc_mod"
#define VERTALIGNMENT_PSCHIST_PSC_TOC_FIELD "psc_toc"
#define VERTALIGNMENT_PSCHIST_PSC_TOC_TABLE_FIELD "VertAlignment_pschist.psc_toc"
#define VERTALIGNMENT_PSCHIST_PSC_RESTRICT_FIELD "psc_restrict"
#define VERTALIGNMENT_PSCHIST_PSC_RESTRICT_TABLE_FIELD "VertAlignment_pschist.psc_restrict"


#endif

