#ifndef __Define_Installation_Users_pschmask_H__
#define __Define_Installation_Users_pschmask_H__


#define INSTALLATION_USERS_PSCHMASK_TABLE "Installation_Users_pschmask"
#define INSTALLATION_USERS_PSCHMASK_FK_INSTALLATION_FIELD "FK_Installation"
#define INSTALLATION_USERS_PSCHMASK_FK_INSTALLATION_TABLE_FIELD "Installation_Users_pschmask.FK_Installation"
#define INSTALLATION_USERS_PSCHMASK_FK_USERS_FIELD "FK_Users"
#define INSTALLATION_USERS_PSCHMASK_FK_USERS_TABLE_FIELD "Installation_Users_pschmask.FK_Users"
#define INSTALLATION_USERS_PSCHMASK_USERCANMODIFYINSTALLATION_FIELD "userCanModifyInstallation"
#define INSTALLATION_USERS_PSCHMASK_USERCANMODIFYINSTALLATION_TABLE_FIELD "Installation_Users_pschmask.userCanModifyInstallation"
#define INSTALLATION_USERS_PSCHMASK_USERCANCHANGEHOUSEMODE_FIELD "userCanChangeHouseMode"
#define INSTALLATION_USERS_PSCHMASK_USERCANCHANGEHOUSEMODE_TABLE_FIELD "Installation_Users_pschmask.userCanChangeHouseMode"
#define INSTALLATION_USERS_PSCHMASK_PSC_ID_FIELD "psc_id"
#define INSTALLATION_USERS_PSCHMASK_PSC_ID_TABLE_FIELD "Installation_Users_pschmask.psc_id"
#define INSTALLATION_USERS_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define INSTALLATION_USERS_PSCHMASK_PSC_BATCH_TABLE_FIELD "Installation_Users_pschmask.psc_batch"
#define INSTALLATION_USERS_PSCHMASK_PSC_USER_FIELD "psc_user"
#define INSTALLATION_USERS_PSCHMASK_PSC_USER_TABLE_FIELD "Installation_Users_pschmask.psc_user"
#define INSTALLATION_USERS_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define INSTALLATION_USERS_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Installation_Users_pschmask.psc_frozen"
#define INSTALLATION_USERS_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define INSTALLATION_USERS_PSCHMASK_PSC_MOD_TABLE_FIELD "Installation_Users_pschmask.psc_mod"
#define INSTALLATION_USERS_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define INSTALLATION_USERS_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Installation_Users_pschmask.psc_restrict"


#endif

