#ifndef __Define_Command_Pipe_pschmask_H__
#define __Define_Command_Pipe_pschmask_H__


#define COMMAND_PIPE_PSCHMASK_TABLE "Command_Pipe_pschmask"
#define COMMAND_PIPE_PSCHMASK_FK_COMMAND_FIELD "FK_Command"
#define COMMAND_PIPE_PSCHMASK_FK_COMMAND_TABLE_FIELD "Command_Pipe_pschmask.FK_Command"
#define COMMAND_PIPE_PSCHMASK_FK_PIPE_FIELD "FK_Pipe"
#define COMMAND_PIPE_PSCHMASK_FK_PIPE_TABLE_FIELD "Command_Pipe_pschmask.FK_Pipe"
#define COMMAND_PIPE_PSCHMASK_PSC_ID_FIELD "psc_id"
#define COMMAND_PIPE_PSCHMASK_PSC_ID_TABLE_FIELD "Command_Pipe_pschmask.psc_id"
#define COMMAND_PIPE_PSCHMASK_PSC_BATCH_FIELD "psc_batch"
#define COMMAND_PIPE_PSCHMASK_PSC_BATCH_TABLE_FIELD "Command_Pipe_pschmask.psc_batch"
#define COMMAND_PIPE_PSCHMASK_PSC_USER_FIELD "psc_user"
#define COMMAND_PIPE_PSCHMASK_PSC_USER_TABLE_FIELD "Command_Pipe_pschmask.psc_user"
#define COMMAND_PIPE_PSCHMASK_PSC_FROZEN_FIELD "psc_frozen"
#define COMMAND_PIPE_PSCHMASK_PSC_FROZEN_TABLE_FIELD "Command_Pipe_pschmask.psc_frozen"
#define COMMAND_PIPE_PSCHMASK_PSC_MOD_FIELD "psc_mod"
#define COMMAND_PIPE_PSCHMASK_PSC_MOD_TABLE_FIELD "Command_Pipe_pschmask.psc_mod"
#define COMMAND_PIPE_PSCHMASK_PSC_RESTRICT_FIELD "psc_restrict"
#define COMMAND_PIPE_PSCHMASK_PSC_RESTRICT_TABLE_FIELD "Command_Pipe_pschmask.psc_restrict"


#endif

