Document: pluto-marbella-database
Title: Debian pluto-marbella-database Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-marbella-database is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-marbella-database/pluto-marbella-database.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-marbella-database/pluto-marbella-database.ps.gz

Format: text
Files: /usr/share/doc/pluto-marbella-database/pluto-marbella-database.text.gz

Format: HTML
Index: /usr/share/doc/pluto-marbella-database/html/index.html
Files: /usr/share/doc/pluto-marbella-database/html/*.html
