Document: pluto-vipshared
Title: Debian pluto-vipshared Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-vipshared is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-vipshared/pluto-vipshared.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-vipshared/pluto-vipshared.ps.gz

Format: text
Files: /usr/share/doc/pluto-vipshared/pluto-vipshared.text.gz

Format: HTML
Index: /usr/share/doc/pluto-vipshared/html/index.html
Files: /usr/share/doc/pluto-vipshared/html/*.html
