Document: qorbiter
Title: Debian qorbiter Manual
Author: <insert document author here>
Abstract: This manual describes what qorbiter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qorbiter/qorbiter.sgml.gz

Format: postscript
Files: /usr/share/doc/qorbiter/qorbiter.ps.gz

Format: text
Files: /usr/share/doc/qorbiter/qorbiter.text.gz

Format: HTML
Index: /usr/share/doc/qorbiter/html/index.html
Files: /usr/share/doc/qorbiter/html/*.html
