//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PlutoVIP.rc
//
#define IDM_ABOUTBOX                    0x10
#define IDD_ABOUTBOX                    17
#define IDS_ABOUTBOX                    18
#define IDD_TASKBAR_DIALOG              19
#define IDD_PLUTOVIP_MAIN_DIALOG        20
#define IDS_ZERO_DIMENSION              21
#define IDD_APPBAR                      22
#define IDS_ERROR_AUTOHIDE              23
#define IDS_ERROR_NOT_HIDDEN            24
#define IDS_ERROR_SET_AUTOHIDE          25
#define IDR_MAINFRAME                   26
#define IDR_EPIC_BUTTON_MENU            27
#define IDR_PLUTO_CONTEXT_MENT          28
#define IDR_PLUTO_CONTEXT_MENU          28
#define IDR_POPUP_TRAY_ICON             29
#define IDR_MAIN_MENU                   30
#define IDD_HIGHLIGHT                   31
#define IDD_PAGE_INTRODUCTION           32
#define IDD_PAGE_INTERNET               33
#define IDD_PAGE_PANEL_POSITION         34
#define IDD_PAGE_DATABASE               35
#define IDD_PAGE_TERMINALS              36
#define IDD_UPDATE                      37
#define IDB_DUMMY_BITMAP                39
#define IDD_RECORD_ERROR                40
#define IDB_CUSTOMER                    41
#define IDB_STATE                       42
#define IDD_ADD_VISIT                   43
#define IDD_ADD_PURCHASE                44
#define IDD_REDEEM_VISIT                45
#define IDD_REDEEM_PURCHASE             46
#define IDR_MAINFRAME_16X16_TRUE        52
#define IDR_MAINFRAME_32X32_TRUE        53
#define IDR_MAINFRAME_48X48_TRUE        54
#define IDR_MAINFRAME_48X48             55
#define IDC_REGISTER                    1000
#define IDC_START                       1001
#define IDC_UNREGISTER                  1002
#define IDC_CUSTOMER                    1003
#define IDC_AUTOHIDE                    1004
#define IDC_CHECK1                      1005
#define IDC_COPY                        1006
#define IDC_CLIENT                      1007
#define IDC_ONTOP                       1008
#define IDC_LIST1                       1009
#define IDC_INFORMATTION                1010
#define IDC_NICKNAME                    1011
#define IDC_CREDIT                      1012
#define IDC_INTERNET_CONNECTION         1013
#define IDC_RADIO2                      1014
#define IDC_INTERNET_DIALUP             1014
#define IDC_RADIO3                      1015
#define IDC_INTERNET_NO_ACCESS          1015
#define IDC_CONNECTION                  1016
#define IDC_RADIO4                      1017
#define IDC_INTERNET_WHEN               1018
#define IDC_RADIO8                      1019
#define IDC_RADIO5                      1020
#define IDC_RADIO6                      1021
#define IDC_RADIO7                      1024
#define IDC_NEW_CLIENTS_SIDE            1025
#define IDC_CLIENT_NEW_TIME             1026
#define IDC_ADD                         1028
#define IDC_ACTIVE_CLIENTS_SIDE         1029
#define IDC_REMOVE                      1030
#define IDC_RENAME                      1032
#define IDC_RADIO9                      1033
#define IDC_SWITCH                      1034
#define IDC_RECENT_CLIENTS_SIDE         1035
#define IDC_WHICH_ONE                   1036
#define IDC_CLIENT_RECENT_TIME          1037
#define IDC_WHAT_DO                     1038
#define IDC_OTHER_TERMINALS             1039
#define IDC_SERVER                      1040
#define IDC_FIND                        1041
#define IDC_DIRECTORY                   1042
#define IDC_BROWSE                      1043
#define IDC_NEW_APPEARANCE_VISIBLE      1044
#define IDC_UPDATE_PROGRESS             1045
#define IDC_ACTIVE_APPEARANCE_VISIBLE   1045
#define IDC_STATUS                      1046
#define IDC_RECENT_APPEARANCE_VISIBLE   1046
#define IDC_NEW_APPEARANCE_AUTOHIDE     1047
#define IDC_NEW_APPEARANCE_INVISIBLE    1048
#define IDC_ACTIVE_APPEARANCE_AUTOHIDE  1049
#define IDC_OTHER_TERMINALS2            1049
#define IDC_ACTIVE_APPEARANCE_INVISIBLE 1050
#define IDC_FULLNAME                    1050
#define IDC_RECENT_APPEARANCE_AUTOHIDE  1051
#define IDC_CHANGE_STATE                1051
#define IDC_RECENT_APPEARANCE_INVISIBLE 1052
#define IDC_COMMENT                     1052
#define IDC_TASK                        1053
#define IDC_PICTURE                     1054
#define IDC_ADDRESS                     1055
#define IDC_CITY                        1056
#define IDC_STATE                       1057
#define IDC_ZIP                         1058
#define IDC_MAC_ADDRESS                 1060
#define IDC_ACTION                      1061
#define IDC_VISIT                       1062
#define IDC_PURCHASE                    1063
#define IDC_REDEEM_VISIT                1064
#define IDC_REDEEM_VISIT_DESCRIPTION    1065
#define IDC_REDEEM_PURCHASE             1066
#define IDC_REDEEM_PURCHASE_DESCRIPTION 1067
#define IDC_STORE_CUSTOMER_ID           1069
#define IDC_CUSTOMER_EMAIL              1070
#define IDC_BDATE_GENDER                1071
#define IDC_PHONES                      1072
#define IDC_EXTRA                       1073
#define ID_MENUITEM32771                32771
#define ID_APPBAR_ALWAYSONTOP           32772
#define ID_APPBAR_AUTOHIDE              32773
#define ID_APPBAR_ABOUTAPPBAR           32774
#define ID_APPBAR_EXIT                  32775
#define ID_TRAY_ABOUT                   32776
#define ID_TRAY_PREFERENCES             32777
#define ID_TRAY_EXIT                    32778
#define ID_TRAY_RESTORE                 32779
#define ID_MAIN_PREFERENCES             32780
#define ID_HELP_ABOUT                   32781
#define ID_HELP_CONTENTS                32782
#define ID_HELP_PLUTOVIPONTHEWEB_FREESTUFF 32783
#define ID_HELP_PLUTOVIPONTHEWEB_PRODUCTNEWS 32784
#define ID_HELP_PLUTOVIPONTHEWEB_FREQUENTLYASKEDQUESTION 32785
#define ID_HELP_PLUTOVIPONTHEWEB_ONLINESUPPORT 32786
#define ID_HELP_PLUTOVIPONTHEWEB_PLUTOVIPHOMEPAGE 32787
#define ID_HELP_TIPOFTHEDAY             32788
#define ID_MAIN_EXIT                    32789
#define ID_HELP_CHECK_UPDATE            32790
#define ID_MAIN_MINIMIZED               32791
#define ID_CUSTOMER_NEW                 32792
#define ID_CUSTOMER_ACTIVE              32793
#define ID_CUSTOMER_RECENT              32794
#define ID_TASK_CHARGE_CUSTOMER         32795
#define ID_TASK_SEND_IMAGE              32796
#define ID_TASK_TASK3                   32797
#define ID_TASK_TASK4                   32798
#define ID_ACTION_ADDVISIT              32799
#define ID_ACTION_ADDPURCHASE           32800
#define ID_ACTION_REDEEMVISIT           32801
#define ID_ACTION_REDEEMPURCHASE        32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        56
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           1144
#endif
#endif
