ROOT = ..
CXXFLAGS = -Wall -g 
CPPFLAGS = -I$(ROOT)/ -I$(ROOT)/DCE -I$(ROOT)/VIPShared -I/usr/include/mysql -D_REENTRANT -D_GNU_SOURCE -D_DEVEL_X_DEFINES -DGENERATOR
LDFLAGS = -L$(ROOT)/lib 
LDLIBS = -lRACommon -lDCECommon -lPlutoUtils -lSerializeClass -lpthread -lmysqlclient_r #-lattr 
CXX = g++

#<-mkr_B_use_mysql_wrapper_b->
CPPFLAGS += -I/usr/include/mysql
LDFLAGS += -lmysqlclient_r
#<-mkr_B_use_mysql_wrapper_e->

#<-mkr_b_use_mysql_wrapper_b->
CPPFLAGS += -DUSE_MYSQL_WRAPPER
#<-mkr_b_use_mysql_wrapper_e->

sources = CommonFunctions.cpp Tribunerequests.cpp R_GetLineups.cpp \
	R_GetChannels.cpp R_GetDiffs.cpp ClientFunctions.cpp \
	Database.cpp Tribuneprocessor.cpp ServerManagement.cpp \
	MapManagement.cpp Tribune.cpp 
#	$(ROOT)/inotify/FileNotifier.cpp $(ROOT)/inotify/inotify_class.cpp

#new_thing = $(sources) TableInfo_SCVS.cpp

all: Tribune
#all: newthing

Tribune: $(sources:.cpp=.o)
	$(CXX) -o $@ $(call cpath,$+) $(LDFLAGS) $(LDLIBS) $(CPPFLAGS)
	cp $@ $(ROOT)/bin

#newthing: $(new_thing:.cpp=.o)
#	@echo "*** Something to do here ***"

clean: clean-recursive
	rm -f $(call cpath,$(sources:.cpp=.o) $(sources:.cpp=.d)) Tribune >/dev/null

include $(ROOT)/PlutoUtils/make.rules
-include $(sources:.cpp=.d)
