Document: squeezeboxserver
Title: Debian squeezeboxserver Manual
Author: <insert document author here>
Abstract: This manual describes what squeezeboxserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/squeezeboxserver/squeezeboxserver.sgml.gz

Format: postscript
Files: /usr/share/doc/squeezeboxserver/squeezeboxserver.ps.gz

Format: text
Files: /usr/share/doc/squeezeboxserver/squeezeboxserver.text.gz

Format: HTML
Index: /usr/share/doc/squeezeboxserver/html/index.html
Files: /usr/share/doc/squeezeboxserver/html/*.html
