Document: lmce-agocontrol-bridge
Title: Debian lmce-agocontrol-bridge Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-agocontrol-bridge is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-agocontrol-bridge/lmce-agocontrol-bridge.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-agocontrol-bridge/lmce-agocontrol-bridge.ps.gz

Format: text
Files: /usr/share/doc/lmce-agocontrol-bridge/lmce-agocontrol-bridge.text.gz

Format: HTML
Index: /usr/share/doc/lmce-agocontrol-bridge/html/index.html
Files: /usr/share/doc/lmce-agocontrol-bridge/html/*.html
