Document: lmce-game
Title: Debian lmce-game Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-game is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-game/lmce-game.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-game/lmce-game.ps.gz

Format: text
Files: /usr/share/doc/lmce-game/lmce-game.text.gz

Format: HTML
Index: /usr/share/doc/lmce-game/html/index.html
Files: /usr/share/doc/lmce-game/html/*.html
