Document: lmce-dhcpd-plugin
Title: Debian lmce-dhcpd-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-dhcpd-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-dhcpd-plugin/lmce-dhcpd-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-dhcpd-plugin/lmce-dhcpd-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-dhcpd-plugin/lmce-dhcpd-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-dhcpd-plugin/html/index.html
Files: /usr/share/doc/lmce-dhcpd-plugin/html/*.html
