Document: lmce-datagrid-plugin
Title: Debian lmce-datagrid-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-datagrid-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-datagrid-plugin/lmce-datagrid-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-datagrid-plugin/lmce-datagrid-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-datagrid-plugin/lmce-datagrid-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-datagrid-plugin/html/index.html
Files: /usr/share/doc/lmce-datagrid-plugin/html/*.html
