Document: lmce-base
Title: Debian lmce-base Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-base/lmce-base.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-base/lmce-base.ps.gz

Format: text
Files: /usr/share/doc/lmce-base/lmce-base.text.gz

Format: HTML
Index: /usr/share/doc/lmce-base/html/index.html
Files: /usr/share/doc/lmce-base/html/*.html
