Document: pluto-xine-player
Title: Debian pluto-xine-player Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-xine-player is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-xine-player/pluto-xine-player.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-xine-player/pluto-xine-player.ps.gz

Format: text
Files: /usr/share/doc/pluto-xine-player/pluto-xine-player.text.gz

Format: HTML
Index: /usr/share/doc/pluto-xine-player/html/index.html
Files: /usr/share/doc/pluto-xine-player/html/*.html
