Document: lmce-hulu-plugin
Title: Debian lmce-hulu-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-hulu-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-hulu-plugin/lmce-hulu-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-hulu-plugin/lmce-hulu-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-hulu-plugin/lmce-hulu-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-hulu-plugin/html/index.html
Files: /usr/share/doc/lmce-hulu-plugin/html/*.html
