#!/bin/make

none:


clean:


install:
	mkdir -p $(DESTDIR)/usr/pluto/orbiter/skins/Basic
	mkdir -p $(DESTDIR)/usr/pluto/orbiter/skins/BlueCrystal
	#mkdir -p $(DESTDIR)/usr/pluto/orbiter/skins/LinuxMCE
	mkdir -p $(DESTDIR)/usr/pluto/orbiter/skins/Slate
	mkdir -p $(DESTDIR)/usr/pluto/orbiter/skins/Titanium
	mkdir -p $(DESTDIR)/usr/pluto/orbiter/skins/UIta

	cp -avR ./Basic $(DESTDIR)/usr/pluto/orbiter/skins/ || true
	cp -avR ./BlueCrystal $(DESTDIR)/usr/pluto/orbiter/skins/ || true
	#cp -avR ./LinuxMCE $(DESTDIR)/usr/pluto/orbiter/skins/ || true
	cp -avR ./Slate $(DESTDIR)/usr/pluto/orbiter/skins/ || true
	cp -avR ./Titanium $(DESTDIR)/usr/pluto/orbiter/skins/ || true
	cp -avR ./UIta $(DESTDIR)/usr/pluto/orbiter/skins/ || true
