Document: pluto-proxy-orbiter
Title: Debian pluto-proxy-orbiter Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-proxy-orbiter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-proxy-orbiter/pluto-proxy-orbiter.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-proxy-orbiter/pluto-proxy-orbiter.ps.gz

Format: text
Files: /usr/share/doc/pluto-proxy-orbiter/pluto-proxy-orbiter.text.gz

Format: HTML
Index: /usr/share/doc/pluto-proxy-orbiter/html/index.html
Files: /usr/share/doc/pluto-proxy-orbiter/html/*.html
