#! /bin/sh /usr/share/dpatch/dpatch-run
## 13-warning-cleanup.dpatch by Mario Limonciello <superm1@ubuntu.com>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: Remove build time debug messages for kernel drivers

@DPATCH@
Index: lirc-0.8.5/drivers/lirc_serial/lirc_serial.c
===================================================================
--- lirc-0.8.5.orig/drivers/lirc_serial/lirc_serial.c	2009-03-15 04:34:00.000000000 -0500
+++ lirc-0.8.5/drivers/lirc_serial/lirc_serial.c	2009-06-15 01:04:29.000000000 -0500
@@ -62,15 +62,6 @@
 
 #include <linux/autoconf.h>
 
-#if defined(CONFIG_SERIAL) || defined(CONFIG_SERIAL_8250)
-#warning "******************************************"
-#warning " Your serial port driver is compiled into "
-#warning " the kernel. You will have to release the "
-#warning " port you want to use for LIRC with:      "
-#warning "    setserial /dev/ttySx uart none	"
-#warning "******************************************"
-#endif
-
 #include <linux/module.h>
 #include <linux/errno.h>
 #include <linux/signal.h>
Index: lirc-0.8.5/drivers/lirc_sir/lirc_sir.c
===================================================================
--- lirc-0.8.5.orig/drivers/lirc_sir/lirc_sir.c	2009-03-08 14:13:45.000000000 -0500
+++ lirc-0.8.5/drivers/lirc_sir/lirc_sir.c	2009-06-15 01:51:45.000000000 -0500
@@ -46,16 +46,6 @@
 #endif
 
 #include <linux/autoconf.h>
-#if !defined(CONFIG_SERIAL_MODULE)
-#if !defined(LIRC_ON_SA1100)
-#warning "******************************************"
-#warning " Your serial port driver is compiled into "
-#warning " the kernel. You will have to release the "
-#warning " port you want to use for LIRC with:      "
-#warning "    setserial /dev/ttySx uart none        "
-#warning "******************************************"
-#endif
-#endif
 
 #include <linux/sched.h>
 #include <linux/errno.h>
