Document: spcp8x5
Title: Debian spcp8x5 Manual
Author: <insert document author here>
Abstract: This manual describes what spcp8x5 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spcp8x5/spcp8x5.sgml.gz

Format: postscript
Files: /usr/share/doc/spcp8x5/spcp8x5.ps.gz

Format: text
Files: /usr/share/doc/spcp8x5/spcp8x5.text.gz

Format: HTML
Index: /usr/share/doc/spcp8x5/html/index.html
Files: /usr/share/doc/spcp8x5/html/*.html

  
