Document: pluto-std-plugins
Title: Debian pluto-std-plugins Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-std-plugins is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-std-plugins/pluto-std-plugins.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-std-plugins/pluto-std-plugins.ps.gz

Format: text
Files: /usr/share/doc/pluto-std-plugins/pluto-std-plugins.text.gz

Format: HTML
Index: /usr/share/doc/pluto-std-plugins/html/index.html
Files: /usr/share/doc/pluto-std-plugins/html/*.html
