Document: lmce-pandora-plugin
Title: Debian lmce-pandora-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-pandora-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-pandora-plugin/lmce-pandora-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-pandora-plugin/lmce-pandora-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-pandora-plugin/lmce-pandora-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-pandora-plugin/html/index.html
Files: /usr/share/doc/lmce-pandora-plugin/html/*.html
