Document: pluto-avwizard-sounds
Title: Debian pluto-avwizard-sounds Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-avwizard-sounds is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-avwizard-sounds/pluto-avwizard-sounds.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-avwizard-sounds/pluto-avwizard-sounds.ps.gz

Format: text
Files: /usr/share/doc/pluto-avwizard-sounds/pluto-avwizard-sounds.text.gz

Format: HTML
Index: /usr/share/doc/pluto-avwizard-sounds/html/index.html
Files: /usr/share/doc/pluto-avwizard-sounds/html/*.html

  
