#!/bin/bash
# vim:set ft=sh:

set -e 
. ./filesd-parms.sh $@
. /usr/pluto/bin/Config_Ops.sh
. /usr/pluto/bin/Network_Parameters.sh

## fstab for diskless mds
File="/etc/rcS.d/S99firstrun"
Content="#!/bin/bash
trap 'rm -f $File' EXIT
apt-get update
update-pciids
. /usr/pluto/bin/Utils.sh
CheckVideoDriver 
sleep 5 
if echo \"\$Best_Video_Driver\" | grep -Eq '(nvidia|fglrx|via|virge|savage)'; then 
	reboot 
fi
"
if ! [[ -d "${Parm_RootLocation}/$(dirname $File)" ]]; then
	mkdir -p "${Parm_RootLocation}/$(dirname $File)"
fi
echo "$Content" > "${Parm_RootLocation}/${File}"
chmod +x "${Parm_RootLocation}/${File}"
