#!/bin/bash
# vim:set ft=sh:

set -e 
. ./filesd-parms.sh $@
. /usr/pluto/bin/Config_Ops.sh
. /usr/pluto/bin/Network_Parameters.sh
. /usr/pluto/bin/SQL_Ops.sh

DEVICEDATA_DISTRO=7

DisklessDir="$Parm_Device"
if [[ -n "$Parm_Subname" ]]; then
	DisklessDir="$DisklessDir/$Parm_Subname"
fi

## fstab for diskless mds
File="/etc/fstab"
TemplateFile="/usr/pluto/templates/fstab.tmpl"
mkdir -p "${Parm_RootLocation}/$(dirname $File)"
cp "${TemplateFile}" "${Parm_RootLocation}${File}"

sed --in-place -e "s,\(%CORE_INTERNAL_ADDRESS%\),${IntIP},g" ${Parm_RootLocation}/${File}
sed --in-place -e "s,\(%MOON_ID%\),${DisklessDir},g" ${Parm_RootLocation}/${File}

PK_Distro=$(RunSQL "SELECT IK_DeviceData FROM Device_DeviceData WHERE FK_Device='$Parm_Device' AND FK_DeviceData='$DEVICEDATA_DISTRO'")
if [[ 19 -eq "$PK_Distro" ]] ;then
	# Raspbian needs /boot mounted to /dev/mmcblk0p1
	echo "/dev/mmcblk0p1  /sdcard           vfat    defaults                0       0" >>${Parm_RootLocation}/${File}
fi

## Create some mountpoint so we know for sure that they exist
mkdir -p "${Parm_RootLocation}/usr/pluto/var"
mkdir -p "${Parm_RootLocation}/usr/pluto/orbiter"
mkdir -p "${Parm_RootLocation}/usr/pluto/keys"
mkdir -p "${Parm_RootLocation}/usr/pluto/deb-cache"
mkdir -p "${Parm_RootLocation}/var/spool/asterisk"



