#!/bin/bash
# vim:set ft=sh:

set -e 
. ./filesd-parms.sh $@
. /usr/pluto/bin/Config_Ops.sh
. /usr/pluto/bin/Network_Parameters.sh

DisklessDir="$Parm_Device"
if [[ -n "$Parm_Subname" ]]; then
	DisklessDir="$DisklessDir/$Parm_Subname"
fi

## fstab for diskless mds
File="/etc/fstab"
Content=""

Content="${Content}proc            /proc           proc    defaults                0       0\n"
Content="${Content}/dev/fd0        /floppy         auto    user,noauto             0       0\n"
Content="${Content}/dev/cdrom      /cdrom          iso9660 ro,user,noauto          0       0\n"
Content="${Content}sysfs           /sys            sysfs   defaults                0       0\n"
Content="${Content}${IntIP}:/usr/pluto/diskless/${DisklessDir} /                  nfs  intr,udp,rsize=32768,wsize=32768,retrans=10,timeo=50 1 1\n"
Content="${Content}${IntIP}:/usr/pluto/var                    /usr/pluto/var      nfs  intr,udp,rsize=32768,wsize=32768,retrans=10,timeo=50 1 1\n"
Content="${Content}${IntIP}:/usr/pluto/orbiter                /usr/pluto/orbiter  nfs  intr,udp,rsize=32768,wsize=32768,retrans=10,timeo=50 1 1\n"
Content="${Content}${IntIP}:/usr/pluto/keys                   /usr/pluto/keys     nfs  intr,udp,rsize=32768,wsize=32768,retrans=10,timeo=50 1 1\n"

if [[ "$Parm_Template" != 1893 ]]; then
	Content="${Content}${IntIP}:/usr/pluto/deb-cache              /usr/pluto/deb-cache nfs  intr,udp,rsize=32768,wsize=32768,retrans=10,timeo=50 1 1\n"
fi

Content="${Content}//${IntIP}/home                           /home               cifs forcedirectio,credentials=/usr/plutc/var/sambaCredentials.secret   1 1\n"
Content="${Content}\n"


mkdir -p "${Parm_RootLocation}/$(dirname $File)"
echo -e $Content > "${Parm_RootLocation}/${File}"

## Create some mountpoint so we know for sure that they exist
mkdir -p "${Parm_RootLocation}/usr/pluto/var"
mkdir -p "${Parm_RootLocation}/usr/pluto/orbiter"
mkdir -p "${Parm_RootLocation}/usr/pluto/keys"
mkdir -p "${Parm_RootLocation}/usr/pluto/deb-cache"



