#!/bin/bash
# vim:set ft=sh:

set -e 
. ./filesd-parms.sh $@
. /usr/pluto/bin/Config_Ops.sh
. /usr/pluto/bin/Network_Parameters.sh

DisklessDir="$Parm_Device"
if [[ -n "$Parm_Subname" ]]; then
	DisklessDir="$DisklessDir/$Parm_Subname"
fi

## fstab for diskless mds
File="/etc/fstab"
TemplateFile="/usr/pluto/templates/fstab.tmpl"
mkdir -p "${Parm_RootLocation}/$(dirname $File)"
cp "${TemplateFile}" "${Parm_RootLocation}${File}"

sed --in-place -e "s,\(%CORE_INTERNAL_ADDRESS%\),${IntIP},g" ${Parm_RootLocation}/${File}
sed --in-place -e "s,\(%MOON_ID%\),${DisklessDir},g" ${Parm_RootLocation}/${File}

## Create some mountpoint so we know for sure that they exist
mkdir -p "${Parm_RootLocation}/usr/pluto/var"
mkdir -p "${Parm_RootLocation}/usr/pluto/orbiter"
mkdir -p "${Parm_RootLocation}/usr/pluto/keys"
mkdir -p "${Parm_RootLocation}/usr/pluto/deb-cache"
mkdir -p "${Parm_RootLocation}/var/spool/asterisk"



