#!/bin/bash

set -e 

. ./filesd-parms.sh $@

. /usr/pluto/bin/SQL_Ops.sh

function IsDeviceInQuickStart {
	local device=$1
	local Devs=$2

	for dev in $Devs ;do
		if [[ "$dev" == "$device" ]] ;then
			return 0
		fi
	done

	return 1
}

Q="SELECT PK_Device FROM Device WHERE FK_DeviceTemplate=28"
Devices=$(RunSQL "$Q")

Q="SELECT FK_Device FROM Device_QuickStart WHERE FK_QuickStartTemplate=2"
DevsQuickStart=$(RunSQL "$Q")

for device in $Devices ;do
	if ! IsDeviceInQuickStart "$device" "$DevsQuickStart" ;then 
		Q="INSERT INTO Device_QuickStart(FK_Device,Description,SortOrder,FK_QuickStartTemplate) VALUES("$device",'MythTV Setup',"1","2")"
		RunSQL "$Q"
	fi
done

mkdir -p ${Parm_RootLocation}/root/.mythtv/ || :
touch ${Parm_RootLocation}/root/.mythtv/ignoregroup || :

