#!/bin/bash

set -e 

. ./filesd-parms.sh $@

. /usr/pluto/bin/SQL_Ops.sh

function addRootUser
{
	is_in_group="false"
	for group in `id -nG root` ;do
		if [[ "$group" == "mythtv" ]] ;then
			is_in_group="true"
		fi
	done

	if [[ "$is_in_group" == "false" ]] ;then
		group_line=$(grep "^mythtv:" /etc/group)
		if [[ "$(echo $group_line | cut -d':' -f4)" == "" ]] ;then
			group_line="${group_line}root"
		else
		    group_line="${group_line},root"
		fi
        echo $group_line > /etc/group.$$	
        grep -v "^mythtv:" /etc/group >> /etc/group.$$
        mv /etc/group.$$ /etc/group
	fi																																	
}

function IsDeviceInQuickStart {
	local device=$1
	local Devs=$2

	for dev in $Devs ;do
		if [[ "$dev" == "$device" ]] ;then
			return 0
		fi
	done

	return 1
}

## Set root user to mythtv group
if grep -q 'mythtv' /etc/group ;then
	addRootUser
else
	groupadd mythtv || :
	addRootUser
fi

Q="SELECT PK_Device FROM Device WHERE FK_DeviceTemplate=28"
Devices=$(RunSQL "$Q")

Q="SELECT FK_Device FROM Device_QuickStart WHERE FK_QuickStartTemplate=2"
DevsQuickStart=$(RunSQL "$Q")

for device in $Devices ;do
	if ! IsDeviceInQuickStart "$device" "$DevsQuickStart" ;then 
		Q="INSERT INTO Device_QuickStart(FK_Device,Description,SortOrder,FK_QuickStartTemplate) VALUES("$device",'MythTV Setup',"1","2")"
		RunSQL "$Q"
	fi
done

