#!/bin/bash

set -e 

. ./filesd-parms.sh $@

function addRootUser
{
	is_in_group="false"
	for group in `id -nG root` ;do
		if [[ "$group" == "mythtv" ]] ;then
			is_in_group="true"
		fi
	done

	if [[ "$is_in_group" == "false" ]] ;then
		group_line=$(grep "^mythtv:" /etc/group)
		if [[ "$(echo $group_line | cut -d':' -f4)" == "" ]] ;then
			group_line="${group_line}root"
		else
		    group_line="${group_line},root"
		fi
        echo $group_line > /etc/group.$$	
        grep -v "^mythtv:" /etc/group >> /etc/group.$$
        mv /etc/group.$$ /etc/group
	fi																																	
}


## Set root user to mythtv group
if grep -q 'mythtv' /etc/group ;then
	addRootUser
else
	groupadd mythtv || :
	addRootUser
fi
