#!/bin/bash

set -e 

. ./filesd-parms.sh $@

. /usr/pluto/bin/Network_Parameters.sh
. /usr/pluto/bin/Section_Ops.sh

## Config for nis to act as a client
File="/etc/default/nis"
mkdir -p "${Parm_RootLocation}/$(dirname $File)"
cp "/usr/pluto/templates/nis-client.template" "${Parm_RootLocation}/${File}"
PopulateSection "${Parm_RootLocation}/${File}" "Nis Master" "NISMASTER=$IntIP"

## Set the default nis domain
File="/etc/defaultdomain"
mkdir -p "${Parm_RootLocation}/$(dirname $File)"
echo "pluto" > "${Parm_RootLocation}/${File}"

File="/etc/yp.conf"
mkdir -p "$Parm_RootLocation}/$(dirname $File)"
echo "ypserver ${IntIP}" > "${Parm_RootLocation}/${File}"
##

## Force a diskless client to get passwd/shadow & group from nis
if [[ -f ${Parm_RootLocation}/etc/passwd ]] ;then
	grep -q "+::::::"   ${Parm_RootLocation}/etc/passwd || echo "+::::::"   >> ${Parm_RootLocation}/etc/passwd
fi
if [[ -f ${Parm_RootLocation}/etc/shadow ]] ;then
	grep -q "+::::::::" ${Parm_RootLocation}/etc/shadow || echo "+::::::::" >> ${Parm_RootLocation}/etc/shadow
fi

if [[ -f ${Parm_RootLocation}/etc/group ]] ;then
	grep -q "+:::"      ${Parm_RootLocation}/etc/group  || echo "+:::"      >> ${Parm_RootLocation}/etc/group
fi
