#!/bin/bash
# vim:set ft=sh:

set -e 

. ./filesd-parms.sh $@

## Shutdown sequence
Files=("/etc/rc"{0,6}".d/S01shutdown")
Content="#!/bin/bash

/usr/pluto/bin/Report_MachineOff.sh
"

for File in "${Files[@]}"; do
	echo "$Content" > "$Parm_RootLocation/$File"
	chmod +x "$Parm_RootLocation/$File"
done
