#!/bin/bash
# vim:set ft=sh:

set -e 
. ./filesd-parms.sh $@
. /usr/pluto/bin/Config_Ops.sh
. /usr/pluto/bin/Network_Parameters.sh

## timezone for diskless mds
File="/etc/timezone"
Content=""

mkdir -p "${Parm_RootLocation}/$(dirname $File)"
if [[ -f /etc/timezone ]]; then
	TimeZone="$(cat /etc/timezone)"
else
	TimeZone="$(readlink /etc/localtime)"
	TimeZone="${TimeZone#/usr/share/zoneinfo/}"
fi
echo "$TimeZone" >"${Parm_RootLocation}/${File}"
[[ -f "$Parm_RootLocation/etc/localtime" ]] && rm -f "$Parm_RootLocation"/etc/localtime # in case it's a file from the old (wrong) way of setting this up
ln -sf /usr/share/zoneinfo/"$TimeZone" "$Parm_RootLocation"/etc/localtime
