debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_decode_ff.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_decode_faad.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_decode_mad.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_decode_mpeg2.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_decode_a52.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_decode_dts.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_dmx_mpeg.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_dmx_mpeg_block.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_dmx_mpeg_elem.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_dmx_mpeg_pes.so
debian/tmp/opt/libxine/lib/xine/plugins/*/xineplug_dmx_mpeg_ts.so

# postprocess plugins
debian/tmp/opt/libxine/lib/xine/plugins/*/post/xineplug_post_planar.so
