#!/bin/bash

case "$1" in
  start)
        /bin/bash /usr/pluto/bin/HaltMDs.sh
        ;;
  stop)
	 /bin/bash /usr/pluto/bin/HaltMDs.sh
        ;;
  reload|force-reload)
        ;;
  restart)
        ;;
  *)
        echo \"Usage: /etc/init.d/haltMDs {start|stop|reload|force-reload|restart}\"
        exit 1
esac

