#!/bin/bash
### BEGIN INIT INFO
# Provides:          lmceupdate
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:
# Default-Start:     2
# Default-Stop:      1
# Short-Description: LMCEUpdate
# Description:       This script updates the LMCE MD
### END INIT INFO #

case "$1" in
	start)
        	if [ -x /bin/plymouth ]; then
                	/bin/plymouth update --status="Starting LinuxMCE update"
        	fi
                if [ -x /sbin/usplash_write ]; then
			usplash_write TEXT "Starting Linux MCE Update"
		fi

		/usr/pluto/bin/LMCEUpdate_Apply.sh

                if [ -x /bin/plymouth ]; then
                        /bin/plymouth update --status="Finished LinuxMCE update"
                fi
                if [ -x /sbin/usplash_write ]; then
			usplash_write TEXT "Finished Linux MCE Update"
		fi
		;;
	
	stop|restart|reload|force-reload)
        	echo "Error: argument '$1' not supported" >&2
	        exit 3
		;;
	*)
		echo "Usage: $0 start" >&2
		exit 3
		;;
esac
