Document: lmce-windowsutils
Title: Debian lmce-windowsutils Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-windowsutils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-windowsutils/lmce-windowsutils.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-windowsutils/lmce-windowsutils.ps.gz

Format: text
Files: /usr/share/doc/lmce-windowsutils/lmce-windowsutils.text.gz

Format: HTML
Index: /usr/share/doc/lmce-windowsutils/html/index.html
Files: /usr/share/doc/lmce-windowsutils/html/*.html
