#!/bin/bash

#set -e

. /usr/pluto/install/install-core.sh

firstboot_core_md_preinst () {
	:
}

firstboot_core_md_postinst () {
	if ! grep ubiquity /proc/cmdline ; then
		Create_And_Config_Hybrid_MD
	fi
}

