Document: libsdl
Title: Debian libsdl Manual
Author: <insert document author here>
Abstract: This manual describes what libsdl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsdl/libsdl.sgml.gz

Format: postscript
Files: /usr/share/doc/libsdl/libsdl.ps.gz

Format: text
Files: /usr/share/doc/libsdl/libsdl.text.gz

Format: HTML
Index: /usr/share/doc/libsdl/html/index.html
Files: /usr/share/doc/libsdl/html/*.html
