#ifndef __Define_CoverArtScanEntry_H__
#define __Define_CoverArtScanEntry_H__


#define COVERARTSCANENTRY_TABLE "CoverArtScanEntry"
#define COVERARTSCANENTRY_PK_COVERARTSCANENTRY_FIELD "PK_CoverArtScanEntry"
#define COVERARTSCANENTRY_PK_COVERARTSCANENTRY_TABLE_FIELD "CoverArtScanEntry.PK_CoverArtScanEntry"
#define COVERARTSCANENTRY_FK_COVERARTSCAN_FIELD "FK_CoverArtScan"
#define COVERARTSCANENTRY_FK_COVERARTSCAN_TABLE_FIELD "CoverArtScanEntry.FK_CoverArtScan"
#define COVERARTSCANENTRY_ID_FIELD "ID"
#define COVERARTSCANENTRY_ID_TABLE_FIELD "CoverArtScanEntry.ID"
#define COVERARTSCANENTRY_URL_FIELD "URL"
#define COVERARTSCANENTRY_URL_TABLE_FIELD "CoverArtScanEntry.URL"
#define COVERARTSCANENTRY_ATTRIBUTES_FIELD "Attributes"
#define COVERARTSCANENTRY_ATTRIBUTES_TABLE_FIELD "CoverArtScanEntry.Attributes"
#define COVERARTSCANENTRY_PSC_ID_FIELD "psc_id"
#define COVERARTSCANENTRY_PSC_ID_TABLE_FIELD "CoverArtScanEntry.psc_id"
#define COVERARTSCANENTRY_PSC_BATCH_FIELD "psc_batch"
#define COVERARTSCANENTRY_PSC_BATCH_TABLE_FIELD "CoverArtScanEntry.psc_batch"
#define COVERARTSCANENTRY_PSC_USER_FIELD "psc_user"
#define COVERARTSCANENTRY_PSC_USER_TABLE_FIELD "CoverArtScanEntry.psc_user"
#define COVERARTSCANENTRY_PSC_FROZEN_FIELD "psc_frozen"
#define COVERARTSCANENTRY_PSC_FROZEN_TABLE_FIELD "CoverArtScanEntry.psc_frozen"
#define COVERARTSCANENTRY_PSC_MOD_FIELD "psc_mod"
#define COVERARTSCANENTRY_PSC_MOD_TABLE_FIELD "CoverArtScanEntry.psc_mod"
#define COVERARTSCANENTRY_PSC_RESTRICT_FIELD "psc_restrict"
#define COVERARTSCANENTRY_PSC_RESTRICT_TABLE_FIELD "CoverArtScanEntry.psc_restrict"


#endif

