#ifndef __Define_SearchToken_Attribute_H__
#define __Define_SearchToken_Attribute_H__


#define SEARCHTOKEN_ATTRIBUTE_TABLE "SearchToken_Attribute"
#define SEARCHTOKEN_ATTRIBUTE_FK_SEARCHTOKEN_FIELD "FK_SearchToken"
#define SEARCHTOKEN_ATTRIBUTE_FK_SEARCHTOKEN_TABLE_FIELD "SearchToken_Attribute.FK_SearchToken"
#define SEARCHTOKEN_ATTRIBUTE_FK_ATTRIBUTE_FIELD "FK_Attribute"
#define SEARCHTOKEN_ATTRIBUTE_FK_ATTRIBUTE_TABLE_FIELD "SearchToken_Attribute.FK_Attribute"
#define SEARCHTOKEN_ATTRIBUTE_PSC_ID_FIELD "psc_id"
#define SEARCHTOKEN_ATTRIBUTE_PSC_ID_TABLE_FIELD "SearchToken_Attribute.psc_id"
#define SEARCHTOKEN_ATTRIBUTE_PSC_BATCH_FIELD "psc_batch"
#define SEARCHTOKEN_ATTRIBUTE_PSC_BATCH_TABLE_FIELD "SearchToken_Attribute.psc_batch"
#define SEARCHTOKEN_ATTRIBUTE_PSC_USER_FIELD "psc_user"
#define SEARCHTOKEN_ATTRIBUTE_PSC_USER_TABLE_FIELD "SearchToken_Attribute.psc_user"
#define SEARCHTOKEN_ATTRIBUTE_PSC_FROZEN_FIELD "psc_frozen"
#define SEARCHTOKEN_ATTRIBUTE_PSC_FROZEN_TABLE_FIELD "SearchToken_Attribute.psc_frozen"
#define SEARCHTOKEN_ATTRIBUTE_PSC_MOD_FIELD "psc_mod"
#define SEARCHTOKEN_ATTRIBUTE_PSC_MOD_TABLE_FIELD "SearchToken_Attribute.psc_mod"
#define SEARCHTOKEN_ATTRIBUTE_PSC_RESTRICT_FIELD "psc_restrict"
#define SEARCHTOKEN_ATTRIBUTE_PSC_RESTRICT_TABLE_FIELD "SearchToken_Attribute.psc_restrict"


#endif

