#ifndef __Define_MediaType_FileFormat_H__
#define __Define_MediaType_FileFormat_H__


#define MEDIATYPE_FILEFORMAT_TABLE "MediaType_FileFormat"
#define MEDIATYPE_FILEFORMAT_EK_MEDIATYPE_FIELD "EK_MediaType"
#define MEDIATYPE_FILEFORMAT_EK_MEDIATYPE_TABLE_FIELD "MediaType_FileFormat.EK_MediaType"
#define MEDIATYPE_FILEFORMAT_FK_FILEFORMAT_FIELD "FK_FileFormat"
#define MEDIATYPE_FILEFORMAT_FK_FILEFORMAT_TABLE_FIELD "MediaType_FileFormat.FK_FileFormat"
#define MEDIATYPE_FILEFORMAT_PSC_ID_FIELD "psc_id"
#define MEDIATYPE_FILEFORMAT_PSC_ID_TABLE_FIELD "MediaType_FileFormat.psc_id"
#define MEDIATYPE_FILEFORMAT_PSC_BATCH_FIELD "psc_batch"
#define MEDIATYPE_FILEFORMAT_PSC_BATCH_TABLE_FIELD "MediaType_FileFormat.psc_batch"
#define MEDIATYPE_FILEFORMAT_PSC_USER_FIELD "psc_user"
#define MEDIATYPE_FILEFORMAT_PSC_USER_TABLE_FIELD "MediaType_FileFormat.psc_user"
#define MEDIATYPE_FILEFORMAT_PSC_FROZEN_FIELD "psc_frozen"
#define MEDIATYPE_FILEFORMAT_PSC_FROZEN_TABLE_FIELD "MediaType_FileFormat.psc_frozen"
#define MEDIATYPE_FILEFORMAT_PSC_MOD_FIELD "psc_mod"
#define MEDIATYPE_FILEFORMAT_PSC_MOD_TABLE_FIELD "MediaType_FileFormat.psc_mod"
#define MEDIATYPE_FILEFORMAT_PSC_RESTRICT_FIELD "psc_restrict"
#define MEDIATYPE_FILEFORMAT_PSC_RESTRICT_TABLE_FIELD "MediaType_FileFormat.psc_restrict"


#endif

