#ifndef __Define_AttributeType_H__
#define __Define_AttributeType_H__

#define ATTRIBUTETYPE_Director_CONST 1
#define ATTRIBUTETYPE_Performer_CONST 2
#define ATTRIBUTETYPE_Album_CONST 3
#define ATTRIBUTETYPE_Song_CONST 4
#define ATTRIBUTETYPE_Track_CONST 5
#define ATTRIBUTETYPE_ASIN_CONST 6
#define ATTRIBUTETYPE_CDDB_CONST 7
#define ATTRIBUTETYPE_Genre_CONST 8
#define ATTRIBUTETYPE_Ref_Num_CONST 9
#define ATTRIBUTETYPE_Channel_CONST 10
#define ATTRIBUTETYPE_Episode_CONST 11
#define ATTRIBUTETYPE_Program_CONST 12
#define ATTRIBUTETYPE_Title_CONST 13
#define ATTRIBUTETYPE_Disc_ID_CONST 14
#define ATTRIBUTETYPE_Conductor_CONST 15
#define ATTRIBUTETYPE_Composer_CONST 16
#define ATTRIBUTETYPE_Studio_CONST 17
#define ATTRIBUTETYPE_Rating_CONST 18
#define ATTRIBUTETYPE_Release_Date_CONST 19
#define ATTRIBUTETYPE_Website_CONST 20

#define ATTRIBUTETYPE_TABLE "AttributeType"
#define ATTRIBUTETYPE_PK_ATTRIBUTETYPE_FIELD "PK_AttributeType"
#define ATTRIBUTETYPE_PK_ATTRIBUTETYPE_TABLE_FIELD "AttributeType.PK_AttributeType"
#define ATTRIBUTETYPE_DESCRIPTION_FIELD "Description"
#define ATTRIBUTETYPE_DESCRIPTION_TABLE_FIELD "AttributeType.Description"
#define ATTRIBUTETYPE_DEFINE_FIELD "Define"
#define ATTRIBUTETYPE_DEFINE_TABLE_FIELD "AttributeType.Define"
#define ATTRIBUTETYPE_PICPRIORITY_FIELD "PicPriority"
#define ATTRIBUTETYPE_PICPRIORITY_TABLE_FIELD "AttributeType.PicPriority"
#define ATTRIBUTETYPE_PSC_ID_FIELD "psc_id"
#define ATTRIBUTETYPE_PSC_ID_TABLE_FIELD "AttributeType.psc_id"
#define ATTRIBUTETYPE_PSC_BATCH_FIELD "psc_batch"
#define ATTRIBUTETYPE_PSC_BATCH_TABLE_FIELD "AttributeType.psc_batch"
#define ATTRIBUTETYPE_PSC_USER_FIELD "psc_user"
#define ATTRIBUTETYPE_PSC_USER_TABLE_FIELD "AttributeType.psc_user"
#define ATTRIBUTETYPE_PSC_FROZEN_FIELD "psc_frozen"
#define ATTRIBUTETYPE_PSC_FROZEN_TABLE_FIELD "AttributeType.psc_frozen"
#define ATTRIBUTETYPE_PSC_MOD_FIELD "psc_mod"
#define ATTRIBUTETYPE_PSC_MOD_TABLE_FIELD "AttributeType.psc_mod"
#define ATTRIBUTETYPE_PSC_RESTRICT_FIELD "psc_restrict"
#define ATTRIBUTETYPE_PSC_RESTRICT_TABLE_FIELD "AttributeType.psc_restrict"


#endif

