#ifndef __Define_AttributeType_H__
#define __Define_AttributeType_H__

#define ATTRIBUTETYPE_Director_CONST 1
#define ATTRIBUTETYPE_Performer_CONST 2
#define ATTRIBUTETYPE_Album_CONST 3
#define ATTRIBUTETYPE_Track_CONST 5
#define ATTRIBUTETYPE_ASIN_CONST 6
#define ATTRIBUTETYPE_CDDB_CONST 7
#define ATTRIBUTETYPE_Genre_CONST 8
#define ATTRIBUTETYPE_Ref_Num_CONST 9
#define ATTRIBUTETYPE_Channel_CONST 10
#define ATTRIBUTETYPE_Episode_CONST 11
#define ATTRIBUTETYPE_Program_CONST 12
#define ATTRIBUTETYPE_Title_CONST 13
#define ATTRIBUTETYPE_Disc_ID_CONST 14
#define ATTRIBUTETYPE_Conductor_CONST 15
#define ATTRIBUTETYPE_ComposerWriter_CONST 16
#define ATTRIBUTETYPE_Studio_CONST 17
#define ATTRIBUTETYPE_Rating_CONST 18
#define ATTRIBUTETYPE_Release_Date_CONST 19
#define ATTRIBUTETYPE_Website_CONST 20
#define ATTRIBUTETYPE_Chapter_CONST 21
#define ATTRIBUTETYPE_Encoding_CONST 22
#define ATTRIBUTETYPE_Format_CONST 23
#define ATTRIBUTETYPE_Aspect_Ratio_s_CONST 24
#define ATTRIBUTETYPE_Audio_Encoding_CONST 25
#define ATTRIBUTETYPE_Rated_CONST 26
#define ATTRIBUTETYPE_DVD_Release_Date_CONST 27
#define ATTRIBUTETYPE_Run_Time_CONST 28
#define ATTRIBUTETYPE_Keyword_CONST 29
#define ATTRIBUTETYPE_Screen_Saver_For_MD_CONST 30
#define ATTRIBUTETYPE_Region_CONST 32
#define ATTRIBUTETYPE_Language_CONST 33
#define ATTRIBUTETYPE_Aspect_Ratio_CONST 34
#define ATTRIBUTETYPE_Number_of_Discs_CONST 35
#define ATTRIBUTETYPE_IMDB_CONST 36
#define ATTRIBUTETYPE_Synopsis_CONST 37
#define ATTRIBUTETYPE_Producer_CONST 38
#define ATTRIBUTETYPE_Executive_Producer_CONST 39
#define ATTRIBUTETYPE_Purchase_Info_CONST 40
#define ATTRIBUTETYPE_TV_Channel_ID_CONST 41
#define ATTRIBUTETYPE_TV_Program_ID_CONST 42
#define ATTRIBUTETYPE_TV_Series_ID_CONST 43
#define ATTRIBUTETYPE_Creation_Date_CONST 44
#define ATTRIBUTETYPE_THX_Disk_ID_CONST 45
#define ATTRIBUTETYPE_Screen_saver_disabled_CONST 46
#define ATTRIBUTETYPE_Manufacturer_CONST 47
#define ATTRIBUTETYPE_Year_CONST 48

#define ATTRIBUTETYPE_TABLE "AttributeType"
#define ATTRIBUTETYPE_PK_ATTRIBUTETYPE_FIELD "PK_AttributeType"
#define ATTRIBUTETYPE_PK_ATTRIBUTETYPE_TABLE_FIELD "AttributeType.PK_AttributeType"
#define ATTRIBUTETYPE_DESCRIPTION_FIELD "Description"
#define ATTRIBUTETYPE_DESCRIPTION_TABLE_FIELD "AttributeType.Description"
#define ATTRIBUTETYPE_DEFINE_FIELD "Define"
#define ATTRIBUTETYPE_DEFINE_TABLE_FIELD "AttributeType.Define"
#define ATTRIBUTETYPE_PICPRIORITY_FIELD "PicPriority"
#define ATTRIBUTETYPE_PICPRIORITY_TABLE_FIELD "AttributeType.PicPriority"
#define ATTRIBUTETYPE_PSC_ID_FIELD "psc_id"
#define ATTRIBUTETYPE_PSC_ID_TABLE_FIELD "AttributeType.psc_id"
#define ATTRIBUTETYPE_PSC_BATCH_FIELD "psc_batch"
#define ATTRIBUTETYPE_PSC_BATCH_TABLE_FIELD "AttributeType.psc_batch"
#define ATTRIBUTETYPE_PSC_USER_FIELD "psc_user"
#define ATTRIBUTETYPE_PSC_USER_TABLE_FIELD "AttributeType.psc_user"
#define ATTRIBUTETYPE_PSC_FROZEN_FIELD "psc_frozen"
#define ATTRIBUTETYPE_PSC_FROZEN_TABLE_FIELD "AttributeType.psc_frozen"
#define ATTRIBUTETYPE_PSC_MOD_FIELD "psc_mod"
#define ATTRIBUTETYPE_PSC_MOD_TABLE_FIELD "AttributeType.psc_mod"
#define ATTRIBUTETYPE_PSC_RESTRICT_FIELD "psc_restrict"
#define ATTRIBUTETYPE_PSC_RESTRICT_TABLE_FIELD "AttributeType.psc_restrict"


#endif

