#ifndef __Define_Attribute_Settings_H__
#define __Define_Attribute_Settings_H__


#define ATTRIBUTE_SETTINGS_TABLE "Attribute_Settings"
#define ATTRIBUTE_SETTINGS_FK_ATTRIBUTE_FIELD "FK_Attribute"
#define ATTRIBUTE_SETTINGS_FK_ATTRIBUTE_TABLE_FIELD "Attribute_Settings.FK_Attribute"
#define ATTRIBUTE_SETTINGS_VIDEOSETTING_FIELD "VideoSetting"
#define ATTRIBUTE_SETTINGS_VIDEOSETTING_TABLE_FIELD "Attribute_Settings.VideoSetting"
#define ATTRIBUTE_SETTINGS_AUDIOSETTING_FIELD "AudioSetting"
#define ATTRIBUTE_SETTINGS_AUDIOSETTING_TABLE_FIELD "Attribute_Settings.AudioSetting"
#define ATTRIBUTE_SETTINGS_COMMANDS_FIELD "Commands"
#define ATTRIBUTE_SETTINGS_COMMANDS_TABLE_FIELD "Attribute_Settings.Commands"
#define ATTRIBUTE_SETTINGS_PSC_ID_FIELD "psc_id"
#define ATTRIBUTE_SETTINGS_PSC_ID_TABLE_FIELD "Attribute_Settings.psc_id"
#define ATTRIBUTE_SETTINGS_PSC_BATCH_FIELD "psc_batch"
#define ATTRIBUTE_SETTINGS_PSC_BATCH_TABLE_FIELD "Attribute_Settings.psc_batch"
#define ATTRIBUTE_SETTINGS_PSC_USER_FIELD "psc_user"
#define ATTRIBUTE_SETTINGS_PSC_USER_TABLE_FIELD "Attribute_Settings.psc_user"
#define ATTRIBUTE_SETTINGS_PSC_FROZEN_FIELD "psc_frozen"
#define ATTRIBUTE_SETTINGS_PSC_FROZEN_TABLE_FIELD "Attribute_Settings.psc_frozen"
#define ATTRIBUTE_SETTINGS_PSC_MOD_FIELD "psc_mod"
#define ATTRIBUTE_SETTINGS_PSC_MOD_TABLE_FIELD "Attribute_Settings.psc_mod"
#define ATTRIBUTE_SETTINGS_PSC_RESTRICT_FIELD "psc_restrict"
#define ATTRIBUTE_SETTINGS_PSC_RESTRICT_TABLE_FIELD "Attribute_Settings.psc_restrict"


#endif

