#ifndef __Define_psc_media_batdet_H__
#define __Define_psc_media_batdet_H__


#define PSC_MEDIA_BATDET_TABLE "psc_media_batdet"
#define PSC_MEDIA_BATDET_PK_PSC_MEDIA_BATDET_FIELD "PK_psc_media_batdet"
#define PSC_MEDIA_BATDET_PK_PSC_MEDIA_BATDET_TABLE_FIELD "psc_media_batdet.PK_psc_media_batdet"
#define PSC_MEDIA_BATDET_FK_PSC_MEDIA_BATHDR_FIELD "FK_psc_media_bathdr"
#define PSC_MEDIA_BATDET_FK_PSC_MEDIA_BATHDR_TABLE_FIELD "psc_media_batdet.FK_psc_media_bathdr"
#define PSC_MEDIA_BATDET_TABLENAME_FIELD "Tablename"
#define PSC_MEDIA_BATDET_TABLENAME_TABLE_FIELD "psc_media_batdet.Tablename"
#define PSC_MEDIA_BATDET_NEW_FIELD "New"
#define PSC_MEDIA_BATDET_NEW_TABLE_FIELD "psc_media_batdet.New"
#define PSC_MEDIA_BATDET_DELETED_FIELD "Deleted"
#define PSC_MEDIA_BATDET_DELETED_TABLE_FIELD "psc_media_batdet.Deleted"
#define PSC_MEDIA_BATDET_MODIFIED_FIELD "Modified"
#define PSC_MEDIA_BATDET_MODIFIED_TABLE_FIELD "psc_media_batdet.Modified"
#define PSC_MEDIA_BATDET_FK_PSC_MEDIA_BATHDR_ORIG_FIELD "FK_psc_media_bathdr_orig"
#define PSC_MEDIA_BATDET_FK_PSC_MEDIA_BATHDR_ORIG_TABLE_FIELD "psc_media_batdet.FK_psc_media_bathdr_orig"
#define PSC_MEDIA_BATDET_FK_PSC_MEDIA_BATHDR_AUTH_FIELD "FK_psc_media_bathdr_auth"
#define PSC_MEDIA_BATDET_FK_PSC_MEDIA_BATHDR_AUTH_TABLE_FIELD "psc_media_batdet.FK_psc_media_bathdr_auth"
#define PSC_MEDIA_BATDET_FK_PSC_MEDIA_BATHDR_UNAUTH_FIELD "FK_psc_media_bathdr_unauth"
#define PSC_MEDIA_BATDET_FK_PSC_MEDIA_BATHDR_UNAUTH_TABLE_FIELD "psc_media_batdet.FK_psc_media_bathdr_unauth"


#endif

