#ifndef __Define_PlaylistEntry_H__
#define __Define_PlaylistEntry_H__


#define PLAYLISTENTRY_TABLE "PlaylistEntry"
#define PLAYLISTENTRY_PK_PLAYLISTENTRY_FIELD "PK_PlaylistEntry"
#define PLAYLISTENTRY_PK_PLAYLISTENTRY_TABLE_FIELD "PlaylistEntry.PK_PlaylistEntry"
#define PLAYLISTENTRY_FK_PLAYLIST_FIELD "FK_Playlist"
#define PLAYLISTENTRY_FK_PLAYLIST_TABLE_FIELD "PlaylistEntry.FK_Playlist"
#define PLAYLISTENTRY_FK_FILE_FIELD "FK_File"
#define PLAYLISTENTRY_FK_FILE_TABLE_FIELD "PlaylistEntry.FK_File"
#define PLAYLISTENTRY_FK_BOOKMARK_FIELD "FK_Bookmark"
#define PLAYLISTENTRY_FK_BOOKMARK_TABLE_FIELD "PlaylistEntry.FK_Bookmark"
#define PLAYLISTENTRY_PATH_FIELD "Path"
#define PLAYLISTENTRY_PATH_TABLE_FIELD "PlaylistEntry.Path"
#define PLAYLISTENTRY_FILENAME_FIELD "Filename"
#define PLAYLISTENTRY_FILENAME_TABLE_FIELD "PlaylistEntry.Filename"
#define PLAYLISTENTRY_ORDER_FIELD "Order"
#define PLAYLISTENTRY_ORDER_TABLE_FIELD "PlaylistEntry.Order"
#define PLAYLISTENTRY_DURATION_FIELD "Duration"
#define PLAYLISTENTRY_DURATION_TABLE_FIELD "PlaylistEntry.Duration"
#define PLAYLISTENTRY_EK_COMMANDGROUP_START_FIELD "EK_CommandGroup_Start"
#define PLAYLISTENTRY_EK_COMMANDGROUP_START_TABLE_FIELD "PlaylistEntry.EK_CommandGroup_Start"
#define PLAYLISTENTRY_EK_COMMANDGROUP_STOP_FIELD "EK_CommandGroup_Stop"
#define PLAYLISTENTRY_EK_COMMANDGROUP_STOP_TABLE_FIELD "PlaylistEntry.EK_CommandGroup_Stop"
#define PLAYLISTENTRY_PSC_ID_FIELD "psc_id"
#define PLAYLISTENTRY_PSC_ID_TABLE_FIELD "PlaylistEntry.psc_id"
#define PLAYLISTENTRY_PSC_BATCH_FIELD "psc_batch"
#define PLAYLISTENTRY_PSC_BATCH_TABLE_FIELD "PlaylistEntry.psc_batch"
#define PLAYLISTENTRY_PSC_USER_FIELD "psc_user"
#define PLAYLISTENTRY_PSC_USER_TABLE_FIELD "PlaylistEntry.psc_user"
#define PLAYLISTENTRY_PSC_FROZEN_FIELD "psc_frozen"
#define PLAYLISTENTRY_PSC_FROZEN_TABLE_FIELD "PlaylistEntry.psc_frozen"
#define PLAYLISTENTRY_PSC_MOD_FIELD "psc_mod"
#define PLAYLISTENTRY_PSC_MOD_TABLE_FIELD "PlaylistEntry.psc_mod"
#define PLAYLISTENTRY_PSC_RESTRICT_FIELD "psc_restrict"
#define PLAYLISTENTRY_PSC_RESTRICT_TABLE_FIELD "PlaylistEntry.psc_restrict"


#endif

