#ifndef __Define_AttributeType_H__
#define __Define_AttributeType_H__

#define ATTRIBUTETYPE_Individual_CONST 1
#define ATTRIBUTETYPE_Group_CONST 2
#define ATTRIBUTETYPE_Album_CONST 3
#define ATTRIBUTETYPE_Song_CONST 4
#define ATTRIBUTETYPE_Track_CONST 5
#define ATTRIBUTETYPE_ASIN_CONST 6
#define ATTRIBUTETYPE_CDDB_CONST 7
#define ATTRIBUTETYPE_Genre_CONST 8
#define ATTRIBUTETYPE_Ref_Num_CONST 9
#define ATTRIBUTETYPE_Channel_CONST 10
#define ATTRIBUTETYPE_Episode_CONST 11
#define ATTRIBUTETYPE_Program_CONST 12
#define ATTRIBUTETYPE_Title_CONST 13

#define ATTRIBUTETYPE_TABLE "AttributeType"
#define ATTRIBUTETYPE_PK_ATTRIBUTETYPE_FIELD "PK_AttributeType"
#define ATTRIBUTETYPE_PK_ATTRIBUTETYPE_TABLE_FIELD "AttributeType.PK_AttributeType"
#define ATTRIBUTETYPE_DESCRIPTION_FIELD "Description"
#define ATTRIBUTETYPE_DESCRIPTION_TABLE_FIELD "AttributeType.Description"
#define ATTRIBUTETYPE_DEFINE_FIELD "Define"
#define ATTRIBUTETYPE_DEFINE_TABLE_FIELD "AttributeType.Define"
#define ATTRIBUTETYPE_PSC_ID_FIELD "psc_id"
#define ATTRIBUTETYPE_PSC_ID_TABLE_FIELD "AttributeType.psc_id"
#define ATTRIBUTETYPE_PSC_BATCH_FIELD "psc_batch"
#define ATTRIBUTETYPE_PSC_BATCH_TABLE_FIELD "AttributeType.psc_batch"
#define ATTRIBUTETYPE_PSC_USER_FIELD "psc_user"
#define ATTRIBUTETYPE_PSC_USER_TABLE_FIELD "AttributeType.psc_user"
#define ATTRIBUTETYPE_PSC_FROZEN_FIELD "psc_frozen"
#define ATTRIBUTETYPE_PSC_FROZEN_TABLE_FIELD "AttributeType.psc_frozen"
#define ATTRIBUTETYPE_PSC_MOD_FIELD "psc_mod"
#define ATTRIBUTETYPE_PSC_MOD_TABLE_FIELD "AttributeType.psc_mod"


#endif

