#ifndef __Define_Attribute_MediaType_H__
#define __Define_Attribute_MediaType_H__


#define ATTRIBUTE_MEDIATYPE_TABLE "Attribute_MediaType"
#define ATTRIBUTE_MEDIATYPE_FK_ATTRIBUTE_FIELD "FK_Attribute"
#define ATTRIBUTE_MEDIATYPE_FK_ATTRIBUTE_TABLE_FIELD "Attribute_MediaType.FK_Attribute"
#define ATTRIBUTE_MEDIATYPE_EK_MEDIATYPE_FIELD "EK_MediaType"
#define ATTRIBUTE_MEDIATYPE_EK_MEDIATYPE_TABLE_FIELD "Attribute_MediaType.EK_MediaType"
#define ATTRIBUTE_MEDIATYPE_NUMFILES_FIELD "NumFiles"
#define ATTRIBUTE_MEDIATYPE_NUMFILES_TABLE_FIELD "Attribute_MediaType.NumFiles"


#endif

