#ifndef __Define_File_H__
#define __Define_File_H__


#define FILE_TABLE "File"
#define FILE_PK_FILE_FIELD "PK_File"
#define FILE_PK_FILE_TABLE_FIELD "File.PK_File"
#define FILE_EK_MEDIATYPE_FIELD "EK_MediaType"
#define FILE_EK_MEDIATYPE_TABLE_FIELD "File.EK_MediaType"
#define FILE_FK_MEDIASUBTYPE_FIELD "FK_MediaSubType"
#define FILE_FK_MEDIASUBTYPE_TABLE_FIELD "File.FK_MediaSubType"
#define FILE_FK_FILEFORMAT_FIELD "FK_FileFormat"
#define FILE_FK_FILEFORMAT_TABLE_FIELD "File.FK_FileFormat"
#define FILE_FK_FILEGROUP_FIELD "FK_FileGroup"
#define FILE_FK_FILEGROUP_TABLE_FIELD "File.FK_FileGroup"
#define FILE_DATEADDED_FIELD "DateAdded"
#define FILE_DATEADDED_TABLE_FIELD "File.DateAdded"
#define FILE_PATH_FIELD "Path"
#define FILE_PATH_TABLE_FIELD "File.Path"
#define FILE_FILENAME_FIELD "Filename"
#define FILE_FILENAME_TABLE_FIELD "File.Filename"
#define FILE_MISSING_FIELD "Missing"
#define FILE_MISSING_TABLE_FIELD "File.Missing"
#define FILE_ISDIRECTORY_FIELD "IsDirectory"
#define FILE_ISDIRECTORY_TABLE_FIELD "File.IsDirectory"
#define FILE_EK_USERS_PRIVATE_FIELD "EK_Users_Private"
#define FILE_EK_USERS_PRIVATE_TABLE_FIELD "File.EK_Users_Private"
#define FILE_EK_DEVICE_FIELD "EK_Device"
#define FILE_EK_DEVICE_TABLE_FIELD "File.EK_Device"
#define FILE_MODIFICATIONDATE_FIELD "ModificationDate"
#define FILE_MODIFICATIONDATE_TABLE_FIELD "File.ModificationDate"
#define FILE_ATTRCOUNT_FIELD "AttrCount"
#define FILE_ATTRCOUNT_TABLE_FIELD "File.AttrCount"
#define FILE_ATTRDATE_FIELD "AttrDate"
#define FILE_ATTRDATE_TABLE_FIELD "File.AttrDate"
#define FILE_DATELASTVIEWED_FIELD "DateLastViewed"
#define FILE_DATELASTVIEWED_TABLE_FIELD "File.DateLastViewed"
#define FILE_ISNEW_FIELD "IsNew"
#define FILE_ISNEW_TABLE_FIELD "File.IsNew"
#define FILE_IGNORE_FIELD "Ignore"
#define FILE_IGNORE_TABLE_FIELD "File.Ignore"
#define FILE_INODE_FIELD "INode"
#define FILE_INODE_TABLE_FIELD "File.INode"
#define FILE_PSC_ID_FIELD "psc_id"
#define FILE_PSC_ID_TABLE_FIELD "File.psc_id"
#define FILE_PSC_BATCH_FIELD "psc_batch"
#define FILE_PSC_BATCH_TABLE_FIELD "File.psc_batch"
#define FILE_PSC_USER_FIELD "psc_user"
#define FILE_PSC_USER_TABLE_FIELD "File.psc_user"
#define FILE_PSC_FROZEN_FIELD "psc_frozen"
#define FILE_PSC_FROZEN_TABLE_FIELD "File.psc_frozen"
#define FILE_PSC_MOD_FIELD "psc_mod"
#define FILE_PSC_MOD_TABLE_FIELD "File.psc_mod"
#define FILE_PSC_RESTRICT_FIELD "psc_restrict"
#define FILE_PSC_RESTRICT_TABLE_FIELD "File.psc_restrict"


#endif

