#!/bin/sh

#   Written by Diego Iastrubni <diego.iastrubni@xorcom.com>
#   Copyright (C) 2005,2006,2007 Xorcom
#  
#   All rights reserved.
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#  
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# a small script, which uses genzaptelconf to search for new drivers 
# edit /etc/modules as needed, calling zap2amp to generate AMP configuration
# and eventually restart asterisk to make it aware of the new HW


make_sound_zaptel(){
	if [ ! -x /usr/bin/beep ]; then
		return 0
	fi

# no zaptel channels found - no zaptel HW	
#	if ! cat /etc/zaptel.conf | grep -v '^#' | grep -q 'fx.*=[0-9]*'; then 
#		exit
#	fi

	if cat /proc/zaptel/* 2> /dev/null | grep -q '/[0-9]/[0-9]/[0-9]' ; then 
		# old ts-1
		# /usr/bin/beep -f 10000
	
		# new ts-1
		beep -f 5000 -l 100 -d 10 -r 2
	fi	
}

# nullify a file
blank_file(){
	if [ -f  $1 ]; then
		rm -f $1
		touch $1
	fi
}
		
				
set -e

AST_USER=asterisk
AST_GROUP=asterisk
AST_SHELL=/bin/sh

# find new HW, asterisk will be running after it, as zap2amp
# needs asterisk running. will also rewrite /etc/modules
echo ' * Searching for new zapata hardware'

blank_file /etc/asterisk/zapata-channels.conf
blank_file /etc/asterisk/zapata-auto.conf
blank_file /etc/asterisk/zapata_additional.conf
touch /etc/asterisk/zapata_additional.conf

# do not run the version in /usr/local/sbin,
# since trixbox contains a stupid version out there
/usr/sbin/genzaptelconf -d -s -M -F

echo ' * Generating amportal configuration'
chown asterisk: /etc/asterisk/zapata*
chmod g+rw /etc/asterisk/zapata*
chmod o+r /etc/zaptel.conf
su $AST_USER -s $AST_SHELL -c /usr/share/freepbx-common/zap2amp
su $AST_USER -s $AST_SHELL -c /usr/share/asterisk/bin/retrieve_conf
su $AST_USER -s $AST_SHELL -c /usr/share/freepbx-common/fix_ast_db

echo ' * Reloading zaptel configuration'
/etc/init.d/asterisk restart
make_sound_zaptel

if [ -x /etc/init.d/op-panel ]; then
	echo ' * Reloading Flash Operator Panel'
	/etc/init.d/op-panel restart
fi

echo "DONE"
