#!/bin/bash
if [[ "$6" != "" ]]; then
    . /usr/pluto/bin/Network_Parameters.sh
    if [[ "$VPNenabled" == "on" ]]; then
	. /usr/pluto/bin/Config_Ops.sh
	if [[ "$DisableIPv4Firewall" != "1" ]]; then
	    R=$(mysql pluto_main -ss -e"SELECT Place, Protocol FROM Firewall WHERE RuleType='VPN' AND SourceIP='$5' AND Protocol='ip-ipv4' ORDER BY PK_Firewall")
	    if [[ "$R" ]]; then
	        for Port in $R; do
                        Place=$(Field 1 "$Port")
                        Protocol=$(Field 2 "$Port")
		        mysql pluto_main -ss -e "UPDATE Firewall SET Offline=1 WHERE RuleType='VPN' AND SourceIP='$5'"
		      /usr/pluto/bin/Network_Firewall.sh -L Rule -A Disable -P $Protocol -p $Place
		   done
	    fi
	fi
    fi
fi
