#!/bin/bash
if [[ "$6" != "" ]]; then
    . /usr/pluto/bin/Network_Parameters.sh
    if [[ "$VPNenabled" == "on" ]]; then
	. /usr/pluto/bin/Config_Ops.sh
	if [[ "$DisableIPv4Firewall" != "1" ]]; then
	    sql="SELECT Protocol FROM Firewall WHERE RuleType='VPN' AND SourceIP='$5' AND Protocol='ip-ipv4' ORDER BY PK_Firewall"
	    R=$(RunSQL "$sql")
	    if [[ "$R" ]]; then
		mysql pluto_main -ss -e "UPDATE Firewall SET Offline=1 WHERE RuleType='VPN' AND SourceIP='$5'"
	    fi
	    /usr/pluto/bin/Network_Firewall.sh -L Rule -A Offline -C VPN -P $Protocol -p $Place
	fi
    fi
fi
