#!/bin/sh -e

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null
then
	dpkg-maintscript-helper rm_conffile /etc/default/zfsload -- "$@"
	dpkg-maintscript-helper rm_conffile /etc/init.d/zfs -- "$@"
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d zfs-share remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

