#!/bin/sh -e

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null
then
	dpkg-maintscript-helper rm_conffile /etc/default/zfsload -- "$@"
	dpkg-maintscript-helper rm_conffile /etc/init.d/zfs -- "$@"
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/zpool-import" ]; then
	if [ ! -e "/etc/init/zpool-import.conf" ]; then
		update-rc.d zpool-import defaults >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f zpool-import remove >/dev/null || exit $?
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/zfs-share" ]; then
	if [ ! -e "/etc/init/zfs-share.conf" ]; then
		update-rc.d zfs-share defaults 25 15 >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_installudev
if [ "$1" = configure ]; then
	if [ -e "/etc/udev/rules.d/60_zfsutils.zvol.rules" ]; then
		echo "Preserving user changes to /etc/udev/rules.d/60-zvol.rules ..."
		if [ -e "/etc/udev/rules.d/60-zvol.rules" ]; then
			mv -f "/etc/udev/rules.d/60-zvol.rules" "/etc/udev/rules.d/60-zvol.rules.dpkg-new"
		fi
		mv -f "/etc/udev/rules.d/60_zfsutils.zvol.rules" "/etc/udev/rules.d/60-zvol.rules"
	fi
fi
# End automatically added section
# Automatically added by dh_installudev
if [ "$1" = configure ]; then
	if [ -e "/etc/udev/rules.d/69_zfsutils.vdev.rules" ]; then
		echo "Preserving user changes to /etc/udev/rules.d/69-vdev.rules ..."
		if [ -e "/etc/udev/rules.d/69-vdev.rules" ]; then
			mv -f "/etc/udev/rules.d/69-vdev.rules" "/etc/udev/rules.d/69-vdev.rules.dpkg-new"
		fi
		mv -f "/etc/udev/rules.d/69_zfsutils.vdev.rules" "/etc/udev/rules.d/69-vdev.rules"
	fi
fi
# End automatically added section

