Document: libserialize
Title: Debian libserialize Manual
Author: <insert document author here>
Abstract: This manual describes what libserialize is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libserialize/libserialize.sgml.gz

Format: postscript
Files: /usr/share/doc/libserialize/libserialize.ps.gz

Format: text
Files: /usr/share/doc/libserialize/libserialize.text.gz

Format: HTML
Index: /usr/share/doc/libserialize/html/index.html
Files: /usr/share/doc/libserialize/html/*.html
