Document: lmce-mythtv-plugin
Title: Debian lmce-mythtv-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-mythtv-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-mythtv-plugin/lmce-mythtv-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-mythtv-plugin/lmce-mythtv-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-mythtv-plugin/lmce-mythtv-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-mythtv-plugin/html/index.html
Files: /usr/share/doc/lmce-mythtv-plugin/html/*.html
