#!/bin/bash

# Copy the make_resolv_conf function
eval "$(declare -f make_resolv_conf | awk 'NR==1 {print "make_resolv_conf_orig()"; next} {print}')"

# "Derive" the make_resolv_conf function
make_resolv_conf()
{
	make_resolv_conf_orig
	/usr/pluto/bin/Network_DNS.sh dhclienthook
	/usr/pluto/bin/Network_NIS.sh
}
