#!/bin/bash
### BEGIN INIT INFO
# Provides:          linuxmce
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LinuxMCE
# Description:       This script is the entry point to start the LinuxMCE core
#                    It starts all needed services and daemons, runs AV Wizard & loads X (if running with AutoStartMedia)
#                    and launches core services (if running with AutoStartCore)
#                    and executes LMCE_Launch_Manager to take care of the rest.
### END INIT INFO #

DD_DISTRO_Raspbian_Wheezy_CONST=19
DD_DISTRO_Raspbian_Jessie_CONST=22
DD_DISTRO_Ubuntu_Xenial_CONST=23
DD_DEVICETEMPLATE_Core=7
DD_DEVICETEMPLATE_GenericPC_as_MD=28
DD_DEVICETEMPLATE_GenericPC_as_qMD=2277
DD_DEVICETEMPLATE_RPi_B_as_MD=2216
DD_DEVICETEMPLATE_RPi_B_as_qMD=2281
DD_DEVICETEMPLATE_Joggler=2176


# Source fuction library
. /lib/lsb/init-functions

Message() {
    echo -en "\033[1m# $*"
    tput sgr0
}

StartService() {
	ServiceDescription=$1
	ServiceCmd=$2
	ServiceBkg=$3

	if [[ -x $(echo $ServiceCmd | cut -d ' ' -f1) ]] ;then
		#if [[ -x /bin/plymouth ]]; then
		#	/bin/plymouth update --status="$ServiceDescription ... " || :
		#fi
		#echo -n "$ServiceDescription ... "

		log_daemon_msg "$ServiceDescription" "$ServiceCmd"
		if [[ "$ServiceBkg" == "&" ]] ;then
			$ServiceCmd 1>/dev/null 2>/dev/null &
		else
			$ServiceCmd 1>/dev/null 2>/dev/null
		fi
		err=$?
		log_end_msg $err

		#if [[ "$err" == "0" ]] ;then
		#	echo "ok"
		#else
		#	echo "fail"
		#fi
	fi

	return $err
}

StartDaemon() {
	ServiceDescription=$1
	ServiceCmd=$2
	ServiceScreen=$3

	if [[ -x $(echo $ServiceCmd | cut -d ' ' -f1) ]] ;then
		#if [[ -x /bin/plymouth ]]; then
			#/bin/plymouth update --status="$ServiceDescription ... " || :
		#fi
		#echo -n "$ServiceDescription ... "

		log_daemon_msg "$ServiceDescription" "$ServiceCmd"
		screen -d -m -S "$ServiceScreen" $ServiceCmd
		err=$?
		log_end_msg $err

		#if [[ "$err" == "0" ]] ;then
		#	echo "ok"
		#else
		#	echo "fail"
		#fi
	fi

	return $err
}

StartX() {
	# Only start X if we want to autostart the media.
	if [[ "$Display" == "" ]] ;then
		if [[ "$DISPLAY" == "" ]] ;then
			export DISPLAY=:0
		fi
	else
		export DISPLAY=":${Display}"
	fi
	if [[ -r /var/run/plutoX${Display}.pid ]]; then
		XPID=$(</var/run/plutoX${Display}.pid)
	else
		XPID=""
	fi

	if [ -z "$XPID" -o ! -d /proc/"$XPID" ]; then
		AlphaBlending=$(AlphaBlendingEnabled)

		#XClient=/usr/pluto/bin/Start_IceWM.sh
		if [[ -e /usr/bin/xfwm4 ]] ;then
			XClient=/usr/bin/xfwm4
		else
			XClient=/usr/bin/kwin
		fi
		XClientParm=()
		XOrgConf="/etc/X11/xorg.conf"

		XServerParm=(-logverbose 9 -br)
		Background=y
		XDisplay=":$Display"

		Xcompmgr=/bin/true
		if [[ "$AlphaBlending" != 1 && "$XClient" != "/usr/bin/kwin" ]]; then
			XClientParm=(--compositor=off)
		fi

		for ((i = 1; i <= "$#"; i++)); do
			case "${!i}" in
				-client) ((i++)); XClient="${!i}" ;;
				-parm) ((i++)); XClientParm=("${XClientParm[@]}" "${!i}") ;;
				-fg) Background=n ;;
				-srvparm) ((i++)); XServerParm=("${XServerParm[@]}" "${!i}") ;;
				-display) ((i++)); XDisplay="${!i}" ;;
				-flags) ((i++)); WrapperFlags=("${WrapperFlags[@]}" "${!i}") ;;
				-config) ((i++)); XOrgConf=${!i} ;;
			esac
		done

		Logging "$TYPE" "$SEVERITY_NORMAL" "$0" "Starting X server (client: $XClient; parms: ${XClientParm[*]})"

		VT=${XDisplay#:}
		VT=vt"$((7+VT))"

		# Start X11
		if [[ "$PK_Distro" == "$DD_DISTRO_Raspbian_Wheezy_CONST" || "$PK_Distro" == "$DD_DISTRO_Raspbian_Jessie_CONST" ]] ;then
			# Raspbian does not get an xorg.conf
			Xcmd=(/usr/pluto/bin/Start_X_Wrapper.sh --parms "$@" --client "$XClient" "${XClientParm[@]}" --server "$XDisplay" -ignoreABI -ac -allowMouseOpenFail "$VT" "${XServerParm[@]}" --flags "${WrapperFlags[@]}")
		else
			Xcmd=(/usr/pluto/bin/Start_X_Wrapper.sh --parms "$@" --client "$XClient" "${XClientParm[@]}" --server "$XDisplay" -ignoreABI -ac -allowMouseOpenFail "$VT" "${XServerParm[@]}" --flags "${WrapperFlags[@]}" -config "${XOrgConf}")
		fi
		if [[ "$Background" == y ]]; then
			screen -d -m -S XWindowSystem "${Xcmd[@]}"
			# Start everouter for gyration mouse
			#if [[ -x /usr/pluto/bin/StartGyrationEvrouter.sh ]]; then
			#	screen -d -m -S GyrationMouse /usr/pluto/bin/StartGyrationEvrouter.sh
			#fi
			sleep 1

			Logging "$TYPE" "$SEVERITY_NORMAL" "$0" "X server: backround; AlphaBlending: $AlphaBlending"
			if [[ "$AlphaBlending" == 1 ]]; then
				DISPLAY=:0 "$Xcompmgr" &>/dev/null </dev/null &
				disown -a
			fi
		else
			Logging "$TYPE" "$SEVERITY_NORMAL" "$0" "X server: foreground"
			"${Xcmd[@]}"
		fi
	fi

}



start() {
	#	if [[ -x /bin/plymouth ]]; then
	#	/bin/plymouth message --text="Starting up LinuxMCE..." || :
	#	fi
	if [[ -x /bin/plymouth ]]; then
	/bin/plymouth --hide-splash || :
	fi

	log_daemon_msg "Starting up LinuxMCE" "linuxmce"
	err=0

	service kdm stop >/dev/null 2>&1 || :
	service sddm stop >/dev/null 2>&1 || :
	service lightdm stop >/dev/null 2>&1 || :

	# Disable display manager
	mkdir -p "/etc/X11"
	echo "/bin/false" >/etc/X11/default-display-manager

	setterm -blank >/dev/console             # disable console blanking
	mkdir -p /var/log/pluto                  # setup log dir
	chmod 777 /var/log/pluto 2>/dev/null     # setup log dir
	chmod 777 /etc/pluto.conf 2>/dev/null    # ensure access rights on pluto.conf
	rm -f /var/log/pluto/running.pids 2>/dev/null # clean running pid list
	mkdir -p /usr/pluto/locks                # clean up locks
	rm -f /usr/pluto/locks/*                 # clean up locks
	rm -f /var/run/plutoX*.pid		 # clean up x11 locks
	rm -f /mnt/optical/*.checksum
	if [[ -f /etc/logrotate.d/linuxmce ]]; then
	        rm -f /etc/logrotate.d/pluto*     # make sure there are not leftover logrotate configuration files
	fi
	rm -f /etc/rc{0,6}.d/S*{umountnfs.sh,portmap,networking}

	# TODO: move to gc100 boot-addon script
	rm -f /dev/ttyS_*                        # remove all ttyS_* (created by gc100s) entries from /dev

	# These helpers are essential to the entire boot process, they *must* exist.
	. /usr/pluto/bin/Config_Ops.sh
	. /usr/pluto/bin/pluto.func
	. /usr/pluto/bin/SQL_Ops.sh
	. /usr/pluto/bin/Utils.sh

	# Enable SSH asap
	StartService "Setting SSH Keys" "/usr/pluto/bin/SSH_Keys.sh" "&"

	# start ubiquity *after* network config has been done
	if grep -q ubiquity /proc/cmdline ; then
		/usr/pluto/install/firstboot
		service ubiquity start
		exit 0
	fi

	# check firstboot completion and launch firstboot from here
	if [[ "$FirstBoot" != "false" ]] ; then
		/usr/pluto/install/firstboot
		err=$?
		if [[ "$err" != "0" ]]; then
			Message "FIRSTBOOT ERROR $err, FIRSTBOOT DID NOT COMPLETE"
			return $err
		fi
		# TODO: this is here because avwizard gets skipped without it for some reason, need to investigate
		reboot
	fi

	# check firstboot completion prior to continuing to launch linuxmce.
	ConfEval;
	if [[ "$FirstBoot" != "false" ]] ; then
		Message "FIRSTBOOT NOT COMPLETE, CANNOT CONTINUE LOADING LINUXMCE."
		err=1
		return $err
	fi

	StartService "Starting LinuxMCE Update Service" "/usr/pluto/bin/LMCEUpdate_Apply.sh"

	# Start core services required for DCERouter and networking
	if [[ "$AutostartCore" -eq "1" ]] ; then
		StartService "Starting MySQL Server" "service mysql start"
		StartService "Starting DHCP Server" "service isc-dhcp-server start" "&"
		StartService "Starting DNS Server" "service bind9 start" "&"

		if [[ "$PK_Distro" == "$DD_DISTRO_Ubuntu_Xenial_CONST" ]] ; then
			while ! systemctl is-active mysql ; do
				sleep 1
			done
		fi
		StartService "Verify Device and Child PK_Distro values" "/usr/pluto/bin/VerifyDistro.sh" "&"
		StartService "Configuring Network Firewall" "/usr/pluto/bin/Network_Firewall.sh" "&"
		StartService "Detecting Timezone" "/usr/pluto/bin/Timezone_Detect.sh" "&"
		StartService "Confirm Installation" "/usr/pluto/bin/ConfirmInstallation.sh"

		# Update PK_Installation in case it has changed in the DB (see ConfirmInstallation.sh)
		Q="SELECT FK_Installation FROM Device WHERE PK_Device='$PK_Device'"
		R="$(RunSQL "$Q")"
		ConfSet PK_Installation "$R"

		# Update PK_Users in case the number of users has changed
		Q="SELECT PK_Users FROM Users LIMIT 1"
		R="$(RunSQL "$Q")"
		ConfSet PK_Users "$R"

		# un-set any RegenInProgress values for OrbiterGen status
		RunSQL "UPDATE Orbiter set Regen=2,RegenInProgress=0 where RegenInProgress=1"
	fi

	# Load MD modules in case they are needed for AV Output
	if [[ "$AutostartMedia" -eq "1" ]] ; then
		StartService "Loading Kernel Modules" "/usr/pluto/bin/LoadMDModules.sh"
	fi

	# Launch AV Wizard after module loading
	StartService "Starting LinuxMCE AV Wizard" "/usr/pluto/bin/Start_AVWizard.sh start"

	# Check AV Wizard completion prior to continuing to launch linuxmce.
	ConfEval;
	if [[ "$AutostartMedia" == "1" ]] ; then
		if [[ "$AVWizardDone" != "1" ]] ; then
			Message "AVWIZARD NOT COMPLETE, LINUXMCE MAY NOT LOAD PROPERLY."
#			err=1
#			return $err
		fi
	fi

	export DISPLAY=":${Display}"
	# hack: cleaning lockfile on M/D start to allow local devices to start
	# TODO: remove this when correct locking will be implemented
	rm -f /usr/pluto/locks/pluto_spawned_local_devices.txt
	if [[ "$AutostartMedia" -eq "1" ]] ; then
		/usr/pluto/bin/SetupAudioVideo.sh

		Q="SELECT FK_DeviceTemplate FROM Device WHERE PK_Device=$PK_Device"
		FK_DeviceTemplate=$(RunSQL "$Q")

		# FIXME: Look for an Orbiter on non-rpi-qMDs to determine if X is needed?
		if [[ "$FK_DeviceTemplate" == "$DD_DEVICETEMPLATE_GenericPC_as_MD" ]] ||
			[[ "$FK_DeviceTemplate" == "$DD_DEVICETEMPLATE_GenericPC_as_qMD" ]] ||
			[[ "$FK_DeviceTemplate" == "$DD_DEVICETEMPLATE_RPi_B_as_MD" ]] ||
			[[ "$FK_DeviceTemplate" == "$DD_DEVICETEMPLATE_Core" ]] ||
			[[ "$FK_DeviceTemplate" == "$DD_DEVICETEMPLATE_Joggler" ]] ; then
				StartX
		fi
	fi

	# X is running, run ConfirmDependencies and start LMCE_Launch_Manager (including DCERouter if this is the core)
	StartService "Setting Coredump Location" "/usr/pluto/bin/corefile.sh" "&"
	StartService "Configure Device Changes" "/usr/pluto/bin/Config_Device_Changes.sh"
	StartDaemon  "Starting LinuxMCE Launch Manager" "/usr/pluto/bin/LaunchManagerDaemon.sh" "LMCE_Launch_Manager"

	# Start core services - not required until after DCERouter is running
	if [[ "$AutostartCore" -eq "1" ]] ; then
		# asterisk is not configured properly and sip phones cannot register otherwise
		service asterisk restart
		StartDaemon "Start Voicemail Monitor" "/usr/pluto/bin/VoiceMailMonitor.sh" "VoiceMailMonitor"
		StartDaemon "Starting Dhcp Plugin" "/usr/pluto/bin/Dhcpd-Plugin.sh" "DhcpdPlugin"
		StartDaemon "Start PNP MD Plugin (interactor)" "/usr/pluto/bin/Start_NewMD_interactor.sh" "NewMDinteractor"
		StartService "Starting Samba Radar" "/usr/pluto/bin/StorageDevices_SambaRadar.sh" "&"
		StartService "Starting NFS Radar" "/usr/pluto/bin/StorageDevices_NFSRadar.sh" "&"
		StartService "Update deb-cache" "/usr/pluto/bin/UpdateDebCache.sh"
	fi

	StartService "Enable Wake-on-LAN" "/usr/pluto/bin/enable_wol.sh" "&"
	StartService "Configuring Pluto Storage Devices" "/usr/pluto/bin/StorageDevices_Setup.sh" "&"
	StartService "Starting Status Radar" "/usr/pluto/bin/StorageDevices_StatusRadar.sh" "&"
	StartService "Reporting Machine Status" "/usr/pluto/bin/Report_Machine_Status.sh" "&"

	# TODO: move to a boot-addon script for the individual devices (firewire/pvr250).
	#StartService "Creating Firewire 2 Video4Linux Pipes" "/usr/pluto/bin/Firewire2Video4Linux.sh" "&"
	#StartService "PVR-250 tuner restore" "/usr/pluto/bin/CaptureCards_BootConfig_PVR-250.sh" "&"

	# TODO: move to a vdr boot-addon script
	# If we are using VDR as our PVR, make sure the video dir is available, and restart VDR
	# if needed.
	if VDRInstalled ; then
		if [[ -f /etc/default/vdr ]]; then
			. /etc/default/vdr
		fi
		cd $VIDEO_DIR
		if ! pidof vdr ; then
			# If we are running on the cure, we need to restart VDR after mounting the relevant devices
			if [[ "$AutostartCore" -eq "1" ]] ; then
				service vdr restart
			fi
		fi
	fi

	# Start core services - not required until after DCERouter is running
	if [[ "$AutostartCore" -eq "1" ]] && [[ "$AutostartMedia" -eq "0" ]]; then
		screen -r LMCE_Launch_Manager
	fi

	return $err
}

StopService() {
	ServiceDescription=$1
	ServiceCmd=$2
	ServiceName=$3

	log_daemon_msg "$ServiceDescription" "$ServiceCmd"

	screenpid=$(basename $(find /var/run/screen | grep "$ServiceName") 2>/dev/null)
	err=$?
	if [[ "$err" == "0" ]]; then
		pid=$(echo $screenpid | cut -d '.' -f1)
		kill $pid
		err=$?
		if [[ "$err" != "0" ]]; then
			kill -9 $pid
			err=$?
		fi
	fi
	log_end_msg $err
	return $err
}

stop() {
	#StopService "Stopping Restart_Myth_Backend" "/usr/pluto/bin/Restart_Myth_Backend.sh" "Restart_Myth_Backend"
	#StopService "Stopping discovery" "/usr/pluto/bin/discovery.py" "discovery"
	#StopService "Stopping Orbiter" "/usr/pluto/bin/Spawn_Device.sh" "OnScreen_Orbiter"
	#StopService "Stopping LMCE Launch Manager" "/usr/pluto/bin/LaunchManagerDaemon.sh" "LMCE_Launch_Manager"
	#StopService "Stopping DCERouter" "/usr/pluto/bin/Spawn_DCERouter.sh" "DCERouter"
	#StopService "Stopping XWindowSystem" "/usr/pluto/bin/Start_X_Wrapper.sh" "XWindowSystem"

	#StopService "Stopping Gamepad Radar" "/usr/pluto/bin/Gamepad_Detect.sh" "GamepadRadar"
	#StopService "Stopping NFS Radar" "/usr/pluto/bin/StorageDevices_NFSRadar.sh" "NFSRadar"
	#StopService "Stopping Samba Radar" "/usr/pluto/bin/StorageDevices_SambaRadar.sh" "SambaRadar"
	#StopService "Stopping Storage Status Radar" "/usr/pluto/bin/StorageDevices_StatusRadar.sh" "StorageStatusRadar"
	#StopService "Stopping Voicemail Monitor" "/usr/pluto/bin/VoiceMailMonitor.sh" "VoiceMailMonitor"
	#StopService "Stopping PNP MD Plugin (interactor)" "/usr/pluto/bin/Start_NewMD_interactor.sh" "NewMDinteractor"
	#StopService "Stopping Dhcpd Plugin" "/usr/pluto/bin/Dhcpd-Plugin.sh" "DhcpdPlugin"

	StartService "Enable Wake-on-LAN" "/usr/pluto/bin/enable_wol.sh"
	if [[ "$AutostartCore" -eq "1" ]] ; then
		StartService "Halt MDs" "/usr/pluto/bin/HaltMDs.sh"
	fi
	/usr/pluto/bin/Report_MachineOff.sh

	:
	return $?
}

status() {
	status_of_proc linuxmce LinuxMCE
	return $?
}

### main logic ###
case "$1" in
	start)
		$1
		retval=$?
		;;
	stop)
		$1
		retval=$?
		;;
	status)
		$1
		retval=$?
		;;
	restart|reload)
		: # noop
		retval=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		retval=1
esac
exit $retval
