#!/bin/bash
if [[ "$6" != "" ]]; then
    . /usr/pluto/bin/Network_Parameters.sh
    if [[ "$VPNenabled" == "on" ]]; then
	. /usr/pluto/bin/Config_Ops.sh
	if [[ "$DisableIPv4Firewall" != "1" ]]; then
	    R=$(mysql pluto_main -ss -e"SELECT Protocol FROM Firewall WHERE RuleType='VPN' AND SourceIP='$5' AND Protocol='ip-ipv4' ORDER BY PK_Firewall")
	    if [[ "$R" ]]; then
		mysql pluto_main -ss -e "UPDATE Firewall SET Offline=0 WHERE RuleType='VPN' AND SourceIP='$5'"
	    fi
	    /usr/pluto/bin/Network_Firewall.sh
	fi
    fi
fi
