#ifndef GOOGLAPIINTERFACE_GLOBAL_H
#define GOOGLAPIINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GOOGLAPIINTERFACE_LIBRARY)
#  define GOOGLAPIINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GOOGLAPIINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GOOGLAPIINTERFACE_GLOBAL_H
