Document: pluto-sqlcvs
Title: Debian pluto-sqlcvs Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-sqlcvs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-sqlcvs/pluto-sqlcvs.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-sqlcvs/pluto-sqlcvs.ps.gz

Format: text
Files: /usr/share/doc/pluto-sqlcvs/pluto-sqlcvs.text.gz

Format: HTML
Index: /usr/share/doc/pluto-sqlcvs/html/index.html
Files: /usr/share/doc/pluto-sqlcvs/html/*.html
