Document: pluto-upgrade-helper
Title: Debian pluto-upgrade-helper Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-upgrade-helper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-upgrade-helper/pluto-upgrade-helper.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-upgrade-helper/pluto-upgrade-helper.ps.gz

Format: text
Files: /usr/share/doc/pluto-upgrade-helper/pluto-upgrade-helper.text.gz

Format: HTML
Index: /usr/share/doc/pluto-upgrade-helper/html/index.html
Files: /usr/share/doc/pluto-upgrade-helper/html/*.html
