Document: lmce-security-plugin
Title: Debian lmce-security-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-security-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-security-plugin/lmce-security-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-security-plugin/lmce-security-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-security-plugin/lmce-security-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-security-plugin/html/index.html
Files: /usr/share/doc/lmce-security-plugin/html/*.html
