#ifndef __Define_psc_security_batdet_H__
#define __Define_psc_security_batdet_H__


#define PSC_SECURITY_BATDET_TABLE "psc_security_batdet"
#define PSC_SECURITY_BATDET_PK_PSC_SECURITY_BATDET_FIELD "PK_psc_security_batdet"
#define PSC_SECURITY_BATDET_PK_PSC_SECURITY_BATDET_TABLE_FIELD "psc_security_batdet.PK_psc_security_batdet"
#define PSC_SECURITY_BATDET_FK_PSC_SECURITY_BATHDR_FIELD "FK_psc_security_bathdr"
#define PSC_SECURITY_BATDET_FK_PSC_SECURITY_BATHDR_TABLE_FIELD "psc_security_batdet.FK_psc_security_bathdr"
#define PSC_SECURITY_BATDET_TABLENAME_FIELD "Tablename"
#define PSC_SECURITY_BATDET_TABLENAME_TABLE_FIELD "psc_security_batdet.Tablename"
#define PSC_SECURITY_BATDET_NEW_FIELD "New"
#define PSC_SECURITY_BATDET_NEW_TABLE_FIELD "psc_security_batdet.New"
#define PSC_SECURITY_BATDET_DELETED_FIELD "Deleted"
#define PSC_SECURITY_BATDET_DELETED_TABLE_FIELD "psc_security_batdet.Deleted"
#define PSC_SECURITY_BATDET_MODIFIED_FIELD "Modified"
#define PSC_SECURITY_BATDET_MODIFIED_TABLE_FIELD "psc_security_batdet.Modified"
#define PSC_SECURITY_BATDET_FK_PSC_SECURITY_BATHDR_ORIG_FIELD "FK_psc_security_bathdr_orig"
#define PSC_SECURITY_BATDET_FK_PSC_SECURITY_BATHDR_ORIG_TABLE_FIELD "psc_security_batdet.FK_psc_security_bathdr_orig"
#define PSC_SECURITY_BATDET_FK_PSC_SECURITY_BATHDR_AUTH_FIELD "FK_psc_security_bathdr_auth"
#define PSC_SECURITY_BATDET_FK_PSC_SECURITY_BATHDR_AUTH_TABLE_FIELD "psc_security_batdet.FK_psc_security_bathdr_auth"
#define PSC_SECURITY_BATDET_FK_PSC_SECURITY_BATHDR_UNAUTH_FIELD "FK_psc_security_bathdr_unauth"
#define PSC_SECURITY_BATDET_FK_PSC_SECURITY_BATHDR_UNAUTH_TABLE_FIELD "psc_security_batdet.FK_psc_security_bathdr_unauth"


#endif

