#ifndef __Define_psc_security_batuser_H__
#define __Define_psc_security_batuser_H__


#define PSC_SECURITY_BATUSER_TABLE "psc_security_batuser"
#define PSC_SECURITY_BATUSER_PK_PSC_SECURITY_BATUSER_FIELD "PK_psc_security_batuser"
#define PSC_SECURITY_BATUSER_PK_PSC_SECURITY_BATUSER_TABLE_FIELD "psc_security_batuser.PK_psc_security_batuser"
#define PSC_SECURITY_BATUSER_FK_PSC_SECURITY_BATHDR_FIELD "FK_psc_security_bathdr"
#define PSC_SECURITY_BATUSER_FK_PSC_SECURITY_BATHDR_TABLE_FIELD "psc_security_batuser.FK_psc_security_bathdr"
#define PSC_SECURITY_BATUSER_PSC_USER_FIELD "psc_user"
#define PSC_SECURITY_BATUSER_PSC_USER_TABLE_FIELD "psc_security_batuser.psc_user"
#define PSC_SECURITY_BATUSER_IS_SUP_FIELD "is_sup"
#define PSC_SECURITY_BATUSER_IS_SUP_TABLE_FIELD "psc_security_batuser.is_sup"


#endif

