#ifndef __Define_psc_security_repset_H__
#define __Define_psc_security_repset_H__


#define PSC_SECURITY_REPSET_TABLE "psc_security_repset"
#define PSC_SECURITY_REPSET_PK_PSC_SECURITY_REPSET_FIELD "PK_psc_security_repset"
#define PSC_SECURITY_REPSET_PK_PSC_SECURITY_REPSET_TABLE_FIELD "psc_security_repset.PK_psc_security_repset"
#define PSC_SECURITY_REPSET_SETTING_FIELD "Setting"
#define PSC_SECURITY_REPSET_SETTING_TABLE_FIELD "psc_security_repset.Setting"
#define PSC_SECURITY_REPSET_VALUE_FIELD "Value"
#define PSC_SECURITY_REPSET_VALUE_TABLE_FIELD "psc_security_repset.Value"


#endif

