Document: djmount
Title: Debian djmount Manual
Author: <insert document author here>
Abstract: This manual describes what djmount is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/djmount/djmount.sgml.gz

Format: postscript
Files: /usr/share/doc/djmount/djmount.ps.gz

Format: text
Files: /usr/share/doc/djmount/djmount.text.gz

Format: HTML
Index: /usr/share/doc/djmount/html/index.html
Files: /usr/share/doc/djmount/html/*.html

  
