#!/bin/sh

PREREQ=""

# Output pre-requisites
prereqs()
{
	echo "$PREREQ"
}

case "$1" in
    prereqs)
	prereqs
	exit 0
	;;
esac

exec 1>&2

DT=$(/scripts/DeviceTemplate)

NICS=$(ip -o link | grep "link/ether" | awk '{ print $2; }' | cut -d':' -f1)
NIC_COUNT=$(echo $NICS | wc -w)
ExtIf=$(echo $NICS | awk '{ print $1; }')

MyIP=`ifconfig $ExtIf | grep "inet addr" | sed -r 's/^.* inet addr:([0-9.]*).*/\1/g'`
MyMAC=`ifconfig $ExtIf | grep "HWaddr "  | sed -r 's/^.* HWaddr ([a-zA-Z0-9:]*)/\1/g'`
Gateway=`ip route | grep "default via" | cut -d " " -f3`

Architecture="i386"

#Temporarily Removed until amd64 builds are re-instated. -tschak
#Reinstated for we have the builds now -phenigma 6/10/2017
if grep -q "^flags.* lm " /proc/cpuinfo ;then
	Architecture="amd64"
fi

echo "IP: $MyIP; MAC: $MyMAC; Gateway: $Gateway; Architecture: $Architecture; DT: $DT"
/scripts/interactor "$Gateway" "$MyIP" "$MyMAC" "$Architecture" "$DT"

clear
echo "ERROR: Cannot connect to router, rebooting in 5 seconds.."
sleep 5
reboot
