Document: lmce-infrared-plugin
Title: Debian lmce-infrared-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-infrared-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-infrared-plugin/lmce-infrared-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-infrared-plugin/lmce-infrared-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-infrared-plugin/lmce-infrared-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-infrared-plugin/html/index.html
Files: /usr/share/doc/lmce-infrared-plugin/html/*.html
