#!/bin/sh

#DEBHELPER#

if [ "$(uname -r)" = "_KVERS_" ] ; then
	if [ -x /etc/init.d/alsa ] ; then
		if ! /etc/init.d/alsa force-reload ; then
			echo 'You should now stop all applications using sound devices ' >&2
			echo 'and run "/etc/init.d/alsa force-reload" to load the new modules.' >&2
		fi
	else
		echo 'You should now stop all applications using sound devices ' >&2
		echo 'and reload all ALSA sound modules.' >&2
	fi
fi

