Document: lmce-climate-plugin
Title: Debian lmce-climate-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-climate-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-climate-plugin/lmce-climate-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-climate-plugin/lmce-climate-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-climate-plugin/lmce-climate-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-climate-plugin/html/index.html
Files: /usr/share/doc/lmce-climate-plugin/html/*.html
