#!/bin/csh -f

$LIA_PHON_REP/bin/lia_retik -r $LIA_PHON_REP/data/regles_retik | \
$LIA_PHON_REP/bin/lia_liaison $LIA_PHON_REP/data/regles_l.pro3 $LIA_PHON_REP/data/h_aspi.sirlex | \
$LIA_PHON_REP/bin/lia_phonetise -l | \
$LIA_PHON_REP/bin/lia_pprocess -r $LIA_PHON_REP/data/rule_phon.pro | \
$LIA_PHON_REP/bin/lia_nett_phon
 
