#!/bin/bash -e

if [[ "$1" == configure ]]; then
	. /usr/pluto/bin/SQL_Ops.sh

	asterisk -V >/etc/asterisk/version
	if [[ -n "$MySqlPassword" ]]; then
		PassParm="-p$MySqlPassword"
	fi
	if [[ -z "$(RunSQL "SHOW DATABASES LIKE 'asterisk'")" ]]; then
		RunSQL "CREATE DATABASE asterisk"
		RunSQL "CREATE DATABASE asteriskcdrdb"
		RunSQL "GRANT ALL PRIVILEGES ON asterisk.* TO asteriskuser@localhost IDENTIFIED BY 'amp109'"
		RunSQL "GRANT ALL PRIVILEGES ON asteriskcdrdb.* TO asteriskuser@localhost IDENTIFIED BY 'amp109'"

		mysql -h "$MySqlHost" -u "$MySqlUser" $PassParm asteriskcdrdb </var/lib/freepbx/SQL/cdr_mysql_table.sql
		mysql -h "$MySqlHost" -u "$MySqlUser" $PassParm asterisk </var/lib/freepbx/SQL/newinstall.sql
	fi

	cp /var/www/admin/modules/core/etc/* /etc/asterisk/
	mkdir -p /var/log/asterisk

	adduser www-data asterisk

	chown -R asterisk.asterisk /var/log/asterisk /usr/share/asterisk/agi-bin/ /etc/asterisk
	chmod -R ug+rw /etc/asterisk
	invoke-rc.d apache2 restart
	invoke-rc.d asterisk restart
	
	for Module in core conferences dashboard featurecodeadmin infoservices ivr music queues recordings ringgroups timeconditions voicemail; do
		echo "Installing module '$Module'"
		/var/lib/asterisk/bin/module_admin --no-warnings -f install "$Module"
	done

	/usr/pluto/bin/sync_pluto2amp.pl || :
fi
