#!/bin/bash -e

if [[ "$1" == configure ]]; then
	. /usr/pluto/bin/SQL_Ops.sh

	asterisk -V >/etc/asterisk/version
	if [[ -n "$MySqlPassword" ]]; then
		PassParm="-p$MySqlPassword"
	fi

	# create and populate asteriskcdrdb database if it does not exist
	RunSQL "CREATE DATABASE IF NOT EXISTS asteriskcdrdb"
	mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm asteriskcdrdb </var/lib/freepbx/SQL/cdr_mysql_table.sql

	# create asterisk database if it does not exist
	RunSQL "CREATE DATABASE IF NOT EXISTS asterisk"

	# create/update asterisk database schema
	if [[ -z "$(RunSQL "USE asterisk; DESC notifications")" ]]; then
		mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm asterisk </var/lib/freepbx/SQL/newinstall.sql
	else
		mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm asterisk </var/lib/freepbx/SQL/upgradedb.sql
	fi
	
	# ensure access privileges on the asterisk and asteriskcdrdb databases
	RunSQL "GRANT ALL PRIVILEGES ON asterisk.* TO asteriskuser@localhost IDENTIFIED BY 'amp109'"
	RunSQL "GRANT ALL PRIVILEGES ON asteriskcdrdb.* TO asteriskuser@localhost IDENTIFIED BY 'amp109'"

	if [[ -f /etc/init.d/asterisk.dpkg-new ]] ;then
		rm /etc/init.d/asterisk
		mv /etc/init.d/asterisk.dpkg-new /etc/init.d/asterisk
	fi

	cp /var/www/admin/modules/core/etc/* /etc/asterisk/
	mkdir -p /var/{log,spool}/asterisk

	adduser www-data asterisk

	chown -R asterisk.asterisk {/usr/share,/var/{log,lib,spool},/etc}/asterisk
	chmod -R ug+rw /etc/asterisk
	invoke-rc.d apache2 restart
	invoke-rc.d asterisk restart
	
	for Module in core conferences dashboard featurecodeadmin infoservices ivr music queues recordings ringgroups timeconditions voicemail; do
		echo "Installing module '$Module'"
		/var/lib/asterisk/bin/module_admin --no-warnings -f install "$Module"
	done

	/usr/pluto/bin/sync_pluto2amp.pl || :
	
	# just to be sure
	## the installed modules add files to some of these directories and the ownership needs to be set for them too
	chown -R asterisk.asterisk {/usr/share,/var/{log,lib,spool},/etc}/asterisk
fi
