#!/bin/bash

#set -e

if [[ -n "$HEADER_FB_CSTCK" ]]; then
	return 0
fi
HEADER_FB_CSTCK=included

find_linux_root_device() {
	RDEV=$(mountpoint -d /)

	for file in $(find /dev -type b 2>/dev/null) ; 	do
		MAJOR=$(stat --printf="%t" "$file")
		MAJOR_DEC=$((16#$MAJOR))
		MINOR=$(stat --printf="%T" "$file")
		MINOR_DEC=$((16#$MINOR))

		if [ "$MAJOR_DEC:$MINOR_DEC" = "$RDEV" ]; then
			ROOTDEVICE="$file"
			break;
		fi
	done
	echo "$ROOTDEVICE"
}

firstboot_md_cstck_preinst() {
	return 0
}


firstboot_md_cstck_kernel() {
	return 0
}

firstboot_md_cstck_postinst() {
	return 0
}
