Document: libdce
Title: Debian libdce Manual
Author: <insert document author here>
Abstract: This manual describes what libdce is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libdce/libdce.sgml.gz

Format: postscript
Files: /usr/share/doc/libdce/libdce.ps.gz

Format: text
Files: /usr/share/doc/libdce/libdce.text.gz

Format: HTML
Index: /usr/share/doc/libdce/html/index.html
Files: /usr/share/doc/libdce/html/*.html
