Document: tee-pluto
Title: Debian tee-pluto Manual
Author: <insert document author here>
Abstract: This manual describes what tee-pluto is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tee-pluto/tee-pluto.sgml.gz

Format: postscript
Files: /usr/share/doc/tee-pluto/tee-pluto.ps.gz

Format: text
Files: /usr/share/doc/tee-pluto/tee-pluto.text.gz

Format: HTML
Index: /usr/share/doc/tee-pluto/html/index.html
Files: /usr/share/doc/tee-pluto/html/*.html

  
