//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VIPDesign.rc
//
#define IDR_MANIFEST                    1
#define IDD_VIPTEXT                     9
#define IDD_ABOUTBOX                    100
#define IDD_VIPGRAPHIC                  101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_VIPDesignTYPE               129
#define ID_ADD_TEXT                     130
#define ID_ADD_GRAPHI                   131
#define ID_ADD_INPUT                    132
#define ID_ADD_RESOLUTION               133
#define ID_ADD_TEXT135                  135
#define ID_ADD_GRAPHIC                  137
#define ID_EDIT_TEXT                    138
#define ID_EDIT_GRAPHIC                 139
#define ID_ADD_INPUT140                 140
#define ID_ADD_ZONE                     141
#define ID_ADD_RESOLUTION142            142
#define ID_ADD_MENU                     143
#define ID_ADD_VARIABLE                 144
#define ID_EDIT_INPUT                   145
#define ID_EDIT_ZONE                    146
#define ID_EDIT_RESOLUTION              147
#define ID_EDIT_MENU                    148
#define ID_EDIT_VARIABLE                149
#define IDD_VIPEDIT                     150
#define IDD_VIPINPUT                    151
#define IDD_VIPRESOLUTION               152
#define IDD_VIPMENU                     153
#define IDD_VIPVARIABLE                 154
#define ID_Menu                         155
#define ID_VIEW_GOTOMENU                156
#define ID_VIEW_EMULATOR                157
#define ID_GOTO_LISTMENUS               158
#define IDD_PROPERTIES                  159
#define ID_MODIFY_PROPERTIES            160
#define IDD_VIPLIST                     160
#define ID_ADD_LIST                     161
#define ID_MODIFY_LIST                  162
#define IDD_RESET_EMULATOR              163
#define ID_POS_MEMBERIDENTIFIED         164
#define IDD_DIALOG1                     165
#define IDC_TEXT_SIZE                   1001
#define IDC_TEXT_FONT                   1003
#define IDC_TEXT                        1004
#define IDC_TEXT_X                      1007
#define IDC_TEXT_Y                      1008
#define IDC_TEXT_WIDTH                  1009
#define IDC_TEXT_HEIGHT                 1010
#define IDC_GRAPHIC_HEIGHT              1011
#define IDC_GRAPHIC_WIDTH               1012
#define IDC_GRAPHIC_Y                   1013
#define IDC_GRAPHIC_X                   1014
#define IDC_GRAPHIC_FILENAME            1015
#define IDC_LIST_ITEMS                  1016
#define IDC_EDIT_UP                     1017
#define IDC_EDIT_DOWN                   1018
#define IDC_EDIT_EDIT                   1019
#define IDC_EDIT_DELETE                 1021
#define IDC_GRAPHIC_FIND                1022
#define IDC_INPUT_AUTOTERM              1023
#define IDC_INPUT_NUMCHARS              1024
#define IDC_INPUT_CLEARVAR              1025
#define IDC_INPUT_VARIABLE              1026
#define IDC_RES_Y                       1027
#define IDC_RES_N                       1028
#define IDC_RES_E                       1029
#define IDC_RES_F                       1030
#define IDC_RES_UP                      1031
#define IDC_RES_DOWN                    1032
#define IDC_RES_LEFT                    1033
#define IDC_RES_RIGHT                   1034
#define IDC_RES_1                       1036
#define IDC_RES_2                       1037
#define IDC_RES_3                       1038
#define IDC_RES_4                       1039
#define IDC_RES_5                       1040
#define IDC_RES_0                       1041
#define IDC_RES_6                       1042
#define IDC_RES_7                       1043
#define IDC_RES_8                       1044
#define IDC_RES_9                       1045
#define IDC_RES_CRIT_VARIABLE           1048
#define IDC_RES_CRIT_VAR_VALUE          1049
#define IDC_RES_HIDE_APP                1050
#define IDC_RES_CLOSE_REQUEST           1052
#define IDC_RES_GOTO                    1054
#define IDC_RES_ACTION_VARIABLE         1055
#define IDC_RES_VALUE                   1056
#define IDC_RES_REPORT                  1057
#define IDC_MENU_DESCRIPTION            1058
#define IDC_VAR_PREDEFINED              1059
#define IDC_VAR_CUSTOM_VARIABLE         1060
#define IDC_VAR_ENCRYPT                 1061
#define IDC_VAR_PHONE_SETS_VALUE        1062
#define IDC_VAR_FORMAT                  1063
#define IDC_EDIT2                       1064
#define IDC_VAR_VALUE                   1064
#define IDC_TEXT_G                      1064
#define IDC_PROP_HEIGHT                 1064
#define IDC_RES_BASKET_COST             1064
#define IDC_GRAPHIC_BASKETOPTION        1064
#define IDC_TEXT_R                      1065
#define IDC_TEXT_B                      1066
#define IDC_TEXT_COLOR                  1067
#define IDC_PROP_WIDTH                  1068
#define IDC_TEXT_BASKETOPTION2          1068
#define IDC_LIST_FONT                   1069
#define IDC_LIST_SIZE                   1070
#define IDC_LIST_R                      1071
#define IDC_LIST_G                      1072
#define IDC_LIST_B                      1073
#define IDC_LIST_X                      1074
#define IDC_LIST_Y                      1075
#define IDC_LIST_WIDTH                  1076
#define IDC_LIST_HEIGHT                 1077
#define IDC_LIST_ISALPHA                1078
#define IDC_LIST_MAXLINES               1079
#define IDC_LIST_TABSTOPS               1080
#define IDC_LIST_TEXT                   1081
#define IDC_PROP_STARTINGMENU           1085
#define IDC_COMBO1                      1086
#define IDC_CB_TEXT                     1086
#define IDC_BASKET_ACTION               1086
#define IDC_PROP_COLLECTIONID           1087
#define IDC_RES_BASKET_ID               1088
#define IDC_RES_BASKET_DESCRIPTION      1089
#define IDC_RES_BASKET_TOGGLE           1090
#define IDC_GRAPHIC_VARIABLE            1092
#define IDC_TEXT_VARIABLE               1093
#define IDC_LIST_BASKETOPTION           1094
#define IDC_LIST_VARIABLE               1095
#define IDC_RES_CLEAR                   1096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
