Document: pluto-voicemail-monitor
Title: Debian pluto-voicemail-monitor Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-voicemail-monitor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-voicemail-monitor/pluto-voicemail-monitor.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-voicemail-monitor/pluto-voicemail-monitor.ps.gz

Format: text
Files: /usr/share/doc/pluto-voicemail-monitor/pluto-voicemail-monitor.text.gz

Format: HTML
Index: /usr/share/doc/pluto-voicemail-monitor/html/index.html
Files: /usr/share/doc/pluto-voicemail-monitor/html/*.html
