<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: SDL - Win32 (WCE ARMV4) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\Race\LOCALS~1\Temp\RSP261.tmp" with contents
[
/nologo /W3 /Zi /Od /I "../../include" /I "../../src" /I "../../src/audio" /I "../../src/cdrom" /I "../../src/endian" /I "../../src/events" /I "../../src/file" /I "../../src/joystick" /I "../../src/thread" /I "../../src/thread/win32" /I "../../src/timer" /I "../../src/video" /I "../../src/video/wincommon" /I "../../src/video/windib" /I "../../src/video/windx5" /D "DEBUG" /D "ARM" /D "_ARM_" /D "ARMV4" /D UNDER_CE=420 /D _WIN32_WCE=420 /D "WIN32_PLATFORM_PSPC=400" /D "UNICODE" /D "_UNICODE" /D "WIN32" /D "WINCE" /D "ORBITER" /D "ENABLE_WINDIB" /D "NO_SIGNAL_H" /D "ORBITER_CE_HOOK" /Fo"ARMV4Dbg/" /Fd"ARMV4Dbg/" /GF /c 
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\SDL.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\events\SDL_active.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\audio\SDL_audio.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\audio\SDL_audiocvt.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\audio\SDL_audiodev.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\audio\SDL_audiomem.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_blit.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_blit_0.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_blit_1.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_blit_A.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_blit_N.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_bmp.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\cdrom\SDL_cdrom.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_cursor.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\audio\windib\SDL_dibaudio.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\windib\SDL_dibevents.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\windib\SDL_dibvideo.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\endian\SDL_endian.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\SDL_error.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\events\SDL_events.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\events\SDL_expose.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\SDL_fatal.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_gamma.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\SDL_getenv.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\joystick\SDL_joystick.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\events\SDL_keyboard.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\audio\SDL_mixer.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\events\SDL_mouse.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_pixels.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\events\SDL_quit.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\events\SDL_resize.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_RLEaccel.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\file\SDL_rwops.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_stretch.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_surface.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\cdrom\dummy\SDL_syscdrom.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\wincommon\SDL_sysevents.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\joystick\dummy\SDL_sysjoystick.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\wincommon\SDL_sysmouse.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\thread\win32\SDL_sysmutex.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\thread\win32\SDL_syssem.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\thread\win32\SDL_systhread.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\timer\win32\SDL_systimer.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\wincommon\SDL_syswm.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\thread\SDL_thread.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\timer\SDL_timer.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_video.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\audio\SDL_wave.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\wincommon\SDL_wingl.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_yuv.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_yuv_mmx.c"
"c:\pluto\trunk\CrossPlatform-Libs\SDL-1.2.7\src\video\SDL_yuv_sw.c"
]
Creating command line "clarm.exe @C:\DOCUME~1\Race\LOCALS~1\Temp\RSP261.tmp" 
Creating temporary file "C:\DOCUME~1\Race\LOCALS~1\Temp\RSP262.tmp" with contents
[
commctrl.lib coredll.lib /nologo /base:"0x00100000" /stack:0x10000,0x1000 /entry:"_DllMainCRTStartup" /dll /incremental:yes /pdb:"ARMV4Dbg/SDL.pdb" /debug /nodefaultlib:"libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib" /out:"ARMV4Dbg/SDL.dll" /implib:"ARMV4Dbg/SDL.lib" /subsystem:windowsce,4.20 
".\ARMV4Dbg\SDL.obj"
".\ARMV4Dbg\SDL_active.obj"
".\ARMV4Dbg\SDL_audio.obj"
".\ARMV4Dbg\SDL_audiocvt.obj"
".\ARMV4Dbg\SDL_audiodev.obj"
".\ARMV4Dbg\SDL_audiomem.obj"
".\ARMV4Dbg\SDL_blit.obj"
".\ARMV4Dbg\SDL_blit_0.obj"
".\ARMV4Dbg\SDL_blit_1.obj"
".\ARMV4Dbg\SDL_blit_A.obj"
".\ARMV4Dbg\SDL_blit_N.obj"
".\ARMV4Dbg\SDL_bmp.obj"
".\ARMV4Dbg\SDL_cdrom.obj"
".\ARMV4Dbg\SDL_cursor.obj"
".\ARMV4Dbg\SDL_dibaudio.obj"
".\ARMV4Dbg\SDL_dibevents.obj"
".\ARMV4Dbg\SDL_dibvideo.obj"
".\ARMV4Dbg\SDL_endian.obj"
".\ARMV4Dbg\SDL_error.obj"
".\ARMV4Dbg\SDL_events.obj"
".\ARMV4Dbg\SDL_expose.obj"
".\ARMV4Dbg\SDL_fatal.obj"
".\ARMV4Dbg\SDL_gamma.obj"
".\ARMV4Dbg\SDL_getenv.obj"
".\ARMV4Dbg\SDL_joystick.obj"
".\ARMV4Dbg\SDL_keyboard.obj"
".\ARMV4Dbg\SDL_mixer.obj"
".\ARMV4Dbg\SDL_mouse.obj"
".\ARMV4Dbg\SDL_pixels.obj"
".\ARMV4Dbg\SDL_quit.obj"
".\ARMV4Dbg\SDL_resize.obj"
".\ARMV4Dbg\SDL_RLEaccel.obj"
".\ARMV4Dbg\SDL_rwops.obj"
".\ARMV4Dbg\SDL_stretch.obj"
".\ARMV4Dbg\SDL_surface.obj"
".\ARMV4Dbg\SDL_syscdrom.obj"
".\ARMV4Dbg\SDL_sysevents.obj"
".\ARMV4Dbg\SDL_sysjoystick.obj"
".\ARMV4Dbg\SDL_sysmouse.obj"
".\ARMV4Dbg\SDL_sysmutex.obj"
".\ARMV4Dbg\SDL_syssem.obj"
".\ARMV4Dbg\SDL_systhread.obj"
".\ARMV4Dbg\SDL_systimer.obj"
".\ARMV4Dbg\SDL_syswm.obj"
".\ARMV4Dbg\SDL_thread.obj"
".\ARMV4Dbg\SDL_timer.obj"
".\ARMV4Dbg\SDL_video.obj"
".\ARMV4Dbg\SDL_wave.obj"
".\ARMV4Dbg\SDL_wingl.obj"
".\ARMV4Dbg\SDL_yuv.obj"
".\ARMV4Dbg\SDL_yuv_mmx.obj"
".\ARMV4Dbg\SDL_yuv_sw.obj"
]
Creating command line "link.exe @C:\DOCUME~1\Race\LOCALS~1\Temp\RSP262.tmp"
<h3>Output Window</h3>
Compiling...
SDL.c
SDL_active.c
SDL_audio.c
SDL_audiocvt.c
SDL_audiodev.c
SDL_audiomem.c
SDL_blit.c
SDL_blit_0.c
SDL_blit_1.c
SDL_blit_A.c
SDL_blit_N.c
SDL_bmp.c
SDL_cdrom.c
SDL_cursor.c
SDL_dibaudio.c
SDL_dibevents.c
SDL_dibvideo.c
SDL_endian.c
SDL_error.c
SDL_events.c
Generating Code...
Compiling...
SDL_expose.c
SDL_fatal.c
SDL_gamma.c
SDL_getenv.c
SDL_joystick.c
SDL_keyboard.c
SDL_mixer.c
SDL_mouse.c
SDL_pixels.c
SDL_quit.c
SDL_resize.c
SDL_RLEaccel.c
SDL_rwops.c
SDL_stretch.c
SDL_surface.c
SDL_syscdrom.c
SDL_sysevents.c
SDL_sysjoystick.c
SDL_sysmouse.c
SDL_sysmutex.c
Generating Code...
Compiling...
SDL_syssem.c
SDL_systhread.c
SDL_systimer.c
SDL_syswm.c
SDL_thread.c
SDL_timer.c
SDL_video.c
SDL_wave.c
SDL_wingl.c
SDL_yuv.c
SDL_yuv_mmx.c
SDL_yuv_sw.c
Generating Code...
Linking...
   Creating library ARMV4Dbg/SDL.lib and object ARMV4Dbg/SDL.exp
SDL_blit_A.obj : warning LNK1166: cannot adjust code at offset=0x00001000, rva=0x0000CA64
SDL_blit_N.obj : warning LNK1166: cannot adjust code at offset=0x00001000, rva=0x00016950
SDL_RLEaccel.obj : warning LNK1166: cannot adjust code at offset=0x00001000, rva=0x000319E8





<h3>Results</h3>
SDL.dll - 0 error(s), 3 warning(s)
</pre>
</body>
</html>
