#!/bin/bash

for i in `ls $1 -l |grep ^d | rev | cut -d' ' -f1 | rev`; 
do 

	echo removing directory structure added by documenter for project $i
	rm -fdr $1/$i/${i}_doxygendoc 2>/dev/null
	rm -fdr $1/$i/${i}_doxygenconfig 2>/dev/null

done
