Document: lmce-lighting-plugin
Title: Debian lmce-lighting-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-lighting-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-lighting-plugin/lmce-lighting-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-lighting-plugin/lmce-lighting-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-lighting-plugin/lmce-lighting-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-lighting-plugin/html/index.html
Files: /usr/share/doc/lmce-lighting-plugin/html/*.html
