#!/bin/bash

Print="-print"
if [[ "$(basename "$0")" == "svnfind0" ]]; then
	Print="-print0"
fi

Names=()
for ((i = 1; i <= "$#"; i++)); do
	if [[ "${#Names}" -gt 0 ]]; then
		Names=("${Names[@]}" -or -name "${!i}")
	else
		Names=(-name "${!i}")
	fi
done

find -type d -name .svn -prune -or -type f "${Names[@]}" "$Print"
