#!/bin/bash

NamesSection=n
Params=()
Names=()
for ((i = 2; i <= "$#"; i++)); do
	if [[ "${!i}" == -- ]]; then
		NamesSection=y
	elif [[ "$NamesSection" == n ]]; then
		[[ "${#Params}" -ne 0 ]] && Params=("${Params[@]}" ${!i})
	else
		[[ "${#Names}" -ne 0 ]] && Names=("${Names[@]}" -or -name "${!i}") || Names=(-name "${!i}")
	fi
done

[[ "${#Names}" -ne 0 ]] && Names=('(' "${Names[@]}" ')')

find -type d -name .svn -prune -or -type f "${Names[@]}" -exec grep -nH "${Params[@]}" -- "$1" '{}' ';'
