Document: pluto-telecom
Title: Debian pluto-telecom Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-telecom is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-telecom/pluto-telecom.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-telecom/pluto-telecom.ps.gz

Format: text
Files: /usr/share/doc/pluto-telecom/pluto-telecom.text.gz

Format: HTML
Index: /usr/share/doc/pluto-telecom/html/index.html
Files: /usr/share/doc/pluto-telecom/html/*.html
