Document: pluto-default-tftpboot
Title: Debian pluto-default-tftpboot Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-default-tftpboot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-default-tftpboot/pluto-default-tftpboot.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-default-tftpboot/pluto-default-tftpboot.ps.gz

Format: text
Files: /usr/share/doc/pluto-default-tftpboot/pluto-default-tftpboot.text.gz

Format: HTML
Index: /usr/share/doc/pluto-default-tftpboot/html/index.html
Files: /usr/share/doc/pluto-default-tftpboot/html/*.html

  
