Document: lmce-dpms-monitor
Title: Debian lmce-dpms-monitor Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-dpms-monitor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-dpms-monitor/lmce-dpms-monitor.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-dpms-monitor/lmce-dpms-monitor.ps.gz

Format: text
Files: /usr/share/doc/lmce-dpms-monitor/lmce-dpms-monitor.text.gz

Format: HTML
Index: /usr/share/doc/lmce-dpms-monitor/html/index.html
Files: /usr/share/doc/lmce-dpms-monitor/html/*.html
