#!/bin/bash

if [[ "$1" == configure ]]; then
	. /usr/pluto/bin/SQL_Ops.sh
	. /usr/pluto/bin/Utils.sh

	if [[ -n "$MySqlPassword" ]]; then
		PassParm="-p$MySqlPassword"
	fi

	res=$(mysql --batch --skip-column-names -e "SHOW DATABASES LIKE 'asterisk'" | grep asterisk)
	
	# create asterisk database if it does not exist
	mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm < /usr/share/asterisk/sql/createdb.sql
	# populate new db with our default values
	mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm < /usr/share/asterisk/sql/initialdb.sql

	if [[ -e /usr/sbin/asterisk ]] && [[ "$res" == "asterisk" ]]; then
		adduser www-data asterisk
		
		mkdir -p /var/lib/asterisk/mohmp3
		mkdir -p /var/{log,spool}/asterisk
		
		chmod -R ug+rw /etc/asterisk
		chown -R www-data: /var/lib/asterisk/mohmp3
		chown -R asterisk.asterisk {/usr/share,/var/{log,lib,spool},/etc}/asterisk

		/usr/pluto/bin/db_create_dialplan.sh || :
		/usr/pluto/bin/db_phone_config.sh || :

		service apache2 restart
		service asterisk restart
	fi	

fi
