#!/bin/bash

if [[ "$1" == configure ]]; then
	. /usr/pluto/bin/SQL_Ops.sh
	. /usr/pluto/bin/Utils.sh

	if [[ -n "$MySqlPassword" ]]; then
		PassParm="-p$MySqlPassword"
	fi

	# check if asterisk db exists
	res=$(mysql --batch --skip-column-names -e "SHOW DATABASES LIKE 'asterisk'" | grep asterisk)
	
	# if asterisk db already exists delete some tables and recreate them to make sure they correspond to latest schema
	if [[ "$res" == "asterisk" ]]; then
		mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm -e "use asterisk; ALTER TABLE phonelines ADD isfax ENUM('yes','no') NOT NULL DEFAULT 'no' AFTER enabled;" 2>>/dev/null
		mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm -e "use asterisk; ALTER TABLE phonelines ADD faxmail VARCHAR(50) AFTER password;" 2>>/dev/null
	fi
	
	# recreate asterisk database (except tables which contains user data)
	mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm < /usr/share/asterisk/sql/createdb.sql
	
	# populate new db with our default values
	mysql -f -h "$MySqlHost" -u "$MySqlUser" $PassParm < /usr/share/asterisk/sql/initialdb.sql

	# if asterisk is already installed, and db creation succeded make sure file rights are correct
	if [[ -e /usr/sbin/asterisk ]] && [[ "$res" == "asterisk" ]]; then

		#create asterisk group if it does not yet exist 
		egrep -i "^asterisk" /etc/group >/dev/null 
		if [[ $? -ne 0 ]]; then 
			addgroup asterisk 
		fi 
			 
		#create asterisk account if it does not yet exist
		id -u asterisk >/dev/null 2>/dev/null
		if [[ $? -ne 0 ]]; then
			adduser www-data asterisk
		fi
		
		mkdir -p /var/lib/asterisk/mohmp3
		mkdir -p /var/{log,spool}/asterisk
		
		chmod -R ug+rw /etc/asterisk
		chown -R www-data: /var/lib/asterisk/mohmp3
		chown -R asterisk:asterisk {/usr/share,/var/{log,lib,spool},/etc}/asterisk

		/usr/pluto/bin/db_create_dialplan.sh || :
		/usr/pluto/bin/db_phone_config.sh || :
		

		service apache2 restart
		service asterisk restart
	fi	

fi
