#!/bin/bash -e

if [[ "$1" == configure ]]; then
	. /usr/pluto/bin/SQL_Ops.sh

	asterisk -V >/etc/asterisk/version
	if [[ -n "$MySqlPassword" ]]; then
		PassParm="-p$MySqlPassword"
	fi
	if [[ -z "$(RunSQL "SHOW DATABASES LIKE 'asterisk'")" ]]; then
		RunSQL "CREATE DATABASE IF NOT EXISTS asterisk"
		RunSQL "CREATE DATABASE IF NOT EXISTS asteriskcdrdb"
		RunSQL "GRANT ALL PRIVILEGES ON asterisk.* TO asteriskuser@localhost IDENTIFIED BY 'amp109'"
		RunSQL "GRANT ALL PRIVILEGES ON asteriskcdrdb.* TO asteriskuser@localhost IDENTIFIED BY 'amp109'"

		mysql -h "$MySqlHost" -u "$MySqlUser" $PassParm asteriskcdrdb </usr/share/freepbx/SQL/cdr_mysql_table.sql
		mysql -h "$MySqlHost" -u "$MySqlUser" $PassParm asterisk </usr/share/freepbx/SQL/newinstall.sql
	fi

	/var/lib/freepbx/apply_conf.sh
	asterisk -rx 'reload manager'

	PrevVer="$2"
	#/var/lib/freepbx/upgrade_all.php "$PrevVer"

	UseDB asterisk
	Version=$(RunSQL "SELECT value FROM admin WHERE variable = 'version'")
	echo "$(Field 1 "$Version")" >/var/www/admin/version.txt

	#su - asterisk -c /var/lib/asterisk/bin/bounce_op.sh

	pushd /var/www/admin/modules
	for Module in *; do
		if [[ "$Module" == [._]* || ! -d "$Module" ]]; then
			continue
		fi
		if [[ "$Module" == framework ]]; then
			/var/lib/asterisk/bin/module_admin --no-warnings -f enable "$Module"
		else
			/var/lib/asterisk/bin/module_admin --no-warnings -f install "$Module"
		fi
	done
	popd
	
	RunSQL "UPDATE admin SET value = 'true' WHERE variable = 'need_reload'"
fi
