Document: pluto-system-database
Title: Debian pluto-system-database Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-system-database is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-system-database/pluto-system-database.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-system-database/pluto-system-database.ps.gz

Format: text
Files: /usr/share/doc/pluto-system-database/pluto-system-database.text.gz

Format: HTML
Index: /usr/share/doc/pluto-system-database/html/index.html
Files: /usr/share/doc/pluto-system-database/html/*.html
