#!/bin/sh -e

# Automatically added by dh_dkms
DKMS_NAME=zfs
DKMS_VERSION=0.6.5.9

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section

