Document: pluto-dcerouter
Title: Debian pluto-dcerouter Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-dcerouter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-dcerouter/pluto-dcerouter.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-dcerouter/pluto-dcerouter.ps.gz

Format: text
Files: /usr/share/doc/pluto-dcerouter/pluto-dcerouter.text.gz

Format: HTML
Index: /usr/share/doc/pluto-dcerouter/html/index.html
Files: /usr/share/doc/pluto-dcerouter/html/*.html
