#!/bin/sh

PREREQ=""

# Output pre-requisites
prereqs()
{
	echo "$PREREQ"
}

case "$1" in
    prereqs)
	prereqs
	exit 0
	;;
esac

exec 1>&2

sleep 5
wait_for_udev 10

DT=$(/scripts/DeviceTemplate)

MyIP=`ifconfig eth0 | grep "inet addr" | sed -r 's/^.* inet addr:([0-9.]*).*/\1/g'`
MyMAC=`ifconfig eth0 | grep "HWaddr "  | sed -r 's/^.* HWaddr ([a-zA-Z0-9:]*)/\1/g'`
Gateway=`ip route | grep "default via" | cut -d " " -f3`

#Architecture="i386"
Architecture="armhf"

#Temporarily Removed until amd64 builds are re-instated. -tschak
#if grep -q "^flags.* lm" /proc/cpuinfo ;then
#	Architecture="amd64"
#fi

echo "IP: $MyIP; MAC: $MyMAC; Gateway: $Gateway; Architecture: $Architecture; DT: $DT"
/scripts/interactor "$Gateway" "$MyIP" "$MyMAC" "$Architecture" "$DT"

clear
echo "ERROR: Cannot connect to router, rebooting in 5 seconds.."
sleep 5
reboot
