#<-dceag-mh-b->
GENDEV=../Gen_Devices

SNR_CPPFLAGS ?= <-mkr_t_compile_defines->
SNR_LDFLAGS ?= <-mkr_t_compile_libs->

ROOT = ..
CXX = g++
CXXFLAGS = -Wall -fPIC -ggdb3
CPPFLAGS = -I$(ROOT) -I$(ROOT)/DCE -I/usr/include/mysql $(SNR_CPPFLAGS)
LDFLAGS = $(SNR_LDFLAGS) -L$(ROOT)/lib
BASELDLIBS = -lSerializeClass -lDCECommon -lPlutoUtils -lmysqlclient_r -lpthread

MYNAME = Bluetooth_Dongle
VERSION = 2.0.0
MYDEVTEMPLATEID = 13mplateID

Gen_Dev_Files = $(GENDEV)/Bluetooth_DongleBase.cpp
sources = Main.cpp Bluetooth_Dongle.cpp $(Gen_Dev_Files)
#<-dceag-mh-e->

CXXFLAGS +=
CPPFLAGS += -I/usr/include/SDL -DORBITER -DBLUETOOTH_DONGLE
LDFLAGS +=
XTRALDLIBS = -lVIPCommon -lBDCommon -lSDL_Helpers -lbluetooth -lSDL -lSDL_ttf -lSDL_image -lSGE -lSDL_gfx -lGL -lXrender -ljpeg

#<-mkr_B_use_mysql_wrapper_b->
CPPFLAGS += -I/usr/include/mysql
LDFLAGS += -lmysqlclient_r
#<-mkr_B_use_mysql_wrapper_e->

#<-mkr_b_use_mysql_wrapper_b->
CPPFLAGS += -DUSE_MYSQL_WRAPPER
#<-mkr_b_use_mysql_wrapper_e->


Gen_Dev_Files += $(GENDEV)/OrbiterBase.cpp
sources += \
	OrbiterBluetooth.cpp \
	OrbiterBluetoothCreator.cpp \
	OrbiterRenderer_SDL_Bluetooth.cpp \
	DataGridRenderer_Bluetooth.cpp \
	../Orbiter/OrbiterFileBrowser.cpp \
	../Orbiter/Simulator.cpp \
	../Orbiter/DesignObj_Data.cpp \
	../Orbiter/DesignObj_Orbiter.cpp \
	../Orbiter/DesignObj_DataGrid.cpp \
	../Orbiter/Orbiter.cpp \
	../Orbiter/GraphicBuilder.cpp \
	../Orbiter/RendererMNG.cpp \
	../Orbiter/TextStyle.cpp \
	../Orbiter/CacheImageManager.cpp \
	../Orbiter/RendererOCG.cpp \
	../Orbiter/ScreenHistory.cpp \
	../Orbiter/SDL/SDLRendererOCGHelper.cpp \
	../Orbiter/SDL/SDLGraphic.cpp \
	../Orbiter/SDL/JpegWrapper.cpp \
	../Orbiter/ScreenHandler.cpp \
	../Orbiter/CallBackData.cpp \
	../Orbiter/PlutoGraphic.cpp \
	../Orbiter/OrbiterRenderer.cpp \
	../Orbiter/OrbiterRendererFactory.cpp \
	../Orbiter/SDL/OrbiterRenderer_SDL.cpp \
	../Orbiter/DataGridRenderer.cpp \
	../Orbiter/ObjectRenderer.cpp \
	../Orbiter/ObjectRendererFactory.cpp \
	../Splitter/TextWrapper.cpp \
	../Splitter/TextSplitter.cpp \
	../LIRC_DCE/IRReceiverBase.cpp 

#<-dceag-mf-b->
LDLIBS = $(XTRALDLIBS) $(BASELDLIBS)

whattodo:
	@echo "type 'make bin', 'make so' or 'make all'"

all: bin so

bin: Bluetooth_Dongle

so: Bluetooth_Dongle.so

Bluetooth_Dongle.so: $(sources:.cpp=.o)
	$(CXX) -shared -o $(MYNAME).so $(call cpath,$+) $(LDFLAGS) $(LDLIBS)
	cp $@ ../bin
	chmod +x post_make.sh
	./post_make.sh $@
		
Bluetooth_Dongle: $(sources:.cpp=.o)
	$(CXX) -o $(MYNAME) $(call cpath,$+) $(LDFLAGS) $(LDLIBS)
	cp $@ ../bin
	./post_make.sh $@

clean: clean-recursive
	rm -f $(call cpath,$(sources:.cpp=.o) $(sources:.cpp=.d)) Bluetooth_Dongle.bin Bluetooth_Dongle.so >/dev/null

package:
	chmod +x make_package.sh
	./make_package.sh $(MYNAME) $(VERSION) $(MYDEVTEMPLATEID)

include $(ROOT)/PlutoUtils/make.rules
ifeq (,$(findstring clean, $(MAKECMDGOALS)))
-include $(sources:.cpp=.d)
endif
#<-dceag-mf-e->

