ivtv-objs    := ivtv-driver.o ivtv-fileops.o ivtv-i2c.o ivtv-streams.o \
		ivtv-firmware.o ivtv-reset.o ivtv-gpio.o ivtv-queue.o \
		ivtv-irq.o ivtv-mailbox.o ivtv-vbi.o ivtv-kthreads.o \
		ivtv-audio.o ivtv-ioctl.o ivtv-controls.o ivtv-video.o \
		ivtv-cards.o v4l1-compat.o ivtv-yuv.o
ivtv-fb-objs := ivtv-osd.o ivtv-queue.o

NO_SUP_MODULES := $(shell test $(SUBLEVEL) -ge 15 -a $(PATCHLEVEL) -ge 6 -a "$(CONFIG_VIDEO_DECODER)" -a "$(CONFIG_VIDEO_AUDIO_DECODER)" -a "$(CONFIG_VIDEO_TUNER)" && echo 1)
ifneq ($(NO_SUP_MODULES),1)
cx25840-objs := cx25840-core.o cx25840-audio.o cx25840-firmware.o cx25840-vbi.o

obj-m += msp3400.o saa7115.o cx25840.o wm8775.o saa7127.o cs53l32a.o

ifndef NO_IVTV_TUNER
obj-m += tuner.o tveeprom.o tda9887.o
endif
endif

obj-m += ivtv.o

ifneq ($(CONFIG_FB),)
obj-m += ivtv-fb.o
endif
