ALTER TABLE Command ADD CONSTRAINT FK_Command__FK_CommandCategory__CommandCategory
	FOREIGN KEY (FK_CommandCategory) REFERENCES CommandCategory(PK_CommandCategory)
ALTER TABLE Command_CommandParameter ADD CONSTRAINT FK_Command_CommandParameter__FK_Command__Command
	FOREIGN KEY (FK_Command) REFERENCES Command(PK_Command)
ALTER TABLE Command_CommandParameter ADD CONSTRAINT FK_Command_CommandParameter__FK_CommandParameter__CommandParameter
	FOREIGN KEY (FK_CommandParameter) REFERENCES CommandParameter(PK_CommandParameter)
ALTER TABLE CommandCategory ADD CONSTRAINT FK_CommandCategory__FK_CommandCategory_Parent__CommandCategory
	FOREIGN KEY (FK_CommandCategory_Parent) REFERENCES CommandCategory(PK_CommandCategory)
ALTER TABLE CommandGroup_D_Command ADD CONSTRAINT FK_CommandGroup_D_Command__FK_CommandGroup_D__CommandGroup_D
	FOREIGN KEY (FK_CommandGroup_D) REFERENCES CommandGroup_D(PK_CommandGroup_D)
ALTER TABLE CommandGroup_D_Command ADD CONSTRAINT FK_CommandGroup_D_Command__FK_Command__Command
	FOREIGN KEY (FK_Command) REFERENCES Command(PK_Command)
ALTER TABLE CommandGroup_D_Command ADD CONSTRAINT FK_CommandGroup_D_Command__FK_DeviceTemplate__DeviceTemplate
	FOREIGN KEY (FK_DeviceTemplate) REFERENCES DeviceTemplate(PK_DeviceTemplate)
ALTER TABLE CommandGroup_D_Command_CommandParameter ADD CONSTRAINT FK_CommandGroup_D_Command_CommandParameter__FK_CommandGroup_D_Command__CommandGroup_D_Command
	FOREIGN KEY (FK_CommandGroup_D_Command) REFERENCES CommandGroup_D_Command(PK_CommandGroup_D_Command)
ALTER TABLE CommandGroup_D_Command_CommandParameter ADD CONSTRAINT FK_CommandGroup_D_Command_CommandParameter__FK_CommandParameter__CommandParameter
	FOREIGN KEY (FK_CommandParameter) REFERENCES CommandParameter(PK_CommandParameter)
ALTER TABLE CommandParameter ADD CONSTRAINT FK_CommandParameter__FK_ParameterType__ParameterType
	FOREIGN KEY (FK_ParameterType) REFERENCES ParameterType(PK_ParameterType)
ALTER TABLE Criteria_D ADD CONSTRAINT FK_Criteria_D__FK_CriteriaParmNesting_D__CriteriaParmNesting_D
	FOREIGN KEY (FK_CriteriaParmNesting_D) REFERENCES CriteriaParmNesting_D(PK_CriteriaParmNesting_D)
ALTER TABLE Criteria_D ADD CONSTRAINT FK_Criteria_D__FK_CriteriaList__CriteriaList
	FOREIGN KEY (FK_CriteriaList) REFERENCES CriteriaList(PK_CriteriaList)
ALTER TABLE CriteriaList_CriteriaParmList ADD CONSTRAINT FK_CriteriaList_CriteriaParmList__FK_CriteriaList__CriteriaList
	FOREIGN KEY (FK_CriteriaList) REFERENCES CriteriaList(PK_CriteriaList)
ALTER TABLE CriteriaList_CriteriaParmList ADD CONSTRAINT FK_CriteriaList_CriteriaParmList__FK_CriteriaParmList__CriteriaParmList
	FOREIGN KEY (FK_CriteriaParmList) REFERENCES CriteriaParmList(PK_CriteriaParmList)
ALTER TABLE CriteriaParm_D ADD CONSTRAINT FK_CriteriaParm_D__FK_CriteriaParmNesting_D__CriteriaParmNesting_D
	FOREIGN KEY (FK_CriteriaParmNesting_D) REFERENCES CriteriaParmNesting_D(PK_CriteriaParmNesting_D)
ALTER TABLE CriteriaParm_D ADD CONSTRAINT FK_CriteriaParm_D__FK_CriteriaParmList__CriteriaParmList
	FOREIGN KEY (FK_CriteriaParmList) REFERENCES CriteriaParmList(PK_CriteriaParmList)
ALTER TABLE CriteriaParmList ADD CONSTRAINT FK_CriteriaParmList__FK_ParameterType__ParameterType
	FOREIGN KEY (FK_ParameterType) REFERENCES ParameterType(PK_ParameterType)
ALTER TABLE CriteriaParmNesting_D ADD CONSTRAINT FK_CriteriaParmNesting_D__FK_CriteriaParmNesting_D_Parent__CriteriaParmNesting_D
	FOREIGN KEY (FK_CriteriaParmNesting_D_Parent) REFERENCES CriteriaParmNesting_D(PK_CriteriaParmNesting_D)
ALTER TABLE DesignObj ADD CONSTRAINT FK_DesignObj__FK_DesignObjType__DesignObjType
	FOREIGN KEY (FK_DesignObjType) REFERENCES DesignObjType(PK_DesignObjType)
ALTER TABLE DesignObj ADD CONSTRAINT FK_DesignObj__FK_DesignObjCategory__DesignObjCategory
	FOREIGN KEY (FK_DesignObjCategory) REFERENCES DesignObjCategory(PK_DesignObjCategory)
ALTER TABLE DesignObj ADD CONSTRAINT FK_DesignObj__FK_DesignObj_IncludeIfOtherIncluded__DesignObj
	FOREIGN KEY (FK_DesignObj_IncludeIfOtherIncluded) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjCategory ADD CONSTRAINT FK_DesignObjCategory__FK_DesignObjCategory_Parent__DesignObjCategory
	FOREIGN KEY (FK_DesignObjCategory_Parent) REFERENCES DesignObjCategory(PK_DesignObjCategory)
ALTER TABLE DesignObjParameter ADD CONSTRAINT FK_DesignObjParameter__FK_ParameterType__ParameterType
	FOREIGN KEY (FK_ParameterType) REFERENCES ParameterType(PK_ParameterType)
ALTER TABLE DesignObjType_DesignObjParameter ADD CONSTRAINT FK_DesignObjType_DesignObjParameter__FK_DesignObjType__DesignObjType
	FOREIGN KEY (FK_DesignObjType) REFERENCES DesignObjType(PK_DesignObjType)
ALTER TABLE DesignObjType_DesignObjParameter ADD CONSTRAINT FK_DesignObjType_DesignObjParameter__FK_DesignObjParameter__DesignObjParameter
	FOREIGN KEY (FK_DesignObjParameter) REFERENCES DesignObjParameter(PK_DesignObjParameter)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_DesignObj__DesignObj
	FOREIGN KEY (FK_DesignObj) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_Criteria_D__Criteria_D
	FOREIGN KEY (FK_Criteria_D) REFERENCES Criteria_D(PK_Criteria_D)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_DesignObj_Goto__DesignObj
	FOREIGN KEY (FK_DesignObj_Goto) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_CommandGroup_D_OnActivate__CommandGroup_D
	FOREIGN KEY (FK_CommandGroup_D_OnActivate) REFERENCES CommandGroup_D(PK_CommandGroup_D)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_CommandGroup_D_OnLoad__CommandGroup_D
	FOREIGN KEY (FK_CommandGroup_D_OnLoad) REFERENCES CommandGroup_D(PK_CommandGroup_D)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_CommandGroup_D_OnUnload__CommandGroup_D
	FOREIGN KEY (FK_CommandGroup_D_OnUnload) REFERENCES CommandGroup_D(PK_CommandGroup_D)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_CommandGroup_D_OnTimeout__CommandGroup_D
	FOREIGN KEY (FK_CommandGroup_D_OnTimeout) REFERENCES CommandGroup_D(PK_CommandGroup_D)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_CommandGroup_D_OnStartup__CommandGroup_D
	FOREIGN KEY (FK_CommandGroup_D_OnStartup) REFERENCES CommandGroup_D(PK_CommandGroup_D)
ALTER TABLE DesignObjVariation ADD CONSTRAINT FK_DesignObjVariation__FK_Button__Button
	FOREIGN KEY (FK_Button) REFERENCES Button(PK_Button)
ALTER TABLE DesignObjVariation_DesignObj ADD CONSTRAINT FK_DesignObjVariation_DesignObj__FK_DesignObjVariation_Parent__DesignObjVariation
	FOREIGN KEY (FK_DesignObjVariation_Parent) REFERENCES DesignObjVariation(PK_DesignObjVariation)
ALTER TABLE DesignObjVariation_DesignObj ADD CONSTRAINT FK_DesignObjVariation_DesignObj__FK_DesignObj_Child__DesignObj
	FOREIGN KEY (FK_DesignObj_Child) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjVariation_DesignObj ADD CONSTRAINT FK_DesignObjVariation_DesignObj__FK_DesignObj_InsteadOf__DesignObj
	FOREIGN KEY (FK_DesignObj_InsteadOf) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjVariation_DesignObj ADD CONSTRAINT FK_DesignObjVariation_DesignObj__FK_DesignObj_Up__DesignObj
	FOREIGN KEY (FK_DesignObj_Up) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjVariation_DesignObj ADD CONSTRAINT FK_DesignObjVariation_DesignObj__FK_DesignObj_Down__DesignObj
	FOREIGN KEY (FK_DesignObj_Down) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjVariation_DesignObj ADD CONSTRAINT FK_DesignObjVariation_DesignObj__FK_DesignObj_Left__DesignObj
	FOREIGN KEY (FK_DesignObj_Left) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjVariation_DesignObj ADD CONSTRAINT FK_DesignObjVariation_DesignObj__FK_DesignObj_Right__DesignObj
	FOREIGN KEY (FK_DesignObj_Right) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE DesignObjVariation_DesignObjParameter ADD CONSTRAINT FK_DesignObjVariation_DesignObjParameter__FK_DesignObjVariation__DesignObjVariation
	FOREIGN KEY (FK_DesignObjVariation) REFERENCES DesignObjVariation(PK_DesignObjVariation)
ALTER TABLE DesignObjVariation_DesignObjParameter ADD CONSTRAINT FK_DesignObjVariation_DesignObjParameter__FK_DesignObjParameter__DesignObjParameter
	FOREIGN KEY (FK_DesignObjParameter) REFERENCES DesignObjParameter(PK_DesignObjParameter)
ALTER TABLE DesignObjVariation_Text ADD CONSTRAINT FK_DesignObjVariation_Text__FK_DesignObjVariation__DesignObjVariation
	FOREIGN KEY (FK_DesignObjVariation) REFERENCES DesignObjVariation(PK_DesignObjVariation)
ALTER TABLE DesignObjVariation_Text ADD CONSTRAINT FK_DesignObjVariation_Text__FK_Text__Text
	FOREIGN KEY (FK_Text) REFERENCES Text(PK_Text)
ALTER TABLE DesignObjVariation_Text ADD CONSTRAINT FK_DesignObjVariation_Text__FK_Text_OverrideFromHeader__Text
	FOREIGN KEY (FK_Text_OverrideFromHeader) REFERENCES Text(PK_Text)
ALTER TABLE DesignObjVariation_Text_Skin_Language ADD CONSTRAINT FK_DesignObjVariation_Text_Skin_Language__FK_DesignObjVariation_Text__DesignObjVariation_Text
	FOREIGN KEY (FK_DesignObjVariation_Text) REFERENCES DesignObjVariation_Text(PK_DesignObjVariation_Text)
ALTER TABLE DesignObjVariation_Text_Skin_Language ADD CONSTRAINT FK_DesignObjVariation_Text_Skin_Language__FK_Skin__Skin
	FOREIGN KEY (FK_Skin) REFERENCES Skin(PK_Skin)
ALTER TABLE DesignObjVariation_Text_Skin_Language ADD CONSTRAINT FK_DesignObjVariation_Text_Skin_Language__FK_Language__Language
	FOREIGN KEY (FK_Language) REFERENCES Language(PK_Language)
ALTER TABLE DesignObjVariation_Text_Skin_Language ADD CONSTRAINT FK_DesignObjVariation_Text_Skin_Language__FK_HorizAlignment__HorizAlignment
	FOREIGN KEY (FK_HorizAlignment) REFERENCES HorizAlignment(PK_HorizAlignment)
ALTER TABLE DesignObjVariation_Text_Skin_Language ADD CONSTRAINT FK_DesignObjVariation_Text_Skin_Language__FK_VertAlignment__VertAlignment
	FOREIGN KEY (FK_VertAlignment) REFERENCES VertAlignment(PK_VertAlignment)
ALTER TABLE DesignObjVariation_Text_Skin_Language ADD CONSTRAINT FK_DesignObjVariation_Text_Skin_Language__FK_Style__Style
	FOREIGN KEY (FK_Style) REFERENCES Style(PK_Style)
ALTER TABLE DesignObjVariation_Zone ADD CONSTRAINT FK_DesignObjVariation_Zone__FK_DesignObjVariation__DesignObjVariation
	FOREIGN KEY (FK_DesignObjVariation) REFERENCES DesignObjVariation(PK_DesignObjVariation)
ALTER TABLE DesignObjVariation_Zone ADD CONSTRAINT FK_DesignObjVariation_Zone__FK_Button__Button
	FOREIGN KEY (FK_Button) REFERENCES Button(PK_Button)
ALTER TABLE DesignObjVariation_Zone ADD CONSTRAINT FK_DesignObjVariation_Zone__FK_CommandGroup_D__CommandGroup_D
	FOREIGN KEY (FK_CommandGroup_D) REFERENCES CommandGroup_D(PK_CommandGroup_D)
ALTER TABLE DesignObjVariation_Zone ADD CONSTRAINT FK_DesignObjVariation_Zone__FK_DesignObj_Goto__DesignObj
	FOREIGN KEY (FK_DesignObj_Goto) REFERENCES DesignObj(PK_DesignObj)
ALTER TABLE Installation ADD CONSTRAINT FK_Installation__FK_Version__Version
	FOREIGN KEY (FK_Version) REFERENCES Version(PK_Version)
ALTER TABLE Language ADD CONSTRAINT FK_Language__FK_Language_TextPlacement__Language
	FOREIGN KEY (FK_Language_TextPlacement) REFERENCES Language(PK_Language)
ALTER TABLE Skin ADD CONSTRAINT FK_Skin__FK_Style__Style
	FOREIGN KEY (FK_Style) REFERENCES Style(PK_Style)
ALTER TABLE Skin ADD CONSTRAINT FK_Skin__FK_Skin_TextPlacement__Skin
	FOREIGN KEY (FK_Skin_TextPlacement) REFERENCES Skin(PK_Skin)
ALTER TABLE Style ADD CONSTRAINT FK_Style__FK_Style_Selected__Style
	FOREIGN KEY (FK_Style_Selected) REFERENCES Style(PK_Style)
ALTER TABLE Style ADD CONSTRAINT FK_Style__FK_Style_Highlighted__Style
	FOREIGN KEY (FK_Style_Highlighted) REFERENCES Style(PK_Style)
ALTER TABLE Style ADD CONSTRAINT FK_Style__FK_Style_Alt__Style
	FOREIGN KEY (FK_Style_Alt) REFERENCES Style(PK_Style)
ALTER TABLE StyleVariation ADD CONSTRAINT FK_StyleVariation__FK_Style__Style
	FOREIGN KEY (FK_Style) REFERENCES Style(PK_Style)
ALTER TABLE StyleVariation ADD CONSTRAINT FK_StyleVariation__FK_Skin__Skin
	FOREIGN KEY (FK_Skin) REFERENCES Skin(PK_Skin)
ALTER TABLE StyleVariation ADD CONSTRAINT FK_StyleVariation__FK_Criteria_D__Criteria_D
	FOREIGN KEY (FK_Criteria_D) REFERENCES Criteria_D(PK_Criteria_D)
ALTER TABLE StyleVariation ADD CONSTRAINT FK_StyleVariation__FK_HorizAlignment__HorizAlignment
	FOREIGN KEY (FK_HorizAlignment) REFERENCES HorizAlignment(PK_HorizAlignment)
ALTER TABLE StyleVariation ADD CONSTRAINT FK_StyleVariation__FK_VertAlignment__VertAlignment
	FOREIGN KEY (FK_VertAlignment) REFERENCES VertAlignment(PK_VertAlignment)
ALTER TABLE Text ADD CONSTRAINT FK_Text__FK_TextCategory__TextCategory
	FOREIGN KEY (FK_TextCategory) REFERENCES TextCategory(PK_TextCategory)
ALTER TABLE Text_LS_AltVersions ADD CONSTRAINT FK_Text_LS_AltVersions__FK_Text__Text
	FOREIGN KEY (FK_Text) REFERENCES Text(PK_Text)
ALTER TABLE Text_LS_AltVersions ADD CONSTRAINT FK_Text_LS_AltVersions__FK_Language__Language
	FOREIGN KEY (FK_Language) REFERENCES Language(PK_Language)
ALTER TABLE TextCategory ADD CONSTRAINT FK_TextCategory__FK_TextCategory_Parent__TextCategory
	FOREIGN KEY (FK_TextCategory_Parent) REFERENCES TextCategory(PK_TextCategory)
ALTER TABLE Users ADD CONSTRAINT FK_Users__FK_Language__Language
	FOREIGN KEY (FK_Language) REFERENCES Language(PK_Language)
ALTER TABLE Users ADD CONSTRAINT FK_Users__FK_Installation_Main__Installation
	FOREIGN KEY (FK_Installation_Main) REFERENCES Installation(PK_Installation)
