#!/bin/bash

. /usr/pluto/bin/Config_Ops.sh
. /usr/pluto/bin/Utils.sh

# Make sure the currect NVidia driver is installed
installCorrectNvidiaDriver reboot

if [[ "$AVWizardOverride" == "1" || "$AVWizardDone" != "1" ]] ;then
	ConfSet "AVWizardOverride" "0"
	/usr/pluto/bin/AVWizard_Run.sh 1>/dev/null 2>/dev/null </dev/null
else
	beep -l 50 -f 1000 -n -l 50 -f 1200 -n -l 50 -f 1400 -n -l 50 -f 1600 -n -l 50 -f 1800 -n -l 50 -f 2000 -n -l 50 -f 2200 &
fi

killall WatchGyroRemote 2>/dev/null
