#!/bin/bash
### BEGIN INIT INFO
# Provides:          avwizard
# Required-Start:    check_avwizard
# Required-Stop:
# Should-Start
# Default-Start:     2 3 4 5
# Default-Stop:      1 6
# Short-Description: AVWizard
# Description:       This script starts the AV Wizard
### END INIT INFO #

# Source fuction library
. /lib/lsb/init-functions

CheckAVWizard () {
	if [[ "1" == "$AVWizardOverride" || "1" != "$AVWizardDone" ]] && [[ "1" == "$AutostartMedia" ]] ;then
		## Install driver based on the type of video card used
		CheckVideoDriver

		## Run the AVWizard
		/usr/pluto/bin/AVWizard_Run.sh 1>/dev/null 2>/dev/null </dev/null
		ConfSet "AVWizardOverride" "0"
	else
		beep -l 50 -f 1000 -n -l 50 -f 1200 -n -l 50 -f 1400 -n -l 50 -f 1600 -n -l 50 -f 1800 -n -l 50 -f 2000 -n -l 50 -f 2200 &
	fi
}

start() {
	. /usr/pluto/bin/Utils.sh

	CheckAVWizard
	killall WatchGyroRemote 2>/dev/null
}


### main logic ###
case "$1" in
  start)
	log_daemon_msg "Starting AVWizard" "AVWizard_Run.sh"
        $1
	log_end_msg 0
	retval=0
        ;;
  stop)
        : # noop
	retval=0
        ;;
  status)
        status_of_proc AVWizard_Run.sh AVWizard
	retval=$?
        ;;
  restart|reload)
        : # noop
	retval=0
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        retval=1
esac
exit $retval

