#!/bin/bash
### BEGIN INIT INFO
# Provides:          check_avwizard
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CheckAVWizard
# Description:       This script starts the AV Wizard IF the SHIFT-KEY is pressed during startup.
#
### END INIT INFO #

# Source fuction library
. /lib/lsb/init-functions

check_shift_state() {
	if [[ -x /usr/pluto/bin/WatchGyroRemote ]] ;then
		/usr/pluto/bin/WatchGyroRemote &>/dev/null </dev/null &
	fi

	beep -l 50 -f 2200 -n -l 50 -f 2000 -n -l 50 -f 1800 -n -l 50 -f 1600 -n -l 50 -f 1400 -n -l 50 -f 1200 -n -l 50 -f 1000 &
	sleep 2

	if [[ -x /usr/pluto/bin/shift_state ]] ;then
		if [[ "$( /usr/pluto/bin/shift_state )" == "1" ]] ;then
			beep -l 500
			. /usr/pluto/bin/Config_Ops.sh
			ConfSet "AVWizardOverride" "1"
		fi
	fi
}

workaround_msi() {
	# workaround for the MSI K9NGM3 motherboard
	if lspci -nnv -s 00:07.0 -d 10de:055c|grep -q 1462:7349; then
		set -x
		exec 4>&1 5>&2
		exec 1>>/var/log/pluto/intel-msi-hack.log 2>&1
		date
		modprobe -r snd_hda_intel || :
		modprobe snd_hda_intel model=6stack-dell || :
		set +x
		exec 1>&4 2>&5 4>&- 5>&-
	fi
}

start() {
	check_shift_state
	workaround_msi
}

### main logic ###
case "$1" in
  start)
        log_daemon_msg "Starting AVWizard" "AVWizard_Run.sh"
        $1
        retval=0
        log_end_msg $retval
        ;;
  stop)
        : # noop
        retval=0
        ;;
  status)
        status_of_proc check_avwizard CheckAVWizard
        retval=$?
        ;;
  restart|reload)
        : # noop
        retval=0
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        retval=1
esac
exit $retval

