#!/bin/bash

if [[ -x /usr/pluto/bin/WatchGyroRemote ]] ;then
	 beep -l 50 -f 2200 -n -l 50 -f 2000 -n -l 50 -f 1800 -n -l 50 -f 1600 -n -l 50 -f 1400 -n -l 50 -f 1200 -n -l 50 -f 1000 &
	 /usr/pluto/bin/WatchGyroRemote &>/dev/null </dev/null &
	 sleep 2
fi

if [[ -x /usr/pluto/bin/shift_state ]] ;then
	if [[ "$( /usr/pluto/bin/shift_state )" == "1" ]] ;then
		beep -l 500
		. /usr/pluto/bin/Config_Ops.sh 
		ConfSet "AVWizardOverride" "1"
	fi
fi

# workaround for the MSI K9NGM3 motherboard
if lspci -nnv -s 00:07.0 -d 10de:055c|grep -q 1462:7349; then
	set -x
	exec 4>&1 5>&2
	exec 1>>/var/log/pluto/intel-msi-hack.log 2>&1
	modprobe -r snd_hda_intel || :
	modprobe snd_hda_intel model=6stack-dell || :
	set +x
	exec 1>&4 2>&5 4>&- 5>&-
fi

