Document: lmce-usbuirt
Title: Debian lmce-usbuirt Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-usbuirt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-usbuirt/lmce-usbuirt.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-usbuirt/lmce-usbuirt.ps.gz

Format: text
Files: /usr/share/doc/lmce-usbuirt/lmce-usbuirt.text.gz

Format: HTML
Index: /usr/share/doc/lmce-usbuirt/html/index.html
Files: /usr/share/doc/lmce-usbuirt/html/*.html
