Document: pluto-irbase
Title: Debian pluto-irbase Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-irbase is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-irbase/pluto-irbase.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-irbase/pluto-irbase.ps.gz

Format: text
Files: /usr/share/doc/pluto-irbase/pluto-irbase.text.gz

Format: HTML
Index: /usr/share/doc/pluto-irbase/html/index.html
Files: /usr/share/doc/pluto-irbase/html/*.html
