#!/bin/bash
clear
#Work Area
CURRENT_DIRECTORY=""
CURRENT_SKIN_PATH=""
QML_ROOT=""
QMLDIR_HEADING="# This qmldir file has been automatically generated by makeQmlManifest.sh in qml_root/skins-common/tools. Use that tool to make sure you dont miss anything and please ensure you commit your changes"
target_paths=( "android" "desktop" "rpi" "qt5-desktop" )

function processSkinDirectory(){

echo "Processing $CURRENT_SKIN_PATH" 
cd $CURRENT_SKIN_PATH

if [ -e "qmldir" ]; then
echo "qmldir file exists, updating as needed"
rm qmldir
touch qmldir
echo "$QMLDIR_HEADING" >>  qmldir
echo "Updated qmldir"
else
touch qmldir
echo $$QMLDIR_HEADING >> qmldir
echo "Created Missing qmldir file"
fi
svn add qmldir
for skin in $CURRENT_SKIN_PATH/*
	do
	echo " Processing Item::"$skin

	if [ -f "$skin" ]; then

        currentFileName=$(basename "$skin")
 	currentFileType="${currentFileName##*.}"
	currentFullFileName="${currentFileName%.*}"
#	echo $currentFileType
#	echo $currentFileName
		if [ "$currentFileType" == "qml" ]; then
		QMLDIR_STRING="$currentFullFileName		$currentFileName			#no comment"
		echo "$QMLDIR_STRING" >> qmldir
		else
		echo "Not a .qml file, skipping"
		fi
	else
	echo "Not file, needs inspection"
		
		if [ -d "$skin" ]; then
		echo "Directory"
		cd $skin
			if [ -e qmldir ];then
			rm qmldir
			fi
		touch qmldir
svn add qmldir
		echo "$QMLDIR_HEADING" >> qmldir
			for subFile in "$skin"/*
			do
			currentSubFile=$(basename "$subFile")
			currentSubFileType="${currentSubFileName##*.}"
        		currentSubFileName="${currentSubFile%.*}"
        			if [ -f "$subFile" ] ; then
	                	QMLDIR_STRING="$currentSubFileName             $currentSubFile                        #no comment"
                		echo "$QMLDIR_STRING" >> qmldir
                		else
                		echo "Not a file, skipping"
                		fi
			done
		fi
	fi 

done

#ls -lha
echo "                                       "
cd $QML_ROOT

}

function lookupDir(){

echo "Searching::$CURRENT_DIRECTORY"
#ls -lha $CURRENT_DIRECTORY

#now we go through and find skin directories

for currentDir in $CURRENT_DIRECTORY/*
do

	if [ -d "$currentDir" ]; then
	echo "$currentDir is to be processed"
	CURRENT_SKIN_PATH="$currentDir"
	processSkinDirectory
	else
	echo "$currentDir is a file and will be skipped"
	fi

done

echo "Done with $CURRENT_DIRECTORY"
echo "----------------------------
"

}

#----------
clear
echo "LinuxMCE QML manifest export - Automated qmldir creator"
echo "Switching to qml root"
cd ../../
QML_ROOT=$(pwd)
echo $QML_ROOT" is qml root dir"
echo "Beginning"
echo "Target Paths::" ${target_paths[@]}

for dir in "${target_paths[@]}"
do
TEST_PATH=$(pwd)"/""$dir"
echo $TEST_PATH
CURRENT_DIRECTORY=$TEST_PATH
lookupDir
done





