Document: pluto-updateentarea
Title: Debian pluto-updateentarea Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-updateentarea is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-updateentarea/pluto-updateentarea.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-updateentarea/pluto-updateentarea.ps.gz

Format: text
Files: /usr/share/doc/pluto-updateentarea/pluto-updateentarea.text.gz

Format: HTML
Index: /usr/share/doc/pluto-updateentarea/html/index.html
Files: /usr/share/doc/pluto-updateentarea/html/*.html
