/**
 * Codes used for INotify Sockets in LMCE Game Player
 *
 * Author: Thomas Cherryhomes
 *
 * Version: 1.0
 */

#ifndef INOTIFYCODES_H
#define INOTIFYCODES_H
#define LMCE_INOTIFY_DONE 0x00
#define LMCE_INOTIFY_PAUSE 0x01
#define LMCE_INOTIFY_UNPAUSE 0x02
#define LMCE_INOTIFY_P1START 0x03
#define LMCE_INOTIFY_P2START 0x04
#define LMCE_INOTIFY_P3START 0x05
#define LMCE_INOTIFY_P4START 0x06
#define LMCE_INOTIFY_COIN1 0x07
#define LMCE_INOTIFY_COIN2 0x08
#define LMCE_INOTIFY_PRESS_BUTTON 0x09
#define LMCE_INOTIFY_MOUSE_CLICK 0x0A
#define LMCE_INOTIFY_SET_SPEED 0x0B
#define LMCE_INOTIFY_GET_SNAP 0x0C
#define LMCE_INOTIFY_GOTO_MENU 0x0D
#define LMCE_INOTIFY_UI_UP 0x0E
#define LMCE_INOTIFY_UI_DOWN 0x0F
#define LMCE_INOTIFY_UI_LEFT 0x10
#define LMCE_INOTIFY_UI_RIGHT 0x11
#define LMCE_INOTIFY_UI_OK 0x12
#define LMCE_INOTIFY_PRESS_0 0x13
#define LMCE_INOTIFY_PRESS_1 0x14
#define LMCE_INOTIFY_PRESS_2 0x15
#define LMCE_INOTIFY_PRESS_3 0x16
#define LMCE_INOTIFY_PRESS_4 0x17
#define LMCE_INOTIFY_PRESS_5 0x18
#define LMCE_INOTIFY_PRESS_6 0x19
#define LMCE_INOTIFY_PRESS_7 0x1A
#define LMCE_INOTIFY_PRESS_8 0x1B
#define LMCE_INOTIFY_PRESS_9 0x1C
#define LMCE_INOTIFY_PRESS_ASERISK 0x1D
#define LMCE_INOTIFY_PRESS_POUND 0x1E
#define LMCE_INOTIFY_UI_BACK 0x1F
#define LMCE_INOTIFY_SAVE_STATE 0x20
#define LMCE_INOTIFY_LOAD_STATE 0x21
#define LMCE_INOTIFY_SERVICE_1 0x22
#define LMCE_INOTIFY_SERVICE_2 0x23
#define LMCE_INOTIFY_SELECT_KEY 0x24
#define LMCE_INOTIFY_OPTION_KEY 0x25
#define LMCE_INOTIFY_RESET 0x26
#define LMCE_INOTIFY_RECORD_START 0x27
#define LMCE_INOTIFY_RECORD_STOP 0x28
#define LMCE_INOTIFY_SELECT_A 0x29
#define LMCE_INOTIFY_SELECT_B 0x2A 
#endif
