Document: ffmpeg
Title: Debian ffmpeg Manual
Author: <insert document author here>
Abstract: This manual describes what ffmpeg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ffmpeg/ffmpeg.sgml.gz

Format: postscript
Files: /usr/share/doc/ffmpeg/ffmpeg.ps.gz

Format: text
Files: /usr/share/doc/ffmpeg/ffmpeg.text.gz

Format: HTML
Index: /usr/share/doc/ffmpeg/html/index.html
Files: /usr/share/doc/ffmpeg/html/*.html

  
