#! /bin/sh
#
# postrm script for vdr-plugin-vompserver
#

set -e

case "$1" in
    purge)    
        # delete client specific conf files
        rm -rf /var/lib/vdr/plugins/vompserver/vomp-??-??-??-??-??-??.conf
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
