#!/bin/bash

#set -e

. /usr/pluto/bin/Config_Ops.sh
. /usr/pluto/install/install-core.sh

StatsMessage "Running firstboot_core - Begin"

# run any device specific firstboot add-on scripts here
for f in /usr/pluto/install/firstboot_core_* ; do
	StatsMessage "Running script: ${f}_preinst - Begin"
	. "$f" || :
	$(basename "$f")_preinst || :
	StatsMessage "Running script: ${f}_preinst - End"
done
###########################################################
###########################################################
###########################################################

Nic_Config # setup initial nic config
Configure_Network_Options # determine ip & int/ext if
Configure_Network_Files # write /etc/network/interfaces /etc/hosts
ifup -a || :
TimeUpdate
Create_And_Config_Core # create the core device in the database
Configure_Network_Database # write the network settings to the database

###########################################################
###########################################################
###########################################################
# run any device specific firstboot add-on scripts here
for f in /usr/pluto/install/firstboot_core_* ; do
	StatsMessage "Running script: ${f}_postinst - Begin"
	. "$f" || :
	$(basename "$f")_postinst || :
	StatsMessage "Running script: ${f}_postinst - End"
done

StatsMessage "Running firstboot_core - End"

return 0
