#!/bin/bash

#set -e

. /usr/pluto/bin/Config_Ops.sh
. /usr/pluto/install/install-core.sh

StatsMessage "Running firstboot_core - Begin"

# run any device specific firstboot add-on scripts here
for f in /usr/pluto/install/firstboot_core_* ; do
	StatsMessage "Running script: ${f}_preinst - Begin"
	. "$f" || :
	$(basename "$f")_preinst || :
	StatsMessage "Running script: ${f}_preinst - End"
done
###########################################################
###########################################################
###########################################################

Nic_Config
Configure_Network_Options
Create_And_Config_Core
TimeUpdate

###########################################################
###########################################################
###########################################################
# run any device specific firstboot add-on scripts here
for f in /usr/pluto/install/firstboot_core_* ; do
	StatsMessage "Running script: ${f}_postinst - Begin"
	. "$f" || :
	$(basename "$f")_postinst || :
	StatsMessage "Running script: ${f}_postinst - End"
done

StatsMessage "Running firstboot_core - End"

return 0
