#!/bin/bash

LogFile="/var/log/pluto/firstboot.log"
. /usr/pluto/bin/TeeMyOutput.sh --outfile "$LogFile" --stdboth --append -- "$@"

## Install nvidia-glx if needed
if lshwd | grep -qi 'VGA .* (nv)'; then
	apt-get -y -f install pluto-nvidia-video-drivers
fi
apt-get -f -y dist-upgrade

trap 'rm -f /etc/rc2.d/S89firstboot' EXIT
