#!/bin/sh

scripts/bttv.pl bttv.h bttv-cards.c \
	| perl -ne 's/[ \t]+$//; print' > doc/CARDLIST.bttv

scripts/cx88.pl cx88.h cx88-cards.c \
	| perl -ne 's/[ \t]+$//; print' > doc/CARDLIST.cx88

./scripts/em2820.pl em2820-cards.c \
	| perl -ne 's/[ \t]+$//; print' > doc/CARDLIST.em2820
cat tuner-simple.c \
	| grep "{ \"" \
	| perl -ne '/"([^"]+)"/; printf("tuner=%d - %s\n",$i++,$1)' \
	| perl -ne 's/[ \t]+$//; print' > doc/CARDLIST.tuner

scripts/saa7134.pl saa7134.h saa7134-cards.c \
	| perl -ne 's/[ \t]+$//; print' > doc/CARDLIST.saa7134

