<?php
function securityScenarios($output,$dbADO) {
	// include language files
	include(APPROOT.'/languages/'.$GLOBALS['lang'].'/common.lang.php');
	include(APPROOT.'/languages/'.$GLOBALS['lang'].'/securityScenarios.lang.php');
	
/* @var $dbADO ADOConnection */
/* @var $rs ADORecordSet */

$action = isset($_REQUEST['action'])?cleanString($_REQUEST['action']):'form';
$out='';
$installationID = (int)@$_SESSION['installationID'];
$arrayID = $GLOBALS['ArrayIDForSecurity'];	

$cameraDevices=getDevicesArrayFromCategory($GLOBALS['rootCameras'],$dbADO);
$cameraIDArray=array_keys($cameraDevices);
$deviceGroups=getDeviceGroups($installationID,$dbADO);

if($action=='form') {
	
	$queryArray = 'SELECT * FROM Array WHERE PK_Array=?';	
	$resArray = $dbADO->Execute($queryArray,$arrayID);
	$rowArray=$resArray->FetchRow();

	$out.=setLeftMenu($dbADO);

	$out.='
	<div class="err">'.(isset($_GET['error'])?strip_tags($_GET['error']):'').'</div>
	<div align="center" class="confirm"><B>'.@$_REQUEST['msg'].'</B></div>
	<form action="index.php" method="POST" name="securityScenarios">
		<input type="hidden" name="section" value="securityScenarios">
		<input type="hidden" name="action" value="add">	
		<input type="hidden" name="roomID" value="">	
	
	<table width="100%" cellpadding="4" cellspacing="0" border="0">';
	
	$selectCameraCG='
		SELECT CommandGroup.*,IK_CommandParameter 
		FROM CommandGroup 
			INNER JOIN CommandGroup_Command ON FK_CommandGroup=PK_CommandGroup
			INNER JOIN CommandGroup_Command_CommandParameter ON FK_CommandGroup_Command=PK_CommandGroup_Command
		WHERE FK_Template=? AND FK_Installation=? AND FK_CommandParameter=?';
	$resCameraCG=$dbADO->Execute($selectCameraCG,array($GLOBALS['SecurityViewOneCameraTemplate'],$installationID,$GLOBALS['commandParameterValueToAsign']));
	$camerasCGArray=array();
	while($rowCameraCG=$resCameraCG->FetchRow()){
		$camerasCGArray[$rowCameraCG['IK_CommandParameter']]=$rowCameraCG['PK_CommandGroup'];
	}

	$queryRooms='
		SELECT Room.*, Room.Description AS RoomName FROM Room
		WHERE FK_Installation=?
			ORDER BY Room.Description ASC';
	$resRooms=$dbADO->Execute($queryRooms,$installationID);
	if($resRooms->RecordCount()==0){
		$out.=$TEXT_SS_NO_ROOMS_CONST;
	}
	$displayedCommandGroups=array();
	$displayedRooms=array();
	$displayedRoomNames=array();
	while($rowRooms=$resRooms->FetchRow()){
		
		$displayedRooms[]=$rowRooms['PK_Room'];
		$displayedRoomNames[]=$rowRooms['RoomName'];
		$out.='
		<tr bgcolor="#D1D9EA">
			<td colspan="2"><B>'.$rowRooms['RoomName'].'</B></td>
		</tr>
			<tr>
				<td align="left" colspan="2">'.autogeneratedScenarios($arrayID,0,$dbADO,2,'securityScenarios',$rowRooms['PK_Room']).'</td>
			</tr>';
		$out.='			
			<tr>
				<td></td>
				<td><table width="100%">';
		$selectCommandGroups='
			SELECT * 
			FROM CommandGroup
			INNER JOIN CommandGroup_Room ON FK_CommandGroup=PK_CommandGroup
			WHERE FK_Room=? AND FK_Installation=? AND FK_Template=?';
		$resCommandGroups=$dbADO->Execute($selectCommandGroups,array($rowRooms['PK_Room'],$installationID,$GLOBALS['securityScenariosTemplate']));
		if($resCommandGroups->RecordCount()==0){
		$out.='
			<tr>
				<td colspan="3">'.$TEXT_NO_SECURITY_SCENARIOS_CONST.'</td>
			</tr>';
		}
		while($rowCG=$resCommandGroups->FetchRow()){
			$displayedCommandGroups[]=$rowCG['PK_CommandGroup'];
			
			$queryCheckValidity='
				SELECT 
					FK_CommandParameter,
					CommandGroup_Command_CommandParameter.IK_CommandParameter
				FROM CommandGroup_Command_CommandParameter
				INNER JOIN CommandGroup_Command ON FK_CommandGroup_Command=PK_CommandGroup_Command
				INNER JOIN CommandGroup ON CommandGroup_Command.FK_CommandGroup=PK_CommandGroup
				INNER JOIN CommandGroup_Room ON CommandGroup_Room.FK_CommandGroup=PK_CommandGroup 
				LEFT JOIN Device ON PK_Device=IK_CommandParameter
				WHERE (PK_Device IS NULL AND IK_CommandParameter!=0) AND CommandGroup_Room.FK_Room=? AND CommandGroup.FK_Installation=? AND FK_Template=? AND FK_CommandParameter=5 AND PK_CommandGroup=?';
			$resCV=$dbADO->Execute($queryCheckValidity,array($rowRooms['PK_Room'],$installationID,$GLOBALS['securityScenariosTemplate'],$rowCG['PK_CommandGroup']));
			if($resCV->RecordCount()==0){
				$out.='
				<tr bgcolor="#DDDDDD">
					<td>'.nl2br($rowCG['Description']).'</td>
					<td align="center"><a href="index.php?section=securityScenarios&cgID='.$rowCG['PK_CommandGroup'].'&action=testScenario">'.$TEXT_TEST_CONST.'</a></td>
					<td align="center"><a href="index.php?section=securityScenarios&cgID='.$rowCG['PK_CommandGroup'].'&action=editScenario">'.$TEXT_EDIT_SIMPLE_MODE_CONST.'</a></td>
					<td align="center"><a href="index.php?section=scenarioWizard&cgID='.$rowCG['PK_CommandGroup'].'&wizard=2&from=securityScenarios">'.$TEXT_EDIT_WIZARD_MODE_CONST.'</a></td>
					<td align="center"><a href="#" onClick="javascript:if(confirm(\''.$TEXT_DELETE_SECURITY_SCENARIO_CONFIRMATION_CONST.'\'))self.location=\'index.php?section=securityScenarios&cgDelID='.$rowCG['PK_CommandGroup'].'&action=del\';">'.$TEXT_DELETE_CONST.'</a></td>
				</tr>
				';
			}else{
				$out.='
				<tr bgcolor="#FF9F9F">
					<td>'.$rowCG['Description'].'</td>
					<td align="center" colspan="3">'.$TEXT_INVALID_SECURITY_SCENARIO_CONST.'</td>
					<td align="center">
						<a href="#" onClick="javascript:if(confirm(\''.$TEXT_KEEP_INVALID_SECURITY_SCENARIO_CONFIRMATION_CONST.'\'))self.location=\'index.php?section=securityScenarios&cgKeepID='.$rowCG['PK_CommandGroup'].'&action=keep\';">'.$TEXT_KEEP_CONST.'</a> 
						<a href="#" onClick="javascript:if(confirm(\'Are you sure you want to delete this scenario?\'))self.location=\'index.php?section=securityScenarios&cgDelID='.$rowCG['PK_CommandGroup'].'&action=del\';">'.$TEXT_DELETE_CONST.'</a></td>
				</tr>
				';
			
			}
		}
		$out.='</table><input type="button" class="button" name="newScenario" value="'.$TEXT_NEW_QUAD_CAMERA_SECURITY_SCENARIO_CONST.'" onClick="self.location=\'index.php?section=securityScenarios&roomID='.$rowRooms['PK_Room'].'&RoomName='.urlencode($rowRooms['RoomName']).'&action=addScenario\'">';
	}
	$out.='		</td>
			</tr>';
			$out.='
		</table>
	<input type="hidden" name="displayedRooms" value="'.join(',',$displayedRooms).'">
	<input type="hidden" name="displayedRoomNames" value="'.join(',',$displayedRoomNames).'">	
	<input type="hidden" name="displayedCommandGroups" value="'.join(',',$displayedCommandGroups).'">	
	</form>
	';
							
}elseif($action=='addScenario'){
	$roomID=$_REQUEST['roomID'];
	
	$out.='	<form action="index.php" method="POST" name="securityScenarios">
		<input type="hidden" name="section" value="securityScenarios">
		<input type="hidden" name="action" value="add">	
		<input type="hidden" name="roomID" value="'.$roomID.'">	
		<input type="hidden" name="RoomName" value="'.stripslashes($_REQUEST['RoomName']).'">	
		<table cellpadding="4" cellspacing="0" border="0">
			<tr>
				<td colspan="2"><h3>'.$TEXT_NEW_QUAD_CAMERA_SECURITY_SCENARIO_CONST.'</h3></td>
			</tr>
			<tr>
				<td><B>'.$TEXT_DESCRIPTION_CONST.' *</B></td>
				<td><textarea name="description" style="width:200px;"></textarea></td>
			</tr>
			<tr>
				<td colspan="2"><b>'.$TEXT_SELECT_CAMERAS_FOR_QUAD_VIEW_CONST.':</b></td>
			</tr>';
			$camerasTxt='';
			$xinePlayers=getAssocArray('Device','PK_Device','Description',$dbADO,'WHERE FK_Installation='.$installationID.' AND FK_DeviceTemplate='.$GLOBALS['XinePlayer']);
			$cameraDevices=$cameraDevices+$xinePlayers;
			asort($cameraDevices);
			$devicesRooms=getAssocArray('Device','PK_Device','Room.Description AS Room',$dbADO,'LEFT JOIN Room ON FK_Room=PK_Room WHERE Device.FK_Installation='.$installationID.' AND FK_DeviceTemplate='.$GLOBALS['XinePlayer']);
			foreach($cameraDevices as $cameraID=>$cameraDescription){
				$camerasTxt.='<option value="'.$cameraID.'">'.$cameraDescription.' ['.@$devicesRooms[$cameraID].']</option>';
			}
			
			for($i=1;$i<5;$i++){
				$out.='
				<tr>
					<td><B>'.$TEXT_CAMERA_CONST.' '.$i.': </B></td>
					<td><select name="camera_'.$i.'">
						<option value="0"></option>
						'.$camerasTxt.'						
					</select></td>
				</tr>';
			}
		$out.='	
			<tr>
				<td align="center" colspan="2"><input type="submit" class="button" name="addScenario" value="'.$TEXT_NEW_QUAD_CAMERA_SECURITY_SCENARIO_CONST.'"  > <input type="button" class="button" name="cancel" value="'.$TEXT_CANCEL_CONST.'" onClick="self.location=\'index.php?section=securityScenarios\'"></td>
			</tr>
		</table>
		<em>* '.$TEXT_REQUIRED_FIELDS_CONST.'</em>
			<script>
		 		var frmvalidator = new formValidator("securityScenarios");
 				frmvalidator.addValidation("description","req","'.$TEXT_SECURITY_SCENARIO_DESCRIPTION_REQUIRED_CONST.'");			
			</script>		
	</form>
';
}elseif($action=='editScenario'){

	$cgID=$_REQUEST['cgID'];
	$queryCG='SELECT * FROM CommandGroup WHERE PK_CommandGroup=?';
	$resCG=$dbADO->Execute($queryCG,$cgID);
	$rowCG=$resCG->FetchRow();
	$description=$rowCG['Description'];
	$hint=$rowCG['Hint'];

	$selectCameraCG_C='
		SELECT CommandGroup.PK_CommandGroup, FK_Array,FK_Installation, CommandGroup.Description, IK_CommandParameter, FK_CommandGroup_Command
		FROM CommandGroup 
			INNER JOIN CommandGroup_Command ON FK_CommandGroup=PK_CommandGroup 
			INNER JOIN CommandGroup_Command_CommandParameter ON FK_CommandGroup_Command=PK_CommandGroup_Command 
		WHERE FK_CommandParameter=? AND PK_CommandGroup=?';

	$resCameraCG_C=$dbADO->Execute($selectCameraCG_C,array($GLOBALS['commandParameterListDevice'],$cgID));
	while($rowCameraCG_C=$resCameraCG_C->FetchRow()){
		$oldCameras=explode(',',$rowCameraCG_C['IK_CommandParameter']);
	}

	$out.='	<form action="index.php" method="POST" name="securityScenarios">
		<input type="hidden" name="section" value="securityScenarios">
		<input type="hidden" name="action" value="update">	
		<input type="hidden" name="cgID" value="'.$cgID.'">	
	
		<table cellpadding="4" cellspacing="0" border="0">
			<tr>
				<td colspan="2"><h3>'.$TEXT_EDIT_QUAD_CAMERA_SECURITY_SCENARIO_CONST.'</h3></td>
			</tr>
			<tr>
				<td><B>'.$TEXT_DESCRIPTION_CONST.': </B></td>
				<td><textarea name="description" style="width:200px;" rows="2">'.$description.'</textarea></td>
			</tr>
			<tr>
				<td><B>'.$TEXT_HINT_CONST.': </B></td>
				<td><input type="text" name="hint" value="'.$hint.'"></td>
			</tr>
			<tr>
				<td colspan="2"><b>'.$TEXT_SELECT_CAMERAS_FOR_QUAD_VIEW_CONST.':</b></td>
			</tr>';
			for($cameraNO=1;$cameraNO<5;$cameraNO++){
				$out.='
				<input type="hidden" name="oldCamera_'.$cameraNO.'" value="'.@$oldIDs[$cameraNO].'">
				<input type="hidden" name="oldCameraCG_C_'.$cameraNO.'" value="'.@$CG_CArray[$cameraNO].'">
				<tr>
					<td><B>'.$TEXT_CAMERA_CONST.' '.$cameraNO.': </B></td>
					<td><select name="camera_'.$cameraNO.'">
						<option value="0"></option>';
					$xinePlayers=getAssocArray('Device','PK_Device','Description',$dbADO,'WHERE FK_Installation='.$installationID.' AND FK_DeviceTemplate='.$GLOBALS['XinePlayer']);
					$cameraDevices=$cameraDevices+$xinePlayers;
					asort($cameraDevices);
					foreach($cameraDevices as $cameraID=>$cameraDescription){
						$out.='<option value="'.$cameraID.'" '.(($cameraID==@$oldCameras[$cameraNO-1])?'selected':'').'>'.$cameraDescription.'</option>';
					}
				
				$out.='						
					</select></td>
				</tr>';
			}
		$out.='	
			<tr>
				<td align="center" colspan="2"><input type="submit" class="button" name="editScenario" value="'.$TEXT_UPDATE_QUAD_CAMERA_SECURITY_SCENARIO_CONST.'"> <input type="button" class="button" name="cancel" value="Cancel" onClick="self.location=\'index.php?section=securityScenarios\'"></td>
			</tr>
		</table>
			<script>
		 		var frmvalidator = new formValidator("securityScenarios");
 				frmvalidator.addValidation("description","req","'.$TEXT_SECURITY_SCENARIO_DESCRIPTION_REQUIRED_CONST.'");			
			</script>		
	</form>
';
}elseif($action=='testScenario'){
	
	$cgID=$_REQUEST['cgID'];
	testScenario($cgID);
	
	header("Location: index.php?section=securityScenarios&msg=$TEXT_SECURITY_SCENARIO_TEST_CONST");
	exit();	
}else{
	// check if the user has the right to modify installation
	$canModifyInstallation = getUserCanModifyInstallation($_SESSION['userID'],$_SESSION['installationID'],$dbADO);
	if (!$canModifyInstallation){
		header("Location: index.php?section=securityScenarios&error=$TEXT_NOT_AUTHORISED_TO_MODIFY_INSTALLATION_CONST");
		exit(0);
	}

	if(isset($_GET['cgDelID']) && (int)$_GET['cgDelID']!=0){
		$cgToDelete=(int)$_GET['cgDelID'];
		deleteCommandGroup($cgToDelete,$dbADO);
		setOrbitersNeedConfigure($installationID,$dbADO);
		header("Location: index.php?section=securityScenarios&msg=$TEXT_SECURITY_SCENARIO_DELETED_CONST");
	}

	if(isset($_GET['cgKeepID']) && (int)$_GET['cgKeepID']!=0){
		$cgToKeep=(int)$_GET['cgKeepID'];
		$dbADO->Execute('UPDATE CommandGroup SET FK_Template = NULL WHERE PK_CommandGroup=?',$cgToKeep);
		setOrbitersNeedConfigure($installationID,$dbADO);
		header("Location: index.php?section=securityScenarios&msg=$TEXT_SECURITY_SCENARIO_KEEPED_CONST");
	}

	if(isset($_POST['addScenario'])){
		$roomID=(int)$_REQUEST['roomID'];
		$roomName=stripslashes($_REQUEST['RoomName']);
		$description=cleanString($_POST['description']);
		
		$insertCommandGroup='
			INSERT INTO CommandGroup 
				(FK_Array,FK_Installation,Description,Hint,CanTurnOff,AlwaysShow,CanBeHidden,FK_Template)
			VALUES
				(?,?,?,?,?,?,?,?)';
		$dbADO->Execute($insertCommandGroup,array($arrayID,$installationID,$description,$roomName,0,0,0,$GLOBALS['securityScenariosTemplate']));
		$cgID=$dbADO->Insert_ID();
		setOrbitersNeedConfigure($installationID,$dbADO);		
		$insertCG_Room='
			INSERT INTO CommandGroup_Room 
				(FK_CommandGroup, FK_Room,Sort)
			VALUES
				(?,?,?)';
		$dbADO->Execute($insertCG_Room,array($cgID,$roomID,$cgID));
		$insertCG_C='
			INSERT INTO CommandGroup_Command 
				(FK_CommandGroup,FK_Command,TurnOff,OrderNum,FK_Device)
			VALUES
				(?,?,?,?,?)';
		$insertCG_C_CP='
			INSERT INTO CommandGroup_Command_CommandParameter 
				(FK_CommandGroup_Command,FK_CommandParameter,IK_CommandParameter)
			VALUES
				(?,?,?)';
		
		$dbADO->Execute($insertCG_C,array($cgID,$GLOBALS['GoToScreen'],0,10,$GLOBALS['localOrbiter']));
		$cg_cID=$dbADO->Insert_ID();
		addScenarioCommandParameters($cg_cID,$GLOBALS['GoToScreen'],$dbADO,array($GLOBALS['commandParamPK_Screen']=>17));	

		$cameraDevices=array();
		for($i=1;$i<5;$i++){
			$camera=(int)$_POST['camera_'.$i];
			if($camera>0){
				$cameraDevices[]=$camera;
			}
		}
		addScenarioCommandParameters($cg_cID,$GLOBALS['GoToScreen'],$dbADO,array($GLOBALS['commandParameterListDevice']=>join(',',$cameraDevices)),17);	
		
		$msg=$TEXT_SECURITY_SCENARIO_ADDED_CONST;
	}

	
	
	if(isset($_POST['editScenario'])){
		$description=cleanString($_POST['description']);
		$hint=cleanString($_POST['hint']);

		$cgID=$_REQUEST['cgID'];

		$updateCommandGroup='
			UPDATE CommandGroup SET 
				Description=?,Hint=?
			WHERE
				PK_CommandGroup=?';
		$dbADO->Execute($updateCommandGroup,array($description,$hint,$cgID));
		setOrbitersNeedConfigure($installationID,$dbADO);
		
		$cameraDevices=array();
		for($i=1;$i<5;$i++){
			$camera=(int)$_POST['camera_'.$i];
			if($camera>0){
				$cameraDevices[]=$camera;
			}
		}
		
		$selectCameraCG_C='
		SELECT FK_CommandGroup_Command,FK_CommandParameter
		FROM CommandGroup 
			INNER JOIN CommandGroup_Command ON FK_CommandGroup=PK_CommandGroup 
			INNER JOIN CommandGroup_Command_CommandParameter ON FK_CommandGroup_Command=PK_CommandGroup_Command 
		WHERE FK_CommandParameter=? AND PK_CommandGroup=?';
		$resCameraCG_C=$dbADO->Execute($selectCameraCG_C,array($GLOBALS['commandParameterListDevice'],$cgID));
		if($resCameraCG_C->RecordCount()>0){
			$rowCameraCG_C=$resCameraCG_C->FetchRow();
			$dbADO->Execute('UPDATE CommandGroup_Command_CommandParameter SET IK_CommandParameter=? WHERE FK_CommandGroup_Command=? AND FK_CommandParameter=?',array(join(',',$cameraDevices),$rowCameraCG_C['FK_CommandGroup_Command'],$rowCameraCG_C['FK_CommandParameter']));
		}else{
			$insertCG_C='
				INSERT INTO CommandGroup_Command 
					(FK_CommandGroup,FK_Command,TurnOff,OrderNum,FK_Device)
				VALUES
					(?,?,?,?,?)';
			$insertCG_C_CP='
				INSERT INTO CommandGroup_Command_CommandParameter 
					(FK_CommandGroup_Command,FK_CommandParameter,IK_CommandParameter)
				VALUES
					(?,?,?)';
			
			$dbADO->Execute($insertCG_C,array($cgID,$GLOBALS['GoToScreen'],0,10,$GLOBALS['localOrbiter']));
			$cg_cID=$dbADO->Insert_ID();
			addScenarioCommandParameters($cg_cID,$GLOBALS['GoToScreen'],$dbADO,array($GLOBALS['commandParamPK_Screen']=>17));	
			addScenarioCommandParameters($cg_cID,$GLOBALS['GoToScreen'],$dbADO,array($GLOBALS['commandParameterListDevice']=>join(',',$cameraDevices)),17);	
		}

		$msg=$TEXT_SECURITY_SCENARIO_UPDATED_CONST;
		setOrbitersNeedConfigure($installationID,$dbADO);
		header("Location: index.php?section=securityScenarios&msg=$msg");
		exit();	
	}
	
	
	if(isset($_POST['updateScenario']) || $action=='externalSubmit'){
		$insertCG_C='
			INSERT INTO CommandGroup_Command 
				(FK_CommandGroup,FK_Command,TurnOff,OrderNum, FK_Device)
			VALUES
				(?,?,?,?,?)';
		$insertCG_C_CP='
			INSERT INTO CommandGroup_Command_CommandParameter 
				(FK_CommandGroup_Command,FK_CommandParameter,IK_CommandParameter)
			VALUES
				(?,?,?)';

		$displayedRoomsArray=explode(',',$_POST['displayedRooms']);
		$displayedRoomNamesArray=explode(',',$_POST['displayedRoomNames']);
		
		
		// Update CommandGroups description
		/*
		$displayedCommandGroupsArray=explode(',',$_POST['displayedCommandGroups']);
		foreach($displayedCommandGroupsArray as $commandGroup){
			$description=@$_POST['commandGroup_'.$commandGroup];
			$updateCommandGroup='UPDATE CommandGroup SET Description=? WHERE PK_CommandGroup=?';
			$dbADO->Execute($updateCommandGroup,array($description,$commandGroup));
		}
		*/
		setOrbitersNeedConfigure($installationID,$dbADO);
		$msg=$TEXT_SECURITY_SCENARIO_UPDATED_CONST;
	}
	
	header("Location: index.php?section=securityScenarios&msg=$msg");
}

	$output->setMenuTitle($TEXT_WIZARD_CONST.' |');
	$output->setPageTitle($TEXT_SECURITY_SCENARIOS_CONST);
	$output->setNavigationMenu(array($TEXT_MY_SCENARIOS_CONST=>'index.php?section=myScenarios',$TEXT_SECURITY_SCENARIOS_CONST=>'index.php?section=securityScenarios'));
	$output->setScriptCalendar('null');
	$output->setBody($out);
	$output->setTitle(APPLICATION_NAME.' :: '.$TEXT_SECURITY_SCENARIOS_CONST);
	$output->output();

}
?>
