<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: mnglib - Win32 (WCE ARM) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\DJRobX\LOCALS~1\Temp\RSP84.tmp" with contents
[
/nologo /W3 /Zi /O2 /I "../../../lcms/include" /I "../../../zlib" /I "../../../jpgsrc6b" /D "DEBUG" /D "ARM" /D "_ARM_" /D "NO_ERRNO_H" /D "NO_GETENV" /D _WIN32_WCE=300 /D "WIN32_PLATFORM_PSPC=310" /D UNDER_CE=300 /D "UNICODE" /D "_UNICODE" /D "_LIB" /Fp"ARMDbg/mnglib.pch" /YX /Fo"ARMDbg/" /Fd"ARMDbg/" /MC /c 
"C:\ha\level1\Libraries\zlib\adler32.c"
"C:\ha\level1\Libraries\lcms\src\cmscam97.c"
"C:\ha\level1\Libraries\lcms\src\cmscnvrt.c"
"C:\ha\level1\Libraries\lcms\src\cmsgamma.c"
"C:\ha\level1\Libraries\lcms\src\cmsgmt.c"
"C:\ha\level1\Libraries\lcms\src\cmslut.c"
"C:\ha\level1\Libraries\lcms\src\cmsmatsh.c"
"C:\ha\level1\Libraries\lcms\src\cmspack.c"
"C:\ha\level1\Libraries\lcms\src\cmspcs.c"
"C:\ha\level1\Libraries\lcms\src\cmssamp.c"
"C:\ha\level1\Libraries\lcms\src\cmswtpnt.c"
"C:\ha\level1\Libraries\lcms\src\cmsxform.c"
"C:\ha\level1\Libraries\zlib\compress.c"
"C:\ha\level1\Libraries\zlib\crc32.c"
"C:\ha\level1\Libraries\zlib\deflate.c"
"C:\ha\level1\Libraries\zlib\infblock.c"
"C:\ha\level1\Libraries\zlib\infcodes.c"
"C:\ha\level1\Libraries\zlib\inffast.c"
"C:\ha\level1\Libraries\zlib\inflate.c"
"C:\ha\level1\Libraries\zlib\inftrees.c"
"C:\ha\level1\Libraries\zlib\infutil.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcapimin.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcapistd.c"
"C:\ha\level1\Libraries\jpgsrc6b\jccoefct.c"
"C:\ha\level1\Libraries\jpgsrc6b\jccolor.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcdctmgr.c"
"C:\ha\level1\Libraries\jpgsrc6b\jchuff.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcinit.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcmainct.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcmarker.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcmaster.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcomapi.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcparam.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcphuff.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcprepct.c"
"C:\ha\level1\Libraries\jpgsrc6b\jcsample.c"
"C:\ha\level1\Libraries\jpgsrc6b\jctrans.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdapimin.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdapistd.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdatadst.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdatasrc.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdcoefct.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdcolor.c"
"C:\ha\level1\Libraries\jpgsrc6b\jddctmgr.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdhuff.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdinput.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdmainct.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdmarker.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdmaster.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdmerge.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdphuff.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdpostct.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdsample.c"
"C:\ha\level1\Libraries\jpgsrc6b\jdtrans.c"
"C:\ha\level1\Libraries\jpgsrc6b\jerror.c"
"C:\ha\level1\Libraries\jpgsrc6b\jfdctflt.c"
"C:\ha\level1\Libraries\jpgsrc6b\jfdctfst.c"
"C:\ha\level1\Libraries\jpgsrc6b\jfdctint.c"
"C:\ha\level1\Libraries\jpgsrc6b\jidctflt.c"
"C:\ha\level1\Libraries\jpgsrc6b\jidctfst.c"
"C:\ha\level1\Libraries\jpgsrc6b\jidctint.c"
"C:\ha\level1\Libraries\jpgsrc6b\jidctred.c"
"C:\ha\level1\Libraries\jpgsrc6b\jmemmgr.c"
"C:\ha\level1\Libraries\jpgsrc6b\jmemnobs.c"
"C:\ha\level1\Libraries\jpgsrc6b\jquant1.c"
"C:\ha\level1\Libraries\jpgsrc6b\jquant2.c"
"C:\ha\level1\Libraries\jpgsrc6b\jutils.c"
"C:\ha\level1\Libraries\libmng\libmng_callback_xs.c"
"C:\ha\level1\Libraries\libmng\libmng_chunk_io.c"
"C:\ha\level1\Libraries\libmng\libmng_chunk_prc.c"
"C:\ha\level1\Libraries\libmng\libmng_chunk_xs.c"
"C:\ha\level1\Libraries\libmng\libmng_cms.c"
"C:\ha\level1\Libraries\libmng\libmng_display.c"
"C:\ha\level1\Libraries\libmng\libmng_dither.c"
"C:\ha\level1\Libraries\libmng\libmng_error.c"
"C:\ha\level1\Libraries\libmng\libmng_filter.c"
"C:\ha\level1\Libraries\libmng\libmng_hlapi.c"
"C:\ha\level1\Libraries\libmng\libmng_jpeg.c"
"C:\ha\level1\Libraries\libmng\libmng_object_prc.c"
"C:\ha\level1\Libraries\libmng\libmng_pixels.c"
"C:\ha\level1\Libraries\libmng\libmng_prop_xs.c"
"C:\ha\level1\Libraries\libmng\libmng_read.c"
"C:\ha\level1\Libraries\libmng\libmng_trace.c"
"C:\ha\level1\Libraries\libmng\libmng_write.c"
"C:\ha\level1\Libraries\libmng\libmng_zlib.c"
"C:\ha\level1\Libraries\zlib\maketree.c"
"C:\ha\level1\Libraries\jpgsrc6b\rdbmp.c"
"C:\ha\level1\Libraries\jpgsrc6b\rdcolmap.c"
"C:\ha\level1\Libraries\jpgsrc6b\rdgif.c"
"C:\ha\level1\Libraries\jpgsrc6b\rdppm.c"
"C:\ha\level1\Libraries\jpgsrc6b\rdrle.c"
"C:\ha\level1\Libraries\jpgsrc6b\rdswitch.c"
"C:\ha\level1\Libraries\jpgsrc6b\rdtarga.c"
"C:\ha\level1\Libraries\jpgsrc6b\transupp.c"
"C:\ha\level1\Libraries\zlib\trees.c"
"C:\ha\level1\Libraries\zlib\uncompr.c"
"C:\ha\level1\Libraries\jpgsrc6b\wrbmp.c"
"C:\ha\level1\Libraries\jpgsrc6b\wrgif.c"
"C:\ha\level1\Libraries\jpgsrc6b\wrppm.c"
"C:\ha\level1\Libraries\jpgsrc6b\wrrle.c"
"C:\ha\level1\Libraries\jpgsrc6b\wrtarga.c"
"C:\ha\level1\Libraries\zlib\zutil.c"
]
Creating command line "clarm.exe @C:\DOCUME~1\DJRobX\LOCALS~1\Temp\RSP84.tmp" 
Creating temporary file "C:\DOCUME~1\DJRobX\LOCALS~1\Temp\RSP85.tmp" with contents
[
/nologo /out:"ARMDbg\mnglib.lib" 
.\ARMDbg\adler32.obj
.\ARMDbg\cmscam97.obj
.\ARMDbg\cmscnvrt.obj
.\ARMDbg\cmsgamma.obj
.\ARMDbg\cmsgmt.obj
.\ARMDbg\cmslut.obj
.\ARMDbg\cmsmatsh.obj
.\ARMDbg\cmspack.obj
.\ARMDbg\cmspcs.obj
.\ARMDbg\cmssamp.obj
.\ARMDbg\cmswtpnt.obj
.\ARMDbg\cmsxform.obj
.\ARMDbg\compress.obj
.\ARMDbg\crc32.obj
.\ARMDbg\deflate.obj
.\ARMDbg\infblock.obj
.\ARMDbg\infcodes.obj
.\ARMDbg\inffast.obj
.\ARMDbg\inflate.obj
.\ARMDbg\inftrees.obj
.\ARMDbg\infutil.obj
.\ARMDbg\jcapimin.obj
.\ARMDbg\jcapistd.obj
.\ARMDbg\jccoefct.obj
.\ARMDbg\jccolor.obj
.\ARMDbg\jcdctmgr.obj
.\ARMDbg\jchuff.obj
.\ARMDbg\jcinit.obj
.\ARMDbg\jcmainct.obj
.\ARMDbg\jcmarker.obj
.\ARMDbg\jcmaster.obj
.\ARMDbg\jcomapi.obj
.\ARMDbg\jcparam.obj
.\ARMDbg\jcphuff.obj
.\ARMDbg\jcprepct.obj
.\ARMDbg\jcsample.obj
.\ARMDbg\jctrans.obj
.\ARMDbg\jdapimin.obj
.\ARMDbg\jdapistd.obj
.\ARMDbg\jdatadst.obj
.\ARMDbg\jdatasrc.obj
.\ARMDbg\jdcoefct.obj
.\ARMDbg\jdcolor.obj
.\ARMDbg\jddctmgr.obj
.\ARMDbg\jdhuff.obj
.\ARMDbg\jdinput.obj
.\ARMDbg\jdmainct.obj
.\ARMDbg\jdmarker.obj
.\ARMDbg\jdmaster.obj
.\ARMDbg\jdmerge.obj
.\ARMDbg\jdphuff.obj
.\ARMDbg\jdpostct.obj
.\ARMDbg\jdsample.obj
.\ARMDbg\jdtrans.obj
.\ARMDbg\jerror.obj
.\ARMDbg\jfdctflt.obj
.\ARMDbg\jfdctfst.obj
.\ARMDbg\jfdctint.obj
.\ARMDbg\jidctflt.obj
.\ARMDbg\jidctfst.obj
.\ARMDbg\jidctint.obj
.\ARMDbg\jidctred.obj
.\ARMDbg\jmemmgr.obj
.\ARMDbg\jmemnobs.obj
.\ARMDbg\jquant1.obj
.\ARMDbg\jquant2.obj
.\ARMDbg\jutils.obj
.\ARMDbg\libmng_callback_xs.obj
.\ARMDbg\libmng_chunk_io.obj
.\ARMDbg\libmng_chunk_prc.obj
.\ARMDbg\libmng_chunk_xs.obj
.\ARMDbg\libmng_cms.obj
.\ARMDbg\libmng_display.obj
.\ARMDbg\libmng_dither.obj
.\ARMDbg\libmng_error.obj
.\ARMDbg\libmng_filter.obj
.\ARMDbg\libmng_hlapi.obj
.\ARMDbg\libmng_jpeg.obj
.\ARMDbg\libmng_object_prc.obj
.\ARMDbg\libmng_pixels.obj
.\ARMDbg\libmng_prop_xs.obj
.\ARMDbg\libmng_read.obj
.\ARMDbg\libmng_trace.obj
.\ARMDbg\libmng_write.obj
.\ARMDbg\libmng_zlib.obj
.\ARMDbg\maketree.obj
.\ARMDbg\rdbmp.obj
.\ARMDbg\rdcolmap.obj
.\ARMDbg\rdgif.obj
.\ARMDbg\rdppm.obj
.\ARMDbg\rdrle.obj
.\ARMDbg\rdswitch.obj
.\ARMDbg\rdtarga.obj
.\ARMDbg\transupp.obj
.\ARMDbg\trees.obj
.\ARMDbg\uncompr.obj
.\ARMDbg\wrbmp.obj
.\ARMDbg\wrgif.obj
.\ARMDbg\wrppm.obj
.\ARMDbg\wrrle.obj
.\ARMDbg\wrtarga.obj
.\ARMDbg\zutil.obj
]
Creating command line "link.exe -lib @C:\DOCUME~1\DJRobX\LOCALS~1\Temp\RSP85.tmp"
<h3>Output Window</h3>
Compiling...
adler32.c
cmscam97.c
cmscnvrt.c
cmsgamma.c
cmsgmt.c
cmslut.c
cmsmatsh.c
cmspack.c
cmspcs.c
cmssamp.c
cmswtpnt.c
cmsxform.c
compress.c
crc32.c
deflate.c
infblock.c
infcodes.c
inffast.c
inflate.c
inftrees.c
infutil.c
jcapimin.c
jcapistd.c
jccoefct.c
jccolor.c
jcdctmgr.c
jchuff.c
jcinit.c
jcmainct.c
jcmarker.c
jcmaster.c
jcomapi.c
jcparam.c
jcphuff.c
jcprepct.c
jcsample.c
jctrans.c
jdapimin.c
C:\ha\level1\Libraries\jpgsrc6b\jdapimin.c(42) : warning C4018: '!=' : signed/unsigned mismatch
jdapistd.c
jdatadst.c
jdatasrc.c
jdcoefct.c
jdcolor.c
jddctmgr.c
jdhuff.c
jdinput.c
jdmainct.c
jdmarker.c
jdmaster.c
jdmerge.c
jdphuff.c
jdpostct.c
jdsample.c
jdtrans.c
jerror.c
jfdctflt.c
jfdctfst.c
jfdctint.c
jidctflt.c
jidctfst.c
jidctint.c
jidctred.c
jmemmgr.c
jmemnobs.c
jquant1.c
jquant2.c
jutils.c
libmng_callback_xs.c
libmng_chunk_io.c
libmng_chunk_prc.c
libmng_chunk_xs.c
libmng_cms.c
libmng_display.c
libmng_dither.c
libmng_error.c
libmng_filter.c
libmng_hlapi.c
libmng_jpeg.c
libmng_object_prc.c
libmng_pixels.c
C:\ha\level1\Libraries\libmng\libmng_pixels.c(1125) : warning C4761: integral size mismatch in argument; conversion supplied
C:\ha\level1\Libraries\libmng\libmng_pixels.c(1125) : warning C4761: integral size mismatch in argument; conversion supplied
C:\ha\level1\Libraries\libmng\libmng_pixels.c(1125) : warning C4761: integral size mismatch in argument; conversion supplied
libmng_prop_xs.c
libmng_read.c
libmng_trace.c
libmng_write.c
libmng_zlib.c
maketree.c
rdbmp.c
rdcolmap.c
rdgif.c
rdppm.c
rdrle.c
rdswitch.c
rdtarga.c
transupp.c
trees.c
C:\ha\level1\Libraries\zlib\trees.c(1110) : warning C4018: '<' : signed/unsigned mismatch
uncompr.c
wrbmp.c
wrgif.c
wrppm.c
wrrle.c
wrtarga.c
zutil.c
Creating library...



<h3>Results</h3>
mnglib.lib - 0 error(s), 5 warning(s)
</pre>
</body>
</html>
