Document: lmce-plug-and-play-plugin
Title: Debian lmce-plug-and-play-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-plug-and-play-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-plug-and-play-plugin/lmce-plug-and-play-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-plug-and-play-plugin/lmce-plug-and-play-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-plug-and-play-plugin/lmce-plug-and-play-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-plug-and-play-plugin/html/index.html
Files: /usr/share/doc/lmce-plug-and-play-plugin/html/*.html
