Document: qmediaplayer-player
Title: Debian qmediaplayer-player Manual
Author: <insert document author here>
Abstract: This manual describes what qmediaplayer-player is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qmediaplayer-player/qmediaplayer-player.sgml.gz

Format: postscript
Files: /usr/share/doc/qmediaplayer-player/qmediaplayer-player.ps.gz

Format: text
Files: /usr/share/doc/qmediaplayer-player/qmediaplayer-player.text.gz

Format: HTML
Index: /usr/share/doc/qmediaplayer-player/html/index.html
Files: /usr/share/doc/qmediaplayer-player/html/*.html
