Document: pluto-plutoutils
Title: Debian pluto-plutoutils Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-plutoutils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-plutoutils/pluto-plutoutils.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-plutoutils/pluto-plutoutils.ps.gz

Format: text
Files: /usr/share/doc/pluto-plutoutils/pluto-plutoutils.text.gz

Format: HTML
Index: /usr/share/doc/pluto-plutoutils/html/index.html
Files: /usr/share/doc/pluto-plutoutils/html/*.html
