Document: pluto-slim-server-streamer
Title: Debian pluto-slim-server-streamer Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-slim-server-streamer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-slim-server-streamer/pluto-slim-server-streamer.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-slim-server-streamer/pluto-slim-server-streamer.ps.gz

Format: text
Files: /usr/share/doc/pluto-slim-server-streamer/pluto-slim-server-streamer.text.gz

Format: HTML
Index: /usr/share/doc/pluto-slim-server-streamer/html/index.html
Files: /usr/share/doc/pluto-slim-server-streamer/html/*.html
