Document: pluto-vdr
Title: Debian pluto-vdr Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-vdr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-vdr/pluto-vdr.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-vdr/pluto-vdr.ps.gz

Format: text
Files: /usr/share/doc/pluto-vdr/pluto-vdr.text.gz

Format: HTML
Index: /usr/share/doc/pluto-vdr/html/index.html
Files: /usr/share/doc/pluto-vdr/html/*.html
