Document: pluto-asterisk
Title: Debian pluto-asterisk Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-asterisk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-asterisk/pluto-asterisk.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-asterisk/pluto-asterisk.ps.gz

Format: text
Files: /usr/share/doc/pluto-asterisk/pluto-asterisk.text.gz

Format: HTML
Index: /usr/share/doc/pluto-asterisk/html/index.html
Files: /usr/share/doc/pluto-asterisk/html/*.html
