Document: dce-whisperer
Title: Debian dce-whisperer Manual
Author: <insert document author here>
Abstract: This manual describes what dce-whisperer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dce-whisperer/dce-whisperer.sgml.gz

Format: postscript
Files: /usr/share/doc/dce-whisperer/dce-whisperer.ps.gz

Format: text
Files: /usr/share/doc/dce-whisperer/dce-whisperer.text.gz

Format: HTML
Index: /usr/share/doc/dce-whisperer/html/index.html
Files: /usr/share/doc/dce-whisperer/html/*.html

  
