Document: ushare
Title: Debian ushare Manual
Author: <insert document author here>
Abstract: This manual describes what ushare is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ushare/ushare.sgml.gz

Format: postscript
Files: /usr/share/doc/ushare/ushare.ps.gz

Format: text
Files: /usr/share/doc/ushare/ushare.text.gz

Format: HTML
Index: /usr/share/doc/ushare/html/index.html
Files: /usr/share/doc/ushare/html/*.html

  
