#ifndef __Define_psc_telecom_batdet_H__
#define __Define_psc_telecom_batdet_H__


#define PSC_TELECOM_BATDET_TABLE "psc_telecom_batdet"
#define PSC_TELECOM_BATDET_PK_PSC_TELECOM_BATDET_FIELD "PK_psc_telecom_batdet"
#define PSC_TELECOM_BATDET_PK_PSC_TELECOM_BATDET_TABLE_FIELD "psc_telecom_batdet.PK_psc_telecom_batdet"
#define PSC_TELECOM_BATDET_FK_PSC_TELECOM_BATHDR_FIELD "FK_psc_telecom_bathdr"
#define PSC_TELECOM_BATDET_FK_PSC_TELECOM_BATHDR_TABLE_FIELD "psc_telecom_batdet.FK_psc_telecom_bathdr"
#define PSC_TELECOM_BATDET_TABLENAME_FIELD "Tablename"
#define PSC_TELECOM_BATDET_TABLENAME_TABLE_FIELD "psc_telecom_batdet.Tablename"
#define PSC_TELECOM_BATDET_NEW_FIELD "New"
#define PSC_TELECOM_BATDET_NEW_TABLE_FIELD "psc_telecom_batdet.New"
#define PSC_TELECOM_BATDET_DELETED_FIELD "Deleted"
#define PSC_TELECOM_BATDET_DELETED_TABLE_FIELD "psc_telecom_batdet.Deleted"
#define PSC_TELECOM_BATDET_MODIFIED_FIELD "Modified"
#define PSC_TELECOM_BATDET_MODIFIED_TABLE_FIELD "psc_telecom_batdet.Modified"
#define PSC_TELECOM_BATDET_FK_PSC_TELECOM_BATHDR_ORIG_FIELD "FK_psc_telecom_bathdr_orig"
#define PSC_TELECOM_BATDET_FK_PSC_TELECOM_BATHDR_ORIG_TABLE_FIELD "psc_telecom_batdet.FK_psc_telecom_bathdr_orig"
#define PSC_TELECOM_BATDET_FK_PSC_TELECOM_BATHDR_AUTH_FIELD "FK_psc_telecom_bathdr_auth"
#define PSC_TELECOM_BATDET_FK_PSC_TELECOM_BATHDR_AUTH_TABLE_FIELD "psc_telecom_batdet.FK_psc_telecom_bathdr_auth"
#define PSC_TELECOM_BATDET_FK_PSC_TELECOM_BATHDR_UNAUTH_FIELD "FK_psc_telecom_bathdr_unauth"
#define PSC_TELECOM_BATDET_FK_PSC_TELECOM_BATHDR_UNAUTH_TABLE_FIELD "psc_telecom_batdet.FK_psc_telecom_bathdr_unauth"


#endif

