#ifndef __Define_psc_telecom_tables_H__
#define __Define_psc_telecom_tables_H__


#define PSC_TELECOM_TABLES_TABLE "psc_telecom_tables"
#define PSC_TELECOM_TABLES_PK_PSC_TELECOM_TABLES_FIELD "PK_psc_telecom_tables"
#define PSC_TELECOM_TABLES_PK_PSC_TELECOM_TABLES_TABLE_FIELD "psc_telecom_tables.PK_psc_telecom_tables"
#define PSC_TELECOM_TABLES_TABLENAME_FIELD "Tablename"
#define PSC_TELECOM_TABLES_TABLENAME_TABLE_FIELD "psc_telecom_tables.Tablename"
#define PSC_TELECOM_TABLES_FILTER_FIELD "filter"
#define PSC_TELECOM_TABLES_FILTER_TABLE_FIELD "psc_telecom_tables.filter"
#define PSC_TELECOM_TABLES_FROZEN_FIELD "frozen"
#define PSC_TELECOM_TABLES_FROZEN_TABLE_FIELD "psc_telecom_tables.frozen"
#define PSC_TELECOM_TABLES_ANONYMOUS_FIELD "anonymous"
#define PSC_TELECOM_TABLES_ANONYMOUS_TABLE_FIELD "psc_telecom_tables.anonymous"
#define PSC_TELECOM_TABLES_LAST_PSC_ID_FIELD "last_psc_id"
#define PSC_TELECOM_TABLES_LAST_PSC_ID_TABLE_FIELD "psc_telecom_tables.last_psc_id"
#define PSC_TELECOM_TABLES_LAST_PSC_BATCH_FIELD "last_psc_batch"
#define PSC_TELECOM_TABLES_LAST_PSC_BATCH_TABLE_FIELD "psc_telecom_tables.last_psc_batch"


#endif

