#ifndef __Define_psc_telecom_batuser_H__
#define __Define_psc_telecom_batuser_H__


#define PSC_TELECOM_BATUSER_TABLE "psc_telecom_batuser"
#define PSC_TELECOM_BATUSER_PK_PSC_TELECOM_BATUSER_FIELD "PK_psc_telecom_batuser"
#define PSC_TELECOM_BATUSER_PK_PSC_TELECOM_BATUSER_TABLE_FIELD "psc_telecom_batuser.PK_psc_telecom_batuser"
#define PSC_TELECOM_BATUSER_FK_PSC_TELECOM_BATHDR_FIELD "FK_psc_telecom_bathdr"
#define PSC_TELECOM_BATUSER_FK_PSC_TELECOM_BATHDR_TABLE_FIELD "psc_telecom_batuser.FK_psc_telecom_bathdr"
#define PSC_TELECOM_BATUSER_PSC_USER_FIELD "psc_user"
#define PSC_TELECOM_BATUSER_PSC_USER_TABLE_FIELD "psc_telecom_batuser.psc_user"
#define PSC_TELECOM_BATUSER_IS_SUP_FIELD "is_sup"
#define PSC_TELECOM_BATUSER_IS_SUP_TABLE_FIELD "psc_telecom_batuser.is_sup"
#define PSC_TELECOM_BATUSER_NO_PASS_FIELD "no_pass"
#define PSC_TELECOM_BATUSER_NO_PASS_TABLE_FIELD "psc_telecom_batuser.no_pass"


#endif

