Document: shell-io
Title: Debian shell-io Manual
Author: <insert document author here>
Abstract: This manual describes what shell-io is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shell-io/shell-io.sgml.gz

Format: postscript
Files: /usr/share/doc/shell-io/shell-io.ps.gz

Format: text
Files: /usr/share/doc/shell-io/shell-io.text.gz

Format: HTML
Index: /usr/share/doc/shell-io/html/index.html
Files: /usr/share/doc/shell-io/html/*.html

  
