#!/bin/sh /etc/rc.common

START=51

start() {
	/usr/bin/fiire-ra-daemon.sh	
}

stop() {
	daemon_pid=`ps  | grep 'fiire-ra-daemon.sh' | grep -v grep | awk '{print $1}'`
	if [[ "$daemon_pid" != "" ]] ;then
	        kill -9 "$daemon_pid"
	fi
}
