#!/bin/sh /etc/rc.common

START=61

start() {
	/usr/bin/fiire-ra-daemon.sh	
}

stop() {
	daemon_pid=`ps  | grep 'fiire-ra-daemon.sh' | grep -v grep | awk '{print $1}'`
	if [[ "$daemon_pid" != "" ]] ;then
		for pid in $daemon_pid ;do
		        kill -9 "$pid"
		done
	fi
}
