#!/bin/sh /etc/rc.common

START=50

boot()
{
	if [[ ! -f /etc/pluto/fresh_install ]]; then
		return 0
	fi

	WANif=$(uci get network.wan.ifname)
	WANip=$(ifconfig $WANif | grep 'inet addr' | sed -r 's/^[^0-9.]*([0-9.]+).*$/\1/')

	IPtype=routable
	if [[ -z "$WANip" ]]; then
		IPtype=none
	else
		d1=$(echo "$WANip" | cut -d. -f1)
		d2=$(echo "$WANip" | cut -d. -f2)

		if [[ "$d1" == 10 ]]; then
			IPtype=local
		elif [[ "$d1" == 192 ]] && [[ "$d2" == 168 ]]; then
			IPtype=local
		elif [[ "$d1" == 172 ]] && [[ "$d2" -ge 16 ]] && [[ "$d2" -le 31 ]]; then
			IPtype=local
		fi
	fi

	uci set network.lan.proto=static
	uci set network.lan.ipaddr=192.168.81.1
	uci set network.lan.netmask=255.255.255.0

	Cfg=$(uci show dhcp|grep interface=lan|cut -d. -f2)
	case "$IPtype" in
		local)
			uci set dhcp.$Cfg.ignore=1
			uci set network.wan.proto=none
			uci set network.eth0.vlan0="0 1 2 3 4 5*"
			uci del network.eth0.vlan1
			;;
		none)
			uci set dhcp.$Cfg.ignore=0
			uci set network.eth0.vlan0="1 2 3 4 5*"
			uci set network.eth0.vlan1="0 5"
			;;
		routable)
			uci set dhcp.$Cfg.ignore=0
			uci set network.eth0.vlan0="1 2 3 4 5*"
			uci set network.eth0.vlan1="0 5"
			;;
	esac
	uci commit

	/etc/init.d/network restart
	/etc/init.d/dnsmasq restart
	/etc/init.d/firewall restart

	rm -f /etc/pluto/fresh_install
}
