Document: lmce-game-plugin
Title: Debian lmce-game-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-game-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-game-plugin/lmce-game-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-game-plugin/lmce-game-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-game-plugin/lmce-game-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-game-plugin/html/index.html
Files: /usr/share/doc/lmce-game-plugin/html/*.html
