Document: lmce-datalog
Title: Debian lmce-datalog Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-datalog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-datalog/lmce-datalog.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-datalog/lmce-datalog.ps.gz

Format: text
Files: /usr/share/doc/lmce-datalog/lmce-datalog.text.gz

Format: HTML
Index: /usr/share/doc/lmce-datalog/html/index.html
Files: /usr/share/doc/lmce-datalog/html/*.html
