sources += \
AMixerOptions.cpp \
AMixerParser.cpp \
AVWizardConfParser.cpp \
ColorDesc.cpp \
GenerateWizardConfigDefaults.cpp \
GUIWizardUtils.cpp \
main.cpp \
PageFileParser.cpp \
RefreshRates.cpp \
Resolution.cpp \
ResolutionRefreshScreen.cpp \
SaveSettingsScreen.cpp \
ScreenManager.cpp \
ScreenModes.cpp \
SDLFrontEnd.cpp \
SettingsDictionary.cpp \
SettingsDictionaryTree.cpp \
SoundScreen.cpp \
SoundUtils.cpp \
StartScreen.cpp \
WizardCommandLineParser.cpp \
WizardConfigParser.cpp \
Wizard.cpp \
WizardPage.cpp \
WizardPagesFactory.cpp \
WizardSettings.cpp \
WizardWidgetBase.cpp \
WizardWidgetButton.cpp \
WizardWidgetContainer.cpp \
WizardWidgetEventManager.cpp \
WizardWidgetImage.cpp \
WizardWidgetLabel.cpp \
WizardWidgetListBox.cpp \
WizardWidgetPage.cpp \
WizardWidgetsFactory.cpp \
WM_Event.cpp \
XRandrParser.cpp \
WizardPageWelcome.cpp \
WizardPageVideoRatio.cpp \
WizardPageVideoOutput.cpp \
WizardPageVideoResolution.cpp \
WizardPageAudioConnector.cpp \
WizardPageAudioVolume.cpp \
WizardPageDolbyTest.cpp \
WizardPageDTSTest.cpp \
WizardPageFinalSelections.cpp \
XinePlayer.cpp \
XUtilities.cpp 
