sources += \
PageSequence.cpp \
AVWizardConfParser.cpp \
ColorDesc.cpp \
GenerateWizardConfigDefaults.cpp \
GUIWizardUtils.cpp \
main.cpp \
PageFileParser.cpp \
RefreshRates.cpp \
Resolution.cpp \
SaveSettingsScreen.cpp \
ScreenManager.cpp \
ScreenModes.cpp \
SDLFrontEnd.cpp \
SettingsDictionary.cpp \
SettingsDictionaryTree.cpp \
WizardCommandLineParser.cpp \
WizardConfigParser.cpp \
WizardRemote.cpp \
Wizard.cpp \
WizardPage.cpp \
WizardPagesFactory.cpp \
WizardSettings.cpp \
WizardWidgetBase.cpp \
WizardWidgetButton.cpp \
WizardWidgetContainer.cpp \
WizardWidgetEventManager.cpp \
WizardWidgetBackground.cpp \
WizardWidgetImage.cpp \
WizardWidgetLabel.cpp \
WizardWidgetListBox.cpp \
WizardWidgetPage.cpp \
WizardWidgetScrollList.cpp \
WizardWidgetsFactory.cpp \
WM_Event.cpp \
XRandrParser.cpp \
WizardPageWelcome.cpp \
WizardPageVideoRatio.cpp \
WizardPageVideoResolutionConfirm.cpp \
WizardPageVideoAdjustSize.cpp \
WizardPageAudioConnector.cpp \
WizardPageAudioVolume.cpp \
WizardPageDolbyTest.cpp \
WizardPageDTSTest.cpp \
WizardPageFinalSelections.cpp \
WizardPageUISwitcher.cpp \
XinePlayer.cpp \
SocketRemoteServer.cpp \
SocketRemoteClient.cpp \
SafetyLock.cpp \
ThreadSleeper.cpp \
SkinGenerator.cpp \
GenericBackEnd.cpp \
OpenGLFrontEnd.cpp \
BackEndFactory.cpp \
XUtilities.cpp 
