Document: lmce-orbiter-plugin
Title: Debian lmce-orbiter-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-orbiter-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-orbiter-plugin/lmce-orbiter-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-orbiter-plugin/lmce-orbiter-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-orbiter-plugin/lmce-orbiter-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-orbiter-plugin/html/index.html
Files: /usr/share/doc/lmce-orbiter-plugin/html/*.html
