#!/bin/make

none:


clean:


install:
	mkdir -p $(DESTDIR)/home/public/data/samples
	cp -avR ./UIdiag_sample.mpg $(DESTDIR)/home/public/data/samples/ || true
	cp -avR ./floorplans $(DESTDIR)/home/public/data/samples/ || true
	cp -avR ./media $(DESTDIR)/home/public/data/samples/ || true
	cp -avR ./security $(DESTDIR)/home/public/data/samples/ || true
