Document: qmediaplayer-plugin
Title: Debian qmediaplayer-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what qmediaplayer-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qmediaplayer-plugin/qmediaplayer-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/qmediaplayer-plugin/qmediaplayer-plugin.ps.gz

Format: text
Files: /usr/share/doc/qmediaplayer-plugin/qmediaplayer-plugin.text.gz

Format: HTML
Index: /usr/share/doc/qmediaplayer-plugin/html/index.html
Files: /usr/share/doc/qmediaplayer-plugin/html/*.html
