#ifndef __Define_Type_AttributeType_H__
#define __Define_Type_AttributeType_H__


#define TYPE_ATTRIBUTETYPE_TABLE "Type_AttributeType"
#define TYPE_ATTRIBUTETYPE_FK_TYPE_FIELD "FK_Type"
#define TYPE_ATTRIBUTETYPE_FK_TYPE_TABLE_FIELD "Type_AttributeType.FK_Type"
#define TYPE_ATTRIBUTETYPE_FK_ATTRIBUTETYPE_FIELD "FK_AttributeType"
#define TYPE_ATTRIBUTETYPE_FK_ATTRIBUTETYPE_TABLE_FIELD "Type_AttributeType.FK_AttributeType"
#define TYPE_ATTRIBUTETYPE_IDENTIFIER_FIELD "Identifier"
#define TYPE_ATTRIBUTETYPE_IDENTIFIER_TABLE_FIELD "Type_AttributeType.Identifier"
#define TYPE_ATTRIBUTETYPE_COMBINEASONE_FIELD "CombineAsOne"
#define TYPE_ATTRIBUTETYPE_COMBINEASONE_TABLE_FIELD "Type_AttributeType.CombineAsOne"
#define TYPE_ATTRIBUTETYPE_PSC_ID_FIELD "psc_id"
#define TYPE_ATTRIBUTETYPE_PSC_ID_TABLE_FIELD "Type_AttributeType.psc_id"
#define TYPE_ATTRIBUTETYPE_PSC_BATCH_FIELD "psc_batch"
#define TYPE_ATTRIBUTETYPE_PSC_BATCH_TABLE_FIELD "Type_AttributeType.psc_batch"
#define TYPE_ATTRIBUTETYPE_PSC_USER_FIELD "psc_user"
#define TYPE_ATTRIBUTETYPE_PSC_USER_TABLE_FIELD "Type_AttributeType.psc_user"
#define TYPE_ATTRIBUTETYPE_PSC_FROZEN_FIELD "psc_frozen"
#define TYPE_ATTRIBUTETYPE_PSC_FROZEN_TABLE_FIELD "Type_AttributeType.psc_frozen"
#define TYPE_ATTRIBUTETYPE_PSC_MOD_FIELD "psc_mod"
#define TYPE_ATTRIBUTETYPE_PSC_MOD_TABLE_FIELD "Type_AttributeType.psc_mod"


#endif

