Document: pluto-add-software
Title: Debian pluto-add-software Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-add-software is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-add-software/pluto-add-software.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-add-software/pluto-add-software.ps.gz

Format: text
Files: /usr/share/doc/pluto-add-software/pluto-add-software.text.gz

Format: HTML
Index: /usr/share/doc/pluto-add-software/html/index.html
Files: /usr/share/doc/pluto-add-software/html/*.html
