Document: lmce-telecom-plugin
Title: Debian lmce-telecom-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-telecom-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-telecom-plugin/lmce-telecom-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-telecom-plugin/lmce-telecom-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-telecom-plugin/lmce-telecom-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-telecom-plugin/html/index.html
Files: /usr/share/doc/lmce-telecom-plugin/html/*.html
