obj-m += upd64031a.o upd64083.o saa717x.o wm8739.o

ifeq ($(wildcard $(M)/../v4l-dvb),)
CONFIG_VIDEO_ADV_DEBUG=y
else
include $(M)/../v4l-dvb/v4l/Make.config

CPPFLAGS := -I$(M)/../v4l-dvb/linux/include -I$(M)/../v4l-dvb/v4l $(CPPFLAGS)
endif

CPPFLAGS += -I$(M)/../driver

ifeq ($(CONFIG_VIDEO_ADV_DEBUG),y)
EXTRA_CFLAGS += -DCONFIG_VIDEO_ADV_DEBUG=1
endif
