#!/bin/sh

set -e

. /usr/share/debconf/confmodule

case "$1" in
    purge)
	#These files may have been created during installation
	rm -f /etc/mythtv/mythweb-htaccess
	rm -f /etc/mythtv/mythweb-htaccess.dpkg-old
	rm -f /etc/mythtv/mythweb-digest
    rm -f /etc/apache2/sites-available/mythweb.conf
;;

    remove|upgrade|abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
