#ifndef QTMEDIAPLAYERPLUGIN_GLOBAL_H
#define QTMEDIAPLAYERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTMEDIAPLAYERPLUGIN_LIBRARY)
#  define QTMEDIAPLAYERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTMEDIAPLAYERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMEDIAPLAYERPLUGIN_GLOBAL_H
