# Provisional Makefile for proof-of-concept code; TODO: make it a library or something

all: inotify_class.o
	g++ $(CXXFLAGS) class_test.cpp inotify_class.o -o class_test

clean:
	rm class_test inotify_class.o
