Document: pluto-videolan-client
Title: Debian pluto-videolan-client Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-videolan-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-videolan-client/pluto-videolan-client.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-videolan-client/pluto-videolan-client.ps.gz

Format: text
Files: /usr/share/doc/pluto-videolan-client/pluto-videolan-client.text.gz

Format: HTML
Index: /usr/share/doc/pluto-videolan-client/html/index.html
Files: /usr/share/doc/pluto-videolan-client/html/*.html
