
obj-m += saa7115.o
obj-m += tveeprom.o
obj-m += tuner.o
obj-m += msp3400.o


#  Stuff for Emacs to see, in order to encourage consistent editing style:
#  *** Local Variables: ***
#  *** mode: Makefile ***
#  *** fill-column: 75 ***
#  *** indent-tabs-mode: nil ***
#  *** End: ***

#  Similarly for vim to see:
#  vim:expandtab:textwidth=75
