#!/bin/bash

pushd /usr/pluto/deb-cache
	dpkg-scanpackages -m . /dev/null | tee Packages | gzip -c > Packages.gz
popd

trap 'rm -f /etc/rc2.d/S90firstboot' EXIT

## Reconfigure netowkring
export NPflagReconfNetwork=yes
/usr/pluto/bin/Network_Setup.sh
/etc/init.d/networking restart
/usr/pluto/bin/DHCP_config.sh
/etc/init.d/networking restart
/usr/pluto/bin/Network_Firewall.sh
/usr/pluto/bin/ConfirmInstallation.sh
/usr/pluto/bin/Timezone_Detect.sh

if [[ ! -f /etc/pluto/install_cleandb ]]; then # on upgrade, the old keys are already in place, so keep them
	## Create new set of ssh keys
	rm -f /etc/ssh/ssh_host_*
	dpkg-reconfigure -pcritical openssh-server
fi

## Install nvidia-glx if needed
if lshwd | grep -qi 'VGA .* (nv)'; then
        apt-get -y -f install pluto-nvidia-video-drivers
fi

PostInstPkg=(
	pluto-local-database pluto-media-database pluto-security-database pluto-system-database
	pluto-telecom-database freepbx
)

for Pkg in "${PostInstPkg[@]}"; do
	/var/lib/dpkg/info/"$Pkg".postinst configure
done

. /usr/pluto/bin/SQL_Ops.sh

Queries=(
	"UPDATE Device_DeviceData
		SET IK_DeviceData=15
		WHERE PK_Device IN (
				SELECT PK_Device FROM Device WHERE FK_DeviceTemplate IN (7, 28)
			)
			AND FK_DeviceData=7
	"
	"UPDATE Device_DeviceData SET IK_DeviceData='LMCE_CORE_u0710_i386' WHERE IK_DeviceData='LMCE_CORE_1_1'"
	"UPDATE Device_DeviceData SET IK_DeviceData='LMCE_MD_u0710_i386'   WHERE IK_DeviceData='LMCE_MD_1_1'"
	"UPDATE Device_DeviceData SET IK_DeviceData='0' WHERE FK_DeviceData='234'"
)

for Q in "${Queries[@]}"; do
	RunSQL "$Q"
done
