/* include/config1.h.  Generated from config1.h.in by configure.  */
/* Soundcard configuration for ALSA driver */
/* Copyright (c) by Jaroslav Kysela <perex@perex.cz>, */
/*                  Anders Semb Hermansen <ahermans@vf.telia.no> */

#define CONFIG_SOUND_MODULE 1
/* #undef CONFIG_HAS_IOMEM_MODULE */
/* #undef CONFIG_SOUND_OSS_CORE */
/* #undef CONFIG_M68K_MODULE */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_HWDEP_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
/* #undef CONFIG_SND_JACK */
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_SEQ_DUMMY_MODULE 1
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_PLUGINS 1
#define CONFIG_SND_SEQUENCER_OSS 1
#define CONFIG_SND_RTCTIMER_MODULE 1
/* #undef CONFIG_RTC_MODULE */
#define CONFIG_SND_SEQ_RTCTIMER_DEFAULT 1
/* #undef CONFIG_SND_DYNAMIC_MINORS */
#define CONFIG_SND_SUPPORT_OLD_API 1
#define CONFIG_SND_VERBOSE_PROCFS 1
/* #undef CONFIG_PROC_FS_MODULE */
#define CONFIG_SND_VERBOSE_PRINTK 1
/* #undef CONFIG_SND_DEBUG */
/* #undef CONFIG_SND_DEBUG_VERBOSE */
/* #undef CONFIG_SND_PCM_XRUN_DEBUG */
#define CONFIG_SND_VMASTER 1
/* #undef CONFIG_SND_BIT32_EMUL_MODULE */
/* #undef CONFIG_SND_DEBUG_MEMORY */
/* #undef CONFIG_SND_HPET_MODULE */
/* #undef CONFIG_HPET_MODULE */
/* #undef CONFIG_BROKEN_MODULE */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_OPL3_LIB_MODULE 1
#define CONFIG_SND_OPL4_LIB_MODULE 1
#define CONFIG_SND_VX_LIB_MODULE 1
#define CONFIG_SND_AC97_CODEC_MODULE 1
#define CONFIG_SND_DRIVERS 1
/* #undef CONFIG_SND_PCSP_MODULE */
/* #undef CONFIG_PCSPKR_PLATFORM_MODULE */
/* #undef CONFIG_X86_PC_MODULE */
/* #undef CONFIG_HIGH_RES_TIMERS_MODULE */
/* #undef CONFIG_INPUT_MODULE */
/* #undef CONFIG_EXPERIMENTAL_MODULE */
#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#define CONFIG_SND_MTPAV_MODULE 1
#define CONFIG_SND_MTS64_MODULE 1
/* #undef CONFIG_PARPORT_MODULE */
#define CONFIG_SND_SERIAL_U16550_MODULE 1
#define CONFIG_SND_MPU401_MODULE 1
#define CONFIG_SND_PORTMAN2X4_MODULE 1
/* #undef CONFIG_SND_ML403_AC97CR_MODULE */
/* #undef CONFIG_XILINX_VIRTEX_MODULE */
/* #undef CONFIG_SND_AC97_POWER_SAVE */
/* #undef CONFIG_SND_AC97_POWER_SAVE_DEFAULT */
/* #undef CONFIG_SND_SERIALMIDI_MODULE */
#define CONFIG_SND_LOOPBACK_MODULE 1
#define CONFIG_SND_WSS_LIB_MODULE 1
#define CONFIG_SND_SB_COMMON_MODULE 1
#define CONFIG_SND_SB8_DSP_MODULE 1
#define CONFIG_SND_SB16_DSP_MODULE 1
#define CONFIG_SND_ISA 1
/* #undef CONFIG_ISA_MODULE */
/* #undef CONFIG_ISA_DMA_API_MODULE */
#define CONFIG_SND_ADLIB_MODULE 1
#define CONFIG_SND_AD1816A_MODULE 1
/* #undef CONFIG_PNP_MODULE */
/* #undef CONFIG_ISAPNP_MODULE */
#define CONFIG_SND_AD1848_MODULE 1
#define CONFIG_SND_ALS100_MODULE 1
#define CONFIG_SND_AZT2320_MODULE 1
#define CONFIG_SND_CMI8330_MODULE 1
#define CONFIG_SND_CS4231_MODULE 1
#define CONFIG_SND_CS4232_MODULE 1
#define CONFIG_SND_CS4236_MODULE 1
#define CONFIG_SND_DT019X_MODULE 1
#define CONFIG_SND_ES968_MODULE 1
#define CONFIG_SND_ES1688_MODULE 1
#define CONFIG_SND_ES18XX_MODULE 1
/* #undef CONFIG_SND_SC6000_MODULE */
/* #undef CONFIG_HAS_IOPORT_MODULE */
#define CONFIG_SND_GUSCLASSIC_MODULE 1
#define CONFIG_SND_GUSEXTREME_MODULE 1
#define CONFIG_SND_GUSMAX_MODULE 1
#define CONFIG_SND_INTERWAVE_MODULE 1
#define CONFIG_SND_INTERWAVE_STB_MODULE 1
#define CONFIG_SND_OPL3SA2_MODULE 1
#define CONFIG_SND_OPTI92X_AD1848_MODULE 1
#define CONFIG_SND_OPTI92X_CS4231_MODULE 1
#define CONFIG_SND_OPTI93X_MODULE 1
#define CONFIG_SND_MIRO_MODULE 1
#define CONFIG_SND_SB8_MODULE 1
#define CONFIG_SND_SB16_MODULE 1
#define CONFIG_SND_SBAWE_MODULE 1
#define CONFIG_SND_SB16_CSP 1
/* #undef CONFIG_PPC_MODULE */
/* #undef CONFIG_FW_LOADER_MODULE */
#define CONFIG_SND_SGALAXY_MODULE 1
#define CONFIG_SND_SSCAPE_MODULE 1
#define CONFIG_SND_WAVEFRONT_MODULE 1
#define CONFIG_SND_WAVEFRONT_FIRMWARE_IN_KERNEL 1
/* #undef CONFIG_SND_PC98_CS4232_MODULE */
/* #undef CONFIG_X86_PC9800_MODULE */
/* #undef CONFIG_SND_MSND_PINNACLE_MODULE */
/* #undef CONFIG_X86_MODULE */
#define CONFIG_SND_PCI 1
/* #undef CONFIG_PCI_MODULE */
#define CONFIG_SND_AD1889_MODULE 1
#define CONFIG_SND_ALS300_MODULE 1
#define CONFIG_SND_ALS4000_MODULE 1
#define CONFIG_SND_ALI5451_MODULE 1
#define CONFIG_SND_ATIIXP_MODULE 1
#define CONFIG_SND_ATIIXP_MODEM_MODULE 1
#define CONFIG_SND_AU8810_MODULE 1
#define CONFIG_SND_AU8820_MODULE 1
#define CONFIG_SND_AU8830_MODULE 1
#define CONFIG_SND_AW2_MODULE 1
#define CONFIG_SND_AZT3328_MODULE 1
#define CONFIG_SND_BT87X_MODULE 1
#define CONFIG_SND_BT87X_OVERCLOCK 1
#define CONFIG_SND_CA0106_MODULE 1
#define CONFIG_SND_CMIPCI_MODULE 1
#define CONFIG_SND_OXYGEN_LIB_MODULE 1
#define CONFIG_SND_OXYGEN_MODULE 1
#define CONFIG_SND_CS4281_MODULE 1
#define CONFIG_SND_CS46XX_MODULE 1
#define CONFIG_SND_CS46XX_NEW_DSP 1
#define CONFIG_SND_CS5530_MODULE 1
/* #undef CONFIG_SND_CS5535AUDIO_MODULE */
/* #undef CONFIG_X86_64_MODULE */
#define CONFIG_SND_DARLA20_MODULE 1
#define CONFIG_SND_GINA20_MODULE 1
#define CONFIG_SND_LAYLA20_MODULE 1
#define CONFIG_SND_DARLA24_MODULE 1
#define CONFIG_SND_GINA24_MODULE 1
#define CONFIG_SND_LAYLA24_MODULE 1
#define CONFIG_SND_MONA_MODULE 1
#define CONFIG_SND_MIA_MODULE 1
#define CONFIG_SND_ECHO3G_MODULE 1
#define CONFIG_SND_INDIGO_MODULE 1
#define CONFIG_SND_INDIGOIO_MODULE 1
#define CONFIG_SND_INDIGODJ_MODULE 1
#define CONFIG_SND_EMU10K1_MODULE 1
#define CONFIG_SND_EMU10K1X_MODULE 1
#define CONFIG_SND_ENS1370_MODULE 1
#define CONFIG_SND_ENS1371_MODULE 1
#define CONFIG_SND_ES1938_MODULE 1
#define CONFIG_SND_ES1968_MODULE 1
#define CONFIG_SND_FM801_MODULE 1
#define CONFIG_SND_FM801_TEA575X_BOOL 1
/* #undef CONFIG_VIDEO_V4L1_MODULE */
/* #undef CONFIG_SND_FM801_TEA575X_MODULE */
#define CONFIG_SND_HDA_INTEL_MODULE 1
#define CONFIG_SND_HDA_HWDEP 1
#define CONFIG_SND_HDA_INPUT_BEEP 1
#define CONFIG_SND_HDA_CODEC_REALTEK 1
#define CONFIG_SND_HDA_CODEC_ANALOG 1
#define CONFIG_SND_HDA_CODEC_SIGMATEL 1
#define CONFIG_SND_HDA_CODEC_VIA 1
#define CONFIG_SND_HDA_CODEC_ATIHDMI 1
#define CONFIG_SND_HDA_CODEC_NVHDMI 1
#define CONFIG_SND_HDA_CODEC_CONEXANT 1
#define CONFIG_SND_HDA_CODEC_CMEDIA 1
#define CONFIG_SND_HDA_CODEC_SI3054 1
#define CONFIG_SND_HDA_GENERIC 1
#define CONFIG_SND_HDA_POWER_SAVE 1
#define CONFIG_SND_HDA_POWER_SAVE_DEFAULT 0
#define CONFIG_SND_HDSP_MODULE 1
#define CONFIG_SND_HDSPM_MODULE 1
#define CONFIG_SND_HIFIER_MODULE 1
#define CONFIG_SND_ICE1712_MODULE 1
#define CONFIG_SND_ICE1724_MODULE 1
#define CONFIG_SND_INTEL8X0_MODULE 1
#define CONFIG_SND_INTEL8X0M_MODULE 1
#define CONFIG_SND_KORG1212_MODULE 1
#define CONFIG_SND_MAESTRO3_MODULE 1
#define CONFIG_SND_MIXART_MODULE 1
#define CONFIG_SND_NM256_MODULE 1
#define CONFIG_SND_PCXHR_MODULE 1
#define CONFIG_SND_RIPTIDE_MODULE 1
#define CONFIG_SND_RME32_MODULE 1
#define CONFIG_SND_RME96_MODULE 1
#define CONFIG_SND_RME9652_MODULE 1
/* #undef CONFIG_SND_SIS7019_MODULE */
#define CONFIG_SND_SONICVIBES_MODULE 1
#define CONFIG_SND_TRIDENT_MODULE 1
#define CONFIG_SND_VIA82XX_MODULE 1
#define CONFIG_SND_VIA82XX_MODEM_MODULE 1
#define CONFIG_SND_VIRTUOSO_MODULE 1
#define CONFIG_SND_VX222_MODULE 1
#define CONFIG_SND_YMFPCI_MODULE 1
#define CONFIG_SND_PDPLUS_MODULE 1
/* #undef CONFIG_SND_ASIHPI_MODULE */
/* #undef CONFIG_SND_PPC */
/* #undef CONFIG_PPC64_MODULE */
/* #undef CONFIG_PPC32_MODULE */
/* #undef CONFIG_SND_POWERMAC_MODULE */
/* #undef CONFIG_I2C_MODULE */
/* #undef CONFIG_PPC_PMAC_MODULE */
/* #undef CONFIG_SND_POWERMAC_AUTO_DRC */
/* #undef CONFIG_SND_PS3_MODULE */
/* #undef CONFIG_PS3_PS3AV_MODULE */
/* #undef CONFIG_SND_PS3_DEFAULT_START_DELAY */
/* #undef CONFIG_SND_AOA_MODULE */
/* #undef CONFIG_SND_AOA_FABRIC_LAYOUT_MODULE */
/* #undef CONFIG_SND_AOA_ONYX_MODULE */
/* #undef CONFIG_I2C_POWERMAC_MODULE */
/* #undef CONFIG_SND_AOA_TAS_MODULE */
/* #undef CONFIG_SND_AOA_TOONIE_MODULE */
/* #undef CONFIG_SND_AOA_SOUNDBUS_MODULE */
/* #undef CONFIG_SND_AOA_SOUNDBUS_I2S_MODULE */
/* #undef CONFIG_SND_ARM */
/* #undef CONFIG_ARM_MODULE */
/* #undef CONFIG_SND_SA11XX_UDA1341_MODULE */
/* #undef CONFIG_ARCH_SA1100_MODULE */
/* #undef CONFIG_L3_MODULE */
/* #undef CONFIG_SND_ARMAACI_MODULE */
/* #undef CONFIG_ARM_AMBA_MODULE */
/* #undef CONFIG_SND_PXA2XX_PCM_MODULE */
/* #undef CONFIG_SND_PXA2XX_LIB_MODULE */
/* #undef CONFIG_SND_PXA2XX_LIB_AC97 */
/* #undef CONFIG_SND_PXA2XX_AC97_MODULE */
/* #undef CONFIG_ARCH_PXA_MODULE */
/* #undef CONFIG_SND_S3C2410_MODULE */
/* #undef CONFIG_ARCH_S3C2410_MODULE */
/* #undef CONFIG_I2C_SENSOR_MODULE */
/* #undef CONFIG_SND_PXA2XX_I2SOUND_MODULE */
/* #undef CONFIG_SND_SPI */
/* #undef CONFIG_SPI_MODULE */
/* #undef CONFIG_SND_AT73C213_MODULE */
/* #undef CONFIG_ATMEL_SSC_MODULE */
/* #undef CONFIG_SND_AT73C213_TARGET_BITRATE */
/* #undef CONFIG_SND_MIPS */
/* #undef CONFIG_MIPS_MODULE */
/* #undef CONFIG_SND_SGI_O2_MODULE */
/* #undef CONFIG_SGI_IP32_MODULE */
/* #undef CONFIG_SND_SGI_HAL2_MODULE */
/* #undef CONFIG_SGI_HAS_HAL2_MODULE */
/* #undef CONFIG_SND_AU1X00_MODULE */
/* #undef CONFIG_SOC_AU1000_MODULE */
/* #undef CONFIG_SOC_AU1100_MODULE */
/* #undef CONFIG_SOC_AU1500_MODULE */
/* #undef CONFIG_SND_SUPERH */
/* #undef CONFIG_SUPERH_MODULE */
/* #undef CONFIG_SND_AICA_MODULE */
/* #undef CONFIG_SH_DREAMCAST_MODULE */
#define CONFIG_SND_USB 1
/* #undef CONFIG_USB_MODULE */
#define CONFIG_SND_USB_AUDIO_MODULE 1
/* #undef CONFIG_SND_USB_USX2Y_MODULE */
/* #undef CONFIG_ALPHA_MODULE */
#define CONFIG_SND_USB_CAIAQ_MODULE 1
#define CONFIG_SND_USB_CAIAQ_INPUT 1
/* #undef CONFIG_SND_USB_US122L_MODULE */
#define CONFIG_SND_PCMCIA 1
/* #undef CONFIG_PCMCIA_MODULE */
#define CONFIG_SND_VXPOCKET_MODULE 1
#define CONFIG_SND_PDAUDIOCF_MODULE 1
/* #undef CONFIG_SND_SPARC */
/* #undef CONFIG_SPARC_MODULE */
/* #undef CONFIG_SND_SUN_AMD7930_MODULE */
/* #undef CONFIG_SBUS_MODULE */
/* #undef CONFIG_SND_SUN_CS4231_MODULE */
/* #undef CONFIG_SND_SUN_DBRI_MODULE */
/* #undef CONFIG_SND_GSC */
/* #undef CONFIG_GSC_MODULE */
/* #undef CONFIG_SND_HARMONY_MODULE */
#define CONFIG_SND_SOC_MODULE 1
/* #undef CONFIG_SND_SOC_AC97_BUS */
/* #undef CONFIG_SND_AT32_SOC_MODULE */
/* #undef CONFIG_AVR32_MODULE */
/* #undef CONFIG_SND_AT32_SOC_SSC_MODULE */
/* #undef CONFIG_SND_AT32_SOC_PLAYPAQ_MODULE */
/* #undef CONFIG_BOARD_PLAYPAQ_MODULE */
/* #undef CONFIG_SND_AT32_SOC_PLAYPAQ_SLAVE */
/* #undef CONFIG_SND_AT91_SOC_MODULE */
/* #undef CONFIG_ARCH_AT91_MODULE */
/* #undef CONFIG_SND_AT91_SOC_SSC_MODULE */
/* #undef CONFIG_SND_SOC_AU1XPSC_MODULE */
/* #undef CONFIG_SOC_AU1200_MODULE */
/* #undef CONFIG_SOC_AU1550_MODULE */
/* #undef CONFIG_SND_SOC_AU1XPSC_I2S_MODULE */
/* #undef CONFIG_SND_SOC_AU1XPSC_AC97_MODULE */
/* #undef CONFIG_SND_SOC_SAMPLE_PSC_AC97_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_AC97_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_I2S_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_CORGI_MODULE */
/* #undef CONFIG_PXA_SHARP_C7XX_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_SPITZ_MODULE */
/* #undef CONFIG_PXA_SHARP_CXX00_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_POODLE_MODULE */
/* #undef CONFIG_MACH_POODLE_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_TOSA_MODULE */
/* #undef CONFIG_MACH_TOSA_MODULE */
/* #undef CONFIG_MFD_TC6393XB_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_E800_MODULE */
/* #undef CONFIG_MACH_E800_MODULE */
/* #undef CONFIG_SND_PXA2XX_SOC_EM_X270_MODULE */
/* #undef CONFIG_MACH_EM_X270_MODULE */
/* #undef CONFIG_SND_S3C24XX_SOC_MODULE */
/* #undef CONFIG_SND_S3C24XX_SOC_I2S_MODULE */
/* #undef CONFIG_SND_S3C2412_SOC_I2S_MODULE */
/* #undef CONFIG_SND_S3C2443_SOC_AC97_MODULE */
/* #undef CONFIG_SND_S3C24XX_SOC_NEO1973_WM8753_MODULE */
/* #undef CONFIG_MACH_NEO1973_GTA01_MODULE */
/* #undef CONFIG_SND_S3C24XX_SOC_SMDK2443_WM9710_MODULE */
/* #undef CONFIG_MACH_SMDK2443_MODULE */
/* #undef CONFIG_SND_S3C24XX_SOC_LN2440SBC_ALC650_MODULE */
/* #undef CONFIG_SND_SOC_PCM_SH7760_MODULE */
/* #undef CONFIG_CPU_SUBTYPE_SH7760_MODULE */
/* #undef CONFIG_SH_DMABRG_MODULE */
/* #undef CONFIG_SND_SOC_SH4_HAC_MODULE */
/* #undef CONFIG_SND_SOC_SH4_SSI_MODULE */
/* #undef CONFIG_SND_SH7760_AC97_MODULE */
/* #undef CONFIG_SND_SOC_OF_SIMPLE_MODULE */
/* #undef CONFIG_SND_SOC_MPC8610 */
/* #undef CONFIG_MPC8610_HPCD_MODULE */
/* #undef CONFIG_SND_SOC_MPC8610_HPCD */
/* #undef CONFIG_SND_SOC_MPC5200_I2S_MODULE */
/* #undef CONFIG_PPC_MPC52XX_MODULE */
/* #undef CONFIG_SND_DAVINCI_SOC_MODULE */
/* #undef CONFIG_ARCH_DAVINCI_MODULE */
/* #undef CONFIG_SND_DAVINCI_SOC_I2S_MODULE */
/* #undef CONFIG_SND_DAVINCI_SOC_EVM_MODULE */
/* #undef CONFIG_MACH_DAVINCI_EVM_MODULE */
/* #undef CONFIG_SND_OMAP_SOC_MODULE */
/* #undef CONFIG_ARCH_OMAP_MODULE */
/* #undef CONFIG_SND_OMAP_SOC_MCBSP_MODULE */
/* #undef CONFIG_OMAP_MCBSP_MODULE */
/* #undef CONFIG_SND_OMAP_SOC_N810_MODULE */
/* #undef CONFIG_MACH_NOKIA_N810_MODULE */
/* #undef CONFIG_SND_OMAP_SOC_OSK5912_MODULE */
/* #undef CONFIG_MACH_OMAP_OSK_MODULE */
/* #undef CONFIG_SND_BF5XX_I2S_MODULE */
/* #undef CONFIG_BLACKFIN_MODULE */
/* #undef CONFIG_SND_BF5XX_SOC_SSM2602_MODULE */
/* #undef CONFIG_I2C_BLACKFIN_TWI_MODULE */
/* #undef CONFIG_SND_BF5XX_SOC_AD73311_MODULE */
/* #undef CONFIG_SND_BFIN_AD73311_SE */
/* #undef CONFIG_SND_BF5XX_AC97_MODULE */
/* #undef CONFIG_SND_MMAP_SUPPORT */
/* #undef CONFIG_SND_BF5XX_SOC_SPORT_MODULE */
/* #undef CONFIG_SND_BF5XX_SOC_I2S_MODULE */
/* #undef CONFIG_SND_BF5XX_SOC_AC97_MODULE */
/* #undef CONFIG_SND_BF5XX_SOC_AD1980_MODULE */
/* #undef CONFIG_SND_BF5XX_SPORT_NUM */
/* #undef CONFIG_SND_BF5XX_HAVE_COLD_RESET */
/* #undef CONFIG_SND_BF5XX_RESET_GPIO_NUM */
/* #undef CONFIG_SND_SOC_ALL_CODECS_MODULE */
/* #undef CONFIG_SPI_MASTER_MODULE */
/* #undef CONFIG_SND_SOC_AC97_CODEC_MODULE */
/* #undef CONFIG_SND_SOC_AD1980_MODULE */
/* #undef CONFIG_SND_SOC_AD73311_MODULE */
/* #undef CONFIG_SND_SOC_AK4535_MODULE */
/* #undef CONFIG_SND_SOC_CS4270_MODULE */
/* #undef CONFIG_SND_SOC_CS4270_HWMUTE */
/* #undef CONFIG_SND_SOC_CS4270_VD33_ERRATA */
/* #undef CONFIG_SND_SOC_SSM2602_MODULE */
/* #undef CONFIG_SND_SOC_TLV320AIC23_MODULE */
/* #undef CONFIG_SND_SOC_TLV320AIC26_MODULE */
/* #undef CONFIG_SND_SOC_TLV320AIC3X_MODULE */
/* #undef CONFIG_SND_SOC_UDA1380_MODULE */
/* #undef CONFIG_SND_SOC_WM8510_MODULE */
/* #undef CONFIG_SND_SOC_WM8580_MODULE */
/* #undef CONFIG_SND_SOC_WM8731_MODULE */
/* #undef CONFIG_SND_SOC_WM8750_MODULE */
/* #undef CONFIG_SND_SOC_WM8753_MODULE */
/* #undef CONFIG_SND_SOC_WM8900_MODULE */
/* #undef CONFIG_SND_SOC_WM8903_MODULE */
/* #undef CONFIG_SND_SOC_WM8971_MODULE */
/* #undef CONFIG_SND_SOC_WM8990_MODULE */
/* #undef CONFIG_SND_SOC_WM9712_MODULE */
/* #undef CONFIG_SND_SOC_WM9713_MODULE */
/* #undef CONFIG_SOUND_PRIME_MODULE */
#define CONFIG_AC97_BUS_MODULE 1
