#!/bin/sh
module="gc100"
device="gcs"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove stale nodes

rm -f /dev/${device} /dev/${device}[0-7] 
rm -f /dev/${device} /dev/${device}d[0-7] 
