
#obj-$(CONFIG_IBM_ASM) := ibmasm.o
obj-$(CONFIG_GC100) := gc100.o

#ibmasm-y :=	module.o      \
#		ibmasmfs.o    \
#		event.o       \
#		command.o     \
#		remote.o      \
#		heartbeat.o   \
#		r_heartbeat.o \
#		dot_command.o \
#		lowlevel.o

#gc100-module-y := gc100.o
#gc100-module-m := gc100.o

#ibmasm-$(CONFIG_SERIAL_8250) += uart.o
