Document: lmce-mythtv-player
Title: Debian lmce-mythtv-player Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-mythtv-player is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-mythtv-player/lmce-mythtv-player.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-mythtv-player/lmce-mythtv-player.ps.gz

Format: text
Files: /usr/share/doc/lmce-mythtv-player/lmce-mythtv-player.text.gz

Format: HTML
Index: /usr/share/doc/lmce-mythtv-player/html/index.html
Files: /usr/share/doc/lmce-mythtv-player/html/*.html
