Document: lmce-rpc-plugin
Title: Debian lmce-rpc-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-rpc-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-rpc-plugin/lmce-rpc-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-rpc-plugin/lmce-rpc-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-rpc-plugin/lmce-rpc-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-rpc-plugin/html/index.html
Files: /usr/share/doc/lmce-rpc-plugin/html/*.html
