Document: pluto-hal-device-finder
Title: Debian pluto-hal-device-finder Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-hal-device-finder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-hal-device-finder/pluto-hal-device-finder.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-hal-device-finder/pluto-hal-device-finder.ps.gz

Format: text
Files: /usr/share/doc/pluto-hal-device-finder/pluto-hal-device-finder.text.gz

Format: HTML
Index: /usr/share/doc/pluto-hal-device-finder/html/index.html
Files: /usr/share/doc/pluto-hal-device-finder/html/*.html
