#!/bin/sh
# Start/stop pluto update media.

. /lib/lsb/init-functions

case "$1" in
start)	
;;
stop)
	pidscreen=`screen -ls | grep UpdateMediaDaemon | cut -d '.' -f1`
	kill $pidscreen
;;
*)	
	echo "Usage: $0 {stop}"
        exit 1 
        ;;
esac
exit 0
