#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

copy_exec /bin/ip /sbin
copy_exec /sbin/ifconfig /sbin
copy_exec /usr/bin/cut /sbin
copy_exec /bin/grep /sbin
copy_exec /bin/sed /sbin
