Document: mce-installer
Title: Debian mce-installer Manual
Author: <insert document author here>
Abstract: This manual describes what mce-installer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mce-installer/mce-installer.sgml.gz

Format: postscript
Files: /usr/share/doc/mce-installer/mce-installer.ps.gz

Format: text
Files: /usr/share/doc/mce-installer/mce-installer.text.gz

Format: HTML
Index: /usr/share/doc/mce-installer/html/index.html
Files: /usr/share/doc/mce-installer/html/*.html

  
