Document: lmce-airplay-streamer
Title: Debian lmce-airplay-streamer Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-airplay-streamer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-airplay-streamer/lmce-airplay-streamer.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-airplay-streamer/lmce-airplay-streamer.ps.gz

Format: text
Files: /usr/share/doc/lmce-airplay-streamer/lmce-airplay-streamer.text.gz

Format: HTML
Index: /usr/share/doc/lmce-airplay-streamer/html/index.html
Files: /usr/share/doc/lmce-airplay-streamer/html/*.html
