#!/bin/sh
# Run various programs to select packages to install.
set -e

case "$1" in
''|new)
	# Make dpkg not background itself to get a shell.
	export DPKG_NO_TSTP="yes"

	# Set DEBIAN_FRONTEND, since some evil postinst scripts still
	# check it directly.
	if [ -z "$DEBIAN_FRONTEND" ] ; then
		DEBIAN_FRONTEND=$($0 get_frontend 4>&1 || true)
		if [ "$DEBIAN_FRONTEND" ] ; then
			export DEBIAN_FRONTEND
		else
			unset DEBIAN_FRONTEND || true
		fi
	fi

	# Make popularity-contest be selected for installation by default. It
	# lets the user choose whether or not to enable it. We need more
	# people using this so we can hope to get better data about who is
	# using what packages in debian.
	# (Doesn't work with new tasksel.)
	#echo popularity-contest install | dpkg --set-selections
	
	# X needs some packages installed before its debconf config is run
	# to make it do hardware autodetection. The only way to make sure these
	# are installed properly is to install them now, before packages are
	# selected. This way, even if the user picks xserver-xfree86 in
	# aptitude and installs using aptitude, they will be available.
	for pkg in mdetect read-edid ; do
		if ! dpkg --get-selections | grep "$pkg" | grep -q install; then
			if apt-get -y -f install "$pkg"; then
				extra="$pkg $extra"
			fi
		fi
	done

	mv /usr/pluto/install/deb-cache/* /var/cache/apt/archives
	rmdir /usr/pluto/install/deb-cache

	ok=0
	until [ "$ok" -eq 1 ]; do
		echo "Do you want a Pluto system or a regular Debian system?"
		echo "(P=Pluto (default),D=Debian): "
		read answer
		[ "$answer" == "P" -o "$answer" == "p" -o -z "$answer" ] && want_pluto=1 && ok=1
		[ "$answer" == "D" -o "$answer" == "d" ] && want_pluto=0 && ok=1
		[ "$ok" -eq 0 ] && echo "Unrecognized answer '$answer'. Try again"
	done
	[ "$want_pluto" -eq 1 ] && echo "Installing a Pluto system" || echo "Installing a Debian system"

	[ "$want_pluto" -eq 1 ] && /usr/pluto/install/Initial_Config.sh
	pluto_ok=$?

	if [ "$want_pluto" -eq 0 ] && which tasksel >/dev/null 2>&1; then
		if [ "$1" = new ]; then
			tasksel_param="--new-install"
		fi
		if ! tasksel -ris $tasksel_param; then
			$0 failure
			exit 1
		fi
	fi

#	if [ "$KEEP_BASE_DEBS" != yes ]; then
#		apt-get -f clean || true
#	fi
	
	# If X was not installed, remove the hardware detection
	# programs. Of course, this fails if the user manually choose
	# to install these, or wants them installed for some other reason.
	# But I cannot help that.
	if ! dpkg --get-selections | grep xserver-xfree86 | grep -q install; then
		if [ -n "$extra" ] ; then
			dpkg --purge $extra || true
		fi
	fi

	if [ "$want_pluto" -eq 1 ]; then
		[ "$pluto_ok" -eq 0 ] && exit 0 || exit "$pluto_ok"
	fi
	;;
failure)
	# This branch is reached if there was some problem installing.
	# It uses debconf (which the other branch cannot use) to explain
	# the failure to the user.
	. /usr/share/debconf/confmodule
	db_settitle base-config/title
	db_fset base-config/install-problem seen false
	db_input critical base-config/install-problem || true
	db_go || true
	;;
get_frontend)
	. /usr/share/debconf/confmodule
	db_get debconf/frontend
	# Convert to lower case to avoid warning from newer debconf
	echo $RET | tr A-Z a-z >&4
	;;
esac
