Document: lmce-screen-capture-camera
Title: Debian lmce-screen-capture-camera Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-screen-capture-camera is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-screen-capture-camera/lmce-screen-capture-camera.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-screen-capture-camera/lmce-screen-capture-camera.ps.gz

Format: text
Files: /usr/share/doc/lmce-screen-capture-camera/lmce-screen-capture-camera.text.gz

Format: HTML
Index: /usr/share/doc/lmce-screen-capture-camera/html/index.html
Files: /usr/share/doc/lmce-screen-capture-camera/html/*.html
