Document: lmce-videolan-plugin
Title: Debian lmce-videolan-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-videolan-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-videolan-plugin/lmce-videolan-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-videolan-plugin/lmce-videolan-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-videolan-plugin/lmce-videolan-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-videolan-plugin/html/index.html
Files: /usr/share/doc/lmce-videolan-plugin/html/*.html
