#ifndef __Define_Text_H__
#define __Define_Text_H__

#define TEXT_Media_CONST 825
#define TEXT_Computing_CONST 826
#define TEXT_Car_Setup_CONST 827
#define TEXT_Home_CONST 828
#define TEXT_Radio_CONST 829
#define TEXT_TV_CONST 830
#define TEXT_CD_CONST 831
#define TEXT_Hard_drive_CONST 832
#define TEXT_Internet_CONST 833
#define TEXT_Email_CONST 834
#define TEXT_Agenda_CONST 835
#define TEXT_Other_CONST 836
#define TEXT_Lighting_CONST 837
#define TEXT_Climate_CONST 838
#define TEXT_Security_CONST 839
#define TEXT_Telecom_CONST 840
#define TEXT_Nav_CONST 841
#define TEXT_Info_CONST 842
#define TEXT_Car_CONST 843
#define TEXT_Setup_CONST 844
#define TEXT_Memory_CONST 845
#define TEXT_Radio_control_CONST 846
#define TEXT_Frequency_CONST 847
#define TEXT_Sound_CONST 848
#define TEXT_Live_TV_CONST 849
#define TEXT_Recorded_TV_CONST 850
#define TEXT_Program_Guide_CONST 851
#define TEXT_Recording_list_CONST 852
#define TEXT_Control_CONST 853
#define TEXT_Track_list_CONST 854
#define TEXT_Changer_CONST 855
#define TEXT_Sound_cd_CONST 856
#define TEXT_Music_CONST 857
#define TEXT_Video_CONST 858
#define TEXT_Pictures_CONST 859
#define TEXT_Bookmarks_CONST 860
#define TEXT_Control_i9nternet_CONST 861
#define TEXT_Manual_CONST 862
#define TEXT_Full_screen_internet_CONST 863
#define TEXT_Read_CONST 864
#define TEXT_Write_CONST 865
#define TEXT_SendReceive_CONST 866
#define TEXT_User_CONST 867
#define TEXT_Calendar_CONST 868
#define TEXT_Contacts_CONST 869
#define TEXT_To_do_CONST 870
#define TEXT_User_agenda_CONST 871
#define TEXT_Program_list_CONST 872
#define TEXT_Documents_CONST 873
#define TEXT_Install_Remove_CONST 874
#define TEXT_User_other_CONST 875
#define TEXT_Memory_nav_CONST 876
#define TEXT_Nav_info_CONST 877
#define TEXT_Route_CONST 878
#define TEXT_Map_CONST 879
#define TEXT_TP_Memo_CONST 880
#define TEXT_Telematics_CONST 881
#define TEXT_Source_CONST 882
#define TEXT_User_car_CONST 883
#define TEXT_Systems_CONST 884
#define TEXT_Handbook_CONST 885
#define TEXT_Version_CONST 886
#define TEXT_Directory_CONST 887
#define TEXT_Display_CONST 888
#define TEXT_Settings_CONST 889
#define TEXT_Sound_setup_CONST 890
#define TEXT_opt1_CONST 891
#define TEXT_List_lighting_CONST 892
#define TEXT_Map_lighting_CONST 893
#define TEXT_List_telecom_CONST 894
#define TEXT_Map_telecom_CONST 895
#define TEXT_Make_call_CONST 896
#define TEXT_Intercom_CONST 897
#define TEXT_List_security_CONST 898
#define TEXT_Map_security_CONST 899
#define TEXT_Cameras_CONST 900
#define TEXT_Doors_CONST 901
#define TEXT_List_climate_CONST 902
#define TEXT_Map_climate_CONST 903
#define TEXT_Main_menu_CONST 904
#define TEXT_adaptive_air_suspension_CONST 905
#define TEXT_lift_CONST 906
#define TEXT_Maximilian_CONST 907
#define TEXT_Alexander_CONST 908
#define TEXT_Sophie_CONST 909
#define TEXT_user4_CONST 910
#define TEXT_comfort_CONST 911
#define TEXT_automatic_CONST 912
#define TEXT_dynamic_CONST 913
#define TEXT_Bayern_5_CONST 914
#define TEXT_Radio_in_CONST 915
#define TEXT_Bayern_2_CONST 916
#define TEXT_Bayern_1_CONST 917
#define TEXT_Bayern_4_CONST 918
#define TEXT_Control_dvd_CONST 919
#define TEXT_Sound_dvd_CONST 920
#define TEXT_Options_CONST 921
#define TEXT_Menu_CONST 922
#define TEXT_DVD_CONST 923
#define TEXT_media_description_CONST 924
#define TEXT_Rewind_CONST 925
#define TEXT_Previous_CONST 926
#define TEXT_Scan_CONST 927
#define TEXT_Name_CONST 928
#define TEXT_Shuffle_cd_CONST 929
#define TEXT_Next_CONST 930
#define TEXT_Forward_CONST 931
#define TEXT_Tune_down_CONST 932
#define TEXT_Tune_up_CONST 933
#define TEXT_Seek_up_CONST 934
#define TEXT_Seek_down_CONST 935
#define TEXT_Scan_redio_CONST 936
#define TEXT_Store_CONST 937
#define TEXT_Bayern_3_CONST 938
#define TEXT_destinations_CONST 939
#define TEXT_Route_planning_CONST 940
#define TEXT_Route_list_CONST 941
#define TEXT_Route_criteria_CONST 942
#define TEXT_Exclude_route_from_here_CONST 943
#define TEXT_Country_CONST 944
#define TEXT_Town_Zip_CONST 945
#define TEXT_Street_CONST 946
#define TEXT_Special_destination_CONST 947
#define TEXT_Start_route_guidance_CONST 948
#define TEXT_Towing_mode_CONST 949
#define TEXT_Car_jack_mode_CONST 950
#define TEXT_Find_entry_CONST 951
#define TEXT_Show_list_CONST 952
#define TEXT_Display_points_of_interest_CONST 953
#define TEXT_New_entry_CONST 954
#define TEXT_Delete_directory_CONST 955
#define TEXT_Menu_lang_CONST 956
#define TEXT_Measurement_units_CONST 957
#define TEXT_Time_settings_CONST 958
#define TEXT_System_tones_CONST 959
#define TEXT_Speech_dialog_controls_CONST 960
#define TEXT_Factory_settings_CONST 961
#define TEXT_CD_DVD_CONST 962
#define TEXT_Loading_from_device_CONST 963
#define TEXT_Full_screen_CONST 964
#define TEXT_Subtitles_CONST 965
#define TEXT_Angles_CONST 966
#define TEXT_Audio_tracks_CONST 967
#define TEXT_Sound_dvd_options_CONST 968
#define TEXT_Last_destionations_CONST 969
#define TEXT_Top_categories_CONST 970
#define TEXT_brightness_CONST 971
#define TEXT_Balance_CONST 972
#define TEXT_Fader_CONST 973
#define TEXT_Treble_CONST 974
#define TEXT_Bass_CONST 975
#define TEXT_Subwoofer_CONST 976
#define TEXT_FM_very_high_frequency_CONST 977
#define TEXT_MW_medium_wave_CONST 978
#define TEXT_LW_long_wave_CONST 979
#define TEXT_CD_1_ACDC_Stiff_Upper_Lip_CONST 980
#define TEXT_CD_2_Best_of_the_Millennium_Classical_CONST 981
#define TEXT_CD_3_Chris_Botti_When_I_Fall_In_Lov_CONST 982
#define TEXT_CD_4_Regis_Philbin_When_Youre_Smili_CONST 983
#define TEXT_891_MHz_CONST 984
#define TEXT_Sending_and_receiving_emails_CONST 985
#define TEXT_acoustic_parking_system_CONST 986
#define TEXT_adaptive_cruise_control_CONST 987
#define TEXT_exterior_lighting_CONST 988
#define TEXT_battery_level_CONST 989
#define TEXT_previous_dvd_CONST 990
#define TEXT_step_backward_CONST 991
#define TEXT_pause_CONST 992
#define TEXT_play_CONST 993
#define TEXT_stop_dvd_CONST 994
#define TEXT_step_forward_CONST 995
#define TEXT_next_dvd_CONST 996
#define TEXT_save_CONST 997
#define TEXT_fast_rewind_CONST 998
#define TEXT_fast_forward_CONST 999
#define TEXT_Save_dafsad_CONST 1000
#define TEXT_Stored_DVDs_CONST 1001
#define TEXT_Recorded_TV_hard_drive_CONST 1002
#define TEXT_Queue_CONST 1003
#define TEXT_Control_video_hard_drive_CONST 1004
#define TEXT_Playlists_CONST 1005
#define TEXT_Programs_CONST 1006
#define TEXT_1_CONST 1007
#define TEXT_2_CONST 1008
#define TEXT_3_CONST 1009
#define TEXT_4_CONST 1010
#define TEXT_5_CONST 1011
#define TEXT_6_CONST 1012
#define TEXT_7_CONST 1013
#define TEXT_8_CONST 1014
#define TEXT_9_CONST 1015
#define TEXT_0_CONST 1016
#define TEXT_Num_CONST 1017
#define TEXT__CONST 1018
#define TEXT_FM_CONST 1019
#define TEXT_LW_CONST 1020
#define TEXT_MW_CONST 1021
#define TEXT_read_from_mobile_keyboard_CONST 1022
#define TEXT_back_CONST 1023
#define TEXT_stop_CONST 1024
#define TEXT_reload_CONST 1025
#define TEXT_Front_door_CONST 1026
#define TEXT_Back_door_CONST 1027
#define TEXT_bedroom_extension_101_CONST 1028
#define TEXT_kitchen_extension_102_CONST 1029
#define TEXT_front_door_extension_103_CONST 1030
#define TEXT_office_extension_104_CONST 1031
#define TEXT_Type_entry_on_the_phone_CONST 1032
#define TEXT_resave_this_queue_as__11_CONST 1033
#define TEXT_save_this_queue_as_a_new_playlist_CONST 1034
#define TEXT_rearrange_queue_CONST 1035
#define TEXT_delete_something_from_the_queue_CONST 1036
#define TEXT_rename_the_playlist__11_CONST 1037
#define TEXT_delete_the_playlist__11_CONST 1038
#define TEXT_scroll_CONST 1040
#define TEXT_Seek_In_Data_Grid_CONST 1041
#define TEXT_Path_CONST 1042
#define TEXT_Audio_CONST 1043
#define TEXT_Video_hd_CONST 1044
#define TEXT_http_www_CONST 1045
#define TEXT_Inbox_CONST 1046
#define TEXT_Message_from_Alexander_CONST 1047
#define TEXT_How_are_you_CONST 1048
#define TEXT_Compose_CONST 1049
#define TEXT_TO_CONST 1050
#define TEXT_Subject_CONST 1051
#define TEXT_Message_CONST 1052
#define TEXT_New_phone_CONST 1053
#define TEXT_Yes_Install_Pluto_Software_CONST 1054
#define TEXT_No_This_device_is_something_else_CONST 1055
#define TEXT_var_Channel_Name_CONST 1056
#define TEXT_var_Show_Name_CONST 1057
#define TEXT_var_Synopsis_CONST 1058
#define TEXT_go_to_remote_media_CONST 1059
#define TEXT_Channel_Name_CONST 1061
#define TEXT_Show_Name_CONST 1062
#define TEXT_Synopsis_CONST 1063
#define TEXT_Read_phone_heyboard_CONST 1064

#define TEXT_TABLE "Text"
#define TEXT_PK_TEXT_FIELD "PK_Text"
#define TEXT_PK_TEXT_TABLE_FIELD "Text.PK_Text"
#define TEXT_FK_TEXTCATEGORY_FIELD "FK_TextCategory"
#define TEXT_FK_TEXTCATEGORY_TABLE_FIELD "Text.FK_TextCategory"
#define TEXT_DESCRIPTION_FIELD "Description"
#define TEXT_DESCRIPTION_TABLE_FIELD "Text.Description"
#define TEXT_DEFINE_FIELD "Define"
#define TEXT_DEFINE_TABLE_FIELD "Text.Define"
#define TEXT_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define TEXT_MODIFICATION_RECORDINFO_TABLE_FIELD "Text.Modification_RecordInfo"
#define TEXT_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define TEXT_ISNEW_RECORDINFO_TABLE_FIELD "Text.IsNew_RecordInfo"
#define TEXT_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define TEXT_ISDELETED_RECORDINFO_TABLE_FIELD "Text.IsDeleted_RecordInfo"
#define TEXT_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define TEXT_FK_USERS_RECORDINFO_TABLE_FIELD "Text.FK_Users_RecordInfo"


#endif

