#ifndef __Define_CommandCategory_H__
#define __Define_CommandCategory_H__


#define COMMANDCATEGORY_TABLE "CommandCategory"
#define COMMANDCATEGORY_PK_COMMANDCATEGORY_FIELD "PK_CommandCategory"
#define COMMANDCATEGORY_PK_COMMANDCATEGORY_TABLE_FIELD "CommandCategory.PK_CommandCategory"
#define COMMANDCATEGORY_FK_COMMANDCATEGORY_PARENT_FIELD "FK_CommandCategory_Parent"
#define COMMANDCATEGORY_FK_COMMANDCATEGORY_PARENT_TABLE_FIELD "CommandCategory.FK_CommandCategory_Parent"
#define COMMANDCATEGORY_DESCRIPTION_FIELD "Description"
#define COMMANDCATEGORY_DESCRIPTION_TABLE_FIELD "CommandCategory.Description"
#define COMMANDCATEGORY_PSC_ID_FIELD "psc_id"
#define COMMANDCATEGORY_PSC_ID_TABLE_FIELD "CommandCategory.psc_id"
#define COMMANDCATEGORY_PSC_BATCH_FIELD "psc_batch"
#define COMMANDCATEGORY_PSC_BATCH_TABLE_FIELD "CommandCategory.psc_batch"
#define COMMANDCATEGORY_PSC_USER_FIELD "psc_user"
#define COMMANDCATEGORY_PSC_USER_TABLE_FIELD "CommandCategory.psc_user"
#define COMMANDCATEGORY_PSC_FROZEN_FIELD "psc_frozen"
#define COMMANDCATEGORY_PSC_FROZEN_TABLE_FIELD "CommandCategory.psc_frozen"
#define COMMANDCATEGORY_PSC_MOD_FIELD "psc_mod"
#define COMMANDCATEGORY_PSC_MOD_TABLE_FIELD "CommandCategory.psc_mod"


#endif

