#ifndef __Define_DSPMode_H__
#define __Define_DSPMode_H__


#define DSPMODE_TABLE "DSPMode"
#define DSPMODE_PK_DSPMODE_FIELD "PK_DSPMode"
#define DSPMODE_PK_DSPMODE_TABLE_FIELD "DSPMode.PK_DSPMode"
#define DSPMODE_DESCRIPTION_FIELD "Description"
#define DSPMODE_DESCRIPTION_TABLE_FIELD "DSPMode.Description"
#define DSPMODE_DEFINE_FIELD "Define"
#define DSPMODE_DEFINE_TABLE_FIELD "DSPMode.Define"
#define DSPMODE_FK_COMMAND_FIELD "FK_Command"
#define DSPMODE_FK_COMMAND_TABLE_FIELD "DSPMode.FK_Command"
#define DSPMODE_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define DSPMODE_MODIFICATION_RECORDINFO_TABLE_FIELD "DSPMode.Modification_RecordInfo"
#define DSPMODE_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define DSPMODE_ISNEW_RECORDINFO_TABLE_FIELD "DSPMode.IsNew_RecordInfo"
#define DSPMODE_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define DSPMODE_ISDELETED_RECORDINFO_TABLE_FIELD "DSPMode.IsDeleted_RecordInfo"
#define DSPMODE_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define DSPMODE_FK_USERS_RECORDINFO_TABLE_FIELD "DSPMode.FK_Users_RecordInfo"


#endif

