#ifndef __Define_EventParameter_H__
#define __Define_EventParameter_H__

#define EVENTPARAMETER_X_Position_CONST 1
#define EVENTPARAMETER_Y_Position_CONST 2
#define EVENTPARAMETER_FK_MediaType_CONST 3
#define EVENTPARAMETER_MRL_CONST 4
#define EVENTPARAMETER_Mac_Address_CONST 5
#define EVENTPARAMETER_Signal_Strength_CONST 6
#define EVENTPARAMETER_ID_CONST 7
#define EVENTPARAMETER_Version_CONST 8
#define EVENTPARAMETER_Stream_ID_CONST 9
#define EVENTPARAMETER_OnOff_CONST 10

#define EVENTPARAMETER_TABLE "EventParameter"
#define EVENTPARAMETER_PK_EVENTPARAMETER_FIELD "PK_EventParameter"
#define EVENTPARAMETER_PK_EVENTPARAMETER_TABLE_FIELD "EventParameter.PK_EventParameter"
#define EVENTPARAMETER_DESCRIPTION_FIELD "Description"
#define EVENTPARAMETER_DESCRIPTION_TABLE_FIELD "EventParameter.Description"
#define EVENTPARAMETER_DEFINE_FIELD "Define"
#define EVENTPARAMETER_DEFINE_TABLE_FIELD "EventParameter.Define"
#define EVENTPARAMETER_COMMENTS_FIELD "Comments"
#define EVENTPARAMETER_COMMENTS_TABLE_FIELD "EventParameter.Comments"
#define EVENTPARAMETER_FK_PARAMETERTYPE_FIELD "FK_ParameterType"
#define EVENTPARAMETER_FK_PARAMETERTYPE_TABLE_FIELD "EventParameter.FK_ParameterType"
#define EVENTPARAMETER_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define EVENTPARAMETER_MODIFICATION_RECORDINFO_TABLE_FIELD "EventParameter.Modification_RecordInfo"
#define EVENTPARAMETER_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define EVENTPARAMETER_ISNEW_RECORDINFO_TABLE_FIELD "EventParameter.IsNew_RecordInfo"
#define EVENTPARAMETER_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define EVENTPARAMETER_ISDELETED_RECORDINFO_TABLE_FIELD "EventParameter.IsDeleted_RecordInfo"
#define EVENTPARAMETER_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define EVENTPARAMETER_FK_USERS_RECORDINFO_TABLE_FIELD "EventParameter.FK_Users_RecordInfo"


#endif

