#ifndef __Define_MobilePhoneVersion_H__
#define __Define_MobilePhoneVersion_H__


#define MOBILEPHONEVERSION_TABLE "MobilePhoneVersion"
#define MOBILEPHONEVERSION_PK_MOBILEPHONEVERSION_FIELD "PK_MobilePhoneVersion"
#define MOBILEPHONEVERSION_PK_MOBILEPHONEVERSION_TABLE_FIELD "MobilePhoneVersion.PK_MobilePhoneVersion"
#define MOBILEPHONEVERSION_DESCRIPTION_FIELD "Description"
#define MOBILEPHONEVERSION_DESCRIPTION_TABLE_FIELD "MobilePhoneVersion.Description"
#define MOBILEPHONEVERSION_DEFINE_FIELD "Define"
#define MOBILEPHONEVERSION_DEFINE_TABLE_FIELD "MobilePhoneVersion.Define"
#define MOBILEPHONEVERSION_MODELS_FIELD "Models"
#define MOBILEPHONEVERSION_MODELS_TABLE_FIELD "MobilePhoneVersion.Models"
#define MOBILEPHONEVERSION_HEIGHT_FIELD "Height"
#define MOBILEPHONEVERSION_HEIGHT_TABLE_FIELD "MobilePhoneVersion.Height"
#define MOBILEPHONEVERSION_WIDTH_FIELD "Width"
#define MOBILEPHONEVERSION_WIDTH_TABLE_FIELD "MobilePhoneVersion.Width"
#define MOBILEPHONEVERSION_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define MOBILEPHONEVERSION_MODIFICATION_RECORDINFO_TABLE_FIELD "MobilePhoneVersion.Modification_RecordInfo"
#define MOBILEPHONEVERSION_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define MOBILEPHONEVERSION_ISNEW_RECORDINFO_TABLE_FIELD "MobilePhoneVersion.IsNew_RecordInfo"
#define MOBILEPHONEVERSION_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define MOBILEPHONEVERSION_ISDELETED_RECORDINFO_TABLE_FIELD "MobilePhoneVersion.IsDeleted_RecordInfo"
#define MOBILEPHONEVERSION_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define MOBILEPHONEVERSION_FK_USERS_RECORDINFO_TABLE_FIELD "MobilePhoneVersion.FK_Users_RecordInfo"


#endif

