#ifndef __Define_CriteriaParm_D_H__
#define __Define_CriteriaParm_D_H__


#define CRITERIAPARM_D_TABLE "CriteriaParm_D"
#define CRITERIAPARM_D_PK_CRITERIAPARM_FIELD "PK_CriteriaParm"
#define CRITERIAPARM_D_PK_CRITERIAPARM_TABLE_FIELD "CriteriaParm_D.PK_CriteriaParm"
#define CRITERIAPARM_D_FK_CRITERIAPARMNESTING_D_FIELD "FK_CriteriaParmNesting_D"
#define CRITERIAPARM_D_FK_CRITERIAPARMNESTING_D_TABLE_FIELD "CriteriaParm_D.FK_CriteriaParmNesting_D"
#define CRITERIAPARM_D_FK_CRITERIAPARMLIST_FIELD "FK_CriteriaParmList"
#define CRITERIAPARM_D_FK_CRITERIAPARMLIST_TABLE_FIELD "CriteriaParm_D.FK_CriteriaParmList"
#define CRITERIAPARM_D_OPERATOR_FIELD "Operator"
#define CRITERIAPARM_D_OPERATOR_TABLE_FIELD "CriteriaParm_D.Operator"
#define CRITERIAPARM_D_VALUE_FIELD "Value"
#define CRITERIAPARM_D_VALUE_TABLE_FIELD "CriteriaParm_D.Value"
#define CRITERIAPARM_D_FK_CANNEDEVENTS_CRITERIAPARMLIST_FIELD "FK_CannedEvents_CriteriaParmList"
#define CRITERIAPARM_D_FK_CANNEDEVENTS_CRITERIAPARMLIST_TABLE_FIELD "CriteriaParm_D.FK_CannedEvents_CriteriaParmList"
#define CRITERIAPARM_D_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define CRITERIAPARM_D_MODIFICATION_RECORDINFO_TABLE_FIELD "CriteriaParm_D.Modification_RecordInfo"
#define CRITERIAPARM_D_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define CRITERIAPARM_D_ISNEW_RECORDINFO_TABLE_FIELD "CriteriaParm_D.IsNew_RecordInfo"
#define CRITERIAPARM_D_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define CRITERIAPARM_D_ISDELETED_RECORDINFO_TABLE_FIELD "CriteriaParm_D.IsDeleted_RecordInfo"
#define CRITERIAPARM_D_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define CRITERIAPARM_D_FK_USERS_RECORDINFO_TABLE_FIELD "CriteriaParm_D.FK_Users_RecordInfo"


#endif

