#ifndef __Define_ConfigType_File_H__
#define __Define_ConfigType_File_H__


#define CONFIGTYPE_FILE_TABLE "ConfigType_File"
#define CONFIGTYPE_FILE_PK_CONFIGTYPE_FILE_FIELD "PK_ConfigType_File"
#define CONFIGTYPE_FILE_PK_CONFIGTYPE_FILE_TABLE_FIELD "ConfigType_File.PK_ConfigType_File"
#define CONFIGTYPE_FILE_FK_CONFIGTYPE_FIELD "FK_ConfigType"
#define CONFIGTYPE_FILE_FK_CONFIGTYPE_TABLE_FIELD "ConfigType_File.FK_ConfigType"
#define CONFIGTYPE_FILE_INPUTFILE_FIELD "InputFile"
#define CONFIGTYPE_FILE_INPUTFILE_TABLE_FIELD "ConfigType_File.InputFile"
#define CONFIGTYPE_FILE_OUTPUTFILE_FIELD "OutputFile"
#define CONFIGTYPE_FILE_OUTPUTFILE_TABLE_FIELD "ConfigType_File.OutputFile"
#define CONFIGTYPE_FILE_EFS_FIELD "EFS"
#define CONFIGTYPE_FILE_EFS_TABLE_FIELD "ConfigType_File.EFS"
#define CONFIGTYPE_FILE_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define CONFIGTYPE_FILE_MODIFICATION_RECORDINFO_TABLE_FIELD "ConfigType_File.Modification_RecordInfo"
#define CONFIGTYPE_FILE_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define CONFIGTYPE_FILE_ISNEW_RECORDINFO_TABLE_FIELD "ConfigType_File.IsNew_RecordInfo"
#define CONFIGTYPE_FILE_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define CONFIGTYPE_FILE_ISDELETED_RECORDINFO_TABLE_FIELD "ConfigType_File.IsDeleted_RecordInfo"
#define CONFIGTYPE_FILE_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define CONFIGTYPE_FILE_FK_USERS_RECORDINFO_TABLE_FIELD "ConfigType_File.FK_Users_RecordInfo"


#endif

