#ifndef __Define_RepositorySource_URL_H__
#define __Define_RepositorySource_URL_H__


#define REPOSITORYSOURCE_URL_TABLE "RepositorySource_URL"
#define REPOSITORYSOURCE_URL_PK_REPOSITORYSOURCE_URL_FIELD "PK_RepositorySource_URL"
#define REPOSITORYSOURCE_URL_PK_REPOSITORYSOURCE_URL_TABLE_FIELD "RepositorySource_URL.PK_RepositorySource_URL"
#define REPOSITORYSOURCE_URL_FK_REPOSITORYSOURCE_FIELD "FK_RepositorySource"
#define REPOSITORYSOURCE_URL_FK_REPOSITORYSOURCE_TABLE_FIELD "RepositorySource_URL.FK_RepositorySource"
#define REPOSITORYSOURCE_URL_URL_FIELD "URL"
#define REPOSITORYSOURCE_URL_URL_TABLE_FIELD "RepositorySource_URL.URL"
#define REPOSITORYSOURCE_URL_FK_COUNTRY_FIELD "FK_Country"
#define REPOSITORYSOURCE_URL_FK_COUNTRY_TABLE_FIELD "RepositorySource_URL.FK_Country"
#define REPOSITORYSOURCE_URL_USERNAME_FIELD "Username"
#define REPOSITORYSOURCE_URL_USERNAME_TABLE_FIELD "RepositorySource_URL.Username"
#define REPOSITORYSOURCE_URL_PASSWORD_FIELD "Password"
#define REPOSITORYSOURCE_URL_PASSWORD_TABLE_FIELD "RepositorySource_URL.Password"


#endif

