#ifndef __Define_Device_EntertainArea_H__
#define __Define_Device_EntertainArea_H__


#define DEVICE_ENTERTAINAREA_TABLE "Device_EntertainArea"
#define DEVICE_ENTERTAINAREA_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_ENTERTAINAREA_FK_DEVICE_TABLE_FIELD "Device_EntertainArea.FK_Device"
#define DEVICE_ENTERTAINAREA_FK_ENTERTAINAREA_FIELD "FK_EntertainArea"
#define DEVICE_ENTERTAINAREA_FK_ENTERTAINAREA_TABLE_FIELD "Device_EntertainArea.FK_EntertainArea"
#define DEVICE_ENTERTAINAREA_PSC_ID_FIELD "psc_id"
#define DEVICE_ENTERTAINAREA_PSC_ID_TABLE_FIELD "Device_EntertainArea.psc_id"
#define DEVICE_ENTERTAINAREA_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_ENTERTAINAREA_PSC_BATCH_TABLE_FIELD "Device_EntertainArea.psc_batch"
#define DEVICE_ENTERTAINAREA_PSC_USER_FIELD "psc_user"
#define DEVICE_ENTERTAINAREA_PSC_USER_TABLE_FIELD "Device_EntertainArea.psc_user"
#define DEVICE_ENTERTAINAREA_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_ENTERTAINAREA_PSC_FROZEN_TABLE_FIELD "Device_EntertainArea.psc_frozen"
#define DEVICE_ENTERTAINAREA_PSC_MOD_FIELD "psc_mod"
#define DEVICE_ENTERTAINAREA_PSC_MOD_TABLE_FIELD "Device_EntertainArea.psc_mod"


#endif

