#ifndef __Define_DeviceTemplate_DSPMode_H__
#define __Define_DeviceTemplate_DSPMode_H__


#define DEVICETEMPLATE_DSPMODE_TABLE "DeviceTemplate_DSPMode"
#define DEVICETEMPLATE_DSPMODE_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define DEVICETEMPLATE_DSPMODE_FK_DEVICETEMPLATE_TABLE_FIELD "DeviceTemplate_DSPMode.FK_DeviceTemplate"
#define DEVICETEMPLATE_DSPMODE_FK_DSPMODE_FIELD "FK_DSPMode"
#define DEVICETEMPLATE_DSPMODE_FK_DSPMODE_TABLE_FIELD "DeviceTemplate_DSPMode.FK_DSPMode"
#define DEVICETEMPLATE_DSPMODE_PSC_ID_FIELD "psc_id"
#define DEVICETEMPLATE_DSPMODE_PSC_ID_TABLE_FIELD "DeviceTemplate_DSPMode.psc_id"
#define DEVICETEMPLATE_DSPMODE_PSC_BATCH_FIELD "psc_batch"
#define DEVICETEMPLATE_DSPMODE_PSC_BATCH_TABLE_FIELD "DeviceTemplate_DSPMode.psc_batch"
#define DEVICETEMPLATE_DSPMODE_PSC_USER_FIELD "psc_user"
#define DEVICETEMPLATE_DSPMODE_PSC_USER_TABLE_FIELD "DeviceTemplate_DSPMode.psc_user"
#define DEVICETEMPLATE_DSPMODE_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICETEMPLATE_DSPMODE_PSC_FROZEN_TABLE_FIELD "DeviceTemplate_DSPMode.psc_frozen"
#define DEVICETEMPLATE_DSPMODE_PSC_MOD_FIELD "psc_mod"
#define DEVICETEMPLATE_DSPMODE_PSC_MOD_TABLE_FIELD "DeviceTemplate_DSPMode.psc_mod"


#endif

