#ifndef __Define_DeviceTemplate_Package_H__
#define __Define_DeviceTemplate_Package_H__


#define DEVICETEMPLATE_PACKAGE_TABLE "DeviceTemplate_Package"
#define DEVICETEMPLATE_PACKAGE_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define DEVICETEMPLATE_PACKAGE_FK_DEVICETEMPLATE_TABLE_FIELD "DeviceTemplate_Package.FK_DeviceTemplate"
#define DEVICETEMPLATE_PACKAGE_FK_PACKAGE_FIELD "FK_Package"
#define DEVICETEMPLATE_PACKAGE_FK_PACKAGE_TABLE_FIELD "DeviceTemplate_Package.FK_Package"
#define DEVICETEMPLATE_PACKAGE_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define DEVICETEMPLATE_PACKAGE_FK_OPERATINGSYSTEM_TABLE_FIELD "DeviceTemplate_Package.FK_OperatingSystem"
#define DEVICETEMPLATE_PACKAGE_FK_DISTRO_FIELD "FK_Distro"
#define DEVICETEMPLATE_PACKAGE_FK_DISTRO_TABLE_FIELD "DeviceTemplate_Package.FK_Distro"
#define DEVICETEMPLATE_PACKAGE_DEVELOPMENTONLY_FIELD "DevelopmentOnly"
#define DEVICETEMPLATE_PACKAGE_DEVELOPMENTONLY_TABLE_FIELD "DeviceTemplate_Package.DevelopmentOnly"
#define DEVICETEMPLATE_PACKAGE_PSC_ID_FIELD "psc_id"
#define DEVICETEMPLATE_PACKAGE_PSC_ID_TABLE_FIELD "DeviceTemplate_Package.psc_id"
#define DEVICETEMPLATE_PACKAGE_PSC_BATCH_FIELD "psc_batch"
#define DEVICETEMPLATE_PACKAGE_PSC_BATCH_TABLE_FIELD "DeviceTemplate_Package.psc_batch"
#define DEVICETEMPLATE_PACKAGE_PSC_USER_FIELD "psc_user"
#define DEVICETEMPLATE_PACKAGE_PSC_USER_TABLE_FIELD "DeviceTemplate_Package.psc_user"
#define DEVICETEMPLATE_PACKAGE_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICETEMPLATE_PACKAGE_PSC_FROZEN_TABLE_FIELD "DeviceTemplate_Package.psc_frozen"
#define DEVICETEMPLATE_PACKAGE_PSC_MOD_FIELD "psc_mod"
#define DEVICETEMPLATE_PACKAGE_PSC_MOD_TABLE_FIELD "DeviceTemplate_Package.psc_mod"


#endif

