#ifndef __Define_Users_H__
#define __Define_Users_H__


#define USERS_TABLE "Users"
#define USERS_PK_USERS_FIELD "PK_Users"
#define USERS_PK_USERS_TABLE_FIELD "Users.PK_Users"
#define USERS_USERNAME_FIELD "UserName"
#define USERS_USERNAME_TABLE_FIELD "Users.UserName"
#define USERS_PASSWORD_FIELD "Password"
#define USERS_PASSWORD_TABLE_FIELD "Users.Password"
#define USERS_HASMAILBOX_FIELD "HasMailbox"
#define USERS_HASMAILBOX_TABLE_FIELD "Users.HasMailbox"
#define USERS_ACCESSGENERALMAILBOX_FIELD "AccessGeneralMailbox"
#define USERS_ACCESSGENERALMAILBOX_TABLE_FIELD "Users.AccessGeneralMailbox"
#define USERS_EXTENSION_FIELD "Extension"
#define USERS_EXTENSION_TABLE_FIELD "Users.Extension"
#define USERS_FIRSTNAME_FIELD "FirstName"
#define USERS_FIRSTNAME_TABLE_FIELD "Users.FirstName"
#define USERS_LASTNAME_FIELD "LastName"
#define USERS_LASTNAME_TABLE_FIELD "Users.LastName"
#define USERS_NICKNAME_FIELD "Nickname"
#define USERS_NICKNAME_TABLE_FIELD "Users.Nickname"
#define USERS_EXTENSIONRINGTIMEOUT_FIELD "ExtensionRingTimeout"
#define USERS_EXTENSIONRINGTIMEOUT_TABLE_FIELD "Users.ExtensionRingTimeout"
#define USERS_EMAIL_FIELD "Email"
#define USERS_EMAIL_TABLE_FIELD "Users.Email"
#define USERS_FK_LANGUAGE_FIELD "FK_Language"
#define USERS_FK_LANGUAGE_TABLE_FIELD "Users.FK_Language"
#define USERS_FK_INSTALLATION_MAIN_FIELD "FK_Installation_Main"
#define USERS_FK_INSTALLATION_MAIN_TABLE_FIELD "Users.FK_Installation_Main"
#define USERS_PSC_ID_FIELD "psc_id"
#define USERS_PSC_ID_TABLE_FIELD "Users.psc_id"
#define USERS_PSC_BATCH_FIELD "psc_batch"
#define USERS_PSC_BATCH_TABLE_FIELD "Users.psc_batch"
#define USERS_PSC_USER_FIELD "psc_user"
#define USERS_PSC_USER_TABLE_FIELD "Users.psc_user"
#define USERS_PSC_FROZEN_FIELD "psc_frozen"
#define USERS_PSC_FROZEN_TABLE_FIELD "Users.psc_frozen"
#define USERS_PSC_MOD_FIELD "psc_mod"
#define USERS_PSC_MOD_TABLE_FIELD "Users.psc_mod"


#endif

