#ifndef __Define_DeviceTemplate_AV_H__
#define __Define_DeviceTemplate_AV_H__


#define DEVICETEMPLATE_AV_TABLE "DeviceTemplate_AV"
#define DEVICETEMPLATE_AV_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define DEVICETEMPLATE_AV_FK_DEVICETEMPLATE_TABLE_FIELD "DeviceTemplate_AV.FK_DeviceTemplate"
#define DEVICETEMPLATE_AV_IR_POWERDELAY_FIELD "IR_PowerDelay"
#define DEVICETEMPLATE_AV_IR_POWERDELAY_TABLE_FIELD "DeviceTemplate_AV.IR_PowerDelay"
#define DEVICETEMPLATE_AV_IR_MODEDELAY_FIELD "IR_ModeDelay"
#define DEVICETEMPLATE_AV_IR_MODEDELAY_TABLE_FIELD "DeviceTemplate_AV.IR_ModeDelay"
#define DEVICETEMPLATE_AV_DIGITDELAY_FIELD "DigitDelay"
#define DEVICETEMPLATE_AV_DIGITDELAY_TABLE_FIELD "DeviceTemplate_AV.DigitDelay"
#define DEVICETEMPLATE_AV_TOGGLEPOWER_FIELD "TogglePower"
#define DEVICETEMPLATE_AV_TOGGLEPOWER_TABLE_FIELD "DeviceTemplate_AV.TogglePower"
#define DEVICETEMPLATE_AV_TOGGLEDSP_FIELD "ToggleDSP"
#define DEVICETEMPLATE_AV_TOGGLEDSP_TABLE_FIELD "DeviceTemplate_AV.ToggleDSP"
#define DEVICETEMPLATE_AV_TOGGLEINPUT_FIELD "ToggleInput"
#define DEVICETEMPLATE_AV_TOGGLEINPUT_TABLE_FIELD "DeviceTemplate_AV.ToggleInput"
#define DEVICETEMPLATE_AV_TOGGLEOUTPUT_FIELD "ToggleOutput"
#define DEVICETEMPLATE_AV_TOGGLEOUTPUT_TABLE_FIELD "DeviceTemplate_AV.ToggleOutput"
#define DEVICETEMPLATE_AV_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define DEVICETEMPLATE_AV_MODIFICATION_RECORDINFO_TABLE_FIELD "DeviceTemplate_AV.Modification_RecordInfo"
#define DEVICETEMPLATE_AV_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define DEVICETEMPLATE_AV_ISNEW_RECORDINFO_TABLE_FIELD "DeviceTemplate_AV.IsNew_RecordInfo"
#define DEVICETEMPLATE_AV_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define DEVICETEMPLATE_AV_ISDELETED_RECORDINFO_TABLE_FIELD "DeviceTemplate_AV.IsDeleted_RecordInfo"
#define DEVICETEMPLATE_AV_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define DEVICETEMPLATE_AV_FK_USERS_RECORDINFO_TABLE_FIELD "DeviceTemplate_AV.FK_Users_RecordInfo"


#endif

