#ifndef __Define_InfraredCode_H__
#define __Define_InfraredCode_H__


#define INFRAREDCODE_TABLE "InfraredCode"
#define INFRAREDCODE_FK_INFRAREDGROUP_FIELD "FK_InfraredGroup"
#define INFRAREDCODE_FK_INFRAREDGROUP_TABLE_FIELD "InfraredCode.FK_InfraredGroup"
#define INFRAREDCODE_FK_COMMAND_FIELD "FK_Command"
#define INFRAREDCODE_FK_COMMAND_TABLE_FIELD "InfraredCode.FK_Command"
#define INFRAREDCODE_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define INFRAREDCODE_FK_DEVICETEMPLATE_TABLE_FIELD "InfraredCode.FK_DeviceTemplate"
#define INFRAREDCODE_FK_DEVICE_FIELD "FK_Device"
#define INFRAREDCODE_FK_DEVICE_TABLE_FIELD "InfraredCode.FK_Device"
#define INFRAREDCODE_DESCRIPTION_FIELD "Description"
#define INFRAREDCODE_DESCRIPTION_TABLE_FIELD "InfraredCode.Description"
#define INFRAREDCODE_IRDATA_FIELD "IRData"
#define INFRAREDCODE_IRDATA_TABLE_FIELD "InfraredCode.IRData"
#define INFRAREDCODE_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define INFRAREDCODE_MODIFICATION_RECORDINFO_TABLE_FIELD "InfraredCode.Modification_RecordInfo"
#define INFRAREDCODE_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define INFRAREDCODE_ISNEW_RECORDINFO_TABLE_FIELD "InfraredCode.IsNew_RecordInfo"
#define INFRAREDCODE_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define INFRAREDCODE_ISDELETED_RECORDINFO_TABLE_FIELD "InfraredCode.IsDeleted_RecordInfo"
#define INFRAREDCODE_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define INFRAREDCODE_FK_USERS_RECORDINFO_TABLE_FIELD "InfraredCode.FK_Users_RecordInfo"


#endif

