#ifndef __Define_CriteriaParmNesting_D_H__
#define __Define_CriteriaParmNesting_D_H__


#define CRITERIAPARMNESTING_D_TABLE "CriteriaParmNesting_D"
#define CRITERIAPARMNESTING_D_PK_CRITERIAPARMNESTING_D_FIELD "PK_CriteriaParmNesting_D"
#define CRITERIAPARMNESTING_D_PK_CRITERIAPARMNESTING_D_TABLE_FIELD "CriteriaParmNesting_D.PK_CriteriaParmNesting_D"
#define CRITERIAPARMNESTING_D_FK_CRITERIAPARMNESTING_D_PARENT_FIELD "FK_CriteriaParmNesting_D_Parent"
#define CRITERIAPARMNESTING_D_FK_CRITERIAPARMNESTING_D_PARENT_TABLE_FIELD "CriteriaParmNesting_D.FK_CriteriaParmNesting_D_Parent"
#define CRITERIAPARMNESTING_D_ISAND_FIELD "IsAnd"
#define CRITERIAPARMNESTING_D_ISAND_TABLE_FIELD "CriteriaParmNesting_D.IsAnd"
#define CRITERIAPARMNESTING_D_ISNOT_FIELD "IsNot"
#define CRITERIAPARMNESTING_D_ISNOT_TABLE_FIELD "CriteriaParmNesting_D.IsNot"
#define CRITERIAPARMNESTING_D_PSC_ID_FIELD "psc_id"
#define CRITERIAPARMNESTING_D_PSC_ID_TABLE_FIELD "CriteriaParmNesting_D.psc_id"
#define CRITERIAPARMNESTING_D_PSC_BATCH_FIELD "psc_batch"
#define CRITERIAPARMNESTING_D_PSC_BATCH_TABLE_FIELD "CriteriaParmNesting_D.psc_batch"
#define CRITERIAPARMNESTING_D_PSC_USER_FIELD "psc_user"
#define CRITERIAPARMNESTING_D_PSC_USER_TABLE_FIELD "CriteriaParmNesting_D.psc_user"
#define CRITERIAPARMNESTING_D_PSC_FROZEN_FIELD "psc_frozen"
#define CRITERIAPARMNESTING_D_PSC_FROZEN_TABLE_FIELD "CriteriaParmNesting_D.psc_frozen"
#define CRITERIAPARMNESTING_D_PSC_MOD_FIELD "psc_mod"
#define CRITERIAPARMNESTING_D_PSC_MOD_TABLE_FIELD "CriteriaParmNesting_D.psc_mod"


#endif

