#ifndef __Define_RepositoryType_H__
#define __Define_RepositoryType_H__

#define REPOSITORYTYPE_PACKAGE_CONST 1
#define REPOSITORYTYPE_FTP_download_CONST 2
#define REPOSITORYTYPE_CVS_CONST 3
#define REPOSITORYTYPE_Subversion_SVN_CONST 4
#define REPOSITORYTYPE_HTTP_Download_CONST 5

#define REPOSITORYTYPE_TABLE "RepositoryType"
#define REPOSITORYTYPE_PK_REPOSITORYTYPE_FIELD "PK_RepositoryType"
#define REPOSITORYTYPE_PK_REPOSITORYTYPE_TABLE_FIELD "RepositoryType.PK_RepositoryType"
#define REPOSITORYTYPE_DESCRIPTION_FIELD "Description"
#define REPOSITORYTYPE_DESCRIPTION_TABLE_FIELD "RepositoryType.Description"
#define REPOSITORYTYPE_DEFINE_FIELD "Define"
#define REPOSITORYTYPE_DEFINE_TABLE_FIELD "RepositoryType.Define"
#define REPOSITORYTYPE_SOURCEONLY_FIELD "SourceOnly"
#define REPOSITORYTYPE_SOURCEONLY_TABLE_FIELD "RepositoryType.SourceOnly"
#define REPOSITORYTYPE_PATHTOFILE_FIELD "PathToFile"
#define REPOSITORYTYPE_PATHTOFILE_TABLE_FIELD "RepositoryType.PathToFile"
#define REPOSITORYTYPE_INSTRUCTIONS_FIELD "Instructions"
#define REPOSITORYTYPE_INSTRUCTIONS_TABLE_FIELD "RepositoryType.Instructions"
#define REPOSITORYTYPE_PSC_ID_FIELD "psc_id"
#define REPOSITORYTYPE_PSC_ID_TABLE_FIELD "RepositoryType.psc_id"
#define REPOSITORYTYPE_PSC_BATCH_FIELD "psc_batch"
#define REPOSITORYTYPE_PSC_BATCH_TABLE_FIELD "RepositoryType.psc_batch"
#define REPOSITORYTYPE_PSC_USER_FIELD "psc_user"
#define REPOSITORYTYPE_PSC_USER_TABLE_FIELD "RepositoryType.psc_user"
#define REPOSITORYTYPE_PSC_FROZEN_FIELD "psc_frozen"
#define REPOSITORYTYPE_PSC_FROZEN_TABLE_FIELD "RepositoryType.psc_frozen"
#define REPOSITORYTYPE_PSC_MOD_FIELD "psc_mod"
#define REPOSITORYTYPE_PSC_MOD_TABLE_FIELD "RepositoryType.psc_mod"


#endif

