#ifndef __Define_Device_H__
#define __Define_Device_H__


#define DEVICE_TABLE "Device"
#define DEVICE_PK_DEVICE_FIELD "PK_Device"
#define DEVICE_PK_DEVICE_TABLE_FIELD "Device.PK_Device"
#define DEVICE_DISABLED_FIELD "Disabled"
#define DEVICE_DISABLED_TABLE_FIELD "Device.Disabled"
#define DEVICE_FK_ROOM_FIELD "FK_Room"
#define DEVICE_FK_ROOM_TABLE_FIELD "Device.FK_Room"
#define DEVICE_FK_INSTALLATION_FIELD "FK_Installation"
#define DEVICE_FK_INSTALLATION_TABLE_FIELD "Device.FK_Installation"
#define DEVICE_FK_DESIGNOBJ_FIELD "FK_DesignObj"
#define DEVICE_FK_DESIGNOBJ_TABLE_FIELD "Device.FK_DesignObj"
#define DEVICE_DESCRIPTION_FIELD "Description"
#define DEVICE_DESCRIPTION_TABLE_FIELD "Device.Description"
#define DEVICE_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define DEVICE_FK_DEVICETEMPLATE_TABLE_FIELD "Device.FK_DeviceTemplate"
#define DEVICE_FK_DEVICE_CONTROLLEDVIA_FIELD "FK_Device_ControlledVia"
#define DEVICE_FK_DEVICE_CONTROLLEDVIA_TABLE_FIELD "Device.FK_Device_ControlledVia"
#define DEVICE_IPADDRESS_FIELD "IPaddress"
#define DEVICE_IPADDRESS_TABLE_FIELD "Device.IPaddress"
#define DEVICE_MACADDRESS_FIELD "MACaddress"
#define DEVICE_MACADDRESS_TABLE_FIELD "Device.MACaddress"
#define DEVICE_IGNOREONOFF_FIELD "IgnoreOnOff"
#define DEVICE_IGNOREONOFF_TABLE_FIELD "Device.IgnoreOnOff"
#define DEVICE_FK_DEVICE_SLAVETO_FIELD "FK_Device_SlaveTo"
#define DEVICE_FK_DEVICE_SLAVETO_TABLE_FIELD "Device.FK_Device_SlaveTo"
#define DEVICE_NEEDCONFIGURE_FIELD "NeedConfigure"
#define DEVICE_NEEDCONFIGURE_TABLE_FIELD "Device.NeedConfigure"
#define DEVICE_PSC_ID_FIELD "psc_id"
#define DEVICE_PSC_ID_TABLE_FIELD "Device.psc_id"
#define DEVICE_PSC_BATCH_FIELD "psc_batch"
#define DEVICE_PSC_BATCH_TABLE_FIELD "Device.psc_batch"
#define DEVICE_PSC_USER_FIELD "psc_user"
#define DEVICE_PSC_USER_TABLE_FIELD "Device.psc_user"
#define DEVICE_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICE_PSC_FROZEN_TABLE_FIELD "Device.psc_frozen"
#define DEVICE_PSC_MOD_FIELD "psc_mod"
#define DEVICE_PSC_MOD_TABLE_FIELD "Device.psc_mod"


#endif

