#ifndef __Define_psc_designer_batdet_H__
#define __Define_psc_designer_batdet_H__


#define PSC_DESIGNER_BATDET_TABLE "psc_designer_batdet"
#define PSC_DESIGNER_BATDET_PK_PSC_DESIGNER_BATDET_FIELD "PK_psc_designer_batdet"
#define PSC_DESIGNER_BATDET_PK_PSC_DESIGNER_BATDET_TABLE_FIELD "psc_designer_batdet.PK_psc_designer_batdet"
#define PSC_DESIGNER_BATDET_FK_PSC_DESIGNER_BATHDR_FIELD "FK_psc_designer_bathdr"
#define PSC_DESIGNER_BATDET_FK_PSC_DESIGNER_BATHDR_TABLE_FIELD "psc_designer_batdet.FK_psc_designer_bathdr"
#define PSC_DESIGNER_BATDET_TABLENAME_FIELD "Tablename"
#define PSC_DESIGNER_BATDET_TABLENAME_TABLE_FIELD "psc_designer_batdet.Tablename"
#define PSC_DESIGNER_BATDET_NEW_FIELD "New"
#define PSC_DESIGNER_BATDET_NEW_TABLE_FIELD "psc_designer_batdet.New"
#define PSC_DESIGNER_BATDET_DELETED_FIELD "Deleted"
#define PSC_DESIGNER_BATDET_DELETED_TABLE_FIELD "psc_designer_batdet.Deleted"
#define PSC_DESIGNER_BATDET_MODIFIED_FIELD "Modified"
#define PSC_DESIGNER_BATDET_MODIFIED_TABLE_FIELD "psc_designer_batdet.Modified"
#define PSC_DESIGNER_BATDET_FK_PSC_DESIGNER_BATHDR_ORIG_FIELD "FK_psc_designer_bathdr_orig"
#define PSC_DESIGNER_BATDET_FK_PSC_DESIGNER_BATHDR_ORIG_TABLE_FIELD "psc_designer_batdet.FK_psc_designer_bathdr_orig"
#define PSC_DESIGNER_BATDET_FK_PSC_DESIGNER_BATHDR_AUTH_FIELD "FK_psc_designer_bathdr_auth"
#define PSC_DESIGNER_BATDET_FK_PSC_DESIGNER_BATHDR_AUTH_TABLE_FIELD "psc_designer_batdet.FK_psc_designer_bathdr_auth"
#define PSC_DESIGNER_BATDET_FK_PSC_DESIGNER_BATHDR_UNAUTH_FIELD "FK_psc_designer_bathdr_unauth"
#define PSC_DESIGNER_BATDET_FK_PSC_DESIGNER_BATHDR_UNAUTH_TABLE_FIELD "psc_designer_batdet.FK_psc_designer_bathdr_unauth"


#endif

