#ifndef __Define_Device_CommandGroup_H__
#define __Define_Device_CommandGroup_H__


#define DEVICE_COMMANDGROUP_TABLE "Device_CommandGroup"
#define DEVICE_COMMANDGROUP_FK_DEVICE_FIELD "FK_Device"
#define DEVICE_COMMANDGROUP_FK_DEVICE_TABLE_FIELD "Device_CommandGroup.FK_Device"
#define DEVICE_COMMANDGROUP_FK_COMMANDGROUP_FIELD "FK_CommandGroup"
#define DEVICE_COMMANDGROUP_FK_COMMANDGROUP_TABLE_FIELD "Device_CommandGroup.FK_CommandGroup"
#define DEVICE_COMMANDGROUP_SORT_FIELD "Sort"
#define DEVICE_COMMANDGROUP_SORT_TABLE_FIELD "Device_CommandGroup.Sort"
#define DEVICE_COMMANDGROUP_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define DEVICE_COMMANDGROUP_MODIFICATION_RECORDINFO_TABLE_FIELD "Device_CommandGroup.Modification_RecordInfo"
#define DEVICE_COMMANDGROUP_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define DEVICE_COMMANDGROUP_ISNEW_RECORDINFO_TABLE_FIELD "Device_CommandGroup.IsNew_RecordInfo"
#define DEVICE_COMMANDGROUP_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define DEVICE_COMMANDGROUP_ISDELETED_RECORDINFO_TABLE_FIELD "Device_CommandGroup.IsDeleted_RecordInfo"
#define DEVICE_COMMANDGROUP_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define DEVICE_COMMANDGROUP_FK_USERS_RECORDINFO_TABLE_FIELD "Device_CommandGroup.FK_Users_RecordInfo"


#endif

