#ifndef __Define_psc_constants_batdet_H__
#define __Define_psc_constants_batdet_H__


#define PSC_CONSTANTS_BATDET_TABLE "psc_constants_batdet"
#define PSC_CONSTANTS_BATDET_PK_PSC_CONSTANTS_BATDET_FIELD "PK_psc_constants_batdet"
#define PSC_CONSTANTS_BATDET_PK_PSC_CONSTANTS_BATDET_TABLE_FIELD "psc_constants_batdet.PK_psc_constants_batdet"
#define PSC_CONSTANTS_BATDET_FK_PSC_CONSTANTS_BATHDR_FIELD "FK_psc_constants_bathdr"
#define PSC_CONSTANTS_BATDET_FK_PSC_CONSTANTS_BATHDR_TABLE_FIELD "psc_constants_batdet.FK_psc_constants_bathdr"
#define PSC_CONSTANTS_BATDET_TABLENAME_FIELD "Tablename"
#define PSC_CONSTANTS_BATDET_TABLENAME_TABLE_FIELD "psc_constants_batdet.Tablename"
#define PSC_CONSTANTS_BATDET_NEW_FIELD "New"
#define PSC_CONSTANTS_BATDET_NEW_TABLE_FIELD "psc_constants_batdet.New"
#define PSC_CONSTANTS_BATDET_DELETED_FIELD "Deleted"
#define PSC_CONSTANTS_BATDET_DELETED_TABLE_FIELD "psc_constants_batdet.Deleted"
#define PSC_CONSTANTS_BATDET_MODIFIED_FIELD "Modified"
#define PSC_CONSTANTS_BATDET_MODIFIED_TABLE_FIELD "psc_constants_batdet.Modified"
#define PSC_CONSTANTS_BATDET_FK_PSC_CONSTANTS_BATHDR_ORIG_FIELD "FK_psc_constants_bathdr_orig"
#define PSC_CONSTANTS_BATDET_FK_PSC_CONSTANTS_BATHDR_ORIG_TABLE_FIELD "psc_constants_batdet.FK_psc_constants_bathdr_orig"
#define PSC_CONSTANTS_BATDET_FK_PSC_CONSTANTS_BATHDR_AUTH_FIELD "FK_psc_constants_bathdr_auth"
#define PSC_CONSTANTS_BATDET_FK_PSC_CONSTANTS_BATHDR_AUTH_TABLE_FIELD "psc_constants_batdet.FK_psc_constants_bathdr_auth"
#define PSC_CONSTANTS_BATDET_FK_PSC_CONSTANTS_BATHDR_UNAUTH_FIELD "FK_psc_constants_bathdr_unauth"
#define PSC_CONSTANTS_BATDET_FK_PSC_CONSTANTS_BATHDR_UNAUTH_TABLE_FIELD "psc_constants_batdet.FK_psc_constants_bathdr_unauth"


#endif

