#ifndef __Define_PhoneLineType_H__
#define __Define_PhoneLineType_H__


#define PHONELINETYPE_TABLE "PhoneLineType"
#define PHONELINETYPE_PK_PHONELINETYPE_FIELD "PK_PhoneLineType"
#define PHONELINETYPE_PK_PHONELINETYPE_TABLE_FIELD "PhoneLineType.PK_PhoneLineType"
#define PHONELINETYPE_DESCRIPTION_FIELD "Description"
#define PHONELINETYPE_DESCRIPTION_TABLE_FIELD "PhoneLineType.Description"
#define PHONELINETYPE_DEFINE_FIELD "Define"
#define PHONELINETYPE_DEFINE_TABLE_FIELD "PhoneLineType.Define"
#define PHONELINETYPE_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define PHONELINETYPE_MODIFICATION_RECORDINFO_TABLE_FIELD "PhoneLineType.Modification_RecordInfo"
#define PHONELINETYPE_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define PHONELINETYPE_ISNEW_RECORDINFO_TABLE_FIELD "PhoneLineType.IsNew_RecordInfo"
#define PHONELINETYPE_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define PHONELINETYPE_ISDELETED_RECORDINFO_TABLE_FIELD "PhoneLineType.IsDeleted_RecordInfo"
#define PHONELINETYPE_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define PHONELINETYPE_FK_USERS_RECORDINFO_TABLE_FIELD "PhoneLineType.FK_Users_RecordInfo"


#endif

