#ifndef __Define_ConfigType_Token_H__
#define __Define_ConfigType_Token_H__


#define CONFIGTYPE_TOKEN_TABLE "ConfigType_Token"
#define CONFIGTYPE_TOKEN_FK_CONFIGTYPE_SETTING_FIELD "FK_ConfigType_Setting"
#define CONFIGTYPE_TOKEN_FK_CONFIGTYPE_SETTING_TABLE_FIELD "ConfigType_Token.FK_ConfigType_Setting"
#define CONFIGTYPE_TOKEN_FK_CONFIGTYPE_FILE_FIELD "FK_ConfigType_File"
#define CONFIGTYPE_TOKEN_FK_CONFIGTYPE_FILE_TABLE_FIELD "ConfigType_Token.FK_ConfigType_File"
#define CONFIGTYPE_TOKEN_FINDSTR_FIELD "FindStr"
#define CONFIGTYPE_TOKEN_FINDSTR_TABLE_FIELD "ConfigType_Token.FindStr"
#define CONFIGTYPE_TOKEN_REPLACESTR_FIELD "ReplaceStr"
#define CONFIGTYPE_TOKEN_REPLACESTR_TABLE_FIELD "ConfigType_Token.ReplaceStr"
#define CONFIGTYPE_TOKEN_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define CONFIGTYPE_TOKEN_MODIFICATION_RECORDINFO_TABLE_FIELD "ConfigType_Token.Modification_RecordInfo"
#define CONFIGTYPE_TOKEN_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define CONFIGTYPE_TOKEN_ISNEW_RECORDINFO_TABLE_FIELD "ConfigType_Token.IsNew_RecordInfo"
#define CONFIGTYPE_TOKEN_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define CONFIGTYPE_TOKEN_ISDELETED_RECORDINFO_TABLE_FIELD "ConfigType_Token.IsDeleted_RecordInfo"
#define CONFIGTYPE_TOKEN_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define CONFIGTYPE_TOKEN_FK_USERS_RECORDINFO_TABLE_FIELD "ConfigType_Token.FK_Users_RecordInfo"


#endif

