#ifndef __Define_CriteriaList_CriteriaParmList_H__
#define __Define_CriteriaList_CriteriaParmList_H__


#define CRITERIALIST_CRITERIAPARMLIST_TABLE "CriteriaList_CriteriaParmList"
#define CRITERIALIST_CRITERIAPARMLIST_FK_CRITERIALIST_FIELD "FK_CriteriaList"
#define CRITERIALIST_CRITERIAPARMLIST_FK_CRITERIALIST_TABLE_FIELD "CriteriaList_CriteriaParmList.FK_CriteriaList"
#define CRITERIALIST_CRITERIAPARMLIST_FK_CRITERIAPARMLIST_FIELD "FK_CriteriaParmList"
#define CRITERIALIST_CRITERIAPARMLIST_FK_CRITERIAPARMLIST_TABLE_FIELD "CriteriaList_CriteriaParmList.FK_CriteriaParmList"


#endif

