#ifndef __Define_InfraredGroup_DSPMode_H__
#define __Define_InfraredGroup_DSPMode_H__


#define INFRAREDGROUP_DSPMODE_TABLE "InfraredGroup_DSPMode"
#define INFRAREDGROUP_DSPMODE_FK_INFRAREDGROUP_FIELD "FK_InfraredGroup"
#define INFRAREDGROUP_DSPMODE_FK_INFRAREDGROUP_TABLE_FIELD "InfraredGroup_DSPMode.FK_InfraredGroup"
#define INFRAREDGROUP_DSPMODE_FK_DSPMODE_FIELD "FK_DSPMode"
#define INFRAREDGROUP_DSPMODE_FK_DSPMODE_TABLE_FIELD "InfraredGroup_DSPMode.FK_DSPMode"
#define INFRAREDGROUP_DSPMODE_DESCRIPTION_FIELD "Description"
#define INFRAREDGROUP_DSPMODE_DESCRIPTION_TABLE_FIELD "InfraredGroup_DSPMode.Description"
#define INFRAREDGROUP_DSPMODE_FK_COMMAND_FIELD "FK_Command"
#define INFRAREDGROUP_DSPMODE_FK_COMMAND_TABLE_FIELD "InfraredGroup_DSPMode.FK_Command"
#define INFRAREDGROUP_DSPMODE_PSC_ID_FIELD "psc_id"
#define INFRAREDGROUP_DSPMODE_PSC_ID_TABLE_FIELD "InfraredGroup_DSPMode.psc_id"
#define INFRAREDGROUP_DSPMODE_PSC_BATCH_FIELD "psc_batch"
#define INFRAREDGROUP_DSPMODE_PSC_BATCH_TABLE_FIELD "InfraredGroup_DSPMode.psc_batch"
#define INFRAREDGROUP_DSPMODE_PSC_USER_FIELD "psc_user"
#define INFRAREDGROUP_DSPMODE_PSC_USER_TABLE_FIELD "InfraredGroup_DSPMode.psc_user"
#define INFRAREDGROUP_DSPMODE_PSC_FROZEN_FIELD "psc_frozen"
#define INFRAREDGROUP_DSPMODE_PSC_FROZEN_TABLE_FIELD "InfraredGroup_DSPMode.psc_frozen"
#define INFRAREDGROUP_DSPMODE_PSC_MOD_FIELD "psc_mod"
#define INFRAREDGROUP_DSPMODE_PSC_MOD_TABLE_FIELD "InfraredGroup_DSPMode.psc_mod"


#endif

