#ifndef __Define_FloorplanObjectType_H__
#define __Define_FloorplanObjectType_H__


#define FLOORPLANOBJECTTYPE_TABLE "FloorplanObjectType"
#define FLOORPLANOBJECTTYPE_PK_FLOORPLANDESIGNOBJTYPE_FIELD "PK_FloorplanDesignObjType"
#define FLOORPLANOBJECTTYPE_PK_FLOORPLANDESIGNOBJTYPE_TABLE_FIELD "FloorplanObjectType.PK_FloorplanDesignObjType"
#define FLOORPLANOBJECTTYPE_FK_FLOORPLANTYPE_FIELD "FK_FloorplanType"
#define FLOORPLANOBJECTTYPE_FK_FLOORPLANTYPE_TABLE_FIELD "FloorplanObjectType.FK_FloorplanType"
#define FLOORPLANOBJECTTYPE_DESCRIPTION_FIELD "Description"
#define FLOORPLANOBJECTTYPE_DESCRIPTION_TABLE_FIELD "FloorplanObjectType.Description"
#define FLOORPLANOBJECTTYPE_DEFINE_FIELD "Define"
#define FLOORPLANOBJECTTYPE_DEFINE_TABLE_FIELD "FloorplanObjectType.Define"
#define FLOORPLANOBJECTTYPE_DIRECTION_FIELD "Direction"
#define FLOORPLANOBJECTTYPE_DIRECTION_TABLE_FIELD "FloorplanObjectType.Direction"
#define FLOORPLANOBJECTTYPE_FK_DESIGNOBJ_CONTROL_FIELD "FK_DesignObj_Control"
#define FLOORPLANOBJECTTYPE_FK_DESIGNOBJ_CONTROL_TABLE_FIELD "FloorplanObjectType.FK_DesignObj_Control"
#define FLOORPLANOBJECTTYPE_FILENAME_FIELD "Filename"
#define FLOORPLANOBJECTTYPE_FILENAME_TABLE_FIELD "FloorplanObjectType.Filename"
#define FLOORPLANOBJECTTYPE_FILLX_FIELD "FillX"
#define FLOORPLANOBJECTTYPE_FILLX_TABLE_FIELD "FloorplanObjectType.FillX"
#define FLOORPLANOBJECTTYPE_FILLY_FIELD "FillY"
#define FLOORPLANOBJECTTYPE_FILLY_TABLE_FIELD "FloorplanObjectType.FillY"
#define FLOORPLANOBJECTTYPE_PSC_ID_FIELD "psc_id"
#define FLOORPLANOBJECTTYPE_PSC_ID_TABLE_FIELD "FloorplanObjectType.psc_id"
#define FLOORPLANOBJECTTYPE_PSC_BATCH_FIELD "psc_batch"
#define FLOORPLANOBJECTTYPE_PSC_BATCH_TABLE_FIELD "FloorplanObjectType.psc_batch"
#define FLOORPLANOBJECTTYPE_PSC_USER_FIELD "psc_user"
#define FLOORPLANOBJECTTYPE_PSC_USER_TABLE_FIELD "FloorplanObjectType.psc_user"
#define FLOORPLANOBJECTTYPE_PSC_FROZEN_FIELD "psc_frozen"
#define FLOORPLANOBJECTTYPE_PSC_FROZEN_TABLE_FIELD "FloorplanObjectType.psc_frozen"
#define FLOORPLANOBJECTTYPE_PSC_MOD_FIELD "psc_mod"
#define FLOORPLANOBJECTTYPE_PSC_MOD_TABLE_FIELD "FloorplanObjectType.psc_mod"


#endif

