#ifndef __Define_DeviceTemplate_H__
#define __Define_DeviceTemplate_H__

#define DEVICETEMPLATE_Standard_Orbiters_in_my_room_CONST -303
#define DEVICETEMPLATE_Mobile_Orbiters_in_my_room_CONST -302
#define DEVICETEMPLATE_Orbiters_in_my_room_CONST -301
#define DEVICETEMPLATE_VirtDev_Disc_Drive_CONST -202
#define DEVICETEMPLATE_VirtDev_AppServer_CONST -201
#define DEVICETEMPLATE_VirtDev_Security_Plugin_CONST -108
#define DEVICETEMPLATE_VirtDev_Telecom_Plugin_CONST -107
#define DEVICETEMPLATE_VirtDev_Media_Plugin_CONST -106
#define DEVICETEMPLATE_VirtDev_Climate_PlugIn_CONST -105
#define DEVICETEMPLATE_VirtDev_Lighting_PlugIn_CONST -104
#define DEVICETEMPLATE_VirtDev_General_Info_Plugin_CONST -103
#define DEVICETEMPLATE_VirtDev_Datagrid_Plugin_CONST -102
#define DEVICETEMPLATE_VirtDev_Orbiter_Plugin_CONST -101
#define DEVICETEMPLATE_VirtDev_DCE_Router_CONST -100
#define DEVICETEMPLATE_DCE_Router_CONST 1
#define DEVICETEMPLATE_Media_Plugin_CONST 2
#define DEVICETEMPLATE_Entertain_Unit_CONST 3
#define DEVICETEMPLATE_DCE_Router_old_CONST 4
#define DEVICETEMPLATE_Xine_Player_CONST 5
#define DEVICETEMPLATE_Xine_Plugin_CONST 6
#define DEVICETEMPLATE_Pluto_Core_CONST 7
#define DEVICETEMPLATE_Orbiter_CONST 8
#define DEVICETEMPLATE_Datagrid_Plugin_CONST 9
#define DEVICETEMPLATE_File_Grids_Plugin_CONST 10
#define DEVICETEMPLATE_Disk_Drive_CONST 11
#define DEVICETEMPLATE_Orbiter_Plugin_CONST 12
#define DEVICETEMPLATE_Bluetooth_Dongle_CONST 13
#define DEVICETEMPLATE_test_CONST 14
#define DEVICETEMPLATE_Symbian_60_CONST 24
#define DEVICETEMPLATE_not_usedMedia_Grids_Plug_CONST 25
#define DEVICETEMPLATE_App_Server_CONST 26
#define DEVICETEMPLATE_General_Info_Plugin_CONST 27
#define DEVICETEMPLATE_Generic_Linux_MD_CONST 28
#define DEVICETEMPLATE_Mozilla_Plugin_CONST 30
#define DEVICETEMPLATE_Climate_Plugin_CONST 31
#define DEVICETEMPLATE_Lighting_Plugin_CONST 32
#define DEVICETEMPLATE_Security_Plugin_CONST 33
#define DEVICETEMPLATE_Telecom_Plugin_CONST 34
#define DEVICETEMPLATE_MythTV_Player_CONST 35
#define DEVICETEMPLATE_MythTV_PlugIn_CONST 36
#define DEVICETEMPLATE_Light_Switch_onoff_CONST 37
#define DEVICETEMPLATE_Light_Switch_dimmable_CONST 38
#define DEVICETEMPLATE_Infrared_Plugin_CONST 39
#define DEVICETEMPLATE_gc100_CONST 40
#define DEVICETEMPLATE_Test_TV_CONST 41
#define DEVICETEMPLATE_IO_Relay_CONST 42
#define DEVICETEMPLATE_Generic_Input_Ouput_CONST 43

#define DEVICETEMPLATE_TABLE "DeviceTemplate"
#define DEVICETEMPLATE_PK_DEVICETEMPLATE_FIELD "PK_DeviceTemplate"
#define DEVICETEMPLATE_PK_DEVICETEMPLATE_TABLE_FIELD "DeviceTemplate.PK_DeviceTemplate"
#define DEVICETEMPLATE_DESCRIPTION_FIELD "Description"
#define DEVICETEMPLATE_DESCRIPTION_TABLE_FIELD "DeviceTemplate.Description"
#define DEVICETEMPLATE_COMMENTS_FIELD "Comments"
#define DEVICETEMPLATE_COMMENTS_TABLE_FIELD "DeviceTemplate.Comments"
#define DEVICETEMPLATE_FK_DEVICECATEGORY_FIELD "FK_DeviceCategory"
#define DEVICETEMPLATE_FK_DEVICECATEGORY_TABLE_FIELD "DeviceTemplate.FK_DeviceCategory"
#define DEVICETEMPLATE_FK_MANUFACTURER_FIELD "FK_Manufacturer"
#define DEVICETEMPLATE_FK_MANUFACTURER_TABLE_FIELD "DeviceTemplate.FK_Manufacturer"
#define DEVICETEMPLATE_DEFINE_FIELD "Define"
#define DEVICETEMPLATE_DEFINE_TABLE_FIELD "DeviceTemplate.Define"
#define DEVICETEMPLATE_IMPLEMENTSDCE_FIELD "ImplementsDCE"
#define DEVICETEMPLATE_IMPLEMENTSDCE_TABLE_FIELD "DeviceTemplate.ImplementsDCE"
#define DEVICETEMPLATE_ISEMBEDDED_FIELD "IsEmbedded"
#define DEVICETEMPLATE_ISEMBEDDED_TABLE_FIELD "DeviceTemplate.IsEmbedded"
#define DEVICETEMPLATE_COMMANDLINE_FIELD "CommandLine"
#define DEVICETEMPLATE_COMMANDLINE_TABLE_FIELD "DeviceTemplate.CommandLine"
#define DEVICETEMPLATE_REQUIRESGUI_FIELD "RequiresGUI"
#define DEVICETEMPLATE_REQUIRESGUI_TABLE_FIELD "DeviceTemplate.RequiresGUI"
#define DEVICETEMPLATE_ISAVDEVICE_FIELD "IsAVDevice"
#define DEVICETEMPLATE_ISAVDEVICE_TABLE_FIELD "DeviceTemplate.IsAVDevice"
#define DEVICETEMPLATE_ISPLUGIN_FIELD "IsPlugIn"
#define DEVICETEMPLATE_ISPLUGIN_TABLE_FIELD "DeviceTemplate.IsPlugIn"
#define DEVICETEMPLATE_IRFREQUENCY_FIELD "IRFrequency"
#define DEVICETEMPLATE_IRFREQUENCY_TABLE_FIELD "DeviceTemplate.IRFrequency"
#define DEVICETEMPLATE_FK_STABILITYSTATUS_FIELD "FK_StabilityStatus"
#define DEVICETEMPLATE_FK_STABILITYSTATUS_TABLE_FIELD "DeviceTemplate.FK_StabilityStatus"
#define DEVICETEMPLATE_FK_PACKAGE_FIELD "FK_Package"
#define DEVICETEMPLATE_FK_PACKAGE_TABLE_FIELD "DeviceTemplate.FK_Package"
#define DEVICETEMPLATE_DESTINATIONDIR_FIELD "DestinationDir"
#define DEVICETEMPLATE_DESTINATIONDIR_TABLE_FIELD "DeviceTemplate.DestinationDir"
#define DEVICETEMPLATE_FK_USERS_MAINTAINER_FIELD "FK_Users_Maintainer"
#define DEVICETEMPLATE_FK_USERS_MAINTAINER_TABLE_FIELD "DeviceTemplate.FK_Users_Maintainer"
#define DEVICETEMPLATE_PSC_ID_FIELD "psc_id"
#define DEVICETEMPLATE_PSC_ID_TABLE_FIELD "DeviceTemplate.psc_id"
#define DEVICETEMPLATE_PSC_BATCH_FIELD "psc_batch"
#define DEVICETEMPLATE_PSC_BATCH_TABLE_FIELD "DeviceTemplate.psc_batch"
#define DEVICETEMPLATE_PSC_USER_FIELD "psc_user"
#define DEVICETEMPLATE_PSC_USER_TABLE_FIELD "DeviceTemplate.psc_user"
#define DEVICETEMPLATE_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICETEMPLATE_PSC_FROZEN_TABLE_FIELD "DeviceTemplate.psc_frozen"
#define DEVICETEMPLATE_PSC_MOD_FIELD "psc_mod"
#define DEVICETEMPLATE_PSC_MOD_TABLE_FIELD "DeviceTemplate.psc_mod"


#endif

