#ifndef __Define_DesignObj_H__
#define __Define_DesignObj_H__

#define DESIGNOBJ_home_CONST 2656
#define DESIGNOBJ_go_to_lighting_CONST 2657
#define DESIGNOBJ_go_to_climate_CONST 2658
#define DESIGNOBJ_go_to_security_CONST 2659
#define DESIGNOBJ_go_to_telecom_CONST 2660
#define DESIGNOBJ_center_CONST 2661
#define DESIGNOBJ_carsetup_CONST 2662
#define DESIGNOBJ_go_to_info_CONST 2664
#define DESIGNOBJ_go_to_nav_CONST 2665
#define DESIGNOBJ_go_to_setup_CONST 2666
#define DESIGNOBJ_go_to_car_CONST 2667
#define DESIGNOBJ_media_CONST 2668
#define DESIGNOBJ_go_to_radio_CONST 2669
#define DESIGNOBJ_go_to_tv_CONST 2670
#define DESIGNOBJ_go_to_hard_drive_CONST 2671
#define DESIGNOBJ_go_to_cddvd_CONST 2672
#define DESIGNOBJ_computing_CONST 2674
#define DESIGNOBJ_go_to_internet_CONST 2675
#define DESIGNOBJ_go_to_email_CONST 2676
#define DESIGNOBJ_go_to_agenda_CONST 2677
#define DESIGNOBJ_go_to_others_CONST 2678
#define DESIGNOBJ_main_CONST 2680
#define DESIGNOBJ_currently_playing_CONST 2681
#define DESIGNOBJ_control_CONST 2682
#define DESIGNOBJ_go_to_computing_CONST 2683
#define DESIGNOBJ_leftupoff_CONST 2684
#define DESIGNOBJ_go_to_home_CONST 2685
#define DESIGNOBJ_go_to_carsetup_CONST 2686
#define DESIGNOBJ_radio_CONST 2687
#define DESIGNOBJ_tv_CONST 2688
#define DESIGNOBJ_cd_CONST 2689
#define DESIGNOBJ_hard_drive_CONST 2690
#define DESIGNOBJ_go_to_memory_CONST 2691
#define DESIGNOBJ_go_to_radio_control_CONST 2692
#define DESIGNOBJ_go_to_sound_CONST 2693
#define DESIGNOBJ_go_to_frequency_CONST 2694
#define DESIGNOBJ_go_to_recorded_tv_CONST 2696
#define DESIGNOBJ_go_to_live_tv_CONST 2697
#define DESIGNOBJ_go_to_full_screen_CONST 2698
#define DESIGNOBJ_go_to_program_guide_CONST 2699
#define DESIGNOBJ_go_to_cd_control_CONST 2701
#define DESIGNOBJ_go_to_track_list_CONST 2702
#define DESIGNOBJ_go_to_changer_CONST 2704
#define DESIGNOBJ_go_to_recorded_dvd_CONST 2706
#define DESIGNOBJ_go_to_music_CONST 2707
#define DESIGNOBJ_go_to_playlist_CONST 2708
#define DESIGNOBJ_go_to_pictures_CONST 2709
#define DESIGNOBJ_Internet_CONST 2711
#define DESIGNOBJ_Email_CONST 2712
#define DESIGNOBJ_Agenda_CONST 2713
#define DESIGNOBJ_Other_CONST 2714
#define DESIGNOBJ_leftdownoff_CONST 2715
#define DESIGNOBJ_rightdownoff_CONST 2717
#define DESIGNOBJ_rightupoff_CONST 2718
#define DESIGNOBJ_Nav_CONST 2736
#define DESIGNOBJ_Info_CONST 2737
#define DESIGNOBJ_Car_CONST 2738
#define DESIGNOBJ_Setup_CONST 2739
#define DESIGNOBJ_Lighting_CONST 2760
#define DESIGNOBJ_Climate_CONST 2761
#define DESIGNOBJ_Security_CONST 2762
#define DESIGNOBJ_Telecom_CONST 2763
#define DESIGNOBJ_go_to_map_CONST 2764
#define DESIGNOBJ_option_1_CONST 2769
#define DESIGNOBJ_go_to_doors_CONST 2777
#define DESIGNOBJ_go_to_cameras_CONST 2778
#define DESIGNOBJ_go_to_intercom_CONST 2782
#define DESIGNOBJ_option_2_CONST 2785
#define DESIGNOBJ_option_3_CONST 2786
#define DESIGNOBJ_option_4_CONST 2787
#define DESIGNOBJ_option_5_CONST 2788
#define DESIGNOBJ_option_6_CONST 2789
#define DESIGNOBJ_onoff_CONST 2790
#define DESIGNOBJ_return_CONST 2791
#define DESIGNOBJ_left_CONST 2792
#define DESIGNOBJ_right_CONST 2793
#define DESIGNOBJ_maincontrol_CONST 2795
#define DESIGNOBJ_leftup_CONST 2796
#define DESIGNOBJ_leftdown_CONST 2797
#define DESIGNOBJ_centerup_CONST 2798
#define DESIGNOBJ_centerdown_CONST 2799
#define DESIGNOBJ_rightup_CONST 2800
#define DESIGNOBJ_rightdown_CONST 2801
#define DESIGNOBJ_rotate_CONST 2802
#define DESIGNOBJ_highlight_spot_CONST 2803
#define DESIGNOBJ_parent_CONST 2804
#define DESIGNOBJ_go_main_menu_CONST 2806
#define DESIGNOBJ_lift_CONST 2822
#define DESIGNOBJ_user_CONST 2823
#define DESIGNOBJ_row1_CONST 2824
#define DESIGNOBJ_row2_CONST 2825
#define DESIGNOBJ_row3_CONST 2826
#define DESIGNOBJ_row4_CONST 2827
#define DESIGNOBJ_comfort_CONST 2830
#define DESIGNOBJ_automatic_CONST 2831
#define DESIGNOBJ_dynamic_CONST 2832
#define DESIGNOBJ_memory_CONST 2833
#define DESIGNOBJ_row5_CONST 2838
#define DESIGNOBJ_dvd_CONST 2840
#define DESIGNOBJ_go_to_dvd_menu_CONST 2843
#define DESIGNOBJ_go_to_options_CONST 2845
#define DESIGNOBJ_cd_control_CONST 2846
#define DESIGNOBJ_next_CONST 2848
#define DESIGNOBJ_previous_CONST 2849
#define DESIGNOBJ_forward_CONST 2850
#define DESIGNOBJ_mix_CONST 2851
#define DESIGNOBJ_name_CONST 2852
#define DESIGNOBJ_rewind_CONST 2853
#define DESIGNOBJ_scan_CONST 2854
#define DESIGNOBJ_track_list_CONST 2862
#define DESIGNOBJ_changer_CONST 2863
#define DESIGNOBJ_sound_CONST 2865
#define DESIGNOBJ_spinwheel_CONST 2866
#define DESIGNOBJ_radiocontrol_CONST 2867
#define DESIGNOBJ_frequency_CONST 2868
#define DESIGNOBJ_seekdown_CONST 2871
#define DESIGNOBJ_seekup_CONST 2872
#define DESIGNOBJ_store_CONST 2873
#define DESIGNOBJ_tunedown_CONST 2874
#define DESIGNOBJ_tuneup_CONST 2875
#define DESIGNOBJ_tp_memo_CONST 2884
#define DESIGNOBJ_source_CONST 2886
#define DESIGNOBJ_navinfo_CONST 2887
#define DESIGNOBJ_route_CONST 2888
#define DESIGNOBJ_map_CONST 2893
#define DESIGNOBJ_row6_CONST 2899
#define DESIGNOBJ_white_rectangle_CONST 2900
#define DESIGNOBJ_directory_CONST 2904
#define DESIGNOBJ_display_CONST 2910
#define DESIGNOBJ_settings_CONST 2911
#define DESIGNOBJ_Application_Desktop_CONST 2918
#define DESIGNOBJ_loading_CONST 2919
#define DESIGNOBJ_dvdcontrols_CONST 2920
#define DESIGNOBJ_full_screen_CONST 2921
#define DESIGNOBJ_go_to_cd_CONST 2922
#define DESIGNOBJ_go_to_dvd_CONST 2923
#define DESIGNOBJ_dvd_go_back_from_full_scree_CONST 2924
#define DESIGNOBJ_tv_go_back_from_full_screen_CONST 2925
#define DESIGNOBJ_recorded_tv_CONST 2926
#define DESIGNOBJ_program_guide_CONST 2927
#define DESIGNOBJ_options_CONST 2929
#define DESIGNOBJ_music_CONST 2934
#define DESIGNOBJ_go_back_to_nav_CONST 2937
#define DESIGNOBJ_File_list_CONST 2938
#define DESIGNOBJ_power_off_tv_CONST 2939
#define DESIGNOBJ_step_backward_CONST 2941
#define DESIGNOBJ_pause_CONST 2942
#define DESIGNOBJ_play_CONST 2943
#define DESIGNOBJ_stop_CONST 2944
#define DESIGNOBJ_step_forward_CONST 2945
#define DESIGNOBJ_systems_CONST 2947
#define DESIGNOBJ_calendar_CONST 2948
#define DESIGNOBJ_contacts_CONST 2949
#define DESIGNOBJ_todo_CONST 2950
#define DESIGNOBJ_read_CONST 2955
#define DESIGNOBJ_write_CONST 2956
#define DESIGNOBJ_send_CONST 2957
#define DESIGNOBJ_program_list_CONST 2958
#define DESIGNOBJ_documents_CONST 2959
#define DESIGNOBJ_install_remove_CONST 2960
#define DESIGNOBJ_list_CONST 2961
#define DESIGNOBJ_cameras_CONST 2967
#define DESIGNOBJ_doors_CONST 2968
#define DESIGNOBJ_make_a_call_CONST 2971
#define DESIGNOBJ_intercom_CONST 2972
#define DESIGNOBJ_Scroll_Grid_Down_CONST 2975
#define DESIGNOBJ_Exit_Full_Screen_CONST 2976
#define DESIGNOBJ_CD_Tracks_CONST 2977
#define DESIGNOBJ_DummyText_CONST 2978
#define DESIGNOBJ_save_dvd_CONST 2979
#define DESIGNOBJ_fast_rewind_CONST 2980
#define DESIGNOBJ_fast_forward_CONST 2981
#define DESIGNOBJ_save_CONST 2982
#define DESIGNOBJ_video_CONST 2984
#define DESIGNOBJ_video_hard_drive_CONST 2987
#define DESIGNOBJ_go_to_queue_CONST 2989
#define DESIGNOBJ_go_to_control_CONST 2990
#define DESIGNOBJ_audio_hard_drive_CONST 2992
#define DESIGNOBJ_parent_level_2_CONST 2993
#define DESIGNOBJ_queue_CONST 2994
#define DESIGNOBJ_actual_playlist_CONST 2995
#define DESIGNOBJ_pictures_CONST 2996
#define DESIGNOBJ_txt_previous_CONST 2997
#define DESIGNOBJ_txt_fast_forward_CONST 2998
#define DESIGNOBJ_txt_step_backward_CONST 2999
#define DESIGNOBJ_txt_pause_CONST 3000
#define DESIGNOBJ_txt_play_CONST 3001
#define DESIGNOBJ_txt_stop_CONST 3002
#define DESIGNOBJ_txt_step_forward_CONST 3003
#define DESIGNOBJ_txt_fast_rewind_CONST 3004
#define DESIGNOBJ_txt_next_CONST 3005
#define DESIGNOBJ_txt_save_CONST 3006
#define DESIGNOBJ_go_back_CONST 3007
#define DESIGNOBJ_go_to_dvd_control_CONST 3009
#define DESIGNOBJ_row1_on_CONST 3015
#define DESIGNOBJ_row2_on_CONST 3016
#define DESIGNOBJ_row_CONST 3017
#define DESIGNOBJ_Mozilla_favorites_CONST 3018
#define DESIGNOBJ_go_to_remote_media_CONST 3021
#define DESIGNOBJ_dial_CONST 3022
#define DESIGNOBJ_up_CONST 3025
#define DESIGNOBJ_down_CONST 3026
#define DESIGNOBJ_enter_CONST 3027
#define DESIGNOBJ_subtitles_CONST 3028
#define DESIGNOBJ_angles_CONST 3029
#define DESIGNOBJ_audio_tracks_CONST 3030
#define DESIGNOBJ_go_to_subtitles_CONST 3031
#define DESIGNOBJ_go_to_angles_CONST 3032
#define DESIGNOBJ_go_to_audio_tracks_CONST 3033
#define DESIGNOBJ_navigation_CONST 3034
#define DESIGNOBJ_go_to_navigation_tv_CONST 3035
#define DESIGNOBJ_surfing_CONST 3036
#define DESIGNOBJ_go_to_pluto_tv_CONST 3037
#define DESIGNOBJ_go_to_egp_CONST 3038
#define DESIGNOBJ_epg_CONST 3039
#define DESIGNOBJ_go_to_surfing_CONST 3040
#define DESIGNOBJ_bookmarks_CONST 3042
#define DESIGNOBJ_manual_CONST 3043
#define DESIGNOBJ_internet_controls_CONST 3044
#define DESIGNOBJ_back_CONST 3045
#define DESIGNOBJ_reload_CONST 3047
#define DESIGNOBJ_scroll_up_down_CONST 3048
#define DESIGNOBJ_scroll_right_left_CONST 3049
#define DESIGNOBJ_lights_CONST 3053
#define DESIGNOBJ_climate_CONST 3054
#define DESIGNOBJ_security_CONST 3055
#define DESIGNOBJ_telecom_CONST 3056
#define DESIGNOBJ_new_playlist_CONST 3065
#define DESIGNOBJ_txt_back_CONST 3070
#define DESIGNOBJ_txt_reload_CONST 3071
#define DESIGNOBJ_txt_scroll_updown_CONST 3073
#define DESIGNOBJ_txt_scroll_left_right_CONST 3074
#define DESIGNOBJ_cover_art_CONST 3075
#define DESIGNOBJ_row3_on_CONST 3076
#define DESIGNOBJ_row4_on_CONST 3077
#define DESIGNOBJ_row5_on_CONST 3078
#define DESIGNOBJ_row6_on_CONST 3079
#define DESIGNOBJ_New_phone_detected_CONST 3093
#define DESIGNOBJ_Make_mobile_orbiter_CONST 3094
#define DESIGNOBJ_Ignore_it_CONST 3095
#define DESIGNOBJ_dvd_menu_CONST 3096
#define DESIGNOBJ_File_List_Media_Type_CONST 3100
#define DESIGNOBJ_Broadcast_Video_CONST 3102
#define DESIGNOBJ_filelist_CONST 3103
#define DESIGNOBJ_radio_control_new_graphics_CONST 3104
#define DESIGNOBJ_cd_control_new_graphics_CONST 3105
#define DESIGNOBJ_round_dial_CONST 3106
#define DESIGNOBJ_go_to_audio_hard_drive_CONST 3122
#define DESIGNOBJ_stop_media_CONST 3123
#define DESIGNOBJ_track_up_CONST 3126
#define DESIGNOBJ_Track_Down_CONST 3127
#define DESIGNOBJ_go_to_new_phone_CONST 3130
#define DESIGNOBJ_EPG_Grid_CONST 3131
#define DESIGNOBJ_go_to_remote_control_CONST 3132
#define DESIGNOBJ_audi_logo_CONST 3133
#define DESIGNOBJ_Sample_TV_CONST 3135
#define DESIGNOBJ_live_tv_CONST 3136
#define DESIGNOBJ_short_row2_CONST 3137
#define DESIGNOBJ_short_row3_CONST 3138
#define DESIGNOBJ_channel_info_CONST 3139

#define DESIGNOBJ_TABLE "DesignObj"
#define DESIGNOBJ_PK_DESIGNOBJ_FIELD "PK_DesignObj"
#define DESIGNOBJ_PK_DESIGNOBJ_TABLE_FIELD "DesignObj.PK_DesignObj"
#define DESIGNOBJ_DESCRIPTION_FIELD "Description"
#define DESIGNOBJ_DESCRIPTION_TABLE_FIELD "DesignObj.Description"
#define DESIGNOBJ_DEFINE_FIELD "Define"
#define DESIGNOBJ_DEFINE_TABLE_FIELD "DesignObj.Define"
#define DESIGNOBJ_FK_DESIGNOBJTYPE_FIELD "FK_DesignObjType"
#define DESIGNOBJ_FK_DESIGNOBJTYPE_TABLE_FIELD "DesignObj.FK_DesignObjType"
#define DESIGNOBJ_FK_DESIGNOBJCATEGORY_FIELD "FK_DesignObjCategory"
#define DESIGNOBJ_FK_DESIGNOBJCATEGORY_TABLE_FIELD "DesignObj.FK_DesignObjCategory"
#define DESIGNOBJ_FK_DESIGNOBJ_INCLUDEIFOTHERINCLUDED_FIELD "FK_DesignObj_IncludeIfOtherIncluded"
#define DESIGNOBJ_FK_DESIGNOBJ_INCLUDEIFOTHERINCLUDED_TABLE_FIELD "DesignObj.FK_DesignObj_IncludeIfOtherIncluded"
#define DESIGNOBJ_PRIORITY_FIELD "Priority"
#define DESIGNOBJ_PRIORITY_TABLE_FIELD "DesignObj.Priority"
#define DESIGNOBJ_CANTGOBACK_FIELD "CantGoBack"
#define DESIGNOBJ_CANTGOBACK_TABLE_FIELD "DesignObj.CantGoBack"
#define DESIGNOBJ_COMMANDSPROCESSEDATSERVER_FIELD "CommandsProcessedAtServer"
#define DESIGNOBJ_COMMANDSPROCESSEDATSERVER_TABLE_FIELD "DesignObj.CommandsProcessedAtServer"
#define DESIGNOBJ_TIMEOUTSECONDS_FIELD "TimeoutSeconds"
#define DESIGNOBJ_TIMEOUTSECONDS_TABLE_FIELD "DesignObj.TimeoutSeconds"
#define DESIGNOBJ_ANIMATE_FIELD "Animate"
#define DESIGNOBJ_ANIMATE_TABLE_FIELD "DesignObj.Animate"
#define DESIGNOBJ_FK_STABILITYSTATUS_FIELD "FK_StabilityStatus"
#define DESIGNOBJ_FK_STABILITYSTATUS_TABLE_FIELD "DesignObj.FK_StabilityStatus"
#define DESIGNOBJ_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define DESIGNOBJ_MODIFICATION_RECORDINFO_TABLE_FIELD "DesignObj.Modification_RecordInfo"
#define DESIGNOBJ_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define DESIGNOBJ_ISNEW_RECORDINFO_TABLE_FIELD "DesignObj.IsNew_RecordInfo"
#define DESIGNOBJ_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define DESIGNOBJ_ISDELETED_RECORDINFO_TABLE_FIELD "DesignObj.IsDeleted_RecordInfo"
#define DESIGNOBJ_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define DESIGNOBJ_FK_USERS_RECORDINFO_TABLE_FIELD "DesignObj.FK_Users_RecordInfo"


#endif

