#ifndef __Define_DeviceCategory_Event_H__
#define __Define_DeviceCategory_Event_H__


#define DEVICECATEGORY_EVENT_TABLE "DeviceCategory_Event"
#define DEVICECATEGORY_EVENT_FK_DEVICECATEGORY_FIELD "FK_DeviceCategory"
#define DEVICECATEGORY_EVENT_FK_DEVICECATEGORY_TABLE_FIELD "DeviceCategory_Event.FK_DeviceCategory"
#define DEVICECATEGORY_EVENT_FK_EVENT_FIELD "FK_Event"
#define DEVICECATEGORY_EVENT_FK_EVENT_TABLE_FIELD "DeviceCategory_Event.FK_Event"
#define DEVICECATEGORY_EVENT_PSC_ID_FIELD "psc_id"
#define DEVICECATEGORY_EVENT_PSC_ID_TABLE_FIELD "DeviceCategory_Event.psc_id"
#define DEVICECATEGORY_EVENT_PSC_BATCH_FIELD "psc_batch"
#define DEVICECATEGORY_EVENT_PSC_BATCH_TABLE_FIELD "DeviceCategory_Event.psc_batch"
#define DEVICECATEGORY_EVENT_PSC_USER_FIELD "psc_user"
#define DEVICECATEGORY_EVENT_PSC_USER_TABLE_FIELD "DeviceCategory_Event.psc_user"
#define DEVICECATEGORY_EVENT_PSC_FROZEN_FIELD "psc_frozen"
#define DEVICECATEGORY_EVENT_PSC_FROZEN_TABLE_FIELD "DeviceCategory_Event.psc_frozen"
#define DEVICECATEGORY_EVENT_PSC_MOD_FIELD "psc_mod"
#define DEVICECATEGORY_EVENT_PSC_MOD_TABLE_FIELD "DeviceCategory_Event.psc_mod"


#endif

