#ifndef __Define_Text_LS_AltVersions_H__
#define __Define_Text_LS_AltVersions_H__


#define TEXT_LS_ALTVERSIONS_TABLE "Text_LS_AltVersions"
#define TEXT_LS_ALTVERSIONS_FK_TEXT_FIELD "FK_Text"
#define TEXT_LS_ALTVERSIONS_FK_TEXT_TABLE_FIELD "Text_LS_AltVersions.FK_Text"
#define TEXT_LS_ALTVERSIONS_FK_LANGUAGE_FIELD "FK_Language"
#define TEXT_LS_ALTVERSIONS_FK_LANGUAGE_TABLE_FIELD "Text_LS_AltVersions.FK_Language"
#define TEXT_LS_ALTVERSIONS_VERSION_FIELD "Version"
#define TEXT_LS_ALTVERSIONS_VERSION_TABLE_FIELD "Text_LS_AltVersions.Version"
#define TEXT_LS_ALTVERSIONS_DESCRIPTION_FIELD "Description"
#define TEXT_LS_ALTVERSIONS_DESCRIPTION_TABLE_FIELD "Text_LS_AltVersions.Description"
#define TEXT_LS_ALTVERSIONS_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define TEXT_LS_ALTVERSIONS_MODIFICATION_RECORDINFO_TABLE_FIELD "Text_LS_AltVersions.Modification_RecordInfo"
#define TEXT_LS_ALTVERSIONS_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define TEXT_LS_ALTVERSIONS_ISNEW_RECORDINFO_TABLE_FIELD "Text_LS_AltVersions.IsNew_RecordInfo"
#define TEXT_LS_ALTVERSIONS_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define TEXT_LS_ALTVERSIONS_ISDELETED_RECORDINFO_TABLE_FIELD "Text_LS_AltVersions.IsDeleted_RecordInfo"
#define TEXT_LS_ALTVERSIONS_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define TEXT_LS_ALTVERSIONS_FK_USERS_RECORDINFO_TABLE_FIELD "Text_LS_AltVersions.FK_Users_RecordInfo"


#endif

