#ifndef __Define_Package_Source_Compat_H__
#define __Define_Package_Source_Compat_H__


#define PACKAGE_SOURCE_COMPAT_TABLE "Package_Source_Compat"
#define PACKAGE_SOURCE_COMPAT_PK_PACKAGE_SOURCE_COMPAT_FIELD "PK_Package_Source_Compat"
#define PACKAGE_SOURCE_COMPAT_PK_PACKAGE_SOURCE_COMPAT_TABLE_FIELD "Package_Source_Compat.PK_Package_Source_Compat"
#define PACKAGE_SOURCE_COMPAT_FK_PACKAGE_SOURCE_FIELD "FK_Package_Source"
#define PACKAGE_SOURCE_COMPAT_FK_PACKAGE_SOURCE_TABLE_FIELD "Package_Source_Compat.FK_Package_Source"
#define PACKAGE_SOURCE_COMPAT_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define PACKAGE_SOURCE_COMPAT_FK_OPERATINGSYSTEM_TABLE_FIELD "Package_Source_Compat.FK_OperatingSystem"
#define PACKAGE_SOURCE_COMPAT_FK_DISTRO_FIELD "FK_Distro"
#define PACKAGE_SOURCE_COMPAT_FK_DISTRO_TABLE_FIELD "Package_Source_Compat.FK_Distro"
#define PACKAGE_SOURCE_COMPAT_MUSTBUILDFROMSOURCE_FIELD "MustBuildFromSource"
#define PACKAGE_SOURCE_COMPAT_MUSTBUILDFROMSOURCE_TABLE_FIELD "Package_Source_Compat.MustBuildFromSource"
#define PACKAGE_SOURCE_COMPAT_COMMENTS_FIELD "Comments"
#define PACKAGE_SOURCE_COMPAT_COMMENTS_TABLE_FIELD "Package_Source_Compat.Comments"
#define PACKAGE_SOURCE_COMPAT_PSC_ID_FIELD "psc_id"
#define PACKAGE_SOURCE_COMPAT_PSC_ID_TABLE_FIELD "Package_Source_Compat.psc_id"
#define PACKAGE_SOURCE_COMPAT_PSC_BATCH_FIELD "psc_batch"
#define PACKAGE_SOURCE_COMPAT_PSC_BATCH_TABLE_FIELD "Package_Source_Compat.psc_batch"
#define PACKAGE_SOURCE_COMPAT_PSC_USER_FIELD "psc_user"
#define PACKAGE_SOURCE_COMPAT_PSC_USER_TABLE_FIELD "Package_Source_Compat.psc_user"
#define PACKAGE_SOURCE_COMPAT_PSC_FROZEN_FIELD "psc_frozen"
#define PACKAGE_SOURCE_COMPAT_PSC_FROZEN_TABLE_FIELD "Package_Source_Compat.psc_frozen"
#define PACKAGE_SOURCE_COMPAT_PSC_MOD_FIELD "psc_mod"
#define PACKAGE_SOURCE_COMPAT_PSC_MOD_TABLE_FIELD "Package_Source_Compat.psc_mod"


#endif

