#ifndef __Define_CriteriaParm_H__
#define __Define_CriteriaParm_H__


#define CRITERIAPARM_TABLE "CriteriaParm"
#define CRITERIAPARM_PK_CRITERIAPARM_FIELD "PK_CriteriaParm"
#define CRITERIAPARM_PK_CRITERIAPARM_TABLE_FIELD "CriteriaParm.PK_CriteriaParm"
#define CRITERIAPARM_FK_CRITERIAPARMNESTING_FIELD "FK_CriteriaParmNesting"
#define CRITERIAPARM_FK_CRITERIAPARMNESTING_TABLE_FIELD "CriteriaParm.FK_CriteriaParmNesting"
#define CRITERIAPARM_FK_CRITERIAPARMLIST_FIELD "FK_CriteriaParmList"
#define CRITERIAPARM_FK_CRITERIAPARMLIST_TABLE_FIELD "CriteriaParm.FK_CriteriaParmList"
#define CRITERIAPARM_OPERATOR_FIELD "Operator"
#define CRITERIAPARM_OPERATOR_TABLE_FIELD "CriteriaParm.Operator"
#define CRITERIAPARM_VALUE_FIELD "Value"
#define CRITERIAPARM_VALUE_TABLE_FIELD "CriteriaParm.Value"
#define CRITERIAPARM_FK_CANNEDEVENTS_CRITERIAPARMLIST_FIELD "FK_CannedEvents_CriteriaParmList"
#define CRITERIAPARM_FK_CANNEDEVENTS_CRITERIAPARMLIST_TABLE_FIELD "CriteriaParm.FK_CannedEvents_CriteriaParmList"
#define CRITERIAPARM_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define CRITERIAPARM_MODIFICATION_RECORDINFO_TABLE_FIELD "CriteriaParm.Modification_RecordInfo"
#define CRITERIAPARM_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define CRITERIAPARM_ISNEW_RECORDINFO_TABLE_FIELD "CriteriaParm.IsNew_RecordInfo"
#define CRITERIAPARM_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define CRITERIAPARM_ISDELETED_RECORDINFO_TABLE_FIELD "CriteriaParm.IsDeleted_RecordInfo"
#define CRITERIAPARM_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define CRITERIAPARM_FK_USERS_RECORDINFO_TABLE_FIELD "CriteriaParm.FK_Users_RecordInfo"


#endif

