#ifndef __Define_Package_Directory_File_H__
#define __Define_Package_Directory_File_H__


#define PACKAGE_DIRECTORY_FILE_TABLE "Package_Directory_File"
#define PACKAGE_DIRECTORY_FILE_PK_PACKAGE_DIRECTORY_FILE_FIELD "PK_Package_Directory_File"
#define PACKAGE_DIRECTORY_FILE_PK_PACKAGE_DIRECTORY_FILE_TABLE_FIELD "Package_Directory_File.PK_Package_Directory_File"
#define PACKAGE_DIRECTORY_FILE_FK_PACKAGE_DIRECTORY_FIELD "FK_Package_Directory"
#define PACKAGE_DIRECTORY_FILE_FK_PACKAGE_DIRECTORY_TABLE_FIELD "Package_Directory_File.FK_Package_Directory"
#define PACKAGE_DIRECTORY_FILE_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define PACKAGE_DIRECTORY_FILE_FK_OPERATINGSYSTEM_TABLE_FIELD "Package_Directory_File.FK_OperatingSystem"
#define PACKAGE_DIRECTORY_FILE_FK_DISTRO_FIELD "FK_Distro"
#define PACKAGE_DIRECTORY_FILE_FK_DISTRO_TABLE_FIELD "Package_Directory_File.FK_Distro"
#define PACKAGE_DIRECTORY_FILE_FILE_FIELD "File"
#define PACKAGE_DIRECTORY_FILE_FILE_TABLE_FIELD "Package_Directory_File.File"
#define PACKAGE_DIRECTORY_FILE_SEARCH_FIELD "Search"
#define PACKAGE_DIRECTORY_FILE_SEARCH_TABLE_FIELD "Package_Directory_File.Search"
#define PACKAGE_DIRECTORY_FILE_MAKECOMMAND_FIELD "MakeCommand"
#define PACKAGE_DIRECTORY_FILE_MAKECOMMAND_TABLE_FIELD "Package_Directory_File.MakeCommand"


#endif

