#ifndef __Define_Device_H__
#define __Define_Device_H__


#define DEVICE_TABLE "Device"
#define DEVICE_PK_DEVICE_FIELD "PK_Device"
#define DEVICE_PK_DEVICE_TABLE_FIELD "Device.PK_Device"
#define DEVICE_DISABLED_FIELD "Disabled"
#define DEVICE_DISABLED_TABLE_FIELD "Device.Disabled"
#define DEVICE_FK_ROOM_FIELD "FK_Room"
#define DEVICE_FK_ROOM_TABLE_FIELD "Device.FK_Room"
#define DEVICE_FK_INSTALLATION_FIELD "FK_Installation"
#define DEVICE_FK_INSTALLATION_TABLE_FIELD "Device.FK_Installation"
#define DEVICE_FK_DESIGNOBJ_FIELD "FK_DesignObj"
#define DEVICE_FK_DESIGNOBJ_TABLE_FIELD "Device.FK_DesignObj"
#define DEVICE_DESCRIPTION_FIELD "Description"
#define DEVICE_DESCRIPTION_TABLE_FIELD "Device.Description"
#define DEVICE_FK_DEVICETEMPLATE_FIELD "FK_DeviceTemplate"
#define DEVICE_FK_DEVICETEMPLATE_TABLE_FIELD "Device.FK_DeviceTemplate"
#define DEVICE_FK_DEVICE_AUDIO_FIELD "FK_Device_Audio"
#define DEVICE_FK_DEVICE_AUDIO_TABLE_FIELD "Device.FK_Device_Audio"
#define DEVICE_FK_INPUT_AUDIO_FIELD "FK_Input_Audio"
#define DEVICE_FK_INPUT_AUDIO_TABLE_FIELD "Device.FK_Input_Audio"
#define DEVICE_FK_DEVICE_VIDEO_FIELD "FK_Device_Video"
#define DEVICE_FK_DEVICE_VIDEO_TABLE_FIELD "Device.FK_Device_Video"
#define DEVICE_FK_INPUT_VIDEO_FIELD "FK_Input_Video"
#define DEVICE_FK_INPUT_VIDEO_TABLE_FIELD "Device.FK_Input_Video"
#define DEVICE_FK_DEVICE_CONTROLLEDVIA_FIELD "FK_Device_ControlledVia"
#define DEVICE_FK_DEVICE_CONTROLLEDVIA_TABLE_FIELD "Device.FK_Device_ControlledVia"
#define DEVICE_FK_INTERFACE_FIELD "FK_Interface"
#define DEVICE_FK_INTERFACE_TABLE_FIELD "Device.FK_Interface"
#define DEVICE_IPADDRESS_FIELD "IPaddress"
#define DEVICE_IPADDRESS_TABLE_FIELD "Device.IPaddress"
#define DEVICE_MACADDRESS_FIELD "MACaddress"
#define DEVICE_MACADDRESS_TABLE_FIELD "Device.MACaddress"
#define DEVICE_IGNOREONOFF_FIELD "IgnoreOnOff"
#define DEVICE_IGNOREONOFF_TABLE_FIELD "Device.IgnoreOnOff"
#define DEVICE_FK_DEVICE_SLAVETO_FIELD "FK_Device_SlaveTo"
#define DEVICE_FK_DEVICE_SLAVETO_TABLE_FIELD "Device.FK_Device_SlaveTo"
#define DEVICE_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define DEVICE_MODIFICATION_RECORDINFO_TABLE_FIELD "Device.Modification_RecordInfo"
#define DEVICE_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define DEVICE_ISNEW_RECORDINFO_TABLE_FIELD "Device.IsNew_RecordInfo"
#define DEVICE_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define DEVICE_ISDELETED_RECORDINFO_TABLE_FIELD "Device.IsDeleted_RecordInfo"
#define DEVICE_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define DEVICE_FK_USERS_RECORDINFO_TABLE_FIELD "Device.FK_Users_RecordInfo"


#endif

