#ifndef __Define_ParameterType_H__
#define __Define_ParameterType_H__

#define PARAMETERTYPE_string_CONST 1
#define PARAMETERTYPE_int_CONST 2
#define PARAMETERTYPE_bool_CONST 3
#define PARAMETERTYPE_Special_CONST 4
#define PARAMETERTYPE_Data_CONST 5
#define PARAMETERTYPE_PlutoColor_CONST 6
#define PARAMETERTYPE_PlutoDate_CONST 7

#define PARAMETERTYPE_TABLE "ParameterType"
#define PARAMETERTYPE_PK_PARAMETERTYPE_FIELD "PK_ParameterType"
#define PARAMETERTYPE_PK_PARAMETERTYPE_TABLE_FIELD "ParameterType.PK_ParameterType"
#define PARAMETERTYPE_DESCRIPTION_FIELD "Description"
#define PARAMETERTYPE_DESCRIPTION_TABLE_FIELD "ParameterType.Description"
#define PARAMETERTYPE_DEFINE_FIELD "Define"
#define PARAMETERTYPE_DEFINE_TABLE_FIELD "ParameterType.Define"
#define PARAMETERTYPE_CPPTYPE_FIELD "CPPType"
#define PARAMETERTYPE_CPPTYPE_TABLE_FIELD "ParameterType.CPPType"
#define PARAMETERTYPE_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define PARAMETERTYPE_MODIFICATION_RECORDINFO_TABLE_FIELD "ParameterType.Modification_RecordInfo"
#define PARAMETERTYPE_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define PARAMETERTYPE_ISNEW_RECORDINFO_TABLE_FIELD "ParameterType.IsNew_RecordInfo"
#define PARAMETERTYPE_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define PARAMETERTYPE_ISDELETED_RECORDINFO_TABLE_FIELD "ParameterType.IsDeleted_RecordInfo"
#define PARAMETERTYPE_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define PARAMETERTYPE_FK_USERS_RECORDINFO_TABLE_FIELD "ParameterType.FK_Users_RecordInfo"


#endif

