#ifndef __Define_RepositorySource_H__
#define __Define_RepositorySource_H__

#define REPOSITORYSOURCE_Debian_CONST 1
#define REPOSITORYSOURCE_Pluto_Debian_CONST 2
#define REPOSITORYSOURCE_CDDB_direct_link_CONST 3
#define REPOSITORYSOURCE_Pluto_FTP_CONST 4
#define REPOSITORYSOURCE_MythTV_CONST 5
#define REPOSITORYSOURCE_Nerimnet_CONST 6
#define REPOSITORYSOURCE_Pluto_CVS_CONST 7
#define REPOSITORYSOURCE_Pluto_SVN_CONST 8
#define REPOSITORYSOURCE_Pluto_Debian_Sarge_Archives_CONST 9
#define REPOSITORYSOURCE_Pluto_Windows_Archives_CONST 10
#define REPOSITORYSOURCE_Pluto_Source_Archives_CONST 11
#define REPOSITORYSOURCE_SourceForge_CVS_CONST 12
#define REPOSITORYSOURCE_SourceForge_Archives_CONST 13
#define REPOSITORYSOURCE_Installable_Packages_CONST 14

#define REPOSITORYSOURCE_TABLE "RepositorySource"
#define REPOSITORYSOURCE_PK_REPOSITORYSOURCE_FIELD "PK_RepositorySource"
#define REPOSITORYSOURCE_PK_REPOSITORYSOURCE_TABLE_FIELD "RepositorySource.PK_RepositorySource"
#define REPOSITORYSOURCE_FK_OPERATINGSYSTEM_FIELD "FK_OperatingSystem"
#define REPOSITORYSOURCE_FK_OPERATINGSYSTEM_TABLE_FIELD "RepositorySource.FK_OperatingSystem"
#define REPOSITORYSOURCE_FK_DISTRO_FIELD "FK_Distro"
#define REPOSITORYSOURCE_FK_DISTRO_TABLE_FIELD "RepositorySource.FK_Distro"
#define REPOSITORYSOURCE_FK_REPOSITORYTYPE_FIELD "FK_RepositoryType"
#define REPOSITORYSOURCE_FK_REPOSITORYTYPE_TABLE_FIELD "RepositorySource.FK_RepositoryType"
#define REPOSITORYSOURCE_DESCRIPTION_FIELD "Description"
#define REPOSITORYSOURCE_DESCRIPTION_TABLE_FIELD "RepositorySource.Description"
#define REPOSITORYSOURCE_DEFINE_FIELD "Define"
#define REPOSITORYSOURCE_DEFINE_TABLE_FIELD "RepositorySource.Define"
#define REPOSITORYSOURCE_INSTRUCTIONS_FIELD "Instructions"
#define REPOSITORYSOURCE_INSTRUCTIONS_TABLE_FIELD "RepositorySource.Instructions"
#define REPOSITORYSOURCE_PSC_ID_FIELD "psc_id"
#define REPOSITORYSOURCE_PSC_ID_TABLE_FIELD "RepositorySource.psc_id"
#define REPOSITORYSOURCE_PSC_BATCH_FIELD "psc_batch"
#define REPOSITORYSOURCE_PSC_BATCH_TABLE_FIELD "RepositorySource.psc_batch"
#define REPOSITORYSOURCE_PSC_USER_FIELD "psc_user"
#define REPOSITORYSOURCE_PSC_USER_TABLE_FIELD "RepositorySource.psc_user"
#define REPOSITORYSOURCE_PSC_FROZEN_FIELD "psc_frozen"
#define REPOSITORYSOURCE_PSC_FROZEN_TABLE_FIELD "RepositorySource.psc_frozen"
#define REPOSITORYSOURCE_PSC_MOD_FIELD "psc_mod"
#define REPOSITORYSOURCE_PSC_MOD_TABLE_FIELD "RepositorySource.psc_mod"


#endif

