#ifndef __Define_Orbiter_Users_PasswordReq_H__
#define __Define_Orbiter_Users_PasswordReq_H__


#define ORBITER_USERS_PASSWORDREQ_TABLE "Orbiter_Users_PasswordReq"
#define ORBITER_USERS_PASSWORDREQ_FK_ORBITER_FIELD "FK_Orbiter"
#define ORBITER_USERS_PASSWORDREQ_FK_ORBITER_TABLE_FIELD "Orbiter_Users_PasswordReq.FK_Orbiter"
#define ORBITER_USERS_PASSWORDREQ_FK_USERS_FIELD "FK_Users"
#define ORBITER_USERS_PASSWORDREQ_FK_USERS_TABLE_FIELD "Orbiter_Users_PasswordReq.FK_Users"
#define ORBITER_USERS_PASSWORDREQ_PSC_ID_FIELD "psc_id"
#define ORBITER_USERS_PASSWORDREQ_PSC_ID_TABLE_FIELD "Orbiter_Users_PasswordReq.psc_id"
#define ORBITER_USERS_PASSWORDREQ_PSC_BATCH_FIELD "psc_batch"
#define ORBITER_USERS_PASSWORDREQ_PSC_BATCH_TABLE_FIELD "Orbiter_Users_PasswordReq.psc_batch"
#define ORBITER_USERS_PASSWORDREQ_PSC_USER_FIELD "psc_user"
#define ORBITER_USERS_PASSWORDREQ_PSC_USER_TABLE_FIELD "Orbiter_Users_PasswordReq.psc_user"
#define ORBITER_USERS_PASSWORDREQ_PSC_FROZEN_FIELD "psc_frozen"
#define ORBITER_USERS_PASSWORDREQ_PSC_FROZEN_TABLE_FIELD "Orbiter_Users_PasswordReq.psc_frozen"
#define ORBITER_USERS_PASSWORDREQ_PSC_MOD_FIELD "psc_mod"
#define ORBITER_USERS_PASSWORDREQ_PSC_MOD_TABLE_FIELD "Orbiter_Users_PasswordReq.psc_mod"


#endif

