#ifndef __Define_Orbiter_H__
#define __Define_Orbiter_H__


#define ORBITER_TABLE "Orbiter"
#define ORBITER_PK_ORBITER_FIELD "PK_Orbiter"
#define ORBITER_PK_ORBITER_TABLE_FIELD "Orbiter.PK_Orbiter"
#define ORBITER_FK_DESIGNOBJ_MAINMENU_FIELD "FK_DesignObj_MainMenu"
#define ORBITER_FK_DESIGNOBJ_MAINMENU_TABLE_FIELD "Orbiter.FK_DesignObj_MainMenu"
#define ORBITER_FK_DESIGNOBJ_SLEEPING_FIELD "FK_DesignObj_Sleeping"
#define ORBITER_FK_DESIGNOBJ_SLEEPING_TABLE_FIELD "Orbiter.FK_DesignObj_Sleeping"
#define ORBITER_FK_DESIGNOBJ_SCREENSAVER_FIELD "FK_DesignObj_ScreenSaver"
#define ORBITER_FK_DESIGNOBJ_SCREENSAVER_TABLE_FIELD "Orbiter.FK_DesignObj_ScreenSaver"
#define ORBITER_FK_ENTERTAINAREA_FIELD "FK_EntertainArea"
#define ORBITER_FK_ENTERTAINAREA_TABLE_FIELD "Orbiter.FK_EntertainArea"
#define ORBITER_FK_SYSTEM_FIELD "FK_System"
#define ORBITER_FK_SYSTEM_TABLE_FIELD "Orbiter.FK_System"
#define ORBITER_FK_SKIN_FIELD "FK_Skin"
#define ORBITER_FK_SKIN_TABLE_FIELD "Orbiter.FK_Skin"
#define ORBITER_FK_SIZE_FIELD "FK_Size"
#define ORBITER_FK_SIZE_TABLE_FIELD "Orbiter.FK_Size"
#define ORBITER_FK_VERSION_FIELD "FK_Version"
#define ORBITER_FK_VERSION_TABLE_FIELD "Orbiter.FK_Version"
#define ORBITER_FK_LANGUAGE_FIELD "FK_Language"
#define ORBITER_FK_LANGUAGE_TABLE_FIELD "Orbiter.FK_Language"
#define ORBITER_NOEFFECTS_FIELD "NoEffects"
#define ORBITER_NOEFFECTS_TABLE_FIELD "Orbiter.NoEffects"
#define ORBITER_FLOORPLANINFO_FIELD "FloorplanInfo"
#define ORBITER_FLOORPLANINFO_TABLE_FIELD "Orbiter.FloorplanInfo"
#define ORBITER_MODIFICATION_LASTGEN_FIELD "Modification_LastGen"
#define ORBITER_MODIFICATION_LASTGEN_TABLE_FIELD "Orbiter.Modification_LastGen"
#define ORBITER_PSC_ID_FIELD "psc_id"
#define ORBITER_PSC_ID_TABLE_FIELD "Orbiter.psc_id"
#define ORBITER_PSC_BATCH_FIELD "psc_batch"
#define ORBITER_PSC_BATCH_TABLE_FIELD "Orbiter.psc_batch"
#define ORBITER_PSC_USER_FIELD "psc_user"
#define ORBITER_PSC_USER_TABLE_FIELD "Orbiter.psc_user"
#define ORBITER_PSC_FROZEN_FIELD "psc_frozen"
#define ORBITER_PSC_FROZEN_TABLE_FIELD "Orbiter.psc_frozen"
#define ORBITER_PSC_MOD_FIELD "psc_mod"
#define ORBITER_PSC_MOD_TABLE_FIELD "Orbiter.psc_mod"


#endif

