#ifndef __Define_DesignObjType_H__
#define __Define_DesignObjType_H__

#define DESIGNOBJTYPE_Bitmap_CONST 1
#define DESIGNOBJTYPE_Rectangle_CONST 2
#define DESIGNOBJTYPE_Array_CONST 3
#define DESIGNOBJTYPE_Broadcast_Video_CONST 4
#define DESIGNOBJTYPE_App_Desktop_CONST 5
#define DESIGNOBJTYPE_Datagrid_CONST 6
#define DESIGNOBJTYPE_Web_Browser_CONST 8
#define DESIGNOBJTYPE_Floorplan_CONST 9
#define DESIGNOBJTYPE_Pronto_File_CONST 10

#define DESIGNOBJTYPE_TABLE "DesignObjType"
#define DESIGNOBJTYPE_PK_DESIGNOBJTYPE_FIELD "PK_DesignObjType"
#define DESIGNOBJTYPE_PK_DESIGNOBJTYPE_TABLE_FIELD "DesignObjType.PK_DesignObjType"
#define DESIGNOBJTYPE_DESCRIPTION_FIELD "Description"
#define DESIGNOBJTYPE_DESCRIPTION_TABLE_FIELD "DesignObjType.Description"
#define DESIGNOBJTYPE_DEFINE_FIELD "Define"
#define DESIGNOBJTYPE_DEFINE_TABLE_FIELD "DesignObjType.Define"
#define DESIGNOBJTYPE_CANCLICK_FIELD "CanClick"
#define DESIGNOBJTYPE_CANCLICK_TABLE_FIELD "DesignObjType.CanClick"
#define DESIGNOBJTYPE_CONTAINSTEXT_FIELD "ContainsText"
#define DESIGNOBJTYPE_CONTAINSTEXT_TABLE_FIELD "DesignObjType.ContainsText"
#define DESIGNOBJTYPE_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define DESIGNOBJTYPE_MODIFICATION_RECORDINFO_TABLE_FIELD "DesignObjType.Modification_RecordInfo"
#define DESIGNOBJTYPE_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define DESIGNOBJTYPE_ISNEW_RECORDINFO_TABLE_FIELD "DesignObjType.IsNew_RecordInfo"
#define DESIGNOBJTYPE_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define DESIGNOBJTYPE_ISDELETED_RECORDINFO_TABLE_FIELD "DesignObjType.IsDeleted_RecordInfo"
#define DESIGNOBJTYPE_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define DESIGNOBJTYPE_FK_USERS_RECORDINFO_TABLE_FIELD "DesignObjType.FK_Users_RecordInfo"


#endif

