#ifndef __Define_CriteriaParmList_H__
#define __Define_CriteriaParmList_H__


#define CRITERIAPARMLIST_TABLE "CriteriaParmList"
#define CRITERIAPARMLIST_PK_CRITERIAPARMLIST_FIELD "PK_CriteriaParmList"
#define CRITERIAPARMLIST_PK_CRITERIAPARMLIST_TABLE_FIELD "CriteriaParmList.PK_CriteriaParmList"
#define CRITERIAPARMLIST_FK_PARAMETERTYPE_FIELD "FK_ParameterType"
#define CRITERIAPARMLIST_FK_PARAMETERTYPE_TABLE_FIELD "CriteriaParmList.FK_ParameterType"
#define CRITERIAPARMLIST_DESCRIPTION_FIELD "Description"
#define CRITERIAPARMLIST_DESCRIPTION_TABLE_FIELD "CriteriaParmList.Description"
#define CRITERIAPARMLIST_DEFINE_FIELD "Define"
#define CRITERIAPARMLIST_DEFINE_TABLE_FIELD "CriteriaParmList.Define"
#define CRITERIAPARMLIST_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define CRITERIAPARMLIST_MODIFICATION_RECORDINFO_TABLE_FIELD "CriteriaParmList.Modification_RecordInfo"
#define CRITERIAPARMLIST_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define CRITERIAPARMLIST_ISNEW_RECORDINFO_TABLE_FIELD "CriteriaParmList.IsNew_RecordInfo"
#define CRITERIAPARMLIST_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define CRITERIAPARMLIST_ISDELETED_RECORDINFO_TABLE_FIELD "CriteriaParmList.IsDeleted_RecordInfo"
#define CRITERIAPARMLIST_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define CRITERIAPARMLIST_FK_USERS_RECORDINFO_TABLE_FIELD "CriteriaParmList.FK_Users_RecordInfo"


#endif

