#ifndef __Define_ConfigType_Setting_H__
#define __Define_ConfigType_Setting_H__


#define CONFIGTYPE_SETTING_TABLE "ConfigType_Setting"
#define CONFIGTYPE_SETTING_PK_CONFIGTYPE_SETTING_FIELD "PK_ConfigType_Setting"
#define CONFIGTYPE_SETTING_PK_CONFIGTYPE_SETTING_TABLE_FIELD "ConfigType_Setting.PK_ConfigType_Setting"
#define CONFIGTYPE_SETTING_FK_CONFIGTYPE_FIELD "FK_ConfigType"
#define CONFIGTYPE_SETTING_FK_CONFIGTYPE_TABLE_FIELD "ConfigType_Setting.FK_ConfigType"
#define CONFIGTYPE_SETTING_DESCRIPTION_FIELD "Description"
#define CONFIGTYPE_SETTING_DESCRIPTION_TABLE_FIELD "ConfigType_Setting.Description"
#define CONFIGTYPE_SETTING_PSC_ID_FIELD "psc_id"
#define CONFIGTYPE_SETTING_PSC_ID_TABLE_FIELD "ConfigType_Setting.psc_id"
#define CONFIGTYPE_SETTING_PSC_BATCH_FIELD "psc_batch"
#define CONFIGTYPE_SETTING_PSC_BATCH_TABLE_FIELD "ConfigType_Setting.psc_batch"
#define CONFIGTYPE_SETTING_PSC_USER_FIELD "psc_user"
#define CONFIGTYPE_SETTING_PSC_USER_TABLE_FIELD "ConfigType_Setting.psc_user"
#define CONFIGTYPE_SETTING_PSC_FROZEN_FIELD "psc_frozen"
#define CONFIGTYPE_SETTING_PSC_FROZEN_TABLE_FIELD "ConfigType_Setting.psc_frozen"
#define CONFIGTYPE_SETTING_PSC_MOD_FIELD "psc_mod"
#define CONFIGTYPE_SETTING_PSC_MOD_TABLE_FIELD "ConfigType_Setting.psc_mod"


#endif

