#ifndef __Define_DesignObjType_H__
#define __Define_DesignObjType_H__

#define DESIGNOBJTYPE_Bitmap_CONST 1
#define DESIGNOBJTYPE_Rectangle_CONST 2
#define DESIGNOBJTYPE_Array_CONST 3
#define DESIGNOBJTYPE_Broadcast_Video_CONST 4
#define DESIGNOBJTYPE_App_Desktop_CONST 5
#define DESIGNOBJTYPE_Datagrid_CONST 6
#define DESIGNOBJTYPE_Web_Browser_CONST 8
#define DESIGNOBJTYPE_Floorplan_CONST 9
#define DESIGNOBJTYPE_Pronto_File_CONST 10

#define DESIGNOBJTYPE_TABLE "DesignObjType"
#define DESIGNOBJTYPE_PK_DESIGNOBJTYPE_FIELD "PK_DesignObjType"
#define DESIGNOBJTYPE_PK_DESIGNOBJTYPE_TABLE_FIELD "DesignObjType.PK_DesignObjType"
#define DESIGNOBJTYPE_DESCRIPTION_FIELD "Description"
#define DESIGNOBJTYPE_DESCRIPTION_TABLE_FIELD "DesignObjType.Description"
#define DESIGNOBJTYPE_DEFINE_FIELD "Define"
#define DESIGNOBJTYPE_DEFINE_TABLE_FIELD "DesignObjType.Define"
#define DESIGNOBJTYPE_CANCLICK_FIELD "CanClick"
#define DESIGNOBJTYPE_CANCLICK_TABLE_FIELD "DesignObjType.CanClick"
#define DESIGNOBJTYPE_CONTAINSTEXT_FIELD "ContainsText"
#define DESIGNOBJTYPE_CONTAINSTEXT_TABLE_FIELD "DesignObjType.ContainsText"
#define DESIGNOBJTYPE_PSC_ID_FIELD "psc_id"
#define DESIGNOBJTYPE_PSC_ID_TABLE_FIELD "DesignObjType.psc_id"
#define DESIGNOBJTYPE_PSC_BATCH_FIELD "psc_batch"
#define DESIGNOBJTYPE_PSC_BATCH_TABLE_FIELD "DesignObjType.psc_batch"
#define DESIGNOBJTYPE_PSC_USER_FIELD "psc_user"
#define DESIGNOBJTYPE_PSC_USER_TABLE_FIELD "DesignObjType.psc_user"
#define DESIGNOBJTYPE_PSC_FROZEN_FIELD "psc_frozen"
#define DESIGNOBJTYPE_PSC_FROZEN_TABLE_FIELD "DesignObjType.psc_frozen"
#define DESIGNOBJTYPE_PSC_MOD_FIELD "psc_mod"
#define DESIGNOBJTYPE_PSC_MOD_TABLE_FIELD "DesignObjType.psc_mod"


#endif

