#ifndef __Define_Installation_Users_H__
#define __Define_Installation_Users_H__


#define INSTALLATION_USERS_TABLE "Installation_Users"
#define INSTALLATION_USERS_FK_INSTALLATION_FIELD "FK_Installation"
#define INSTALLATION_USERS_FK_INSTALLATION_TABLE_FIELD "Installation_Users.FK_Installation"
#define INSTALLATION_USERS_FK_USERS_FIELD "FK_Users"
#define INSTALLATION_USERS_FK_USERS_TABLE_FIELD "Installation_Users.FK_Users"
#define INSTALLATION_USERS_USERCANMODIFYINSTALLATION_FIELD "userCanModifyInstallation"
#define INSTALLATION_USERS_USERCANMODIFYINSTALLATION_TABLE_FIELD "Installation_Users.userCanModifyInstallation"
#define INSTALLATION_USERS_USERCANCHANGEHOUSEMODE_FIELD "userCanChangeHouseMode"
#define INSTALLATION_USERS_USERCANCHANGEHOUSEMODE_TABLE_FIELD "Installation_Users.userCanChangeHouseMode"
#define INSTALLATION_USERS_PSC_ID_FIELD "psc_id"
#define INSTALLATION_USERS_PSC_ID_TABLE_FIELD "Installation_Users.psc_id"
#define INSTALLATION_USERS_PSC_BATCH_FIELD "psc_batch"
#define INSTALLATION_USERS_PSC_BATCH_TABLE_FIELD "Installation_Users.psc_batch"
#define INSTALLATION_USERS_PSC_USER_FIELD "psc_user"
#define INSTALLATION_USERS_PSC_USER_TABLE_FIELD "Installation_Users.psc_user"
#define INSTALLATION_USERS_PSC_FROZEN_FIELD "psc_frozen"
#define INSTALLATION_USERS_PSC_FROZEN_TABLE_FIELD "Installation_Users.psc_frozen"
#define INSTALLATION_USERS_PSC_MOD_FIELD "psc_mod"
#define INSTALLATION_USERS_PSC_MOD_TABLE_FIELD "Installation_Users.psc_mod"


#endif

