#ifndef __Define_CommandGroup_H__
#define __Define_CommandGroup_H__


#define COMMANDGROUP_TABLE "CommandGroup"
#define COMMANDGROUP_PK_COMMANDGROUP_FIELD "PK_CommandGroup"
#define COMMANDGROUP_PK_COMMANDGROUP_TABLE_FIELD "CommandGroup.PK_CommandGroup"
#define COMMANDGROUP_FK_ARRAY_FIELD "FK_Array"
#define COMMANDGROUP_FK_ARRAY_TABLE_FIELD "CommandGroup.FK_Array"
#define COMMANDGROUP_FK_INSTALLATION_FIELD "FK_Installation"
#define COMMANDGROUP_FK_INSTALLATION_TABLE_FIELD "CommandGroup.FK_Installation"
#define COMMANDGROUP_DESCRIPTION_FIELD "Description"
#define COMMANDGROUP_DESCRIPTION_TABLE_FIELD "CommandGroup.Description"
#define COMMANDGROUP_HINT_FIELD "Hint"
#define COMMANDGROUP_HINT_TABLE_FIELD "CommandGroup.Hint"
#define COMMANDGROUP_CANTURNOFF_FIELD "CanTurnOff"
#define COMMANDGROUP_CANTURNOFF_TABLE_FIELD "CommandGroup.CanTurnOff"
#define COMMANDGROUP_ALWAYSSHOW_FIELD "AlwaysShow"
#define COMMANDGROUP_ALWAYSSHOW_TABLE_FIELD "CommandGroup.AlwaysShow"
#define COMMANDGROUP_CANBEHIDDEN_FIELD "CanBeHidden"
#define COMMANDGROUP_CANBEHIDDEN_TABLE_FIELD "CommandGroup.CanBeHidden"
#define COMMANDGROUP_FK_CRITERIA_ORBITER_FIELD "FK_Criteria_Orbiter"
#define COMMANDGROUP_FK_CRITERIA_ORBITER_TABLE_FIELD "CommandGroup.FK_Criteria_Orbiter"
#define COMMANDGROUP_FK_DESIGNOBJ_FIELD "FK_DesignObj"
#define COMMANDGROUP_FK_DESIGNOBJ_TABLE_FIELD "CommandGroup.FK_DesignObj"
#define COMMANDGROUP_TEMPLATEID_FIELD "TemplateID"
#define COMMANDGROUP_TEMPLATEID_TABLE_FIELD "CommandGroup.TemplateID"
#define COMMANDGROUP_ALTID_FIELD "AltID"
#define COMMANDGROUP_ALTID_TABLE_FIELD "CommandGroup.AltID"
#define COMMANDGROUP_FK_ICON_FIELD "FK_Icon"
#define COMMANDGROUP_FK_ICON_TABLE_FIELD "CommandGroup.FK_Icon"
#define COMMANDGROUP_MODIFICATION_RECORDINFO_FIELD "Modification_RecordInfo"
#define COMMANDGROUP_MODIFICATION_RECORDINFO_TABLE_FIELD "CommandGroup.Modification_RecordInfo"
#define COMMANDGROUP_ISNEW_RECORDINFO_FIELD "IsNew_RecordInfo"
#define COMMANDGROUP_ISNEW_RECORDINFO_TABLE_FIELD "CommandGroup.IsNew_RecordInfo"
#define COMMANDGROUP_ISDELETED_RECORDINFO_FIELD "IsDeleted_RecordInfo"
#define COMMANDGROUP_ISDELETED_RECORDINFO_TABLE_FIELD "CommandGroup.IsDeleted_RecordInfo"
#define COMMANDGROUP_FK_USERS_RECORDINFO_FIELD "FK_Users_RecordInfo"
#define COMMANDGROUP_FK_USERS_RECORDINFO_TABLE_FIELD "CommandGroup.FK_Users_RecordInfo"


#endif

