#ifndef __Define_Command_H__
#define __Define_Command_H__

#define COMMAND_Capture_Keyboard_To_Variable_CONST 1
#define COMMAND_Orbiter_Beep_CONST 2
#define COMMAND_Display_OnOff_CONST 3
#define COMMAND_Go_back_CONST 4
#define COMMAND_Goto_Screen_CONST 5
#define COMMAND_Show_Object_CONST 6
#define COMMAND_Terminate_Orbiter_CONST 7
#define COMMAND_Remove_Screen_From_History_CONST 8
#define COMMAND_Scroll_Grid_CONST 9
#define COMMAND_Move_Highlight_CONST 10
#define COMMAND_Play_Sound_CONST 13
#define COMMAND_Refresh_CONST 14
#define COMMAND_Regen_Screen_CONST 15
#define COMMAND_Requires_Special_Handling_CONST 16
#define COMMAND_Seek_Data_Grid_CONST 17
#define COMMAND_Set_Graphic_To_Display_CONST 18
#define COMMAND_Set_House_Mode_CONST 19
#define COMMAND_Set_Object_Parameter_CONST 20
#define COMMAND_Set_Object_Position_CONST 21
#define COMMAND_Set_Object_Size_CONST 22
#define COMMAND_Set_Pos_Rel_To_Parent_CONST 23
#define COMMAND_Set_Size_Rel_To_Parent_CONST 24
#define COMMAND_Set_Text_CONST 25
#define COMMAND_Set_User_Mode_CONST 26
#define COMMAND_Set_Variable_CONST 27
#define COMMAND_Simulate_Keypress_CONST 28
#define COMMAND_Simulate_Mouse_Click_CONST 29
#define COMMAND_Stop_Sound_CONST 30
#define COMMAND_Store_Variables_CONST 31
#define COMMAND_Update_Object_Image_CONST 32
#define COMMAND_Start_Media_CONST 33
#define COMMAND_Request_Datagrid_Contents_CONST 34
#define COMMAND_Populate_Datagrid_CONST 35
#define COMMAND_Create_Media_CONST 36
#define COMMAND_Play_Media_CONST 37
#define COMMAND_Stop_Media_CONST 38
#define COMMAND_Pause_Media_CONST 39
#define COMMAND_Restart_Media_CONST 40
#define COMMAND_Change_Playback_Speed_CONST 41
#define COMMAND_Rewind_Playback_CONST 42
#define COMMAND_MH_Play_Media_CONST 43
#define COMMAND_MH_Stop_Media_CONST 44
#define COMMAND_Disk_Drive_Monitoring_ON_CONST 45
#define COMMAND_Disk_Drive_Monitoring_OFF_CONST 46
#define COMMAND_Reset_Disk_Drive_CONST 47
#define COMMAND_Eject_Disk_CONST 48
#define COMMAND_Start_Burn_Session_CONST 49
#define COMMAND_Start_Ripping_Session_CONST 50
#define COMMAND_Add_File_To_Burning_Session_CONST 51
#define COMMAND_Start_Burning_CONST 52
#define COMMAND_Abort_Burning_CONST 53
#define COMMAND_Mount_Disk_Image_CONST 54
#define COMMAND_Start_Ripping_DVD_CONST 55
#define COMMAND_Format_Drive_CONST 56
#define COMMAND_Close_Tray_CONST 57
#define COMMAND_Set_Current_User_CONST 58
#define COMMAND_Set_Entertainment_Area_CONST 59
#define COMMAND_Link_with_mobile_orbiter_CONST 60
#define COMMAND_Get_Signal_Strength_CONST 61
#define COMMAND_Create_Mobile_Orbiter_CONST 62
#define COMMAND_Skip_Forward_CONST 63
#define COMMAND_Skip_Back_CONST 64
#define COMMAND_Jump_Position_In_Playlist_CONST 65
#define COMMAND_Select_Object_CONST 66
#define COMMAND_Spawn_Application_CONST 67
#define COMMAND_Get_Device_Data_CONST 68
#define COMMAND_Kill_Application_CONST 69
#define COMMAND_Hide_Application_CONST 70
#define COMMAND_Request_File_CONST 71
#define COMMAND_Surrender_to_OS_CONST 72
#define COMMAND_MH_Send_Me_To_Remote_CONST 73
#define COMMAND_Bind_to_Media_Remote_CONST 74
#define COMMAND_Start_TV_CONST 75
#define COMMAND_Stop_TV_CONST 76
#define COMMAND_Set_Current_Room_CONST 77
#define COMMAND_New_Mobile_Orbiter_CONST 78
#define COMMAND_Add_Unknown_Device_CONST 79
#define COMMAND_Send_File_To_Device_CONST 80
#define COMMAND_Navigate_Next_CONST 81
#define COMMAND_Navigate_Prev_CONST 82
#define COMMAND_Select_Current_Navigable_Area_CONST 83
#define COMMAND_Get_Video_Frame_CONST 84
#define COMMAND_Rest_Highlight_CONST 85
#define COMMAND_Goto_Menu_not_used_CONST 86
#define COMMAND_Goto_Media_Menu_CONST 87

#define COMMAND_TABLE "Command"
#define COMMAND_PK_COMMAND_FIELD "PK_Command"
#define COMMAND_PK_COMMAND_TABLE_FIELD "Command.PK_Command"
#define COMMAND_DESCRIPTION_FIELD "Description"
#define COMMAND_DESCRIPTION_TABLE_FIELD "Command.Description"
#define COMMAND_DEFINE_FIELD "Define"
#define COMMAND_DEFINE_TABLE_FIELD "Command.Define"
#define COMMAND_FK_COMMANDCATEGORY_FIELD "FK_CommandCategory"
#define COMMAND_FK_COMMANDCATEGORY_TABLE_FIELD "Command.FK_CommandCategory"
#define COMMAND_AVCOMMAND_FIELD "AVCommand"
#define COMMAND_AVCOMMAND_TABLE_FIELD "Command.AVCommand"
#define COMMAND_PSC_ID_FIELD "psc_id"
#define COMMAND_PSC_ID_TABLE_FIELD "Command.psc_id"
#define COMMAND_PSC_BATCH_FIELD "psc_batch"
#define COMMAND_PSC_BATCH_TABLE_FIELD "Command.psc_batch"
#define COMMAND_PSC_USER_FIELD "psc_user"
#define COMMAND_PSC_USER_TABLE_FIELD "Command.psc_user"
#define COMMAND_PSC_FROZEN_FIELD "psc_frozen"
#define COMMAND_PSC_FROZEN_TABLE_FIELD "Command.psc_frozen"
#define COMMAND_PSC_MOD_FIELD "psc_mod"
#define COMMAND_PSC_MOD_TABLE_FIELD "Command.psc_mod"


#endif

