#ifndef __Define_StartupScript_H__
#define __Define_StartupScript_H__


#define STARTUPSCRIPT_TABLE "StartupScript"
#define STARTUPSCRIPT_PK_STARTUPSCRIPT_FIELD "PK_StartupScript"
#define STARTUPSCRIPT_PK_STARTUPSCRIPT_TABLE_FIELD "StartupScript.PK_StartupScript"
#define STARTUPSCRIPT_COMMAND_FIELD "Command"
#define STARTUPSCRIPT_COMMAND_TABLE_FIELD "StartupScript.Command"
#define STARTUPSCRIPT_DESCRIPTION_FIELD "Description"
#define STARTUPSCRIPT_DESCRIPTION_TABLE_FIELD "StartupScript.Description"
#define STARTUPSCRIPT_PARAMETER_SYNTAX_FIELD "Parameter_Syntax"
#define STARTUPSCRIPT_PARAMETER_SYNTAX_TABLE_FIELD "StartupScript.Parameter_Syntax"
#define STARTUPSCRIPT_CORE_BOOT_ORDER_FIELD "Core_Boot_Order"
#define STARTUPSCRIPT_CORE_BOOT_ORDER_TABLE_FIELD "StartupScript.Core_Boot_Order"
#define STARTUPSCRIPT_CORE_BACKGROUND_FIELD "Core_Background"
#define STARTUPSCRIPT_CORE_BACKGROUND_TABLE_FIELD "StartupScript.Core_Background"
#define STARTUPSCRIPT_CORE_ENABLED_FIELD "Core_Enabled"
#define STARTUPSCRIPT_CORE_ENABLED_TABLE_FIELD "StartupScript.Core_Enabled"
#define STARTUPSCRIPT_CORE_PARAMETER_FIELD "Core_Parameter"
#define STARTUPSCRIPT_CORE_PARAMETER_TABLE_FIELD "StartupScript.Core_Parameter"
#define STARTUPSCRIPT_MD_BOOT_ORDER_FIELD "MD_Boot_Order"
#define STARTUPSCRIPT_MD_BOOT_ORDER_TABLE_FIELD "StartupScript.MD_Boot_Order"
#define STARTUPSCRIPT_MD_BACKGROUND_FIELD "MD_Background"
#define STARTUPSCRIPT_MD_BACKGROUND_TABLE_FIELD "StartupScript.MD_Background"
#define STARTUPSCRIPT_MD_ENABLED_FIELD "MD_Enabled"
#define STARTUPSCRIPT_MD_ENABLED_TABLE_FIELD "StartupScript.MD_Enabled"
#define STARTUPSCRIPT_MD_PARAMETER_FIELD "MD_Parameter"
#define STARTUPSCRIPT_MD_PARAMETER_TABLE_FIELD "StartupScript.MD_Parameter"
#define STARTUPSCRIPT_HYBRID_BOOT_ORDER_FIELD "Hybrid_Boot_Order"
#define STARTUPSCRIPT_HYBRID_BOOT_ORDER_TABLE_FIELD "StartupScript.Hybrid_Boot_Order"
#define STARTUPSCRIPT_HYBRID_BACKGROUND_FIELD "Hybrid_Background"
#define STARTUPSCRIPT_HYBRID_BACKGROUND_TABLE_FIELD "StartupScript.Hybrid_Background"
#define STARTUPSCRIPT_HYBRID_ENABLED_FIELD "Hybrid_Enabled"
#define STARTUPSCRIPT_HYBRID_ENABLED_TABLE_FIELD "StartupScript.Hybrid_Enabled"
#define STARTUPSCRIPT_HYBRID_PARAMETER_FIELD "Hybrid_Parameter"
#define STARTUPSCRIPT_HYBRID_PARAMETER_TABLE_FIELD "StartupScript.Hybrid_Parameter"


#endif

