Document: pluto-sql2cpp
Title: Debian pluto-sql2cpp Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-sql2cpp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-sql2cpp/pluto-sql2cpp.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-sql2cpp/pluto-sql2cpp.ps.gz

Format: text
Files: /usr/share/doc/pluto-sql2cpp/pluto-sql2cpp.text.gz

Format: HTML
Index: /usr/share/doc/pluto-sql2cpp/html/index.html
Files: /usr/share/doc/pluto-sql2cpp/html/*.html
