Document: pluto-mplayer-player
Title: Debian pluto-mplayer-player Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-mplayer-player is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-mplayer-player/pluto-mplayer-player.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-mplayer-player/pluto-mplayer-player.ps.gz

Format: text
Files: /usr/share/doc/pluto-mplayer-player/pluto-mplayer-player.text.gz

Format: HTML
Index: /usr/share/doc/pluto-mplayer-player/html/index.html
Files: /usr/share/doc/pluto-mplayer-player/html/*.html
