Document: mtx
Title: Debian mtx Manual
Author: <insert document author here>
Abstract: This manual describes what mtx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mtx/mtx.sgml.gz

Format: postscript
Files: /usr/share/doc/mtx/mtx.ps.gz

Format: text
Files: /usr/share/doc/mtx/mtx.text.gz

Format: HTML
Index: /usr/share/doc/mtx/html/index.html
Files: /usr/share/doc/mtx/html/*.html

  
