#ifndef __CONSTANTS_H_
#define __CONSTANTS_H_

#define MASTER_BACKEND_HOST		"localhost"
#define MASTER_BACKEND_PORT		6143

#define FOO_MASTER_BACKEND_PORT		6543

#define FOO_MIN_BACKENDPORT			6666
#define FOO_MAX_BACKENDPORT			7777

#endif
