Document: lmce-xine-plugin
Title: Debian lmce-xine-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-xine-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-xine-plugin/lmce-xine-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-xine-plugin/lmce-xine-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-xine-plugin/lmce-xine-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-xine-plugin/html/index.html
Files: /usr/share/doc/lmce-xine-plugin/html/*.html
