Document: mce-launcher
Title: Debian mce-launcher Manual
Author: <insert document author here>
Abstract: This manual describes what mce-launcher is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mce-launcher/mce-launcher.sgml.gz

Format: postscript
Files: /usr/share/doc/mce-launcher/mce-launcher.ps.gz

Format: text
Files: /usr/share/doc/mce-launcher/mce-launcher.text.gz

Format: HTML
Index: /usr/share/doc/mce-launcher/html/index.html
Files: /usr/share/doc/mce-launcher/html/*.html

  
