#!/bin/bash
if [[ -n "$HEADER_FB_JOGGLER" ]]; then
	return 0
fi
HEADER_FB_JOGGLER=included

firstboot_lmce_joggler_preinst() {
	mv /etc/init/tty1* ~/
	cp -a /etc/init/tty2.conf /etc/init/tty1.conf
	: # no-op
}

firstboot_lmce_joggler_postinst() {
	echo -e "Setting up joggler specific boot settings" >&2

	. /usr/pluto/bin/Config_Ops.sh

	ConfSet "AVWizardOverride" "0"
	ConfSet "AVWizardDone" "1"
}
