#!/bin/bash
if [[ -n "$HEADER_FB_JOGGLER" ]]; then
	return 0
fi
HEADER_FB_JOGGLER=included

firstboot_mid_joggler_preinst() {
	rm -f /etc/init/tty1.conf* || :
	rm -f /home/joggler/.xinitrc || :

	cat <<-EEOF > /etc/asound.conf
		pcm.!default {
		    type plug
		    slave.pcm "dmixer"
		}

		pcm.dmixer  {
		    type dmix
		    ipc_key 1024
		    slave {
		        pcm "hw:0,0"
		        period_time 0
		        period_size 1024
		        buffer_size 4096
		        rate 44100
		    }
		    bindings {
		        0 0
		        1 1
		    }
		}

		ctl.dmixer {
		    type hw
		    card 0
		}
		EEOF
}


firstboot_mid_joggler_kernel() {
	:
}

firstboot_mid_joggler_postinst() {
	echo -e "Setting up joggler specific boot settings" >&2

	. /usr/pluto/bin/Config_Ops.sh

	ConfSet "AVWizardOverride" "0"
	ConfSet "AVWizardDone" "1"

	update-rc.d -f backlight defaults 10 >/dev/null
}
