Document: pluto-security
Title: Debian pluto-security Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-security is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-security/pluto-security.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-security/pluto-security.ps.gz

Format: text
Files: /usr/share/doc/pluto-security/pluto-security.text.gz

Format: HTML
Index: /usr/share/doc/pluto-security/html/index.html
Files: /usr/share/doc/pluto-security/html/*.html
