<?

	$content["home"]="content/home.inc";

	$content["batch/view"]="content/batch/view.inc";
	$content["batch/detail"]="content/batch/detail.inc";

	$content["schema/view"]="content/schema/view.inc";

	$content["tables/view"]="content/tables/view.inc";

	$content["row/view"]="content/row/view.inc";

	$content["users/view"]="content/users/view.inc";
	$content["users/add"]="content/users/add.inc";
	$content["users/add_form"]="content/users/add_form.inc";

	$content["server/log"]="content/server/log.inc";

	$content["ops/approve"]="content/ops/approve.inc";
	$content["ops/approve_form"]="content/ops/approve_form.inc";

	$content["login"]="content/login.inc";
	$content["logout"]="content/logout.inc";
?>
