<center>
- <? echo _("Batches") ?> -
<p>
<a href="?site=batch/view"><? echo _("View batches"); ?></a>
<p>
<a href="?site=ops/approve_form"><? echo _("Approve batch"); ?></a>
<p>
- <? echo _("Tables") ?> -
<p>
<a href="?site=tables/view"><? echo _("View tables"); ?></a>
<p>
- <? echo _("Schema") ?> -
<p>
<a href="?site=schema/view"><? echo _("View schema"); ?></a>
<p>
- <? echo _("User Management") ?> -
<p>
<a href="?site=login"><? echo _("Login"); ?></a>
<p>
<a href="?site=users/view"><? echo _("View users"); ?></a>
<p>
- <? echo _("sqlCVS Server") ?> -
<p>
<a href="?site=server/log"><? echo _("View Logfile"); ?></a>
<p>
- <? echo _("LMCE")." "._("Links") ?> -
<p>
<a href="http://wiki.linuxmce.org" target="lmce_wiki"><? echo _("Wiki"); ?></a>
<p>
<a href="http://forum.linuxmce.org" target="lmce_forum"><? echo _("Forum"); ?></a>
<p>
<a href="http://www.charonmedia.org/mailman/listinfo" target="lmce_list"><? echo _("Mailing Lists"); ?></a>
<p>
</center>
