#ifndef __CORP_SERVER_DEFINES_H__0983475
#define __CORP_SERVER_DEFINES_H__0983475


#define CORPSERVER_COMMAND_UPDATE_EPG 		1
#define CORPSERVER_COMMAND_UPDATE_CONFIG 	2
#define CORPSERVER_COMMAND_UPDATE_SOFTWARE 	3
#define CORPSERVER_COMMAND_RESTART	 	4
#define CORPSERVER_COMMAND_SEND_LOG	 	5


#define CORPSERVER_EVENT_SHUTDOWN	 	6
#define CORPSERVER_EVENT_STARTUP 		7
#define CORPSERVER_EVENT_PACKAGEVERSION		8
#define CORPSERVER_EVENT_PING			9

#define CORPSERVER_PARAM_STATUS			1
#define CORPSERVER_PARAM_NAME			2
#define CORPSERVER_PARAM_VERSION		3
#define CORPSERVER_PARAM_IP			4

#define CORPSERVER_STATUS_OK			1
#define CORPSERVER_STATUS_ERROR			2
#define CORPSERVER_STATUS_RELOAD		3
#define CORPSERVER_STATUS_SOCKETFAILED		4
#define CORPSERVER_STATUS_RECONNECT		5
#define CORPSERVER_STATUS_UNKNOWN		6

#endif
