#!/bin/bash

if [[ -n "$HEADER_install_common" ]]; then
	return 0
fi
HEADER_install_common=included

###########################################################
### Setup global variables
###########################################################
log_file=/var/log/LinuxMCE_Setup.log

TARGET_DISTRO=$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')
TARGET_RELEASE=$(lsb_release -c -s)
TARGET_ARCH=$(apt-config dump | grep 'APT::Architecture' | sed 's/.*"\(.*\)".*/\1/g' | head -1)
DEB_CACHE="$TARGET_DISTRO-$TARGET_RELEASE-$TARGET_ARCH"
REPO="main"

TARGET_KVER_LTS_HES=""
[[ "precise" == "$TARGET_RELEASE" ]] && TARGET_KVER_LTS_HES="-lts-trusty"
[[ "trusty" == "$TARGET_RELEASE" ]] && TARGET_KVER_LTS_HES="-lts-utopic"

DISTRO="$TARGET_RELEASE"
LOCAL_REPO_BASE=/usr/pluto/deb-cache/$DEB_CACHE
LOCAL_REPO_DIR=./

DT_CORE=1
DT_HYBRID=2
DT_MEDIA_DIRECTOR=3

DEVICEDATA_DISTRO_Raspbian_Wheezy_CONST=19
DEVICEDATA_DISTRO_Ubuntu_Precise_CONST=20
DEVICEDATA_DISTRO_Ubuntu_Trusty_CONST=21
DEVICEDATA_DISTRO_Raspbian_Jessie_CONST=22

mce_wizard_data_shell=/tmp/mce_wizard_data.sh

MESSGFILE=/tmp/messenger

#Setup Pathing
export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# TODO: make compatible with raspbian
case "$TARGET_ARCH" in
	i386|amd64)
		TARGET_REPO="http://archive.ubuntu.com/ubuntu/"
		SECURITY_REPO="http://security.ubuntu.com/ubuntu/"
		;;
	armhf)
		TARGET_REPO="http://ports.ubuntu.com/"
		SECURITY_REPO="http://ports.ubuntu.com/"
		;;
esac

###########################################################
### Setup Functions - Error checking and logging
###########################################################

StatsMessage () {
	printf "`date` - $* \n"
}

VerifyExitCode () {
	local EXITCODE=$?
	if [ "$EXITCODE" != "0" ] ; then
		echo "An error (Exit code $EXITCODE) occured during the last action"
		echo "$1"
		exit 1
	fi
}

TeeMyOutput () {
	# Usage:
	# source TeeMyOutput.sh --outfile <file> [--infile <file>] [--stdout|--stderr|--stdboth] [--append] [--exclude <egrep pattern>] -- "$@"
	#   --outfile <file>         the file to tee our output to
	#   --infile <file>          the file to feed ourselves with on stdin
	#   --stdout                 redirect stdout (default)
	#   --stderr                 redirect stderr
	#   --stdboth                redirect both stdout and stderr
	#   --append                 run tee in append mode
	#   --exclude <pattern>      strip matching lines from output; pattern is used with egrep
	#
	# Environment:
	#   SHELLCMD="<shell command>" (ex: bash -x)

	if [[ -n "$TeeMyOutput" ]]; then
	        return 0
	fi
	Me="TeeMyOutput"

	# parse parameters
	for ((i = 1; i <= "$#"; i++)); do
	        Parm="${!i}"
	        case "$Parm" in
	                --outfile) ((i++)); OutFile="${!i}" ;;
	                --infile) ((i++)); InFile="${!i}" ;;
	                --stdout|--stderr|--stdboth) Mode="${!i#--std}" ;;
	                --append) Append=yes ;;
	                --exclude) ((i++)); Exclude="${!i}" ;;
	                --) LastParm="$i"; break ;;
	                *) echo "$Me: Unknown parameter '$Parm'"; exit 1
	        esac
	done

	if [[ -z "$OutFile" ]]; then
	        echo "$Me: No outfile"
	        exit 1
	fi

	if [[ -z "$LastParm" ]]; then
	        LastParm="$#"
	fi

	# original parameters
	for ((i = "$LastParm" + 1; i <= "$#"; i++)); do
	        OrigParms=("${OrigParms[@]}" "${!i}")
	done

	# construct command components
	case "$Mode" in
	        out) OurRedirect=() ;;
	        err) OurRedirect=("2>&1" "1>/dev/null") ;;
	        both) OurRedirect=("2>&1") ;;
	esac

	if [[ "$Append" == yes ]]; then
	        TeeParm=(-a)
	fi

	if [[ -n "$InFile" ]]; then
	        OurRedirect=("${OurRedirect[@]}" "<$InFile")
	fi

	# do our stuff
	export TeeMyOutput=yes
	ExitCodeFile="/tmp/TeeMyOutputExitCode_$$"
	trap "rm -rf '$ExitCodeFile'" EXIT

	Run() {
	        eval exec "${OurRedirect[@]}"
	        $SHELLCMD "$0" "${OrigParms[@]}"
	        echo $? >"$ExitCodeFile"
	}

	if [[ -z "$Exclude" ]]; then
	        Run | tee "${TeeParm[@]}" "$OutFile"
	else
	        Run | grep --line-buffered -v "$Exclude" | tee "${TeeParm[@]}" "$OutFile"
	fi

	ExitCode=$(<"$ExitCodeFile")
	exit "$ExitCode"
	exit 1 # just in case
}

Setup_Logfile () {
	if [ ! -f ${log_file} ]; then
		touch ${log_file}
		if [ $? = 1 ]; then
			echo "`date` - Unable to write to ${log_file} - re-run script as root"
			exit 1
		fi
	else
		#zero out an existing file
		echo > ${log_file}
	fi
	TeeMyOutput --outfile ${log_file} --stdboth --append -- "$@"
	VerifyExitCode "Log Setup"
	echo "`date` - Logging initiatilized to ${log_file}"
}


###########################################################
### Setup Functions - General functions
###########################################################

gpgUpdate () {
	# TODO: FIXME: remove ping??? why is this here???
	# This does an update, while adding gpg keys for any that are missing.
	# check if online first? TODO: we have a fn for this
	if ping -c 1 google.com; then
		#sed -i 's/#deb/deb/g' /etc/apt/sources.list
		gpgs=$(apt-get update |& grep -s NO_PUBKEY | awk '{ print $NF }' | cut -c 9-16);
		if [ -n "$gpgs" ]; then
			echo "$gpgs" | while read gpgkeys; do
				gpg --keyserver pgp.mit.edu --recv-keys "$gpgkeys"
				gpg --export --armor "$gpgkeys" | apt-key add -
			done
		fi
	fi
}

AptUpdate () {
	apt-get -qq update
	VerifyExitCode "apt-get update"
}

AptUpgrade () {
	apt-get -y -q -f --force-yes upgrade
	VerifyExitCode "apt-get upgrade"
}

AptDistUpgrade () {
	apt-get -y -q -f --force-yes dist-upgrade
	VerifyExitCode "apt-get dist-upgrade"
}

UpdateUpgrade () {
	#perform an update and a dist-upgrade
	StatsMessage "Performing an update and an upgrade to all components"
	gpgUpdate # AptUpdate
	AptDistUpgrade
}

TimeUpdate () {
	StatsMessage "Synchronizing time with an online server"
	#Update system time to match ntp server
	ntpdate ntp.ubuntu.com
}

Disable_NetworkManager () {
	update-rc.d -f NetworkManager remove
}

ConfigSources () {
	StatsMessage "Configuring sources.list for MCE install"

	. /usr/pluto/install/AptSources.sh
	AptSrc_ParseSourcesList "/etc/apt/sources.list"
	AptSrc_AddSource "file:${LOCAL_REPO_BASE} ${LOCAL_REPO_DIR}"
	AptSrc_AddSource "http://deb.linuxmce.org/${TARGET_DISTRO}/ ${TARGET_RELEASE} ${REPO}"
	AptSrc_WriteSourcesList
}

UpdateDebCache () {
	StatsMessage "Updating deb-cache package files"
	/usr/pluto/bin/UpdateDebCache.sh
}

Notify_Reboot () {
	/usr/share/update-notifier/notify-reboot-required
}


return 0

###########################################################
###########################################################
### Deprecated Functions
###########################################################
###########################################################

CreateBackupSources () {
	# FIXME: REMOVE? This has moved to pluto-boot-scripts postinst
	:
	if [ ! -e /etc/apt/sources.list.pbackup ]; then
		StatsMessage "Backing up sources.list file"
		cp -a /etc/apt/sources.list /etc/apt/sources.list.pbackup
	fi
}

CreateBasePackagesFile () {
	# FIXME: REMOVE? This has moved to pluto-boot-scripts postinst
	:
	StatsMessage "Setting up deb-cache/ packages files"
	#Make sure there is are Packages files on the MD so apt-get update does not fail
	if [[ ! -f /usr/pluto/deb-cache/Packages.gz ]] ; then
		mkdir -p /usr/pluto/deb-cache/
		rm -f /usr/pluto/deb-cache/Packages
		touch  /usr/pluto/deb-cache/Packages
		gzip -9c < /usr/pluto/deb-cache/Packages > /usr/pluto/deb-cache/Packages.gz
	fi

	StatsMessage "Setting up deb-cache/$DEB_CACHE packages files"
	#Make sure there is are Packages files on the MD so apt-get update does not fail
	if [[ ! -f /usr/pluto/deb-cache/$DEB_CACHE/Packages.gz ]] ; then
		mkdir -p /usr/pluto/deb-cache/$DEB_CACHE
		rm -f /usr/pluto/deb-cache/$DEB_CACHE/Packages
		touch  /usr/pluto/deb-cache/$DEB_CACHE/Packages
		gzip -9c < /usr/pluto/deb-cache/$DEB_CACHE/Packages > /usr/pluto/deb-cache/$DEB_CACHE/Packages.gz
	fi
}

Disable_CompCache () {
	# FIXME: REMOVE? This has moved to pluto-boot-scripts postinst
	:
	# Disable compcache
	if [ -f /usr/share/initramfs-tools/conf.d/compcache ]; then
		rm -f /usr/share/initramfs-tools/conf.d/compcache && update-initramfs -u
	fi
}

ConfigAptConf () {
	# FIXME: REMOVE? This is in pluto-boot-scripts postinst
	:
	# Setup LinuxMCE's apt.conf
	cat <<-EOF >/etc/apt/apt.conf.d/30pluto
		// LinuxMCE apt conf add-on
		#Apt::Cache-Limit "12582912";
		Dpkg::Options { "--force-confold"; };
		Acquire::http::timeout "10";
		Acquire::ftp::timeout "10";
		APT::Get::AllowUnauthenticated "true";
		//APT::Get::force-yes "yes";
		APT::Acquire { Retries  "20" };
		EOF
}

PreSeed_DebConf () {
	# FIXME: REMOVE? This is in pluto-boot-scripts preinst
	:
	StatsMessage "PreSeeding package installation preferences"

	debconf-set-selections /usr/pluto/install/preseed.cfg
	VerifyExitCode "debconf-set-selections - preseed data"
}

Fix_LSB_Data () {
	# FIXME: REMOVE? This has moved to pluto-boot-scripts postinst
	:
	case "$TARGET_DISTRO" in
		raspbian)
			# raspbian doesn't come with lsb-release by default???
			cat <<-EOF > /etc/lsb-release
				DISTRIB_ID=Raspbian
				DISTRIB_CODENAME=$TARGET_RELEASE
				EOF
			;;
	esac
}

Disable_DisplayManager () {
	# FIXME: REMOVE? This has moved to pluto-boot-scripts postinst
	:
	# TODO: dpkg-divert this so it doesn't come back
	StatsMessage "Disabling display manager"
	mkdir -p "/etc/X11"
	echo "/bin/false" >/etc/X11/default-display-manager
	update-rc.d -f kdm remove >/dev/null
	update-rc.d -f sddm remove >/dev/null
	update-rc.d -f lightdm remove >/dev/null
}




#!/bin/bash

. /usr/pluto/install/install-common.sh	# lmce-install-scripts

if [[ -n "$HEADER_install_core" ]]; then
	return 0
fi
HEADER_install_core=included

###########################################################
### Setup Functions - Reference functions
###########################################################

Create_Wizard_Data-Double_Nic_Shell () {
	echo "c_deviceType=2 # 1-Core, 2-Hybrid, 3-DiskedMD
c_netIfaceNo=1
c_netExtName='{extif}'
c_netExtIP=''
c_netExtMask=''
c_netExtGateway=''
c_netExtDNS1=''
c_netExtDNS2=''
c_netExtUseDhcp=1 # 1 - Yes / 0 - No
c_runDhcpServer=1 # 1 - Yes / 0 - No
c_netIntName='{intif}'
c_netIntIPN='192.168.80'
c_startupType=1 #0 - Start Kde / 1 - Start LMCE
c_installType=1
c_installMirror='http://archive.ubuntu.com/ubuntu/'
c_netExtKeep='true'
c_installUI=0 # 0 - UI1, 1 - UI2M, 2 - UI2A
c_linuxmceCdFrom=1 # 1 - CD, 2 -ISO
c_linuxmceCdIsoPath='' 
c_ubuntuExtraCdFrom=1
c_ubuntuExtraCdPath=''
c_ubuntuLiveCdFrom=1
c_ubuntuLiveCdPath=''
"
}

Create_Wizard_Data-Single_Nic_Shell () {
echo "c_deviceType=2 # 1-Core, 2-Hybrid, 3-DiskedMD
c_netIfaceNo=1
c_netExtName='{extif}'
c_netExtIP='{extip}'
c_netExtMask='{extMask}'
c_netExtGateway='{extGW}'
c_netExtDNS1='{extDNS}'
c_netExtDNS2=''
c_netExtUseDhcp={extUseDhcp} # 1 - Yes / 0 - No
c_runDhcpServer={runDhcp} # 1 - Yes / 0 - No
c_netIntName='{extif}:1'
c_netIntIPN='192.168.80'
c_startupType=1 #0 - Start Kde / 1 - Start LMCE
c_installType=1
c_installMirror='http://archive.ubuntu.com/ubuntu/'
c_netExtKeep='true'
c_installUI=0 # 0 - UI1, 1 - UI2M, 2 - UI2A
c_linuxmceCdFrom=1 # 1 - CD, 2 -ISO
c_linuxmceCdIsoPath='' 
c_ubuntuExtraCdFrom=1
c_ubuntuExtraCdPath=''
c_ubuntuLiveCdFrom=1
c_ubuntuLiveCdPath=''
c_singleNIC=1
"
}


###########################################################
### Setup Functions - General functions
###########################################################

Setup_Pluto_Conf () {
	StatsMessage "Seting Up MCE Configuration file"
	AutostartCore=1
	AutostartMedia=1

	case "$TARGET_RELEASE" in
		"intrepid")
			# select UI1
			PK_DISTRO=17
			;;
		"lucid")
			# select UI2 without alpha blending
			PK_DISTRO=18
			;;
		"precise")
			PK_DISTRO=20
			LTS_HES=-lts-trusty
			;;
		"trusty")
			PK_DISTRO=21
			LTS_HES=-lts-utopic
			;;
		"wheezy")
			PK_DISTRO=19
			;;
		"jessie")
			PK_DISTRO=22
			;;
	esac


	StatsMessage "Generating Default Config File"
	cat <<-EOF >/etc/pluto.conf
		# Pluto config file
		MySqlHost = localhost
		MySqlUser = root
		MySqlPassword =
		MySqlDBName = pluto_main
		DCERouter = localhost
		MySqlPort = 3306
		DCERouterPort = 3450
		PK_Device = 1
		Activation_Code = 1111
		PK_Installation = 1
		PK_Users = 1
		PK_Distro = $PK_DISTRO
		Display = 0
		SharedDesktop = 1
		OfflineMode = false
		#<-mkr_b_videowizard_b->
		UseVideoWizard = 1
		#<-mkr_b_videowizard_e->
		LogLevels = 1,5,7,8
		#ImmediatelyFlushLog = 1
		AutostartCore = $AutostartCore
		AutostartMedia = $AutostartMedia
		LTS_HES = $LTS_HES
		EOF
	chmod 777 /etc/pluto.conf &>/dev/null
}

Create_And_Config_Devices () {
	#Source the SQL_OPS file
	. /usr/pluto/bin/SQL_Ops.sh	# pluto-boot-scripts

	DEVICE_TEMPLATE_Core=7
	DEVICE_TEMPLATE_MediaDirector=28

	## Update some info in the database
	Q="INSERT INTO Installation(Description, ActivationCode) VALUES('LinuxMCE', '1111')"
	RunSQL "$Q"

	## Create the Core device and set it's description
	StatsMessage "Setting up your computer to act as a 'Core'"
	Core_PK_Device=$(/usr/pluto/bin/CreateDevice -d $DEVICE_TEMPLATE_Core | tee /dev/stderr | tail -1)
	Q="UPDATE Device SET Description='CORE' WHERE PK_Device='$Core_PK_Device'"
	RunSQL "$Q"

	#Setup media director with core
	StatsMessage "Setting up your computer to act as a 'Media Director'"
	/usr/pluto/bin/CreateDevice -d $DEVICE_TEMPLATE_MediaDirector -C "$Core_PK_Device"
	Hybrid_DT=$(RunSQL "SELECT PK_Device FROM Device WHERE FK_DeviceTemplate='$DEVICE_TEMPLATE_MediaDirector' LIMIT 1")
	Q="UPDATE Device SET Description='The core/hybrid' WHERE PK_Device='$Hybrid_DT'"
	RunSQL "$Q"

	StatsMessage "Updating Startup Scripts"
	# "DCERouter postinstall"
	/usr/pluto/bin/Update_StartupScrips.sh
}

Config_Device_Changes () {
	StatsMessage "Running /usr/pluto/bin/Config_Device_Changes.sh"
	/usr/pluto/bin/Config_Device_Changes.sh
}

Nic_Config () {
	StatsMessage "Starting NIC Discovery and Configuration"
	# Find out, what nic configuration we have. This is needed for later on to fill the database
	# correctly.
	if  [[ `ifconfig -s -a  | awk '$1 != "Iface" && $1 != "lo" && $1 != "pan0" { print $1 }' | wc -l` > 1 ]]; then
		Create_Wizard_Data-Double_Nic_Shell > ${mce_wizard_data_shell}
		#Use these for the defaults if we cannot automatically determine which to use
		#TODO: Error out and instruct the user to setup a working connection? Or ask them to manually choose?
		extif="eth0"
		intif="eth1"
		if route -n | grep -q '^0.0.0.0'; then
			#We have a default route, use it for finding external interface.
			extif=`route -n | awk '$1 == "0.0.0.0" { print $8 }'`
			#Use the first available interface as the internal interface.
			for if in `ifconfig -s -a | awk '$1 != "Iface" && $1 != "lo"  && $1 != "pan0" { print $1 }'`
			do
				if [ "$if" != "$extif" ]
				then
					intif=$if
					break
				fi
			done
		fi
		echo "Using $extif for external interface"
		echo "Using $intif for internal interface"

		sed --in-place -e "s,\({extif}\),$extif,g" ${mce_wizard_data_shell}
		sed --in-place -e "s,\({intif}\),$intif,g" ${mce_wizard_data_shell}
	else
		extif=eth0
		if route -n | grep -q '^0.0.0.0'; then
			#We have a default route, use it for finding external interface.
			extif=`route -n | awk '$1 == "0.0.0.0" { print $8 }'`
		fi
		Create_Wizard_Data-Single_Nic_Shell > ${mce_wizard_data_shell}
		echo "Using $extif for single nic install"
		sed --in-place -e "s,\({extif}\),$extif,g" ${mce_wizard_data_shell}

		# set c_netExtIP and friends , as this is used in Configure_Network_Options (i.e. before Network_Setup...)
		extIP=$(ip addr | grep "$extif" | grep -m 1 'inet ' | awk '{print $2}' | cut -d/ -f1)
		sed --in-place -e "s,\({extip}\),$extIP,g" ${mce_wizard_data_shell}

		# Set use external DHCP and run own dhcp based on extifs current setting
		ExtUsesDhcp=$(grep "iface $extif " /etc/network/interfaces | grep -cF 'dhcp')
		if [[ $ExtUsesDhcp == 0 ]]; then
			# Not dhcp defined in config file, test if dhclient got us an IP
			# /var/run/dhcp for newer than 1004
			if [[ (`ls /var/lib/dhcp/dhclient-*-$extif.lease && [[ $? == 0 ]]` || -e /var/run/dhclient-$extif.pid) && `pgrep -c dhclient` == 1 ]]; then
				ExtUsesDhcp=1
			fi
		fi
		RunDHCP=0
		if [[ $ExtUsesDhcp == 0 ]]; then
			echo "$extif does not use DHCP, setting ExtUseDhcp=0 and RunDHCPServer=1 and detecting current network settings"
			RunDHCP=1

			ExtGateway=$(grep -A 10 "^iface $extif" /etc/network/interfaces | grep '^\s*gateway' -m 1 | grep -o  '[0-9.]*')
			ExtMask=$(grep -A 10 "^iface $extif" /etc/network/interfaces | grep '^\s*netmask' -m 1 | grep -o '[0-9.]*')
			ExtDNS=$(grep 'nameserver' /etc/resolv.conf | grep -o '[0-9.]*' -m 1)
		fi

		sed --in-place -e "s,\({extMask}\),$ExtMask,g" ${mce_wizard_data_shell}
		sed --in-place -e "s,\({extGW}\),$ExtGateway,g" ${mce_wizard_data_shell}
		sed --in-place -e "s,\({extDNS}\),$ExtDNS,g" ${mce_wizard_data_shell}

		sed --in-place -e "s,\({extUseDhcp}\),$ExtUsesDhcp,g" ${mce_wizard_data_shell}
		sed --in-place -e "s,\({runDhcp}\),$RunDHCP,g" ${mce_wizard_data_shell}
	fi

	if [[ ! -r ${mce_wizard_data_shell} ]]; then
	        echo "`date` - Wizard Information is corrupted or missing."
		exit 1
	fi
	. ${mce_wizard_data_shell}
	VerifyExitCode "MCE Wizard Data"

	Core_PK_Device="0"

	#Setup the network interfaces
	echo > /etc/network/interfaces
	echo "auto lo" >> /etc/network/interfaces
	echo "iface lo inet loopback" >> /etc/network/interfaces
	echo >> /etc/network/interfaces
	echo "auto $c_netExtName" >> /etc/network/interfaces
	if [[ $c_netExtUseDhcp  == "1" ]] ;then
		echo "    iface $c_netExtName inet dhcp" >> /etc/network/interfaces
	else
		if [[ "$c_netExtIP" != "" ]] && [[ "$c_netExtName" != "" ]] &&
		   [[ "$c_netExtMask" != "" ]] && [[ "$c_netExtGateway" != "" ]] ;then
			echo "" >> /etc/network/interfaces
			echo "    iface $c_netExtName inet static" >> /etc/network/interfaces
			echo "    address $c_netExtIP" >> /etc/network/interfaces
			echo "    netmask $c_netExtMask" >> /etc/network/interfaces
			echo "    gateway $c_netExtGateway" >> /etc/network/interfaces
		fi
	fi
	echo "" >> /etc/network/interfaces
	echo "auto $c_netIntName" >> /etc/network/interfaces
	echo "    iface $c_netIntName inet static" >> /etc/network/interfaces
	echo "    address $c_netIntIPN" >> /etc/network/interfaces
	echo "    netmask 255.255.255.0" >> /etc/network/interfaces
}

Configure_Network_Options () {
	# Updating hosts file and the Device_Data for the core with the internal and external network
	# addresses - uses Initial_DHCP_Config.sh from the lmce-install-scripts package.
	StatsMessage "Configuring your internal network"
	#Source the SQL Ops file
	. /usr/pluto/bin/SQL_Ops.sh	# pluto-boot-scripts

	## Setup /etc/hosts
	echo > /etc/hosts
	echo "127.0.0.1 localhost.localdomain localhost" >> /etc/hosts
	echo "$c_netExtIP dcerouter $(/bin/hostname)"    >> /etc/hosts

	error=false
	Network=""
	Digits_Count=0

	for Digits in $(echo "$c_netIntIPN" | tr '.' ' ') ;do
		[[ "$Digits" == *[^0-9]* ]]            && error=true
		[[ $Digits -lt 0 || $Digits -gt 255 ]] && error=true

		if [[ "$Network" == "" ]] ;then
			Network="$Digits"
		else
			Network="${Network}.${Digits}"
		fi

		Digits_Count=$(( $Digits_Count + 1 ))
	done
	[[ $Digits_Count -lt 1 || $Digits_Count -gt 3 ]] && error=true

	if [[ "$error" == "true" ]] ;then
		Network="192.168.80"
		Digits_Count="3"
	fi

	IntIP="$Network"
	IntNetmask=""
	for i in `seq 1 $Digits_Count` ;do
		if [[ "$IntNetmask" == "" ]] ;then
			IntNetmask="255"
		else
			IntNetmask="${IntNetmask}.255"
		fi
	done
	for i in `seq $Digits_Count 3` ;do
		if [[ $i == "3" ]] ;then
			IntIP="${IntIP}.1"
		else
			IntIP="${IntIP}.0"
		fi

		IntNetmask="${IntNetmask}.0"
	done

	if [[ "$c_netIntName" == "" ]] ;then
		IntIf="$c_netExtName:0"
	else
		IntIf="$c_netIntName"
	fi

	if [[ "$c_singleNIC" == "1" ]] ;then
		#Disable firewalls on single NIC operation, refs #396
		echo "We are in single NIC mode -> internal firewalls disabled"
		echo "DisableFirewall=1" >>/etc/pluto.conf
		echo "DisableIPv6Firewall=1" >>/etc/pluto.conf
	fi

	if [[ "$c_netExtUseDhcp" == "0" ]] ;then
		NETsetting="$c_netExtName,$c_netExtIP,$c_netExtMask,$c_netExtGateway,$c_netExtDNS1|$IntIf,$IntIP,$IntNetmask"
	else
		NETsetting="$c_netExtName,dhcp|$IntIf,$IntIP,$IntNetmask"
	fi

	DHCPsetting=$(/usr/pluto/install/Initial_DHCP_Config.sh "$Network" "$Digits_Count")

	Q="REPLACE INTO Device_DeviceData(FK_Device,FK_DeviceData,IK_DeviceData) VALUES('$Core_PK_Device',32,'$NETsetting')"
	RunSQL "$Q"
	if [[ "$c_runDhcpServer" == "1" ]]; then
		Q="REPLACE INTO Device_DeviceData(FK_Device, FK_DeviceData, IK_DeviceData)
			VALUES($Core_PK_Device, 28, '$DHCPsetting')"
		RunSQL "$Q"
	fi

	# create empty IPv6 tunnel settings field
	Q="REPLACE INTO Device_DeviceData(FK_Device,FK_DeviceData,IK_DeviceData) VALUES('$Core_PK_Device',292,'')"
	RunSQL "$Q"
}

addAdditionalTTYStart () {
	# TODO: this is ubuntu specific, alter to fn properly for debian/raspbian as well
	if [[ "$TARGET_RELEASE" = "lucid" ]] || [[ "$TARGET_RELEASE" = "precise" ]] || [[ "$TARGET_RELEASE" == "trusty" ]]; then
		sed -i 's/23/235/' /etc/init/tty2.conf
		sed -i 's/23/235/' /etc/init/tty3.conf
		sed -i 's/23/235/' /etc/init/tty4.conf
		# disable plymouth splash for now. Could be replaced by own LMCE splash later
		sed -i 's/ splash//' /etc/default/grub
		#Setup vmalloc for video drivers
		sed -i 's/GRUB_CMDLINE_LINUX=\"\"/GRUB_CMDLINE_LINUX=\"vmalloc=256m\"/' /etc/default/grub
		/usr/sbin/update-grub
	else
		echo "start on runlevel 5">>/etc/event.d/tty2
		echo "start on runlevel 5">>/etc/event.d/tty3
		echo "start on runlevel 5">>/etc/event.d/tty4
	fi
}

CleanInstallSteps () {
	return;

	# This is old and needs work but would allow you to wipe a db and start fresh without re-installing from scratch.
	if [[ -f /etc/pluto/install_cleandb ]]; then
		# on upgrade, the old keys are already in place, so keep them
		rm -f /etc/ssh/ssh_host_*
		dpkg-reconfigure -pcritical openssh-server

		PostInstPkg=(
			pluto-local-database pluto-media-database pluto-security-database pluto-system-database
			pluto-telecom-database lmce-asterisk
		)

		for Pkg in "${PostInstPkg[@]}"; do
			/var/lib/dpkg/info/"$Pkg".postinst configure
		done

		. /usr/pluto/bin/SQL_Ops.sh	# pluto-boot-scripts
		. /usr/pluto/bin/Config_Ops.sh	# pluto-boot-scripts

		# Raise max char limit on php.ini
		if ! grep -q 'max_input_vars' /etc/php5/apache2/php.ini; then 
			echo "max_input_vars = 15000" >> /etc/php5/apache2/php.ini
		fi

		# Mark remote assistance as diabled
		ConfDel remote

		arch=$(apt-config dump | grep 'APT::Architecture' | sed 's/APT::Architecture.*"\(.*\)".*/\1/g')

		Queries=(
			"UPDATE Device_DeviceData
				SET IK_DeviceData=15
			WHERE PK_Device IN (
				SELECT PK_Device FROM Device WHERE FK_DeviceTemplate IN (7, 28)
			)
			AND FK_DeviceData=7"
			"UPDATE Device_DeviceData SET IK_DeviceData='LMCE_CORE_u0804_$arch' WHERE IK_DeviceData='LMCE_CORE_1_1'"
			"UPDATE Device_DeviceData SET IK_DeviceData='LMCE_MD_u0804_i386'   WHERE IK_DeviceData='LMCE_MD_1_1'"
			"UPDATE Device_DeviceData SET IK_DeviceData='0' WHERE FK_DeviceData='234'"
			"UPDATE Device_DeviceData SET IK_DeviceData='i386' WHERE FK_DeviceData='112' AND IK_DeviceData='686'"
		 )

		for Q in "${Queries[@]}"; do
			RunSQL "$Q"
		done

		DT_DiskDrive=11
		DiskDrives=$(RunSQL "SELECT PK_Device FROM Device WHERE FK_DeviceTemplate='$DT_DiskDrive'")
		for DiskDrive in $DiskDrives ;do
			DiskDrive_DeviceID=$(Field 1 "$DiskDrive")
			for table in 'CommandGroup_Command' 'Device_Command' 'Device_CommandGroup' 'Device_DeviceData' 'Device_DeviceGroup' 'Device_Device_Related' 'Device_EntertainArea' 'Device_HouseMode' 'Device_Orbiter' 'Device_StartupScript' 'Device_Users' ;do
				RunSQL "DELETE FROM \\`$table\\` WHERE FK_DeviceID = '$DiskDrive_DeviceID' LIMIT 1"
			done
			RunSQL "DELETE FROM Device WHERE PK_Device = '$DiskDrive_DeviceID' LIMIT 1"
		done
	fi
}

CreateDisklessImage () {
	local diskless_log=/var/log/pluto/Diskless_Create-`date +"%F"`.log
	nohup /usr/pluto/bin/Diskless_CreateTBZ.sh >> ${diskless_log} 2>&1 &
}

Fix_Initrd_Vmlinux () {
	# FIXME: is this still necessary?
	:
	##### this occurs if we're installing after a kernel update, but prior to reboot
	StatsMessage "Starting initrd and vmlinuz fix"
	# Fix a problem with the /initrd.img and /vmlinuz links pointing to a different kernel than the
	# newest (and currently running) one
	LATEST_KERNEL=`ls /lib/modules --sort time --group-directories-first|head -1`
	KERNEL_TO_USE=`uname -r`

	if [ -f "/boot/initrd.img-$LATEST_KERNEL" ]; then
		KERNEL_TO_USE=$LATEST_KERNEL
	fi
	ln -s -f /boot/initrd.img-$KERNEL_TO_USE /initrd.img
	ln -s -f /boot/vmlinuz-$KERNEL_TO_USE /vmlinuz
}



return 0

###########################################################
###########################################################
### Deprecated Functions
###########################################################
###########################################################

Setup_Kernel_PostInst () {
	#FIXME: this has moved to pluto-boot-scripts - preinst
	:
	StatsMessage "Setting up kernel symlink fix"
	## Setup kernel postinst script to repair vmlinuz/initrd.img symlinks in /
	cat <<-"EOF" >/etc/kernel/postinst.d/update-symlinks
		#!/bin/bash
		# LinuxMCE post kernel image install.
		#
		# We make sure we can read the image and the kernel, and the softlink is correct.
		chmod g+r /boot/* || :
		chmod o+r /boot/* || :

		pushd / >/dev/null
		ln -sf boot/initrd.img-$1 initrd.img || :
		ln -sf boot/vmlinuz-$1 vmlinuz || :
		popd > /deb/null

		exit 0
		EOF
	chmod +x /etc/kernel/postinst.d/update-symlinks
}

PreSeed_MythWeb () {
	# FIXME: moved to pluto-mythtv-plugin preinst
	:
	#Seeding mythweb preferences to not override the LMCE site on install - for some odd reason, mythweb packages don't accept the set-selections
	touch /etc/default/mythweb
	cat <<-EOF >/etc/default/mythweb
		[cfg]
		enable = false
		only = false
		username =
		password =
		EOF
}

Setup_NIS () {
	# FIXME: this has moved to lmce-core preinst
	:
	# Put a temporary nis config file that will prevent ypbind to start
	# Temporary NIS setup, disabling NIS server and client.
	StatsMessage "Temporarily modifying the NIS configuration file disabling the NIS server and client"
	cat <<-EOF >/etc/default/nis
		NISSERVER=false
		NISCLIENT=false
		YPPWDDIR=/etc
		YPCHANGEOK=chsh
		NISMASTER=
		YPSERVARGS=
		YPBINDARGS=
		YPPASSWDDARGS=
		YPXFRDARGS=
		EOF
}

Config_MySQL_Server () {
	# FIXME: moved to lmce-core postinst
	:
	#Run mysql statement
	echo "UPDATE user SET Create_view_priv = 'Y', Show_view_priv = 'Y', \
		Create_routine_priv = 'Y', Alter_routine_priv = 'Y', \
		Create_user_priv = 'Y' WHERE User = 'debian-sys-maint'; \
		FLUSH PRIVILEGES; \
		" | mysql --defaults-extra-file=/etc/mysql/debian.cnf mysql
}

Setup_MakeDev () {
	# FIXME: Is this still necessary?
	:
	#Create logical link for MAKEDEV for the mdadm installation
	ln -s /sbin/MAKEDEV /dev/MAKEDEV
}

Setup_Hostname () {
	# FIXME: this has moved to lmce-core postinst
	:
	echo "Setting hostname"
	# set the hostname to dcerouter
	echo dcerouter > /etc/hostname
}



#!/bin/bash

. /usr/pluto/install/install-core.sh

if [[ -n "$HEADER_install_livedvd" ]]; then
	return 0
fi
HEADER_install_livedvd=included

###########################################################
### Live DVD Specific Fn's
###########################################################

FirstNetwork () {
	### This is a Live DVD Fn.

	echo "creating dumb DHCP interfaces template" > /var/log/pluto/firstnet.log
	nic_num=$(lspci | grep -ic "Ethernet")
	if [[ $nic_num -gt "1" ]]; then
		cat <<-EOF > /etc/network/interfaces
			auto lo
			iface lo inet loopback
			auto eth0
			iface eth0 inet dhcp
			auto eth1
			iface eth1 inet dhcp
			EOF
		ifconfig eth1 del 192.168.80.0 || :
	else
		cat <<-EOF > /etc/network/interfaces
			auto lo
			iface lo inet loopback
			auto eth0
			iface eth0 inet dhcp
			EOF
	fi
	/etc/init.d/networking stop
	service networking start --no-wait
}

SetupNetworking () {
	### This is a Live DVD Fn.

	### This is all done in /etc/init.d/linuxmce
	rm -f /etc/X11/xorg.conf
	rm -f /etc/network/interfaces
	## Reconfigure networking
	/usr/pluto/bin/Network_Setup.sh
	/usr/pluto/bin/ConfirmInstallation.sh
	/usr/pluto/bin/Timezone_Detect.sh
}

VideoDriverLive () {
	### This is a Live DVD Fn.

	vga_pci=$(lspci -v | grep ' VGA ')
	prop_driver="fbdev"
	chip_man=$(echo "$vga_pci" | grep -Ewo '(\[1002|\[1106|\[10de|\[8086)')

	case "$chip_man" in
		[10de)
			prop_driver="nouveau" ;;
		[1002)
			prop_driver="radeon" ;;
		[8086)
			prop_driver="intel"
			if echo $vga_pci | grep "i740"; then
				prop_driver="i740"
			fi
			if echo $vga_pci | grep "i128"; then
				prop_driver="i128"
			fi
			if echo $vga_driver | grep "mach"; then
				prop_driver="mach64"
			fi ;;
		[1106)
			prop_driver="openchrome"
			if echo $vga_pci | grep -i "Savage"; then
				prop_driver="savage"
			fi
			#if echo $vga_pci | grep -i "s3"; then
			#	prop_driver="via"
			#fi
			if echo $vga_pci | grep -i "virge"; then
				prop_driver="virge"
			fi ;;
		*)
			prop_driver="fbdev" ;;
	esac

	### Install driver based on the type of video card used
	#Install nouveau driver to avoid reboot if nvidia
	case $prop_driver in
		nouveau)
			apt-get -yf install xserver-xorg-nouveau-video$LTS_HES ;;
		radeon)
			apt-get -yf install xserver-xorg-video-radeon$LTS_HES ;;
		r128)
			apt-get -yf install xserver-xorg-video-r128$LTS_HES ;;
		mach64)
			apt-get -yf install xserver-xorg-video-mach64$LTS_HES ;;
		intel)
			apt-get -yf install xserver-xorg-video-intel$LTS_HES ;;
		i128)
			apt-get -yf install xserver-xorg-video-i128$LTS_HES ;;
		i740)
			apt-get -yf install xserver-xorg-video-i740$LTS_HES ;;
		openchrome)
			apt-get -yf install xserver-xorg-video-openchrome$LTS_HES ;;
	esac
	if [[ "$chip_man" == "Intel" ]]; then
		if ping -c 1 google.com; then
			apt-get -yf install libva-driver-i965
		fi
	fi
	VideoDriver="$prop_driver"
	export Best_Video_Driver="$prop_driver"
}

InitialBootPrep () {
	### This is a Live DVD Fn.
	:

	# Remove deprecated options from /etc/default/grub
	#sed -i '/GRUB_HIDDEN_/d' /etc/default/grub
	#/usr/sbin/update-grub
}

PackageCleanUp () {
	### This is a Live DVD Fn.
	### This is i386 ONLY!!!

	# Remove all but the latest package
	thedir="${LOCAL_REPO_BASE}"
	X=$(dpkg -l|grep "^ii"|awk '{print $2,$3}')
	odd="1"
	for var in $X ; do
		if [[ "$odd" -eq "1" ]]; then
			package="$var"
			odd="0"
		else
			version="$var"
			odd="1"
			all="$package"
			all+="_*"
			latest="${thedir}/${package}"
			latest+="_$version"
			latest+="_i386.deb"
			Alls=$(find "$thedir" -iname "$all")
			for each in $Alls ; do
				if [[ "$each" != "$latest" ]]; then
					rm "$each"
				fi
			done
		fi
	done > /dev/null
}

TempEMIFix () {
	# Placeholder fn.  This is done elsewhere if appropriate
	:
}

SetupAptSources () {
	ConfigSources	# install-core.sh
}


return 0

###########################################################
###########################################################
### Deprecated Functions
###########################################################
###########################################################





#!/bin/bash

if [[ -n "$HEADER_install_md" ]]; then
	return 0
fi
HEADER_install_md=included

# include all the common install helpers
. /usr/pluto/install/install-common.sh

[[ -e /usr/pluto/bin/Config_Ops.sh ]] && . /usr/pluto/bin/Config_Ops.sh
[[ -e /usr/pluto/bin/SQL_Ops.sh ]] && . /usr/pluto/bin/SQL_Ops.sh
[[ -e /usr/pluto/bin/Utils.sh ]] && . /usr/pluto/bin/Utils.sh

###########################################################
### Setup global variables
###########################################################

FSTAB_FILE="/etc/fstab"
DEVID_FILE="/etc/Disked_DeviceID"

#INSTALL_KUBUNTU_DESKTOP="yes"
INSTALL_KUBUNTU_DESKTOP="no"

# Get the Core's IP Address using the locator
CORE_IP=$(/usr/pluto/install/core-locator)

###########################################################
### Config setup fns.
###########################################################

MD_Setup_Fstab() {
	# Hmm, let's see if the mounts are here, if not add them
	check=$(grep "${CORE_IP}" "${FSTAB_FILE}" || :)
	if [ -z "$check" ] ; then
		cat <<-EOF >> "${FSTAB_FILE}"
			${CORE_IP}:/usr/pluto/var/		/usr/pluto/var/		nfs4 retrans=10,timeo=50 1 1
			${CORE_IP}:/usr/pluto/orbiter		/usr/pluto/orbiter	nfs4 retrans=10,timeo=50 1 1
			${CORE_IP}:/usr/pluto/keys		/usr/pluto/keys		nfs4 retrans=10,timeo=50 1 1
			${CORE_IP}:/usr/pluto/deb-cache		/usr/pluto/deb-cache    nfs4 retrans=10,timeo=50 1 1
			${CORE_IP}:/var/spool/asterisk		/var/spool/asterisk     nfs4 retrans=10,timeo=50 1 1
			${CORE_IP}:/home			/home			nfs4 retrans=10,timeo=50 1 1
			${CORE_IP}:/home/cameras		/home/cameras		nfs4 retrans=10,timeo=50 1 1
			EOF
	fi
	mkdir -p /usr/pluto/var/
	mkdir -p /usr/pluto/orbiter
	mkdir -p /usr/pluto/keys
	mkdir -p /usr/pluto/deb-cache
	mkdir -p /var/spool/asterisk
	mkdir -p /home/cameras
	mount -a || :
}

MD_Setup_Plutoconf() {
	. /usr/pluto/bin/Config_Ops.sh

	# get PK_Device from "/etc/Disked_DeviceID", created by interactor
	DEVICE=$(cat "$DEVID_FILE")
	[ -n "$PK_Device" ] || ConfSet "PK_Device" "$DEVICE"

	# TODO: start_interactor already did this and put it in the DB
	# TODO: get the data from the DB instead?
	# get PK_Distro from OS
	case "$TARGET_RELEASE" in
		precise)
			distro=$DEVICEDATA_DISTRO_Ubuntu_Precise_CONST 	;;
		trusty)
			distro=$DEVICEDATA_DISTRO_Ubuntu_Trusty_CONST 	;;
		wheezy)
			distro=$DEVICEDATA_DISTRO_Raspbian_Wheezy_CONST ;;
		jessie)
			distro=$DEVICEDATA_DISTRO_Raspbian_Jessie_CONST ;;
	esac
	[ -n "$PK_Distro" ] || [ -n "$distro" ] && ConfSet "PK_Distro" "$distro"

	[ -n "$MySqlHost" ] || ConfSet "MySqlHost" "${CORE_IP}"
	[ -n "$MySqlUser" ] || ConfSet "MySqlUser" "root"
	[ -n "$MySqlPassword" ] || ConfSet "MySqlPassword" ""
	[ -n "$MySqlDBName" ] || ConfSet "MySqlDBName" "pluto_main"
	[ -n "$DCERouter" ] || ConfSet "DCERouter" "${CORE_IP}"
	[ -n "$MySqlPort" ] || ConfSet "MySqlPort" "3306"
	[ -n "$DCERouterPort" ] || ConfSet "DCERouterPort" "3450"
	[ -n "$AutostartCore" ] || ConfSet "AutostartCore" "0"
	[ -n "$AutostartMedia" ] || ConfSet "AutostartMedia" "1"
	[ -n "$AVWizardDone" ] || ConfSet "AVWizardDone" "0"
}

###########################################################
### Setup Functions - General functions
###########################################################

MD_Find_Core () {
	# TODO: Use service discovery to find the Core's IP address
	:
}

MD_System_Level_Prep () {
	ConfigSources	# install-common.sh

	## Setup initial ssh access
	StatsMessage "Setting up SSH"
	[[ -f /usr/pluto/keys/id_dsa_pluto.pub ]] && mkdir -p /root/.ssh && cat /usr/pluto/keys/id_dsa_pluto.pub >> /root/.ssh/authorized_keys
}

MD_Seamless_Compatability () {
	: # no-op
}

MD_Preseed () {
	PreSeed_DebConf	# install-common.sh
}

MD_Update () {
	StatsMessage "Setting up apt gpg keys"
	gpgUpdate	# install-common.sh

	apt-get -f -y install

	AptDistUpgrade	# install-common.sh
}

MD_Install_Kernel () {
	StatsMessage "Installing kernel headers"

	# TODO: get as much of this from database as possible
	# run any device specific firstboot add-on kernel config here
	ret=""
	for f in /usr/pluto/install/firstboot_lmce_* ; do
		StatsMessage "Running device specific script: $f _kernel - Begin"
		. "$f" || :
		$(basename "$f")_kernel || :
		ret="0"
		StatsMessage "Running device specific script: $f _kernel - End"
	done

	# Default kernel installation is ubuntu based, if the above is not run
	if [[ "$ret" != "0" ]] ; then
		StatsMessage "Setting up Ubuntu HardWare Enablement Stack"
		. /usr/pluto/bin/Config_Ops.sh
		ConfSet "LTS_HES" "$TARGET_KVER_LTS_HES"

		StatsMessage "Installing Ubuntu kernel"
		apt-get -f -y install --install-recommends linux-generic"$TARGET_KVER_LTS_HES" linux-image-generic"$TARGET_KVER_LTS_HES"
		VerifyExitCode "Install linux kernel package failed"

		StatsMessage "Installing Ubuntu kernel headers"
		#Install headers and run depmod for the seamless integraton function, ensure no errors exist
		apt-get -f -y --no-install-recommends install linux-headers-generic"$TARGET_KVER_LTS_HES"
		VerifyExitCode "Install linux headers package failed"
	fi

	#StatsMessage "Installing firmware"
	#apt-get -f -y install --no-install-recommends linux-firmware || :
	#VerifyExitCode "Install linux firmware failed" || :

	StatsMessage "Running depmod"
	TARGET_KVER=$(ls -vd /lib/modules/[0-9]* | sed 's/.*\///g' | tail -1)
	depmod -v "$TARGET_KVER"
	VerifyExitCode "depmod failed for $TARGET_KVER"
}

MD_Install_Packages () {
	StatsMessage "Installing packages to MD"

	StatsMessage "Setting locales"
	# FIXME: locales are already generated, trigger regen?
	echo "en_US.UTF-8 UTF-8" >/etc/locale.gen

	StatsMessage "Installing X.Org"
	#Install X prior to linuxmce to get lts_hwe pkgs.

	case "$TARGET_RELEASE" in
		"precise")	# 1204
			apt-get -f -y --install-recommends install \
				xserver-xorg"$TARGET_KVER_LTS_HES" \
				xserver-xorg-video-all"$TARGET_KVER_LTS_HES" \
				libgl1-mesa-glx"$TARGET_KVER_LTS_HES"
				VerifyExitCode "Installing X.Org failed"
			;;
		"trusty")	# 1404
			apt-get -f -y --install-recommends install \
				xserver-xorg-core-"$TARGET_KVER_LTS_HES" \
				xserver-xorg"$TARGET_KVER_LTS_HES" \
				xserver-xorg-video-all"$TARGET_KVER_LTS_HES" \
				xserver-xorg-input-all"$TARGET_KVER_LTS_HES" \
				libwayland-egl1-mesa"$TARGET_KVER_LTS_HES"
				VerifyExitCode "Installing X.Org failed"
			;;
		*)	# *
			apt-get -f -y --install-recommends install \
				xserver-xorg \
				xserver-xorg-video-all
				VerifyExitCode "Installing X.Org failed"
			;;
	esac

	StatsMessage "Installing primary MD packages"
	apt-get -f -y --no-install-recommends install lmce-md-meta nfs-common openssh-server pastebinit locales
	VerifyExitCode "Installing lmce-md-meta failed"

	if [[ "$INSTALL_KUBUNTU_DESKTOP" != "no" ]]; then
		StatsMessage "Installing kubuntu desktop packages"
		apt-get -f -y --no-install-recommends install kubuntu-desktop
		VerifyExitCode "kubuntu-desktop"
	fi
}

MD_Config_MySQL_Client () {
	StatsMessage "Setting up mysql client - server hostname"
	# Make sure, the root user is connecting to DCEROUTER for any MySQL connection
	cat <<-EOF > /root/.my.cnf
		[client]
		host = dcerouter
		EOF
}

MD_Populate_Debcache () {
	StatsMessage "Creating deb-cache dir"
	CreateBasePackagesFiles		# install-common.sh
	#UpdateDebCache "$DEB_CACHE"	# install-common.sh
}

MD_Cleanup () {
	StatsMessage "Cleaning up from package installations..."
	#Copy the orbiter activation command to the MD's desktop
	mkdir -p /root/Desktop
	cp -r /etc/skel/Desktop/* /root/Desktop

	#Remove the xorg file(s) from installation, need to start with a fresh slate
	rm -f /etc/X11/xorg.conf*

	#Clean up apt from the installs
	apt-get -y clean
	VerifyExitCode "APT Clean"

	#Create a list of installed packages
	#COLUMNS=1024 dpkg -l | awk '/^ii/ {print $2}' >/tmp/pkglist-diskless.txt # used for deb-cache cleanup in the builder
}


return 0

###########################################################
###########################################################
### Deprecated Functions
###########################################################
###########################################################



##########################################################################################################
##########################################################################################################
##########################################################################################################
##########################################################################################################
##########################################################################################################
##########################################################################################################


dontrun() {
#### this is the generic MD firstrun file
	if [ ! -f "$DEVID_FILE" ]; then
		echo "ERR: interactor has not yet created '$DEVID_FILE'."
		return 10
	fi

	#TODO get as much of this from database as possible
	# run any device specific firstboot add-on scripts here
	for f in /usr/pluto/install/firstboot_lmce_* ; do
		StatsMessage "Running device specific script: $f _preinst - Begin"
		. "$f" || :
		$(basename "$f")_preinst || :
		StatsMessage "Running device specific script: $f _preinst - End"
	done

	MD_Find_Core
MD_Config_MySQL_Client
	MD_System_Level_Prep
	#MD_Seamless_Compatability
	#MD_Preseed
	MD_Update
	MD_Setup_Fstab
	MD_Setup_Plutoconf
	MD_Install_Kernel
	MD_Install_Packages
	Disable_DisplayManager
	Disable_NetworkManager
	MD_Populate_Debcache
	MD_Cleanup

	# run any device specific firstboot add-on scripts here
	for f in /usr/pluto/install/firstboot_lmce_* ; do
		StatsMessage "Running device specific script: $f _postinst - Begin"
		. "$f" || :
		$(basename "$f")_postinst || :
		StatsMessage "Running device specific script: $f _postinst - End"
	done

	StatsMessage "Setting firstboot = false"
	ConfSet "FirstBoot" "false"
	sync

	StatsMessage "Rebooting in 5 seconds"
	sleep 1
	StatsMessage "Rebooting in 4 seconds"
	sleep 1
	StatsMessage "Rebooting in 3 seconds"
	sleep 1
	StatsMessage "Rebooting in 2 seconds"
	sleep 1
	StatsMessage "Rebooting in 1 seconds"
	sleep 1
	StatsMessage "Rebooting"
	reboot
	return 0
}
