#ifndef __Define_CHANNELGROUPS_H__
#define __Define_CHANNELGROUPS_H__


#define CHANNELGROUPS_TABLE "CHANNELGROUPS"
#define CHANNELGROUPS_ID_FIELD "Id"
#define CHANNELGROUPS_ID_TABLE_FIELD "CHANNELGROUPS.Id"
#define CHANNELGROUPS_NAME_FIELD "Name"
#define CHANNELGROUPS_NAME_TABLE_FIELD "CHANNELGROUPS.Name"
#define CHANNELGROUPS_COUNTER_FIELD "Counter"
#define CHANNELGROUPS_COUNTER_TABLE_FIELD "CHANNELGROUPS.Counter"


#endif

