#ifndef __Define_MUSIC_H__
#define __Define_MUSIC_H__


#define MUSIC_TABLE "MUSIC"
#define MUSIC_ID_FIELD "Id"
#define MUSIC_ID_TABLE_FIELD "MUSIC.Id"
#define MUSIC_FILE_FIELD "FILE"
#define MUSIC_FILE_TABLE_FIELD "MUSIC.FILE"
#define MUSIC_ARTIST_FIELD "ARTIST"
#define MUSIC_ARTIST_TABLE_FIELD "MUSIC.ARTIST"
#define MUSIC_ALBUM_FIELD "ALBUM"
#define MUSIC_ALBUM_TABLE_FIELD "MUSIC.ALBUM"
#define MUSIC_TITLE_FIELD "TITLE"
#define MUSIC_TITLE_TABLE_FIELD "MUSIC.TITLE"
#define MUSIC_COMMENT_FIELD "COMMENT"
#define MUSIC_COMMENT_TABLE_FIELD "MUSIC.COMMENT"
#define MUSIC_TRACKNUM_FIELD "TRACKNUM"
#define MUSIC_TRACKNUM_TABLE_FIELD "MUSIC.TRACKNUM"
#define MUSIC_YEAR_FIELD "YEAR"
#define MUSIC_YEAR_TABLE_FIELD "MUSIC.YEAR"
#define MUSIC_GENRE_FIELD "GENRE"
#define MUSIC_GENRE_TABLE_FIELD "MUSIC.GENRE"
#define MUSIC_BITRATE_FIELD "BITRATE"
#define MUSIC_BITRATE_TABLE_FIELD "MUSIC.BITRATE"
#define MUSIC_FREQUENCY_FIELD "FREQUENCY"
#define MUSIC_FREQUENCY_TABLE_FIELD "MUSIC.FREQUENCY"
#define MUSIC_SECS_FIELD "SECS"
#define MUSIC_SECS_TABLE_FIELD "MUSIC.SECS"


#endif

