#ifndef __Define_TIMERS_H__
#define __Define_TIMERS_H__


#define TIMERS_TABLE "TIMERS"
#define TIMERS_ID_FIELD "Id"
#define TIMERS_ID_TABLE_FIELD "TIMERS.Id"
#define TIMERS_STATUS_FIELD "Status"
#define TIMERS_STATUS_TABLE_FIELD "TIMERS.Status"
#define TIMERS_CHANNELID_FIELD "ChannelID"
#define TIMERS_CHANNELID_TABLE_FIELD "TIMERS.ChannelID"
#define TIMERS_DAY_FIELD "Day"
#define TIMERS_DAY_TABLE_FIELD "TIMERS.Day"
#define TIMERS_START_FIELD "Start"
#define TIMERS_START_TABLE_FIELD "TIMERS.Start"
#define TIMERS_STOP_FIELD "Stop"
#define TIMERS_STOP_TABLE_FIELD "TIMERS.Stop"
#define TIMERS_PRIORITY_FIELD "Priority"
#define TIMERS_PRIORITY_TABLE_FIELD "TIMERS.Priority"
#define TIMERS_LIFETIME_FIELD "Lifetime"
#define TIMERS_LIFETIME_TABLE_FIELD "TIMERS.Lifetime"
#define TIMERS_FILE_FIELD "File"
#define TIMERS_FILE_TABLE_FIELD "TIMERS.File"
#define TIMERS_SUMMARY_FIELD "Summary"
#define TIMERS_SUMMARY_TABLE_FIELD "TIMERS.Summary"
#define TIMERS_NEXTSTARTTIME_FIELD "NextStartTime"
#define TIMERS_NEXTSTARTTIME_TABLE_FIELD "TIMERS.NextStartTime"
#define TIMERS_NEXTSTOPTIME_FIELD "NextStopTime"
#define TIMERS_NEXTSTOPTIME_TABLE_FIELD "TIMERS.NextStopTime"
#define TIMERS_COLLISION_FIELD "Collision"
#define TIMERS_COLLISION_TABLE_FIELD "TIMERS.Collision"
#define TIMERS_NEXTEPGID_FIELD "NextEpgId"
#define TIMERS_NEXTEPGID_TABLE_FIELD "TIMERS.NextEpgId"
#define TIMERS_AUTOTIMERID_FIELD "AutotimerId"
#define TIMERS_AUTOTIMERID_TABLE_FIELD "TIMERS.AutotimerId"
#define TIMERS_ADDTIME_FIELD "addtime"
#define TIMERS_ADDTIME_TABLE_FIELD "TIMERS.addtime"
#define TIMERS_CHECKED_FIELD "Checked"
#define TIMERS_CHECKED_TABLE_FIELD "TIMERS.Checked"


#endif

