#ifndef __Define_RECORDS_H__
#define __Define_RECORDS_H__


#define RECORDS_TABLE "RECORDS"
#define RECORDS_EVENTID_FIELD "eventid"
#define RECORDS_EVENTID_TABLE_FIELD "RECORDS.eventid"
#define RECORDS_RECORDID_FIELD "RecordId"
#define RECORDS_RECORDID_TABLE_FIELD "RECORDS.RecordId"
#define RECORDS_PATH_FIELD "Path"
#define RECORDS_PATH_TABLE_FIELD "RECORDS.Path"
#define RECORDS_PRIO_FIELD "Prio"
#define RECORDS_PRIO_TABLE_FIELD "RECORDS.Prio"
#define RECORDS_LIFETIME_FIELD "Lifetime"
#define RECORDS_LIFETIME_TABLE_FIELD "RECORDS.Lifetime"
#define RECORDS_STATE_FIELD "State"
#define RECORDS_STATE_TABLE_FIELD "RECORDS.State"
#define RECORDS_MARKS_FIELD "Marks"
#define RECORDS_MARKS_TABLE_FIELD "RECORDS.Marks"
#define RECORDS_TYPE_FIELD "Type"
#define RECORDS_TYPE_TABLE_FIELD "RECORDS.Type"
#define RECORDS_ADDTIME_FIELD "addtime"
#define RECORDS_ADDTIME_TABLE_FIELD "RECORDS.addtime"


#endif

