#ifndef __Define_CHANNELS_H__
#define __Define_CHANNELS_H__


#define CHANNELS_TABLE "CHANNELS"
#define CHANNELS_ID_FIELD "Id"
#define CHANNELS_ID_TABLE_FIELD "CHANNELS.Id"
#define CHANNELS_NAME_FIELD "Name"
#define CHANNELS_NAME_TABLE_FIELD "CHANNELS.Name"
#define CHANNELS_FREQUENCY_FIELD "Frequency"
#define CHANNELS_FREQUENCY_TABLE_FIELD "CHANNELS.Frequency"
#define CHANNELS_PARAMETERS_FIELD "Parameters"
#define CHANNELS_PARAMETERS_TABLE_FIELD "CHANNELS.Parameters"
#define CHANNELS_SOURCE_FIELD "Source"
#define CHANNELS_SOURCE_TABLE_FIELD "CHANNELS.Source"
#define CHANNELS_SRATE_FIELD "Srate"
#define CHANNELS_SRATE_TABLE_FIELD "CHANNELS.Srate"
#define CHANNELS_VPID_FIELD "VPID"
#define CHANNELS_VPID_TABLE_FIELD "CHANNELS.VPID"
#define CHANNELS_APID_FIELD "APID"
#define CHANNELS_APID_TABLE_FIELD "CHANNELS.APID"
#define CHANNELS_TPID_FIELD "TPID"
#define CHANNELS_TPID_TABLE_FIELD "CHANNELS.TPID"
#define CHANNELS_CA_FIELD "CA"
#define CHANNELS_CA_TABLE_FIELD "CHANNELS.CA"
#define CHANNELS_SID_FIELD "SID"
#define CHANNELS_SID_TABLE_FIELD "CHANNELS.SID"
#define CHANNELS_NID_FIELD "NID"
#define CHANNELS_NID_TABLE_FIELD "CHANNELS.NID"
#define CHANNELS_TID_FIELD "TID"
#define CHANNELS_TID_TABLE_FIELD "CHANNELS.TID"
#define CHANNELS_RID_FIELD "RID"
#define CHANNELS_RID_TABLE_FIELD "CHANNELS.RID"
#define CHANNELS_GRP_FIELD "GRP"
#define CHANNELS_GRP_TABLE_FIELD "CHANNELS.GRP"
#define CHANNELS_POS_FIELD "POS"
#define CHANNELS_POS_TABLE_FIELD "CHANNELS.POS"


#endif

