#ifndef __Define_CHRONICLE_H__
#define __Define_CHRONICLE_H__


#define CHRONICLE_TABLE "CHRONICLE"
#define CHRONICLE_ID_FIELD "id"
#define CHRONICLE_ID_TABLE_FIELD "CHRONICLE.id"
#define CHRONICLE_HASH_FIELD "hash"
#define CHRONICLE_HASH_TABLE_FIELD "CHRONICLE.hash"
#define CHRONICLE_TITLE_FIELD "title"
#define CHRONICLE_TITLE_TABLE_FIELD "CHRONICLE.title"
#define CHRONICLE_CHANNEL_ID_FIELD "channel_id"
#define CHRONICLE_CHANNEL_ID_TABLE_FIELD "CHRONICLE.channel_id"
#define CHRONICLE_STARTTIME_FIELD "starttime"
#define CHRONICLE_STARTTIME_TABLE_FIELD "CHRONICLE.starttime"
#define CHRONICLE_DURATION_FIELD "duration"
#define CHRONICLE_DURATION_TABLE_FIELD "CHRONICLE.duration"


#endif

