opt/linphone-1.3.5/bin/linphone
opt/linphone-1.3.5/lib/bonobo/servers/GNOME_LinphoneApplet.server
opt/linphone-1.3.5/libexec/linphone_applet				/opt/linphone-1.3.5/lib/gnome-applets
opt/linphone-1.3.5/share/man/man1/linphone.1
opt/linphone-1.3.5/share/pixmaps/linphone
opt/linphone-1.3.5/share/applications/linphone.desktop
opt/linphone-1.3.5/share/gnome-2.0/ui/GNOME_LinphoneApplet.xml
opt/linphone-1.3.5/share/gnome/help/linphone
opt/linphone-1.3.5/share/doc/linphone/html
