#ifndef __Define_Game_GameSystem_H__
#define __Define_Game_GameSystem_H__


#define GAME_GAMESYSTEM_TABLE "Game_GameSystem"
#define GAME_GAMESYSTEM_PK_GAME_GAMESYSTEM_FIELD "PK_Game_GameSystem"
#define GAME_GAMESYSTEM_PK_GAME_GAMESYSTEM_TABLE_FIELD "Game_GameSystem.PK_Game_GameSystem"
#define GAME_GAMESYSTEM_FK_GAME_FIELD "FK_Game"
#define GAME_GAMESYSTEM_FK_GAME_TABLE_FIELD "Game_GameSystem.FK_Game"
#define GAME_GAMESYSTEM_FK_GAMESYSTEM_FIELD "FK_GameSystem"
#define GAME_GAMESYSTEM_FK_GAMESYSTEM_TABLE_FIELD "Game_GameSystem.FK_GameSystem"
#define GAME_GAMESYSTEM_FK_MANUFACTURER_FIELD "FK_Manufacturer"
#define GAME_GAMESYSTEM_FK_MANUFACTURER_TABLE_FIELD "Game_GameSystem.FK_Manufacturer"
#define GAME_GAMESYSTEM_FK_GENRE_FIELD "FK_Genre"
#define GAME_GAMESYSTEM_FK_GENRE_TABLE_FIELD "Game_GameSystem.FK_Genre"
#define GAME_GAMESYSTEM_NAME_FIELD "Name"
#define GAME_GAMESYSTEM_NAME_TABLE_FIELD "Game_GameSystem.Name"
#define GAME_GAMESYSTEM_SUBTITLE_FIELD "Subtitle"
#define GAME_GAMESYSTEM_SUBTITLE_TABLE_FIELD "Game_GameSystem.Subtitle"
#define GAME_GAMESYSTEM_YEAR_FIELD "Year"
#define GAME_GAMESYSTEM_YEAR_TABLE_FIELD "Game_GameSystem.Year"


#endif

