#ifndef __Define_Game_GameSystem_Rom_Configuration_H__
#define __Define_Game_GameSystem_Rom_Configuration_H__


#define GAME_GAMESYSTEM_ROM_CONFIGURATION_TABLE "Game_GameSystem_Rom_Configuration"
#define GAME_GAMESYSTEM_ROM_CONFIGURATION_PK_GAME_GAMESYSTEM_ROM_CONFIGURATION_FIELD "PK_Game_GameSystem_Rom_Configuration"
#define GAME_GAMESYSTEM_ROM_CONFIGURATION_PK_GAME_GAMESYSTEM_ROM_CONFIGURATION_TABLE_FIELD "Game_GameSystem_Rom_Configuration.PK_Game_GameSystem_Rom_Configuration"
#define GAME_GAMESYSTEM_ROM_CONFIGURATION_FK_GAME_GAMESYSTEM_ROM_FIELD "FK_Game_GameSystem_Rom"
#define GAME_GAMESYSTEM_ROM_CONFIGURATION_FK_GAME_GAMESYSTEM_ROM_TABLE_FIELD "Game_GameSystem_Rom_Configuration.FK_Game_GameSystem_Rom"
#define GAME_GAMESYSTEM_ROM_CONFIGURATION_FK_CONFIGURATION_FIELD "FK_Configuration"
#define GAME_GAMESYSTEM_ROM_CONFIGURATION_FK_CONFIGURATION_TABLE_FIELD "Game_GameSystem_Rom_Configuration.FK_Configuration"


#endif

