#ifndef __Define_RomAttributeType_H__
#define __Define_RomAttributeType_H__

#define ROMATTRIBUTETYPE_title_CONST 1
#define ROMATTRIBUTETYPE_year_CONST 2
#define ROMATTRIBUTETYPE_manufacturer_CONST 3
#define ROMATTRIBUTETYPE_genre_CONST 4
#define ROMATTRIBUTETYPE_system_CONST 5
#define ROMATTRIBUTETYPE_subtitle_CONST 6

#define ROMATTRIBUTETYPE_TABLE "RomAttributeType"
#define ROMATTRIBUTETYPE_PK_ROMATTRIBUTETYPE_FIELD "PK_RomAttributeType"
#define ROMATTRIBUTETYPE_PK_ROMATTRIBUTETYPE_TABLE_FIELD "RomAttributeType.PK_RomAttributeType"
#define ROMATTRIBUTETYPE_DEFINE_FIELD "Define"
#define ROMATTRIBUTETYPE_DEFINE_TABLE_FIELD "RomAttributeType.Define"
#define ROMATTRIBUTETYPE_DESCRIPTION_FIELD "Description"
#define ROMATTRIBUTETYPE_DESCRIPTION_TABLE_FIELD "RomAttributeType.Description"
#define ROMATTRIBUTETYPE_PICPRIORITY_FIELD "PicPriority"
#define ROMATTRIBUTETYPE_PICPRIORITY_TABLE_FIELD "RomAttributeType.PicPriority"
#define ROMATTRIBUTETYPE_PSC_ID_FIELD "psc_id"
#define ROMATTRIBUTETYPE_PSC_ID_TABLE_FIELD "RomAttributeType.psc_id"
#define ROMATTRIBUTETYPE_PSC_BATCH_FIELD "psc_batch"
#define ROMATTRIBUTETYPE_PSC_BATCH_TABLE_FIELD "RomAttributeType.psc_batch"
#define ROMATTRIBUTETYPE_PSC_USER_FIELD "psc_user"
#define ROMATTRIBUTETYPE_PSC_USER_TABLE_FIELD "RomAttributeType.psc_user"
#define ROMATTRIBUTETYPE_PSC_FROZEN_FIELD "psc_frozen"
#define ROMATTRIBUTETYPE_PSC_FROZEN_TABLE_FIELD "RomAttributeType.psc_frozen"
#define ROMATTRIBUTETYPE_PSC_MOD_FIELD "psc_mod"
#define ROMATTRIBUTETYPE_PSC_MOD_TABLE_FIELD "RomAttributeType.psc_mod"
#define ROMATTRIBUTETYPE_PSC_RESTRICT_FIELD "psc_restrict"
#define ROMATTRIBUTETYPE_PSC_RESTRICT_TABLE_FIELD "RomAttributeType.psc_restrict"


#endif

