#!/bin/bash

trap 'rm -f /etc/rc2.d/S90firstboot' EXIT


## Reconfigure netowkring
export NPflagReconfNetwork=yes
/usr/pluto/bin/Network_Setup.sh
/etc/init.d/networking restart
/usr/pluto/bin/DHCP_config.sh
/etc/init.d/networking restart
/usr/pluto/bin/Network_Firewall.sh
/usr/pluto/bin/ConfirmInstallation.sh
/usr/pluto/bin/Timezone_Detect.sh

## Create new set of ssh keys
rm -f /etc/ssh/ssh_host_*
dpkg-reconfigure -pcritical openssh-server

## Install video-wizard-video
apt-get -y -f install video-wizard-videos

## Install nvidia-glx if needed
if lshwd | grep -qi 'VGA .* (nv)'; then
        apt-get -y -f install pluto-nvidia-video-drivers
fi

echo "
	REPLACE INTO Device_DeviceData(IK_DeviceData, FK_Device, FK_DeviceData)
	VALUE('eth1,dhcp|eth0,192.168.80.1,255.255.255.0', 1, 32)
" | mysql pluto_main
