#!/bin/bash

trap 'rm -f /etc/rc2.d/S90firstboot' EXIT


## Reconfigure netowkring
export NPflagReconfNetwork=yes
/usr/pluto/bin/Network_Setup.sh

## Create new set of ssh keys
rm -f /etc/ssh/ssh_host_*
dpkg-reconfigure -pcritical openssh-server

## Install video-wizard-video
apt-get -y -f install video-wizard-videos
