#!/bin/bash

case "$1" in
	start)
		/bin/bash /usr/bin/lite-installer-via.sh
	;;
	stop)
	;;
	reload|force-reload)
	;;
	restart)
	;;
	*)
		echo "Usage: $0 {start|stop|reload|force-reload|restart}"
		exit 1
	;;
esac
