#!/bin/make

none:


clean:


install:
	find . -iname "*.mp3" -exec install -m644 -D {} $(DESTDIR)/usr/pluto/orbiter/skins/{} \;
	find . -iname "*.wav" -exec install -m644 -D {} $(DESTDIR)/usr/pluto/orbiter/skins/{} \;
	find . -iname "*.ac3" -exec install -m644 -D {} $(DESTDIR)/usr/pluto/orbiter/skins/{} \;
