#!/bin/make

none:


clean:


install:
	find . -iname "*.mp3" -exec install -m644 -D {} $(DESTDIR)/home/public/data/avwizard-sounds/{} \;
	find . -iname "*.wav" -exec install -m644 -D {} $(DESTDIR)/home/public/data/avwizard-sounds/{} \;
	find . -iname "*.ac3" -exec install -m644 -D {} $(DESTDIR)/home/public/data/avwizard-sounds/{} \;
