// Do NOT edit this file, it is automatically generated prior to build.
#ifndef VERSION
#define VERSION "2.0.0.46.15082731279"
#endif

#ifndef LMCE_version_h
#define LMCE_version_h
// In source files stored in archives and packages, these 2 lines will have the release version (build)
// and the svn revision as a global variable that can be inspected within a core dump
#ifdef EXTERN_REVISION_DATE
extern const char *g_szCompile_Date;
extern int g_SvnRevision;
#else
const char *g_szCompile_Date="Thu Aug 27 00:54:38 UTC 2015";
int g_SvnRevision=31279;
#endif
#endif
