Document: lmce-slimserver-plugin
Title: Debian lmce-slimserver-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-slimserver-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-slimserver-plugin/lmce-slimserver-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-slimserver-plugin/lmce-slimserver-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-slimserver-plugin/lmce-slimserver-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-slimserver-plugin/html/index.html
Files: /usr/share/doc/lmce-slimserver-plugin/html/*.html
