.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LSHWD SECTION "January  6, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lshwd \- lists hardware devices and their approp modules.
.SH SYNOPSIS
.B lshwd
.RI [OPTIONS] 
.br
.SH DESCRIPTION
Lists hardware devices and their approp modules. currently supports pci, 
usb, pcmcia, and firewire devices. Uses pcitable & usbtable files (can
be located at same directory or \fI/usr/share/hwdata\fP) for displaying extended
description and module names, module names are then parsed for generic names
and changes accordingly.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBlshwd\fP tries to mimic the lsxxx tools family (lspci, lsusb) output when no
commandline is specified. using \fB-cc\fP option provides a more "user-friendly"
output.
.TP
.B \-a
 auto-modprobe
.TP
.B \-c
 categorized output
.TP
.B \-cc
 colorized && categorized output
.TP
.B \-d
 display default device description
.TP
.B \-id
 display hardware id
.TP
.B \-m
 machine readable format
.TP
.B \-n
 no duplicates
.TP
.B \-os
 output X info to /tmp/xinfo (only gfx card section)
.TP
.B \-s
 probe using sysfs (EXPERIMENTAL)

.SH AUTHOR
lshwd was written by Elia Yehuda <z4ziggy@user-contributions.org>
.PP
This manual page was written by Razvan Gavril <razvan.g@plutohome.com>,
for the Pluto project (but may be used by others).
