Document: lmce-generic-pc-workstation
Title: Debian lmce-generic-pc-workstation Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-generic-pc-workstation is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-generic-pc-workstation/lmce-generic-pc-workstation.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-generic-pc-workstation/lmce-generic-pc-workstation.ps.gz

Format: text
Files: /usr/share/doc/lmce-generic-pc-workstation/lmce-generic-pc-workstation.text.gz

Format: HTML
Index: /usr/share/doc/lmce-generic-pc-workstation/html/index.html
Files: /usr/share/doc/lmce-generic-pc-workstation/html/*.html
