#ifndef QTMEDIACALLBACKS_GLOBAL_H
#define QTMEDIACALLBACKS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTMEDIACALLBACKS_LIBRARY)
#  define QTMEDIACALLBACKSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTMEDIACALLBACKSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMEDIACALLBACKS_GLOBAL_H
