Document: chan-sccp
Title: Debian chan-sccp Manual
Author: <insert document author here>
Abstract: This manual describes what chan-sccp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/chan-sccp/chan-sccp.sgml.gz

Format: postscript
Files: /usr/share/doc/chan-sccp/chan-sccp.ps.gz

Format: text
Files: /usr/share/doc/chan-sccp/chan-sccp.text.gz

Format: HTML
Index: /usr/share/doc/chan-sccp/html/index.html
Files: /usr/share/doc/chan-sccp/html/*.html

  
