Document: lmce-airplay-plugin
Title: Debian lmce-airplay-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-airplay-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-airplay-plugin/lmce-airplay-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-airplay-plugin/lmce-airplay-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-airplay-plugin/lmce-airplay-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-airplay-plugin/html/index.html
Files: /usr/share/doc/lmce-airplay-plugin/html/*.html
