Document: lmce-shoutcast-plugin
Title: Debian lmce-shoutcast-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-shoutcast-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-shoutcast-plugin/lmce-shoutcast-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-shoutcast-plugin/lmce-shoutcast-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-shoutcast-plugin/lmce-shoutcast-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-shoutcast-plugin/html/index.html
Files: /usr/share/doc/lmce-shoutcast-plugin/html/*.html
