Document: lmce-datalogger-plugin
Title: Debian lmce-datalogger-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what lmce-datalogger-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmce-datalogger-plugin/lmce-datalogger-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lmce-datalogger-plugin/lmce-datalogger-plugin.ps.gz

Format: text
Files: /usr/share/doc/lmce-datalogger-plugin/lmce-datalogger-plugin.text.gz

Format: HTML
Index: /usr/share/doc/lmce-datalogger-plugin/html/index.html
Files: /usr/share/doc/lmce-datalogger-plugin/html/*.html
