Document: pluto-messagetrans
Title: Debian pluto-messagetrans Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-messagetrans is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-messagetrans/pluto-messagetrans.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-messagetrans/pluto-messagetrans.ps.gz

Format: text
Files: /usr/share/doc/pluto-messagetrans/pluto-messagetrans.text.gz

Format: HTML
Index: /usr/share/doc/pluto-messagetrans/html/index.html
Files: /usr/share/doc/pluto-messagetrans/html/*.html
