Document: pluto-qos
Title: Debian pluto-qos Manual
Author: <insert document author here>
Abstract: This manual describes what pluto-qos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pluto-qos/pluto-qos.sgml.gz

Format: postscript
Files: /usr/share/doc/pluto-qos/pluto-qos.ps.gz

Format: text
Files: /usr/share/doc/pluto-qos/pluto-qos.text.gz

Format: HTML
Index: /usr/share/doc/pluto-qos/html/index.html
Files: /usr/share/doc/pluto-qos/html/*.html
